### ISSUE TITLE
Bug: Documentation link for "Next version (Unreleased)" does not work.

### ISSUE THREAD

**Issue by hlevring** [pixijs/pixijs#10038]
### Current Behavior

The [documentation link](https://pixijs.download/release/docs) on this page https://pixijs.com/versions#latest for "Next version (Unreleased)" does not work. Fails with permission error.

### Expected Behavior

The documentation link should work.

### Steps to Reproduce

1. Goto https://pixijs.com/versions#latest

2. Press this link 
![image](https://github.com/pixijs/pixijs/assets/7360168/350d2c4a-bacc-4462-9e39-6e8671cfebba)

3. Results in the following error:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8M1TY8DWRSYTSXND</RequestId>
<HostId>qCe+1CY2lMz/8O5Mx2d16z3vBC0gw6K1C6aR8/VQDQ7rZivSlllil+NUXVjvZp3vJKqTscDlejs=</HostId>
</Error>

### Environment

- **`pixi.js` version**: *NOT APPLICABLE*
- **Browser & Version**: *Chrome 120 *
- **OS & Version**: *Windows 11*

**Comment by SuperSodaSea** [comment]
This issue should be transfered to [pixijs/pixijs.com](https://github.com/pixijs/pixijs.com).
