### ISSUE TITLE
Bug: 8.0.0-rc UniformBufferSystem does not work with esbuild

### ISSUE THREAD

**Issue by zjkmxy** [pixijs/pixijs#10036]
### Current Behavior

In `syncUniformGroup`, the generated `syncFunction` throws a ReferenceError exception due to name mangling.
Generated function looks like following:
```javascript
function anonymous(uv, data, offset) {

    var v = null;
    var v2 = null;
    var t = 0;
    var index = 0;
    var name = null;

name = "projectionMatrix";
offset += 0;
{const i=e[t].toArray(!0);r[s]=i[0],r[s+1]=i[1],r[s+2]=i[2],r[s+4]=i[3],r[s+5]=i[4],r[s+6]=i[5],r[s+8]=i[6],r[s+9]=i[7],r[s+10]=i[8]}
// <SNIP>
}
```

The reason I guess is

https://github.com/pixijs/pixijs/blob/4e5d82135131dd9dcd5dd4c6873866ba6283a237/src/rendering/renderers/shared/utils/parseFunctionBody.ts#L3

This parser does not work well with esbuild. 

### Expected Behavior

`uniformBufferParsers[mat3x3<f32>].code` should not be mangled.

### Steps to Reproduce

Create an application (using WebGL renderer) in ViteJS, `build` and `preview`.

[Code sandbox](https://codesandbox.io/p/devbox/pixijs-8rc-vite-s2d363?file=%2Fsrc%2Fmain.ts%3A30%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqvw3mg60006396gxlj22fjv%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqvw3mg50002396g17rwhsod%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqvw3mg60004396g78jol2pw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqvw3mg60005396g5cu45ps5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqvw3mg50002396g17rwhsod%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqvw3mg50001396g9umw1egc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqvwzjkw0002396g139u2hl2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A30%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A30%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqvw3mg50002396g17rwhsod%2522%252C%2522activeTabId%2522%253A%2522clqvwzjkw0002396g139u2hl2%2522%257D%252C%2522clqvw3mg60005396g5cu45ps5%2522%253A%257B%2522id%2522%253A%2522clqvw3mg60005396g5cu45ps5%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clqvw3mg60004396g78jol2pw%2522%253A%257B%2522id%2522%253A%2522clqvw3mg60004396g78jol2pw%2522%252C%2522activeTabId%2522%253A%2522clqvx4qgz0038396gdrzm1ugo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqvx4qgz0038396gdrzm1ugo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqvx4qjf0013efcva5v1fyj0%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

In the code sandbox, `yarn dev` (no bundler) works but `yarn build` followed by `yarn preview` does not work.

### Environment

- **`pixi.js` version**: *8.0.0-rc*
- **Bundler**: *vite@5.0.10*, *esbuild@0.19.11*

### Possible Solution

- Rewrite `parseFunctionBody` to make it work with esbuild.
- Write generated code in plain text, instead of `fn.toString()`.
- Ask all users to turn off mangling by setting `esbuild.minifyIdentifiers=false`.

**Comment by GoodBoyDigital** [comment]
thanks for sharing @zjkmxy  - this is next on my list!

**Comment by zjkmxy** [comment]
Thank you for your effort.
It works perfectly with GPU renderer. However, there is still some issue with the WebGL renderer:

https://github.com/pixijs/pixijs/blob/f67772edaf2196a30c369838cd96f59fe697e35f/src/rendering/renderers/gl/shader/program/uniformParsers.ts#L50-L57

This piece of code is mangled.

**Comment by GoodBoyDigital** [comment]
thanks! will look into this!
