### ISSUE TITLE
Feature Request: @pixi/events addEventListener does not obey signal option

### ISSUE THREAD

**Issue by jmcclell** [pixijs/pixijs#10043]
### Current Behavior

When using an `AbortController` to pass a signal to the event package's `addEventListener` options object, the event continues to fire even after the `abort()` method is called on the controller.

### Expected Behavior

The event listener should be removed when the `abort()` method is called.

### Steps to Reproduce

Given an environment with `pixi.js` and `@pixi/events` available:

```
import * as PIXI from 'pixi.js';
import '@pixi/events';

var app = new PIXI.Application({
    width: window.innerWidth,
    height: window.innerHeight,
    backgroundColor: 0x2c3e50
});
document.body.appendChild(app.view);

PIXI.Assets.load('https://pixijs.io/examples/examples/assets/bunny.png')
            .then((img) => startup(img));

function startup(img)
{
    var bunny = new PIXI.Sprite(img);
    bunny.anchor.set(0.5);
    bunny.x = app.renderer.width / 2;
    bunny.y = app.renderer.height / 2;

    app.stage.addChild(bunny);

    // Event test case
    bunny.eventMode = 'static';
    const abort = new AbortController();
    var count = 0;

    bunny.addEventListener('click', (e) => {
      count = count + 1;
      console.log("Clicked", count, "times!");
      bunny.rotation += 10;
      if (count > 2) {
        abort.abort();
      }
    }, { signal: abort.signal });
}
```

After 3 clicks, the bunny should stop rotating on click. The event continues to fire, however.

### Environment

- **`pixi.js` version**: 7.3.3
- **Browser & Version**: Version 120.0.6099.129 (Official Build) (arm64)
- **OS & Version**: Mac Sonoma 14.1.2
- **Running Example**: Playground doesn't support importing events package :(

**Comment by bigtimebuddy** [comment]
Good catch. I added a PR to disable the `signal` property as it is not implemented. Would accept PRs to add this as a feature to events.

**Comment by jmcclell** [comment]
@bigtimebuddy I created PRs #10046 and #10047 to make this method more inline with the DOM implementation. Specifically, support for the `once` and `signal` options.
