### ISSUE TITLE
Bug: Graphics has something wrong with lineTo and fill

### ISSUE THREAD

**Issue by QQstar1** [pixijs/pixijs#10076]
### Current Behavior

I developed a free brush using Graphics, but there are some problems with the brush filling when drawing.
<img width="596" alt="image" src="https://github.com/pixijs/pixijs/assets/37185329/378b3cc3-2e72-4bd4-8683-4511090f3b6d">

### Expected Behavior

Generate correct picture

### Steps to Reproduce

https://jsfiddle.net/yn49otL8/

### Environment

- **`pixi.js` version**: *6.5.10*
- **Browser & Version**: * Chrome 120.0.6099.129*
- **OS & Version**: *macOS Monterey*
- **Running Example**: *https://jsfiddle.net/yn49otL8/*

**Comment by eXponenta** [comment]
By default Pixi use a simple tesselation algorithm that cannot be used for filling self-crossed shapes how you show.
There are a trick for solve this with changing a 

PIXI.graphicsUtils.FILL_COMMANDS.POLY instruction

https://github.com/pixijs/pixijs/blob/dev/packages/graphics/src/utils/index.ts#L34

You should replace a buildPoly onto your valid implementation.

**Comment by QQstar1** [comment]
> 默认情况下，Pixi 使用简单的曲面细分算法，该算法不能用于填充您显示的自交叉形状。 有一个技巧可以通过改变来解决这个问题
> 
> PIXI.graphicsUtils.FILL_COMMANDS.POLY 指令
> 
> https://github.com/pixijs/pixijs/blob/dev/packages/graphics/src/utils/index.ts#L34
> 
> 您应该将 buildPoly 替换为您的有效实现。

**Comment by QQstar1** [comment]
> By default Pixi use a simple tesselation algorithm that cannot be used for filling self-crossed shapes how you show. There are a trick for solve this with changing a
> 
> PIXI.graphicsUtils.FILL_COMMANDS.POLY instruction
> 
> https://github.com/pixijs/pixijs/blob/dev/packages/graphics/src/utils/index.ts#L34
> 
> You should replace a buildPoly onto your valid implementation.

I will try it soon,thanks
