### ISSUE TITLE
Bug: v8.0.0-rc.3 Graphics.regularPoly() stroke not closed

### ISSUE THREAD

**Issue by davidye** [pixijs/pixijs#10097]
### Current Behavior

See playground: https://www.pixiplayground.com/#/edit/yaYfpK8o9qZVFCVYmGmR3

### Expected Behavior

Stroke is closed

### Steps to Reproduce

See playground

### Environment

See playground

**Comment by Nikko-Adrian-Pacleb** [comment]
Hello I am new to contributions and I want to try contributing here but I don't know where to start (file wise).

**Comment by Nikko-Adrian-Pacleb** [comment]
I am looking at this file packages/graphics-extras/src/drawRegularPolygon.ts
Please correct me if I am looking in the wrong location

**Comment by SuperSodaSea** [comment]
This should have been fixed in #10099.
