### ISSUE TITLE
Bug: Shader alpha not working

### ISSUE THREAD

**Issue by SADYX** [pixijs/pixijs#10114]
### Current Behavior

Setting  gl_FragColor.a lower than 1.0 seems to have no effect in fragment shader.
```
// gl_FragColor = vec4(col, 1.);
gl_FragColor = vec4(col, 0.0);
```

### Expected Behavior

Alpha should work in fragment shader.

### Steps to Reproduce

[link](https://pixijs.com/playground?source=eyJjb2RlIjoiaW1wb3J0ICogYXMgUElYSSBmcm9tICdwaXhpLmpzJztcblxuY29uc3QgYXBwID0gbmV3IFBJWEkuQXBwbGljYXRpb24oeyByZXNpemVUbzogd2luZG93IH0pO1xuXG5kb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGFwcC52aWV3KTtcblxuLy8gQnVpbGQgZ2VvbWV0cnkuXG5jb25zdCBnZW9tZXRyeSA9IG5ldyBQSVhJLkdlb21ldHJ5KClcbiAgICAuYWRkQXR0cmlidXRlKCdhVmVydGV4UG9zaXRpb24nLCAvLyB0aGUgYXR0cmlidXRlIG5hbWVcbiAgICAgICAgWy0xMDAsIC0xMDAsIC8vIHgsIHlcbiAgICAgICAgICAgIDEwMCwgLTEwMCwgLy8geCwgeVxuICAgICAgICAgICAgMTAwLCAxMDAsXG4gICAgICAgICAgICAtMTAwLCAxMDBdLCAvLyB4LCB5XG4gICAgICAgIDIpIC8vIHRoZSBzaXplIG9mIHRoZSBhdHRyaWJ1dGVcbiAgICAuYWRkQXR0cmlidXRlKCdhVXZzJywgLy8gdGhlIGF0dHJpYnV0ZSBuYW1lXG4gICAgICAgIFswLCAwLCAvLyB1LCB2XG4gICAgICAgICAgICAxLCAwLCAvLyB1LCB2XG4gICAgICAgICAgICAxLCAxLFxuICAgICAgICAgICAgMCwgMV0sIC8vIHUsIHZcbiAgICAgICAgMikgLy8gdGhlIHNpemUgb2YgdGhlIGF0dHJpYnV0ZVxuICAgIC5hZGRJbmRleChbMCwgMSwgMiwgMCwgMiwgM10pO1xuXG5jb25zdCB2ZXJ0ZXhTcmMgPSBgXG5cbiAgICBwcmVjaXNpb24gbWVkaXVtcCBmbG9hdDtcblxuICAgIGF0dHJpYnV0ZSB2ZWMyIGFWZXJ0ZXhQb3NpdGlvbjtcbiAgICBhdHRyaWJ1dGUgdmVjMiBhVXZzO1xuXG4gICAgdW5pZm9ybSBtYXQzIHRyYW5zbGF0aW9uTWF0cml4O1xuICAgIHVuaWZvcm0gbWF0MyBwcm9qZWN0aW9uTWF0cml4O1xuXG4gICAgdmFyeWluZyB2ZWMyIHZVdnM7XG5cbiAgICB2b2lkIG1haW4oKSB7XG5cbiAgICAgICAgdlV2cyA9IGFVdnM7XG4gICAgICAgIGdsX1Bvc2l0aW9uID0gdmVjNCgocHJvamVjdGlvbk1hdHJpeCAqIHRyYW5zbGF0aW9uTWF0cml4ICogdmVjMyhhVmVydGV4UG9zaXRpb24sIDEuMCkpLnh5LCAwLjAsIDEuMCk7XG5cbiAgICB9YDtcblxuY29uc3QgZnJhZ21lbnRTcmMgPSBgXG4vL0Jhc2VkIG9uIHRoaXM6IGh0dHBzOi8vd3d3LnNoYWRlcnRveS5jb20vdmlldy93dGxTV1hcbnByZWNpc2lvbiBtZWRpdW1wIGZsb2F0O1xuXG52YXJ5aW5nIHZlYzIgdlV2cztcblxudW5pZm9ybSBzYW1wbGVyMkQgbm9pc2U7XG51bmlmb3JtIGZsb2F0IHRpbWU7XG5cbi8vIERpc3RhbmNlIGZ1bmN0aW9uLiBKdXN0IGNhbGN1bGF0ZXMgdGhlIGhlaWdodCAoeikgZnJvbSB4LHkgcGxhbmUgd2l0aCByZWFsbHkgc2ltcGxlIGxlbmd0aCBjaGVjay5cbi8vIEl0cyBub3QgZXhhY3QgYXMgdGhlcmUgY291bGQgYmUgc2hvcnRlciBkaXN0YW5jZXMuXG52ZWMyIGRpc3QodmVjMyBwKVxue1xuICAgIGZsb2F0IGlkID0gZmxvb3IocC54KStmbG9vcihwLnkpO1xuICAgIGlkID0gbW9kKGlkLCAyLik7XG4gICAgZmxvYXQgaCA9IHRleHR1cmUyRChub2lzZSwgdmVjMihwLngsIHAueSkqMC4wNCkucio1LjE7XG4gICAgcmV0dXJuIHZlYzIoaC1wLnosaWQpO1xufVxuXG4vL0xpZ2h0IGNhbGN1bGF0aW9uLlxudmVjMyBjYWxjbGlnaHQodmVjMyBwLCB2ZWMzIHJkKVxue1xuICAgIHZlYzIgZXBzID0gdmVjMiggMC4sIDAuMDAxKTtcbiAgICB2ZWMzIG4gPSBub3JtYWxpemUoIHZlYzMoXG4gICAgZGlzdChwK2Vwcy55eHgpLnggLSBkaXN0KHAtZXBzLnl4eCkueCxcbiAgICBkaXN0KHArZXBzLnh5eCkueCAtIGRpc3QocC1lcHMueHl4KS54LFxuICAgIGRpc3QocCtlcHMueHh5KS54IC0gZGlzdChwLWVwcy54eHkpLnhcbiAgICApKTtcblxuICAgIHZlYzMgZCA9IHZlYzMoIG1heCggMC4sIGRvdCggLXJkICxuKSkpO1xuXG4gICAgcmV0dXJuIGQ7XG59XG5cbnZvaWQgbWFpbigpXG57XG4gICAgdmVjMiB1diA9IHZlYzIodlV2cy54LDEuLXZVdnMueSk7XG4gICAgdXYgKj0yLjtcbiAgICB1di09MS47XG5cbiAgICB2ZWMzIGNhbSA9IHZlYzMoMC4sdGltZSAtMi4sIC0zLik7XG4gICAgdmVjMyB0YXJnZXQgPSB2ZWMzKHNpbih0aW1lKSowLjEsIHRpbWUrY29zKHRpbWUpKzIuLCAwLiApO1xuICAgIGZsb2F0IGZvdiA9IDIuMjtcbiAgICB2ZWMzIGZvcndhcmQgPSBub3JtYWxpemUoIHRhcmdldCAtIGNhbSk7XG4gICAgdmVjMyB1cCA9IG5vcm1hbGl6ZShjcm9zcyggZm9yd2FyZCwgdmVjMygwLiwgMS4sMC4pKSk7XG4gICAgdmVjMyByaWdodCA9IG5vcm1hbGl6ZSggY3Jvc3MoIHVwLCBmb3J3YXJkKSk7XG4gICAgdmVjMyByYXlkaXIgPSBub3JtYWxpemUodmVjMyggdXYueCAqdXAgKyB1di55ICogcmlnaHQgKyBmb3YqZm9yd2FyZCkpO1xuXG4gICAgLy9EbyB0aGUgcmF5bWFyY2hcbiAgICB2ZWMzIGNvbCA9IHZlYzMoMC4pO1xuICAgIGZsb2F0IHQgPSAwLjtcbiAgICBmb3IoIGludCBpID0gMDsgaSA8IDEwMDsgaSsrKVxuICAgIHtcbiAgICB2ZWMzIHAgPSB0ICogcmF5ZGlyICsgY2FtO1xuICAgIHZlYzIgZCA9IGRpc3QocCk7XG4gICAgdCs9ZC54KjAuNTsvL0p1bXAgb25seSBoYWxmIG9mIHRoZSBkaXN0YW5jZSBhcyBoZWlnaHQgZnVuY3Rpb24gdXNlZCBpcyBub3QgcmVhbGx5IHRoZSBiZXN0IGZvciBoZWlnaHRtYXBzLlxuICAgIGlmKGQueCA8IDAuMDAxKVxuICAgIHtcbiAgICAgICAgdmVjMyBiYyA9IGQueSA8IDAuNSA%2FIHZlYzMoMS4wLCAuOCwgMC4pIDpcbiAgICAgICAgICAgICAgICB2ZWMzKDAuOCwwLjAsIDEuMCk7XG4gICAgICAgIGNvbCA9IHZlYzMoIDEuKSAqIGNhbGNsaWdodChwLCByYXlkaXIpICogKDEuIC0gdC8xNTAuKSAqYmM7XG4gICAgICAgIGJyZWFrO1xuICAgIH1cbiAgICBpZih0ID4gMTAwMC4pXG4gICAge1xuICAgICAgICBicmVhaztcbiAgICB9XG4gICAgfVxuICAgIC8vIGdsX0ZyYWdDb2xvciA9IHZlYzQoY29sLCAxLik7XG4gICAgZ2xfRnJhZ0NvbG9yID0gdmVjNChjb2wsIDAuMSk7XG59YDtcblxuY29uc3QgdW5pZm9ybXMgPSB7XG4gICAgbm9pc2U6IFBJWEkuVGV4dHVyZS5mcm9tKCdodHRwczovL3BpeGlqcy5jb20vYXNzZXRzL3Blcmxpbi5qcGcnKSxcbiAgICB0aW1lOiAwLFxufTtcbi8vIE1ha2Ugc3VyZSByZXBlYXQgd3JhcCBpcyB1c2VkIGFuZCBubyBtaXBtYXBwaW5nLlxuXG51bmlmb3Jtcy5ub2lzZS5iYXNlVGV4dHVyZS53cmFwTW9kZSA9IFBJWEkuV1JBUF9NT0RFUy5SRVBFQVQ7XG51bmlmb3Jtcy5ub2lzZS5iYXNlVGV4dHVyZS5taXBtYXAgPSBmYWxzZTtcblxuLy8gQnVpbGQgdGhlIHNoYWRlciBhbmQgdGhlIHF1YWQuXG5jb25zdCBzaGFkZXIgPSBQSVhJLlNoYWRlci5mcm9tKHZlcnRleFNyYywgZnJhZ21lbnRTcmMsIHVuaWZvcm1zKTtcbmNvbnN0IHF1YWQgPSBuZXcgUElYSS5NZXNoKGdlb21ldHJ5LCBzaGFkZXIpO1xuXG5xdWFkLnBvc2l0aW9uLnNldCg0MDAsIDMwMCk7XG5xdWFkLnNjYWxlLnNldCgyKTtcblxuYXBwLnN0YWdlLmFkZENoaWxkKHF1YWQpO1xuXG4vLyBzdGFydCB0aGUgYW5pbWF0aW9uLi5cbmxldCB0aW1lID0gMDtcblxuYXBwLnRpY2tlci5hZGQoKGRlbHRhKSA9Plxue1xuICAgIHRpbWUgKz0gMSAvIDYwO1xuICAgIHF1YWQuc2hhZGVyLnVuaWZvcm1zLnRpbWUgPSB0aW1lO1xuICAgIHF1YWQuc2NhbGUuc2V0KE51bWJlcihNYXRoLmNvcyh0aW1lKSkgKyAyLCBOdW1iZXIoTWF0aC5zaW4odGltZSAqIDAuNykpICsgMik7XG59KTtcbiJ9&exampleId=custom)

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by MichaelMakesGames** [comment]
@SADYX I recently had a similar issue. Setting `backgroundAlpha: 0` in PIXI.Application seemed to make alpha work in the shaders

**Comment by SADYX** [comment]
> @SADYX I recently had a similar issue. Setting `backgroundAlpha: 0` in PIXI.Application seemed to make alpha work in the shaders

Thanks for your sharing!
