### ISSUE TITLE
Bug: v8.0.0-rc4 Texture.update() missing?

### ISSUE THREAD

**Issue by davidye** [pixijs/pixijs#10126]
### Current Behavior

I use a texture that has a canvas source. In v7 it was possible to draw to this canvas, call texture.update(), and then render the updated texture. This doesn't appear possible in v8 anymore?

v8: https://www.pixiplayground.com/#/edit/j8-by8KSiXzp92C2xPrvB
v7: https://www.pixiplayground.com/#/edit/HaCN2gSJBEiTgZZdr3aKv

### Expected Behavior

It should be possible to update the texture / source

### Steps to Reproduce

See playgrounds

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by GoodBoyDigital** [comment]
hey @davidye, thanks for pointing out. I updated the example:

The line needs to be:

` texture.source.update();`

I can look into adding a `texture.update()` thats a pass through function though.

**Comment by GoodBoyDigital** [comment]
interesting! ok - looking into this now
