### ISSUE TITLE
Bug: Pixi 8 build with vite get warning and pixi crashes when minify is turned on

### ISSUE THREAD

**Issue by aronsuarez** [pixijs/pixijs#10137]
### Current Behavior

When i build pixijs with vite and minify turned on i got this warnings:

`Use of eval in "node_modules/pixi.js/lib/compressed-textures/basis/worker/BasisWorker.mjs" is strongly discouraged as it poses security risks and may cause issues with minification.
Use of eval in "node_modules/pixi.js/lib/compressed-textures/ktx/worker/KTXWorker.mjs" is strongly discouraged as it poses security risks and may cause issues with minification.
Use of eval in "node_modules/@protobufjs/inquire/index.js" is strongly discouraged as it poses security risks and may cause issues with minification.`

Deployed, pixi crashes after launching, if a turn off minify in the vite build config, it works as espected

### Expected Behavior

Build the code with minify on and running as expected

### Steps to Reproduce

Setup a vue3 project with vite and integrate pixi js, then build it with and without minify

### Environment

- **`pixi.js` version**: *8.0.0-rc4*
- **Browser & Version**: *Chrome 120*
- **OS & Version**: *MacOS 14.1*

**Comment by norflin321** [comment]
adding `import "pixi.js/unsafe-eval";` should fix the issue

**Comment by aronsuarez** [comment]
@norflin321 it works, thank you!
