### ISSUE TITLE
Bug: in docs, example for PIXI.Geometry draws a dovetail instead of a square

### ISSUE THREAD

**Issue by humodz** [pixijs/pixijs#10155]
### Current Behavior

The following documentation page for PIXI.Geometry contains a peculiar example: https://pixijs.download/dev/docs/PIXI.Geometry.html

If we pass that geometry to a PIXI.Mesh, a dovetail shape is rendered:

![image](https://github.com/pixijs/pixijs/assets/8527969/319f203a-bfd2-4ae8-8ea5-04bbe7e39ef0)

### Expected Behavior

It feels like the example wants to draw a square instead of a dovetail?

### Steps to Reproduce

```js
const geometry = new PIXI.Geometry();

geometry.addAttribute('positions', [0, 0, 100, 0, 100, 100, 0, 100], 2);
geometry.addAttribute('uvs', [0, 0, 1, 0, 1, 1, 0, 1], 2);
geometry.addIndex([0, 1, 2, 1, 3, 2]);

const texture = PIXI.Texture.from(someTexture);
const material = new PIXI.MeshMaterial(texture);
const mesh = new PIXI.Mesh(geometry, material);
app.stage.addChild(mesh);
```

### Environment

- **`pixi.js` version**: *7.1.0*
- **Browser & Version**: *Chrome 108*
- **OS & Version**: *Ubuntu 22.04*
- **Running Example**: *https://pixiplayground.com/#/edit/ZsBOclpkV1ku5OWXC_lw-*

### Possible Solution

change the example in the docs to the following:

```js
const geometry = new PIXI.Geometry();
geometry.addAttribute('positions', [0, 0, 100, 0, 0, 100, 100, 100], 2);
geometry.addAttribute('uvs', [0, 0, 1, 0, 0, 1, 1, 1], 2);
geometry.addIndex([0, 1, 2, 1, 3, 2]);
```

**Comment by Nitz2611** [comment]
Hi @humodz i want to contribute but i can't find source code of documentation. Can you help me with this.

**Comment by bigtimebuddy** [comment]
Here it is:

https://github.com/pixijs/pixijs/blob/dev/packages/core/src/geometry/Geometry.ts

**Comment by himakhaitan** [comment]
Hey @humodz Which branch should be pulled to solve this issue?

**Comment by himakhaitan** [comment]
https://github.com/pixijs/pixijs/pull/10225

I have created this pull request in front of this Issue
