### ISSUE TITLE
Bug: When curve the text, the bounds of the text get cut off in pixijs 4.8.9

### ISSUE THREAD

**Issue by keisariben** [pixijs/pixijs#10167]
### Current Behavior

![image](https://github.com/pixijs/pixijs/assets/92005974/e0ca37d9-65db-430a-9008-0022e78f9382)
![image](https://github.com/pixijs/pixijs/assets/92005974/23150866-6391-4d97-a954-43d4f0f5c6c0)

when it's plain text, everything is working well but in the case of the curve text, the bounds get cut off.
i am using pixijs 4.8.9
I have already referenced the pixijs issues and discussion and there are some reports related with this case.
but it didnt help for me.

### Expected Behavior

it dont have to cut off the bounds of text

### Steps to Reproduce

this is my code snippet.
`object.curve = curve;
    if (
      object.context.measureText(object.text).width * 1.3 >
      object.style.wordWrapWidth
    ) {
      var style = object.style.clone();
      style.wordWrapWidth = object.context.measureText(object.text).width * 1.3;
      object.style = style;
      object.updateText(true);
    }

    var curveRadian = Math.abs(curve) * (Math.PI / 180);
    var circumference = (360 / Math.abs(curve)) * object.width;
    var radius = circumference / (2 * Math.PI);

    var startDegree = (curve > 0 ? Math.PI : Math.PI * 2) - curveRadian / 2;
    var degreeIncrement = curveRadian / 100;

    var points = [];
    for (var i = 0; i <= curveRadian; i += degreeIncrement) {
      var degree = startDegree + i;
      var radian = degree;
      radian = radian + Math.PI / 2;
      if (degree > 360) degree = degree - 360;
      points.push(
        new PIXI.Point(Math.cos(radian) * radius, Math.sin(radian) * radius)
      );
    }
    if (curve < 0) points = points.reverse();
    const container = new PIXI.Container();
    const rope = new PIXI.mesh.Rope(object.texture, points);
    container.addChild(rope);
    const bounds = container.getLocalBounds();
    const matrix = new PIXI.Matrix();
    matrix.tx = -bounds.x;
    matrix.ty = -bounds.y;

    const renderTexture = PIXI.RenderTexture.create(
      bounds.width,
      bounds.height
    );
    window.editor
      .getRenderer()
      .render(container, renderTexture, true, matrix, false);
    const sprite = PIXI.Sprite.from(renderTexture);
    sprite.position.set(object.x, object.y);`

### Environment

- **`pixi.js` version**: * 4.8.9*
- **Browser & Version**: * Chrome 108*
- **OS & Version**: *Win 10*

**Comment by bigtimebuddy** [comment]
Unfortunately, we are no longer supporting v4.x of Pixi and cannot support your use-case. Also, text-on-a-curve is not a feature Pixi does out of the box and is likely something that is custom and should live in userland. If you need advice, please make a discussion or ask on Discord and I'm sure folks can help you find a workaround.
