### ISSUE TITLE
Bug: v8.0.0-rc.7 Calling Texture.update() causes texture rendering to fail

### ISSUE THREAD

**Issue by davidye** [pixijs/pixijs#10179]
### Current Behavior

See playground: https://www.pixiplayground.com/#/edit/WWR4CksEeaOL6UfDGTnZ8

### Expected Behavior

Updated texture should render

### Steps to Reproduce

See playground

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by GoodBoyDigital** [comment]
should be fixed by #10187 :)
