### ISSUE TITLE
Bug: v8.0.0-rc.7 Canvas texture conflicts with Graphics when WebGL is used

### ISSUE THREAD

**Issue by zjkmxy** [pixijs/pixijs#10182]
### Current Behavior

PIXI.Graphics' alpha will be applied unequally when the following conditions meet:
1. The renderer is WebGL.
2. There exist both a PIXI.Sprite whose texture is a HTMLCanvasElement and a PIXI.Graphics, in the same batch.
3. PIXI.Graphics' alpha is not 0 or 1.
4. PIXI.Sprite's visibility changes from `true` to `false` after it is rendered at least once.

### Expected Behavior

WebGPU renderer can correctly render the scene. WebGL should give the same result as WebGPU.

### Steps to Reproduce

A more visible Playground sample is [here](https://pixiplayground.com/#/edit/pKf-Optl4es4itEI8yI8G)
Minimal code to reproduce is as follows:
```javascript
const app = new PIXI.Application();
// 1. Use WebGL
await app.init({ resizeTo: window, preference: "webgl"});
document.body.appendChild(app.canvas);
// 2. Add a Canvas Sprite before the Graphics
const squareSprite = PIXI.Sprite.from(document.createElement("canvas"));
app.stage.addChild(squareSprite);
// 3. Add a Graphics with alpha
const graphics = new PIXI.Graphics()
    .rect(0, 0, app.screen.width, app.screen.height)
    .fill({ color: "white", alpha: 0.5 })
graphics.context.batchMode = 'batch'; // Make sure they are batched
app.stage.addChild(graphics);
// 4. Let the sprite render once, then hide it
setTimeout(() => squareSprite.visible = false, 500);
```

### Environment

- **`pixi.js` version**: v8.0.0-rc.7
- **Browser & Version**: Firefox 122.0, Edge 122.0
- **OS & Version**: Debian and Windows (shouldn't matter)
- **Running Example**: <https://pixiplayground.com/#/edit/pKf-Optl4es4itEI8yI8G>

**Comment by zjkmxy** [comment]
I think this and #10179 may be the same issue, but I did not update the texture.

**Comment by GoodBoyDigital** [comment]
thanks for posting @zjkmxy i recently just enabled uint16 buffers - caused a few weird things to happen. Il look into this now.

**Comment by GoodBoyDigital** [comment]
all sorted  :D
