### ISSUE TITLE
Graphics not rendering

### ISSUE THREAD

**Issue by amitmpixentech** [pixijs/pixijs#10206]
### Current Behavior

Graphics are not rendering and is getting created with width and height as 0. Here is my code

const graphics: Graphics = new Graphics();
graphics.setStrokeStyle({ width: 2, color: 0x000000 });
graphics.fill(color);
graphics.rect(x, y, width, height);
console.log(width, height, graphics.width, graphics.height)
return graphics;

### Expected Behavior

Should render a rectangle

### Steps to Reproduce

Run the above code

### Environment

- **`pixi.js` version**: *e.g. 8.0.0-rc.9*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *Windows*

### Possible Solution

No idea.

**Comment by amitmpixentech** [comment]
![image](https://github.com/pixijs/pixijs/assets/104749364/bd60a964-70d2-483d-aa23-acce89744b12)

**Comment by david-ergoss** [comment]
Also in Pixi 8 vs 7, graphic stroke width is not working when filled. The fill color extend above the stroke leaving only one pixel visible.

**Comment by Zyie** [comment]
Hey, you need to call `.rect` before `.fill`

```ts
const graphics: Graphics = new Graphics();
graphics.setStrokeStyle({ width: 2, color: 0x000000 });
graphics.rect(x, y, width, height);
graphics.fill(color);
console.log(width, height, graphics.width, graphics.height)
return graphics;
```

**Comment by amitmpixentech** [comment]
Thank you very much. I will give it a try.

**Comment by amitmpixentech** [comment]
It works fine, Thanks for the help.
