### ISSUE TITLE
Bug: Uncaught TypeError: Cannot read properties of null (reading '_x')

### ISSUE THREAD

**Issue by dragoon** [pixijs/pixijs#10205]
### Current Behavior

I have a rather complex animated weather app which runs well on PIXI 7, now I am preparing a branch to upgrade to PIXI 8.
The app runs several animated cards with their own WebGL canvases. Every 30 min, the weather is updated, which can cause some sprites to be removed and some to be added. I have no clue what is this component in PIXI in which the error is happening, and what else to test, so I am opening a bug here.

![Screenshot 2024-01-19 at 14 18 29](https://github.com/pixijs/pixijs/assets/490130/e7a3b55e-3bdd-467b-bac1-cba4efafa5d9)

And thank you for all the work on PIXI, I would really like to update to PIXI 8, my app now runs smoothly (>50 FPS) on Raspberry.

### Expected Behavior

No errors

### Steps to Reproduce

https://codepen.io/rprokofyev/pen/YzgROZm
Happens at the next call of setInverval function (after 1 min). Maybe I'm doing something in a wrong way. but this was working without issues in PIXI 7.

### Environment

- **`pixi.js` version**: 8.0-rc4 - 8.0.-rc9
- **Browser & Version**:  Chrome 119
- **OS & Version**:  OS X and Raspbian
- **Running Example**: https://codepen.io/rprokofyev/pen/YzgROZm

**Comment by Zyie** [comment]
Hey @dragoon are you able to create a smaller example of the issue you are having so we can debug easier. Something on [pixiplayground](https://www.pixiplayground.com/#/edit) or codepen, jsfiddle

**Comment by dragoon** [comment]
Hi @Zyie, I will try, just wanted to check maybe someone knows why the object might be null.

**Comment by dragoon** [comment]
Hi @Zyie , I've been able to re-create the bug with a rather simple example of 230 lines: https://codepen.io/rprokofyev/pen/YzgROZm
The bug usually happens after the next call in the setInverval function at the bottom, I have tried several times and it has reliably occurred at the first time setInverval is called (after one minute)

**Comment by GoodBoyDigital** [comment]
thanks @dragoon ! looking into this now

**Comment by dragoon** [comment]
Okay, thank you for looking into this, I will close this, but interestingly this works in PIXI 7 without issues for some reason.
