### ISSUE TITLE
Assets.init failing

### ISSUE THREAD

**Issue by amitmpixentech** [pixijs/pixijs#10203]
### Current Behavior

I have just migrated to pixijs v 8.0.0-rc.9 and facing this issue. I am not using assetspack but creating my manifest files dynamically from my assetConfig file. Here is my manifest data that I pass to Assets.init.

It was working fine in Pixijs version 7.3.x.

It throws error like 

pixi__js.js?v=28b91217:6802 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at checkDataUrl (pixi__js.js?v=28b91217:6802:15)
    at Object.test (pixi__js.js?v=28b91217:7220:12)
    at chunk-VA4AVU5O.js?v=17aa82f2:1479:26
    at Array.forEach (<anonymous>)
    at chunk-VA4AVU5O.js?v=17aa82f2:1473:14
    at Array.forEach (<anonymous>)
    at chunk-VA4AVU5O.js?v=17aa82f2:1472:17
    at Array.forEach (<anonymous>)
    at Resolver.add (chunk-VA4AVU5O.js?v=17aa82f2:1460:16)
    at chunk-VA4AVU5O.js?v=17aa82f2:1409:12

Here is my manifest data.

{
    "bundles": [
        {
            "name": "default",
            "assets": []
        },
        {
            "name": "preloader",
            "assets": [
                {
                    "alias": "TextConfig.json",
                    "srcs": [
                        "assets/locale/en/TextConfig.json"
                    ]
                },
                {
                    "alias": "gameContent.json",
                    "srcs": [
                        "assets/locale/en/gameContent.json"
                    ]
                }
            ]
        },
        {
            "name": "primary",
            "assets": [
                {
                    "alias": "NotoSans-Medium",
                    "src": [
                        "assets/fonts/en/NotoSans-Medium.ttf"
                    ]
                },
                {
                    "alias": "NotoSansBold",
                    "src": [
                        "assets/fonts/en/NotoSans-Black.ttf"
                    ]
                },
                {
                    "alias": "defender_ballAnims.json",
                    "srcs": [
                        "assets/images/@1x/defender_ballAnims.json"
                    ]
                },
                {
                    "alias": "defender_gamebg.json",
                    "srcs": [
                        "assets/images/@1x/defender_gamebg.json"
                    ]
                },
                {
                    "alias": "defender_ui.json",
                    "srcs": [
                        "assets/images/@1x/defender_ui.json"
                    ]
                }
            ]
        }
    ]
}

### Expected Behavior

It should load assets.

### Steps to Reproduce

Use the manifest data I pasted in the post and try to do Assets.init.

### Environment

- **`pixi.js` version**: *e.g. 8.0.0-rc.9*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *Windows*

**Comment by amitmpixentech** [comment]
Its working if I give a json path and it loads json, but is not accepting data directly.

**Comment by Zyie** [comment]
Hey, in v8 we removed `name` and `srcs` as options for the manifest. You should use `alias` and `src`

**Comment by amitmpixentech** [comment]
If instead of loading an external manifest file, I want to pass the data directly, is that possible?

Best regards,

Amit M
________________________________

**Comment by bigtimebuddy** [comment]
Maybe this will help:

https://github.com/pixijs/pixijs/discussions/10202#discussioncomment-8432509
