### ISSUE TITLE
Feature Request: Video autoPlay for bundle asset loading

### ISSUE THREAD

**Issue by codeerspl** [pixijs/pixijs#10207]
### Description

Hello,

It would be very good if we could define additional options when loading assets from bundles.

i.e. `{ alias: "Example", src: "./video.webm", options: { autoPlay: false } }`

Or define the default autoPlay state for VideoResource globally.

Problem:

When loading a video via bundle, a videoResource is created with autoPlay = true. 

You have to manually pause the video, but the first opportunity is only after the video is already loaded and canplaythrough = true. 

The video plays for a fraction of a second before pausing. The crux of the problem lies in the video sound. You hear it for a split second and then it stops.

You can work around this by manually handling the video bundle and creating a VideoResource, but this is not the desired solution.

**Comment by bigtimebuddy** [comment]
Luckily this is supported!

Here's an [example](https://codesandbox.io/p/sandbox/sharp-jang-mvsrwj?file=%2Fsrc%2Findex.js%3A41%2C3-47%2C6).

```js
  const texture = await PIXI.Assets.load({
    src: "https://pixijs.com/assets/video.mp4",
    alias: "video",
    data: {
      // options to be passed to VideoResource
      resourceOptions: {
        muted: true,
        autoPlay: false
      },
    },
  });
```

You can also set default values like this:

```js
import { loadVideo } from 'pixi.js';

loadVideo.config.defaultMuted = true;
loadVideo.config.defaultAutoPlay = false;
```
See [LoadVideoConfig](https://pixijs.download/dev/docs/PIXI.LoadVideoConfig.html).

**Comment by xeoshow** [comment]
Hello @bigtimebuddy ,
It seems the [example](https://codesandbox.io/p/sandbox/sharp-jang-mvsrwj?file=%2Fsrc%2Findex.js%3A41%2C3-47%2C6) link is broken, just shows ”Sandbox not found", could you please help? 
Thanks v much.

**Comment by gubeils** [comment]
> Hello @bigtimebuddy , It seems the [example](https://codesandbox.io/p/sandbox/sharp-jang-mvsrwj?file=%2Fsrc%2Findex.js%3A41%2C3-47%2C6) link is broken, just shows ”Sandbox not found", could you please help? Thanks v much.

I also met this problem...

**Comment by bigtimebuddy** [comment]
@gubeils @xeoshow I fixed the example, it wasn't set as public. Sorry about that!
