### ISSUE TITLE
Bug: incorrect text stroke drawing with some fonts  

### ISSUE THREAD

**Issue by aram88888** [pixijs/pixijs#10212]
### Current Behavior

![image](https://github.com/pixijs/pixijs/assets/117649338/4ab0f8a3-5a21-4aa0-96bf-d4e459182dd6)

### Expected Behavior

![image](https://github.com/pixijs/pixijs/assets/117649338/ed238d2d-5e3f-4f73-8d37-9170d82512e3)

### Steps to Reproduce

const app = new PIXI.Application({background: '#000000', width: 300, height: 300});
document.body.appendChild(app.view);
addFont('roboto','Roboto-Regular.ttf');
window.onload = function(){
    const text = new PIXI.Text('M', {
        fill: 0xffffff,
        stroke: 0xff0000,
        strokeThickness: 30,
        fontSize: 200,
        fontFamily: 'roboto'
    });
    app.stage.addChild(text);
    text.x = 0;
    text.y = 0;
}

function addFont(key, fontFileName) {
    const css = `@font-face {font-family: ${key};    src: url("./${fontFileName}");')');}`;
    const style = document.createElement('style');
    style.type = 'text/css';
    if (style.styleSheet) {
        style.styleSheet.cssText = css;
    } else {
        style.appendChild(document.createTextNode(css));
    }
    document.head.appendChild(style);
    const p = document.createElement('span');
    p.style.fontFamily = `${key}`;
    p.style.visibility = "hidden";
    p.style.position = "absolute";
    p.innerHTML = ".";
    document.body.insertBefore(p, document.body.firstChild);
}

### Environment

pixi.js v6 and v7

### Additional Information

You can download the font from google fonts

**Comment by bigtimebuddy** [comment]
Try adjusting mitreLimit

From the docs:

> The miter limit to use when using the 'miter' lineJoin mode.
>
> This can reduce or increase the spikiness of rendered text.

**Comment by aram88888** [comment]
Thank you. It worked.  I had a problem setting lineJoin property on IOS devices a long time ago. Can't remember the exact version of operating system.  It caused an application error. Since there I have not used the property. Will mitterLimit work on all platforms?
