### ISSUE TITLE
Feature Request: Change the default priorities of the compressed textures formats

### ISSUE THREAD

**Issue by ddenisyuk** [pixijs/pixijs#10213]
### Description

Change the priorities according to texture qualities: highest quality == highest priority.
Current priorities:
1. s3tc
2. s3tc_sRGB
3. astc
4. etc
5. etc1
6. pvrtc
7. atc
8. bptc

Suggestion:
1. bptc
2. astc
3. etc
4. s3tc
5. s3tc_sRGB
6. pvrtc
7. etc1
8. atc

More details about texture types and their quality can be found here:
- https://aras-p.info/blog/2020/12/08/Texture-Compression-in-2020/
- https://docs.unity3d.com/Manual/class-TextureImporterOverride.html#default-texture-compression-formats-by-platform

**Comment by bigtimebuddy** [comment]
Sounds reasonable. Would welcome a PR to change this, especially for v8.
