### ISSUE TITLE
Impossible to set sprite filters as an empty array to then add multiple filters

### ISSUE THREAD

**Issue by nasselk** [pixijs/pixijs#10226]
I noticed that it's impossible to pre assign an empty array to a sprite filters, and then add multiple filters to it.

Here is a fiddle : https://jsfiddle.net/pn5Lkjy3/1/

As you can see, the filter isn't displayed at all.

However, this would work (direct filter assignment but then we can't use multiple filters on a sprite) : https://jsfiddle.net/pn5Lkjy3/2/

**Edit** : Even when setting directly app.stage.filters = [filter], it wont work after a certain amount of time (generally if you don't create the shockwave immediatly on the main function).

**Comment by bigtimebuddy** [comment]
Here's the code reference for v8 filters assignment:
https://github.com/pixijs/pixijs/blob/c3c8d0e07ccf66ed69443a18f7cbcab66170d20f/src/scene/container/container-mixins/effectsMixin.ts#L137

Because assigning `filters` to `[]` means that internally `hasFilters` is `false` in that function. So this is called:

```ts
this.removeEffect(this._filters.effect);
returnFilterEffect(this._filters.effect);
this._filters.effect = null;
```

Then when you `obj.filters.push(filter)` later, the effect is never getting set.

@GoodBoyDigital thoughts? Should the filters array be a Proxy object instead?

**Comment by GoodBoyDigital** [comment]
this is a bit of a tricky one as generally! We want to not have to cause filters to break batching, so we check at the time of assignment if there are actually any filters. this is done to not have to check the whole scene graph for filter changes each frame.

this means currently the following:
```
container.filters = [] // no filters - s oskipped
container.filters.push(filter) // this is not watched, so still thinks there are no filters
``` 

this best way is to always assign the filters directly:

```
container.filters = [] // no filters
container.filters = [filter] // will add a filter
 ```

i know its a bit weird but, perf wise i know devs use this `container.filters = []` syntax to null out filters.

**Comment by GoodBoyDigital** [comment]
to add to that :)

```
container.filters = [filter] // will add a filter
container.filters.pop() // will not render filters, but still break the batches
```

**Comment by bigtimebuddy** [comment]
Two ideas how we could enforce this:
* Have `filters` getter type as `readonly Filters[]` type
* Do `Object.freeze` on the setter to keep users from manipulating the array
