### ISSUE TITLE
Bug: http://gametest.mobi/pixi/morph is down

### ISSUE THREAD

**Issue by yuxiaoli** [pixijs/pixijs#10244]
### Current Behavior

gametest.mobi is down
http://gametest.mobi/pixi/morph

### Expected Behavior

http://gametest.mobi/pixi/morph shall show a demo page

### Steps to Reproduce

Go to this page: http://gametest.mobi/pixi/morph

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by photonstorm** [comment]
That's my site. I took it down last year. Happy to give you the morph code if you want to put it elsewhere. It's a very old version of Pixi though - v1 I believe!

**Comment by bigtimebuddy** [comment]
No worries @photonstorm. Thanks for responding.

**Comment by yuxiaoli** [comment]
@photonstorm I'd really appreciate it if you can give me the morph code! Yes I'm thinking to host it somewhere else.
