### ISSUE TITLE
Bug: [v8 regression] cannot do many `moveTo`/`lineTo`  

### ISSUE THREAD

**Issue by joergplewe** [pixijs/pixijs#10265]
### Current Behavior

Porting my app to v8 reveals an issue: I do alot of dashed lines consisting of thousands and thousands of  `moveTo`/`lineTo`.
After a not even very bug number of `moveTo`/`lineTo` pairs the browser logs an error and stops rendering.

E.g. for 5000 `moveTo`/`lineTo` pairs:
```
Buffer size (800000000) exceeds the max buffer size limit (268435456).
 - While calling [Device].CreateBuffer([BufferDescriptor "attribute-batch-buffer"]).

Buffer size (600000000) exceeds the max buffer size limit (268435456).
 - While calling [Device].CreateBuffer([BufferDescriptor "index-batch-buffer"]).

249*: [Invalid Buffer "attribute-batch-buffer"] is invalid.
 - While encoding [RenderPassEncoder].SetVertexBuffer(1, [Invalid Buffer "attribute-batch-buffer"], 0, 18446744073709551615).

249*: [Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer]])
```

### Expected Behavior

Worked flawless with v7.

Note: Virtually any number of `moveTo` or `lineTo` can be executed alone, just not pairwise.

### Steps to Reproduce

I created a playground: https://www.pixiplayground.com/#/edit/qLzI54Js-_2Itejv7wB9E

Watch the console.

Not even 5000 `moveTo`/`lineTo` can be done.

### Environment

- **`pixi.js` version**: v8.0.0-rc.11, v8.0.0
- **Browser & Version**: Chrome
- **OS & Version**: Windows11
- **Running Example**: https://www.pixiplayground.com/#/edit/qLzI54Js-_2Itejv7wB9E

**Comment by GoodBoyDigital** [comment]
hey there! this was a conscious choice as we figured by limiting the complexity of the graphics - we could simplify the logic under the hood .

It would be good to understand the use case. Thanks!

**Comment by GoodBoyDigital** [comment]
this is super helpful - thanks for sharing this line drawing code - will have a play and get back to you! the buffer sizes do sound a bit high!

**Comment by joergplewe** [comment]
The line drawing code finds a condensed, isolated form in the playground https://www.pixiplayground.com/#/edit/qLzI54Js-_2Itejv7wB9E

**Comment by GoodBoyDigital** [comment]
Hey @joergplewe  - seems like a webGPU limitation rather than a pixi one. Using the WebGL renderer will provide a work around for now why we investigate at least!

https://www.pixiplayground.com/#/edit/ebpGQ9z8L1Jx9gVs2Uzs_

**Comment by joergplewe** [comment]
Yeah thanks, that slightly shifts the limit from <2900 to <8200.

I did a crosscheck with a v7 version of the same, where the limit is well >2.000.000:

https://www.pixiplayground.com/#/edit/7pqux6HZlhr2M-wOaxhUw

(did you know that one cannot choose v7 version in the playground any more? I recycled on old one :) )

**Comment by GoodBoyDigital** [comment]
looks like it WebGPU has a hard limit on buffers size. Figured most people would not need that much complexity in a single geometry!

perhaps i got that on wrong! For now, would this be enough to render your lines? (like as each full line is an individual graphics?) 

thanks!

**Comment by GoodBoyDigital** [comment]
oh, actually i think i can fix webGL easily.. will report back

**Comment by joergplewe** [comment]
I'm optimistic finding a workaround.
Just ... why does that moderate set of `moveTo`/`lineTo` pairs require that huge buffersizes? While e.g. `lineTo` alone does not?

**Comment by GoodBoyDigital** [comment]
i think there might be something wrong in how the buffer size is calculated for large graphics.  Just verifying now

**Comment by GoodBoyDigital** [comment]
found it! Will push a PR fix for this later today. 2000000 not a problem on either renderer now

**Comment by joergplewe** [comment]
Yeah, you are the man! :)

**Comment by GoodBoyDigital** [comment]
haha! thanks :) - appreciate the help getting to the bottom of this one! Open source at its finest!
