### ISSUE TITLE
Bug: Unexpected behaviour of alpha on Graphics

### ISSUE THREAD

**Issue by delasource** [pixijs/pixijs#10260]
### Current Behavior

setting an alpha value on a parent container results in applying that alpha value to every drawn object (line, circle, etc) - i.e. the color property. This results in having objects overlap/intersect and be different in transparency.
![image](https://github.com/pixijs/pixijs/assets/17216038/e2918d74-b63a-43ac-b193-d51d03b0573a)

### Expected Behavior

Setting an alpha value of a parent container should make the whole Graphics object transparent **evenly.**
![image](https://github.com/pixijs/pixijs/assets/17216038/882ab99e-d9fe-4f1f-bd08-716767ccf4a7)

### Steps to Reproduce

https://jsfiddle.net/delasource/dvxamt6w/9/

### Environment

- **`pixi.js` version**: 7.4
- **Browser & Version**: Brave/Chromium 122
- **OS & Version**: Win 11
- **Running Example**: https://jsfiddle.net/delasource/dvxamt6w/6

### Possible Solution

have alpha apply on the whole Container

**Comment by bigtimebuddy** [comment]
You need to use AlphaFilter to do this. The way the container alpha works is applying alpha to each nested element. AlphaFilter will render the contents to a frame buffer and apply alpha to the whole surface.

**Comment by rnike** [comment]
We are also facing this issue, and unfortunately AlphaFilter results in poor performance. Is there any other solution?

**Comment by GoodBoyDigital** [comment]
you could try rendering the brush to a texture at full alpha and then use that texture as a sprite in your scene. Its kind of what the alpha filter does, but should be faster!

**Comment by delasource** [comment]
Why close this? AlphaFilter is just a workaround.
This issue is about what I **expect,** setting an alpha value for a Graphics object, when in fact it behaves a certain way due to an internal implementation (from my abstract point of view, a Graphics object is the smallest object in my render tree. Not the individual circle)

**Comment by bigtimebuddy** [comment]
I understand you have different expectations but many vector tools operate like this. When you draw a bunch of circles in a single Graphics the renderer treats them as separate objects. Each shape can have its own fill with independent alpha, color, texture. This is, in fact, a feature not a bug.

For a lot of reasons creating a drawing app with Graphics is a bad idea. It's slow to triangulate and slow to render. And it can de-optimize batching. RenderTexture is the way to go if you want to create a single flat, merged surface. Alternatively, there are libraries where you can create a union of geometric shapes. You may consider this to create a single vector shape.
