### ISSUE TITLE
Feature Request: Allow GraphicsContext.poly to accept PointData[]

### ISSUE THREAD

**Issue by alexbown** [pixijs/pixijs#10276]
### Description

The Polygon shape can accept an array of numbers or PointData (which I believe are converted to an array of numbers either way, whereas the GraphicsContext.poly currently only accepts an array of numbers.
I believe that this should be brought in line with the shape to accept PointData to alllow supplying xy pairs as well as just numbers.

Shape constructor:
https://github.com/pixijs/pixijs/blob/705d60f5fb123ec79b6524148c937e45a049ac41/src/maths/shapes/Polygon.ts#L54

GraphicsContext.poly:
https://github.com/pixijs/pixijs/blob/705d60f5fb123ec79b6524148c937e45a049ac41/src/scene/graphics/shared/GraphicsContext.ts#L758

**Comment by Zyie** [comment]
Should be fixed in 8.0.1
