### ISSUE TITLE
Bug: app.renderer.extract.base64 doesn't apply tint

### ISSUE THREAD

**Issue by erikdubbelboer** [pixijs/pixijs#10275]
### Current Behavior

[Playground](https://pixijs.com/playground?state=eyJmaWxlcyI6eyIvc3JjL2luZGV4LmpzIjp7ImNvZGUiOiJpbXBvcnQgeyBBcHBsaWNhdGlvbiwgQXNzZXRzLCBTcHJpdGUsIFJlbmRlclRleHR1cmUgfSBmcm9tICdwaXhpLmpzJztcblxuKGFzeW5jICgpID0%2BXG57XG4gICAgLy8gQ3JlYXRlIGEgbmV3IGFwcGxpY2F0aW9uXG4gICAgY29uc3QgYXBwID0gbmV3IEFwcGxpY2F0aW9uKCk7XG5cbiAgICAvLyBJbml0aWFsaXplIHRoZSBhcHBsaWNhdGlvblxuICAgIGF3YWl0IGFwcC5pbml0KHsgYmFja2dyb3VuZDogJyMxMDk5YmInLCByZXNpemVUbzogd2luZG93IH0pO1xuXG4gICAgLy8gTG9hZCB0aGUgYnVubnkgdGV4dHVyZVxuICAgIGNvbnN0IHRleHR1cmUgPSBhd2FpdCBBc3NldHMubG9hZCgnaHR0cHM6Ly9waXhpanMuY29tL2Fzc2V0cy9idW5ueS5wbmcnKTtcblxuICAgIC8vIENyZWF0ZSBhIGJ1bm55IFNwcml0ZVxuICAgIGNvbnN0IGJ1bm55ID0gbmV3IFNwcml0ZSh0ZXh0dXJlKTtcbiAgICBjb25zdCB3aWR0aCA9IGJ1bm55LndpZHRoO1xuICAgIGNvbnN0IGhlaWdodCA9IGJ1bm55LmhlaWdodDtcblxuICAgIGNvbnN0IHRhcmdldCA9IFJlbmRlclRleHR1cmUuY3JlYXRlKHsgd2lkdGgsIGhlaWdodCB9KTtcbiAgICBhcHAucmVuZGVyZXIucmVuZGVyKHtcbiAgICAgICAgY29udGFpbmVyOiBidW5ueSxcbiAgICAgICAgdGFyZ2V0LFxuICAgICAgICBjbGVhckNvbG9yOiB7IHI6IDAsIGc6IDAsIGI6IDAsIGE6IDAgfSxcbiAgICB9KTtcblxuICAgIGNvbnN0IHMgPSBTcHJpdGUuZnJvbSh0YXJnZXQpO1xuICAgIHMudGludCA9IDB4ZmYwMDAwO1xuICAgIGNvbnN0IGltYWdlID0gYXdhaXQgYXBwLnJlbmRlcmVyLmV4dHJhY3QuYmFzZTY0KHMsICdpbWFnZS9wbmcnKTtcblxuICAgIGNvbnN0IGltZyA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2ltZycpO1xuICAgIGltZy5zcmMgPSBpbWFnZTtcbiAgICBpbWcud2lkdGggPSAyMDA7XG4gICAgaW1nLmhlaWdodCA9IDIwMDtcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGltZyk7XG59KSgpO1xuIn0sIi9zcmMvc3R5bGVzLmNzcyI6eyJjb2RlIjoiYm9keSB7IG1hcmdpbjogMDsgb3ZlcmZsb3c6IGhpZGRlbjsgfSJ9LCIvaW5kZXguaHRtbCI6eyJjb2RlIjoiXG48IURPQ1RZUEUgaHRtbD5cbiAgPGh0bWw%2BXG4gIDxoZWFkPlxuICA8dGl0bGU%2BUGl4aUpTIFBsYXlncm91bmQ8L3RpdGxlPlxuICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIiAvPlxuICA8bGluayByZWw9XCJzdHlsZXNoZWV0XCIgaHJlZj1cInNyYy9zdHlsZXMuY3NzXCI%2BXG48L2hlYWQ%2BXG48Ym9keT5cbiAgPHNjcmlwdCBzcmM9XCJzcmMvaW5kZXguanNcIj48L3NjcmlwdD5cbjwvYm9keT5cbjwvaHRtbD4ifSwiL3BhY2thZ2UuanNvbiI6eyJjb2RlIjoie1xuICBcInNjcmlwdHNcIjoge1xuICAgIFwic3RhcnRcIjogXCJwYXJjZWwgaW5kZXguaHRtbCAtLW9wZW5cIixcbiAgICBcImJ1aWxkXCI6IFwicGFyY2VsIGJ1aWxkIGluZGV4Lmh0bWxcIlxuICB9LFxuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJwaXhpLmpzXCI6IFwiOC4wLjBcIlxuICB9LFxuICBcImRldkRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJwYXJjZWwtYnVuZGxlclwiOiBcIl4xLjYuMVwiLFxuICAgIFwiQGJhYmVsL2NvcmVcIjogXCJeNy4yMS4zXCIsXG4gICAgXCJAYmFiZWwvcGx1Z2luLXByb3Bvc2FsLWNsYXNzLXByb3BlcnRpZXNcIjogXCJeNy4xMC4xXCJcbiAgfSxcbiAgXCJtYWluXCI6IFwiL2luZGV4Lmh0bWxcIlxufSJ9LCIvLmJhYmVscmMiOnsiY29kZSI6IntcbiAgXCJwcmVzZXRzXCI6IFtcbiAgICBbXG4gICAgICBcIkBiYWJlbC9wcmVzZXQtZW52XCIsXG4gICAgICB7XG4gICAgICAgIFwidXNlQnVpbHRJbnNcIjogXCJlbnRyeVwiLFxuICAgICAgICBcImNvcmVqc1wiOiBcIjMuMjlcIixcbiAgICAgICAgXCJ0YXJnZXRzXCI6IFwibGFzdCAyIGNocm9tZSB2ZXJzaW9uc1wiXG4gICAgICB9XG4gICAgXVxuICBdLFxuICBcInBsdWdpbnNcIjogW1xuICAgIFwiQGJhYmVsL3BsdWdpbi1wcm9wb3NhbC1jbGFzcy1wcm9wZXJ0aWVzXCJcbiAgXVxufSJ9fSwidmlzaWJsZUZpbGVzIjpbIi9zcmMvaW5kZXguanMiXSwiYWN0aXZlRmlsZSI6Ii9zcmMvaW5kZXguanMifQ%3D%3D&exampleId=custom)

### Expected Behavior

[Playground](https://pixijs.com/7.x/playground?state=eyJmaWxlcyI6eyIvc3JjL2luZGV4LmpzIjp7ImNvZGUiOiJpbXBvcnQgKiBhcyBQSVhJIGZyb20gJ3BpeGkuanMnO1xuXG5jb25zdCBhcHAgPSBuZXcgUElYSS5BcHBsaWNhdGlvbih7IGJhY2tncm91bmQ6ICcjMTA5OWJiJywgcmVzaXplVG86IHdpbmRvdyB9KTtcblxuUElYSS5Bc3NldHMubG9hZChbJ2h0dHBzOi8vcGl4aWpzLmNvbS9hc3NldHMvYnVubnkucG5nJ10pLnRoZW4oKCkgPT4ge1xuICAgIC8vIGNyZWF0ZSBhIG5ldyBTcHJpdGUgZnJvbSBhbiBpbWFnZSBwYXRoXG4gICAgY29uc3QgYnVubnkgPSBQSVhJLlNwcml0ZS5mcm9tKCdodHRwczovL3BpeGlqcy5jb20vYXNzZXRzL2J1bm55LnBuZycpO1xuICAgIGNvbnN0IHdpZHRoID0gYnVubnkud2lkdGg7XG4gICAgY29uc3QgaGVpZ2h0ID0gYnVubnkuaGVpZ2h0O1xuXG4gICAgY29uc3QgdGFyZ2V0ID0gUElYSS5SZW5kZXJUZXh0dXJlLmNyZWF0ZSh7IHdpZHRoLCBoZWlnaHQgfSk7XG4gICAgYXBwLnJlbmRlcmVyLnJlbmRlcihidW5ueSwgeyByZW5kZXJUZXh0dXJlOiB0YXJnZXQgfSk7XG5cbiAgICBjb25zdCBzID0gUElYSS5TcHJpdGUuZnJvbSh0YXJnZXQpO1xuICAgIHMudGludCA9IDB4ZmYwMDAxO1xuXG4gICAgYXBwLnJlbmRlcmVyLmV4dHJhY3QuYmFzZTY0KHMsICdpbWFnZS9wbmcnKS50aGVuKGltYWdlID0%2BIHtcbiAgICAgICAgY29uc3QgaW1nID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnaW1nJyk7XG4gICAgICAgIGltZy5zcmMgPSBpbWFnZTtcbiAgICAgICAgaW1nLndpZHRoID0gMjAwO1xuICAgICAgICBpbWcuaGVpZ2h0ID0gMjAwO1xuICAgICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGltZyk7XG4gICAgfSk7XG59KTsifSwiL3NyYy9zdHlsZXMuY3NzIjp7ImNvZGUiOiJib2R5IHsgbWFyZ2luOiAwOyBvdmVyZmxvdzogaGlkZGVuOyB9In0sIi9pbmRleC5odG1sIjp7ImNvZGUiOiJcbjwhRE9DVFlQRSBodG1sPlxuICA8aHRtbD5cbiAgPGhlYWQ%2BXG4gIDx0aXRsZT5QaXhpSlMgUGxheWdyb3VuZDwvdGl0bGU%2BXG4gIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiIC8%2BXG4gIDxsaW5rIHJlbD1cInN0eWxlc2hlZXRcIiBocmVmPVwic3JjL3N0eWxlcy5jc3NcIj5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2NyaXB0IHNyYz1cInNyYy9pbmRleC5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuPC9odG1sPiJ9LCIvcGFja2FnZS5qc29uIjp7ImNvZGUiOiJ7XG4gIFwic2NyaXB0c1wiOiB7XG4gICAgXCJzdGFydFwiOiBcInBhcmNlbCBpbmRleC5odG1sIC0tb3BlblwiLFxuICAgIFwiYnVpbGRcIjogXCJwYXJjZWwgYnVpbGQgaW5kZXguaHRtbFwiXG4gIH0sXG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBpeGkuanNcIjogXCI3LjQuMFwiLFxuICAgIFwiQHBpeGkvZ3JhcGhpY3MtZXh0cmFzXCI6IFwiNy40LjBcIixcbiAgICBcIkBwaXhpL21hdGgtZXh0cmFzXCI6IFwiNy40LjBcIlxuICB9LFxuICBcImRldkRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJwYXJjZWwtYnVuZGxlclwiOiBcIl4xLjYuMVwiLFxuICAgIFwiQGJhYmVsL2NvcmVcIjogXCJeNy4yMS4zXCIsXG4gICAgXCJAYmFiZWwvcGx1Z2luLXByb3Bvc2FsLWNsYXNzLXByb3BlcnRpZXNcIjogXCJeNy4xMC4xXCJcbiAgfSxcbiAgXCJtYWluXCI6IFwiL2luZGV4Lmh0bWxcIlxufSJ9LCIvLmJhYmVscmMiOnsiY29kZSI6IntcbiAgXCJwcmVzZXRzXCI6IFtcbiAgICBbXG4gICAgICBcIkBiYWJlbC9wcmVzZXQtZW52XCIsXG4gICAgICB7XG4gICAgICAgIFwidXNlQnVpbHRJbnNcIjogXCJlbnRyeVwiLFxuICAgICAgICBcImNvcmVqc1wiOiBcIjMuMjlcIixcbiAgICAgICAgXCJ0YXJnZXRzXCI6IFwibGFzdCAyIGNocm9tZSB2ZXJzaW9uc1wiXG4gICAgICB9XG4gICAgXVxuICBdLFxuICBcInBsdWdpbnNcIjogW1xuICAgIFwiQGJhYmVsL3BsdWdpbi1wcm9wb3NhbC1jbGFzcy1wcm9wZXJ0aWVzXCJcbiAgXVxufSJ9fSwidmlzaWJsZUZpbGVzIjpbIi9zcmMvaW5kZXguanMiXSwiYWN0aXZlRmlsZSI6Ii9zcmMvaW5kZXguanMifQ%3D%3D)

### Steps to Reproduce

See example code.

### Environment

- **`pixi.js` version**: *8.0.0*
- **Browser & Version**: *any*
- **OS & Version**: *any*

**Comment by GoodBoyDigital** [comment]
fixed by #10292 👍
