### ISSUE TITLE
Bug: API Documentation URLs Leading to 403 Errors

### ISSUE THREAD

**Issue by hansnow** [pixijs/pixijs#10273]
### Current Behavior

I've recently encountered an issue with the PixiJS API documentation that seems to have impacted accessibility via search engines such as Google and Bing. It appears that there has been a bulk replacement of URL paths, changing from /dev/docs/* to /release/docs/*. This modification has inadvertently resulted in many developers, including myself, facing 403 errors when attempting to access documentation pages through search engine results.

For instance:

Accessible URL: https://pixijs.download/release/docs/PIXI.Text.html
Inaccessible URL (leads to a 403 error): https://pixijs.download/dev/docs/PIXI.Text.html
This situation is quite frustrating and I believe it has already affected numerous developers who rely on search engines to find documentation.

### Expected Behavior

The links in the search engine should be able to open normally.

### Steps to Reproduce

try to search `pixijs text` in search engine

### Environment

This issue is unrelated to the environment.

### Possible Solution

To address this issue, I would like to suggest the following actions:

Submit a new sitemap to search engines to expedite the indexing of the updated URLs, ensuring developers are directed to the correct pages.
Implement redirects from /dev/docs/* to /release/docs/* instead of simply returning a 403 error. This would provide a smoother transition for users navigating from outdated links.
I understand that managing such a vast documentation can be challenging, but these changes could significantly improve the user experience for the PixiJS developer community. Thank you for considering my suggestions and for your continued efforts in maintaining and improving PixiJS.

**Comment by bigtimebuddy** [comment]
Thanks for letting us know. I have submitted to Google to re-index which should take a day or so. This will get sorted out shortly. A sitemap would be a good thing for us to generate for the docs in the future.

**Comment by dmitriar** [comment]
As for now, both new and old URLs return 403 error. Please fix that.

**Comment by bigtimebuddy** [comment]
The links to these docs has changed:

* https://pixijs.download/release/docs/scene.Text.html
* https://pixijs.download/dev/docs/scene.Text.html
