### ISSUE TITLE
Bug: [v8 regression] Graphics Mask doesn't always update when clearing and redrawing

### ISSUE THREAD

**Issue by leia-uwu** [pixijs/pixijs#10290]
### Current Behavior

Graphics Container mask doesn't update when clearing the graphics and redrawing it
as a workaround I need to set the container mask to null, redraw the graphics, and set it back to the graphics object

### Expected Behavior

Container mask should update when graphics is redrawed (as it did in v7)

### Steps to Reproduce

Create a container, add something to it, and a graphics mask
then redraw the graphics mask

### Environment

- **pixi.js**: v8.0.0
- **Browser & Version**: reproduced on latest chromium (122) and firefox (123)
- **OS & Version**: Arch linux
- **Running Example**: [pixi playground](https://pixijs.com/playground?state=eyJmaWxlcyI6eyIvc3JjL2luZGV4LmpzIjp7ImNvZGUiOiJpbXBvcnQgeyBBcHBsaWNhdGlvbiwgQXNzZXRzLCBDb250YWluZXIsIFNwcml0ZSwgR3JhcGhpY3MgfSBmcm9tICdwaXhpLmpzJztcblxuKGFzeW5jICgpID0%2BXG57XG4gICAgLy8gQ3JlYXRlIGEgbmV3IGFwcGxpY2F0aW9uXG4gICAgY29uc3QgYXBwID0gbmV3IEFwcGxpY2F0aW9uKCk7XG5cbiAgICAvLyBJbml0aWFsaXplIHRoZSBhcHBsaWNhdGlvblxuICAgIGF3YWl0IGFwcC5pbml0KHsgYmFja2dyb3VuZDogJyMxMDk5YmInLCByZXNpemVUbzogd2luZG93IH0pO1xuXG4gICAgLy8gQXBwZW5kIHRoZSBhcHBsaWNhdGlvbiBjYW52YXMgdG8gdGhlIGRvY3VtZW50IGJvZHlcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGFwcC5jYW52YXMpO1xuXG4gICAgLy8gQ3JlYXRlIGFuZCBhZGQgYSBjb250YWluZXIgdG8gdGhlIHN0YWdlXG4gICAgY29uc3QgY29udGFpbmVyID0gbmV3IENvbnRhaW5lcigpO1xuXG4gICAgYXBwLnN0YWdlLmFkZENoaWxkKGNvbnRhaW5lcik7XG5cbiAgICAvLyBMb2FkIHRoZSBidW5ueSB0ZXh0dXJlXG4gICAgY29uc3QgdGV4dHVyZSA9IGF3YWl0IEFzc2V0cy5sb2FkKCdodHRwczovL3BpeGlqcy5jb20vYXNzZXRzL2J1bm55LnBuZycpO1xuXG4gICAgLy8gQ3JlYXRlIGEgNXg1IGdyaWQgb2YgYnVubmllcyBpbiB0aGUgY29udGFpbmVyXG4gICAgZm9yIChsZXQgaSA9IDA7IGkgPCAyNTsgaSsrKVxuICAgIHtcbiAgICAgICAgY29uc3QgYnVubnkgPSBuZXcgU3ByaXRlKHRleHR1cmUpO1xuXG4gICAgICAgIGJ1bm55LnggPSAoaSAlIDUpICogNDA7XG4gICAgICAgIGJ1bm55LnkgPSBNYXRoLmZsb29yKGkgLyA1KSAqIDQwO1xuICAgICAgICBjb250YWluZXIuYWRkQ2hpbGQoYnVubnkpO1xuICAgIH1cblxuICAgIC8vIE1vdmUgdGhlIGNvbnRhaW5lciB0byB0aGUgY2VudGVyXG4gICAgY29udGFpbmVyLnggPSBhcHAuc2NyZWVuLndpZHRoIC8gMjtcbiAgICBjb250YWluZXIueSA9IGFwcC5zY3JlZW4uaGVpZ2h0IC8gMjtcblxuICAgIC8vIENlbnRlciB0aGUgYnVubnkgc3ByaXRlcyBpbiBsb2NhbCBjb250YWluZXIgY29vcmRpbmF0ZXNcbiAgICBjb250YWluZXIucGl2b3QueCA9IGNvbnRhaW5lci53aWR0aCAvIDI7XG4gICAgY29udGFpbmVyLnBpdm90LnkgPSBjb250YWluZXIuaGVpZ2h0IC8gMjtcblxuICAgIGNvbnN0IG1hc2sgPSBuZXcgR3JhcGhpY3MoKTtcbiAgICBjb250YWluZXIubWFzayA9IG1hc2s7XG4gICAgbGV0IHNpemUgPSAxMDA7XG4gICAgLy8gTGlzdGVuIGZvciBhbmltYXRlIHVwZGF0ZVxuICAgIGFwcC50aWNrZXIuYWRkKCh0aW1lKSA9PlxuICAgIHtcbiAgICAgICAgc2l6ZSArPSAxMCAqIHRpbWUuZGVsdGFUaW1lO1xuICAgICAgICBzaXplICU9IDQwMDtcbiAgICAgICAgLy8gdW5jb21tZW50IGl0IHRvIG1ha2UgdGhlIG1hc2sgYWN0dWFsbHkgdXBkYXRlXG4gICAgICAgIC8vIGNvbnRhaW5lci5tYXNrID0gbnVsbDtcbiAgICAgICAgbWFzay5jbGVhcigpO1xuICAgICAgICBtYXNrLnJlY3QoKGFwcC5zY3JlZW4ud2lkdGggLyAyKSAtIDIwMCwgKGFwcC5zY3JlZW4uaGVpZ2h0IC8gMikgLSAyMDAsIHNpemUsIHNpemUpO1xuICAgICAgICBtYXNrLmZpbGwoKTtcbiAgICAgICAgLy8gY29udGFpbmVyLm1hc2sgPSBtYXNrO1xuICAgIH0pO1xufSkoKTtcbiJ9LCIvc3JjL3N0eWxlcy5jc3MiOnsiY29kZSI6ImJvZHkgeyBtYXJnaW46IDA7IG92ZXJmbG93OiBoaWRkZW47IH0ifSwiL2luZGV4Lmh0bWwiOnsiY29kZSI6IlxuPCFET0NUWVBFIGh0bWw%2BXG4gIDxodG1sPlxuICA8aGVhZD5cbiAgPHRpdGxlPlBpeGlKUyBQbGF5Z3JvdW5kPC90aXRsZT5cbiAgPG1ldGEgY2hhcnNldD1cIlVURi04XCIgLz5cbiAgPGxpbmsgcmVsPVwic3R5bGVzaGVldFwiIGhyZWY9XCJzcmMvc3R5bGVzLmNzc1wiPlxuPC9oZWFkPlxuPGJvZHk%2BXG4gIDxzY3JpcHQgc3JjPVwic3JjL2luZGV4LmpzXCI%2BPC9zY3JpcHQ%2BXG48L2JvZHk%2BXG48L2h0bWw%2BIn0sIi9wYWNrYWdlLmpzb24iOnsiY29kZSI6IntcbiAgXCJzY3JpcHRzXCI6IHtcbiAgICBcInN0YXJ0XCI6IFwicGFyY2VsIGluZGV4Lmh0bWwgLS1vcGVuXCIsXG4gICAgXCJidWlsZFwiOiBcInBhcmNlbCBidWlsZCBpbmRleC5odG1sXCJcbiAgfSxcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwicGl4aS5qc1wiOiBcIjguMC4wXCJcbiAgfSxcbiAgXCJkZXZEZXBlbmRlbmNpZXNcIjoge1xuICAgIFwicGFyY2VsLWJ1bmRsZXJcIjogXCJeMS42LjFcIixcbiAgICBcIkBiYWJlbC9jb3JlXCI6IFwiXjcuMjEuM1wiLFxuICAgIFwiQGJhYmVsL3BsdWdpbi1wcm9wb3NhbC1jbGFzcy1wcm9wZXJ0aWVzXCI6IFwiXjcuMTAuMVwiXG4gIH0sXG4gIFwibWFpblwiOiBcIi9pbmRleC5odG1sXCJcbn0ifSwiLy5iYWJlbHJjIjp7ImNvZGUiOiJ7XG4gIFwicHJlc2V0c1wiOiBbXG4gICAgW1xuICAgICAgXCJAYmFiZWwvcHJlc2V0LWVudlwiLFxuICAgICAge1xuICAgICAgICBcInVzZUJ1aWx0SW5zXCI6IFwiZW50cnlcIixcbiAgICAgICAgXCJjb3JlanNcIjogXCIzLjI5XCIsXG4gICAgICAgIFwidGFyZ2V0c1wiOiBcImxhc3QgMiBjaHJvbWUgdmVyc2lvbnNcIlxuICAgICAgfVxuICAgIF1cbiAgXSxcbiAgXCJwbHVnaW5zXCI6IFtcbiAgICBcIkBiYWJlbC9wbHVnaW4tcHJvcG9zYWwtY2xhc3MtcHJvcGVydGllc1wiXG4gIF1cbn0ifSwiL3NhbmRib3guY29uZmlnLmpzb24iOnsiY29kZSI6IntcbiAgICAgICAgICAgICAgICBcImluZmluaXRlTG9vcFByb3RlY3Rpb25cIjogZmFsc2VcbiAgICAgICAgICAgIH0ifX0sInZpc2libGVGaWxlcyI6WyIvc3JjL2luZGV4LmpzIl0sImFjdGl2ZUZpbGUiOiIvc3JjL2luZGV4LmpzIn0%3D)

**Comment by GoodBoyDigital** [comment]
heya! The mask needs to be added to the stage or weirdness ensues :)

Adding the mask Graphics to the stage fixes the issue in the demo. 

Let me know if this is sufficient!

**Comment by leia-uwu** [comment]
That fixed it, thanks!
