### ISSUE TITLE
Virus detected when I try to download PixiJS

### ISSUE THREAD

**Issue by somunaexe** [pixijs/pixijs#10295]
### Current Behavior

![Screenshot 2024-03-08 005234](https://github.com/pixijs/pixijs/assets/120026203/4be99485-0827-44e5-9436-ee34a1e0c22d)

### Expected Behavior

File should be downloadable and virus-free

### Steps to Reproduce

Right Click the production link and click 'save link as'.
Leave the default name then press enter

### Environment

- **`pixi.js` version**: *e.g. 8.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Windows 10*

**Comment by bigtimebuddy** [comment]
Huh. I cannot reproduce this on macOS on Chrome 122. Please provide some more information.

**Comment by Julien-Marcou** [comment]
I can reproduce, but to be fair, I don't think we can do anything about it.

From my tests, it happens with any JavaScript file you try to download using `Right Click` > `Save link as...`

However, if you first open the link in a new tab and then do `Save as...`, it works 🤷‍♂️
