### ISSUE TITLE
Bug: [v8] Rollup export build error after upgrade to v8 - working on v7

### ISSUE THREAD

**Issue by danielbarion** [pixijs/pixijs#10300]
## V8

```
[!] RollupError: Invalid value "umd" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
```

![image](https://github.com/pixijs/pixijs/assets/9615850/eca09a02-5e44-4752-8ea0-d428d91f750b)

## V7

![image](https://github.com/pixijs/pixijs/assets/9615850/5e230e91-933d-4945-aab6-b4496196ef74)

The errors are the v8 updates I did, to test the build I just downgraded the version and it builded.

### Steps to Reproduce

1. `git clone https://github.com/danielbarion/pixi-8-upgrade-build`
2. install the dependencies, e.g: `yarn`
3. run the project on build mode `yarn dev`
4. the project on the main branch will break and not start the server
5. on the `v7` branch it will start the server

### Environment

- **`pixi.js` version**: *8.0.1*
- **Browser & Version**: *all*
- **OS & Version**: * MacOS Ventura 13.2.1*
- **Running Example**: *https://github.com/danielbarion/pixi-8-upgrade-build*

### Additional Information

Don't expect to see anything on the browser, I cloned my study project and removed a lot of things to make the example simpler, so, I'm just starting the application but not rendering anything, also, I keep the Game class as a reference on how I'm using it (not sure if this will help to debug it).

I'm already using the recommended format of import:

```
import { Application, Container, Renderer, Sprite, Text } from 'pixi.js'
```

**Comment by bigtimebuddy** [comment]
I would probably try to look for a Rollup plugin that could statically inline dynamic imports. We are now using dynamic imports which helps tree-shaking and up-front filesize costs for some bundlers. Since we added another big renderer in v8, it's just not practical to load everything at once.

Quick search found this issue:
https://github.com/rollup/rollup/issues/3490

**Comment by danielbarion** [comment]
Thanks for the issue reference @bigtimebuddy, I checked it and ESM on CanIUse: 

![image](https://github.com/pixijs/pixijs/assets/9615850/df99d3c4-7744-4d62-b353-30e5fec2c9af)

The ESM is already supported by ~96% of browsers, and the version range is great.

Changing the build to use `esm` directly looks to be the right approach.

I still have other things broken after migrate to v8 that is mentioned on the following issue: https://github.com/pixijs/pixijs/issues/10299

So, when I run the project, on the browser I get the following error:

```
Uncaught TypeError: Failed to resolve module specifier "@pixi/core". Relative references must start with either "/", "./", or "../".
```

The browser was not able to load the Pixi core, and those are the built files:
![image](https://github.com/pixijs/pixijs/assets/9615850/8977596d-0650-4ef2-9469-a4b930b780cd)

I'll wait for the other issue and keep doing some tests to see how to fix it.

**Comment by danielbarion** [comment]
hey guys, question about v8 and the ESM build, the following code is being included on the top of the build files:

```
import { SCALE_MODES, extensions as extensions$1, ExtensionType as ExtensionType$1, ObjectRenderer, Buffer as Buffer$1, utils, Shader, Program, Matrix as Matrix$1, Geometry as Geometry$1, Texture as Texture$1, groupD8 as groupD8$1, DRAW_MODES } from '@pixi/core';
import { Container as Container$1, Bounds as Bounds$1 } from '@pixi/display';
```

I don't have `@pixi/display` and  `@pixi/core` as dependencies or dev dependencies on my project because I didn't need it on v7, but now it is being included on the build file and when the browser try to load it, I get the following error `Uncaught TypeError: Failed to resolve module specifier "@pixi/core". Relative references must start with either "/", "./", or "../".` because it is not being included on build file.

![image](https://github.com/pixijs/pixijs/assets/9615850/7e5a4eaf-5e48-41e9-b466-b1f3c778035e)

if I define it to load from CDN it works and the error goes away:

```
      paths: {
        '@pixi/core': 'https://cdn.skypack.dev/@pixi/core',
        '@pixi/display': 'https://cdn.skypack.dev/@pixi/display',
      },
```

is this an expected behavior/approach? I would like to not need this map with the CDN to fill all the needs of Pixi on my build... 

can someone please give me some guidance about it? thanks!

**Comment by danielbarion** [comment]
the issue is that `@pixi/tilemap` and other plugins are still on v7, so they need to be upgraded, after that, the build will work as expected.

Closing as there's nothing to be done here by Pixi team.

**Comment by StoneCypher** [comment]
To resolve this, in your rollup config:

```javascript
const config = {

  output: {
    inlineDynamicImports: true
  }

}
```
