### ISSUE TITLE
Bug: BindGroup setResource called with null

### ISSUE THREAD

**Issue by nw-b** [pixijs/pixijs#10304]
### Current Behavior

When rendering a scene with textures that were previously unloaded, then loaded again:

WebGPU renderer tries to call BindGroup.setResource with `null` resource.
WebGL renderer tries to call applyStyleParams with `null` style.

<img width="881" alt="Screenshot 2024-03-09 at 3 38 37 PM" src="https://github.com/pixijs/pixijs/assets/1254417/de47ac2a-6adb-4f93-8fe7-b2b9421ba118">

<img width="863" alt="Screenshot 2024-03-09 at 3 39 35 PM" src="https://github.com/pixijs/pixijs/assets/1254417/dde6c0c5-5537-42f7-800e-ef257a860407">

### Expected Behavior

No errors, or an explanatory error if I am doing something fundamentally invalid.

### Steps to Reproduce

Having trouble narrowing down what is precisely causing this. 

In my game, it happens only when the user has left one room and is loading into another, which causes the previous room's assets to get unloaded (Assets.unloadBundle), and then the new room's assets to be loaded (Assets.add/loadBundle). Some of these assets may be the same in both rooms, so I am wondering if there is an issue with Asset unloading on v8. This worked without any error in v7.

### Environment

- **`pixi.js` version**: 8.0.1
- **Browser & Version**: Chrome 122.0.6261.112
- **OS & Version**: macOS Sonoma 14.3.1

**Comment by GoodBoyDigital** [comment]
Thanks for sharing @nw-b ! will take a lok at this one today

**Comment by GoodBoyDigital** [comment]
heya, definitely looks like a destroyed texture is being used in the main renderer! 

could you try separating the bundles so they don't overlap please? just for a test? thanks!
