### ISSUE TITLE
Bug: Some link in https://pixijs.download/v8.0.1/docs/rendering.AutoDetectOptions.html not working

### ISSUE THREAD

**Issue by hlevring** [pixijs/pixijs#10308]
### Current Behavior

WebGLOptions / WebGPUOptions option links are not working in this page
https://pixijs.download/v8.0.1/docs/rendering.AutoDetectOptions.html

One shows no options
https://pixijs.download/v8.0.1/docs/rendering.WebGLOptions.html

and the other one returns an error
https://pixijs.download/v8.0.1/docs/global.html#WebGPUOptions

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>2BT1Z6E52KCNZJ22</RequestId>
<HostId>GK/gfKByW8fnMYR4A89i4bt+gWfSKJ33PQWfOXTtohPztMia48m6+8AH1XSeilvIPLKM0J/JaJY=</HostId>
</Error>

### Expected Behavior

Links should work

### Steps to Reproduce

1) Goto https://pixijs.download/v8.0.1/docs/rendering.AutoDetectOptions.html
2) Click links for WebGLOptions
3) [webGLOptions are missing](https://cloud.videocom.com/media/fi_01HRPT3FHZPKFPEBG75M3K0EVE)
--------------------------------
1) Goto https://pixijs.download/v8.0.1/docs/rendering.AutoDetectOptions.html
2) Click link for WebGPUOptions
3) [Page has error](https://cloud.videocom.com/media/fi_01HRPT5BCPHMEPWEYSFGS6EJTJ)

### Environment

Win 11
Pixi v8.0.1
Chrome 122

**Comment by Zyie** [comment]
Thanks for raising this, will fix asap
