### ISSUE TITLE
Bug: [v8] `text.style.fill === null` when `TextStyle` is reused instead of `TextStyleOptions`

### ISSUE THREAD

**Issue by joergplewe** [pixijs/pixijs#10328]
### Current Behavior

In case a `TextStyle` object  - in favor of a `TextStyleOptions` type - is used to create multiple `Text` objects, these may loose their `style.fill` property, which e.g. makes tinting impossible. 

### Expected Behavior

`Text` should well-behave concerning it's way of construction.

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/-V-yqUNla6o8sOKEEKRCk

See that tinting gets lost after 2 seconds and recreation of scenegraph content.

### Environment

- **`pixi.js` version**: 8.0.2
- **Browser & Version**: any
- **OS & Version**: any
- **Running Example**: https://www.pixiplayground.com/#/edit/-V-yqUNla6o8sOKEEKRCk

### Possible Solution

I suspect this has to do with caching and reference counting of ressources.

**Comment by bigtimebuddy** [comment]
Thanks for reporting @joergplewe. This indeed looks like a bug.

**Comment by GoodBoyDigital** [comment]
Hey chaps, looking at the code - currently we destroy a texture style when we destroy a text.
will make it optional (like textures and their sources!)
