### ISSUE TITLE
Performance: [v8 regression] `Container.destroy()` is very slow on crowded containers

### ISSUE THREAD

**Issue by joergplewe** [pixijs/pixijs#10345]
### Current Behavior

Admired developers,

I frequently have to clear crowded containers (>100000 children) and observed that `Container.destroy(true)` can take several seconds. 
Compared to my v7 code, where `destroy()` wasn't noticable at all (using `ParticleContainer`, to be fair).

Clearing the container 'by hand' before calling `destroy()` speeds up the process significantly, which makes me think it might be a bug.

```
myContainer.removeChildren().forEach(child => child.destroy(true));
``` 

### Expected Behavior

`destroy()` shouldn't be slower than clearing a `Container` by hand.

As fast as `ParticleContainer` would be great :).

### Steps to Reproduce

Use playground https://www.pixiplayground.com/#/edit/zFuIcJIth6M6QmC2IAjR9

After 200 frames, the content will be destroyed and starting to reconstruct. 
`largeContainer.destroy(true);` may halt rendering for a couple of seconds.

Setting `MAKE_IT_FAST_AGAIN=true` clears `largeContainer` manually before destruction, bringing up speed again, 

### Environment

- **`pixi.js` version**: 8.0.2
- **Browser & Version**: any
- **OS & Version**: any
- **Running Example**: https://www.pixiplayground.com/#/edit/zFuIcJIth6M6QmC2IAjR9

### Possible Solution

There is a workaround by clearing the container upfront `destroy()`:

```
myContainer.removeChildren().forEach(child => child.destroy(true));
```

**Comment by GoodBoyDigital** [comment]
heya @joergplewe ! can i ask, how does this compare to a regular Pixi v7 Container? thanks!

**Comment by joergplewe** [comment]
Hi  @GoodBoyDigital !

I prepared a comparable playground for v7: https://www.pixiplayground.com/#/edit/YVV1kTr_pTz9VZKNOQFpv

v7 `destroy()` does not even take a blink.
The v8 sample is much slower even with the workaround `MAKE_IT_FAST_AGAIN=true`.

**Comment by joergplewe** [comment]
is this comparable to https://github.com/pixijs/pixijs/issues/10377 ?

**Comment by albertreed** [comment]
I'm new to Pixi, but at least for my application calling `application.destroy()` sits and spins until the tab crashes. Tried the OP's suggestion (on `stage`), but that also hangs.

**Comment by GoodBoyDigital** [comment]
much faster now :D https://github.com/pixijs/pixijs/pull/10505
