### ISSUE TITLE
Bug: [v8.0.2] Sprite not updated correctly when its texture's frame is changed

### ISSUE THREAD

**Issue by TheRamsWay** [pixijs/pixijs#10342]
### Current Behavior

When changing the size of the frame on a sprite's texture, the sprite gets updated and resized to the texture's size. This does work, but not when the update is done in an event listener or a timeout for example: the values are right (the sprite's `width` and `height` are set to the right numbers), but the sprite doesn't get re-rendered and the scale stays relative to the previous texture size.

### Expected Behavior

The sprite's visible size should actually correspond to its `width`, `height` and `scale` after the texture gets updated, and it probably should be re-rendered automatically as well.

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/JE-Ln_Uv9S9l13LY5HkM4
In this example, the texture's frame goes from 16x16 px to 32x32. Clicking the sprite is supposed to resize it, but I have to manually call `render` for it to be visible and the sprite is still 16x16 px, despite its width and height being changed to 32 and its scale still being 1. Replacing the event listener by a direct call to `upd()` resizes the sprite correctly.

### Environment

- **`pixi.js` version**: 8.0.2
- **Browser & Version**: Firefox 123, Edge 121
- **OS & Version**: Windows 10 22H2

**Comment by ivanpopelyshev** [comment]
FIx is being discussed here: #10352
