### ISSUE TITLE
Bug: [v8 regression] moving a crowded `Container` drastically cuts performance

### ISSUE THREAD

**Issue by joergplewe** [pixijs/pixijs#10353]
### Current Behavior

I use to have big containers (>100000 children) which need to be moved around (like panning a map or so).
As soon as the container is moved (`myContainer.position.set(x,y);`) the framerate drops significantly.
I did not observe this effect in v7.

I also noticed that this effect happens with both WebGL and WebGPU, but with WebGL it is less rude, hence still significant compared to v7.  

### Expected Behavior

In my (naive) understanding, moving a `Container` should only touch a single matrix, so framerate must not be affected.
As it was in v7.

### Steps to Reproduce

Use https://www.pixiplayground.com/#/edit/-YSyps117HwGc2RU_AG0p

Either play with constant `CUT_PERFORMANCE` or set it to `false` and drag the mouse pointer around. Observe drop in framerate.

### Environment

- **`pixi.js` version**: 8.0.2
- **Browser & Version**: Chrome
- **OS & Version**: any
- **Running Example**: https://www.pixiplayground.com/#/edit/-YSyps117HwGc2RU_AG0p

**Comment by GoodBoyDigital** [comment]
hey @joergplewe do you have a v7 example of this being slower? is this being compared to a v7 `ParticalContainer` or regular `Container`?

**Comment by GoodBoyDigital** [comment]
a bit more context
- Regular container should be faster on v7 than v8 (or this _is_ a regression)
- ParticleContainer does all transforms on the GPU so will be faster.

**Comment by joergplewe** [comment]
As always no simple answer. 
https://www.pixiplayground.com/#/edit/GQGWEeMK8aMzR2kpMlV5_

Ok, `ParticleContainer` in fact is not affected by moving it. v7 regular `Container` is.
And v8 `Container` is definitely way more powerful then v7, which makes them hard to compare and benchmark.

I tried to measure them both with 200000 children using the regular `Container`:
* v7 drops from 22 FPS to 17
* v8 drops from >>60 FPS to 29 (v8 falls below 60 FPS unmoved only at ~500000 children)

**Comment by GoodBoyDigital** [comment]
cool! ok, that makes sense!

we will make a particle container soon :)

for v8 you also have the renderGroup option:

https://www.pixiplayground.com/#/edit/i5fhM3waCCkMSaOnVD2va

this will be super fast as long as things inside the container remain static!

**Comment by joergplewe** [comment]
Ah thanks for the hint. I will investigate.
I still feel that the relatively huge performance drop in v8 is suspicious, isn't it?

**Comment by joergplewe** [comment]
Ok, thx, I think I got it. 
From the numbers above I'd conclude that the v8 renderer is 29/17 times faster than v7 :)

Closing the issue then.

**Comment by xpluscal** [comment]
Following up on this: We have a container also with about 3-10.000 children.
Container is set to isRenderGroup.

Panning the container, aka translating it by dragging, causes severe drops in fps - what's a good approach to solving those issues?
