### ISSUE TITLE
Feature Request: [v8] Is there any way to pass a canvas instance to the new WebGLRenderer?

### ISSUE THREAD

**Issue by JetLua** [pixijs/pixijs#10360]
#### v8
```js
const renderer = new WebGLRenderer();
await renderer.init();

// Add the renderer to the stage
document.body.appendChild(renderer.canvas);
```

Due to the **WeChat Mini Program** environment, I'm unable to execute the operation `document.body.appendChild(renderer.canvas)`. 

So I hope to pass the canvas instance to the WebGLRenderer via parameters as in previous versions.

#### v6
```js
const renderer = new PIXI.Renderer({
  view: canvas,
 ...
})
```

**Comment by Zyie** [comment]
Hey @JetLua all renderer options have been moved to the `init` function

```ts
renderer.init({
  canvas: canvas,
 ...
})
```

**Comment by JetLua** [comment]
> Hey @JetLua all renderer options have been moved to the `init` function
> 
> ```ts
> await renderer.init({
>   canvas: canvas,
>  ...
> })
> ```

Thanks !!!
