### ISSUE TITLE
[v8] Cannot read property 'addRenderable' of undefined

### ISSUE THREAD

**Issue by JetLua** [pixijs/pixijs#10366]
### Description

I tried using `@pixi/unsafe-eval@7` and `pixi.js@8`, but I found it doesn't work.
```
Current environment does not allow unsafe-eval, please use pixi.js/unsafe-eval module to enable support.
```

**Comment by bigtimebuddy** [comment]
Try including `pixi.js/unsafe-eval`. All packages are now shipped with v8.

**Comment by JetLua** [comment]
> Try including `pixi.js/unsafe-eval`. All packages are now shipped with v8.

@bigtimebuddy Thank you, it's resolved.

When I run the following code in **WeChat**, I encounter an error.

```js

const renderer = new PIXI.WebGLRenderer()

renderer.init({
  canvas,
  antialias: true,
  preferWebGLVersion: 1,
  backgroundColor: 0x171a24,
}).then(() => {
  const g = new PIXI.Graphics()

  g.fill(0xffc333)
  g.rect(0, 0, 100, 100)

  stage.addChild(g)

  renderer.render({container: stage})
})
```

```
Cannot read property 'addRenderable' of undefined
```

I did some basic research and found that the error stems from the following code snippet. Additionally, I added code locally to print variable information.

https://github.com/pixijs/pixijs/blob/d4cb3d10fb8e50be8fc4e41e9d2844831df0a79e/src/scene/container/utils/buildInstructions.ts#L73-L75

```js
console.log(rp)
console.log(container.renderPipeId)
```

output:

<img width="548" alt="image" src="https://github.com/pixijs/pixijs/assets/6738986/9debc883-1e5a-4c68-b871-365c19f9263f">


I found that there is no `graphics` property in `renderPipes`, so `rp[container.renderPipeId]` is `undefined`.

I'm not entirely sure if this is a situation unique to **WeChat**. 

@GoodBoyDigital

**Comment by GoodBoyDigital** [comment]
thanks for sharing! il take a look

**Comment by GoodBoyDigital** [comment]
Hey there! The issue is that the extensions are dynamically loaded when via `autoDetectRenderer`

the quick fix for now would be to do the following:

```
const renderer = await autoDetectRenderer({
    preference:'webgl'
})
```

we will look into adding a `await createWebGLRenderer()` and `await createWebGPURenderer()` functions that install all the plugins and things!

**Comment by kencanak** [comment]
> > Try including `pixi.js/unsafe-eval`. All packages are now shipped with v8.
> 
> @bigtimebuddy hey, I tried to import `pixi.js/unsafe-eval` however, I am still getting the following error.
> 
> I am using Webpack 5 as bundler, so i have resolution config set as follows:
> 
> ```
> 'pixi.js/unsafe-eval': path.resolve(__dirname, './node_modules/pixi.js/lib/unsafe-eval/init.js'),
> ```
> 
> then in the app code:
> 
> ```
> import 'pixi.js/unsafe-eval';
> import { Container, Application, Ticker, Graphics } from 'pixi.js';
> import * as PIXI from 'pixi.js';
> ```
> 
> also tried
> 
> ```
> import { Container, Application, Ticker, Graphics } from 'pixi.js';
> import * as PIXI from 'pixi.js';
> import 'pixi.js/unsafe-eval';
> ```
> 
> any clue, why it's still throwing error? <img alt="Screenshot 2024-05-20 at 9 12 20 PM" width="933" src="https://private-user-images.githubusercontent.com/17525206/332076022-cb0567da-4a0a-4658-acd5-3d2ca857d05d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTE3OTYsIm5iZiI6MTcxNjIxMTQ5NiwicGF0aCI6Ii8xNzUyNTIwNi8zMzIwNzYwMjItY2IwNTY3ZGEtNGEwYS00NjU4LWFjZDUtM2QyY2E4NTdkMDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEzMjQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3Zjc5NDRlNjFlNjRmZGRkYWFiYzc1ODhkYjVkMjVhYjdkNGIwMGZlODE5OGIwN2ExMzYyYWZkMDAyYmQwMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fn3X5w_maf-4a3f0WqBJCmS5t-zbcSYtlztDCjhiv8A">
> 
> Thank you

apologise, please ignore my question. i did a stupid mistake.
