### ISSUE TITLE
[V8] Error with `new Sprite(null)`

### ISSUE THREAD

**Issue by adam-savard** [pixijs/pixijs#10374]
### Current Behavior

When invoking `new Sprite(null)`, there is an error that occurs because the sprite assumes that `options` can be deconstructed. 

### Expected Behavior

A blank sprite should be produced

### Steps to Reproduce

`new Sprite(null)`

### Environment

- **`pixi.js` version**: 8.0.4
- **Browser & Version**: Chrome 122
- **OS & Version**: Fedora 39

**Comment by GoodBoyDigital** [comment]
thanks for posting, does `new Sprite()` work?

**Comment by GoodBoyDigital** [comment]
Hey @adam-savard , just did a quick check:

`new Sprite()` works ok.

I would say `new Sprite(null)` is akin to passing in bad constructor data, so will not class this one as a bug. 

Closing for now, but happy to discuss!
