### ISSUE TITLE
Bug: v8.0.3+ addressMode is repeat by default

### ISSUE THREAD

**Issue by Blueyescat** [pixijs/pixijs#10385]
v8.0.3 started repeating textures because addressMode is repeat by default. I don't think this is intentional?

**Playground**: https://www.pixiplayground.com/#/edit/LC7WO3PbGzSuqSllshe3H

`texture.source.addressMode = "clamp-to-edge"` does work

**Comment by GoodBoyDigital** [comment]
fixed by #10408 :D
