### ISSUE TITLE
Feature Request: Put again sync methods in ExtractSystem

### ISSUE THREAD

**Issue by Kevoting** [pixijs/pixijs#10380]
### Description

Hello!
Is it possible to add synchronous methods to ExtractSystem again and not async mandatory like in pixi 6.0.0?
The reason for this is because being asynchronous I have desync issues
I know I can create a fork, but I'm just asking if it can be added officially

**Comment by GoodBoyDigital** [comment]
heya, this is not currently planned. Pulling data from WebGPU can be an async operation. 
Hopefully not to much of a deal to modify your code to use async / await
