### ISSUE TITLE
Bug: TexturePacker anchor point ignored

### ISSUE THREAD

**Issue by Durss** [pixijs/pixijs#10398]
### Current Behavior

Since migrating from v7 to v8 it seems like the anchor points defined on TexturePacker get ignored.
Until then the Sprite was offset accordingly, now it's not anymore.

Is it a regression or is there a flag or something I should set to enable this?
I see nothing about this in the migration guide

### Expected Behavior

The sprite rendering should be offset accordingly to the TexturePacker's anchor.

### Steps to Reproduce

set this as the anchor of a sprite row on a spritesheet.json:
```
"anchor": {"x":1,"y":1}
```

Setting the sprite on coordinats (100, 200) should palce the bottom right corner of the object on the given coordinates.

### Environment

- **`pixi.js` version**: *e.g. 8.0.4*

**Comment by GoodBoyDigital** [comment]
hey there! would you mind creating an example for us to debug pls? thanks!

**Comment by Durss** [comment]
Here is a simple repro:
https://www.pixiplayground.com/#/edit/1Np1gxGq4RMcI6pjozCu0

The anchor point of the sprites are all on their bottom/left.
When set the sprite at the center of the screen we should get the anchor point of the sprite at the center.
But no matter the anchor point configured we always get the top/left corner of the sprite on the center of the screen

**Comment by GoodBoyDigital** [comment]
perfect! thanks @Durss
