### ISSUE TITLE
Bug: Assets.load for BitmapFonts broken ?

### ISSUE THREAD

**Issue by Durss** [pixijs/pixijs#10397]
### Current Behavior

I'm rather new to PixiJS, sorry if I missed something obvious.

I'm migrating from v7 to v8 am having an issue with fonts loading.

I'm basically trying to load BitmapFonts from XML/PNG files as done in this page:
https://pixijs.com/8.x/examples/text/bitmap-text

But it simply fails with following warning:
> PixiJS Warning:  [Assets] https://pixijs.com/assets/bitmap-font/desyrel.xml could not be loaded as we don't know how to parse it, ensure the correct parser has been added

Given this page, this type of file should be supported :
https://pixijs.com/8.x/guides/components/assets?_highlight=parser#the-assets-package
I tried with a .FNT file with no more success.

Only loading an OTF/TTF file works but, if i understood things correctly it wouldn't be as efficient for my case so I'd rather not do this.

### Expected Behavior

Font should load properly

### Steps to Reproduce

Simply call this:
await Assets.load('https://pixijs.com/assets/bitmap-font/desyrel.xml');

### Environment

- **`pixi.js` version**: *8.0.4*

**Comment by Durss** [comment]
Ok, I think I found my way with BitmapFont.install()
Maybe the example and docs are simply not up to date ?

**Comment by GoodBoyDigital** [comment]
hey there! the example is correct - would you mind posting a playground of your code please? Happy to debug!

**Comment by GoodBoyDigital** [comment]
ooooh! actually i found it. 

Try loading the font after the `init` function for the renderer. It will then load correctly.

cc @Zyie would be good to thing of a nice way around this as its tripped a few people up! haha
