### ISSUE TITLE
Bug: The content of multiple texts overlaps with each other.

### ISSUE THREAD

**Issue by rain7788** [pixijs/pixijs#10406]
### Current Behavior

8.0-8.0.4, use the official website's text demo. If you remove the style and use the default style, let multiple texts use different content, and then refresh the webpage multiple times, you will find a high probability that their content will overlap with each other.

### Expected Behavior

ellipsis

### Steps to Reproduce

ellipsis

### Environment

- **`pixi.js` version**: *e.g. 8.0.4*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by rain7788** [comment]
<img width="938" alt="157A96AD-DD72-47E1-8E61-294898521709" src="https://github.com/pixijs/pixijs/assets/94547185/8816e05b-6879-4aba-af1e-8761a67f87d8">
<img width="646" alt="6464AD2D-AA71-4EE9-A1C5-0941F12BA0B4" src="https://github.com/pixijs/pixijs/assets/94547185/d9cdeca3-241a-4ffe-ab5c-6b5617227eb4">

**Comment by rain7788** [comment]
<img width="1531" alt="image" src="https://github.com/pixijs/pixijs/assets/94547185/3bd02d5c-afc4-42fe-b6c3-541f8a8552b6">

**Comment by GoodBoyDigital** [comment]
hey there @rain7788 , this seems to work ok for me? 

https://www.pixiplayground.com/#/edit/ed1zROx0o9BR8yNhSMORj

let me know if there is a specific version you are using! cheers!

**Comment by GoodBoyDigital** [comment]
struggling to repro! haha do i need to continually hit refresh on the browser? 
could you try please @bigtimebuddy @Zyie ? cheers!

**Comment by rain7788** [comment]
Thank you for your reply.
I just tried and found that he works very well.
But I am certain that there have been issues before, and I have tried versions 8.0-8.0.5 all of which are like this. The only difference is that the company's network was used before, but now it is the home network, which is the only difference between these two tests. So I'm not sure if it's caused by our company's network.
But on version 7. x, it's normal no matter where it is.

**Comment by GoodBoyDigital** [comment]
thanks for clarifying @rain7788 ! Would you mind testing this again at your work pls?

**Comment by rain7788** [comment]
I am on vacation, and I will test again in about two days. Thank you. @GoodBoyDigital

**Comment by rain7788** [comment]
https://github.com/pixijs/pixijs/assets/94547185/5fb0b976-8704-4186-afe7-b355afc10215

@GoodBoyDigital 
I have come to the company, which looks very strange. Everything is normal at home, but when I go to the company, it's just like this. I use my own MacBook.

**Comment by rain7788** [comment]
@GoodBoyDigital 
I found the difference between them!
I am using the same computer, MacBook Pro.
When I unplugged the power and used the battery, everything was fine! Whether running locally or pixiplayground.
However, when I use the power and then reload the webpage, it will display incorrectly.
I didn't use the power at home that day, so he was normal.

**Comment by rain7788** [comment]
By the way, when using the battery, my computer will enable low battery mode.

**Comment by GoodBoyDigital** [comment]
wow, this is so strange one!
I have bumped the version in the playground to 8.0.1

https://www.pixiplayground.com/#/edit/ed1zROx0o9BR8yNhSMORj

could you try this pls? It should be webGL now. This may be a WebGPU issue? lets see!

**Comment by rain7788** [comment]
It works well in version 8.1.0! Currently everything seems normal, thank you!

**Comment by rain7788** [comment]
By the way, when I used 8. x, my computer generated more heat than before, and the computer process displayed a higher usage rate of Chrome's GPU. Is this also related to webGPU? The current 8.1.0 is much better.

**Comment by rain7788** [comment]
The GPU usage in version 8.1 has decreased and the pages have become smoother.

**Comment by GoodBoyDigital** [comment]
likely the WebGPU switch! I think WebGPU in browsers still has a few more gremlins to work out! It will get there though - i. have no doubt!! :D

**Comment by GoodBoyDigital** [comment]
similar WebGPU issue @rain7788 - https://github.com/pixijs/pixijs/issues/10425

**Comment by rain7788** [comment]
@GoodBoyDigital Got it, thank you.
