### ISSUE TITLE
Bug: TypeError: RendererClass is not a constructor

### ISSUE THREAD

**Issue by erikdubbelboer** [pixijs/pixijs#10402]
### Current Behavior

```
TypeError: RendererClass is not a constructor
 at autoDetectRenderer (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js:10567:20)
 at async _Application.init (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js:10588:21)
```

### Expected Behavior

To start properly.

### Steps to Reproduce

Unknown, haven't been able to reproduce. Affects roughly 100 players per day for this game.

### Environment

- **`pixi.js` version**: *8.0.4*
- **Browser & Version**: *Chrome any version up to 123*
- **OS & Version**: *Unknown*
- **Running Example**: https://poki.com/en/g/silly-sky

**Comment by elsassph** [comment]
This happens when webGl isn't available (fails to initialize?), as Pixi 8 doesn't yet have a canvas 2D renderer fallback.

https://github.com/pixijs/pixijs/blob/dev/src/rendering/renderers/autoDetectRenderer.ts#L89

**Comment by shubhamkumar13** [comment]
is there a way to circumvent this error?

**Comment by bigtimebuddy** [comment]
We should throw a helpful error here as failing is the only option. That's more helpful if no renderer is supported. When we reintroduce the canvas renderer, this should get resolved.

**Comment by xpluscal** [comment]
@bigtimebuddy how would you recommend to go about unit testing e.g. vitest?
