### ISSUE TITLE
Bug: Arc line cap not re-rendered if graphics is cleared

### ISSUE THREAD

**Issue by HughEdwards1** [pixijs/pixijs#10416]
### Current Behavior

When I've created a graphics object and an arc then stroke(), if I call .clear() then redraw again - a line cap is added but only to a single side of the arc. 

### Expected Behavior

The initial stroke draws line caps on both sides.

### Steps to Reproduce

```
arc = new PIXI.Graphics();
arc.setStrokeStyle({
    color: 0xFF0000,
    width: 30, 
    cap: 'round'
});

arc
    .arc(0, 0, 100, 0, Math.PI)
    .stroke();

arc.clear();

arc
    .arc(0, 0, 100, 0, Math.PI)
    .stroke();
```

I've created a playground showing the issue.

### Environment

- **`pixi.js` version**: *8.0.4*
- **Browser & Version**: *Firefox 124.0.4, Chrome 123.0*
- **OS & Version**: *e.g. OSX 12.4*
- **Running Example**: *https://www.pixiplayground.com/#/edit/XqXpYJtwlmkmCvL72J8VF*

**Comment by GoodBoyDigital** [comment]
oh, thats an interesting one! thanks for posting - will take a look

**Comment by Zyie** [comment]
This seems to be fixed in the latest version, feel free to reopen if you still have an issue
