### ISSUE TITLE
Bug: [v8] antialias=true drastically cuts performance even when idle

### ISSUE THREAD

**Issue by joergplewe** [pixijs/pixijs#10413]
### Current Behavior

I was investigating for quite a while now why the v8 port of my app runs much slower than v7, while in any lab experiment v8 drastically outperforms v7, especially when idling.

It turns out that `antialias: true` in `Application.init()` causes this behavior.

The provided playground runs with ~30fps even in idle mode. 

### Expected Behavior

When nothing changes in the scenegraph, run with 60FPS as with `antialias: false`.

### Steps to Reproduce

Use https://www.pixiplayground.com/#/edit/RRfYsdhI3eEl1-bQ5KDC6 and look for `CUT_PERFORMANCE`.

### Environment

- **`pixi.js` version**: 8.0.5
- **Browser & Version**: any
- **OS & Version**: any
- **Running Example**: https://www.pixiplayground.com/#/edit/RRfYsdhI3eEl1-bQ5KDC6

**Comment by photonstorm** [comment]
Solid 60fps for me with `antialias: true` (M1 iMac, Chrome).

**Comment by joergplewe** [comment]
Hm, I tried on another machine with slightly different results, but still showing the effect.
I increased to `CONTENT_COUNT = 400000` in the playground.

**Comment by GoodBoyDigital** [comment]
Hey @joergplewe , antialias is something we don't really have much control over when it comes to optimising its behaviour.
It seems that WebGPU antialiasing is slower than WebGLs at this moment in time. I think the best thing todo here is to switch to WebGL (which is now the default renderer since 8.1.0)

hope this helps! Cheers man!

**Comment by zhouccccc** [comment]
> Hey @joergplewe , antialias is something we don't really have much control over when it comes to optimising its behaviour. It seems that WebGPU antialiasing is slower than WebGLs at this moment in time. I think the best thing todo here is to switch to WebGL (which is now the default renderer since 8.1.0)
> 
> hope this helps! Cheers man!

I tried on my Mac 
<img width="348" alt="image" src="https://github.com/user-attachments/assets/593d0977-eb28-40de-8f4f-62bfdd1c4258">
Even switch to WebGL the FPS is slow as before
![image](https://github.com/user-attachments/assets/ca94f272-b8be-4eeb-83f1-4138e7414af4)
 But when set antialias: false. it goes well
 
![image](https://github.com/user-attachments/assets/16eadda4-1e46-499a-8e68-5968ca53d5ec)
