### ISSUE TITLE
Bug: Sprite alpha masks broken in chrome & edge

### ISSUE THREAD

**Issue by HughEdwards1** [pixijs/pixijs#10425]
### Current Behavior

I'm creating some alpha masks using sprites from a gradient fill (using a render texture to use the graphics object as a texture... is there another way to do this on current pixi?).   
I'm applying it to rect objects, and in this example I create them all identically, except the heights of the objects when masks are applied vary unexpectedly.

![New Project(1)](https://github.com/pixijs/pixijs/assets/20678230/82774dd4-2b2a-4299-86ed-30ec1441134e)

### Expected Behavior

All rects have the same height.

### Steps to Reproduce

Code duplicated from playground example here:
```

    const render = (container, texture) => {
        app.renderer.render({
            target: texture,
            container
        });
    }

    const fillGradient = new PIXI.FillGradient(0, 0, 400, 0);

    fillGradient.addColorStop(0, 0xFFFFFF);
    fillGradient.addColorStop(1, 0x000000);

    const gradientFill = new PIXI.Graphics()
        .rect(0, 0, 400, 50)
        .fill(fillGradient)

    const gradientTexture = PIXI.RenderTexture.create({
        width: 400,
        height: 50
    });

    render(gradientFill, gradientTexture);

    const createMaskedRect = (applyMask) => {
        const rectContainer = new PIXI.Container();

        const rect = new PIXI.Graphics()
            .rect(0, 0, 400, 50)
            .fill({ color: 0xFF0000 });

        const mask = new PIXI.Sprite({
            width: 400,
            height: 50,
            texture: gradientTexture
        });

        if (applyMask) {
            rectContainer.mask = mask;
        }
        rectContainer.addChild(rect, mask);

        return rectContainer;
    }

    for (let i = 1; i < 5; ++i) {
        const rect = createMaskedRect(true);

        rect.position.set(0, 100 * i);
        app.stage.addChild(rect);
    }

    for (let i = 5; i < 9; ++i) {
        const rect = createMaskedRect(true);

        rect.position.set(0, 100 * (i + 1));
        app.stage.addChild(rect);
    }

    app.stage.addChild(gradientFill)
```

### Environment

- **`pixi.js` version**: *8.0.4*
- **Browser & Version**: *Chrome 123.0*
- **OS & Version**: *M2 OSX 12.4*
- **Running Example**: *https://www.pixiplayground.com/#/edit/W5wKexEIjQooixhA29DgK*

**Comment by GoodBoyDigital** [comment]
heya, i set up this playground to apply the masks

https://www.pixiplayground.com/#/edit/EwmDuvFCs8id9JvOC4Y5b

<img width="461" alt="image" src="https://github.com/pixijs/pixijs/assets/3112434/e9bf5862-1b2b-4cee-bc96-27ee5f8e7660">


it seems to be working ok for me in chrome? @HughEdwards1 could you verify pls? Cheers man!

**Comment by HughEdwards1** [comment]
Hey @GoodBoyDigital 

Thanks so much for having a look.
I can confirm that the playground you've made there also has the issue for me.

<img width="1695" alt="Screen Shot 2024-04-10 at 9 12 23 am" src="https://github.com/pixijs/pixijs/assets/20678230/364c80c0-4060-4a03-a1a0-b714295e930d">

However I've since made a horrific discovery. The project that I initially encountered this one... I'm hosting it on my local network now... 
On _another_ mac computer, OSX 11.6.4 M1... and it's rendering perfectly fine. On the same chrome version.

I'm not really sure what this says for me. Hardware issue? OS gl issue?   
I'm going to restart this machine and hope that when it opens back up everything works again.

**Comment by HughEdwards1** [comment]
...Restart unsurprisingly did not help.       
Not sure where that puts this ticket.

Pain in the ass to replicate I imagine.   
I'm going to update my OS on the initial machine (OSX 12.4) and see if that brings and joy.

**Comment by GoodBoyDigital** [comment]
hey, could you try using 8.1.0? or setting the renderer to WebGL pls? I think it maaaaay be a WebGPU issue

**Comment by HughEdwards1** [comment]
WebGL sorts the issue. At the cost of a lot of lovely performance which I've come to expect : (

**Comment by GoodBoyDigital** [comment]
You know, i think there is a legit WebGPU bug somewhere in here - similar issue here #10406
Connection affecting GPU textures... 

Can i ask - whats the performance difference for you? WebGL should be similar speeds? Thanks!

**Comment by HughEdwards1** [comment]
> You know, i think there is a legit WebGPU bug somewhere in here - similar issue here #10406 Connection affecting GPU textures...
> 
> Can i ask - whats the performance difference for you? WebGL should be similar speeds? Thanks!

I measured it (my actual full scale project) in a few different test cases:
Resolution 2x (webgl & webgpu) which is how it was initially set.
Then again with 1x resolution.

Then again for both resolutions after removing the alpha masks (welcome back to the original pain) because I noticed even a single large sprite was having a significant performance hit (app is 4K reso.. so at 2x reso I think the textures were just pushing some boundaries)

In almost every case the webgpu version was about twice as fast to render a frame
