### ISSUE TITLE
Bug: [v8] double `onRender` of rendergroup?

### ISSUE THREAD

**Issue by joergplewe** [pixijs/pixijs#10432]
### Current Behavior

Hunting v8 performance issues I made an observation that might be a bug, or might be not:

While observing the `onRender` callback of a container that is marked as a rendergroup (`new PIXI.Container({ isRenderGroup: true })`), the callback is alway called twice, once every 16ms (depending on FPS) and a second time shortly after ~0.1ms.

### Expected Behavior

`onRender` should be called only once

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/QBaZ6bnIbnduncrJiXSRW

and watch console

### Environment

- **`pixi.js` version**: 8.1.0
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**:[ https://www.pixiplayground.com/#/edit/QBaZ6bnIbnduncrJiXSRW

**Comment by GoodBoyDigital** [comment]
thanks for sharing, will take a look!

**Comment by GoodBoyDigital** [comment]
found! it! PR is up 👍
