### ISSUE TITLE
Bug: When forceCanvas is true， mask sprites with sprites  doesn't work 

### ISSUE THREAD

**Issue by realwugang** [pixijs/pixijs#10438]
### Current Behavior

Using pixi.js-legacy forceCavas:true does not take effect
![image](https://github.com/pixijs/pixijs/assets/26088619/b7346391-b696-4b0d-863f-2c954bfb9390)

### Expected Behavior

[https://pixijs.com/7.x/playground?exampleId=masks.sprite](https://pixijs.com/7.x/playground?exampleId=masks.sprite)
![image](https://github.com/pixijs/pixijs/assets/26088619/c1406eac-2983-4de5-a4db-879fccdfef72)

### Steps to Reproduce

[https://codesandbox.io/p/sandbox/mask-xzyqxx?file=%2Fsrc%2FApp.js%3A9%2C36](https://codesandbox.io/p/sandbox/mask-xzyqxx?file=%2Fsrc%2FApp.js%3A9%2C36``)

### Environment

```json
  "dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-scripts": "^5.0.0",
    "pixi.js-legacy": "7.4.2",
    "@pixi/react": "7.1.2"
  },
```

**Comment by GoodBoyDigital** [comment]
heya! sprite masks are not supported in canvas mode im afraid - as they rely on filters behind the scenes.
