### ISSUE TITLE
Bug: [v8] arctifact when rendering big polygon with offscreen coordinates in Firefox and Safari

### ISSUE THREAD

**Issue by erikdubbelboer** [pixijs/pixijs#10435]
### Current Behavior

<img width="1034" alt="Screenshot 2024-04-10 at 13 57 21" src="https://github.com/pixijs/pixijs/assets/522870/8f3e411b-1c27-4e0f-84f2-cf213fd114fe">

The two red areas left and right are rendered using `Graphics.poly/fill`. With `8.0.5` the line thought though the middle wasn't there but now with `8.1.0` it is there.

### Expected Behavior

The line across the screen shouldn't be there.

### Steps to Reproduce

I haven't had the time to create a small reproducible case. But seeing as other polygons that are small and fully in screen work well I think it has to do with the coordinates being outside of the canvas.

### Environment

- **`pixi.js` version**: *8.1.0*
- **Browser & Version**: *Firefox and Safari* _(line is not there in Chrome)_
- **OS & Version**: *Mac*
- **Running Example**: *https://dubbelboer.com/sillysky.html go to the Mountain Valley level*

**Comment by erikdubbelboer** [comment]
Firefox and Safari is because it only happens in `webgl` and this game has `preference: 'webgpu'`.

**Comment by GoodBoyDigital** [comment]
thanks for clarifying @erikdubbelboer !

**Comment by GoodBoyDigital** [comment]
this looks like an artefact caused by the blur filter - would yo mind removing the blur to see if it disappears? Thank!!

**Comment by erikdubbelboer** [comment]
Yes, removing the blur filter fixes it. I'm just doing:
```js
        const filter = new BlurFilter({
            strength: 2,
            quality: 4,
        });
        this.filters = [filter];
```
Where `this` is a `Container` with the `Graphics` in it. I also have this in other places, but there the graphics don't go out of the screen, so that seems to have something to do with it.

**Comment by GoodBoyDigital** [comment]
heya, this _should_ be fixed in the current release - i had set the texture wrap modes to `repeat` in the last version. This was not a smart move - as it resulted in bleeding on filter textures. The next release, this should be back to `clamp-to-edge` and the issue will be resolved! Let me know! thanks!

**Comment by erikdubbelboer** [comment]
@GoodBoyDigital the issue is still present in v8.1.1.

**Comment by GoodBoyDigital** [comment]
thanks for testing @erikdubbelboer ! Will take another looksi

**Comment by aweidler** [comment]
I also experienced this when using the blur filter in v8. Seemed to work when on v7, but sometimes there are now black line artifacts and other "bleeding" over, tried fixing it with a dynamic `boundsArea` setting, but only had some success and couldn't find a way to remove it completely.

<img width="255" alt="Screenshot 2024-06-30 at 18 06 09" src="https://github.com/pixijs/pixijs/assets/8696105/d76fa156-46e6-4255-ad93-8a078f0c1143">

**Comment by alvov-evo** [comment]
> I have a similar issue when applying blur filter to graphics, here's a playground: https://www.pixiplayground.com/#/edit/zlMwVYfILB3ow2gm2-wKU

UPD: seems like this has been fixed, at least I can't reproduce it no more with version 8.4.0

**Comment by erikdubbelboer** [comment]
Same so I'm going to close this.
