### ISSUE TITLE
Is it possible to do a lossless rotation in Pixi?

### ISSUE THREAD

**Issue by steven-twerdochlib** [pixijs/pixijs#10436]
### Description

After rotating the image and downloading it, I noticed the file size had changed and image quality was different. As the title suggests, is it possible to rotate the image so I can download it without losing image quality. Rotation being for example: 70 degrees.

**Comment by bigtimebuddy** [comment]
If you close an issue, it's customary to post your resolution so that other folks searching similar things might get some help.
