### ISSUE TITLE
Bug: Pixi 7 errors: Argument of type '...' is not assignable to parameter of type 'DisplayObject'

### ISSUE THREAD

**Issue by Chankse** [pixijs/pixijs#10448]
### Current Behavior

This is same issue as [8810](https://github.com/pixijs/pixijs/issues/8810)

As I understand issue was fixed by returning the peerDependencies, as stated on [Migration Guide](https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide).

And issue is actually fixed on 7.2 versions. but on anything above that, issue is still reproducible. 

### Expected Behavior

should be fixed by returning peerDependencies in lates v7

### Steps to Reproduce

same as in 8810

### Environment

Works in Pixi v7.2.4, does not work in lates v7

**Comment by bigtimebuddy** [comment]
Can you please provide a reproduction?

**Comment by Chankse** [comment]
@bigtimebuddy I'm not sure what kind of reproduction I can provide, I'm using Angular application, Yarn for package management and Pixi v7. for v.7.2 it works without problem, but for any version newer than that, I'm getting same errors as in [8810](https://github.com/pixijs/pixijs/issues/8810).
I obviously followed all the necessary steps, like removing old pixi first and then adding new version, deleting lock filed, node modules, and running install again, and so on. Still same issue

**Comment by bigtimebuddy** [comment]
Just make a repo with the same dependencies, package.json. Some of this can happen if we look carefully at the dependencies.

**Comment by Chankse** [comment]
@bigtimebuddy Okay, I'll try,
Btw, [this is](https://github.com/pixijs/pixijs/issues/8798) probably more aligned to the issue I have, than 8810. 
Anyway, i'll get back to you with repo

**Comment by Chankse** [comment]
@bigtimebuddy I'm actually not able to reproduce same issue in separate repo, which is really weird, as I tried to simulate everything in a same way, using Pixi v7.4.2, Pixi-Viewport v5.0.2, same Angular and npm versions.

Do you have any idea why this might be happening? To give you bit more context without repo, here's the copy of error message:

`Argument of type 'ImageContainer' is not assignable to parameter of type 'DisplayObject'.`
Example line : `this.addChild(imageCont);`

Where both `imageCont ` and `this` are custom containers created simply like this:
`export class ImageContainer extends Container {}`

And for some reason, this whole setup runs without issue on v7.2.4 and not on lates v7

**Comment by bigtimebuddy** [comment]
See if you have multiple versions of `@pixi/core` `@pixi/display` etc in your lock file. If so you can use  resolutions in you yarn to resolve.

**Comment by Chankse** [comment]
There's no multiple versions for any of the packages Pixi.js depends on, still I've tried adding resolutions for all of them, but I'm still getting the errors
```
"resolutions": {
    "@pixi/accessibility": "7.4.2",
    "@pixi/app": "7.4.2",
    "@pixi/assets": "7.4.2",
    "@pixi/compressed-textures": "7.4.2",
    "@pixi/core": "7.4.2",
    "@pixi/display": "7.4.2",
    "@pixi/events": "7.4.2",
    "@pixi/extensions": "7.4.2",
    "@pixi/extract": "7.4.2",
    "@pixi/filter-alpha": "7.4.2",
    "@pixi/filter-blur": "7.4.2",
    "@pixi/filter-color-matrix": "7.4.2",
    "@pixi/filter-displacement": "7.4.2",
    "@pixi/filter-fxaa": "7.4.2",
    "@pixi/filter-noise": "7.4.2",
    "@pixi/graphics": "7.4.2",
    "@pixi/mesh": "7.4.2",
    "@pixi/mesh-extras": "7.4.2",
    "@pixi/mixin-cache-as-bitmap": "7.4.2",
    "@pixi/mixin-get-child-by-name": "7.4.2",
    "@pixi/mixin-get-global-position": "7.4.2",
    "@pixi/particle-container": "7.4.2",
    "@pixi/prepare": "7.4.2",
    "@pixi/sprite": "7.4.2",
    "@pixi/sprite-animated": "7.4.2",
    "@pixi/sprite-tiling": "7.4.2",
    "@pixi/spritesheet": "7.4.2",
    "@pixi/text": "7.4.2",
    "@pixi/text-bitmap": "7.4.2",
    "@pixi/text-html": "7.4.2"
  }
```

**Comment by Chankse** [comment]
@bigtimebuddy I'm very sorry, this was a Typescript version problem. fixed after updating it. 
Thank you very much for taking your time

**Comment by muhajirdev** [comment]
I am still facing this issue with typescript 5.3.3 . How did you fix this @Chankse ?
