### ISSUE TITLE
Bug: Generated Texture doesn't support scale mode since 8.1.0

### ISSUE THREAD

**Issue by stevenwithaph** [pixijs/pixijs#10440]
### Current Behavior

Creating a texture through app.renderer.generateTexture, applying scale mode to nearest, and then scaling a sprite will result in a blurry sprite.

### Expected Behavior

Scale mode to be applied.

### Steps to Reproduce

[Playground link](https://www.pixiplayground.com/#/edit/tV-S7TGoo3yiRxZ3WZUWV)

Change pixi version from 8.1.0 to 8.0.5 to see changes.

### Environment

- **`pixi.js` version**: *8.1.0*
- **Running Example**: *<https://www.pixiplayground.com/#/edit/tV-S7TGoo3yiRxZ3WZUWV>*

**Comment by stevenwithaph** [comment]
Looked into this more and it seems that the issue is with the webgl renderer.
Works fine with webgpu.

**Comment by GoodBoyDigital** [comment]
The reason this happens is that the texture style is set when its created to render the item. It kind of accidentally works in WebGPU :)

Here is the amended playground that shows how to set the scaling:

https://www.pixiplayground.com/#/edit/IhvqN3yIatrNlj_bwR6ET

There are two ways:

1 (preferred) when calling generate texture you can pass in texture options:

```
   const graphicsTexture = app.renderer.generateTexture({
        target: graphics,
        // set texture options at creation:
        textureSourceOptions:{
            scaleMode:'nearest'
        }
    });
```

the second is once a texture is created, the style can be modified, but `update` needs to be called to let the renderer know that the style has been updated:

```
    graphicsTexture.source.scaleMode = 'nearest';
    graphicsTexture.source.style.update();
```

Hope this helps!
