### ISSUE TITLE
V8 Bug!

### ISSUE THREAD

**Issue by dragonbaba** [pixijs/pixijs#10447]
### Current Behavior

when texture source use resize(),it shouldn't change the current context color ! and resolution!
if i don't use source.resize ,it behavior cant effect canvas context 
but if i use source resize ,it will become black texture to display!
and it cant use the fillstyle i provided, and cant fill text anymore!

### Expected Behavior

do you think what is the correct behavior ?
fill correct color and fill correct text!!

### Steps to Reproduce

```js
// resize code
sprite.texture.source.resize(300,300);
sprite.texture.frame.width = 300;
sprite.texrure.frame.height = 300;
sprite.texture.update();
sprite.onViewUpdate();
//when using texture.source.resize().it will occur incorrect behavior!
```

### Environment

- **`pixi.js` version**: *e.g. 8.1.0*
- **Browser & Version**: *e.g. Chrome 122*
- **when i using texture.source.resize()**: *e.g. <https://pixiplayground.com/#/edit/-WCTWEd6ffsCODUuc4meq/>*

### Possible Solution

canvas should be reset when using source.resize()
context.fillstyle,context.strokestyle
options of context should be reset
i dont know what is the reason cause this behavior?

**Comment by lunarraid** [comment]
This is normal browser behavior. See HTML spec here: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-set-bitmap-dimensions

See demo demonstrating the above here:
https://www.pixiplayground.com/#/edit/YxFMSneAW7n2nnhx2gSHP
