### ISSUE TITLE
Bug: getLocalBounds doesn't return correct values after removing a child

### ISSUE THREAD

**Issue by talhaozdemir** [pixijs/pixijs#10451]
### Current Behavior

Container getLocalBounds method doesn't return correct values after removing a child from the container

### Expected Behavior

getLocalBounds adds removed objects bounds into account

### Steps to Reproduce

[For V7 (Working Fine)](https://www.pixiplayground.com/#/edit/2Q492z0_h7yTHyqBFKbgS)
[For V8 (Buggy)](https://www.pixiplayground.com/#/edit/FDMVKvmK3kZwsBuZ-WsFa)

### Environment

- **`pixi.js` version**: *e.g. 8.1.0*
- **Browser & Version**: *e.g. Chrome 108*

**Comment by GoodBoyDigital** [comment]
great catch! found the issue and will be fixed in next release! 👍
