### ISSUE TITLE
Bug: Pixi 8 - WebGL: INVALID_ENUM: activeTexture: texture unit out of range

### ISSUE THREAD

**Issue by elsassph** [pixijs/pixijs#10452]
### Current Behavior

When running Pixi 8 app on a legacy browser (a LG webOS TV here), some webGl errors occur
```
WebGL: INVALID_ENUM: activeTexture: texture unit out of range
```
This was raised a few years ago for a previous version of Pixi #3373 

### Expected Behavior

It renders.

### Steps to Reproduce

Running a simple Pixi 8 app (at least an image?) with an old enough Chrome browser:
```
Mozilla/5.0 (WebOS; Linux/SmartTV) AppleWebKit/537.36 (KHTML, Like Gecko) Chrome/53.0.2785.34 Safari/537.36 WebAppManager
```

### Environment

- **`pixi.js` version**: ^8.1.0
- **Browser & Version**: Chrome ~53
- **OS & Version**: webOS 4.10
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by GoodBoyDigital** [comment]
fix is up :D
