### ISSUE TITLE
Bug: Can't `await` `Application.init` from top level if bundled using vite

### ISSUE THREAD

**Issue by Nearoo** [pixijs/pixijs#10456]
I don't know if the issue is present with other bundlers.

### Current Behavior

If you do 
```ts
const app = new Application();
await app.init({
  background: '0x1099bb',
});
```

on the top level, the `init` async promise will never resolve, stalling the remainder of the app.

Note that that if you _not_ `await`, then the promise resolves as expected. So a current workaround is wrapping all code in an async IIFE. Also, if the app isn't bundled, the issue isn't there either.

### Expected Behavior

`await app.init` to resolve and execution to continue.

### Steps to Reproduce

[here]( https://stackblitz.com/edit/vitejs-vite-mbxdgn?file=src%2Fmain.ts)'s a stackblitz showing the behaviour.

If you do `npm run build && npm run preview`, the log statement won't show.

### Environment

- **`pixi.js` version**: *8.0.0-rc.9*
- **Browser & Version**: *Google Chrome*
- **OS & Version**: *Ubuntu 22.04, Mac OS*
- **Running Example**: https://stackblitz.com/edit/vitejs-vite-mbxdgn

**Comment by lunarraid** [comment]
Adding to this, it seems that this only occurs if the PixiJS libs are bundled into the same module file as the app code using the top level await. When this happens, the promise will hang indefinitely. If they are chunked separately, this issue does not occur. I'm sure there is some arcane top level await logic that isn't playing nicely here.

**Comment by nightgrey** [comment]
> Adding to this, it seems that this only occurs if the PixiJS libs are bundled into the same module file as the app code using the top level await. When this happens, the promise will hang indefinitely. If they are chunked separately, this issue does not occur. I'm sure there is some arcane top level await logic that isn't playing nicely here.

I've had a related / similar issue. 

When I created a new Application instance in module-a, but initialized it in module-b, it never resolved, either. 

I had to construct and init in the same module.

Seems related. Just adding this for more info.

**Comment by ASoldo** [comment]
I have the same issue. When working with Pixijs 7 i had no issue, now i started the new project with pixi8 and this colored function is now giving me issues when working with vite. How do I resolve this?

```ts
import * as PIXI from "pixi.js";
import { Engine, Render, Runner } from "matter-js";

export const app = new PIXI.Application();
await app.init({
  backgroundColor: 0x1099bb,
  resolution: window.devicePixelRatio || 1,
  autoDensity: true,
  backgroundAlpha: 1,
  resizeTo: window,
});

(globalThis as any).__PIXI_APP__ = app;
// (globalThis as any).__PIXI_STAGE__ = stage;
// (globalThis as any).__PIXI_RENDERER__ = renderer;

export const engine = Engine.create();
export const runner = Runner.create();

export const matterRender = Render.create({
  element: document.getElementById("matter-debug-container") as HTMLElement,
  engine: engine,
  options: {
    width: app.screen.width,
    height: app.screen.height,
    wireframes: true,
    background: "transparent",
  },
});
```

**Comment by lunarraid** [comment]
Easiest answer is to wrap the entire init in a function instead of using top-level await for now. 
```js
(async () => {
  await app.init({
    backgroundColor: 0x1099bb,
    resolution: window.devicePixelRatio || 1,
    autoDensity: true,
    backgroundAlpha: 1,
    resizeTo: window,
  });
})();
```

**Comment by ASoldo** [comment]
It's not working for me when I do it like this and I get the following error in the console and app breaks:
```ts
import * as PIXI from "pixi.js";
import { Engine, Render, Runner } from "matter-js";

export const app = new PIXI.Application();
(async () => {
  await app.init({
    backgroundColor: 0x1099bb,
    resolution: window.devicePixelRatio || 1,
    autoDensity: true,
    backgroundAlpha: 1,
    resizeTo: window,
  });
})();

(globalThis as any).__PIXI_APP__ = app;
// (globalThis as any).__PIXI_STAGE__ = stage;
// (globalThis as any).__PIXI_RENDERER__ = renderer;

export const engine = Engine.create();
export const runner = Runner.create();

export const matterRender = Render.create({
  element: document.getElementById("matter-debug-container") as HTMLElement,
  engine: engine,
  options: {
    width: app.screen.width,
    height: app.screen.height,
    wireframes: true,
    background: "transparent",
  },
});
```
```
chunk-76JMR5L7.js?v=c7ded604:6060 Uncaught TypeError: Cannot read properties of undefined (reading 'screen')
    at get screen (chunk-76JMR5L7.js?v=c7ded604:6060:26)
    at app.ts:26:16
```

**Comment by lunarraid** [comment]
That's because you're trying to use the application before it has initialized. Move the rest into the function after the await if you need to use the application.

**Comment by ASoldo** [comment]
I was able to do it but I had to refactor few files (move code from there to `app.ts`) and use them here:
```ts
import * as PIXI from "pixi.js";
import { Engine, Render, Runner } from "matter-js";
import { game_scene1 } from "./scenes/game_scene1";

export const engine = Engine.create();
export const matterRender = Render.create({
  element: document.getElementById("matter-debug-container") as HTMLElement,
  engine: engine,
  options: {
    width: window.innerWidth,
    height: window.innerHeight,
    wireframes: true,
    background: "transparent",
  },
});
export const runner = Runner.create();
export const app = new PIXI.Application();
(async () => {
  await app.init({
    backgroundColor: 0x1099bb,
    resolution: window.devicePixelRatio || 1,
    autoDensity: true,
    backgroundAlpha: 1,
    resizeTo: window,
  });
  document
    .getElementById("pixi-container")
    ?.appendChild(app.canvas as HTMLCanvasElement);
  const gameScene = new game_scene1(engine, matterRender);
  app.ticker.add((delta: PIXI.Ticker) => gameScene.update(delta.deltaTime));
  app.start();
  (globalThis as any).__PIXI_APP__ = app;
  // (globalThis as any).__PIXI_STAGE__ = stage;
  // (globalThis as any).__PIXI_RENDERER__ = renderer;
})();
```

**Comment by bigtimebuddy** [comment]
I'm going to close this issue. This is a Vite usage and limitation more than a Pixi problem. Try searching for solutions such as setting the build target to esnext or using a plugin like https://www.npmjs.com/package/vite-plugin-top-level-await.

For other questions or support, please consider creating a discussion instead of an issue.

**Comment by willwillems** [comment]
For other people running into this. Using `esnext` or the plugin won't help you, there is something weird going on that is not (just) Vite.

**Comment by zhao-i** [comment]
There seems to be an issue with code splitting when using top-level await, but bundling can be configured to fix it:

```
build: {
            target: 'es2022',
            rollupOptions: {
                output: {
                    manualChunks: {
                        ['pixijs']: ['pixi.js']
                    }
                }
            }
       },
```
