### ISSUE TITLE
Bug: Windows support: npm run build error TS2503: Cannot find namespace 'PixiMixins'

### ISSUE THREAD

**Issue by a7359475** [pixijs/pixijs#10464]
### Current Behavior

$ npm run build

> pixi.js@8.1.0 prebuild
> npm run clean

> pixi.js@8.1.0 clean
> run-s clean:*

> pixi.js@8.1.0 clean:build
> rimraf "{lib,dist,out}" --glob

> pixi.js@8.1.0 clean:index
> rimraf "src/*/**/index.ts" --glob

> pixi.js@8.1.0 clean:uploads
> rimraf .pr_uploads .s3_uploads --glob

> pixi.js@8.1.0 build
> run-s build:index build:pkg build:rollup build:tsc build:dts build:dts-bundle

> pixi.js@8.1.0 build:index
> ts-node --transpile-only ./scripts/index/index.ts

> pixi.js@8.1.0 build:pkg
> ts-node ./scripts/utils/exports.ts

> pixi.js@8.1.0 build:rollup
> npx rollup -c --failAfterWarnings

(node:1364) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

C:\mine\code\github\pixijs\src\environment-browser\browserAll.ts, C:\mine\code\github\pixijs\src\environment-webworker\webworkerAll.ts, C:\mine\code\github\pixijs\src\index.ts, C:\mine\code\github\pixijs\src\rendering\init.ts, C:\mine\code\github\pixijs\src\spritesheet\init.ts, C:\mine\code\github\pixijs\src\rendering\renderers\shared\texture\utils\textureFrom.ts, C:\mine\code\github\pixijs\src\accessibility\init.ts, C:\mine\code\github\pixijs\src\advanced-blend-modes\init.ts, C:\mine\code\github\pixijs\src\app\init.ts, C:\mine\code\github\pixijs\src\compressed-textures\dds\init.ts, C:\mine\code\github\pixijs\src\compressed-textures\ktx\init.ts, C:\mine\code\github\pixijs\src\compressed-textures\ktx2\init.ts, C:\mine\code\github\pixijs\src\compressed-textures\basis\init.ts, C:\mine\code\github\pixijs\src\events\init.ts, C:\mine\code\github\pixijs\src\filters\init.ts, C:\mine\code\github\pixijs\src\math-extras\init.ts, C:\mine\code\github\pixijs\src\scene\sprite-tiling\init.ts, C:\mine\code\github\pixijs\src\scene\text\init.ts, C:\mine\code\github\pixijs\src\scene\text-bitmap\init.ts, C:\mine\code\github\pixijs\src\scene\text-html\init.ts, C:\mine\code\github\pixijs\src\scene\graphics\init.ts, C:\mine\code\github\pixijs\src\scene\mesh\init.ts, C:\mine\code\github\pixijs\src\prepare\init.ts, C:\mine\code\github\pixijs\src\unsafe-eval\init.ts, C:\mine\code\github\pixijs\src\scene\sprite-nine-slice\init.ts → lib, lib...
created lib, lib in 7.4s

C:\mine\code\github\pixijs\src\bundle.browser.ts → dist/pixi.js, dist/pixi.mjs...
created dist/pixi.js, dist/pixi.mjs in 7s

C:\mine\code\github\pixijs\src\bundle.browser.ts → dist/pixi.min.js, dist/pixi.min.mjs...
created dist/pixi.min.js, dist/pixi.min.mjs in 6.6s

C:\mine\code\github\pixijs\src\bundle.math-extras.ts → dist/packages/math-extras.js...
created dist/packages/math-extras.js in 374ms

C:\mine\code\github\pixijs\src\bundle.math-extras.ts → dist/packages/math-extras.min.js...
created dist/packages/math-extras.min.js in 76ms

C:\mine\code\github\pixijs\src\bundle.unsafe-eval.ts → dist/packages/unsafe-eval.js...
created dist/packages/unsafe-eval.js in 152ms

C:\mine\code\github\pixijs\src\bundle.unsafe-eval.ts → dist/packages/unsafe-eval.min.js...
created dist/packages/unsafe-eval.min.js in 130ms

C:\mine\code\github\pixijs\src\bundle.advanced-blend-modes.ts → dist/packages/advanced-blend-modes.js...
created dist/packages/advanced-blend-modes.js in 182ms

C:\mine\code\github\pixijs\src\bundle.advanced-blend-modes.ts → dist/packages/advanced-blend-modes.min.js...
created dist/packages/advanced-blend-modes.min.js in 174ms

C:\mine\code\github\pixijs\src\bundle.webworker.ts → dist/webworker.js, dist/webworker.mjs...
created dist/webworker.js, dist/webworker.mjs in 4.9s

C:\mine\code\github\pixijs\src\bundle.webworker.ts → dist/webworker.min.js, dist/webworker.min.mjs...
created dist/webworker.min.js, dist/webworker.min.mjs in 4.7s

> pixi.js@8.1.0 build:tsc
> tsc -p tsconfig.types.json

> pixi.js@8.1.0 build:dts
> ts-node --transpile-only ./scripts/types/fixTypes.ts && copyfiles -u 1 "src/**/*.d.ts" lib/

> pixi.js@8.1.0 build:dts-bundle
> dts-bundle-generator --config dts.config.js

Compiling input files1...
lib/app/Application.d.ts(68,64): error TS2503: Cannot find namespace 'PixiMixins'.
lib/app/Application.d.ts(70,38): error TS2503: Cannot find namespace 'PixiMixins'.
lib/app/TickerPlugin.d.ts(57,27): error TS2503: Cannot find namespace 'PixiMixins'.
lib/assets/Assets.d.ts(26,78): error TS2503: Cannot find namespace 'PixiMixins'.
lib/environment/canvas/ICanvas.d.ts(44,34): error TS2503: Cannot find namespace 'PixiMixins'.
lib/maths/point/ObservablePoint.d.ts(3,42): error TS2503: Cannot find namespace 'PixiMixins'.
lib/maths/point/Point.d.ts(3,32): error TS2503: Cannot find namespace 'PixiMixins'.
lib/maths/shapes/Rectangle.d.ts(5,36): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(22,70): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(22,99): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(24,73): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(24,100): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(29,114): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(20,72): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(20,101): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(21,75): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(21,102): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(26,116): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/shared/system/AbstractRenderer.d.ts(111,62): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/shared/system/SharedSystems.d.ts(24,94): error TS2503: Cannot find namespace 'PixiMixins'.
lib/scene/container/Container.d.ts(14,68): error TS2503: Cannot find namespace 'PixiMixins'.
lib/scene/container/Container.d.ts(51,86): error TS2503: Cannot find namespace 'PixiMixins'.
lib/scene/container/Container.d.ts(89,67): error TS2503: Cannot find namespace 'PixiMixins'.

Error: Compiled with errors
ERROR: "build:dts-bundle" exited with 1.

### Expected Behavior

Normal generate d.ts

### Steps to Reproduce

1. git clone
2. cd pixijs
3. git checkout v8.1.0
4. npm i
5. npm run build

### Environment

- **`pixi.js` version**: *8.1.0*
- **Terminal & Version**: *Git Bash(Git for Windows v2.37.0)*
- **OS & Version**: *WINDOWS 10 PRO*

**Comment by Zyie** [comment]
I've been unable to recreate this, if its still an issue feel free to reopen

**Comment by rfvtgbzxc** [comment]
I meet this, in v8.2.1, and shows the same problem.
I downloaded the ziped project, unzipped and run npm install, then npm run build, then meeted this.

**Comment by valr2** [comment]
I have the same issue. Pixi v8.0.5 compiles fine, but anything from v8.1.0 onwards up to v8.2.5 fails with the errors described in the original bug report. Newer versions show a few extra errors, but essentially it's the same problem, occurring during build:dts-bundle. 

v8.1.0 is the version that added dts bundling (https://github.com/pixijs/pixijs/pull/10286). 

I've done a clean install of the latest NodeJS (v20.15.1) and NPM (10.8.2). Used Git to checkout all these versions. Deleted node_modules folder, then "npm install" and "npm run build". Running on Win 10 Pro. Local root path for the project is "D:\Symmetry2D\pixijs" (so no long or problematic paths are involved).

What could be causing this and why is it not reproducible for @Zyie? Could you reopen this bug, please? Thanks!

Here are the errors for v8.2.5:

> pixi.js@8.2.5 build:dts-bundle
> dts-bundle-generator --config dts.config.js

Compiling input files...
lib/app/Application.d.ts(68,64): error TS2503: Cannot find namespace 'PixiMixins'.
lib/app/Application.d.ts(70,38): error TS2503: Cannot find namespace 'PixiMixins'.
lib/app/TickerPlugin.d.ts(57,27): error TS2503: Cannot find namespace 'PixiMixins'.
lib/assets/Assets.d.ts(26,78): error TS2503: Cannot find namespace 'PixiMixins'.
lib/environment/canvas/ICanvas.d.ts(44,34): error TS2503: Cannot find namespace 'PixiMixins'.
lib/events/FederatedEvent.d.ts(51,5): error TS2416: Property 'currentTarget' in type 'FederatedEvent<N>' is not assignable to the same property in base type 'UIEvent'.
  Type 'Container<ContainerChild>' is not assignable to type 'EventTarget'.
lib/events/FederatedEvent.d.ts(66,5): error TS2416: Property 'target' in type 'FederatedEvent<N>' is not assignable to the same property in base type 'UIEvent'.
  Type 'Container<ContainerChild>' is not assignable to type 'EventTarget'.
lib/events/FederatedEvent.d.ts(115,5): error TS2416: Property 'composedPath' in type 'FederatedEvent<N>' is not assignable to the same property in base type 'UIEvent'.
  Type '() => Container<ContainerChild>[]' is not assignable to type '{ (): EventTarget[]; (): EventTarget[]; }'.
    Type 'Container<ContainerChild>[]' is not assignable to type 'EventTarget[]'.
      Type 'Container<ContainerChild>' is not assignable to type 'EventTarget'.
lib/events/FederatedMouseEvent.d.ts(10,22): error TS2420: Class 'FederatedMouseEvent' incorrectly implements interface 'MouseEvent'.
  Types of property 'currentTarget' are incompatible.
    Type 'Container<ContainerChild>' is not assignable to type 'EventTarget'.
      Type 'Container<ContainerChild>' is missing the following properties from type 'EventTarget': addEventListener, dispatchEvent, removeEventListener
lib/events/FederatedPointerEvent.d.ts(6,22): error TS2420: Class 'FederatedPointerEvent' incorrectly implements interface 'PointerEvent'.
  Types of property 'currentTarget' are incompatible.
    Type 'Container<ContainerChild>' is not assignable to type 'EventTarget'.
lib/events/FederatedWheelEvent.d.ts(6,22): error TS2420: Class 'FederatedWheelEvent' incorrectly implements interface 'WheelEvent'.
  Types of property 'currentTarget' are incompatible.
    Type 'Container<ContainerChild>' is not assignable to type 'EventTarget'.
lib/maths/point/ObservablePoint.d.ts(3,42): error TS2503: Cannot find namespace 'PixiMixins'.
lib/maths/point/Point.d.ts(3,32): error TS2503: Cannot find namespace 'PixiMixins'.
lib/maths/shapes/Rectangle.d.ts(5,36): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(22,70): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(22,99): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(24,73): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(24,100): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(29,114): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(20,72): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(20,101): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(21,75): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(21,102): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(26,116): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/shared/system/SharedSystems.d.ts(25,94): error TS2503: Cannot find namespace 'PixiMixins'.
lib/scene/container/Container.d.ts(14,68): error TS2503: Cannot find namespace 'PixiMixins'.
lib/scene/container/Container.d.ts(51,86): error TS2503: Cannot find namespace 'PixiMixins'.
lib/scene/container/Container.d.ts(87,62): error TS2503: Cannot find namespace 'PixiMixins'.

Error: Compiled with errors
ERROR: "build:dts-bundle" exited with 1.

**Comment by mironote** [comment]
same error, v83.1

**Comment by e1e5en-gd** [comment]
This bug is present in version 8.6.1.

```
> pixi.js@8.6.1 build:tsc
> tsc -p tsconfig.types.json


> pixi.js@8.6.1 build:dts
> ts-node --transpile-only ./scripts/types/fixTypes.ts && copyfiles -u 1 "src/**/*.d.ts" lib/

> pixi.js@8.6.1 build:dts-bundle
> dts-bundle-generator --config dts.config.js

Compiling input files...
lib/app/Application.d.ts(68,64): error TS2503: Cannot find namespace 'PixiMixins'.
lib/app/Application.d.ts(70,38): error TS2503: Cannot find namespace 'PixiMixins'.
lib/app/TickerPlugin.d.ts(57,27): error TS2503: Cannot find namespace 'PixiMixins'.
lib/assets/Assets.d.ts(26,78): error TS2503: Cannot find namespace 'PixiMixins'.
lib/environment/canvas/ICanvas.d.ts(44,34): error TS2503: Cannot find namespace 'PixiMixins'.
lib/events/FederatedEvent.d.ts(51,5): error TS2416: Property 'currentTarget' in type 'FederatedEvent<N>' is not assignable to the same property in base type 'UIEvent'.
  Type 'Container<ContainerChild>' is not assignable to type 'EventTarget'.
lib/events/FederatedEvent.d.ts(66,5): error TS2416: Property 'target' in type 'FederatedEvent<N>' is not assignable to the same property in base type 'UIEvent'.
  Type 'Container<ContainerChild>' is not assignable to type 'EventTarget'.
lib/events/FederatedEvent.d.ts(115,5): error TS2416: Property 'composedPath' in type 'FederatedEvent<N>' is not assignable to the same property in base type 'UIEvent'.
  Type '() => Container<ContainerChild>[]' is not assignable to type '{ (): EventTarget[]; (): EventTarget[]; }'.
    Type 'Container<ContainerChild>[]' is not assignable to type 'EventTarget[]'.
      Type 'Container<ContainerChild>' is not assignable to type 'EventTarget'.
lib/events/FederatedMouseEvent.d.ts(10,22): error TS2420: Class 'FederatedMouseEvent' incorrectly implements interface 'MouseEvent'.
  Types of property 'currentTarget' are incompatible.
    Type 'Container<ContainerChild>' is not assignable to type 'EventTarget'.
      Type 'Container<ContainerChild>' is missing the following properties from type 'EventTarget': addEventListener, dispatchEvent, removeEventListener
lib/events/FederatedPointerEvent.d.ts(6,22): error TS2420: Class 'FederatedPointerEvent' incorrectly implements interface 'PointerEvent'.
  Types of property 'currentTarget' are incompatible.
    Type 'Container<ContainerChild>' is not assignable to type 'EventTarget'.
lib/events/FederatedWheelEvent.d.ts(6,22): error TS2420: Class 'FederatedWheelEvent' incorrectly implements interface 'WheelEvent'.
  Types of property 'currentTarget' are incompatible.
    Type 'Container<ContainerChild>' is not assignable to type 'EventTarget'.
lib/maths/point/ObservablePoint.d.ts(3,42): error TS2503: Cannot find namespace 'PixiMixins'.
lib/maths/point/Point.d.ts(3,32): error TS2503: Cannot find namespace 'PixiMixins'.
lib/maths/shapes/Rectangle.d.ts(5,36): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(22,70): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(22,99): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(24,73): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(24,100): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gl/WebGLRenderer.d.ts(29,114): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(20,72): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(20,101): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(21,75): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(21,102): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/gpu/WebGPURenderer.d.ts(26,116): error TS2503: Cannot find namespace 'PixiMixins'.
lib/rendering/renderers/shared/system/SharedSystems.d.ts(27,94): error TS2503: Cannot find namespace 'PixiMixins'.
lib/scene/container/Container.d.ts(14,68): error TS2503: Cannot find namespace 'PixiMixins'.
lib/scene/container/Container.d.ts(51,86): error TS2503: Cannot find namespace 'PixiMixins'.
lib/scene/container/Container.d.ts(87,62): error TS2503: Cannot find namespace 'PixiMixins'.

Error: Compiled with errors
ERROR: "build:dts-bundle" exited with 1.
```

**Comment by bigtimebuddy** [comment]
I wonder is this is a Windows issue? Since I on macOS cannot reproduce and our Ubuntu CI doesn't reproduce, it may be Windows issue. Can anyone here confirm?

**Comment by bigtimebuddy** [comment]
This reproduces in Windows in CI: https://github.com/pixijs/pixijs/actions/runs/12088632125/job/33712508931
