### ISSUE TITLE
Bug: V8 graphics tint applied in a weird way

### ISSUE THREAD

**Issue by jakerdy** [pixijs/pixijs#10462]
### Current Behavior

Hi, I finnaly decided to port my app to V8 and encounter couple problems.

First problem that I got, it's different tint behaviour on `Graphics`. In v7 tints applied via color multiplication. In v8 it works somehow differetly, which makes unpredictable results in most cases.

Here you could see this effect:
![image](https://github.com/pixijs/pixijs/assets/66637406/ffbdcef5-2503-4159-ad4e-c194da9ecdbb)

Is this some kind new feature that wasn't described in migration guide and changelogs, or it is a bug?

### Expected Behavior

V8 Graphics tints should be multiplicative. If tint is `black`, `graphics` also should be black.

### Steps to Reproduce

V8 playground: https://www.pixiplayground.com/#/edit/LLWPYftOAq044gn7sSoxV
V7 playground: https://www.pixiplayground.com/#/edit/IDHn7Kt2sVujHnXA512i4

### Environment

- **`pixi.js` version**: *e.g. 8.1.0*
- **Browser & Version**: *e.g. Chrome 124*
- **OS & Version**: *e.g. Windows 10*

**Comment by jakerdy** [comment]
Actually, every single non white renderable ellement where tint was applied looks differently.

Here couple screens from my app:

Pixi v7.4.0:
![v7](https://github.com/pixijs/pixijs/assets/66637406/f407bec6-ef53-4e7e-9f3e-5e44910ee4a8)

Pixi v8.1.0:
![v8](https://github.com/pixijs/pixijs/assets/66637406/a1e5d065-4f10-486d-9afd-066119f85160)

Text movement is a second problem, I will report it as separate issue.

**Comment by GoodBoyDigital** [comment]
thanks for sharing @jakerdy ! will take a poke around

**Comment by GoodBoyDigital** [comment]
definitely a bug! great catch! will post a fix up later today 👍
