### ISSUE TITLE
Feature Request: Is it possible to split a texture after exceeding the maximum texture size?

### ISSUE THREAD

**Issue by pzppzz** [pixijs/pixijs#10460]
### Description

![image](https://github.com/pixijs/pixijs/assets/89590352/f9ebdc5a-5da6-4902-916f-60d44d026aac)
pixijs applications may not work on some devices because of the limit of gpu's TEXTURE_MAX_SIZE

**Comment by bigtimebuddy** [comment]
Thanks for the suggestion. Unfortunately, this isn't something we are likely to address. Developers are welcome to create their own optimizations for max texture size.
