### ISSUE TITLE
Bug: Error: Unable to auto-detect a suitable renderer.

### ISSUE THREAD

**Issue by SolitaryScripter** [pixijs/pixijs#10466]
### Current Behavior

[https://pixijs.com/7.x/playground](url)
<img width="1242" alt="738AEB6A-0585-4BCA-80A6-AC1E8ADD26AD" src="https://github.com/pixijs/pixijs/assets/22770979/07007675-ebc8-4503-8554-a0faa4f59c37">

### Expected Behavior

able to render correctly

### Steps to Reproduce

<img width="744" alt="image" src="https://github.com/pixijs/pixijs/assets/22770979/824ce591-2674-41e5-8d92-b0502d13a9a4">
Turn off GPU acceleration

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by lunarraid** [comment]
@SolitaryScripter  You have disabled hardware acceleration. In v7, you need to use `pixi-legacy` for non-hardware-accelerated canvas support. In v8, this hasn't been written yet. PixiJS WebGL requires hardware acceleration to be enabled.
