### ISSUE TITLE
Bug: When Application is proxied by Vue 3(ref), an error occurs when rendering graphics

### ISSUE THREAD

**Issue by ZaneL1u** [pixijs/pixijs#10477]
### Current Behavior

When Application is proxied by Vue 3, an error occurs when rendering graphics, like:

```vue
<script setup lang="ts">
import { Application, Graphics } from "pixi.js";
import { onMounted, ref } from "vue";

const app = ref<Application>();

onMounted(() => {
  (async () => {
    // Create a new application
    app.value = new Application();

    // Initialize the application
    await app.value.init({ antialias: true, resizeTo: window });

    // Append the application canvas to the document body
    document.body.appendChild(app.value.canvas);

    const graphics = new Graphics();
    graphics.rect(50, 50, 100, 100);
    graphics.fill(0xde3249);

    app.value.stage.addChild(graphics);
  })();
});
</script>

<template>
  <div id="pixi"></div>
</template>

<style scoped>
.pixi {
  width: 100%;
  height: 100%;
}
</style>
```

Then an error will be reported:
<img width="846" alt="image" src="https://github.com/pixijs/pixijs/assets/70258597/990205f4-83fd-4edf-86f0-f817f7fd0fbe">

### Expected Behavior

Align and process rendering correctly.

### Steps to Reproduce

recurrent: https://codesandbox.io/p/devbox/pixijs-texturematrix-recurrent-lqknp4?file=%2Fsrc%2FApp.vue%3A6%2C8

### Environment

- **`pixi.js` version**: *8.0.0 - 8.1.0*
- **Browser & Version**: *Chrome 124*
- **OS & Version**: *MacOS 14.3 (23D56)*
- **Running Example**: *[recurrent](https://codesandbox.io/p/devbox/pixijs-texturematrix-recurrent-lqknp4?file=%2Fsrc%2FApp.vue%3A6%2C8)*

### Possible Solution

After investigation, it was found: https://github.com/pixijs/pixijs/blob/ff67a1d00ebd9d0e887eb075c35c9163d111214f/src/scene/graphics/shared/utils/buildContextBatches.ts#L214

The texture object was mistakenly pointed to the Texture.WHITE object. Comparison.

I want to submit a PR to solve this kind of problem, but it seems that comparing Label is inappropriate, and introducing additional Vue toRaw dependencies will increase complexity.

I would like to hear your suggestions?

**Comment by jarvisniu** [comment]
Change `ref` to `shallowRef` will work

**Comment by ZaneL1u** [comment]
YES, but I need `ref` to listen for deep value changes @jarvisniu

**Comment by ZaneL1u** [comment]
And I think it should be a pointer problem, which will make `Proxy` unavailable.

**Comment by whyhw** [comment]
> > Change `ref` to `shallowRef` will work
> 
> YES, but I need `ref` to listen for deep value changes. And I think it should be a pointer problem, which will make `Proxy` unavailable. @jarvisniu

Hi，I have the same problem by 'ref'. I found line214：texture object became proxy object, so they can't be equal. How can I resolve this problem? Thanks.
