### ISSUE TITLE
Perfromance: CPU100% in OpenGL mode on a big map when computer does not have GPU even the graph is static

### ISSUE THREAD

**Issue by jiajun** [pixijs/pixijs#10473]
### Current Behavior

Our machine is for industry which using Intel Xeon without GPU. We created an application based on pixi v7.4.2 in the default openGL mode. When opened a big map (including more than 60,000 rects), the CPU becomes always 95%-100%, even after the map rendered without any movement. 

### Expected Behavior

The CPU usage should go down after rendering or moving the map. 

### Steps to Reproduce

let me know if you need a sample.

### Environment

- **`pixi.js` version**: *v7.4.2*
- **Browser & Version**: *Electron 25.2.0*
- **OS & Version**: *e.g. Windows 10*

**Comment by GoodBoyDigital** [comment]
i would try bumping to v8 - thous should run static content much faster!

**Comment by GoodBoyDigital** [comment]
couple of other approaches: 
- render the view to a texture - and if nothing moves, just keep re rendering the texture to the viewer. 
- add culling so you only render what you see
hope that helps!
