### ISSUE TITLE
Bug: Mesh emits error when app.stage.interactive is true

### ISSUE THREAD

**Issue by talhaozdemir** [pixijs/pixijs#10485]
### Current Behavior

When hovering over mesh, getting error about containsPoint function, this issue occurs when app.stage.interactive = true

### Expected Behavior

It should't throw error when stage interactivity is true

### Steps to Reproduce

- Add a mesh
- set app.stage.interactive = true
- hover over the mesh

### Environment

- **`pixi.js` version**: 8.1.0*
- **Browser & Version**: Chrome
- **Running Example**:  [Playground Link](https://www.pixiplayground.com/#/edit/2M8HmXPZPqCj4a1A-EojB)

**Comment by GoodBoyDigital** [comment]
good catch! fixed and optimised for good measure :D
