### ISSUE TITLE
Feature-Request: V8 support sub-Textures when creating BitmapFont objects

### ISSUE THREAD

**Issue by alvov-evo** [pixijs/pixijs#10482]
### Current Behavior

BitmapFont doesn't seem to use texture with defined frame but rather a source texture of that framed texture.

### Expected Behavior

BitmapFont uses texture with defined frame.

### Steps to Reproduce

Let there be multiple bitmap font textures combined into one sprite sheet file.

```
const sprite = new PIXI.Spritesheet(texture, data);
await sprite.parse();

const fontTexture = sprite.textures.font;
```

Create BitmapFont with a constructor as follows:

```
const font = new PIXI.BitmapFont({
    data: fontData,
    textures: [fontTexture],
});
```

Then create BitmapText using font family of this font:

```
    const bitmapFontText = new PIXI.BitmapText({
        text: 'some text,
        style: {
            fontFamily: 'Desyrel',
        },
    });
```

In that case BitmapFont doesn't seem to use `fontTexture` as source, but would rather use the whole sprite texture.

For instance, I've created a sprite sheet image with two Desyrel fonts: yellow on the left and green on the right.
Please check the playground: https://www.pixiplayground.com/#/edit/T5-gUiUddcNFhan8QaTPD
I pass the texture referring to the "green" texture to BitmapFont (so rendered text should be green), but it still seems to use the source sprite sheet texture (rendered text is yellow).
(Sorry for the somewhat messy playground example)

### Environment

- **`pixi.js` version**: *8.1.0*
- **Running Example**: *<https://www.pixiplayground.com/#/edit/T5-gUiUddcNFhan8QaTPD>*

**Comment by bigtimebuddy** [comment]
Yeah, that's right, the `fontTexture` here assumes the `fontData` contains coordinates relative to the entire Texture's source. I would put this as a feature request since the behavior is currently undefined. 

There seems to be a simple solution:
https://github.com/pixijs/pixijs/blob/ff67a1d00ebd9d0e887eb075c35c9163d111214f/src/scene/text-bitmap/BitmapFont.ts#L46-L59

We could simply offset Rectangle's x and y values by the Texture's frame. I think that would probably be enough!

**Comment by alvov-evo** [comment]
Thank you for the response!

I forgot to mention that the same case worked in version 7.x (7.3.2 at least), that's why I thought it's a regression.
Now that I know where to look at, I think it previously did a similar thing to what you've proposed:
https://github.com/pixijs/pixijs/blob/9104ebd911ac97cd58928d476b588061fa2ad680/packages/text-bitmap/src/BitmapFont.ts#L224-L229

Any way, I can confirm this solution works for my case 🙇‍♂️

**Comment by bigtimebuddy** [comment]
Nice. Would you mind making a PR for this change @alvov-evo?

**Comment by alvov-evo** [comment]
@bigtimebuddy done
