### ISSUE TITLE
Bug: 8.1.0 Text texture is generated with the previous texture still partially visible

### ISSUE THREAD

**Issue by birodani3** [pixijs/pixijs#10493]
### Current Behavior

Text texture is rendered without fully clearing the previous canvas if padding is set.

### Expected Behavior

Text texture is generated on a cleared canvas

### Steps to Reproduce

- Add a Text with some padding set
- Update a style to change the text width (fontSize is the easiest but reproducible with wordWrapWidth etc.)
- Observe the text: texture is sometimes generated on a partailly cleared canvas and not a fully clear one

+1: Padding is not applied to the left and top sides, only on the bottom and right

### Environment

- **`pixi.js` version**: *8.1.0*
- **Browser & Version**: *Chrome 124.0.6367.92 (Official Build) (64-bit)*
- **OS & Version**: *Windows 11*
- **Running Example**: *[Playground](https://www.pixiplayground.com/#/edit/kPygYIZbVwghwcaLc6Tgt)*

**Comment by birodani3** [comment]
Also reproducible if you destroy your text object add a new one later. In some cases the new text's texture is generated on the previous canvas and is not fully cleared, parts of the previous (destroyed!) text is visible on it.

**Comment by GoodBoyDigital** [comment]
great catch, thanks for sharing - will take a look!

**Comment by birodani3** [comment]
Thank you @GoodBoyDigital !

Could you also check the paddings? It seems that the top and left paddings are not added at all. Maybe the right and bottom are doubled then?

Let me know if I should create a separate ticket with a repro playground link for it.
