### ISSUE TITLE
Bug: Using a eraser, when the webgl device is lost and cannot be restored

### ISSUE THREAD

**Issue by yungzhu** [pixijs/pixijs#10497]
### Current Behavior

Implement a eraser function, but unable to restore context

### Expected Behavior

https://www.pixiplayground.com/#/edit/QHv0al2HxtGV1tf-ac1Cw

### Steps to Reproduce

click the sprite，can not show again

### Environment

- **`pixi.js` version**: *e.g. 8.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by GoodBoyDigital** [comment]
Heya! This is not ideal! but correct behaviour. When a context is lost, all render textures content is lost also. They need to be re-rendered as part of you apps restoring the context process (this is not possible to do from Pixi side unfortunately - we only store the pixels. 

Adjusted example: https://www.pixiplayground.com/#/edit/WR3_70RjJZv_oJjMTfgg2
