### ISSUE TITLE
Feature Request: CacheAsBitmap for V8

### ISSUE THREAD

**Issue by farscapex** [pixijs/pixijs#10504]
### Current Behavior

I noticed that cacheAsBitmap property from Container class has disappeared.
Is there a workaround for that ? Or maybe a come back of the property ?
This feature was really powerful in the previous versions and many projects cannot be migrated without that.

### Expected Behavior

When we have a container and many sprites side by side, with V7 and cacheAsBitmap enabled, we can scale the container as much as we want, the container behave like an image and displays no spaces between the sprites. 

![v7](https://github.com/pixijs/pixijs/assets/14073248/3ab8e9a5-54d8-48b4-9ba7-86e00d4f20c5)

### Steps to Reproduce

in V8 without cacheAsBitmap, when the container is rescaled, some spaces appear between the sprites and do not behave like an image which results in some weird behaviour (see attached images)

![v8](https://github.com/pixijs/pixijs/assets/14073248/365469ac-ed00-4528-85ec-0d838995a9c3)

### Environment

- **`pixi.js` version**: *e.g. 8.1.0*
- **Browser & Version**: *e.g. Chrome*

### Possible Solution

I can export the container as a texture and make a simple workaround like that:

let options = { target:myContainer } 
let texture = app.renderer.extract.texture(options);

but when the container exceed the texture size limit, this workaround cannot work and besides, it adds a new texture to the memory etc, which was well handled in V7 and all previous versions of Pixi...

### Additional Information

Thanks a lot !

**Comment by Makio64** [comment]
In v8 I didnt got this problem with adding 1px padding on my sprite in my spritesheet.

Also in my experience this kind of problem can be also be linked with the generation of the mipmap if the sprite is used to a smaller version of himself, then it will use the generatemipmaps and this typically result in bad behaviors with line appearing on the border like the one you screenshot.

**Comment by farscapex** [comment]
This workaround works in some cases yeah, but it does not come with the cacheAsBitmap functionalities, such as blocking all animations or updates within any cached container.

the cacheAsBitmap property was very useful in previous versions, does the team schedule to implement that again in V8 or it is just erased like that with no migration options ?

Thank you^^

**Comment by Zyie** [comment]
Hey @farscapex we are planning on adding this bac fairly soon

**Comment by CatilonyZhang** [comment]
> Hey @farscapex we are planning on adding this bac fairly soon

please make it quick ,cause without this feature many projects with numerous containers would not be able to function well

**Comment by qtiki** [comment]
@Zyie Any chance the new v8 implementation could support nested bitmap caches?

**Comment by GoodBoyDigital** [comment]
closing as [shipped](https://pixijs.com/8.x/guides/advanced/cache-as-texture) in 8.6.0 :D ! nested cache as texture should work!
