### ISSUE TITLE
Bug: 8.1.0 Text bounds with padding

### ISSUE THREAD

**Issue by andreyostapenko** [pixijs/pixijs#10500]
### Current Behavior

Looks like it's not calculating/including the bottom and right sides.

### Expected Behavior

Text returns the correct bounds.

### Steps to Reproduce

> Add text with padding.
> Observe that the bounds have the wrong dimensions.

### Environment

- **`pixi.js` version**: *e.g. 8.1.0*
- **Browser & Version**: *e.g. Version 124.0.6367.80 (Official Build) (arm64)*
- **OS & Version**: *e.g. Mac OS 14.0*
- **Running Example v8**: *e.g. <https://www.pixiplayground.com/#/edit/kPygYIZbVwghwcaLc6Tgt>*
- **Running Example v7**: *e.g. <https://jsfiddle.net/zyckop6t/1/>*

**Comment by GoodBoyDigital** [comment]
thanks for sharing! and thanks for the example too! Will take a look into this today

**Comment by GoodBoyDigital** [comment]
sorted!
