### ISSUE TITLE
Bug: textureMatrix is null in graphics. (In pixi.js 8.1.0)

### ISSUE THREAD

**Issue by iyagiggun** [pixijs/pixijs#10502]
### Current Behavior

At the first, I upgrade my pixi.js (7.x -> 8.1.0)
and, I just rendered a graphic. (a pixi.js example case)

```JS
    const realPath = new Graphics();

    realPath.moveTo(0, 0);
    realPath.lineTo(100, 200);
    realPath.lineTo(200, 200);
    realPath.lineTo(240, 100);
    realPath.stroke({ width: 2, color: 0xffffff });

    realPath.position.x = 50;
    realPath.position.y = 50;

    application.stage.addChild(realPath);
```

In some time. (in program) the code excuted [this code](https://github.com/pixijs/pixijs/blob/dev/src/scene/graphics/shared/utils/buildContextBatches.ts#L216)
![image](https://github.com/pixijs/pixijs/assets/92807945/c56c8dd5-e4cd-4c2b-9cb2-e88d69a556b7)

and failed to rendering.

![image](https://github.com/pixijs/pixijs/assets/92807945/4e7db447-ada8-4a0a-93cc-adbf7013cb66)

in that case. the `textureMatrix` (= style.matrix) was null.

### Expected Behavior

just rendering like that
![image](https://github.com/pixijs/pixijs/assets/92807945/5193e3f7-249c-4caf-96a7-9ee18d32311c)

### Steps to Reproduce

Sorry. I can't

### Environment

- **`pixi.js` version**: *8.1.0*
- **Browser & Version**: *Chrome 124.0*
- **OS & Version**: *Ubuntu 23.10*
- **Running Example**: *Sorry.. I don't have.*

### Possible Solution

Surely, I don't understand  [this code](https://github.com/pixijs/pixijs/blob/dev/src/scene/graphics/shared/utils/buildContextBatches.ts#L216) and can't make a correct solution.
but, if I excute `style.matrix = style.texture.textureMatrix` it worked well. (surely, it is not a correct solution..)
I think `style.matrix` must not be a null or deal with that case.

### Additional Information

I'm sorry if it was just my mistake and not a code problem. (maybe.. my wrong migration issue..)

thank you for making & sustaining pixi.js.

**Comment by GoodBoyDigital** [comment]
thanks for sharing @iyagiggun , the above code looks good and should work as intended! 

[Playground](https://www.pixiplayground.com/#/edit/YM4UD_wEBBMO4Vh45F4_p) seems to work ok.

Lets try to dig into the differences! Any context you can share will be helpful!

- are you using Texture.WHITE anywhere?
- are you passing in a texture into the style at any point?
- are you destroying the graphics in you app?

**Comment by iyagiggun** [comment]
oh... I'm sorry. it's entirely my mistakes.
I wrote.
```TS
const {
  Graphics, TextStyle, Text,
  Sprite,
} = require('pixi.js'); // << require..
```
Surely, I changed it to 'import' and the problem was solved.

Sorry to wasting your time and thank you for your help.

Have a nice day!

**Comment by GoodBoyDigital** [comment]
no worrries! glad its sorted 👍
