### ISSUE TITLE
Custom filter not working (copied from example)

### ISSUE THREAD

**Issue by weepy** [pixijs/pixijs#10518]
### Current Behavior

The custom filter example works on the PIXI examples website. However if I copy and paste it - it no longer works.

### Expected Behavior

Should see the glsl filter working ok.

### Steps to Reproduce

Here is a stackblitz

https://stackblitz.com/edit/stackblitz-starters-ef4zpt?file=index.html

### Environment

Chrome , Macos, latest pixijs

**Comment by GoodBoyDigital** [comment]
looks like a sneaky  `fg.r= 0.0;` line got added! removing it will make the demo work as intended 👍
