### ISSUE TITLE
Bug: ClassRef is not a constructor

### ISSUE THREAD

**Issue by meghe2000** [pixijs/pixijs#10526]
### Current Behavior

ClassRef is not a constructor
TypeError: ClassRef is not a constructor
    at WebGLRenderer._addSystem (webpack://game-a/./node_modules/pixi.js/lib/rendering/renderers/shared/system/AbstractRenderer.mjs?:201:20)
    at WebGLRenderer._addSystems (webpack://game-a/./node_modules/pixi.js/lib/rendering/renderers/shared/system/AbstractRenderer.mjs?:188:12)
    at new _AbstractRenderer (webpack://game-a/./node_modules/pixi.js/lib/rendering/renderers/shared/system/AbstractRenderer.mjs?:51:10)
    at new WebGLRenderer (webpack://game-a/./node_modules/pixi.js/lib/rendering/renderers/gl/WebGLRenderer.mjs?:81:5)
    at autoDetectRenderer (webpack://game-a/./node_modules/pixi.js/lib/rendering/renderers/autoDetectRenderer.mjs?:57:20)
    at async _Application.init (webpack://game-a/./node_modules/pixi.js/lib/app/Application.mjs?:29:21)
    at async start (webpack://game-a/./game.js?:7:5)

### Expected Behavior

Not getting an error related to ClassRef.

### Steps to Reproduce
```
import { Application } from 'pixi.js';

async function start() {
    const app = new Application();
    await app.init({ width: 640, height: 360 });

}
start();
```
### Environment

- **`pixi.js` version**: *e.g. 8.1.1*
- **Browser & Version**: *e.g. Chrome 124*
- **OS & Version**: *e.g. windows 10*

**Comment by meghe2000** [comment]
I conducted a new review and realized that when I add this code to my project, this issue arises. I need the functions with the same name.

```
Array.prototype.remove = function (item) { return this.splice(this.indexOf(item), 1) }
Array.prototype.insert = function (index) { this.splice.apply(this, [index, 0].concat(Array.prototype.slice.call(arguments, 1))); return this; }
```

**Comment by bigtimebuddy** [comment]
In general, adding prototype methods to global objects is not a good practice. It can lead to issues such as this, where we are doing a for-loop and it picks up these methods as enumerable. We see this sometimes with Object.prototype method because we often enumerate through the keys. The best solution is to create utility methods (e.g., `ArrayUtils.remove(arr, item)`). If you are going to add prototype chain methods, make sure they are not enumerable like this:

```js
Object.defineProperties(Array.prototype, {
  remove: {
    enumerable: false,
    get(item) {
      return this.splice(this.indexOf(item), 1);
    }
  }
});
```

**Comment by Procenkin** [comment]
I get an error: 
```
AbstractRenderer.js:286 Uncaught (in promise) 
TypeError: ClassRef is not a constructor
    at WebGLRenderer._addSystem (AbstractRenderer.js:286:20)
    at WebGLRenderer._addSystems (AbstractRenderer.js:271:14)
    at WebGLRenderer._callee$ (AbstractRenderer.js:87:20)
    at tryCatch (AbstractRenderer.js:4:1062)
    at Generator.eval (AbstractRenderer.js:4:3012)
    at Generator.eval [as next] (AbstractRenderer.js:4:1699)
    at asyncGeneratorStep (AbstractRenderer.js:8:103)
    at _next (AbstractRenderer.js:9:194)
```

On my page in  <head> I have jQuery v3.3.1 connected ( <script src="/assets/js/jquery.min.js"></script>) , as well as bundle.js ( <script src="/assets/js/react/bundle.js"></script>), which is assembled by webpack. In bundle.js an application written in pixi.js version 8. If I disable jQuery, there is no error. Unfortunately I can't disable jQuery.
```

import React, {useEffect, useRef, useState} from 'react';
import App from "./App";
import {Application, Assets, Sprite, Texture} from "pixi.js";
import Preloader from "../../../../../widget/components/preloader";
import {
    graphicsDrawSelect,
    graphicsExtremum, graphicsHover,
    graphicsPlace,
    graphicsSelect,
    graphicsSquare,
    graphicsTooltip,
    sprites,
    worldContainer
} from "./utils/Const";
import {setRole} from "./utils/Common";

var pixiApp = null;

const Index: React.FC<{ data: any, handlers: any, config: any }> = ({data, handlers, config}) => {
    const containerRef: React.MutableRefObject<any> = useRef()
    const [init, setInit] = useState(false)

    useEffect(() => {
        pixiApp = new Application()
        initApp()
        setRole(config)
        return () => {
            pixiApp = null
            graphicsPlace.clear()
            graphicsExtremum.clear()
            graphicsSquare.clear()
            graphicsTooltip.clear()
            graphicsSelect.clear()
            graphicsDrawSelect.clear()
            graphicsHover.clear()
        };
    }, []);

    const initApp = async () => {
        await pixiApp.init({
            background: '#F2F8FF',
            sharedTicker: false,
            antialias: true,
            resizeTo: window,
        });

        containerRef.current.appendChild(pixiApp.canvas);
        pixiApp.stage.label = 'stage'
        pixiApp.stage.hitArea = pixiApp.screen;
        pixiApp.stage.eventMode = 'static';
        worldContainer.interactive = true;
        globalThis.__PIXI_APP__ = pixiApp;

        const alert = await Assets.load('/assets/images/floors/sprite/alert.png');
        const booked = await Assets.load('/assets/images/floors/sprite/booked.png');
        const error = await Assets.load('/assets/images/floors/sprite/error.png');
        const lock = await Assets.load('/assets/images/floors/sprite/lock.png');
        sprites.alert = new Sprite(alert);
        sprites.booked = new Sprite(booked);
        sprites.error = new Sprite(error);
        sprites.lock = new Sprite(lock);

        setRole(config)
        setInit(true)
    }

    return (
        <div>
            {init ? <App data={data} handlers={handlers} app={pixiApp} config={config}/> : <Preloader/>}
            <div className={'pixiApp'} ref={containerRef}></div>
        </div>
    );
};

export default Index;

```

**Comment by baba-smila** [comment]
So it's not a bug that all of the most significant libraries in the world allow you to extend the Array class, but Pixi forces you to do otherwise?

**Comment by iShawnWang** [comment]
same issue here, core js polyfill Array.at function for me, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

**Comment by iShawnWang** [comment]
Could we use Array.forEach simply 
https://github.com/pixijs/pixijs/blob/9d177e2d2d3c33df2b0ae7afef180c5028e4d3af/src/rendering/renderers/shared/system/AbstractRenderer.ts#L438
