### ISSUE TITLE
Bug: `filterArea` only works if it is set before `filters`

### ISSUE THREAD

**Issue by vitch** [pixijs/pixijs#10524]
### Current Behavior

```js
foo.filters = [filter];
foo.filterArea = new Rectangle(0, 0, 500, 100);
```

ignores the `filterArea` but:

```js
foo.filterArea = new Rectangle(0, 0, 500, 100);
foo.filters = [filter];
```

applies it.

### Expected Behavior

Either it doesn't matter when you set `filterArea` or at least the docs call out this requirement. One person in Discord told me the current behaviour was probably a bug

### Steps to Reproduce

Please see a playground [here](https://pixijs.com/8.x/playground?state=eyJmaWxlcyI6eyIvc3JjL2luZGV4LmpzIjp7ImNvZGUiOiIvKipcbiAqIFRoaXMgZXhhbXBsZSBkZW1vbnN0cmF0ZXMgdGhhdCBgZmlsdGVyQXJlYWAgb25seSB3b3JrcyBpZiBpdCBpcyBzZXQgKmJlZm9yZSogYGZpbHRlcnNgXG4gKi9cblxuaW1wb3J0IHsgQXBwbGljYXRpb24sIEFzc2V0cywgU3ByaXRlLCBDb2xvck1hdHJpeEZpbHRlciwgUmVjdGFuZ2xlIH0gZnJvbSAncGl4aS5qcyc7XG5cbihhc3luYyAoKSA9Plxue1xuICAgIGNvbnN0IGFwcCA9IG5ldyBBcHBsaWNhdGlvbigpO1xuXG4gICAgYXdhaXQgYXBwLmluaXQoeyByZXNpemVUbzogd2luZG93IH0pO1xuXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChhcHAuY2FudmFzKTtcblxuICAgIGF3YWl0IEFzc2V0cy5sb2FkKFtcbiAgICAgICAgJ2h0dHBzOi8vcGl4aWpzLmNvbS9hc3NldHMvcGl4aS1maWx0ZXJzL2JnX2RlcHRoX2JsdXIuanBnJyxcbiAgICAgICAgJ2h0dHBzOi8vcGl4aWpzLmNvbS9hc3NldHMvcGl4aS1maWx0ZXJzL2RlcHRoX2JsdXJfbW9ieS5qcGcnLFxuICAgIF0pO1xuXG4gICAgY29uc3QgYmcgPSBTcHJpdGUuZnJvbSgnaHR0cHM6Ly9waXhpanMuY29tL2Fzc2V0cy9waXhpLWZpbHRlcnMvYmdfZGVwdGhfYmx1ci5qcGcnKTtcblxuICAgIGJnLndpZHRoID0gYXBwLnNjcmVlbi53aWR0aDtcbiAgICBiZy5oZWlnaHQgPSBhcHAuc2NyZWVuLmhlaWdodDtcbiAgICBhcHAuc3RhZ2UuYWRkQ2hpbGQoYmcpO1xuXG4gICAgZnVuY3Rpb24gYWRkUm9ib3QoYXBwbHlGaWx0ZXJBcmVhRmlyc3QpIHtcbiAgICAgICAgY29uc3QgbGl0dGxlUm9ib3QgPSBTcHJpdGUuZnJvbSgnaHR0cHM6Ly9waXhpanMuY29tL2Fzc2V0cy9waXhpLWZpbHRlcnMvZGVwdGhfYmx1cl9tb2J5LmpwZycpO1xuXG4gICAgICAgIGxpdHRsZVJvYm90LnkgPSAxMDA7XG4gICAgICAgIGFwcC5zdGFnZS5hZGRDaGlsZChsaXR0bGVSb2JvdCk7XG5cbiAgICAgICAgY29uc3QgZmlsdGVyID0gbmV3IENvbG9yTWF0cml4RmlsdGVyKCk7XG4gICAgICAgIGZpbHRlci5ncmV5c2NhbGUoLjMpO1xuXG4gICAgICAgIGlmIChhcHBseUZpbHRlckFyZWFGaXJzdCkge1xuICAgICAgICAgICAgbGl0dGxlUm9ib3QuZmlsdGVyQXJlYSA9IG5ldyBSZWN0YW5nbGUoMCwgMCwgNTAwLCAxMDApO1xuICAgICAgICAgICAgbGl0dGxlUm9ib3QuZmlsdGVycyA9IFtmaWx0ZXJdO1xuICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgICAgbGl0dGxlUm9ib3QuZmlsdGVycyA9IFtmaWx0ZXJdO1xuICAgICAgICAgICAgbGl0dGxlUm9ib3QuZmlsdGVyQXJlYSA9IG5ldyBSZWN0YW5nbGUoMCwgMCwgNTAwLCAxMDApO1xuICAgICAgICB9XG4gICAgICAgIHJldHVybiBsaXR0bGVSb2JvdDtcbiAgICB9XG5cbiAgICBsZXQgcm9ib3QxID0gYWRkUm9ib3QodHJ1ZSk7XG4gICAgcm9ib3QxLnggPSBhcHAuc3RhZ2Uud2lkdGggLyA0IC0gMjAwO1xuICAgIGxldCByb2JvdDIgPSBhZGRSb2JvdChmYWxzZSk7XG4gICAgcm9ib3QyLnggPSBhcHAuc3RhZ2Uud2lkdGggKiAzIC8gNCAtIDIwMDtcblxufSkoKTtcblxuXG4ifSwiL3NyYy9zdHlsZXMuY3NzIjp7ImNvZGUiOiJib2R5IHsgbWFyZ2luOiAwOyBvdmVyZmxvdzogaGlkZGVuOyB9In0sIi9pbmRleC5odG1sIjp7ImNvZGUiOiJcbjwhRE9DVFlQRSBodG1sPlxuICA8aHRtbD5cbiAgPGhlYWQ%2BXG4gIDx0aXRsZT5QaXhpSlMgUGxheWdyb3VuZDwvdGl0bGU%2BXG4gIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiIC8%2BXG4gIDxsaW5rIHJlbD1cInN0eWxlc2hlZXRcIiBocmVmPVwic3JjL3N0eWxlcy5jc3NcIj5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2NyaXB0IHNyYz1cInNyYy9pbmRleC5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuPC9odG1sPiJ9LCIvcGFja2FnZS5qc29uIjp7ImNvZGUiOiJ7XG4gIFwic2NyaXB0c1wiOiB7XG4gICAgXCJzdGFydFwiOiBcInBhcmNlbCBpbmRleC5odG1sIC0tb3BlblwiLFxuICAgIFwiYnVpbGRcIjogXCJwYXJjZWwgYnVpbGQgaW5kZXguaHRtbFwiXG4gIH0sXG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBpeGkuanNcIjogXCI4LjEuMFwiXG4gIH0sXG4gIFwiZGV2RGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBhcmNlbC1idW5kbGVyXCI6IFwiXjEuNi4xXCIsXG4gICAgXCJAYmFiZWwvY29yZVwiOiBcIl43LjIxLjNcIixcbiAgICBcIkBiYWJlbC9wbHVnaW4tcHJvcG9zYWwtY2xhc3MtcHJvcGVydGllc1wiOiBcIl43LjEwLjFcIlxuICB9LFxuICBcIm1haW5cIjogXCIvaW5kZXguaHRtbFwiXG59In0sIi8uYmFiZWxyYyI6eyJjb2RlIjoie1xuICBcInByZXNldHNcIjogW1xuICAgIFtcbiAgICAgIFwiQGJhYmVsL3ByZXNldC1lbnZcIixcbiAgICAgIHtcbiAgICAgICAgXCJ1c2VCdWlsdEluc1wiOiBcImVudHJ5XCIsXG4gICAgICAgIFwiY29yZWpzXCI6IFwiMy4yOVwiLFxuICAgICAgICBcInRhcmdldHNcIjogXCJsYXN0IDIgY2hyb21lIHZlcnNpb25zXCJcbiAgICAgIH1cbiAgICBdXG4gIF0sXG4gIFwicGx1Z2luc1wiOiBbXG4gICAgXCJAYmFiZWwvcGx1Z2luLXByb3Bvc2FsLWNsYXNzLXByb3BlcnRpZXNcIlxuICBdXG59In0sIi9zYW5kYm94LmNvbmZpZy5qc29uIjp7ImNvZGUiOiJ7XG4gICAgICAgICAgICAgICAgXCJpbmZpbml0ZUxvb3BQcm90ZWN0aW9uXCI6IGZhbHNlXG4gICAgICAgICAgICB9In19LCJ2aXNpYmxlRmlsZXMiOlsiL3NyYy9pbmRleC5qcyJdLCJhY3RpdmVGaWxlIjoiL3NyYy9pbmRleC5qcyJ9&exampleId=custom) which shows the problem

### Environment

- **`pixi.js` version**: 8.0.5
- **Browser & Version**: N/A
- **OS & Version**: N/A
- **Running Example**: [Here](https://pixijs.com/8.x/playground?state=eyJmaWxlcyI6eyIvc3JjL2luZGV4LmpzIjp7ImNvZGUiOiIvKipcbiAqIFRoaXMgZXhhbXBsZSBkZW1vbnN0cmF0ZXMgdGhhdCBgZmlsdGVyQXJlYWAgb25seSB3b3JrcyBpZiBpdCBpcyBzZXQgKmJlZm9yZSogYGZpbHRlcnNgXG4gKi9cblxuaW1wb3J0IHsgQXBwbGljYXRpb24sIEFzc2V0cywgU3ByaXRlLCBDb2xvck1hdHJpeEZpbHRlciwgUmVjdGFuZ2xlIH0gZnJvbSAncGl4aS5qcyc7XG5cbihhc3luYyAoKSA9Plxue1xuICAgIGNvbnN0IGFwcCA9IG5ldyBBcHBsaWNhdGlvbigpO1xuXG4gICAgYXdhaXQgYXBwLmluaXQoeyByZXNpemVUbzogd2luZG93IH0pO1xuXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChhcHAuY2FudmFzKTtcblxuICAgIGF3YWl0IEFzc2V0cy5sb2FkKFtcbiAgICAgICAgJ2h0dHBzOi8vcGl4aWpzLmNvbS9hc3NldHMvcGl4aS1maWx0ZXJzL2JnX2RlcHRoX2JsdXIuanBnJyxcbiAgICAgICAgJ2h0dHBzOi8vcGl4aWpzLmNvbS9hc3NldHMvcGl4aS1maWx0ZXJzL2RlcHRoX2JsdXJfbW9ieS5qcGcnLFxuICAgIF0pO1xuXG4gICAgY29uc3QgYmcgPSBTcHJpdGUuZnJvbSgnaHR0cHM6Ly9waXhpanMuY29tL2Fzc2V0cy9waXhpLWZpbHRlcnMvYmdfZGVwdGhfYmx1ci5qcGcnKTtcblxuICAgIGJnLndpZHRoID0gYXBwLnNjcmVlbi53aWR0aDtcbiAgICBiZy5oZWlnaHQgPSBhcHAuc2NyZWVuLmhlaWdodDtcbiAgICBhcHAuc3RhZ2UuYWRkQ2hpbGQoYmcpO1xuXG4gICAgZnVuY3Rpb24gYWRkUm9ib3QoYXBwbHlGaWx0ZXJBcmVhRmlyc3QpIHtcbiAgICAgICAgY29uc3QgbGl0dGxlUm9ib3QgPSBTcHJpdGUuZnJvbSgnaHR0cHM6Ly9waXhpanMuY29tL2Fzc2V0cy9waXhpLWZpbHRlcnMvZGVwdGhfYmx1cl9tb2J5LmpwZycpO1xuXG4gICAgICAgIGxpdHRsZVJvYm90LnkgPSAxMDA7XG4gICAgICAgIGFwcC5zdGFnZS5hZGRDaGlsZChsaXR0bGVSb2JvdCk7XG5cbiAgICAgICAgY29uc3QgZmlsdGVyID0gbmV3IENvbG9yTWF0cml4RmlsdGVyKCk7XG4gICAgICAgIGZpbHRlci5ncmV5c2NhbGUoLjMpO1xuXG4gICAgICAgIGlmIChhcHBseUZpbHRlckFyZWFGaXJzdCkge1xuICAgICAgICAgICAgbGl0dGxlUm9ib3QuZmlsdGVyQXJlYSA9IG5ldyBSZWN0YW5nbGUoMCwgMCwgNTAwLCAxMDApO1xuICAgICAgICAgICAgbGl0dGxlUm9ib3QuZmlsdGVycyA9IFtmaWx0ZXJdO1xuICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgICAgbGl0dGxlUm9ib3QuZmlsdGVycyA9IFtmaWx0ZXJdO1xuICAgICAgICAgICAgbGl0dGxlUm9ib3QuZmlsdGVyQXJlYSA9IG5ldyBSZWN0YW5nbGUoMCwgMCwgNTAwLCAxMDApO1xuICAgICAgICB9XG4gICAgICAgIHJldHVybiBsaXR0bGVSb2JvdDtcbiAgICB9XG5cbiAgICBsZXQgcm9ib3QxID0gYWRkUm9ib3QodHJ1ZSk7XG4gICAgcm9ib3QxLnggPSBhcHAuc3RhZ2Uud2lkdGggLyA0IC0gMjAwO1xuICAgIGxldCByb2JvdDIgPSBhZGRSb2JvdChmYWxzZSk7XG4gICAgcm9ib3QyLnggPSBhcHAuc3RhZ2Uud2lkdGggKiAzIC8gNCAtIDIwMDtcblxufSkoKTtcblxuXG4ifSwiL3NyYy9zdHlsZXMuY3NzIjp7ImNvZGUiOiJib2R5IHsgbWFyZ2luOiAwOyBvdmVyZmxvdzogaGlkZGVuOyB9In0sIi9pbmRleC5odG1sIjp7ImNvZGUiOiJcbjwhRE9DVFlQRSBodG1sPlxuICA8aHRtbD5cbiAgPGhlYWQ%2BXG4gIDx0aXRsZT5QaXhpSlMgUGxheWdyb3VuZDwvdGl0bGU%2BXG4gIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiIC8%2BXG4gIDxsaW5rIHJlbD1cInN0eWxlc2hlZXRcIiBocmVmPVwic3JjL3N0eWxlcy5jc3NcIj5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2NyaXB0IHNyYz1cInNyYy9pbmRleC5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuPC9odG1sPiJ9LCIvcGFja2FnZS5qc29uIjp7ImNvZGUiOiJ7XG4gIFwic2NyaXB0c1wiOiB7XG4gICAgXCJzdGFydFwiOiBcInBhcmNlbCBpbmRleC5odG1sIC0tb3BlblwiLFxuICAgIFwiYnVpbGRcIjogXCJwYXJjZWwgYnVpbGQgaW5kZXguaHRtbFwiXG4gIH0sXG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBpeGkuanNcIjogXCI4LjEuMFwiXG4gIH0sXG4gIFwiZGV2RGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBhcmNlbC1idW5kbGVyXCI6IFwiXjEuNi4xXCIsXG4gICAgXCJAYmFiZWwvY29yZVwiOiBcIl43LjIxLjNcIixcbiAgICBcIkBiYWJlbC9wbHVnaW4tcHJvcG9zYWwtY2xhc3MtcHJvcGVydGllc1wiOiBcIl43LjEwLjFcIlxuICB9LFxuICBcIm1haW5cIjogXCIvaW5kZXguaHRtbFwiXG59In0sIi8uYmFiZWxyYyI6eyJjb2RlIjoie1xuICBcInByZXNldHNcIjogW1xuICAgIFtcbiAgICAgIFwiQGJhYmVsL3ByZXNldC1lbnZcIixcbiAgICAgIHtcbiAgICAgICAgXCJ1c2VCdWlsdEluc1wiOiBcImVudHJ5XCIsXG4gICAgICAgIFwiY29yZWpzXCI6IFwiMy4yOVwiLFxuICAgICAgICBcInRhcmdldHNcIjogXCJsYXN0IDIgY2hyb21lIHZlcnNpb25zXCJcbiAgICAgIH1cbiAgICBdXG4gIF0sXG4gIFwicGx1Z2luc1wiOiBbXG4gICAgXCJAYmFiZWwvcGx1Z2luLXByb3Bvc2FsLWNsYXNzLXByb3BlcnRpZXNcIlxuICBdXG59In0sIi9zYW5kYm94LmNvbmZpZy5qc29uIjp7ImNvZGUiOiJ7XG4gICAgICAgICAgICAgICAgXCJpbmZpbml0ZUxvb3BQcm90ZWN0aW9uXCI6IGZhbHNlXG4gICAgICAgICAgICB9In19LCJ2aXNpYmxlRmlsZXMiOlsiL3NyYy9pbmRleC5qcyJdLCJhY3RpdmVGaWxlIjoiL3NyYy9pbmRleC5qcyJ9&exampleId=custom)

**Comment by BlackRam-oss** [comment]
Hi, I also encountered the same error and I was talking about it in chat.
Maybe this solution can help:

```ts
const DEFAULT_OPTIONS = {
  // ...
}

class Sprite{
  constructor(_options = {}){
    const options = Object.assign({}, _options, DEFAULT_OPTIONS);
    // do stuff with the options, like set the sprite's coordinates
  }
}
```

**Comment by GoodBoyDigital** [comment]
yeah, that looks like a bug! thanks for sharing - will take a look!

**Comment by GoodBoyDigital** [comment]
sorted :D
