### ISSUE TITLE
Bug: new Sprite gives me an error because the texture is not passed

### ISSUE THREAD

**Issue by BlackRam-oss** [pixijs/pixijs#10528]
### Current Behavior

it gives me an error. because the texture is not passed

```
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'defaultAnchor')
    at _Sprite (/home/blackram/game-template/node_modules/pixi.js/src/scene/sprite/Sprite.ts:119:26)
    at <anonymous> (/home/blackram/game-template/src/values/locations.tsx:13:1)
```

### Expected Behavior

that a blank texture is added by default. or force you to add a texture

### Steps to Reproduce

```ts
new Sprite({
    x: 100,
    y: 100,
});
```

### Environment

- **`pixi.js` version**: 8.1.1
- **Browser & Version**: Chrome
- **OS & Version**: Windows

### Possible Solution

```ts
const DEFAULT_OPTIONS = {
  // ...
}

class Sprite{
  constructor(_options = {}){
    const options = Object.assign({}, _options, DEFAULT_OPTIONS);
    // do stuff with the options, like set the sprite's coordinates
  }
}
```

**Comment by bigtimebuddy** [comment]
Thanks, this definitely is not intended. We should support undefined texture in the constructor. Suggestion is setting a default in the options destructure or reordering the default anchor line to be after the texture set.
