### ISSUE TITLE
Bug: Some line segments are rendered as rays in some mobile

### ISSUE THREAD

**Issue by hblnb1314** [pixijs/pixijs#10522]
### Current Behavior

![IMG_20240509_183006](https://github.com/pixijs/pixijs/assets/37140358/e02376f2-4bcd-43c2-b026-3ba88f549a05)
Some line segments are rendered as rays when line length large

### Expected Behavior

![IMG_20240509_183033](https://github.com/pixijs/pixijs/assets/37140358/47c1443f-da42-4da2-a94a-722add1e30c0)

### Steps to Reproduce

The progress use mesh to render line

### Environment

- **`pixi.js` version**: *6.5.10*
- **Browser & Version**: *Chrome 107*
- **OS & Version**: *android 13 oppo reno 6*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by bigtimebuddy** [comment]
@hblnb1314 how did you resolve this issue? It can be helpful to document the resolution for future developers.

**Comment by hblnb1314** [comment]
> @hblnb1314 how did you resolve this issue? It can be helpful to document the resolution for future developers.

yes,problem has been solved , solve it by set glsl  precision mediump to highp
