### ISSUE TITLE
Bug: Text displays as white or black rectangle on iOS 12 & 13

### ISSUE THREAD

**Issue by bilasyurii** [pixijs/pixijs#10535]
### Current Behavior

On iOS 12 or 13 create a text with Pixi 8.
It's displayed as a white or black rectangle.

### Expected Behavior

On iOS 12 or 13 create a text with Pixi 8.
It's displayed correctly as text. Same as on other devices.

### Steps to Reproduce

Check this playground:
https://codepen.io/Yurii-Bilas/full/KKLpbOb
Notice how the text is rendered - it's displayed as white or black rectangle.
![image](https://github.com/pixijs/pixijs/assets/42247001/f79dfa04-63ec-457a-82c4-e2abaaae577e)
↑ ios 12.1
<img src="https://github.com/pixijs/pixijs/assets/42247001/758a6580-0216-4132-a604-8217b1d3ed43" width="400">
↑ ios 12.5.4

### Environment

- **`pixi.js` version**: *8.1.2*
- **Browser & Version**: *Chrome 108*
- **OS & Version**: *iOS 12.1 (browserstack), iOS 12.5.4 (real device), iOS 13.4 (browserstack)*
- **Running Example**: *<https://codepen.io/Yurii-Bilas/full/KKLpbOb>*

### Possible Solution

Add logic for handling devices that don't support 16 gl textures, but only 8.

### Additional Information

Tested on browserstack.
In console there are a few errors.
![image](https://github.com/pixijs/pixijs/assets/42247001/4cc549f4-8d3f-4cea-9f47-665d7ed780c2)
For globalThis issue I've added a polyfill. But that one visible is from codepen - ignore it.
INVALID_ENUM is an interesting one. I've debugged it and the error happens when activeTexture receives gl.TEXTURE0 + 8 or more (9...15). Maybe on older versions of iOS there are only 8 textures allowed for this.
The last one seems to be connected to the same 8 textures problem.
![image](https://github.com/pixijs/pixijs/assets/42247001/56be53e0-c941-43a1-9d21-60c9deb555a6)

**Comment by GoodBoyDigital** [comment]
thanks for sharing @bilasyurii ! 
Can you try forcing webgl 1 to see if it fixes the issue? thanks!

**Comment by bilasyurii** [comment]
@GoodBoyDigital hi! yep, updated codepen to prefer webgl 1. still reproduceable
