### ISSUE TITLE
Bug: Redrawing `Graphics` leaks memory

### ISSUE THREAD

**Issue by AlexeyNigin** [pixijs/pixijs#10549]
### Current Behavior

I have a project with ~100 `Graphics` objects. Each `Graphics` object is very simple - just a couple lines or circles. However, I need to clear and redraw all of these objects from scratch every frame.

I previously used PixiJS v6.3.2, and my app could run at 140fps for hours with no memory issues. I updated to PixiJS v.8.1.3, and now my app's memory usage grows by ~10MB/s; within minutes, memory usage goes into gigabytes and it becomes a problem.

See below for a minimal example demonstrating this behavior.

### Expected Behavior

The `Graphics` objects should not consume unbounded amount of memory.

### Steps to Reproduce

Here is a minimal example demonstrating the behavior. On my computer at 140fps, this script consumes about 3MB/s of memory. Sometimes the memory usage drops for a second or two, suggesting that some garbage collection is happening, but in just a few minutes the memory usage reached 800MB.

```js
import { Application, Graphics } from 'pixi.js';

(async () =>
{
    // Create a new application
    const app = new Application();

    // Initialize the application
    await app.init({ background: '#222222', resizeTo: window });

    // Append the application canvas to the document body
    document.body.appendChild(app.canvas);

    // Create 100 Graphics objects
    for (let i = 0; i < 100; ++i) app.stage.addChild(new Graphics());

    // Listen for animate update
    app.ticker.add(() =>
    {
        app.stage.children.forEach(graphic => {
            // Redraw each Graphics object from scratch
            graphic
                .clear()
                .circle(100, 100, 10)
                .fill(0xffffff);
        });
    });
})();
```

Live example: <https://pixiplayground.com/#/edit/_1dA0NywAeA34aIS6BA7z> - do not run it unattended, because after a while it can leak enough memory to lag/crash your browser.

### Environment

- **`pixi.js` version**: *8.1.3*
- **Browser & Version**: *Chrome 124*
- **OS & Version**: *Ubuntu 20.04*
- **Running Example**: *<https://pixiplayground.com/#/edit/_1dA0NywAeA34aIS6BA7z>* - do not run unattended!

### Possible Solution

I don't know the exact cause of the problem, but my best guess is that something is wrong in `GraphicsContext` / `GraphicsPath`. This code in particular seems like it can use up some memory: <https://github.com/pixijs/pixijs/blob/v8.1.3/src/scene/graphics/shared/GraphicsContext.ts#L347-L352>

### Additional Information

If redrawing `Graphics` objects each frame is something I should absolutely not be doing, I am open to hearing alternatives - what I really want to accomplish is crisp procedural animation.

Severity: Unfortunately, this is a critical issue for me, I can't upgrade to v8 until this is resolved, because the app is completely unusable in that state. I can keep using v6 for as long as this takes to resolve, though.

**Comment by AlexeyNigin** [comment]
I let the attached example run for a few seconds in Firefox, and then took a memory snapshot. In the snapshot, I noticed a 4MB array that seems to be `GraphicsContextSystem:_needsContextNeedsRebuild`.

Looking through `GraphicsContextSystem.ts`, I see that every time any context gets updated, a reference to the context gets saved to `_needsContextNeedsRebuild`. However, `_needsContextNeedsRebuild` only gets cleared (or gets in any way smaller) when the `GraphicsContextSystem` is destroyed, which in a running app I assume is never.

I doubt this is the entire problem, because that array only stores references to the same 100 contexts, and there is growing object memory unexplained by this array, but I think it's part of the puzzle.

**Comment by GoodBoyDigital** [comment]
thanks for posting the example - will take look!
