### ISSUE TITLE
Bug: 8.1.4 break text

### ISSUE THREAD

**Issue by Makio64** [pixijs/pixijs#10556]
### Current Behavior

version 8.1.3 / version 8.1.4 : 

<img width="158" alt="Screenshot 2024-05-20 at 22 06 05" src="https://github.com/pixijs/pixijs/assets/213351/92f75e78-84a6-4ecf-bdd4-863e78ecc61c">

<img width="162" alt="Screenshot 2024-05-20 at 22 03 01" src="https://github.com/pixijs/pixijs/assets/213351/6539f4de-59a4-477a-84d5-dfa0519d09fe">

the bug vary across the different texts in the game but its like the texture atlas / the texture containing the characters is totally lost.. :)

My script for text writing  : 

```
import stage from "@/makio/core/stage"
import { Text, Container} from "pixi.js"

export default class WritingText extends Container{
	constructor(styleOptions = {}){
		super()
		let style = {fontFamily: 'Quantico',fill: 0x1C005C, fontSize: 30, wordWrap: true, wordWrapWidth: (stage.width-40)*2, align: 'left', lineHeight :50, ...styleOptions}
		this.text = new Text({text:``, style})
		this.text.position.x = 20
		this.text.position.y = 40
		this.text.scale.set(.5,.5)
		this.letters = []
		this.msg = ''
		this.addChild(this.text)

		stage.onUpdate.add(this.update)
	}

	update = (dt) => {
		if (!this.letters.length) return;

		this.time += dt;
		let delay = 8;
		while (this.time >= delay) {
			if (this.letters.length > 0) {
				this.msg += this.letters.shift();
				this.text.text = this.msg;
			}
			this.time -= delay;
		}
	}

	write(text){
		this.time = 0
		this.msg = ''
		this.letters = text.split('')
	}
}
```

### Expected Behavior

The text still work in 8.1.x :)

### Steps to Reproduce

change a text over time.

### Environment

`pixi.js` version**: 8.1.4

**Comment by GoodBoyDigital** [comment]
heya, thanks for flagging - to confirm this is 8.1.3 -> 8.1.4?

**Comment by GoodBoyDigital** [comment]
heya, i am struggling to recreate this one! 
Would you mind testing the game out with [this branch](https://github.com/pixijs/pixijs/tree/test/gl-upload-tweak) please?

Thanks!
