### ISSUE TITLE
Bug: WebGPURenderer: TypeError: Cannot read properties of null (reading 'features') with NW.js v.0.86

### ISSUE THREAD

**Issue by Matt-Maerz** [pixijs/pixijs#10554]
### Current Behavior

WebGPURenderer is not loaded with nw.js v.0.86

`renderer = new PIXI.WebGPURenderer();`
`    await renderer.init({`
`        width: SETTINGS.RESOLUTION_WIDTH,`
`        height: SETTINGS.RESOLUTION_HEIGHT,`
`        background: 0x000000`
`    });`

Error message:
![error GPURenderer with nwjs](https://github.com/pixijs/pixijs/assets/10009596/175bb83d-726b-4efb-84c4-8556e96df7f6)

### Expected Behavior

WebGPURenderer is loaded

### Steps to Reproduce

Javascript Frontend:

`renderer = new PIXI.WebGPURenderer();`
`    await renderer.init({`
`        width: SETTINGS.RESOLUTION_WIDTH,`
`        height: SETTINGS.RESOLUTION_HEIGHT,`
`        background: 0x000000`
`    });`

Compilation to .exe win64 with https://nwjs.io/

### Environment

- **`pixi.js` version**: *8.1.4*
- **Browser & Version**: *Chrome 119.0.6045.200*
- **OS & Version**: *Windows Version 11 Home 23H2*

**Comment by Zyie** [comment]
Hey, this is a known issue that you will want to use `autoDetectRenderer({ preference: 'webgpu', width. height, background })` for now

https://github.com/pixijs/pixijs/issues/10366
