### ISSUE TITLE
Bug: Update Matrix uniforms crashes V8

### ISSUE THREAD

**Issue by shirecoding** [pixijs/pixijs#10553]
### Current Behavior

Unable to update uniform matrix in shader by setting the matrix as container's worldTransform

### Expected Behavior

Should be able to update the uniform matrix by passing in the worldStage container's worldTransform

### Steps to Reproduce

With the following shader
```
Shader.from({
        gl: shaders[s],
        resources: {
            uTexture: texture.source,
            uniforms: {
                uWorldStageTransform: { <----- this crashes
                    value: new Matrix(),
                    type: "mat3<f32>",
                },
                uTx: { <---- this works
                    value: 0,
                    type: "f32",
                },
                uTy: {
                    value: 0,
                    type: "f32",
                },
                uTextureHeight: {
                    value: pixelHeight,
                    type: "f32",
                },
                uTextureWidth: {
                    value: pixelWidth,
                    type: "f32",
                },
            },
        },
    });
```

Updating the uniforms

// This crashes
shader.resources.uniforms.uniforms.uWorldStageTransform.a =
            worldStage.worldTransform;
(in the vert shader)
mat3 mvp = uProjectionMatrix * uWorldTransformMatrix * uWorldStageTransform * uTransformMatrix; 

// This works
shader.resources.uniforms.uniforms.uTx = t.tx;
shader.resources.uniforms.uniforms.uTy = t.ty;
(in the vert shader)
gl_Position = vec4((mvp * vec3(aPosition + aInstancePosition + vec2(uTx, uTy), 1.0)).xy, 0.0, 1.0) ;

error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at generateUniformsSync (generateUniformsSync.ts:75:57)
    at GlUniformGroupSystem._generateUniformsSync (GlUniformGroupSystem.ts:102:16)
    at GlUniformGroupSystem._createUniformSyncFunction (GlUniformGroupSystem.ts:92:36)
    at GlUniformGroupSystem._getUniformSyncFunction (GlUniformGroupSystem.ts:80:21)
    at GlUniformGroupSystem.updateUniformGroup (GlUniformGroupSystem.ts:66:35)
    at eval (eval at generateShaderSyncCode (GenerateShaderSyncCode.ts:112:12), <anonymous>:20:29)
    at GlShaderSystem.bind (GlShaderSystem.ts:95:22)
    at GlEncoderSystem.draw (GlEncoderSystem.ts:56:25)
    at GlMeshAdaptor.execute (GlMeshAdaptor.ts:83:26)
    at MeshPipe.execute (MeshPipe.ts:193:23)
```

### Environment

Pixi: 8.1.4

**Comment by GoodBoyDigital** [comment]
heya! please can you provide this as a playground? I can then help address! thanks!

**Comment by shirecoding** [comment]
Sure, here it is

https://www.pixiplayground.com/#/edit/ygcHzzCAKj51Z4OBlFQ26

you can uncomment out the part that works to see that the bunny is offset to 100 px

**Comment by GoodBoyDigital** [comment]
heya, the type should be `mat3x3<f32>` 

https://github.com/pixijs/pixijs/blob/9fd9c4662f2cc2b5999cdb143847d0db4ec9fdc6/src/rendering/renderers/shared/shader/types.ts#L2

**Comment by GoodBoyDigital** [comment]
If you are using TS, it should give type safety! The PR should make it easier to catch in the future for js too! #10562

**Comment by shirecoding** [comment]
ahh i see, i was using typescript, but it doesnt report the type errors somehow in VS code, it says it should be type string
