### ISSUE TITLE
Bug: Point missing Vector2 math

### ISSUE THREAD

**Issue by ViktorJakobsson** [pixijs/pixijs#10564]
### Current Behavior

Since Pixi 8 `Point` seem to be missing all math functions in runtime, even though they are defined on the type.

The example throws an error: `Uncaught (in promise) TypeError: point.add is not a function`

### Expected Behavior

Math functions to be there.

### Steps to Reproduce

```ts
const point = new PIXI.Point(1,1)
const point2 = new PIXI.Point(1,1)
point.add(point2)
```

### Environment

- **`pixi.js` version**: *8.1.4*
- **Browser & Version**: *Chrome 124*
- **OS & Version**: *MacOS Sonoma 14.3*
- **Running Example**: *https://pixiplayground.com/#/edit/Gh_dMFumg34tlKcbayhJ1*

**Comment by Zyie** [comment]
you need to import math-extras like this

```ts
import 'pixi.js/math-extras`
```

or if you are not using a bundler you need to include this: 
https://github.com/pixijs/pixijs/releases/download/v8.1.4/math-extras.js

**Comment by SaintPepsi** [comment]
@Zyie Doing that produces another error `Cannot find package '@pixi/core'` 
Are `@pixi/math-extras` version `7.4.2` and `pixi.js` version `8.4.1` incompatible?

```json
"pixi.js": "^8.4.1",
"@pixi/math-extras": "^7.4.2",
```

**Comment by SaintPepsi** [comment]
I think the issue arrises as well because the type for `Point` has the signature for `Vector2Math` and therefore the method for `add` which exists on `Vector2Math`'s type is also extended onto `Point`. but really it should only exist when `math-extras` has been added. see `pixi.js.d.ts` line `12769`.

should that be removed/updated perhaps?

**Comment by Zyie** [comment]
hey @SaintPepsi `math-extra` is now part of `pixi.js` when using v8, you just need to import it first

`import 'pixi.js/math-extras'`

**Comment by SaintPepsi** [comment]
My bad! I was confused as I thought `math-extras` had to be installed seperately with `@pixi/math-extras`
