### ISSUE TITLE
Bug: console.error("ERROR: Expression too complex.\n\u0000")

### ISSUE THREAD

**Issue by erikdubbelboer** [pixijs/pixijs#10580]
### Current Behavior

Since 8.1.4 around 1% of the players of my game is getting this `console.error("ERROR: Expression too complex.\n\u0000")`. I'm afraid I don't have a stack trace.

### Expected Behavior

Not getting this.

### Steps to Reproduce

I'm afraid I don't have any steps. It seems to only happen on mobile Chrome. I'm guessing it's a shader that is maybe too complex for simple phones? Since there are only a couple of `console.error` in the source, it should be possible to figure this out?

### Environment

- **`pixi.js` version**: *8.1.4*
- **Browser & Version**: *Any Chrome*
- **OS & Version**: *Android Mobile*
- **Running Example**: https://poki.com/en/preview/7e485857-686e-47f6-9588-1dacf536421b/e9b1fc4d-51d8-49dd-9b51-d531d3d07fde

**Comment by louffoster** [comment]
I have the exact same issue. It only happens to users on mobile, and it happens all of the time. You can even see this if you go to the pix examples page on a mobile device - none of them load. I've tried this with a Samsung A32. 

If I pin my Pixi version to 8.1.3 everything is fine. All later versions fail

**Comment by bigtimebuddy** [comment]
I've noticed that you been posting a few issues recently which are stack traces from, what I assume to be, your logging system with little to no reproduction steps, reproduction or any other context. 

Posting is always better than not, HOWEVER, we need more from you when you're creating issues. This project doesn't have the resources or volunteers to support individual projects. It would help us tremendously if you could do more to narrow down the issue, prove that it's Pixi's bug, and  best for us: create a reproduction or failing test.

I realize that many of your issues are only a few percentage of total users, so at the very least, please including (or add to your logging) more info about platforms and browsers versions affected. For instance, you say "mobile chrome". What mobile devices? Which versions of chrome? Which GPUs?

**Comment by louffoster** [comment]
Screenshot of errors pulled from a remote debug session is attached

![errors](https://github.com/pixijs/pixijs/assets/6174259/11f36dc8-929f-49a8-97fe-17e85c57bf1b)

**Comment by bigtimebuddy** [comment]
Is it possible to get an un-minified line number from WebGPURenderer?

**Comment by louffoster** [comment]
Not exactly sure how to do that... but I'll poke around and see if I can figure something out. It will take a bit because I just rolled back my site to use version 8.1.3.

I've also tested with another Samsung; A53, 5G model. Same problem. Steps to reproduce: simply go to a page with a pixi.js app on it - including any of the version 8.x examples.

**Comment by Zyie** [comment]
Looking at the warnings in the screenshot it seems that the `logProgramError` function is to blame:
https://github.com/pixijs/pixijs/blob/dev/src/rendering/renderers/gl/shader/program/logProgramError.ts#L79

and more specifically [gl.getShaderInfoLog()](https://github.com/pixijs/pixijs/blob/dev/src/rendering/renderers/gl/shader/program/logProgramError.ts#L13) is logged and throw this error

**Comment by louffoster** [comment]
I've reset my site to use the latest version of pixi.js, and I am back to the errors from the screenshot above. I can't figure out how to get un-minified source. 

Steps to reproduce:

1. use an android device (I've tried two: Samsung A53 (relataveliy recent)  and A32 (older) )
2. use the latest Chrome or Brave browser
3. go here: https://studio332apps.com/sweep
4. The page will just be a blue-gray square with no game
5. Remote debug and see the errors from the screenshot above
6. If you click the site header, you can try loading any of the games - all fail in the same way

More details; the site is written using Vue3. These are the dependencies:
    "axios": "^1.6.1",
    "matter-js": "^0.19.0",
    "pinia": "^2.0.14",
    "pixi.js": "^8.1.3",
    "primeicons": "^6.0.1",
    "primevue": "^3.16.0",
    "tweedle.js": "^2.1.0",
    "vue": "^3.2.37",
    "vue-cookies": "^1.7.4",
    "vue-router": "^4.1.2"

**Comment by bigtimebuddy** [comment]
Does this also produce on any of the [examples](https://pixijs.com/8.x/examples)?

**Comment by bigtimebuddy** [comment]
If examples do not reproduce, can you make a minimal example? There's a lot going on with that linked project. It's helpful to narrow it down just to make sure it isn't a code bundling issue, another dependency or some app code.

**Comment by louffoster** [comment]
On my Samsung A32 running  Chrome, Firefox or Brave none of the examples load. I don't know how to get debugging info because of the way the examples are loaded into iframes. The simple example of Basic Container is pretty bare-bones and non-functional for me.

More data points, I had a friend try with their new iPhone on my site. The page loaded, but there were still errors - it was basically a frozen view of the UI.

**Comment by louffoster** [comment]
I just hit the Basic Container example from my phone. It renders a blank blue box. I click the external link in the lower right to open in code sanbox and get the same errors. Screenshot attached.
![Screenshot_20240529_211233_Brave](https://github.com/pixijs/pixijs/assets/6174259/103d17e0-8a89-45a0-b5e1-f39c7d1bc206)

**Comment by bigtimebuddy** [comment]
Summoning @GoodBoyDigital. Thoughts?

**Comment by tzachyrm** [comment]
It happens consistently to me as well on an Android WebView. This is a big issue as it effectively makes PIXI unusable on mobile.

**Comment by tzachyrm** [comment]
And here are the unminified line numbers (v8.1.5)

<img width="1086" alt="image" src="https://github.com/pixijs/pixijs/assets/6254831/69c9b0f4-7ee0-400c-8ec7-58af8721c30c">

And the start of the full shader code:
<img width="1082" alt="image" src="https://github.com/pixijs/pixijs/assets/6254831/c4245fc1-aee8-485a-b762-4743716bf406">
