### ISSUE TITLE
Bug: Memory leak in Graphics destruction in v8

### ISSUE THREAD

**Issue by MattTreichelYeah** [pixijs/pixijs#10586]
### Current Behavior

Rapidly creating and destroying Graphics in v8 leads to a memory leak in at least Chrome, and eventually crashes with a `RangeError: Invalid array length`. Stack Trace:

```
_initContext (GraphicsContextSystem.ts:255)
updateGpuContext (GraphicsContextSystem.ts:151)
addRenderable (GraphicsPipe.ts:109)
collectAllRenderablesSimple (buildInstructions.ts:87)
collectAllRenderables (buildInstructions.ts:71)
collectAllRenderablesAdvanced (buildInstructions.ts:142)
buildInstructions (buildInstructions.ts:47)
render (RenderGroupSystem.ts:116)
emit (SystemRunner.ts:74)
render (AbstractRenderer.ts:298)
render (Application.ts:155)
emit (TickerListener.ts:64)
update (Ticker.ts:461)
_tick (Ticker.ts:163)
requestAnimationFrame (async)
_tick (Ticker.ts:167)
requestAnimationFrame (async)
_tick (Ticker.ts:167)
requestAnimationFrame (async)
_tick (Ticker.ts:167)
...
```

### Expected Behavior

In Pixi v7, this example is stable.

### Steps to Reproduce

The following example reproduces it, linked here: https://www.pixiplayground.com/#/edit/3ocZP-9nVFphFe1ozWvsQ. Chrome's "Memory" heap slowly balloons and eventually crashes with the RangeError after about 15 minutes for me. Setting it to the latest v7 version and running it in parallel doesn't run into the same problems.

If I change the destroy line to `.destroy()` or `.destroy(true)`, it doesn't seem to make a difference.

```
(async () => {
    const app = new PIXI.Application();
    await app.init({
        width: window.innerWidth,
        height: window.innerHeight,
    })
    document.body.appendChild(app.canvas);

    let rectangles = [];

    app.ticker.add(function()
    {
        for (let i = 0; i < 1000; i++) {
            if (rectangles[i]) rectangles[i].destroy({ children: true, context: true });
            const rectangle = new PIXI.Graphics()
                .rect(
                    0,
                    0,
                    100,
                    100,
                )
                .fill({ color: 0xFF0000 });
            rectangles[i] = rectangle;
            app.stage.addChild(rectangle);
        }
    });
})();
```

### Environment

- **`pixi.js` version**: 8.1.5 (still an issue in 8.3.0)
- **Browser & Version**: Chrome 124
- **OS & Version**: MacOS 14.4.1
- **Running Example**: https://www.pixiplayground.com/#/edit/3ocZP-9nVFphFe1ozWvsQ

**Comment by suprAlessio** [comment]
Any update on this one? It seems like it's still replicable in 8.2.5.

**Comment by devyeshtandon** [comment]
This is replicable. Any inputs on how to fix this?

**Comment by MattTreichelYeah** [comment]
@Zyie I guess it's improved but I still see this build memory and crash in a similar way after about, an hour. Dunno what's a reasonable threshold to expect.

<img width="1512" alt="Screenshot 2024-08-27 at 9 36 52 PM" src="https://github.com/user-attachments/assets/50eed705-ad98-4bfd-8cc2-1f60bc768019">

I took this other screenshot in my fully featured project that used to work fine on v7, crashing in a similar way after waiting for awhile, though the crash point is slightly different, `_graphicsBatchHash` vs. `_gpuContextHash` overloading.

<img width="1512" alt="Screenshot 2024-08-26 at 1 20 35 AM" src="https://github.com/user-attachments/assets/ab5e6b08-2404-488c-ab46-07a0898fc9a7">
