### ISSUE TITLE
Bug: TilingSpritePipe crashes on updating tilePosition in invisible TilingSprite

### ISSUE THREAD

**Issue by djkfx** [pixijs/pixijs#10603]
### Current Behavior

Pixi 8 throws an exception when trying to update tilePosition in invisible TilingSprite after a few frames from start:
[https://www.pixiplayground.com/#/edit/enpcvvfKNmXWyM9Sn-cxF](https://www.pixiplayground.com/#/edit/enpcvvfKNmXWyM9Sn-cxF)
Call stack:
`Uncaught TypeError: batchableMesh is undefined
    validateRenderable TilingSpritePipe.ts:65
    validateRenderables validateRenderables.ts:18
    render RenderGroupSystem.ts:77
    emit SystemRunner.ts:70
    render AbstractRenderer.ts:295
    render Application.ts:154
    emit TickerListener.ts:64
    update Ticker.ts:461
    _tick Ticker.ts:163`
    
Works fine when tiling sprite is visible:
[https://www.pixiplayground.com/#/edit/i5bMLqdrO87YNNqzoM2Yf](https://www.pixiplayground.com/#/edit/i5bMLqdrO87YNNqzoM2Yf)

Also works fine when tilingSprite is invisible but updating tilePosition starting from first frame:
[https://www.pixiplayground.com/#/edit/i1aBshgnrbr5NNxrvmOeP](https://www.pixiplayground.com/#/edit/i1aBshgnrbr5NNxrvmOeP)

The same code in pixi 7 works without a problems:
[https://www.pixiplayground.com/#/edit/Uk_SLNZYVV71z-hWcW5y_](https://www.pixiplayground.com/#/edit/Uk_SLNZYVV71z-hWcW5y_)

### Expected Behavior

Not crashing

### Steps to Reproduce

    const app = new PIXI.Application();
    await app.init({ resizeTo: window });
    document.body.appendChild(app.canvas);

    const texture = await PIXI.Assets.load("https://pixijs.com/assets/p2.jpeg");
    
    const tilingSprite = new PIXI.TilingSprite(texture);
    tilingSprite.width = texture.width;
    tilingSprite.height = texture.height;
    tilingSprite.visible = false;
    
    app.stage.addChild(tilingSprite);

    let frames = 0;
    app.ticker.add(() =>
    {
        frames++;

        if(frames > 100) {
            tilingSprite.tilePosition.y += 10;
        }

        if(frames > 200) {   
            tilingSprite.visible = true;
        }
    });

### Environment

- **`pixi.js` version**: *8.1.5*
- **Browser & Version**: *all*
- **OS & Version**: *Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by GoodBoyDigital** [comment]
ooh! good catch - will take a look
