### ISSUE TITLE
Any plans to support canvas2d fallback in Pixi v8?

### ISSUE THREAD

**Issue by blackbird-chrisf** [pixijs/pixijs#10614]
### Description

I've read through https://www.npmjs.com/package/pixi.js-legacy but as far as I can tell it only supports the `v7` API. We've upgraded our app to `v8` but there is still a use case for falling back to plain canvas in some situations (e.g. certain Chromium-based browsers with WebGL disabled).

Is there any plan to update the legacy polyfill for Pixi v8? Thanks! 🎨

**Comment by blackbird-chrisf** [comment]
Ah, I've just seen [this commit](https://github.com/pixijs/pixijs/commit/4ce7191363b2b1eb5aecac5775749848ff84ef4e#diff-5d3582d9a575e4f9d3eed5d15273716980a0763ccc16b1c80e219fbfbadff242R133) which gives me hope 😄

**Comment by bigtimebuddy** [comment]
Yes, this is definitely on the roadmap! And the CanvasRenderer will be included in the default `pixi.js` package. We wanted to sort out all the WebGPU and WebGL stuff first.

**Comment by blackbird-chrisf** [comment]
@bigtimebuddy Thanks! That is awesome news, delighted to hear good ol' canvas rendering will be a first class Pixi citizen just like its much fancier WebG* counterparts 😄

**Comment by qk0106** [comment]
<img width="394" alt="image" src="https://github.com/user-attachments/assets/c54b1d1d-780e-4a9d-a826-6f4b32e71e5c">

pixi.js-legacy is still not updated to v8, is 2d canvas fallback added to pixi.js v8 by default?

**Comment by bigtimebuddy** [comment]
The plan is to add Canvas renderer to the pixi.js v8 package and to deprecate pixi.js-legacy package.

**Comment by Elitis** [comment]
any updates?

**Comment by bigtimebuddy** [comment]
Not yet. We need a hero to help execute on this work. Anyone interested?

**Comment by Mistik** [comment]
> Not yet. We need a hero to help execute on this work. Anyone interested?

did you ever get anyone to help?

**Comment by AntoscencoVladimir** [comment]
any updates?

**Comment by FelixNumworks** [comment]
Hi! Sorry to insist on this issue, but it has been stale for a long time. Is this planned soon?

I have CI tests that run my app in headless Chromium with no access to a GPU.
Currently, Chromium falls back on a CPU implementation of WebGL, but they have announced that this is deprecated and will be removed in future versions (see [Chromium feature tracker](https://chromestatus.com/feature/5166674414927872)).

I have two options from here:
- Grant GPU access to my test container
- Fall back on Canvas2D and use the CPU

For various reasons, the second option would be easier for me to implement.

**Comment by drummerjolev** [comment]
Curious if this is being worked on @bigtimebuddy ? Happy to help!

**Comment by bigtimebuddy** [comment]
@drummerjolev Please!!! We've tried several attempts to get this project going, but haven't found someone who can commit the time. It's definitely an extra large effort.

The ideal solution should:

* Work with our existing visual tests
* Should optionally import the canvas renderer, like our other renderers
* Should follow existing patterns of existing WebGL and WebGPU renderers
* Should support all basic display classes, like BitmapText, Text, Graphics, Sprite, AnimatedSprite, Container
* Feature-wise, filters and other advanced blend modes can likely be ignored, like in v7

Let us know how we can support you.
