### ISSUE TITLE
Bug: Unable to create subtextures from larger textures

### ISSUE THREAD

**Issue by dschumak** [pixijs/pixijs#10611]
### Current Behavior

When running the below snippet, the entire image from "./assets/nature-paltformer-tileset-16x16.png" on my local disk (downloaded from this website: https://rottingpixels.itch.io/nature-platformer-tileset) is being rendered on the screen as the "bunny" (I'm just using the demo code provided on the PIXI.js documentation website) sprite instead of the cropped version of the image whose top left pixel belongs at y_pixel_level = 32 and x_pixel_level = 32 and should only be 16 pixels by 16 pixels wide/tall. 

The code below should pull one tile from this larger tileset and render it on the canvas in the center. Instead the entire tileset is being rendered as one big image

`
    const loadedImage = await PIXI.Assets.load("./assets/nature-paltformer-tileset-16x16.png");
    let frame = new PIXI.Rectangle(32,32,16,16);
    const croppedImage = new PIXI.Texture(loadedImage, frame);
    bunny = new PIXI.Sprite(croppedImage);
    // Add to stage.
    app.stage.addChild(bunny);

    // Center the sprite's anchor point.
    bunny.anchor.set(0.5);

    // Move the sprite to the center of the screen.
    bunny.x = app.screen.width / 2;
    bunny.y = app.screen.height / 2;`

### Expected Behavior

The code below should pull one tile from this larger tileset and render just that one tile on the canvas in the center. The tile should be a 16pixel by 16pixel square which is taken from the larger tileset image. Instead the entire tileset is being rendered as one big image.

`  const loadedImage = await PIXI.Assets.load("./assets/nature-paltformer-tileset-16x16.png");
    let frame = new PIXI.Rectangle(32,32,16,16);
    const croppedImage = new PIXI.Texture(loadedImage, frame);
    bunny = new PIXI.Sprite(croppedImage);
    // Add to stage.
    app.stage.addChild(bunny);

    // Center the sprite's anchor point.
    bunny.anchor.set(0.5);

    // Move the sprite to the center of the screen.
    bunny.x = app.screen.width / 2;
    bunny.y = app.screen.height / 2;`

### Steps to Reproduce

copy paste the below code in a PIXI project (you'll have to load PIXI.js into the project, in this instance I am pulling a minified version of pixi.js and importing it as a script tag in the HTML. It is also possible to pull in PIXI.js using webpack however I am unfamiliar with the process, I just pulled the minified code to make my life easier. You'll also have to download the tileset from this website and store it in a folder in your PIXI project called "assets":  https://rottingpixels.itch.io/nature-platformer-tileset
Otherwise you can use your own image from your own computer, just make sure the image is larger than 48 pixels in each dimension.

`  const loadedImage = await PIXI.Assets.load("./assets/nature-paltformer-tileset-16x16.png");
    let frame = new PIXI.Rectangle(32,32,16,16);
    const croppedImage = new PIXI.Texture(loadedImage, frame);
    bunny = new PIXI.Sprite(croppedImage);
    // Add to stage.
    app.stage.addChild(bunny);

    // Center the sprite's anchor point.
    bunny.anchor.set(0.5);

    // Move the sprite to the center of the screen.
    bunny.x = app.screen.width / 2;
    bunny.y = app.screen.height / 2;`

### Environment

- **`pixi.js` version**: v8.1.5
- **Browser & Version**: Chrome 124.0.6367.119
- **OS & Version**: MacOS 14.2 (23C64)
- **Running Example**: https://github.com/dschumak/Potch

### Possible Solution

I can work around this issue by creating hundreds of smaller files that I crop manually but that's an insane amount of work and will slow down loading times substantially, it's a really bad fix. I must be invoking the Rectangle object incorrectly when instantiating the smaller texture from the larger texture. This used to work just fine, I'm not sure what I'm doing wrong.

### Additional Information

The goal here is to load this tileset, parse it into an array of textures to be used as tiles in a videogame for the background. I'd much rather load one image and parse it into several smaller textures than load several different images of each tile. I know this method used to work when Potch made a videogame using an older version of PIXI.js 4 years ago: https://www.youtube.com/watch?v=dDSKexgVCaU

**Comment by GoodBoyDigital** [comment]
heya! the signiture for textures in v8 has changed a bit. This should do the trick:
```
const croppedTexture = new PIXI.Texture({
    source:texture,
    frame:new PIXI.Rectangle(0,0, 10, 10)
});
```
[example](https://www.pixiplayground.com/#/edit/UA-KAQakB4brq4PhKk73W)

Let me know if this works for ya!

**Comment by dschumak** [comment]
> heya! the signiture for textures in v8 has changed a bit. This should do the trick:
> 
> ```
> const croppedTexture = new PIXI.Texture({
>     source:texture,
>     frame:new PIXI.Rectangle(0,0, 10, 10)
> });
> ```
> 
> [example](https://www.pixiplayground.com/#/edit/UA-KAQakB4brq4PhKk73W)
> 
> Let me know if this works for ya!

Hey thanks for the reply! Is there a good website I can use to view documentation for v8+? I've been poking around these docs: ex: https://pixijs.download/v6.0.0/docs/PIXI.Texture.html
They seem to be mostly for older versions of PIXI, specifically v6.0.0. I'd like to use the latest version but I'm not exactly sure where the best source of truth is besides a few linked examples I've seen on github. In full honesty I'm still an amateur developer to some degree so a lot of examples go way over my head. It'd be nice if I could just have some docs that explicitly define different classes and such for version 8. I tried replacing the 'v6.0.0' in the url with '8.0.0' but I'm just getting 404s or access denied errors.

**Comment by dschumak** [comment]
Nevermind, found v8 docs here https://pixijs.download/v8.0.0-rc.5/docs/index.html

Google doesn't do a great job of getting you to these docs, they're a little buried.
