### ISSUE TITLE
Bug: Shader uniform supported types are missing 'bool'

### ISSUE THREAD

**Issue by CatchABus** [pixijs/pixijs#10624]
### Current Behavior

It seems shader uniform supported types are missing type `bool`.
See: https://github.com/pixijs/pixijs/blob/dev/src/rendering/renderers/shared/shader/types.ts#L2

### Expected Behavior

Type `bool` should be among the uniform supported types since it's defined in other places like: https://github.com/pixijs/pixijs/blob/dev/src/rendering/renderers/gl/shader/utils/generateUniformsSyncTypes.ts#L78

### Steps to Reproduce

Create any shader with a uniform of type `bool`. It will throw
```
Error: Uniform type bool is not supported. Supported uniform types are: f32, i32, vec2<f32>, vec3<f32>, vec4<f32>, mat2x2<f32>, mat3x3<f32>, mat4x4<f32>, mat3x2<f32>, mat4x2<f32>, mat2x3<f32>, mat4x3<f32>, mat2x4<f32>, mat3x4<f32>
```

### Environment

- **`pixi.js` version**: *8.1.6*
- **Browser & Version**: *125.0.6422.142*
- **OS & Version**: *Microsoft Windows 11*

### Possible Solution

Add the missing `bool` type here: https://github.com/pixijs/pixijs/blob/dev/src/rendering/renderers/shared/shader/types.ts#L2

**Comment by GoodBoyDigital** [comment]
heya! this is intentional as WebGPU does not support booleans due to the fact uniforms can only be numbers. You can throw up a `1` or `0` instead!

**Comment by CatchABus** [comment]
> heya! this is intentional as WebGPU does not support booleans due to the fact uniforms can only be numbers. You can throw up a `1` or `0` instead!

Oh I see. Thanks for clarification!
