### ISSUE TITLE
Bug: Container added sprite not updated transform

### ISSUE THREAD

**Issue by jljsj33** [pixijs/pixijs#10659]
### Current Behavior

Adding a sprite that has already been used and then adding it to the Container will not update the transform；
![image](https://github.com/pixijs/pixijs/assets/6802825/623b8bf9-43ca-4732-9495-f2b6b29880a1)

### Expected Behavior

-

### Steps to Reproduce

https://codesandbox.io/p/sandbox/re-addchild-bug-gk6k3s?file=%2Fsrc%2Findex.mjs%3A16%2C19

### Environment

- **`pixi.js` version**: *e.g. 8.2.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by GoodBoyDigital** [comment]
thanks for flagging, taking a look now 👍

**Comment by GoodBoyDigital** [comment]
[this](https://github.com/pixijs/pixijs/pull/10660) should fix it!
