### ISSUE TITLE
Bug: @pixi/unsafe-eval suddenly stopped working

### ISSUE THREAD

**Issue by Autumnlight02** [pixijs/pixijs#10666]
### Current Behavior

Basically whenever in my chrome extension I try to do anything I am getting the eval error.

### Expected Behavior

That it works like previously.

### Steps to Reproduce

  import * as PIXI from "pixi.js";
  import "@pixi/unsafe-eval";
  ... other code.

### Environment

- **`pixi.js` version**: *e.g. 7.4.2*
- **Browser & Version**: *Chrome 126.0.6478.61*
- **OS & Version**: *e.g. Fedora Kionite 40*

### Possible Solution

I dont know.

**Comment by GoodBoyDigital** [comment]
Hi there! Please can you provide more information. Thanks!

**Comment by Autumnlight02** [comment]
Basically the Issue is that even though I am importing the eval package, its complaining about not being there

**Comment by Autumnlight02** [comment]
![image](https://github.com/pixijs/pixijs/assets/68244453/b188ed21-d1ea-47f4-a3bc-4bed7a139052)

**Comment by Autumnlight02** [comment]
![image](https://github.com/pixijs/pixijs/assets/68244453/b188ed21-d1ea-47f4-a3bc-4bed7a139052)

**Comment by Autumnlight02** [comment]
vite update fixed it!
