### ISSUE TITLE
Bug: Sprite Mask filter should default resolution to Renderer

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixijs#10671]
### Current Behavior

When using a Sprite mask and changing the renderer resolution _after_ initialization, can result in the internal Sprite mask filter having a default resolution of `1` which produces some unsightly quality loss.

![Jun-26-2024 15-18-45](https://github.com/pixijs/pixijs/assets/864393/316a937d-41e9-4284-a998-a9d6197b56d4)

Example:
https://jsfiddle.net/bigtimebuddy/6t35ks84/

### Expected Behavior

Sprite masks should always use the default to the Renderer resolution

### Steps to Reproduce

See example.

### Environment

- **`pixi.js` version**: 8.2.1
- **Browser & Version**: Chrome Latest
- **OS & Version**: macOS Latest
- **Running Example**: [*e.g. <https://pixiplayground.com/>*](https://jsfiddle.net/bigtimebuddy/6t35ks84/)

**Comment by GoodBoyDigital** [comment]
thanks for this one @bigtimebuddy ! will take a looksi soon!
