### ISSUE TITLE
Bug: When drawing a line, it cannot be displayed, but when drawing two lines, it can be displayed normally.

### ISSUE THREAD

**Issue by Auler** [pixijs/pixijs#10676]
### Current Behavior

When using Pixi to draw a line, it cannot be drawn properly. It is necessary to configure two consecutive drawing coordinate points in order to display a line normally. There is also a missing line when drawing multiple times.

### Expected Behavior

When using Pixi to draw a line, it can be drawn propertly. Thank you!

### Steps to Reproduce

let line = new PIXI.Graphics();
  line.stroke({
    color:0xaaaaaa,
    width:10,
  });
line.moveTo(100, 100).lineTo(app.screen.width / 2, app.screen.height / 2);
app.stage.addChild(line); 

**The above code cannot be drawn.**

let line = new PIXI.Graphics();
  line.stroke({
    color:0xaaaaaa,
    width:10,
  });
line.moveTo(100, 100).lineTo(app.screen.width / 2, app.screen.height / 2);
  line.stroke({
    color:0xaaaaaa,
    width:10,
  });
line.moveTo(100, 100).lineTo(app.screen.width / 2, app.screen.height / 2);
app.stage.addChild(line); 

**The above code can draw a line.**

### Environment

- **`pixi.js` version**: *e.g.8.0.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. windows10

**Comment by plurry** [comment]
You just need to put `stroke` after `moveTo` and `lineTo` and it'lll work.

https://pixiplayground.com/#/edit/YRXViT5RmlfuojFtIYLrT
