### ISSUE TITLE
Bug: Text Padding does not "add to all sides of text"

### ISSUE THREAD

**Issue by aweidler** [pixijs/pixijs#10675]
### Current Behavior

Current padding is only added to right and bottom of text (or at least that is the new text size given the bounds when I draw a rect around the width and height, see screenshots (one with padding and one without). The text should be centered in the box if it truely "adds padding to all sides". If my understanding is correct? This was an issue for me upgrading from v7 to v8, all my text became misaligned.

<img width="146" alt="Screenshot 2024-06-29 at 16 07 42" src="https://github.com/pixijs/pixijs/assets/8696105/14f2e325-9aeb-4335-a3ef-1a90908f9cb9">
<img width="143" alt="Screenshot 2024-06-29 at 16 08 15" src="https://github.com/pixijs/pixijs/assets/8696105/8a234521-fc4d-46b3-a5b1-6ab7c297a08f">

### Expected Behavior

"Occasionally some fonts are cropped. Adding some padding will prevent this from happening by adding padding to **all sides** of the text."

### Steps to Reproduce

1. Create `PIXI.Text`
2. Add `TextStyle` with large padding
3. Create `Graphics` and draw rect with width and height as size of Text
4. Add both to container and render

### Environment

- **`pixi.js` version**: 8.2.1
- **Browser & Version**: Chrome 126.0.6478.127 (Official Build) (arm64)
- **OS & Version**: MacOS 14.4.1 (M1)
- **Running Example**: `https://pixiplayground.com/#/edit/17VOb4lg3Wk5BztFLsjT_`

**Comment by GoodBoyDigital** [comment]
heya! all good here, updated the demo to account for the x and y and it looks much better!

https://pixiplayground.com/#/edit/17VOb4lg3Wk5BztFLsjT_

**Comment by GoodBoyDigital** [comment]
Actually - there _is_ a bug here - the padding should not show up in the bounds at all. Will fix today.
