### ISSUE TITLE
Bug: Combination of stroke and padding produces incorrect values for textSprite.width and textSprite.height

### ISSUE THREAD

**Issue by ADCDS** [pixijs/pixijs#10755]
### Current Behavior

Setting padding and stroke field in a same TextStyle and then generating a text using this style produces a Text object with invalid "width" and "height" values.

```
const style = new TextStyle({   
    "stroke":{"color":"rgba(0,0,0,1)","width":"19"},
    "padding":28
});

const richText = new Text({
    text: 'Rich text with a lot of options and across multiple lines',
    style,
});

console.log(richText.width, richText.height) // prints -28594.857421875196 2975
```

### Expected Behavior

Valid values for text's width and height

### Steps to Reproduce

For pixi 8 -> [Run](https://pixijs.com/8.x/playground?state=eyJmaWxlcyI6eyIvc3JjL2luZGV4LmpzIjp7ImNvZGUiOiJpbXBvcnQgeyBBcHBsaWNhdGlvbiwgVGV4dCwgVGV4dFN0eWxlLCBDb2xvciwgRmlsbEdyYWRpZW50IH0gZnJvbSAncGl4aS5qcyc7XG4oYXN5bmMgKCkgPT5cbntcbi8vIENyZWF0ZSBhIG5ldyBhcHBsaWNhdGlvblxuY29uc3QgYXBwID0gbmV3IEFwcGxpY2F0aW9uKCk7XG5cbi8vIEluaXRpYWxpemUgdGhlIGFwcGxpY2F0aW9uXG5hd2FpdCBhcHAuaW5pdCh7IGJhY2tncm91bmQ6ICcjMTA5OWJiJywgcmVzaXplVG86IHdpbmRvdyB9KTtcblxuLy8gQXBwZW5kIHRoZSBhcHBsaWNhdGlvbiBjYW52YXMgdG8gdGhlIGRvY3VtZW50IGJvZHlcbmRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYXBwLmNhbnZhcyk7XG5cbmNvbnN0IHN0eWxlID0gbmV3IFRleHRTdHlsZSh7ICAgXG4gICAgXCJzdHJva2VcIjp7XCJjb2xvclwiOlwicmdiYSgwLDAsMCwxKVwiLFwid2lkdGhcIjpcIjE5XCJ9LFxuICAgIFwicGFkZGluZ1wiOjI4XG59KTtcblxuY29uc3QgcmljaFRleHQgPSBuZXcgVGV4dCh7XG4gICAgdGV4dDogJ1JpY2ggdGV4dCB3aXRoIGEgbG90IG9mIG9wdGlvbnMgYW5kIGFjcm9zcyBtdWx0aXBsZSBsaW5lcycsXG4gICAgc3R5bGUsXG59KTtcblxuY29uc29sZS5sb2cocmljaFRleHQud2lkdGgsIHJpY2hUZXh0LmhlaWdodClcblxufSkoKTsifSwiL3NyYy9zdHlsZXMuY3NzIjp7ImNvZGUiOiJib2R5IHsgbWFyZ2luOiAwOyBvdmVyZmxvdzogaGlkZGVuOyB9In0sIi9pbmRleC5odG1sIjp7ImNvZGUiOiJcbjwhRE9DVFlQRSBodG1sPlxuICA8aHRtbD5cbiAgPGhlYWQ%2BXG4gIDx0aXRsZT5QaXhpSlMgUGxheWdyb3VuZDwvdGl0bGU%2BXG4gIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiIC8%2BXG4gIDxsaW5rIHJlbD1cInN0eWxlc2hlZXRcIiBocmVmPVwic3JjL3N0eWxlcy5jc3NcIj5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2NyaXB0IHNyYz1cInNyYy9pbmRleC5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuPC9odG1sPiJ9LCIvcGFja2FnZS5qc29uIjp7ImNvZGUiOiJ7XG4gIFwic2NyaXB0c1wiOiB7XG4gICAgXCJzdGFydFwiOiBcInBhcmNlbCBpbmRleC5odG1sIC0tb3BlblwiLFxuICAgIFwiYnVpbGRcIjogXCJwYXJjZWwgYnVpbGQgaW5kZXguaHRtbFwiXG4gIH0sXG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBpeGkuanNcIjogXCI4LjIuMVwiXG4gIH0sXG4gIFwiZGV2RGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBhcmNlbC1idW5kbGVyXCI6IFwiXjEuNi4xXCIsXG4gICAgXCJAYmFiZWwvY29yZVwiOiBcIl43LjIxLjNcIixcbiAgICBcIkBiYWJlbC9wbHVnaW4tcHJvcG9zYWwtY2xhc3MtcHJvcGVydGllc1wiOiBcIl43LjEwLjFcIlxuICB9LFxuICBcIm1haW5cIjogXCIvaW5kZXguaHRtbFwiXG59In0sIi8uYmFiZWxyYyI6eyJjb2RlIjoie1xuICBcInByZXNldHNcIjogW1xuICAgIFtcbiAgICAgIFwiQGJhYmVsL3ByZXNldC1lbnZcIixcbiAgICAgIHtcbiAgICAgICAgXCJ1c2VCdWlsdEluc1wiOiBcImVudHJ5XCIsXG4gICAgICAgIFwiY29yZWpzXCI6IFwiMy4yOVwiLFxuICAgICAgICBcInRhcmdldHNcIjogXCJsYXN0IDIgY2hyb21lIHZlcnNpb25zXCJcbiAgICAgIH1cbiAgICBdXG4gIF0sXG4gIFwicGx1Z2luc1wiOiBbXG4gICAgXCJAYmFiZWwvcGx1Z2luLXByb3Bvc2FsLWNsYXNzLXByb3BlcnRpZXNcIlxuICBdXG59In0sIi9zYW5kYm94LmNvbmZpZy5qc29uIjp7ImNvZGUiOiJ7XG4gICAgICAgICAgICAgICAgXCJpbmZpbml0ZUxvb3BQcm90ZWN0aW9uXCI6IGZhbHNlXG4gICAgICAgICAgICB9In19LCJ2aXNpYmxlRmlsZXMiOlsiL3NyYy9pbmRleC5qcyJdLCJhY3RpdmVGaWxlIjoiL3NyYy9pbmRleC5qcyJ9) (Check console.log)

### Environment

- **`pixi.js` version**: 8
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: [pixi v8](https://pixijs.com/8.x/playground?state=eyJmaWxlcyI6eyIvc3JjL2luZGV4LmpzIjp7ImNvZGUiOiJpbXBvcnQgeyBBcHBsaWNhdGlvbiwgVGV4dCwgVGV4dFN0eWxlLCBDb2xvciwgRmlsbEdyYWRpZW50IH0gZnJvbSAncGl4aS5qcyc7XG4oYXN5bmMgKCkgPT5cbntcbi8vIENyZWF0ZSBhIG5ldyBhcHBsaWNhdGlvblxuY29uc3QgYXBwID0gbmV3IEFwcGxpY2F0aW9uKCk7XG5cbi8vIEluaXRpYWxpemUgdGhlIGFwcGxpY2F0aW9uXG5hd2FpdCBhcHAuaW5pdCh7IGJhY2tncm91bmQ6ICcjMTA5OWJiJywgcmVzaXplVG86IHdpbmRvdyB9KTtcblxuLy8gQXBwZW5kIHRoZSBhcHBsaWNhdGlvbiBjYW52YXMgdG8gdGhlIGRvY3VtZW50IGJvZHlcbmRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYXBwLmNhbnZhcyk7XG5cbmNvbnN0IHN0eWxlID0gbmV3IFRleHRTdHlsZSh7ICAgXG4gICAgXCJzdHJva2VcIjp7XCJjb2xvclwiOlwicmdiYSgwLDAsMCwxKVwiLFwid2lkdGhcIjpcIjE5XCJ9LFxuICAgIFwicGFkZGluZ1wiOjI4XG59KTtcblxuY29uc3QgcmljaFRleHQgPSBuZXcgVGV4dCh7XG4gICAgdGV4dDogJ1JpY2ggdGV4dCB3aXRoIGEgbG90IG9mIG9wdGlvbnMgYW5kIGFjcm9zcyBtdWx0aXBsZSBsaW5lcycsXG4gICAgc3R5bGUsXG59KTtcblxuY29uc29sZS5sb2cocmljaFRleHQud2lkdGgsIHJpY2hUZXh0LmhlaWdodClcblxufSkoKTsifSwiL3NyYy9zdHlsZXMuY3NzIjp7ImNvZGUiOiJib2R5IHsgbWFyZ2luOiAwOyBvdmVyZmxvdzogaGlkZGVuOyB9In0sIi9pbmRleC5odG1sIjp7ImNvZGUiOiJcbjwhRE9DVFlQRSBodG1sPlxuICA8aHRtbD5cbiAgPGhlYWQ%2BXG4gIDx0aXRsZT5QaXhpSlMgUGxheWdyb3VuZDwvdGl0bGU%2BXG4gIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiIC8%2BXG4gIDxsaW5rIHJlbD1cInN0eWxlc2hlZXRcIiBocmVmPVwic3JjL3N0eWxlcy5jc3NcIj5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2NyaXB0IHNyYz1cInNyYy9pbmRleC5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuPC9odG1sPiJ9LCIvcGFja2FnZS5qc29uIjp7ImNvZGUiOiJ7XG4gIFwic2NyaXB0c1wiOiB7XG4gICAgXCJzdGFydFwiOiBcInBhcmNlbCBpbmRleC5odG1sIC0tb3BlblwiLFxuICAgIFwiYnVpbGRcIjogXCJwYXJjZWwgYnVpbGQgaW5kZXguaHRtbFwiXG4gIH0sXG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBpeGkuanNcIjogXCI4LjIuMVwiXG4gIH0sXG4gIFwiZGV2RGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBhcmNlbC1idW5kbGVyXCI6IFwiXjEuNi4xXCIsXG4gICAgXCJAYmFiZWwvY29yZVwiOiBcIl43LjIxLjNcIixcbiAgICBcIkBiYWJlbC9wbHVnaW4tcHJvcG9zYWwtY2xhc3MtcHJvcGVydGllc1wiOiBcIl43LjEwLjFcIlxuICB9LFxuICBcIm1haW5cIjogXCIvaW5kZXguaHRtbFwiXG59In0sIi8uYmFiZWxyYyI6eyJjb2RlIjoie1xuICBcInByZXNldHNcIjogW1xuICAgIFtcbiAgICAgIFwiQGJhYmVsL3ByZXNldC1lbnZcIixcbiAgICAgIHtcbiAgICAgICAgXCJ1c2VCdWlsdEluc1wiOiBcImVudHJ5XCIsXG4gICAgICAgIFwiY29yZWpzXCI6IFwiMy4yOVwiLFxuICAgICAgICBcInRhcmdldHNcIjogXCJsYXN0IDIgY2hyb21lIHZlcnNpb25zXCJcbiAgICAgIH1cbiAgICBdXG4gIF0sXG4gIFwicGx1Z2luc1wiOiBbXG4gICAgXCJAYmFiZWwvcGx1Z2luLXByb3Bvc2FsLWNsYXNzLXByb3BlcnRpZXNcIlxuICBdXG59In0sIi9zYW5kYm94LmNvbmZpZy5qc29uIjp7ImNvZGUiOiJ7XG4gICAgICAgICAgICAgICAgXCJpbmZpbml0ZUxvb3BQcm90ZWN0aW9uXCI6IGZhbHNlXG4gICAgICAgICAgICB9In19LCJ2aXNpYmxlRmlsZXMiOlsiL3NyYy9pbmRleC5qcyJdLCJhY3RpdmVGaWxlIjoiL3NyYy9pbmRleC5qcyJ9)

**Comment by Zyie** [comment]
Hey @ADCDS I believe this has been fixed in 8.2.5
