### ISSUE TITLE
Bug: TypeError: Failed to execute 'shaderSource' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLShader'.

### ISSUE THREAD

**Issue by CaptainStiggz** [pixijs/pixijs#10843]
### Current Behavior

Our sentry picked up this bug.

```
function compileShader(gl, type, src) {
  const shader = gl.createShader(type);
  gl.shaderSource(shader, src);
  gl.compileShader(shader);
  return shader;
}
```

### Expected Behavior

Not to throw an error.

### Steps to Reproduce

https://visualelectric.sentry.io/share/issue/e1297c59a6124766aa4dccd000e88620/

### Environment

- **`pixi.js` version**: *8.2.5*
- **Browser & Version**: *Chrome 127.0.0/Opera 112.0.0*
- **OS & Version**: *Windows >= 10*

**Comment by bigtimebuddy** [comment]
Again, please don't post sentry stack traces like this, it is not helpful and our small team cannot debug other people's projects. A minimal reproduction is required to verify the bug. Without that we cannot tell if this is a user bug or pixi issue.

**Comment by CaptainStiggz** [comment]
Gotcha, wasn't sure if it was helpful to you or not. I'll refrain from posting more.
