### ISSUE TITLE
Bug: TypeError: Cannot read properties of null (reading 'x')

### ISSUE THREAD

**Issue by CaptainStiggz** [pixijs/pixijs#10842]
### Current Behavior

Our sentry is reporting a bug in pixi. Wish I had more information, but here's what I have.

```
copyFrom(p) {
    if (this._x !== p.x || this._y !== p.y) {
      this._x = p.x;
      this._y = p.y;
      this._observer._onUpdate(this);
    }
    return this;
```

### Expected Behavior

Not to throw an error.

### Steps to Reproduce

https://visualelectric.sentry.io/share/issue/f15def984a38435baef0b180ec0b511c/

### Environment

- **`pixi.js` version**: *8.2.5*
- **Browser & Version**: *Chrome 127.0.0*
- **OS & Version**: *macOs*

**Comment by bigtimebuddy** [comment]
Please provide a minimal reproduction. These logs are not super helpful because it doesn't include how it was called. How do are you sure this isn't a @pixi/react bug?

**Comment by CaptainStiggz** [comment]
Gotcha, wasn't sure if it was helpful to you or not. I'll refrain from posting more.
