### ISSUE TITLE
Bug: TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by CaptainStiggz** [pixijs/pixijs#10841]
### Current Behavior

This is coming from a sentry report on our app. 

https://visualelectric.sentry.io/share/issue/7416183b9e5c4354a2d745c34f384af5/

```
../node_modules/pixi.js/lib/scene/text/AbstractText.mjs in set AbstractText.AbstractText.text at line 73:1

  set roundPixels(value) {
    this._roundPixels = value ? 1 : 0;
  }
  /** Set the copy for the text object. To split a line you can use '\n'. */
  set text(value) {
    value = value.toString(); // problem line
    if (this._text === value)
      return;
    this._text = value;
    this.onViewUpdate();
  }
```

### Expected Behavior

Not to throw an error.

### Steps to Reproduce

https://visualelectric.sentry.io/share/issue/7416183b9e5c4354a2d745c34f384af5/

### Environment

- **`pixi.js` version**: *8.2.5*
- **Browser & Version**: *Chrome 127.0.0*
- **OS & Version**: *macOs*

**Comment by bigtimebuddy** [comment]
Please provide a minimal reproduction. Thank you!

**Comment by CaptainStiggz** [comment]
Gotcha, wasn't sure if it was helpful to you or not. I'll refrain from posting more.
