### ISSUE TITLE
Bug: Surprising behavior with pointer events on Container

### ISSUE THREAD

**Issue by RoryO** [pixijs/pixijs#10850]
### Current Behavior

I'm not sure if this is a bug intended behavior. There's nothing in the documentation about this which is why this is surprising. All of the current examples use Graphics or Sprite when demonstrating pointer events.

Container events do not fire unless the pointer is above something rendered in the container. I discovered this when I wanted to track pointer movement within a certain area. After some frustrating debugging I realized that the events only fire when the pointer moves over something drawable inside the Container. This happens for all `pointer*` events.

### Expected Behavior

Either a Container will capture all pointer events it is listening on regardless if the pointer is over a drawable, or clarify in documentation that Container is a special and you should use a different type instead.

### Steps to Reproduce

Modifying the bunny Container example shows this

```typescript
import { Application, Assets, Container, Sprite } from 'pixi.js';

(async () =>
{
    // Create a new application
    const app = new Application();

    // Initialize the application
    await app.init({ background: '#1099bb', resizeTo: window });

    // Append the application canvas to the document body
    document.body.appendChild(app.canvas);

    // Create and add a container to the stage
    const container = new Container();
    container.eventMode = 'static';
    app.stage.addChild(container);

    // Load the bunny texture
    const texture = await Assets.load('https://pixijs.com/assets/bunny.png');

    // Create a 5x5 grid of bunnies in the container
    for (let i = 0; i < 25; i++)
    {
        const bunny = new Sprite(texture);

        bunny.x = (i % 5) * 80;
        bunny.y = Math.floor(i / 5) * 80;
        container.addChild(bunny);
    }
    // bad perf doing logging every frame, uncomment to see it only fires the events when over a Sprite
    //container.on('pointermove', console.log);
    container.on('pointerdown', () => console.log('click'));
})();
```

Here, the `pointerdown` will only work when the pointer is over a Sprite, which is the surprising bit.

### Environment

- **`pixi.js` version**: *8.4.0*
- **Browser & Version**: *All*
- **OS & Version**: *Any*

### Possible Solution

Either Container responds to pointer events regardless if the pointer is above a drawable, or clarify in the documentation that Container is special and to use Graphics or Sprite if you want to constrain events to an area.

**Comment by bigtimebuddy** [comment]
Yes, I believe what you are describing is the intended behavior. You could try adding a hitArea to the container to define a rectangle or shape to trigger instead of the children. Is that what you're looking for?

**Comment by RoryO** [comment]
Yes, setting `hitArea` to a rectangle works. I don't know if I missed something in the documentation about this, it is surprising behavior where the implicit hit area of a container is the sum of all of its rendererable contents.
