### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by huangnan20030709** [pixijs/pixijs#10865]
### Current Behavior

// import "pixi.js/unsafe-eval"
//@ts-ignore
import { install } from '@pixi/unsafe-eval';
import { ShaderSystem, Renderer } from '@pixi/core';
import syncUniforms from './syncUniforms'

const TAG = 'AIAssistSendGiftPixi';

export interface IProps {}

export default ({}: IProps) => {

    
    async function fn() {
        // install({ShaderSystem});
        install({ShaderSystem:PIXI.GlShaderSystem});
        new Renderer()
        syncUniforms(PIXI.GlShaderSystem)

        console.log(unsafeEvalSupported());
   }
}
![image](https://github.com/user-attachments/assets/d25cede2-8984-4822-8f90-d4a3778c6629)
![image](https://github.com/user-attachments/assets/5dcaf91a-cd59-4d37-8d03-8994b3f55037)
![image](https://github.com/user-attachments/assets/a0736f89-2f0f-424a-a32f-6e9f1bf7a8a1)

### Expected Behavior

1

### Steps to Reproduce

1

### Environment

- **`pixi.js` version**: *e.g. 8.3.3*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*
1

**Comment by bigtimebuddy** [comment]
You are mixing v7 and v8, which isn't designed to interop this way. If you're using v8, you only need `pixi.js`, not the `@pixi/*` packages.

**Comment by huangnan20030709** [comment]
![image](https://github.com/user-attachments/assets/6bd860e9-e5f5-49b4-88b7-5fefa113a759)


But v8 prompted me to introduce module, which may be the reason why my project does not display UI, how should I fix this error in v8, the project is running in react native environment

**Comment by bigtimebuddy** [comment]
Makes sure none of your dependencies are pulling in v7

**Comment by huangnan20030709** [comment]
This issue has been resolved, v8 doesn't need to introduce any libraries for unsafe-eval is my environment that doesn't allow the eval function, and my reduced security solves the problem，thank u
