### ISSUE TITLE
Bug: EventSystem.resolution is not updated when renderer resolution is changed using renderer.resize()

### ISSUE THREAD

**Issue by EneaEntertainment** [pixijs/pixijs#10867]
### Current Behavior

When resizing renderer with resolution parameter `app.renderer.resize(w, h, 2)`, EventSystem.resolution is not updated as when the renderer resolution is changed directly: `app.renderer.resolution = 2`

### Expected Behavior

EventSystem.resolution should be updated using renderer.resize()

### Steps to Reproduce

https://pixiplayground.com/#/edit/u2nxXOhhIrp1wWFDy2jVz

### Environment

- **`pixi.js` version**: *8.3.3*

**Comment by bigtimebuddy** [comment]
Thanks @EneaEntertainment for reporting the bug. I added a PR to get that sorted.

**Comment by EneaEntertainment** [comment]
thank you @bigtimebuddy
