### ISSUE TITLE
Bug: Docs typo "Asset" -> "Assets"

### ISSUE THREAD

**Issue by jdoleary** [pixijs/pixijs#10884]
### Current Behavior

https://pixijs.download/release/docs/rendering.Texture.html
Reads "Asset" instead of "Assets".  Asset does not exist, but Assets does

### Expected Behavior

It should read "Assets"

### Steps to Reproduce

Read the typo at https://pixijs.download/release/docs/rendering.Texture.html

### Environment

- **`pixi.js` version**: *8.3.3*

**Comment by mthirumalai2905** [comment]
Good Evening sir, I have gone through the rules and regulations as well as the documentation would love to contribute and learn from it it would be really great please if u could assign this task to me

**Comment by mthirumalai2905** [comment]
@bigtimebuddy  sir but i cant find the file its located can u help me with that its my first PR

**Comment by bigtimebuddy** [comment]
https://github.com/pixijs/pixijs/blob/dev/src/rendering/renderers/shared/texture/Texture.ts

**Comment by mthirumalai2905** [comment]
Sir i have raised the PR please check if thats all needed #10886
