### ISSUE TITLE
Bug: Parsing favicon.ico image files when creating a Texture fails

### ISSUE THREAD

**Issue by Tolmark12** [pixijs/pixijs#10899]
### Current Behavior

Texture cannot be created from file with the `.ico` file extension–ex: `favicon.ico`

### Expected Behavior

Because `.ico` are images, usually `.png`s, let's parse them as such

### Steps to Reproduce

[Example of failure - Pixi Playground](https://www.pixiplayground.com/#/edit/b1XwGk9LsSqIjzRunD5jg)

```javascript
let texture = await PIXI.Assets.load(`https://icons.duckduckgo.com/ip3/cnn.com.ico`);
let sprite  = new PIXI.Sprite(texture); // throws error
```

### Environment

- **`pixi.js` version**: 8.3.3
- **Browser & Version**: Version 127.0.6533.120 (Official Build) (arm64)
- **OS & Version**: Mac Sonoma 14.6.1
- **Running Example**: https://www.pixiplayground.com/#/edit/b1XwGk9LsSqIjzRunD5jg

### Possible Solution

It may be as simple as adding `.ico` to the list of valid extensions when creating a texture?
https://github.com/pixijs/pixijs/blob/dev/src/assets/loader/parsers/textures/loadTextures.ts#L17

**Comment by bigtimebuddy** [comment]
Because `.ico` is not built in, you need to specify a loadParser:

```ts
let texture = await PIXI.Assets.load({
  src: `https://icons.duckduckgo.com/ip3/cnn.com.ico`, 
  loadParser: "loadTextures"
});
let sprite  = new PIXI.Sprite(texture); 
```

**Comment by Tolmark12** [comment]
Perfect, thank you! 🙏
