### ISSUE TITLE
Bug: BitmapFont does not render correctly when fontStyle: 'italic' is specified

### ISSUE THREAD

**Issue by lunarraid** [pixijs/pixijs#10914]
### Current Behavior

Passing a fontStyle of `italic` to a BitmapText causes unwanted spacing issues in the text

![image](https://github.com/user-attachments/assets/8446b00b-7ce1-4858-88bd-53bce2d3acd1)

The top is using BitmapText. The bottom is using Text.

### Expected Behavior

When passed the same style, BitmapText should look either identical or at least close enough without spacing issues.

### Steps to Reproduce

Add `fontStyle: 'italic'` to a BitmapText style.

https://www.pixiplayground.com/#/edit/9i73iwmNfFDT4INBh0U7y

### Environment

- **`pixi.js` version**: *8.3.4*
- **Browser & Version**: *Chrome Version 128.0.6613.120 (Official Build) (arm64)*
- **Running Example**: *<https://www.pixiplayground.com/#/edit/9i73iwmNfFDT4INBh0U7y>*

**Comment by bigtimebuddy** [comment]
v7 seems to work okay, so I think this is a regression:
https://jsfiddle.net/bigtimebuddy/4d1w8y6k/

**Comment by rtotalminer** [comment]
Hi, when playing around I found out it works if you capitalise 'Italics'.

**Comment by lunarraid** [comment]
Ironically this is itself a bug, since the code to specifically handle italic is checking only for the lowercase spelling. Setting it to a capitalized version is still respected by the browser but ignored by PixiJS. 

> Hi, when playing around I found out it works if you capitalise 'Italic'.
> 
> ` app.stage.addChild(new PIXI.BitmapText({ text: 'Italic text is buggy', style: { fontStyle: 'Italic', fontSize: 32 } }));`

**Comment by bigtimebuddy** [comment]
Seems like this is happening here:
https://github.com/pixijs/pixijs/blob/f5902eb955d7a5b31bdd9cd7f4df1810b50f54f4/src/scene/text-bitmap/DynamicBitmapFont.ts#L150

Probably need to delete this line.

**Comment by lunarraid** [comment]
I can only assume that line was there to account for extra character width when slanting the characters. Can we ensure there is still enough padding for the slant if we remove this?

**Comment by bigtimebuddy** [comment]
We do calculate kerning for BitmapFonts, that should handle the offset. Either way x2 width is definitely not the right approach.

**Comment by bigtimebuddy** [comment]
That fact that it works fine with "Italic" (capital) means that that line doesn't do anything helpful.

**Comment by lunarraid** [comment]
It doesn't work perfectly. It's very slight, but at large enough fonts I start seeing pieces of characters copied in to other characters. I agree 2xing the width is not the correct way to go. Should there be some `padding` modification for the italics case?

**Comment by bigtimebuddy** [comment]
That is likely a separate bug
