### ISSUE TITLE
Bug: Text does not update its value when 2 text fields are using shared style

### ISSUE THREAD

**Issue by vlasenkoigor** [pixijs/pixijs#10915]
### Current Behavior

When 2  textfields that uses shared font style and if we trying for the first one to set same text values that 2nd text field currently has, then 1st text field does not render that value. 

### Expected Behavior

Text fields should be updated

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/M6SOE_CJuV6Gjm2su12GR

In this playground 2 selectors have the same range and and same font style, and if one of them has been switched to value that another already has, it's value stays outdated

### Environment

- **`pixi.js` version**: *8x*
- **Browser & Version**: *Chrome *
- **OS & Version**: *Windows*
- **Running Example**: https://www.pixiplayground.com/#/edit/M6SOE_CJuV6Gjm2su12GR

**Comment by GoodBoyDigital** [comment]
thanks for posting and providing this example! going to do a bit of a text pass next!
