### ISSUE TITLE
Bug: v8.4.0 regression with Graphics getting incorrect transforms

### ISSUE THREAD

**Issue by davidye** [pixijs/pixijs#10927]
### Current Behavior

Graphics rendering has some weird behavior with transforms being inherited by previously destroyed graphics?

In this playground example:

1) Render rectangle with a scaleX transform of 0.5
2) Destroy rectangle
3) Render circle with scaleX transform of 1
4) Circle inherited the destroyed graphics transform

https://www.pixiplayground.com/#/edit/m6R3s24Nqfz-oFyZGy8bo

### Expected Behavior

Circle renders with scaleX of 1

### Steps to Reproduce

See playground

### Environment

- **`pixi.js` version**: 8.4.0

**Comment by bigtimebuddy** [comment]
Thanks for reporting. v8.3.4 works: https://www.pixiplayground.com/#/edit/WiThKA9SaY2R2Ia1B3sO6

**Comment by naramdash** [comment]
I have a similar issue on my private repo.

- OS: Ubuntu 22.04
- Web Browser: Chrome 129 
- Pixi.js: 8.4.0

https://github.com/user-attachments/assets/9ad43c57-ea3a-4483-9fad-8efd0137bd93

(If it's working properly, just a white background)

They were showing up in odd places, flickering, or scaled differently.

This works correctly in v8.3.4

**Comment by GoodBoyDigital** [comment]
thanks @davidye - going to look into htis now!

**Comment by GoodBoyDigital** [comment]
@davidye this example made it very easy to fix :) Thank you for taking the time to recreate such a minimal example!
  https://github.com/pixijs/pixijs/pull/10928
