### ISSUE TITLE
Bug: FillGradient fill causes memory leak (creates one texture per frame)

### ISSUE THREAD

**Issue by westarne** [pixijs/pixijs#10936]
### Current Behavior

When using FillGradient my WebGL context crashes after a certain amount of time. Beforehand the fps drop significantly and using the DevTools Performance recording, it's possible to observe more and more skipped frames without any real scripting load.

### Expected Behavior

No crashes and stable fps.

### Steps to Reproduce

1. Open example page: https://pixijs.com/8.x/examples/graphics/fill-gradient
2. Wait for 30-60s

I've experienced a similar behavior in my more complex app using the pixi-react beta, but since the example crashes my webgl context even faster I think it might be a better reproducer. Though it could be connected to the OS/Vulkan, so I hope you will be able to reproduce the issue.

### Environment

- **`pixi.js` version**: 8.4.1
- **Browser & Version**: Vivaldi 6.9.3447.46 (Stable channel) stable (64-bit) 
- **OS & Version**: Linux Mint 21.3
- Attached [the vivaldi://gpu report](https://github.com/user-attachments/files/17106052/about-gpu-2024-09-23T23-53-08-124Z.txt), including the error logs at the bottom, that have happened within roughly 30s after opening the example page

### Additional Information

Might be connected to: https://stackoverflow.com/questions/78953390/pixijs-fillgradient-memory-leak

**Comment by westarne** [comment]
Here's a screen recording:
https://github.com/user-attachments/assets/8f65d38e-d337-4d78-9899-6642b14080fb

Please ignore the artifacts at the top of the video. That's a recording setup issue.

**Comment by westarne** [comment]
It's actually the same behavior just after more time (5 minutes) on:
- **Browser & Version**: Google Chrome Version 129.0.6668.59 (Official Build) (arm64)
- **OS & Version**: macOS Sonoma 14.4.1
- Attached [the chrome://gpu report](https://github.com/user-attachments/files/17111377/about-gpu-2024-09-24T08-53-48-312Z.txt), including the error logs at the bottom, that have happened within roughly 5 minutes after opening the example page. (All the `EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.` have happened already when starting the browser)

**Comment by westarne** [comment]
Just some investigation, as I'm not really aware of the internal code yet, but it seems like the `Texture` created from the FillGradient is never destroyed: https://github.com/pixijs/pixijs/blob/dev/src/scene/graphics/shared/fill/FillGradient.ts#L89

And since it will call this method with every fill, it will always create new textures: https://github.com/pixijs/pixijs/blob/dev/src/scene/graphics/shared/utils/convertFillInputToFillStyle.ts#L92

**Comment by MisaLiu** [comment]
Hit the same issue on WebGPU renderer, might be logic issue?

**Comment by GoodBoyDigital** [comment]
good catch @westarne , thanks for all the detail too. We will take a look into this

**Comment by Liam-Hegarty** [comment]
I'm also seeing this issue. I've replicated it in the playground here:

https://www.pixiplayground.com/#/edit/y_qhrsKrn7b6lwHZ0_mX2

And I've captured a snapshot and an allocation timeline here:

https://github.com/user-attachments/files/17756204/Archive.zip
