### ISSUE TITLE
Mouse events not working properly when canvas is zoomed with object-fit: contain

### ISSUE THREAD

**Issue by Dylan190774** [pixijs/pixijs#10946]
### Current Behavior

I have a fixed 1000x1000 canvas inside a container (with variable size, like 500x300), but need the Pixi canvas to be entirely visible, so I use CSS-styles : 
```
.container > canvas {
 width: 100%
 height: 100%;
 object-fit: contain;
}
```
This makes the Pixi canvas scale nicely inside its container element;

But any mouse events on Pixi objects don't work properly then. The coordinates are wrong, and `mouseover `and `click` events act unpredicatable. 

What's the right way to have a fixed Pixi canvas and zoom it ?

### Expected Behavior

I need the canvas to be entirely visible, with mouse events working properly.

### Steps to Reproduce

-

### Environment

- **`pixi.js` version**: *8.1.5*
- **Browser & Version**: *Brave 1.70.119 Chromium: 129.0.6668.70*
- **OS & Version**: *Windows 10*

**Comment by bigtimebuddy** [comment]
Pixi does not consider values to object-fit other than fill when calculating the positions of elements. There are a few options however. You can resize and position the canvas with CSS inside a parent element. Or you can resize the Pixi renderer to fit the parent container (Application also has a resizeTo option). Then you internally can responsively handle the layout of elements inside Pixi.

**Comment by Dylan190774** [comment]
Thank you for your answer.
I solved it by not using `object-fit`, but another outer `div`:
```

  <div class="outercontainer">
    <div
      id="canvascontainer"
      class="canvascontainer"
    >
            <!-- this is where Pixi creates the canvas -->
    </div>
  </div>

.canvascontainer > canvas {
  display: block;
  max-width: 100%;
  max-height: 100%;
  width: auto;
  height: auto;
}

.outercontainer {
  width: 100%;
  height: 100%;
  left: 0;
  top: 0;
}

.canvascontainer {
  position: relative;
  width: 100%;
  height: 100%;
  left: 0;
  top: 0;
  display: flex;
  justify-content: center;
  align-items: center;
}
```
