### ISSUE TITLE
Bug: DynamicBitmap destroy on offscreen canvas

### ISSUE THREAD

**Issue by rnike** [pixijs/pixijs#10951]
### Current Behavior

I just saw this context cleanup method in the destroy function.

https://github.com/pixijs/pixijs/blob/529c599a9385eaa0bebb7abf599e54956ff7a7c2/src/scene/text-bitmap/DynamicBitmapFont.ts#L432-L434

From my understanding, this is not working on offscreen canvas. Should we change the code to the following instead?

```ts
const canvas = canvasAndContext.canvas;

if(canvas instanceof OffscreenCanvas){
 canvas.getContext('2d')?.clearRect(0, 0, canvas.width, canvas.height);
} else {
  // clear context.. this is the fastest way apparently!
  // eslint-disable-next-line no-self-assign
  canvas.width = canvas.width
}
```

### Expected Behavior

It should also clear the context for offscreen canvas

### Steps to Reproduce

1. call BitmapFont.install, the offscreencanvas appears on the safari devtool Graphics tab
2. get the DynamicBitmapFont from Cache and call destroy
4. the image on the offscreencanvas is not cleared

### Environment

- **`pixi.js` version**: *8.4.1*
- **Browser & Version**: *Safari 17.3.1*
- **OS & Version**: *MacOS 14.3.1 (23D60)*
- **Running Example**: **

### Possible Solution

```ts
const canvas = canvasAndContext.canvas;

if(canvas instanceof OffscreenCanvas){
 canvas.getContext('2d')?.clearRect(0, 0, canvas.width, canvas.height);
} else {
  // clear context.. this is the fastest way apparently!
  // eslint-disable-next-line no-self-assign
  canvas.width = canvas.width
}
```

### Additional Information

We are using pixi application in web worker

_No response_

**Comment by GoodBoyDigital** [comment]
Hey @rnike , this is a good catch! solution looks good too! mind submitting a PR? thanks!

**Comment by rnike** [comment]
Hi @GoodBoyDigital , here's the PR. I decided to use clearRect for all types of canvas because this seems like a more proper way to clear a canvas, and also we can get rid of the if-else statement for better readability.
