### ISSUE TITLE
Bug: Texture.update() doesn't update the texture.

### ISSUE THREAD

**Issue by matt-bp** [pixijs/pixijs#10954]
### Current Behavior

When calling `sprite.texture.update()` the texture with a source that has changed isn't updated.

Instead, calling `sprite.texture.source.update()` works for pixi v8 (see [PIXI V8 Demo](https://codepen.io/matt-bp/pen/abevgxJ)).

In pixi v7 calling `sprite.texture.update()` worked correctly (see [PIXI V7 Demo](https://codepen.io/matt-bp/pen/rNXxzYm)).

### Expected Behavior

When calling `sprite.texture.update()` the texture with a source that has changed should be updated.

### Steps to Reproduce

These steps can be seen in the following [PIXI V8 Demo](https://codepen.io/matt-bp/pen/abevgxJ).

1. Create a texture whose source can dynamically change (like `HTMLCanvas` or `OffscreenCanvas`)
2. Create a `Sprite` from that texture to view it
3. Change content of the source
4. Call `sprite.texture.update()`
5. See the texture not updating

### Environment

- **`pixi.js` version**: *8.3.4*
- **Browser & Version**: *Chrome 129*
- **OS & Version**: *Windows 10*
- **Running Example V8**: *https://codepen.io/matt-bp/pen/abevgxJ*
- **Running Example V7**: *https://codepen.io/matt-bp/pen/rNXxzYm*

### Possible Solution

In pixi v7 I saw that the underlying `baseTexture`'s `update()` method was called when calling `Texture.update()`. One possible solution would be to call `source.update()` when `texture.update()` is called.

The following addition could be made.
```js
/** call this if you have modified the `texture outside` of the constructor */
public update(): void
{
    if (this.noFrame)
    {
        this.frame.width = this._source.width;
        this.frame.height = this._source.height;
    }

    this.source.update(); // Possible solution here.

    this.updateUvs();
    this.emit('update', this);
}
```

Alternatively, the comment for that method could be changed to be less ambiguous to which update method to call.
```js
/**
 * Call this if you have modified the `texture outside` of the constructor.
 *
 * If you have modified the texture's source, call `texture.source.update()` instead.
 */
```

**Comment by GoodBoyDigital** [comment]
good shout @matt-bp - would happily accept a PR that modifies the docs to better explain how update works. Thanks!

**Comment by GoodBoyDigital** [comment]
closing as resolved, thanks @matt-bp !
