### ISSUE TITLE
Bug: When resizing renderer with `multiView: true`, need to ensure the render canvas size also

### ISSUE THREAD

**Issue by bhousel** [pixijs/pixijs#10972]
### Current Behavior

We're using `multiView` rendering for our app, re #10913 
(h/t @Zyie , thanks!!)

I realized that when we resize our app, we also need to manually resize the rendering canvas..  
(i.e. If our app resizes larger, the rendered output remains cut off at the original size)

### Expected Behavior

I'd expect a `renderer.resize()` to trigger `ensureCanvasSize()` automatically.

### Steps to Reproduce

see solution section below - without the `ensureCanvasSize` line, the rendered output may be cut off.

### Environment

- **`pixi.js` version**: *e.g. 8.4.1*

### Possible Solution

Here's our workaround:

```js
// 'w', 'h' contain the new size
// 'ourcanvas' is our main canvas

// Resize pixi canvas
const renderer = this.pixi.renderer;
renderer.resize(w, h);

// needed for multiview?
// If we are using the WebGL renderer and have multiView enabled,
// Pixi will render to a different canvas before copying to the target canvas.
// The render canvas may need a resize too.
if (renderer.type === PIXI.RendererType.WEBGL && renderer.context.multiView) {
  renderer.context.ensureCanvasSize(ourcanvas);
}

```

### Additional Information

Would love to send a pull request, but I don't know where this would belong, if it's something you want - there is already a bunch of code to handle resizing.

**Comment by GoodBoyDigital** [comment]
heya @bhousel! Thanks for posting the issue! Apologies for the delay on getting back to you. Great to see you using this new feature! We would happily accept a PR here if you have the bandwidth. Perhaps we add `ensureCanvasSize` to `GlRenderTargetAdaptor.startRenderPass?` ?
