### ISSUE TITLE
Bug: BitmapText causes warning

### ISSUE THREAD

**Issue by norflin321** [pixijs/pixijs#10985]
### Current Behavior

When PIXI.BitmapText object created, this warning logged in console: `PixiJS Warning:  [BitmapText] dynamically updating the resolution is not supported. Resolution should be managed by the BitmapFont.`

### Expected Behavior

no warning

### Steps to Reproduce

`new PIXI.BitmapText({ text: "hello"})`

### Environment

- **`pixi.js` version**: *8.5.0*
- **Browser & Version**: *Chrome Version 129.0.6668.60 (Official Build) (arm64)*
- **OS & Version**: *macos Sonoma 14.6.1*

**Comment by norflin321** [comment]
https://github.com/pixijs/pixijs/pull/10983

**Comment by creativoma** [comment]
It still happens, even in version 8.5.1 

```
const textTooltip = new PIXI.BitmapText({
  text: `FPS: loading`,
  resolution: devicePixelRatio / 2,
  style,
})
```

_PixiJS Warning:  [BitmapText] dynamically updating the resolution is not supported. Resolution should be managed by the BitmapFont._
