### ISSUE TITLE
Bug: render of PIXI.NineSliceSprite break at a random moment

### ISSUE THREAD

**Issue by norflin321** [pixijs/pixijs#11002]
### Current Behavior

render of PIXI.NineSliceSprite break at a random moment after about 20-30 seconds of play
<p float="left">
  <img src="https://github.com/user-attachments/assets/d9ec5d9b-8cb4-4caa-bb7d-c85392323aa3" width="49%" />
  <img src="https://github.com/user-attachments/assets/70c621fa-3e59-41a2-a7f7-34f84b688985" width="49%" />
</p>

### Steps to Reproduce

```
const texture = PIXI.Assets.get<PIXI.Texture>(name) ?? PIXI.Texture.EMPTY;
const paddings = { leftWidth: 20, topHeight: 0, rightWidth: 20, bottomHeight: 0 };
const sprite = new PIXI.NineSliceSprite({ label: name, texture, eventMode: "none", scale, ...paddings, });
```
- Maybe this is not enough to reproduce the problem because the reason is what happens in the program after NineSliceSprite created and rendered correctly.
- But I know for sure that no properties of this object are changed by the code of my program, in the time between the NineSliceSprite are being rendered correctly and the moment when it breaks
- It happens to all NineSliceSprites in the game at the same time (their size and/or position are incorrect)

### Environment

- **`pixi.js` version**: *8.5.1*
- **Browser & Version**: *Version 129.0.6668.60 (Official Build) (arm64)*
- **OS & Version**: *e.g. Macos Sonoma 14*

**Comment by bigtimebuddy** [comment]
Could you please create a minimal reproduction using codesandbox.io, jsfiddle.net or pixiplayground.com?

**Comment by norflin321** [comment]
@GoodBoyDigital 
- the problem started after upgrading from [v8.4.1 to v8.5.0](https://github.com/pixijs/pixijs/compare/v8.4.1...v8.5.0)
- I assume it has something to do with changes in the classes [NineSliceSprite](https://github.com/pixijs/pixijs/compare/v8.4.1...v8.5.0#diff-a4e272501ec4d6d11a1e7a36db50ea22626b8a5da500d9a4c234dfba174a050d) or [NineSliceSpritePipe](https://github.com/pixijs/pixijs/compare/v8.4.1...v8.5.0#diff-2382eb8c14a6f3cbdfa93ce23d0caa8d63fbe90fdfa75a7d539d0715838cbe9d)
