### ISSUE TITLE
Bug: blank space in the DynamicBitmapFont resource

### ISSUE THREAD

**Issue by rnike** [pixijs/pixijs#11019]
### Current Behavior

There are some blank spaces in the texture source of DynamicBitmapFont, this increases the page size of the resource

![Image](https://github.com/user-attachments/assets/c7014f1d-3156-44c1-98a7-5f40491f08a6)

### Expected Behavior

![Image](https://github.com/user-attachments/assets/135b0c0e-087f-4568-94c2-577ff4d8a03b)

### Steps to Reproduce

1. open the safari devtool and focus on the Graphics tab
2. call BitmapFont.install
3. see the canvas appear

### Environment

- **`pixi.js` version**: *8.5.1*
- **Browser & Version**: *Safari 17.3.1*
- **OS & Version**: *e.g. macOS 14.3.1*

### Cause
`CanvasPool.getOptimalCanvasAndContext` returns a canvas size larger than `this._textureSize`

https://github.com/pixijs/pixijs/blob/a544f84bcd96ebb01a2d9b0894004a67af4e70e3/src/scene/text-bitmap/DynamicBitmapFont.ts#L314-L318

These two condition below uses `this._textureSize` but not the actual size of the canvas 
https://github.com/pixijs/pixijs/blob/a544f84bcd96ebb01a2d9b0894004a67af4e70e3/src/scene/text-bitmap/DynamicBitmapFont.ts#L179
https://github.com/pixijs/pixijs/blob/a544f84bcd96ebb01a2d9b0894004a67af4e70e3/src/scene/text-bitmap/DynamicBitmapFont.ts#L187

### Solution

1. Calculate the max width and height
```ts
    const maxWidth = canvas.width / this.resolution;
    const maxHeight = canvas.width / this.resolution;
```

2. Use the max width and height to check if should move to a new line or page
```diff
-            if (currentX + paddedWidth > this._textureSize)
+            if (currentX + paddedWidth > maxWidth)
            {
                currentY += maxCharHeight;

                // reset the line x and height..
                maxCharHeight = paddedHeight;
                currentX = 0;

-                if (currentY + maxCharHeight > this._textureSize)
+                if (currentY + maxCharHeight > maxHeight)
```

**Comment by GoodBoyDigital** [comment]
great catch!! hey @rnike would you be able to open a PR for this fix pls? Thanks in advance!
