### ISSUE TITLE
Bug: [v8.x] The setTransform method of graphics doesn't work when it's called after graphics.svg().

### ISSUE THREAD

**Issue by oubenruing** [pixijs/pixijs#11026]
### Current Behavior

The setTransform method of graphics doesn't take effect when it's called after graphics.svg(), but it works normally when called before .svg().

### Expected Behavior

```
// Incorrect
const mat = new Matrix().scale(1,2)
graphics.svg(ANY_SVG).setTransform(mat)
```
```
//Correct
const mat = new Matrix().scale(1,2)
graphics.setTransform(mat).svg(ANY_SVG)
```
Both can achieve the same effect.

### Steps to Reproduce

Incorrect example
[pixijs.com/8.x/playground?...](https://pixijs.com/8.x/playground?state=eyJmaWxlcyI6eyIvc3JjL2luZGV4LmpzIjp7ImNvZGUiOiJpbXBvcnQgeyBBcHBsaWNhdGlvbiwgQXNzZXRzLCBHcmFwaGljcyxNYXRyaXggfSBmcm9tICdwaXhpLmpzJztcblxuKGFzeW5jICgpID0%2BXG57XG4gICAgLy8gQ3JlYXRlIGEgbmV3IGFwcGxpY2F0aW9uXG4gICAgY29uc3QgYXBwID0gbmV3IEFwcGxpY2F0aW9uKCk7XG5cbiAgICAvLyBJbml0aWFsaXplIHRoZSBhcHBsaWNhdGlvblxuICAgIGF3YWl0IGFwcC5pbml0KHtcbiAgICAgICAgYW50aWFsaWFzOiB0cnVlLFxuICAgICAgICBiYWNrZ3JvdW5kQ29sb3I6ICd3aGl0ZScsXG4gICAgICAgIHJlc2l6ZVRvOiB3aW5kb3csXG4gICAgfSk7XG5cbiAgICAvLyBBcHBlbmQgdGhlIGFwcGxpY2F0aW9uIGNhbnZhcyB0byB0aGUgZG9jdW1lbnQgYm9keVxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYXBwLmNhbnZhcyk7XG4gICAgY29uc3QgbWF0ID0gbmV3IE1hdHJpeCgpLnNjYWxlKDMsMSkgXG4gICAgY29uc3QgZ3JhcGhpY3MgPSBuZXcgR3JhcGhpY3MoKS5zdmcoYFxuICAgICAgICAgICAgPHN2ZyBoZWlnaHQ9XCI0MDBcIiB3aWR0aD1cIjQ1MFwiIHhtbG5zPVwiaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmdcIj5cbiAgICAgICAgICAgICAgICA8IS0tIERyYXcgdGhlIHBhdGhzIC0tPlxuICAgICAgICAgICAgICAgIDxwYXRoIGlkPVwibGluZUFCXCIgZD1cIk0gMTAwIDM1MCBsIDE1MCAtMzAwXCIgc3Ryb2tlPVwicmVkXCIgc3Ryb2tlLXdpZHRoPVwiNFwiLz5cbiAgICAgICAgICAgICAgICA8cGF0aCBpZD1cImxpbmVCQ1wiIGQ9XCJNIDI1MCA1MCBsIDE1MCAzMDBcIiBzdHJva2U9XCJyZWRcIiBzdHJva2Utd2lkdGg9XCI0XCIvPlxuICAgICAgICAgICAgICAgIDxwYXRoIGlkPVwibGluZU1JRFwiIGQ9XCJNIDE3NSAyMDAgbCAxNTAgMFwiIHN0cm9rZT1cImdyZWVuXCIgc3Ryb2tlLXdpZHRoPVwiNFwiLz5cbiAgICAgICAgICAgICAgICA8cGF0aCBpZD1cImxpbmVBQ1wiIGQ9XCJNIDEwMCAzNTAgcSAxNTAgLTMwMCAzMDAgMFwiIHN0cm9rZT1cImJsdWVcIiBmaWxsPVwibm9uZVwiIHN0cm9rZS13aWR0aD1cIjRcIi8%2BXG5cbiAgICAgICAgICAgICAgICA8IS0tIE1hcmsgcmVsZXZhbnQgcG9pbnRzIC0tPlxuICAgICAgICAgICAgICAgIDxnIHN0cm9rZT1cImJsYWNrXCIgc3Ryb2tlLXdpZHRoPVwiM1wiIGZpbGw9XCJibGFja1wiPlxuICAgICAgICAgICAgICAgICAgICA8Y2lyY2xlIGlkPVwicG9pbnRBXCIgY3g9XCIxMDBcIiBjeT1cIjM1MFwiIHI9XCI0XCIgLz5cbiAgICAgICAgICAgICAgICAgICAgPGNpcmNsZSBpZD1cInBvaW50QlwiIGN4PVwiMjUwXCIgY3k9XCI1MFwiIHI9XCI0XCIgLz5cbiAgICAgICAgICAgICAgICAgICAgPGNpcmNsZSBpZD1cInBvaW50Q1wiIGN4PVwiNDAwXCIgY3k9XCIzNTBcIiByPVwiNFwiIC8%2BXG4gICAgICAgICAgICAgICAgPC9nPlxuICAgICAgICAgICAgPC9zdmc%2BXG4gICAgICAgIGApLnNldFRyYW5zZm9ybShtYXQpO1xuICAgIFxuICAgIGFwcC5zdGFnZS5hZGRDaGlsZChncmFwaGljcyk7XG59KSgpO1xuIn0sIi9zcmMvc3R5bGVzLmNzcyI6eyJjb2RlIjoiYm9keSB7IG1hcmdpbjogMDsgb3ZlcmZsb3c6IGhpZGRlbjsgfSJ9LCIvaW5kZXguaHRtbCI6eyJjb2RlIjoiXG48IURPQ1RZUEUgaHRtbD5cbiAgPGh0bWw%2BXG4gIDxoZWFkPlxuICA8dGl0bGU%2BUGl4aUpTIFBsYXlncm91bmQ8L3RpdGxlPlxuICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIiAvPlxuICA8bGluayByZWw9XCJzdHlsZXNoZWV0XCIgaHJlZj1cInNyYy9zdHlsZXMuY3NzXCI%2BXG48L2hlYWQ%2BXG48Ym9keT5cbiAgPHNjcmlwdCBzcmM9XCJzcmMvaW5kZXguanNcIj48L3NjcmlwdD5cbjwvYm9keT5cbjwvaHRtbD4ifSwiL3BhY2thZ2UuanNvbiI6eyJjb2RlIjoie1xuICBcInNjcmlwdHNcIjoge1xuICAgIFwic3RhcnRcIjogXCJwYXJjZWwgaW5kZXguaHRtbCAtLW9wZW5cIixcbiAgICBcImJ1aWxkXCI6IFwicGFyY2VsIGJ1aWxkIGluZGV4Lmh0bWxcIlxuICB9LFxuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJwaXhpLmpzXCI6IFwiOC41LjFcIlxuICB9LFxuICBcImRldkRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJwYXJjZWwtYnVuZGxlclwiOiBcIl4xLjYuMVwiLFxuICAgIFwiQGJhYmVsL2NvcmVcIjogXCJeNy4yMS4zXCIsXG4gICAgXCJAYmFiZWwvcGx1Z2luLXByb3Bvc2FsLWNsYXNzLXByb3BlcnRpZXNcIjogXCJeNy4xMC4xXCJcbiAgfSxcbiAgXCJtYWluXCI6IFwiL2luZGV4Lmh0bWxcIlxufSJ9LCIvLmJhYmVscmMiOnsiY29kZSI6IntcbiAgXCJwcmVzZXRzXCI6IFtcbiAgICBbXG4gICAgICBcIkBiYWJlbC9wcmVzZXQtZW52XCIsXG4gICAgICB7XG4gICAgICAgIFwidXNlQnVpbHRJbnNcIjogXCJlbnRyeVwiLFxuICAgICAgICBcImNvcmVqc1wiOiBcIjMuMjlcIixcbiAgICAgICAgXCJ0YXJnZXRzXCI6IFwibGFzdCAyIGNocm9tZSB2ZXJzaW9uc1wiXG4gICAgICB9XG4gICAgXVxuICBdLFxuICBcInBsdWdpbnNcIjogW1xuICAgIFwiQGJhYmVsL3BsdWdpbi1wcm9wb3NhbC1jbGFzcy1wcm9wZXJ0aWVzXCJcbiAgXVxufSJ9LCIvc2FuZGJveC5jb25maWcuanNvbiI6eyJjb2RlIjoie1xuICAgICAgICAgICAgICAgIFwiaW5maW5pdGVMb29wUHJvdGVjdGlvblwiOiBmYWxzZVxuICAgICAgICAgICAgfSJ9fSwidmlzaWJsZUZpbGVzIjpbIi9zcmMvaW5kZXguanMiXSwiYWN0aXZlRmlsZSI6Ii9zcmMvaW5kZXguanMifQ%3D%3D)

### Environment

- **`pixi.js` version**: *8.x*
- **Browser & Version**: *129.0.6668.71*
- **OS & Version**: *macOS 14.2 (23C64)*

**Comment by GoodBoyDigital** [comment]
Heya! This looks correct - you set the transformer than any shapes or svg will have that transform applied. If you set it after it won't have any effect. Let me know if that makes sense! (And that I have understood your issue correctly!) thanks!

**Comment by oubenruing** [comment]
Hi, my use case is that I need to load an SVG, display it on the screen, and then apply a matrix to change the scale of the SVG without scaling the SVG’s stroke. I tried the setFromMatrix method, but it scales the SVG's stroke as well. Is there any other way to achieve this?Thanks!

**Comment by GoodBoyDigital** [comment]
interesting use case! A couple of routes would be:

- Modify the stroke width in the svg before you call ```graphics.svg(`svg-string`)```
- iterate through `graphics.context.instructions` after calling svg and directly modify the stroke style width?

**Comment by oubenruing** [comment]
``` js
 const mat = new Matrix().scale(5,1) 
    const graphics = new Graphics().svg(`
            <svg height="400" width="450" xmlns="http://www.w3.org/2000/svg">
                <!-- Draw the paths -->
                <path id="lineAB" d="M 100 350 l 150 -300" stroke="red" stroke-width="4"/>
                </g>
            </svg>
        `)
   
    graphics.setFromMatrix(mat)

   // The stroke width is scaled differently on the x and y axes based on the matrix
   // I don't want it to change
```

I want features like [non-scaling-stroke](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect#non-scaling-stroke)
Thanks！

**Comment by GoodBoyDigital** [comment]
heya! You will need to redraw the svg each time the stroke changes on fly:



```
const mat = new Matrix().scale(5,1) 

// each draw

graphics.clear()
    .setTransform(mat) // apply here
    .svg(`
            <svg height="400" width="450" xmlns="http://www.w3.org/2000/svg">
                <!-- Draw the paths -->
                <path id="lineAB" d="M 100 350 l 150 -300" stroke="red" stroke-width="4"/>
                </g>
            </svg>
    `)
```

**Comment by oubenruing** [comment]
Got it, thanks a lot!
