### ISSUE TITLE
Objects do not stand out on stage when touched

### ISSUE THREAD

**Issue by gonulbuya** [pixijs/pixijs#11039]
### Current Behavior

Hello. When using "pointerdown" in v8, the touched object does not come to the front.
In previous versions, the following code worked. It does not work in v8.
e.currentTarget.parent.addChild(e.currentTarget);

### Expected Behavior

e.currentTarget.parent.addChild(e.currentTarget);
v8'de I'm waiting for it to work

### Steps to Reproduce

    function onClick(e){

      e.currentTarget.parent.addChild(e.currentTarget);

    }

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide an example for us to debug that would be ace 👍

**Comment by gonulbuya** [comment]
Maybe this is not a bug for pixij.

The example below works as I want in v8.
If the containers where the functions and objects are added are different, I cannot achieve what I want.

sprite.addEventListener("pointerdown",onClick)
kare.addEventListener("pointerdown",onClick)

function onClick(e){

e.currentTarget.parent.addChild(e.currentTarget);

e.currentTarget.scale.x *= 1.25;

e.currentTarget.scale.y *= 1.25;

}

What I expect is: even if the touched object is at the back, it should appear at the top of the stage, even if it is in different functions and different containers.
Is this possible with pixijs?

**Comment by bigtimebuddy** [comment]
This seems like a bug @GoodBoyDigital.
https://pixiplayground.com/#/edit/-hhAuAU4q_cDXES_jQ2K6

`addChild` seems to be doing the right thing and updating `children`'s order correctly.

@gonulbuya, workaround would be to do something like this:

```ts
const parent = target.parent;
parent.removeChild(target);
parent.addChild(target);
```

**Comment by gonulbuya** [comment]
const parent = target.parent;
parent.removeChild(target);
parent.addChild(target);

Yes, this code worked. Thank you.

**Comment by GoodBoyDigital** [comment]
yikes! thanks for looking in @bigtimebuddy - let me fix this now

**Comment by GoodBoyDigital** [comment]
fix is [here](https://github.com/pixijs/pixijs/pull/11041/files)

**Comment by gonulbuya** [comment]
> Thanks for reporting this [@gonulbuya](https://github.com/gonulbuya) 👍

You're welcome
