### ISSUE TITLE
Bug: Interactive/Pointer events firing at incorrect position relative to rendered object

### ISSUE THREAD

**Issue by nekroadmin** [pixijs/pixijs#11047]
### Current Behavior

I was trying to understand why my button object was not responding to interactions, even though it was set up correctly.

It seems that due to scaling and repositioning of the stage, the button object's interactive hit area has shifted to a different location. As a result, the object is drawn in the correct place visually but is only interactive in another part of the window. Alternatively, it could be the other way around – the exact issue is unclear.

Could you help identify the root cause?

### Expected Behavior

The button object should be interactive in the same location where it is rendered. If the button is drawn at the top left of the window, it should respond to pointer events in that same position.

### Steps to Reproduce

The following code seems to be responsible for breaking the interactivity of the object:
```
app.stage.scale.set(width / app.screen.width);
app.stage.position.y = app.screen.height - height;
```

You can find the code being used, and see the issue, in this demo: [Pixi Playground Demo](https://www.pixiplayground.com/#/edit/KGjE7B-KSg-kvB1jCcGSg).
You should be able to interact with the object at the bottom left of the window instead of the top left, where it is actually drawn.

### Environment

- **`pixi.js` version**: *pixi playground - or 8.5.2*
- **Browser & Version**: *130.0.6723.117 (64-bit)*
- **OS & Version**: *Windows 11 10.0.22631*
- **Running Example**: *[Pixi Playground Demo](https://www.pixiplayground.com/#/edit/KGjE7B-KSg-kvB1jCcGSg)*

**Comment by GoodBoyDigital** [comment]
heya! fixed the demo [here](https://www.pixiplayground.com/#/edit/as604NARHvc4xzEOD6R4h)

The main thing is that you need to call `app.renderer.resize(width, height)` as this will make sure all the other variables are correctly updated. Let me know if this works for ya!
