### ISSUE TITLE
Bug: pixelLine rendering error

### ISSUE THREAD

**Issue by MellowCo** [pixijs/pixijs#11096]
### Current Behavior

![Image](https://github.com/user-attachments/assets/47b15ba9-7029-4d8f-bd9f-b3d4482a1405)

### Expected Behavior

![Image](https://github.com/user-attachments/assets/68347eee-f967-4420-81d5-16110505df3b)

### Steps to Reproduce

https://github.com/MellowCo/pixi-bug

1. App.vue  count 
![Image](https://github.com/user-attachments/assets/efb4bd14-9d58-47f5-af30-b5191e6ff46b)

2. `count` exceeds 100
![Image](https://github.com/user-attachments/assets/a60eab5a-8bcb-4d47-af99-1a3cea383f8e)

### Environment

pixi.js version: 8.6.0
OS & Version: Windows 11

**Comment by Zyie** [comment]
Hey @MellowCo thanks for raising this, we are looking into it
