### ISSUE TITLE
Bug: Setting alpha to 0. in graphics.beginFill has the same effect as setting it to 1.

### ISSUE THREAD

**Issue by tari3x** [pixijs/pixijs#11101]
### Current Behavior

Setting alpha to 0. in graphics.beginFill has the same effect as setting it to 1. 

### Expected Behavior

Setting alpha to 0. in graphics.beginFill should be the limit of setting it to 0.1, 0.01, ...

### Steps to Reproduce

```
// Create our application instance
(async () => {
    const app = new PIXI.Application();
    await app.init({
        width: window.innerWidth,
        height: window.innerHeight
    })
    document.body.appendChild(app.canvas);

    var graphics = new PIXI.Graphics();
    app.stage.addChild(graphics);

    graphics.beginFill(0xFF0000, 0.)

    graphics.drawRect(0, 0, 300, 200);

    graphics.endFill();

})();
```

### Environment

- **`pixi.js` version**: 8.6.1
- **Browser & Version**: firefox, chrome
- **Running Example**: https://www.pixiplayground.com/#/edit/5Fw4IN9ZZ-yEo68SXvO1P

### Additional Information

I am aware that this API is deprecated and it looks lie like the new interface gets it right. However I am very sad about the breakage - I am a visual artist and I lost the opportunity to do several performances because things were inexplicably broken after a pixi upgrade.

**Comment by bigtimebuddy** [comment]
Thanks for reporting @tari3x, got a fix for that.
