### ISSUE TITLE
Bug: Container not rendered when it has `Sprite` as mask + `cacheAsTexture`

### ISSUE THREAD

**Issue by alvov-evo** [pixijs/pixijs#11120]
### Current Behavior

Container and it's children are not rendered (not visible).

### Expected Behavior

Container and its children are rendered same way as they would with `cacheAsTexture(false)`.

### Steps to Reproduce

Playground: https://www.pixiplayground.com/#/edit/LmuFz_l1K9cH2LBzoP8eT

Steps to reproduce:
1. create a Container
1. create Sprite or Graphics object, add as child to Container
1. create (another) Sprite object that will be used as a mask, add as child to Container
1. set Sprite from step 2 as `mask` for object from step 1
1.  set `cacheAsTexture(true)` for the Container

### Environment

- **`pixi.js` version**: *8.6.2* (also 8.6.1)
- **Browser & Version**: *Chrome 131*
- **OS & Version**: *macOS Sequoia 15.1*
- **Running Example**: *https://www.pixiplayground.com/#/edit/LmuFz_l1K9cH2LBzoP8eT*

**Comment by GoodBoyDigital** [comment]
thanks for flagging! looking into today :)
