### ISSUE TITLE
Bug: latest typescript: missing `altitudeAngle`, `azimuthAngle` in `FederatedPointerEvent` (incorrectly implements 'PointerEvent')

### ISSUE THREAD

**Issue by rvion** [pixijs/pixijs#11145]
### Current Behavior

type error: 

```
node_modules/pixi.js/lib/events/FederatedPointerEvent.d.ts:6:22 - error TS2420: Class 'FederatedPointerEvent' incorrectly implements interface 'PointerEvent'.
  Type 'FederatedPointerEvent' is missing the following properties from type 'PointerEvent': altitudeAngle, azimuthAngle
```

### Expected Behavior

no type error

### Steps to Reproduce

update to latest pixi, latest typescript

### Environment

- **`pixi.js` version**: *pixi.js@8.6.4* (latest as of 2024-12-10)
- **`typescript` **: *typescript@5.7.2* (latest as of 2024-12-10)
- **Browser & Version**: *electron@32.1.2*
- **OS & Version**: *e.g. macos m1, latest version*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

### Possible Solution

add the two missing properties somewhere so they end up in in node_modules/pixi.js/lib/events/FederatedPointerEvent.d.ts

```
    altitudeAngle: number;
    azimuthAngle: number;
```

**Comment by zenblender** [comment]
Is there a way to get latest TypeScript to work with pixi.js v7? I'm assuming that v7 is no longer being updated?

**Comment by bigtimebuddy** [comment]
For bugs, we can do a v7 release if someone wants to make a PR to the v7.x branch.
