### ISSUE TITLE
Bug: Graphics returns two BatchableGraphics on destroy

### ISSUE THREAD

**Issue by rnike** [pixijs/pixijs#11153]
### Current Behavior

Don't know if this is a bug, I saw when destroying Graphics, it returns 2 BatchableGraphics to the BigPool

### Expected Behavior

Returns 1 BatchableGraphics to the BitPool for an object

### Steps to Reproduce

1. Add 1000 shapes to the stage
2. Print `PIXI.BigPool.getPool(PIXI.BatchableGraphics)` sees the _pool property is an empty array
3. Destroy all shape created by step 1
4. Print `PIXI.BigPool.getPool(PIXI.BatchableGraphics)` again, the _pool property now is a 2000 length array

or see the running example
https://www.pixiplayground.com/#/edit/L1Be5gscZa1QxtZuwjPQg

### Environment

- **`pixi.js` version**: 8.6.4
- **Browser & Version**: Chrome 131
- **OS & Version**: macOS 14.3.1
- **Running Example**: https://www.pixiplayground.com/#/edit/L1Be5gscZa1QxtZuwjPQg

**Comment by GoodBoyDigital** [comment]
thanks for flaggin - I'll look into this!

**Comment by GoodBoyDigital** [comment]
heya! this is actually expected!

- essentially each context has holds the batchable graphics it needs to render somthing.
- when rendering the batch creates a (shallow) copy of it for the Graphics instance using it.

in the below example we create on context and use it accross 1000 graphics

[example](https://www.pixiplayground.com/#/edit/x2SR0S0Di_XvwOC9Uz45M)

not that we end up with 1000 batchable graphics (from the graphics) and one for the context itself

Hope that makes sense!

**Comment by rnike** [comment]
@GoodBoyDigital Thanks for the explanation, it makes sense now
