### ISSUE TITLE
Displacement filter stretches objects that intersect edge of stage.

### ISSUE THREAD

**Issue by ghost** [pixijs/pixijs#2372]
Hello!

I've been trying to solve this problem for a while now. Whenever I displace an object that is halfway outside the stage, it stretches that object in a weird way. This might be something i'm doing wrong since i'm not seeing this issue in the example.

[Here is a codepen showing the issue.](http://codepen.io/anon/pen/GZgJqG)

You can clearly see the issue if you look at the top of the image the second time it goes up above the bounds of the stage.

**Comment by Gaubee** [comment]
The same problem, how to solve this problem? :(

**Comment by englercj** [comment]
Is this still active in v4?

**Comment by Gaubee** [comment]
yeah. look the V4 [displacement-map Demo](https://pixijs.github.io/examples/#/filters/displacement-map.js)

**Comment by ivanpopelyshev** [comment]
Black? AGAIN? clamp failed, ugh :(

**Comment by weepy** [comment]
I still have this problem :(

**Comment by maxackerman** [comment]
I'm seeing the same issue with Pixi v4.8.7 and testing v5

Here is a codepen highlighting the bug: https://codepen.io/violetoffice/full/qwgvQx

The image gets stretched a distance equal to the amount of the displacement. This only happens if he image touches the edge of the scene.

**Comment by mcdenhoed** [comment]
To add on to maxackerman's comment, I am also seeing this in v5 (5.0.2).

**Comment by jdwillemse** [comment]
Still a problem in 5.2.0

**Comment by Thaums** [comment]
Its still a problem in 5.3.3 as well, I don't have much shader knowledge but I assume the issue is because it isn't run for pixels outside of the screen?
