### ISSUE TITLE
Support WebGL without stencil

### ISSUE THREAD

**Issue by Adamfsk** [pixijs/pixijs#5902]
### Expected Behavior
Browser/device configurations that support WebGL but don’t support stencil should use fallbacks for features such as masking, that the framework is currently relying on stencil to perform.

### Current Behavior
Configurations without stencil support will fail with a runtime error saying that WebGL isn’t supported and to use the legacy branch instead. 

### Possible Solution
Masking can be performed in other ways in WebGL. Some explanations of two alternate methods can be found on [this stackoverflow thread](https://stackoverflow.com/questions/39860677/how-to-clip-multiple-textures-to-polygon-in-three-js)

### Environment
- **`pixi.js` @latest

**Comment by ivanpopelyshev** [comment]
I agree, and I think I know fallbacks. I'm gonna prepare big stencil-related PR for 5.2.0.

**Comment by englercj** [comment]
I also agree, using fallbacks for when we don't have stencil rather than just giving up on WebGL entirely would be awesome.

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev addressed this in his two recent PRs for stencils. closing.

**Comment by bySabi** [comment]
@bigtimebuddy @ivanpopelyshev when this feature will be available?

 I Still get "WebGL renderer unsupported in this browser" with Chrome  on PixiJS `5.3.0`

**Comment by cedric-gcturbo** [comment]
I also have this problem with Chrome `Version 85.0.4183.83 (Official Build) (64-bit)` on MacOS `10.12.6`.
What fails is the call to `gl.getContextAttributes()` returning `null` inside `isWebGLSupported`
