### ISSUE TITLE
ios13 graphics arc causes error

### ISSUE THREAD

**Issue by samcreate** [pixijs/pixijs#6170]
### Expected Behavior
To draw a full circle with graphics.arc

### Current Behavior
Creates the arc but with a error thrown

### Steps to Reproduce

1.  go to [this link](https://www.pixiplayground.com/#/edit/WAL9OjtbQMP6aKxkk~4fw) on iOS 13
2. Error triggered in console: WebGL: INVALID_VALUE: uniform1iv: invalid texture unit - syncUniforms core.es.js:9469

### Environment

- **`pixi.js` version**: 5 up (tried every version of 4
- **Browser & Version**: Mobile Safari
- **OS & Version**: iOS 13.1.2
- **Running Example**: https://www.pixiplayground.com/#/edit/WAL9OjtbQMP6aKxkk~4fw

**Comment by samcreate** [comment]
Issues happens here as well: 
https://pixijs.io/examples/#/graphics/advanced.js

**Comment by ivanpopelyshev** [comment]
https://www.html5gamedevs.com/topic/43935-ios-13-webgl-invalid_value-uniform1iv-invalid-texture-unit/

Yeah, iOS13 is buggy :(

**Comment by ivanpopelyshev** [comment]
@samcreate 

please try 

```js
PIXI.settings.PREFER_ENV = PIXI.ENV.WEBGL
```

**Comment by ivanpopelyshev** [comment]
@samcreate which iphone is it? 

Cant reproduce on iphone7

**Comment by samcreate** [comment]
8 plus, I’ll give your suggestion a try shortly

**Comment by ivanpopelyshev** [comment]
Found bug in `dev` branch regarding that pixi-playground example, but its just lineStyle problem that doesnt throw out rendering. in `5.1.5` its fine, just dont use `latest development` for testing :)

**Comment by samcreate** [comment]
I tried using `PIXI.settings.PREFER_ENV = PIXI.ENV.WEBGL`  still the error persists. 

I think it's interesting that it's only happening on the iPhone 7/8+ (maybe the iphone 11pro)  sizes. I wonder why?

**Comment by adamka** [comment]
@ivanpopelyshev This is replicatable in xcode simulator, with or without PIXI.settings.PREFER_ENV = PIXI.ENV.WEBGL enabled.

Open https://www.pixiplayground.com/#/edit/WAL9OjtbQMP6aKxkk~4fw in the simulator to see the error:

![Screenshot 2019-11-21 at 18 48 15](https://user-images.githubusercontent.com/4103595/69367211-bd0fb000-0c8f-11ea-817b-762f7a00a826.png)

The function where it actually fails is an anonymous function, but seems to be mapped. Here's the source:

`function anonymous(ud, uv, renderer) {
var v = null;
    var cv = null
    var gl = renderer.gl
            cv = ud.uSamplers.value;
            v = uv.uSamplers;
            gl.uniform1iv(ud.uSamplers.location, v);

}`

**Comment by adam-mvk** [comment]
I also get warnings about `uniform1iv` being unsupported in chrome

**Comment by naranjamecanica** [comment]
FYI I'm seeing the same error in a Capacitor app running on a iPhone XS  iOS 13.3

**Comment by eXponenta** [comment]
Simulator is not a real device:) Render system is not same and you should use real device for test, when report about bugs.

iPad 2018 iOS 13.3.1 WebGL - doesn't reprodused on real browser.

@naranjamecanica Capacitor use WKWebView that used Safary, basically it isn't bugged, but u should provide a app for debugging on different system versions.

![IMG_0094](https://user-images.githubusercontent.com/12572222/76386683-2b2ece80-6376-11ea-9800-61167b831ab7.png)

**Comment by adam-mvk** [comment]
@eXponenta I provided the information about it failing in Xcode simulator as it’s easily replicatable. It does occur on live devices!

**Comment by FNeves88** [comment]
> ![Screenshot 2019-11-21 at 18 48 15](https://user-images.githubusercontent.com/4103595/69367211-bd0fb000-0c8f-11ea-817b-762f7a00a826.png)

I'm with the same problem on iphone 7 with my app.

But besides that I also have another trigger point in my application that makes the browser crash and webpage reload, not always but most of the time, that is when I call:
`PIXI.Renderer.generateTexture(...)`

**Comment by yangxiao86** [comment]
I'm with the same problem on iphone Xs(13.3.1) with my app.

![image](https://user-images.githubusercontent.com/4556693/84351053-2257ce00-abed-11ea-924f-3a7351aadbe9.png)

**Comment by FNeves88** [comment]
Any news on this?

**Comment by Adamfsk** [comment]
Bump
