### ISSUE TITLE
GraphicsGeometry#updateBatches: Don't force repeat wrap-mode

### ISSUE THREAD

**Issue by ShukantPal** [pixijs/pixijs#6714]
https://github.com/pixijs/pixi.js/blob/01581acc0415a89034b0ef85504467172f8ec5e3/packages/graphics/src/GraphicsGeometry.ts#L508

This hard-coded wrap-mode not only overrides the user-set `wrapMode`, but also leaves no way to change the wrap-mode.

**Comment by ivanpopelyshev** [comment]
need something like WRAP_MODES.AUTO ?
