### ISSUE TITLE
Applying more than one filter resizes element

### ISSUE THREAD

**Issue by TomekStaszkiewicz** [pixijs/pixijs#6811]
### Expected Behavior
I expect that when I set more than one filter on an element I will receive the element with the same size but with filter applied.
### Current Behavior
The element gets resized, sometimes it even disappears. 
![Screenshot 2020-08-13 at 13 22 41](https://user-images.githubusercontent.com/46328998/90128973-13fe6d80-dd68-11ea-986f-93e762aa7ec1.png)
### Possible Solution
I am not sure what causes that issue. In the code sandbox when you click `append filter to container` the element gets scaled. Also when you change the `app.current.stage.scale(1.5)` to `app.current.stage.scale(0.5)` it gets invisible(not sure if it is too small to render or if it gets transparent. 
We noticed that when we change the `const transform` variable to `undefined`, it work fine. Sadly, we need that transform in our project.

What is more - try to uncomment lines 39-42 and, set `app.current.stage.scale(1.5)` and refresh the browser window. When you check the `append filter to container`, set number of filters to 2 and click the button couple of times you will see that the image inside the red square is cropped. 
![Screenshot 2020-08-13 at 13 21 36](https://user-images.githubusercontent.com/46328998/90128888-edd8cd80-dd67-11ea-9461-5a658939faf5.png)

### Steps to Reproduce
https://codesandbox.io/s/confident-grass-5u05g?file=/src/App.js
### Environment

- **`pixi.js` version**: _e.g. 5.3.0_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: https://codesandbox.io/s/confident-grass-5u05g?file=/src/App.js

**Comment by ivanpopelyshev** [comment]
Well, we've changed projectionSystem and filterSystem in 5.3, thanks to @SukantPal .
Yes, we received a number of complaints about it, without good demos though, so thanks for the demo.

Your example is too hacky. I honestly dont understand what is going on with that extra renderer. Maybe the bug is something like "first rendered frame is not correct", or maybe something was added that affects bounds and GlowFilter changes bounds of element, or maybe canvas.drawImage() renders random framebuffer and not the one that is on screen. Too many possibilities, someone has to debug it. did you try it on 5.2.4 or .5.3.3 ?

**Comment by TomekStaszkiewicz** [comment]
Hello again! 

I know it seems complicated, and that is why we created [another reproduction](https://codesandbox.io/s/green-darkness-yt3ji?file=/src/App.js)
You can see that when you set the scale to be 1.5 or 2.0 and render the 1st bunny(the one with sprite mask), the bunny is resized and moved.

We need the second renderer because we use it to handle interactions with canvas. We have like 2 layers:
1. The rendered canvas with all the elements
2. The interaction layer.

The issue is that because sometimes elements are resized because of the mask or filter, we are not able to click on the elements.
We tried it on 5.3.3 but the issue is still there. :(

**Comment by SukantPal** [comment]
Have you had a chance to look at https://github.com/pixijs/pixi.js/issues/6828 because there I describe some the subtle changes regarding RenderTexture semantics.

I'll try to debug your reproduction sometime this week.

**Comment by muhammadhaseebsohail** [comment]
@ivanpopelyshev  can you please me making this?
i want to transform a component and want to get its increased height and width. 
here i want border and these points on sprite,. 
<img width="168" alt="Screenshot 2020-12-01 at 1 46 56 PM" src="https://user-images.githubusercontent.com/37294317/100717331-b73cc680-33db-11eb-999f-8da08a4d9abb.png">
