### ISSUE TITLE
Mask ignored when rendering on RenderTexture (Firefox Linux)

### ISSUE THREAD

**Issue by SnowyCoder** [pixijs/pixijs#6822]
I've added a masked sprite to a container, when I render it on screen the mask works correctly but when I try to render it on a RenderTexture the mask is ignored.
Problem is, I tested it in some environments, here's the list:
|  |  Windows 10 | Manjaro KDE   |
| ------------- |:------:|:-------:|
| Chrome    | Ok    |  Ok   |
| Firefox      | Ok    |  Bug |

I have no clue on the bug's origin.
I've created a [simple playground](https://www.pixiplayground.com/#/edit/iJ6CBxiP5PGlzGXt7zi1s), in the upper half you can see the pixi.js behaviour and in the lower half you can see the RenderTexture behaviour.

### Expected Behavior
![image](https://user-images.githubusercontent.com/10945206/90764330-761b1d80-e2e8-11ea-9ae2-7189ce33c45e.png)

### Current Behavior
![image](https://user-images.githubusercontent.com/10945206/90764494-abc00680-e2e8-11ea-9ee5-fe748d89197d.png)

### Possible Solution
I don't know of any, maybe using filters will bypass the bug but I haven't checked.

### Steps to Reproduce
Get linux + Firefox (I think?) and use this link below.
https://www.pixiplayground.com/#/edit/iJ6CBxiP5PGlzGXt7zi1s

### Environment

- **`pixi.js` version**: 5.3.3
- **Browser & Version**: Firefox 79.0
- **OS & Version**: 5.4.57-1-MANJARO + KDE Plasma 5.12.4
- **Running Example**: https://www.pixiplayground.com/#/edit/iJ6CBxiP5PGlzGXt7zi1s

**Comment by dev7355608** [comment]
Hi @SnowyCoder! Did you gain any new insights, and/or did you report this bug to Mozilla yet?

**Comment by neovatar** [comment]
The bug occurs on my system (Ubuntu18.04, Firefox 87, Nvidia 2070) with a software that uses pixijs. If you want me to test code, just tag me in this issue.

**Comment by SnowyCoder** [comment]
Sorry, my little project ended up not needing this code anymore so I haven't looked into it any further, we would need some way to extract the raw WebGL calls but I'm having problems with SpectorJs.

**Comment by neovatar** [comment]
Just tested with the example that @dev7355608 provided, it is still occuring with latest pixijs and Firefox Nightly 92.0a1 (2021-07-22) (64-bit) on Linux.

Example: https://www.pixiplayground.com/#/edit/e-NUi7fWC-JijPGTbtjSc (should show triangle bunny, but does not)

**Comment by madclem** [comment]
This error is now also happening on Safari 15.+ and iOS Safari. Weirdly, it seems to be very device specific (it works as expected on my iPhone / Desktop Safari, but not on my colleagues devices).

In the meantime, I fixed it on our project using this:
https://gist.github.com/madclem/9de5c340554be824c1cbfd85538358a2

Hopefully it can help!

**Comment by dev7355608** [comment]
> This error is now also happening on Safari 15.+ and iOS Safari. Weirdly, it seems to be very device specific (it works as expected on my iPhone / Desktop Safari, but not on my colleagues devices).
> 
> In the meantime, I fixed it on our project using this: https://gist.github.com/madclem/9de5c340554be824c1cbfd85538358a2
> 
> Hopefully it can help!

I have a question: after rendering `dummy` once to the texture do all subsequent render calls produce correct results without rendering `dummy` ever again (even at a later point in time, or even when rendering other things in between to other render targets)? I assume that's the case because of `_hasRendered`?

**Comment by madclem** [comment]
> > This error is now also happening on Safari 15.+ and iOS Safari. Weirdly, it seems to be very device specific (it works as expected on my iPhone / Desktop Safari, but not on my colleagues devices).
> > In the meantime, I fixed it on our project using this: https://gist.github.com/madclem/9de5c340554be824c1cbfd85538358a2
> > Hopefully it can help!
> 
> I have a question: after rendering `dummy` once to the texture do all subsequent render calls produce correct results without rendering `dummy` ever again (even at a later point in time, or even when rendering other things in between to other render targets)? I assume that's the case because of `_hasRendered`?

Exactly, the `dummy` only gets rendered once.
What I have done in our project is put these helpers into a pool to reuse them in different places, as we do quite a lot of rendering to textures.

**Comment by dev7355608** [comment]
@madclem Interesting. I prepared a few of tests. Let me know whether they succeed or fail:

1. https://www.pixiplayground.com/#/edit/dKPnH5fCiFNzBvhhl9Hq5
2. https://www.pixiplayground.com/#/edit/rsvaluxZhRgVCmW3W8bO3
3. https://www.pixiplayground.com/#/edit/FsUPrjQLEWXtiz5jN3brW
4. https://www.pixiplayground.com/#/edit/aHAIHyBZFIYVcWAOZ-ucA
5. https://www.pixiplayground.com/#/edit/EqPKVBtX11RHHR2frqX2l

![bunny_test](https://user-images.githubusercontent.com/31905376/141158906-b5b39519-22f8-4780-b974-1a37000682b6.png)

**Comment by madclem** [comment]
@dev7355608 Great stuff!

On MacOS firefox:
1. failure
2. failure
3. **success** 💯 
4. failure

**Comment by dev7355608** [comment]
@madclem Follow-up test: https://www.pixiplayground.com/#/edit/ZIryNpBGI1oJ-hcwLpaKd

**Comment by madclem** [comment]
@dev7355608 in the logs: `stencil buffer was initialized with 0`

**Comment by dev7355608** [comment]
@madclem https://www.pixiplayground.com/#/edit/t73KdF129qAyHndkD_bPG

**Comment by madclem** [comment]
@dev7355608 ---> "OK" (looks like it's getting somewhere! 👍  )

**Comment by dev7355608** [comment]
@madclem I actually expected it to be not OK. What does this say? https://www.pixiplayground.com/#/edit/_GUnfNXI1IZknG4vUlv9k (it should be FAILURE)

**Comment by madclem** [comment]
@dev7355608 this one is "OK" too

**Comment by dev7355608** [comment]
@madclem I must have messed something up in my tests, I think. Does this fail? https://www.pixiplayground.com/#/edit/WxCsdIwK-u6EFDE0vvtwQ

![bunny_test](https://user-images.githubusercontent.com/31905376/141158906-b5b39519-22f8-4780-b974-1a37000682b6.png)

**Comment by madclem** [comment]
apologies for the delay, I don't seem to receive any new notifications! 
Weirdly, on MacOS Firefox, it doesn't show **at all**!

**Comment by dev7355608** [comment]
> Weirdly, on MacOS Firefox, it doesn't show at all!

Very weird, but it should show the same thing as https://www.pixiplayground.com/#/edit/dKPnH5fCiFNzBvhhl9Hq5 if I didn't mess up.

So my theory was that after the stencil buffer is created and attached to the framebuffer of the render texture the stencil buffer is in some kind incomplete/weird state for some reason and only after the first clearing it is ready to be used. PIXI does not clear the stencil buffer after it is created, and assumes it is initialized with 0, and clears the stencil buffer after rendering basically. The first successful test confirmed that theory, but the other tests, which I wrote to confirm that the stencil buffer is broken until clear, gave unexpected results. Maybe there's more to the picture or I messed something up.

In this test I patched `StencilSystem`'s push and pop: I changed it to clear in push instead pop. This way the stencil buffer is cleared immediately after it is created. Does this test succeed? https://www.pixiplayground.com/#/edit/ILIR4vP9hu6iYbo_xUO6d

**Comment by madclem** [comment]
@dev7355608 The first ( https://www.pixiplayground.com/#/edit/dKPnH5fCiFNzBvhhl9Hq5) shows the full funny.

The latest one (https://www.pixiplayground.com/#/edit/ILIR4vP9hu6iYbo_xUO6d) succeeds indeed! 💯

**Comment by dev7355608** [comment]
@neovatar Please let me know whether this fix works for you too.

1. This should fail (w/o fix): https://www.pixiplayground.com/#/edit/dKPnH5fCiFNzBvhhl9Hq5
2. This should succeed (w/ fix): https://www.pixiplayground.com/#/edit/ILIR4vP9hu6iYbo_xUO6d

![bunny_test](https://user-images.githubusercontent.com/31905376/141158906-b5b39519-22f8-4780-b974-1a37000682b6.png)

**Comment by domis86** [comment]
> @neovatar Please let me know whether this fix works for you too.
> 
>     1. This should fail (w/o fix): https://www.pixiplayground.com/#/edit/dKPnH5fCiFNzBvhhl9Hq5
> 
>     2. This should succeed (w/ fix): https://www.pixiplayground.com/#/edit/ILIR4vP9hu6iYbo_xUO6d

confirmed on on my Ubuntu 20 (Firefox 86)

**Comment by neovatar** [comment]
> 1. This should fail (w/o fix): https://www.pixiplayground.com/#/edit/dKPnH5fCiFNzBvhhl9Hq5
> 2. This should succeed (w/ fix): https://www.pixiplayground.com/#/edit/ILIR4vP9hu6iYbo_xUO6d

1. fails
2. succeeds

Ubuntu 20.04 with both: 
- Firefox 94.0
- Firefox Nightly 96.0a1 (2021-11-19)
