### ISSUE TITLE
Multisampled textures not handled at all in PixiJS internally

### ISSUE THREAD

**Issue by ShukantPal** [pixijs/pixijs#6844]
@ivanpopelyshev When you created multisampled textures with renderbuffers, you introduced an extra step in the render process:

```js
msaaTexture.framebuffer.multisample = 16;

renderer.render(displayObject, msaaTexture);
renderer.framebuffer.blit();
```

This makes it very problematic to the extent that PixiJS itself fails to take care of this extra step in masking.

No blit here:
https://github.com/pixijs/pixi.js/blob/064135e795dbfe7b53248ff457d71cb8536077ac/packages/core/src/mask/StencilSystem.ts#L93

@bigtimebuddy I would propose that we do a blit in `renderer#render` and save the user all future hassle. What do you think?

## Pen :pen:

Here's an example that fails with masking (comment out `graphics.mask = mask`, and it'll work):

https://codepen.io/sukantpal/pen/abNwBoN

**Comment by ivanpopelyshev** [comment]
We should add an `if` there like in FilterSystem, right?

**Comment by SukantPal** [comment]
You don’t really need to add an `if` b/c `framebuffer.blit()` already checks for it. What do you think about moving the blit into `Renderer#render`?

Sent from my iPad

On Aug 29, 2020, at 8:25 AM, Ivan Popelyshev <notifications@github.com> wrote:

﻿

We should add an if there like in FilterSystem, right?

**Comment by ivanpopelyshev** [comment]
Wait, i still dont udnerstand why doesnt your example work.

I just told you what i think about moving it there.

**Comment by SukantPal** [comment]
@ivanpopelyshev Sorry, that part of your message didn't go into my email. The circle in the example won't show up on a WebGL-2 enabled browser.

**Comment by ivanpopelyshev** [comment]
Because i edit my messages. most of the time.

**Comment by bigtimebuddy** [comment]
I'm in favor of options for render. What do you think about these two signatures?

```js
render(displayObject, options)
render(displayObject, renderTexture, options)
```

Where options is:
* clear
* transform
* skipUpdateTransform
* blit (proposed)

**Comment by SukantPal** [comment]
+1

**Comment by SukantPal** [comment]
We should also create a “renderer.flush” method so users don’t have to both flush the batch renderer and blit the framebuffer after rendering a display-object.

On Sep 12, 2020, at 6:12 AM, Matt Karl <notifications@github.com<mailto:notifications@github.com>> wrote:



I'm in favor of options for render. What do you think about these two signatures?

render(displayObject, options)
render(displayObject, renderTexture, options)

Where options is:

  *   clear
  *   transform
  *   skipUpdateTransform
  *   blit (proposed)

**Comment by GoodBoyDigital** [comment]
both good! no super strong opinion. probably option one! something for next major version?

**Comment by ivanpopelyshev** [comment]
Finally! As prophecied! 

Option two, because most of external calls will be done with renderTexture, and default options are good for case when `renderTexture===null`

**Comment by SukantPal** [comment]
I think doing both would be okay since the render() is not hot.

**Comment by dev7355608** [comment]
Rendering masked objects to multisampled textures doesn't work in v6.0.2. I'd expect to see no bunny at all: [link](https://www.pixiplayground.com/#/edit/ybrmwKaqoVkrl_9_9vCad).

Chrome says
```
[.WebGL-00004148055A2D80] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
```

Firefox says
```
WebGL warning: blitFramebuffer: Framebuffer not complete. (status: 0x8d56) 
WebGL warning: blitFramebuffer: Framebuffer must be complete.
```
