### ISSUE TITLE
Typescript throws error when initializing PIXI.Mesh with PIXI.Shader

### ISSUE THREAD

**Issue by tomktjemsland** [pixijs/pixijs#6882]
The problem can be seen in the image below:

![image](https://user-images.githubusercontent.com/48794877/93206835-5564ad00-f75a-11ea-9cd5-05caaee3a1d4.png)

### Expected Behavior
Expect not having to ignore each line, as in pixi.js 5.1.1 where it was working as intended.
```js
// @ts-ignore
const mesh: PIXI.Mesh = new PIXI.Mesh(geometry, shader);
```

### Current Behavior
Typescript currently throws an error for each PIXI.Mesh constructor when updating from pixi.js 5.1.1 to 5.3.3.
Even simple examples such as [this](https://pixijs.io/examples/#/mesh-and-shaders/triangle.js), will not work as expected in typescript environments.

### Possible Solution
This is most likely caused by a missing constructor overload! Constructor can be seen below, as it appears in pixi.js version 5.3.3:
```js
constructor globalThis.PIXI.Mesh(geometry: PIXI.Geometry, shader: PIXI.MeshMaterial, state?: PIXI.State, drawMode?: number): PIXI.Mesh
```
The shader parameter was in previous versions of pixi given as:

```js
shader: PIXI.MeshMaterial | PIXI.Shader
```

The missing overload can also be seen in the official documentation:
https://pixijs.download/dev/docs/PIXI.Mesh_.html

- **`pixi.js` version**: 5.3.3
- **Browser & Version**: n/a
- **OS & Version**: n/a
- **Running Example**: n/a

**Comment by Mason-Chou** [comment]
@ivanpopelyshev is the intent for `Mesh` to only work with a `MeshMaterial`? I'm not sure on the reasoning why you would want to allow a user to pass in a `Shader` object. 

If the goal is to allow users to run custom programs to render the `Mesh`. One solution would be to create a new constructor in the `MeshMaterial` class and allow users to pass in a `Program`. This should be cleaner and allow the team to manage the extra nuances in `MeshMaterial`.
