### ISSUE TITLE
Calculate bounds at start of render cycle, instead of just transforms

### ISSUE THREAD

**Issue by ShukantPal** [pixijs/pixijs#6894]
Should we recalculate the world bounds of a display object in `Renderer#render`. This would allow libraries to entirely skip bounds calculation inside a render cycle.

https://github.com/pixijs/pixi.js/blob/b7881eb680afd7cad410821dc70027146bef7729/packages/core/src/Renderer.ts#L413

Right now, we only recalculate the transform. If we got this route, we would have to be careful about placing `getBounds` before detaching the display object from its parent.

### Performance

If libraries can be assured that `_bounds.getRectangle()` will be correct, then they won't even have to call `getBounds(true)` (bigger wins).

### Bounds corruption

Currently, calling `getBounds` inside a render() method can **cause corruption of bounds** if the display object being rendered as a parent. It is simple, in fact, because `Renderer#render` **detaches the parent of the object before updating the transforms**. However, calling `getBounds(false)` will cause the transforms to be **recalculated with the parent attached**. Clearly, this will be a major pain point because libraries have to be super-duper careful about always passing `skipUpdate=true` inside a render() method. It can entirely be skipped if they don't even touch recalculation of bounds.

**Comment by ivanpopelyshev** [comment]
`Calculate bounds at start of render cycle`

usually, in my applications, that is done on prerender

**Comment by SukantPal** [comment]
@ivanpopelyshev Yeah, so the point is to make this built-in so all plugins can assume bounds are already calculated.

**Comment by ivanpopelyshev** [comment]
Yes, but then we have a problem: scene with many spine instances without filters => extra time on bounds.

**Comment by ivanpopelyshev** [comment]
Even bunnymark will regress.

**Comment by ivanpopelyshev** [comment]
That's actually a big step forward, because we will be able to optimize interaction that way!

**Comment by muhammadhaseebsohail** [comment]
Hi, can you please send me a sample example of transform pixi sprite.?
