### ISSUE TITLE
Video loop "drops a frame" on firefox browser

### ISSUE THREAD

**Issue by mc-zachbogard** [pixijs/pixijs#6896]
On Firefox, when using a PIXI texture from a video on loop, it looks like a frame drops when the next cycle begins. I'm only seeing this on Firefox. 

The console error is "WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 0 is incomplete: The dimensions of `level_base` are not all positive."

Quick background: I'm creating a chroma key video wrapper - like this one except this is for Three -> https://codepen.io/jhnsnc/pen/qPZvvM

However it does not have that bug on Firefox, so I'm thinking it may be PIXI related.

### Steps to Reproduce

My codepen example: https://codepen.io/zackasaurus/pen/PoNxzYe

### Environment

- **`pixi.js` version**: 5.3.3
- **Browser & Version**: Firefox 80.0.1
- **OS & Version**: _e.g. OSX 10.15.6
- **Running Example**: https://codepen.io/zackasaurus/pen/PoNxzYe

**Comment by SukantPal** [comment]
@mc-zachbogard It would be great if you can file an issue at Firefox as well. This does not seem to be explainable.

**Comment by JustNoon** [comment]
Using a transparent webm results in an additional seemingly related warning.

`WebGL warning: generateMipmap: The texture's base level must be complete.`

I come from a [downstream error](https://gitlab.com/foundrynet/foundryvtt/-/issues/2942).

I have created an [upstream report as well.](https://bugzilla.mozilla.org/show_bug.cgi?id=1675866)
