### ISSUE TITLE
PIXI.Text textBaseline behaviour doesnt match canvas behaviour

### ISSUE THREAD

**Issue by dontwork** [pixijs/pixijs#6899]
I expect the textBaseline values that can be used in PIXI.Text styles should match the behaviour of those values in other applications (canvas)

### Current Behavior
textBaseline in PIXI seems to behave very differently to in canvas

### Possible Solution
Not sure

### Steps to Reproduce

Heres a demo https://codepen.io/olll/pen/dyMQVbb

The demo contains a pure canvas implementation of some simple text and then next to it is the same exact spec text in PIXI

### Environment

- **`pixi.js` version**: 5.3.3
- **Browser & Version**: Chrome
- **OS & Version**:  Windows
- **Running Example**: https://codepen.io/olll/pen/dyMQVbb

**Comment by dontwork** [comment]
@SukantPal I think this is a bug rather than a feature request

**Comment by bigtimebuddy** [comment]
The reason for the discrepancy between canvas and Text is that we render text one glyph at a time, for the most part. Text does some special layout stuff. Anyways, these things should probably be consistent, but for historical reason it's not. This fix would be a breaking change but still worth improving.
