### ISSUE TITLE
hitArea on masked Sprite and cached as bitmap

### ISSUE THREAD

**Issue by gsdev01** [pixijs/pixijs#6917]
Hi everyone,

In a project I’m using interactive Sprites, Masks and CacheAsBitmap (for performance reasons).
I have an image as Sprite, this sprite is masked with a Graphics to get only a part of that sprite and rounded corners and the Sprite result is cached as bitmap.
The issue is that when not using the cache as bitmap the hit area is matching the masked sprite (mask bounds) but when using the cache as bitmap the hit area is matching the sprite and not the mask.

I tried to had a hitArea on Sprite without any success and hitArea are really hard to debug because they are not visible.

I don’t know if that is the correct behaviour or a kind of bug… 

Hope you can help me

**Comment by ivanpopelyshev** [comment]
Personally, I spent too many hours in cacheAsBitmap and other generateTexture's derivatives. Others too. Honestly, this thing will hang for weeks, if you dont try to get more info by yourself

Here are relevant lines in source code:

https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/TreeSearch.ts#L70

This is what changed for sprite: https://github.com/pixijs/pixi.js/blob/dev/packages/mixin-cache-as-bitmap/src/index.ts#L266 , also updateTransform() doesnt happen for elements inside it while its cached, so some matrices can be wrong
