### ISSUE TITLE
Sprite rotation is lost after applying filter

### ISSUE THREAD

**Issue by matsura** [pixijs/pixijs#6936]
Hello!

When applying a self made gradient filter to a sprite that has rotation applied, the gradient is drawn but it does not follow the rotation of the sprite.

The code which describes the issue is here:

https://github.com/matsura/pixi-issue

While the reproduction is contained here:

http://pixi-issue.surge.sh/test_pixi_basic.html

Here is the original situation:

![image](https://user-images.githubusercontent.com/7030762/95688218-c50a7280-0c08-11eb-85d6-b05966e98fba.png)

When multiplying the color with uSampler I get the following:

![image](https://user-images.githubusercontent.com/7030762/95688237-03a02d00-0c09-11eb-8d2b-15fcfadf0b48.png)

You see that the gradient still does not follow the rotation. I tried clamping, subtracting inputSize.zw which I saw in some filters in pixi-filters but nothing. I am sure the issue is something simple. In general when I apply filters like this the sprite way of rotating, scaling behaves unexpected.

**Comment by ivanpopelyshev** [comment]
relevant thread: https://www.html5gamedevs.com/topic/46269-sprite-loses-rotation-after-applying-filter-to-it/

I asked guys in Slack to help but it looks like no one cares about that kind of issues right now)
