### ISSUE TITLE
Intersection functions for geometric shapes

### ISSUE THREAD

**Issue by miltoncandelero** [pixijs/pixijs#6952]
Back in the day of [Flash and AS3](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/geom/Rectangle.html#intersection()), **Rectangle** had two methods: `intersects()` and `intersection()` that compared one rectangle with another.

I asked on slack if these two methods were missing on `PIXI.Rectangle` by design or simply because nobody added them first and a discussion sprung about if they should be inside the geometric shape, inside a helper class, or not at all to prevent bloating.

on top of rectangle vs rectangle, we could add circle vs rectangle since the math is not too complex, however, the intersection between any two convex shapes can be done with separating axis theorem but I do think that would be too much.

**This is a discussion:**

- do we want this? or is this bloating and beyond the scope of pixijs?
- where should we stop? rectangle vs rectangle? rectangle vs circle? full poly vs poly?
- where do we want this? in the objects? in a helper class/functions?
- what would be the standard? should we copy the old as3 api? should we check how other 2d libs do it? should we create our own?

**Comment by bigtimebuddy** [comment]
This issue has come up a number of times most recently here: #6106. I would suggest you take a look at that and related issues.

I made a suggestion that got a few :hearts:'s but no one has acted on yet. Basically someone should create an optional package (not included in the default bundle) within the project that contains a bunch of these mixins for Math. I worry about this being a little like the junk-drawer for Math, but clearly it would be helpful for doing simple operations like the ones you suggest. 

In summary, this is bloat.

**Comment by ivanpopelyshev** [comment]
Later, we can move some mixins from that package to main if we actually use those functions.
