### ISSUE TITLE
Scaling container causes it's children to "wiggle/shake" if it has AlphaFilter

### ISSUE THREAD

**Issue by IljaDaderko** [pixijs/pixijs#6967]
I will attach gif with example behaviour that I am seeing, but in essence on some screen widths while I'm animating (I use gsap3 with pixi plugin) scale of a parent container I can see it's children "wiggle" / "shake". I've tested on several devices and browsers and can replicate this. You will see in the gif that I am also animatin opacity, this is done using `AlphaFilter`. As soon as I remove this filter and just run scale animation, everything stays solid / crips with no issues. I can also animate just `alpha` of container, however that causes issues mentioned in #4334. Wiggle / shake issue still persists even if I am not animating AlphaFilter i.e. if it is just applied to container.

### Expected Behavior
Should scale without shake / wiggle despite different screen dimensions, if I am correct?

### Current Behavior
![Screen Recording 2020-10-27 at 22 45 12](https://user-images.githubusercontent.com/3154053/97360046-5256f380-18a6-11eb-9a2e-00c3fe3aaf07.gif)

### Possible Solution
Not sure

### Steps to Reproduce
I wanted to check if this is a known behaviour first, if not I'll make a codesandbox to reproduce

### Environment
- **`pixi.js` version**: 5.3.3
- **Browser & Version**: Chrome 86.0.4240.111, Safari 14.0
- **OS & Version**: macOS Catalina 10.15.6
- **Running Example**: -

**Comment by IljaDaderko** [comment]
Not sure if related, but container who's scale is being animated is also having its AlphaFilter animated at the same time

**Comment by IljaDaderko** [comment]
So, what's interesting is that if I set `PIXI.settings.FILTER_RESOLUTION` to be 2x larger than than my `PIXI.Application` resolution, it kind of looks ok, but I assume there is performance hit here?

**Comment by bigtimebuddy** [comment]
I think this is a duplicate: #3742

**Comment by IljaDaderko** [comment]
Sounds like it, however I applied high precision and am still seeing this issue, perhaps some of my other options are causing it?

```ts
const { devicePixelRatio, innerWidth, innerHeight } = window;

PIXI.settings.PRECISION_FRAGMENT = PIXI.PRECISION.HIGH;
PIXI.settings.FILTER_RESOLUTION = devicePixelRatio;

const app = new PIXI.Application({
  resolution: devicePixelRatio,
  autoDensity: true,
  width: innerWidth,
  height: innerHeight,
  view: document.getElementById('app-canvas'),
  transparent: true,
  antialias: false
});
```

**Comment by IljaDaderko** [comment]
Was digging deeper into this now, it seems that (at least in my case) this wiggle only happens when my `FILTER_RESOLUTION` setting is set to non-even number, so in my case it was 3 on iphoneX, but once I set it to 2, 4, 6 it works fine. Hence why that fix I mentioned above worked. Any ideas?

**Comment by ivanpopelyshev** [comment]
Make me a minimal demo , and i'll fix it. We changed something of filters/renderTexture/resolution code in 5.3 , so it can be something wrong with it.

Alternative: try pixi 5.1 and 5.2, check if it persists

**Comment by IljaDaderko** [comment]
I can't replicate this issue in codesandbox, have made few different attempts, but it seems to work correctly there. Switching my project back to 5.2 did fix this issue however. I also had to remove bitmap fonts and replace them with text for this (not sure if bitmapfonts are related to the issue, but might be something there as well).

**Comment by bigtimebuddy** [comment]
Which specific version was this issue introduced?
