### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<' and (index):10 Uncaught ReferenceError: PIXI is not defined

### ISSUE THREAD

**Issue by ichabodphage** [pixijs/pixijs#6969]
i tried installing pixi.js, but to no avail can i seem to get the setup to work
```html
<html>
<head>
    <title>game</title>
</head>
<script src="./pixi.min.js"></script>
<body>
    <script type="text/javascript">
    let type = "WebGL"
    if(!PIXI.utils.isWebGLSupported()){
      type = "canvas"
    }

    PIXI.utils.sayHello(type)
  </script>
</body>
</html>
```
here is the code i am using, i have no clue why it does not work, pixi.min.js is in the same file, and i am properly running the file using the http module for node.js

yes i have properly downloaded pixi.min.js as a js file and not an HTML file
![image](https://user-images.githubusercontent.com/40300103/97491790-a73f4c00-1930-11eb-95fe-c6d5e4e569d3.png)
****
here is the image of the folder i am working in, beginGame.js looks like this
```js
var http = require('http');
var fs = require('fs');

const PORT=8080; 

fs.readFile('./index.html', function (err, html) {

    if (err) throw err;    

    http.createServer(function(request, response) {  
        response.writeHeader(200, {"Content-Type": "text/html"});  
        response.write(html);  
        response.end();  
    }).listen(PORT);
});
```

**Comment by bigtimebuddy** [comment]
All this looks good except for your serving solution. I would suggest using a simple tool like this: [`http-server`](https://www.npmjs.com/package/http-server). To install:
```
npm install --global http-server
```
Then run this from the command-line within your folder.
```
http-server . -o
```
This will allow you to run your HTML file for a url like this: http://127.0.0.1:8080/

Good luck!

**Comment by ivanpopelyshev** [comment]
Those problems are easy to debug if you open `network` tab in devtoos and see what exactly was downloaded instead of pixi.min.js

**Comment by Ayfri** [comment]
@ichabodphage Do you still have the error?
