### ISSUE TITLE
Invalid bounding box

### ISSUE THREAD

**Issue by animanathome** [pixijs/pixijs#6974]
<img width="1072" alt="Screen Shot 2020-11-02 at 1 16 04 PM" src="https://user-images.githubusercontent.com/2272141/97920008-9d8d5e00-1d0d-11eb-8401-0978f32b6aac.png">

### Expected Behavior
I would expect `graph.drawRect(100, 0, -100, 100)` would generate the following bounding box: {x: 0, y: 0, width: 100, height: 100}. 

### Current Behavior
It returns a bounding box of {x: 0, y: 0, width: 0, height: 0};

### Possible Solution
Not sure

### Steps to Reproduce
Copy paste the following code in pixiplayground:

```
// Create our application instance
var app = new PIXI.Application({
    width: window.innerWidth,
    height: window.innerHeight,
    backgroundColor: 0x2c3e50
});
document.body.appendChild(app.view);

// Load the bunny texture
app.loader.add('bunny', 'https://pixijs.io/examples/examples/assets/bunny.png')
    .load(startup);

function startup()
{
    const graph = new PIXI.Graphics();
    app.stage.addChild(graph);

    graph.beginFill(16777215)
    graph.drawRect(100, 0, -100, 100);
    graph.endFill();
    console.log('bounds:', graph.getBounds());
}
```

### Environment

- **`pixi.js` version**: _e.g. 5.3.0_
- **Browser & Version**: _e.g. Chrome 86.0.4240.111_
- **OS & Version**: _e.g. OSX_

**Comment by bigtimebuddy** [comment]
I believe that width and height does not allow for negative values. Will result in unexpected results, like you're finding.

**Comment by animanathome** [comment]
It does give me the expected visual result @bigtimebuddy. It's only the bounds that are wrong so the behaviour isn't consistent. From what I gather you're think `drawRect` shouldn't allow a negative width value?

**Comment by eXponenta** [comment]
This can't be solved right for every combination of shapes.
Bounds not runs tesselation by performance reason and can't compile a rendered results of invalid payloads.
Plz, not use a negate width/radius etc.

**Comment by bigtimebuddy** [comment]
Similar to #6748

**Comment by SukantPal** [comment]
@animanathome The behavior is _undefined_ for negative values of width and height. PixiJS can't guarantee consistency for undefined behavior.

**Comment by animanathome** [comment]
Thanks everyone, I'll work around it. It would be a good idea to either assert values smaller than 0 for `width` and `height` or to specify their expectations in the documentation.

**Comment by SukantPal** [comment]
The debug builds might have these assertions in the future 👍, right @bigtimebuddy?

**Comment by ShukantPal** [comment]
We have debug builds now, right @bigtimebuddy?

**Comment by bigtimebuddy** [comment]
Yes, we could add asserts for things like these. Those should get removed in the production build
