### ISSUE TITLE
Supporting semver or participating in semver enhancement

### ISSUE THREAD

**Issue by flashist** [pixijs/pixijs#6981]
Hi all,

I was wondering if pixi.js doesn't follow semver intentionally or it was just a coincidence that if we compare 4.x. and 4.8.8 versions, there would be some major breaking changes in this diff. Actually, if we compare 4.5.x, 4.6.x, 4.7.x, 4.8.0 with 4.8.8 there still would be major breaking changes in these diffs too:

https://github.com/pixijs/pixi.js/compare/v4.8.0...v4.8.8

The reason behind that, as far as I understand it, that it was decided to keep the 1st number of the pixi.js module to indicate MAJOR releases of the engine, which are not connected to semver at all (e.g. transition from the 4.x to 5.x version is a clear indication that the engine moved to another level, that under the hood it's different (e.g. performance improvements, major architecture changes, e.t.c).

Am I right?

1) If I am right, would the pixi.js team consider the idea of adding another 4th number to semver as a good idea? In this case the team could've used it as an indication of major engine releases, while still using the other x.x.x numbers as semver suggests it.

If this idea looks good, it be would awesome if somebody from the team would participate in the discussion here: https://github.com/npm/rfcs/discussions/271

2) If I am not right and the team actually tries to follow semver, why 4.x and 4.8.8 versions have so many breaking changes between them without increasing the 1st number of the semver version?

Thanks!

**Comment by bigtimebuddy** [comment]
The short answer is that we try to be as diligent as possible to adhere to semver. If there are breaking changes, they are usually unintentional. 

Pixi is an aging codebase which is difficult to maintain and has a large API surface and a small core team. In v4 we did a bunch of major overhauls like upgrade to ES6. We do our best to define the public API, but it can be a gray area especially when 3rd party plugins might be using non-public stuff. Makes the ecosystem brittle. I've been working with plugin developers to created more paved roads for their plugins.

I'm not trying to make excuses, but building stability is hard. We don't have people that are willing to make more robust test infrastructure that could prevent some of the unintentional breakages. This might include doing golden image comparisons, smoke tests, cross-browser testing and performance regression testing. All of this requires help. Anyone passionate about this areas? We need you.

Last point I'll add: in the future I would like to create more major releases, more frequently. This v4, v5 is to stifling to progress. In the past I've sometimes allowed breaking changes that were clearly incorrectly implemented features years ago. Technically these are fixes, but they break behavior. I have changed my attitude around these set of issues as now requiring a major bump.

All that said, I believe we are getting better in many ways. Moving to TypeScript has been a huge effort but will make sure the boundary of public and private API is stricter.

**Comment by flashist** [comment]
@bigtimebuddy , what do you think about the idea of having a way to mention the release number/id in package?

For example: would it be useful for the pixi.js team to have a chance to separate v4 and v5 releases under the single "pixi.js" package, smth like:

```
{
  release: 5
  version: "0.1.2"
}
```

The idea is to have a way to keep using semver under different releases.

**Comment by bigtimebuddy** [comment]
How is that any different from peerDependencies? Plugins should be doing this if they aren't  already.

**Comment by flashist** [comment]
I'm not sure that I understand your question. The idea behind release/generation number is that it would be possible to increase the MAJOR part of the semver version as many times as it's needed, without changing the GENERATION part of the project.

So we could've had the situation when the **pixi.js** package with generation **4** has semver version **23.15.1**.

It would've made it clear that we're still working with the **pixi.js** pacakge generation **4** (not 5, not 6), and there are no fundamental changes in it, but there are some breaking changes (doesn't matter whether the breaking changes are caused by the code inside of the pixi.js itself, or by increasing major versions of dependencies).

Npm contributors shared with me a link to discussion under the semver project, where it's explained pretty good: https://github.com/semver/semver/issues/213

**Comment by bigtimebuddy** [comment]
What you're suggesting is not a standard convention. If there's an example of this being used on a mainstream JS project, I'd  consider it. But so much of the ecosystem uses semver, so it not a great idea IMO to use another versioning spec. And how would this even benefit people if no tooling respects or enforces it? 

Awhile ago @GoodBoyDigital and I were chatting about using code names for large running releases. MacOS, Android and some Linux distros do this. The actual version number is less important for many users and harder to understand. Compatibility is more important. In this world, v4 may have had multiple names, because of how often we changed things.

**Comment by flashist** [comment]
It's not a common standard, so far. I have a small hope that ppl from the semver community found some common ground about it after 6 years of discussion here: https://github.com/semver/semver/issues/213

I don't have good examples from the npm ecosystem (and it looks like that nowadays everything should be in NPM). Oh no, Typescript might be a good example of not following semver (but they have their approaches for versioning: https://github.com/microsoft/TypeScript/issues/14116 )

> And how would this even benefit people if no tooling respects or enforces it?

My idea was not force pixi.js maintainers to use this new format from right now, my idea was that if pixi.js community consider this new approach for indicating different GENERATIONS of the package (e.g. pixi.js v4, pixi.js v6) while having a chance to keep using SEMVER, as a good idea, then the maintainers might participate in the semver discussion there: https://github.com/semver/semver/issues/213

pixi.js is a very popular lib and if maintainers of such lib share their ideas with the semver community it might add more "weight" to support the indication of generations of packages.
