### ISSUE TITLE
[QUESTION] 5.4.0-rc.1 and Canvas rendering

### ISSUE THREAD

**Issue by amoscatelli** [pixijs/pixijs#6997]
![image](https://user-images.githubusercontent.com/16684470/98984571-ac042280-2522-11eb-97e0-c9fecb4c054d.png)

Hi everybody.
I am missing something :
Is canvas rendering removed from pixi.js 5 or not ?
I can't render my pixi.js application inside electron using pixi.js 5.3.3 without hardware acceleration but if I open the examples they actually work in canvas mode and pixi.js 5.4.0-rc.1.

What am I missing ?

EDIT:
Also I can't try 5.4.0-rc.1 with my application since I can't compile ... Cannot find namespace 'GlobalMixins'.

**Comment by themoonrat** [comment]
You need to use pixi legacy package. That has the canvas renderer support

**Comment by amoscatelli** [comment]
Please, give me more information. Why can I see 5.4.0-rc.1 and Canvas in the screenshot ?

**Comment by bigtimebuddy** [comment]
We need more information. Could you please provide a running example that reproduces the issue? Screenshots aren’t particularly useful. Thanks.

**Comment by amoscatelli** [comment]
I am not strictly talking about an issue, I am still investigating.
Maybe I didn't explain good enough but I am confused in the first place.
In Chrome or Electron (Chromium), without hardware acceleration, I can run pixi.js examples I can find here (I can run both v4 and v5 examples): 
https://pixijs.io/examples
As you can see in the screenshot it states the example uses version "5.4.0-rc.1" and it also states it is using Canvas.
How is this possible ?
Also, can pixi.js work with WebGL WITHOUT hardware acceleration ?

![image](https://user-images.githubusercontent.com/16684470/99007468-8daf1e80-2544-11eb-9cf8-c07797d1d906.png)

**Comment by amoscatelli** [comment]
Regarding the second question I found the anwer myself by trial and error.
When you have Hardware acceleration disabled, only software support, I managed to make it work by setting:

PIXI.settings.FAIL_IF_MAJOR_PERFORMANCE_CAVEAT = false

**Comment by themoonrat** [comment]
ps for others seeing this, PIXI.settings.FAIL_IF_MAJOR_PERFORMANCE_CAVEAT is false by default on v6
