### ISSUE TITLE
Rive web runtime

### ISSUE THREAD

**Issue by spassvogel** [pixijs/pixijs#7024]
Hi I was wondering if you ever considered to implement something to play Rive web  runtime in pixijs?

 https://help.rive.app/runtimes/add-runtime

**Comment by bigtimebuddy** [comment]
For these types of platforms, frameworks or 3rd party libraries, unless it's an open spec or de facto standard, it's unlikely we will create a plugin in the main repo. We, however, would gladly support someone who wants to start this project. Similar to the spine plugin for PixiJS, we can create a repo on pixijs organization on GitHub and add any necessary APIs needed to enable clean implementation.

**Comment by spassvogel** [comment]
Okay that's good to know. If I ever find the time I'll look into it.

**Comment by madcrackjack** [comment]
Hi there. I’ve made npm package for integrating Rive into Pixi.js. Available for js and ts. Also wanna make it for pixi-react in the near time.
Link on npm:
[pixi-rive](https://www.npmjs.com/package/pixi-rive)

**Comment by anthonysapp** [comment]
> Hi there. I’ve made npm package for integrating Rive into Pixi.js. Available for js and ts. Also wanna make it for pixi-react in the near time. Link on npm: [pixi-rive](https://www.npmjs.com/package/pixi-rive)

Hi @madcrackjack!
Any plans to port it for Pixi.js V8? I am working on something with V8 and getting a "Uncaught (in promise) RuntimeError: null function or function signature mismatch" in rive.wasm.

Happy to move this discussion elsewhere, too!

**Comment by thegoldenmule** [comment]
@madcrackjack Any plans to open source? Would love to add Pixi 8 support.

**Comment by whizzkidwork** [comment]
How do you get this to work?
I get this error: 
wasm streaming compile failed: TypeError: WebAssembly.instantiate(): Import #0 "a": module is not an object or function

**Comment by whizzkidwork** [comment]
I got it to work! 

I could not get rive + pixi to work at the same time, using vite or parcel..  either pixi would not work correctly, or Rive would not load the WASM file correctly.
Then I found out that Rive also has versions with the wasm included in the javascript..  and that one worked.

So my solution for people who also might run into this problem:

change the import of canvas-advanced  in rive-npm code. and in your package.json file
from
@rive-app/canvas-advanced
to  
@rive-app/canvas-advanced-single

and it worked without a hitch.

**Comment by afrankenstine** [comment]
I have forked the above package and added a repo at [rive-pixi](https://github.com/afrankenstine/rive-pixi) @thegoldenmule 
 @anthonysapp . I hope it is okay @madcrackjack

**Comment by thegoldenmule** [comment]
@afrankenstine Nice! The NPM package does say MIT license -- you might want to include that in the repo.

**Comment by afrankenstine** [comment]
@thegoldenmule Thanks for the heads up, I have added the License.

**Comment by ilyar** [comment]
## [Runtime Format](https://rive.app/community/doc/format/docxcTF9lJxR) `.riv`

> The Rive editor exports your project as a  file for consumption by the Rive runtimes. This is a binary representation of your Artboards, Shapes, Animations, State Machines, etc. This is the file that Rive's runtimes read to display your content in an application, game, website, etc. The format was designed to provide a balance of quick load times, small file sizes, and flexibility with regards to future changes/addition of features.
