### ISSUE TITLE
[Proposal]: Open up Graphics backend and allow custom shapes, add support for multi-contour Path shape

### ISSUE THREAD

**Issue by ShukantPal** [pixijs/pixijs#7037]
When writing @pixi-essentials/svg's &lt;path /&gt; implementation, I had difficulty integrating my custom `Path` shape b/c:

* there is no standard way of defining shape bounds (had to override `GraphicsGeometry#calculateBounds`)
* `Shape` is not an interface, rather a union. I had to force cast `Shape` into `Path` and vice versa.
* The `SHAPES` enum is not exported from @pixi/graphics

We should standardize these "backend" pieces so that `Graphics` can properly be extended.

---

Also, I was thinking of bringing in @pixi-essentials/svg's `Path` shape into `Graphics`. It supports multiple contours, and a fill-rule. Stroking is a bit complicated b/c I have to call `buildLine` on each contour (by overriding `GraphicsGeometry#processLine`).

It uses libtess for tessellation and is much more robust.

---

Unrelated Rant: `Graphics#currentPath` should actually be called `Graphics#currentPoly`. I literally named the path object `currentPath2` in @pixi-essentials/svg haha.

---

You can see the implementation here:

* https://github.com/SukantPal/pixi-essentials/blob/master/packages/svg/src/utils/Path.ts
* https://github.com/SukantPal/pixi-essentials/blob/master/packages/svg/src/utils/buildPath.ts

**Comment by SukantPal** [comment]
@bigtimebuddy @ivanpopelyshev Thoughts?

**Comment by bigtimebuddy** [comment]
This is a little unclear what you're asking, there are a few ideas in here I don't understand the full scope of all of them. However, I don't have any problem with adjusting those backend/typing pieces you point out, like making a Shape interface, etc. Those seem pretty basic. 

As for your other ideas (adding Path, etc), I ask that you make small PRs so we can consider those things separately.

**Comment by ivanpopelyshev** [comment]
Thoughts: yeah, we have to do it, but what I recommend is to make another Graphics element. More advanced, more optimized. Dont touch what we have right now.

**Comment by ivanpopelyshev** [comment]
Then swap Graphics and new implementation in major version, like we did with Mesh in v5.

**Comment by SukantPal** [comment]
@ivanpopelyshev I disagree, because we won't be changing anything with the `Graphics` code. The user can draw paths using the existing `drawShape` API. `GraphicsGeometry` will process the paths contours in a loop. See my @pixi-essentials/svg/src/SVGGraphicsGeometry code.
