### ISSUE TITLE
Incorrect framebuffer viewport caused by rounding errors

### ISSUE THREAD

**Issue by dev7355608** [pixijs/pixijs#7038]
This was uncovered after the fix in #7036 was applied. This issue occurs only if the resolution is not 1.

![image](https://user-images.githubusercontent.com/31905376/100557786-83628380-32ab-11eb-9753-da2bd6862dba.png)

The effect gets worse as more filters are applied (something like 0.5-1.0 pixels per active filter).

### Environment

- **`pixi.js` version**: 5.3.3+
- **Browser & Version**: Chrome 87, Firefox 83
- **OS & Version**: Windows 10
- **Running Example**: https://www.pixiplayground.com/#/edit/4rHbrZxn1pnIv7CYFV47d

**Comment by SukantPal** [comment]
<img width="720" alt="Screen Shot 2020-12-23 at 1 01 20 PM" src="https://user-images.githubusercontent.com/22450567/103025016-f663c080-451e-11eb-89aa-3aa475842196.png">

Your playground looks fine here (`devicePixelRatio = 2`)

**Comment by dev7355608** [comment]
@SukantPal Powers of two seems to work in this example, but other resolutions don't.
