### ISSUE TITLE
ROUND_PIXELS issues

### ISSUE THREAD

**Issue by dev7355608** [pixijs/pixijs#7049]
1. Incorrect rounding to grid in `Mesh.calculateVertices()`/`Sprite.calculateVertices()`.
https://github.com/pixijs/pixi.js/blob/8b9845ba423c7ea51efed0d81ae24e332568f400/packages/mesh/src/Mesh.ts#L404
https://github.com/pixijs/pixi.js/blob/8b9845ba423c7ea51efed0d81ae24e332568f400/packages/sprite/src/Sprite.ts#L342
It should be: `vertexData[i] = Math.round(vertexData[i] * resolution) / resolution;`

2. The documentation of `settings.ROUND_PIXELS` isn't quite correct. It says `Math.floor`, but `Math.round` is used everywhere.
https://github.com/pixijs/pixi.js/blob/8b9845ba423c7ea51efed0d81ae24e332568f400/packages/settings/src/settings.ts#L265-L276

3. Is rounding missing in `Mesh._renderDefault()`?

4. Is rounding missing in `Sprite.calculateTrimmedVertices()`?

5. Only `Mesh`, `Sprite`, and `BitmapText` seem to be affected by `ROUND_PIXELS`. Is that intended?

6. Another unrelated thing I just noticed: Is the type of `shader` in `Mesh` `MeshMaterial` or `Shader | MeshMaterial`?
https://github.com/pixijs/pixi.js/blob/8b9845ba423c7ea51efed0d81ae24e332568f400/packages/mesh/src/Mesh.ts#L58-L65
https://github.com/pixijs/pixi.js/blob/8b9845ba423c7ea51efed0d81ae24e332568f400/packages/mesh/src/Mesh.ts#L80-L85

**Comment by ivanpopelyshev** [comment]
Oh , why is it `|0` inside my round? mnust be a bug.

Yes, we dont have implemenation for graphics rounding in v5, we had it in v4.

Shader|MeshMaterial stuff is our bane, we cant figure out what to do with it :)

**Comment by ivanpopelyshev** [comment]
I sent invite to pixijs slack on your email. Lets have a talk :)
