### ISSUE TITLE
textures not getting resized

### ISSUE THREAD

**Issue by edev2020** [pixijs/pixijs#7060]
I am trying to resize the new texture for dragonbones slot but the texture still shows in default size for dragonbones while if i add it in the stage it shows with the new scaling set by me.

My code: (PixiJS 5.4.0-rc.3)

```
var new_texture = new PIXI.Sprite(resources.cloth.texture); 

new_texture.scale.x = 0.1;
new_texture.scale.y = 0.1;
		  
new_texture.pivot.x = new_texture.width * 0.5;
new_texture.pivot.y = new_texture.height * 0.5;  
		
slot.display = new_texture; 
```

I tried using new PIXI.Texture also and set the width/height directly at its option parameters but still the texture showed the default size in the dragonbones armature.

**Comment by bigtimebuddy** [comment]
Thanks for reporting. Would you please make a reproduction of this issue?

**Comment by edev2020** [comment]
[rep.zip](https://github.com/pixijs/pixi.js/files/5681073/rep.zip)
Hello,

Here is the reproduction.

Regards!

**Comment by ivanpopelyshev** [comment]
> but still the texture showed the default size in the dragonbones armature.

I'm afraid you have to ask the guy who makes dragonbones runtime. Injection of new textures or their sizes into existing models (Spine, DragonBones) is usually not supported by runtimes, and any attempts at hacking require debug. Did you try to go inside dragonbones runtime and debug it?

**Comment by ivanpopelyshev** [comment]
For example, in spine runtime we have special hacking function that was written by our users: https://github.com/pixijs/pixi-spine/blob/master/examples/hack_texture.md , its a product of many attempts. And you are asking same from dragonbones runtime which is supported not good compared to spine.

**Comment by ivanpopelyshev** [comment]
The usual way of doing those things - 1. check if runtime actually has this feature inside. 2. if not, be a hero and add it, providing exqample for future users. Sorry if it sounds rude, but its how those things are get done, usually. You might meet someone who's invested in same feature here or on https://www.html5gamedevs.com/forum/15-pixijs/ 

Right now I cant even find which pixi-dragonbones plugin is used in examples, and our main page for plugins (https://github.com/pixijs/pixi.js/wiki) is missing reference to it.

**Comment by edev2020** [comment]
> The usual way of doing those things - 1. check if runtime actually has this feature inside. 2. if not, be a hero and add it, providing exqample for future users. Sorry if it sounds rude, but its how those things are get done, usually. You might meet someone who's invested in same feature here or on https://www.html5gamedevs.com/forum/15-pixijs/
> 
> Right now I cant even find which pixi-dragonbones plugin is used in examples, and our main page for plugins (https://github.com/pixijs/pixi.js/wiki) is missing reference to it.

Hello,

Thanks for all this information, my knowledge does not reach that far but i will try to do something from inside the dragonbones plugin, its the latest version from their official github.
If i succeed on this i will share it here for sure.

Regards!

**Comment by ivanpopelyshev** [comment]
> its the latest version from their official github.

Can you give me the link please?

**Comment by edev2020** [comment]
Hello,

Looks like i am using this version from pixi dragonbones robot demo: https://pixijs.io/examples/pixi-plugins/pixi-dragonbones.js (I think i replaced the original version some time ago with this because was having some issues with mesh).
This is the official one though: https://github.com/DragonBones/DragonBonesJS/tree/master/Pixi/5.x/out

Regards!

**Comment by ivanpopelyshev** [comment]
Well you can copy official and modify it , and add that example, then someone else will take it as official pixi-dragonbones in our team

**Comment by ivanpopelyshev** [comment]
pixi-spine exists as an offshot of official spine-ts runtime, it has specific features that pixi users asked for, like that texture resize
