### ISSUE TITLE
Failure loading WebGL context on Debian 10 buster + Firefox 83 and Firefox 84 (possibly earlier, too)

### ISSUE THREAD

**Issue by thomasdullien** [pixijs/pixijs#7070]
### Expected Behavior

https://pixijs.io/pixi-filters/tools/demo/ should load in Firefox 84.0 on Debian Linux without problem.

### Current Behavior

https://pixijs.io/pixi-filters/tools/demo/ does not load, and throws an error on the console: 
```
Failed to create WebGL context: failIfMajorPerformanceCaveat: Compositor is not hardware-accelerated. utils.min.js:8:1301
Failed to create WebGL context: failIfMajorPerformanceCaveat: Compositor is not hardware-accelerated. utils.min.js:8:1326
Uncaught Error: WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.
    create core.min.js:8
    yn core.min.js:8
    t app.min.js:8
    e index.js:1
    <anonymous> index.js:1
    <anonymous> index.js:1
core.min.js:8:102141
```

WebGL is functional on other websites, like https://webglsamples.org/aquarium/aquarium.html

### Steps to Reproduce

Visit the above URL with Firefox 84.0 on Debian Linux on a Thinkpad Carbon X1 7th gen.

### Environment

- **`pixi.js` version**: 5
- **Browser & Version**: Firefox 83, Firefox 84
- **OS & Version**: Debian 10 buster

**Comment by themoonrat** [comment]
PIXI.settings.FAIL_IF_MAJOR_PERFORMANCE_CAVEAT = false;
before you attempt to create the renderer

**Comment by thomasdullien** [comment]
Ah :-) thank you! :-)

So if I understand correctly: Somehow Firefox fails to do hardware acceleration, and then Pixi bails out?

**Comment by thomasdullien** [comment]
One other question: Why does Pixi think that WebGL hardware acceleration is not available? The `about:support` page in Firefox shows the following:
![Screenshot from 2020-12-16 14-24-33](https://user-images.githubusercontent.com/4587964/102354181-81d2d400-3faa-11eb-9608-e233fcfa0838.png)

That seems to imply to me that WebGL is working, but Pixi thinks it isn't?

**Comment by SukantPal** [comment]
PixiJS basically asks if there is a performance bottleneck in the WebGL pipeline. In your case, the browser says "yes" and PixiJS terminates rendering initialization. If you turn off `failIfMajorPerformanceCaveat`, PixiJS won't ask for this information and continue initialization as normal.

**Comment by kerbrose** [comment]
could you try
    Go to **about:config**, search for **webgl.disabled**, ensure that its value is false.
    Go to **about:config,** search for **webgl.force-enabled**, set it to true.
    Go to **about:config**, search for **layers.acceleration.force-enabled**, set it to true.
    restart your firefox.
