### ISSUE TITLE
TilingSprite becomes mosaic with large tileTransform.position

### ISSUE THREAD

**Issue by JohnEastWork** [pixijs/pixijs#7104]
### Expected Behavior
TilingSprite displays normally with large tileTransform.posiiton.

### Current Behavior
Using WebglRenderer on Android Chrome, create a TilingSprite  set a large number(like 999999) to `x` or `y`  of its tileTransform.position, the sprite will become mosaic. The larger number, the larger mosaic size.

PC Chrome and IOS Safari works fine.
Also CanvasRenderer works fine on Android Chrome, too.

### Possible Solution
Have no idea.

### Steps to Reproduce
A demo.  Open it on Android Chrome.
https://www.pixiplayground.com/#/edit/EZkyIiE8eDwJTlkGPHuub

### Environment

- **`pixi.js` version**: 5.2.4 (also tested 5.4-rc-3, 5.3.6, 4.8.6)
- **Browser & Version**: Android Chrome 87, Android Chrome 68
- **OS & Version**: _e.g. Android 10,  Android 8.1.0
- **Running Example**: https://www.pixiplayground.com/#/edit/EZkyIiE8eDwJTlkGPHuub

**Comment by ivanpopelyshev** [comment]
Yeah, old issue that teaches people why Shader precision is important, and what is "farlands" (like in minecraft)
Workaround: You have to trim it (%width %height). 
Time to fix it maybe :)

**Comment by JohnEastWork** [comment]
> Yeah, old issue that teaches people why Shader precision is important, and what is "farlands" (like in minecraft)
> Workaround: You have to trim it (%width %height).
> Time to fix it maybe :)

Have considered trimming, but with rotation and scale, it may be a bit complex.
😿  Checked `Farlands` in wiki, it seems that even it's fixed, the problem will still exist, but with a larger limit, am i getting it right?

**Comment by ivanpopelyshev** [comment]
limits of 16-bit floats, 24-bit floats, 32-bit and 64-bit doubles are very different :) If doubles become the problem, then your JS code will have much more problems :)
