### ISSUE TITLE
Pixi should support OffscreenCanvas Web Worker environments and other "headless" environments.

### ISSUE THREAD

**Issue by kevzettler** [pixijs/pixijs#7123]
I'm trying to use Pixi.js in a webworker with the [OffscreenCanvas reference API](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) It fails at runtime with a `window undefined error`. 

![Screen Shot 2021-01-02 at 4 47 58 PM](https://user-images.githubusercontent.com/126209/103473316-087a0600-4d4c-11eb-9d75-10041e219eb6.png)

I am aware of the other Github issues that explain how [Pixi does not want to support Node.js](https://github.com/pixijs/pixi.js/issues/3224) ([etc](https://github.com/pixijs/pixi.js/issues/4771)) environments because the Pixi team feels Pixi is a browser only tool and don't want to write isomorphic code but, WebWorker is a browser enviroment. I even tried to use the recommended `pixi-shim` and it failed expecting a `window` object as well (lol):

![Screen Shot 2021-01-02 at 6 35 48 PM](https://user-images.githubusercontent.com/126209/103473326-25163e00-4d4c-11eb-8bee-2eac06c3c815.png)

`OffscreenCanvas` Web worker environments are a "browser environment" so what are Pixis plan to support this enviroment?

Other WebGL rendering libraries like [Regl](http://regl.party/) support this pattern by [accepting a reference to a WebGL context passed directly to the initialization code](https://github.com/regl-project/regl/blob/gh-pages/API.md#from-a-webgl-context). I am making assumptions here but feels like PIXI could follow that pattern?

**Comment by bigtimebuddy** [comment]
We are currently working a project to create less hacky way to support WebWorkers and Node.js. So this is certainly on our roadmap for 6.1.0. @Zyie is working on this atm.

**Comment by Zyie** [comment]
@kevzettler this #6880 PR was recently merged that should have fixed the references to the `window`. I believe its been released in `v6.0.0-rc` (warning: there are a couple of breaking changes)

I haven't tested this myself yet so you may run into further issues.

**Comment by kevzettler** [comment]
@Zyie I have tried `v6.0.0-rc` and it throws a run time error expecting a `document` reference

```
Uncaught (in promise) ReferenceError: document is not defined
    at createWhiteTexture (core.js:3309)
    at Module../node_modules/@pixi/core/dist/esm/core.js (core.js:3342)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:61)
    at Module../node_modules/@pixi/app/dist/esm/app.js (accessibility.js:588)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:61)
    at Module../node_modules/pixi.js/dist/esm/pixi.js (performance-now.js:36)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:61)
    ```

**Comment by Zyie** [comment]
Ah ok, this should be fixed once I have completed abstracting our DOM calls. I should have a PR up in the next couple of days.


If you have the time it would be great if you could provide a small sample of your use case so that I can test my implementation against it.

**Comment by kevzettler** [comment]
@Zyie find a minimal reproduction repo at https://github.com/kevzettler/pixi-webpack-worker let me know if you have any questions

**Comment by arbaaz** [comment]
Any updates on this?

**Comment by Zyie** [comment]
hey @arbaaz yes progress is still being made, just slower than I would have liked.

I currently have pixi working inside a webworker using `OffscreenCanvas`. Here's a little demo http://worker.goodboydigital.com/test/

I'll be testing node support soon

**Comment by arbaaz** [comment]
It would be great if you could share the demo code. I will run it locally and experiment.

**Comment by kevzettler** [comment]
@Zyie great work. I really appreciated the 'start jank' button lol. Any WIP branch I can point at to try this? I am circling back to the feature set I'd need this for after delaying.

**Comment by kevzettler** [comment]
Looks like this is about to get closed by the stale bot any update @Zyie

**Comment by kevzettler** [comment]
I should mention that the author of `pixi-shim` did some work on a new release that looks like it may now be viable to use in webworkers see the thread at: https://github.com/Prozi/pixi-shim/issues/17

**Comment by mmmoli** [comment]
> hey @arbaaz yes progress is still being made, just slower than I would have liked.
> 
> I currently have pixi working inside a webworker using `OffscreenCanvas`. Here's a little demo http://worker.goodboydigital.com/test/
> 
> I'll be testing node support soon

Please don't go stale. I'm desperate to check out how you've done this.

**Comment by zszq** [comment]
> 嘿@arbaaz是的，仍在取得进展，只是比我希望的要慢。
> 
> 我目前有 pixi 在使用`OffscreenCanvas`. 这是一个小演示http://worker.goodboydigital.com/test/
> 
> 我将很快测试节点支持



> hey @arbaaz yes progress is still being made, just slower than I would have liked.
> 
> I currently have pixi working inside a webworker using `OffscreenCanvas`. Here's a little demo http://worker.goodboydigital.com/test/
> 
> I'll be testing node support soon

Can you share the source code? I really need to refer to the source code to give me a hint.

**Comment by zszq** [comment]
> hey @arbaaz yes progress is still being made, just slower than I would have liked.
> 
> I currently have pixi working inside a webworker using `OffscreenCanvas`. Here's a little demo http://worker.goodboydigital.com/test/
> 
> I'll be testing node support soon

Can you share the source code? I really need to refer to the source code to give me a hint.

**Comment by Lehamber** [comment]
> hey @arbaaz yes progress is still being made, just slower than I would have liked.
> 
> I currently have pixi working inside a webworker using `OffscreenCanvas`. Here's a little demo http://worker.goodboydigital.com/test/
> 
> I'll be testing node support soon

I want to see how you do it.
I introduced the latest version of Pixi into my project and tried to use worker, but saw this error
![image](https://user-images.githubusercontent.com/54530132/156306295-5924d5dc-81a4-464e-b103-e98df60a3809.png)

**Comment by hdemmer** [comment]
@Lehamber The reason you see that error is because Pixi uses the HTML Canvas API to create things like the default white texture. So filling this in to support non-browser environments (and even just workers) may not be as easy.

**Comment by kevzettler** [comment]
@hdemmer I think we're all well aware of that restriction and that is the exact issue this entire thread is about.

**Comment by zszq** [comment]
I think I can give some ideas, it's in my dual-graphics laptop currently slowing down the whole computer when there's a lot of data. However, it is not a big problem on a computer with only a core display. . .
Thanks to @IvanZatravkin for helping me
[https://github.com/zszq/pixi_for_worker](https://github.com/zszq/pixi_for_worker)

**Comment by zszq** [comment]
I think I can give some ideas, it's in my dual-graphics laptop currently slowing down the whole computer when there's a lot of data. However, it is not a big problem on a computer with only a core display. . .
Thanks to @IvanZatravkin for helping me
[https://github.com/zszq/pixi_for_worker](https://github.com/zszq/pixi_for_worker)

**Comment by bigtimebuddy** [comment]
We are still working on this and it's on our roadmap for v6. I created a PR this week #8307 which is a first step to at least import without errors. Node.js rendering is a popular request and we're working to make that happen.

**Comment by SuperSodaSea** [comment]
I made PR #8622, hopefully make things work for OffscreenCanvas and Web Worker.

**Comment by SuperSodaSea** [comment]
And examples on [pixijs.io](https://pixijs.io/):

https://pixijs.io/examples/#/offscreen-canvas/basic.js
https://pixijs.io/examples/#/offscreen-canvas/web-worker.js

I think this issue can be closed now.

**Comment by Nishadide** [comment]
> And examples on [pixijs.io](https://pixijs.io/):
> 
> https://pixijs.io/examples/#/offscreen-canvas/basic.js https://pixijs.io/examples/#/offscreen-canvas/web-worker.js
> 
> I think this issue can be closed now.

hi pixi / webworkers URL is not working
