### ISSUE TITLE
Canvas Issue On ipad Safari Browser

### ISSUE THREAD

**Issue by Daljeetsingh42** [pixijs/pixijs#7125]
Hi Guys

I have used Pixi.js for Game on below links
https://imagineland.wpengine.com/paint-game/

user: demo
password: demodemo

This Game is working on Desktop browser and iPad 11 version all browser, But this Script not supported on IOS latest version 13.
is any way to make it work on iPad 13 as well

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment]
Hi @Daljeetsingh42 thanks for reporting this issue. Your bug is insufficient in describing the issue. Please isolate and provide an example with code that we can inspect. We cannot debug your project for you, but if you can prove that PixiJS is the cause of your problems, we do our best to fix it.
