### ISSUE TITLE
ImageResource load rejection is not specific enough

### ISSUE THREAD

**Issue by ShukantPal** [pixijs/pixijs#7127]
The error thrown by when a `ImageResource` fails to load is as follows:

```
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: null
defaultPrevented: false
eventPhase: 0
isTrusted: true
path: Array(1)
0: img
length: 1
__proto__: Array(0)
returnValue: true
srcElement: null
target: null
timeStamp: 7732.700000000023
type: "error"
```

Should we catch the error in the promise since we already emit `onError`? If not, we should probably reject with a `CustomEvent` with additional details in the `details` property.

**Comment by bigtimebuddy** [comment]
This needs some polish, I agree. Error handling for internal Resource-loaded things is not great. PR welcome to improve this, but we also have a task to refactor Resources. This could be folded into that effort.
