### ISSUE TITLE
iPad trackpad support(hover, click, etc)

### ISSUE THREAD

**Issue by SIXSIXSIXX** [pixijs/pixijs#7131]
Hi guys,

https://pixijs.io/examples/#/interaction/custom-hitarea.js
While testing my pixi application or others on iPad(with trackpad) safari the "pointerover" and "click" event works perfect with the trackpad at the beginning. However, after I touched the screen using my finger and reused the trackpad to control the scene I noted that the "pointerover" and "click" event is no-longer emitted.
### Expected Behavior
"Pointerover" and "click" event should always be emitted by using trackpad.
### Current Behavior
"Pointerover" and "click" event is not emitted after touching screen.
### Steps to Reproduce
1. Open any pixi application on iPad safari
2. trackpad works well
3. Touch the screen using fingers
4. "Pointerover", "click" event is not emitted.
### Environment
pixi.js : 5.2.1
Browser & Version: Safari (iPad)
OS: IOS14.1

**Comment by bigtimebuddy** [comment]
This seems pretty niche issue to use a trackpad with an iPad, so verifying this is going to be challenging. We are going to need help debugging this one @SIXSIXSIXX. If you can test a version locally and add some console logging to the InteractionManager, it would be helpful if you (or someone) could investigate. Specifically, I'd look to know if the canvas is receiving the DOM events (click). Right now, it's hard to tell if this is Safari/DOM issue or Pixi issue.

**Comment by petem24** [comment]
Any update on this? Have a client who uses an iPad with trackpad and can't interact with anything
