### ISSUE TITLE
setPrecision in Program before naming

### ISSUE THREAD

**Issue by maximgavrilov** [pixijs/pixijs#7138]
It seems that setPrecision must be called before SHADER_NAME apply, because now we have duplicate in vertex shaders with highp precision:

```
precision highp float;
#define SHADER_NAME pixi-shader-4
precision highp float;
```

https://github.com/pixijs/pixi.js/blob/3619fa0f6e872ffca4df4127353a9f554551c750/packages/core/src/shader/Program.ts#L95

**Comment by SukantPal** [comment]
@ivanpopelyshev is working on a better shader preprocessor. I think that'll fix this.

**Comment by ivanpopelyshev** [comment]
Yeah! I'm working on it. Honestly.

**Comment by ShukantPal** [comment]
#7277
