### ISSUE TITLE
Interactions fail in shadow DOM of web component

### ISSUE THREAD

**Issue by soletan** [pixijs/pixijs#7165]
### Expected Behavior

I'd love to use PIXI.js in context of a web component (made with stenciljs) for rendering an interactive map combining PIXI and leaflet. Markers should be clickable and draggable, thus need to have all interaction events working properly. For ease of implementation there should be a sole covering handler per event on stage or some other container for capturing and handling clicks etc.

### Current Behavior

1. Clicks on interactive display objects don't work. 
2. Clicking an interactive stage doesn't even trigger pointerdown events.

### Possible Solution

1. Click on display object: following some investigating I conclude that this is due to [*up-event's target referring to the wrapping component (host element) rather than PIXI's canvas](https://github.com/pixijs/pixi.js/blob/cdfbc8be6cfbd521c00afc69c996cad48d386ed1/packages/interaction/src/InteractionManager.ts#L1348) (a.k.a. interactionDOMElement) ... thus it assumes *up event having occurred outside of its view and thus doesn't click, but considers interaction sort of cancelled.
2. Click on stage isn't recognized at all: haven't investigated this one, but I assume this is kind of intentional, though stage is a PIXI.Container which is a display object as well. (isn't it?)

### Steps to Reproduce

1. Open fiddle at https://jsfiddle.net/soletan/r9kLstd8/40/
2. Click on red box and observe event handlers logging in on-screen console (or failing to do so).
3. Click on black stage and observe console logging again (though there is no logging).

### Environment

- **`pixi.js` version**: 6.0.0-rc.2
- **Browser & Version**: Firefox 84
- **OS & Version**: Windows 10
- **Running Example**: https://jsfiddle.net/soletan/r9kLstd8/40/

**Comment by andrewstart** [comment]
Containers, while display objects, don't innately have a hit area the way a Sprite or something does. Unless you set its `hitArea` property, if you aren't clicking on one of its children then you are just clicking through it. If you do set a `hitArea`, then that will be used for all hit testing and children will not be considered (by design).

I don't know enough about shadow DOMs to help with the other problem, although your investigation sounds correct.

**Comment by soletan** [comment]
Regarding the hitarea: I see.

Regarding component support: using web components is very handy nowadays. In the existing project I had to switch that component to use a fallback method instead of native shadow DOM. As far as I can tell it's having remarkable negative impact on its rendering performance. When using the component events are basically getting through and I assume all it takes is a different information to be evaluated to discover whether pointer has actually left the listening part of PIXI's tree.

**Comment by soletan** [comment]
Fixing this seems to be a new case of providing different solutions for different browsers.

In current Chrome there is a `path` property listing the actual target first:

![grafik](https://user-images.githubusercontent.com/48088/106023316-fb400500-60c6-11eb-89a8-48a575b73ace.png)

In Firefox there is no such parent:

![grafik](https://user-images.githubusercontent.com/48088/106023449-1ad72d80-60c7-11eb-9dbf-1c34e58af18a.png)

In Firefox, there are vendor-specific properties `explicitOriginalTarget` and `originalTarget` both pointing to the `canvas` element which is actually receiving the event anyway.

Using this for further investigation I've stumbled over this [solution for a similar case](https://github.com/facebook/react/pull/12163/files#diff-16617611f1635a69f89908960fab386169656d9315e71dfb4f5669fdc111f8dbR21). Injected console logging in interaction.es.js of pixi 6.0.0-rc.2:

```javascript
        // if the event wasn't targeting our canvas, then consider it to be pointerupoutside
        // in all cases (unless it was a pointercancel)
      console.log(originalEvent.composedPath ? originalEvent.composedPath()[0] : undefined);
        var eventAppend = originalEvent.target !== this.interactionDOMElement ? 'outside' : '';
        for (var i = 0; i < eventLen; i++) {
```

It is logging the canvas in both cases - Firefox and Chrome.

**Comment by pwalczyszyn** [comment]
I'm seeing the same issue, I actually have whole app composed of custom elements and shadow dom, so it is not an option to disable it :( Actually some pointer events work, like: `pointerdown`, `pointermove`, `pointerover`, `pointerout`, `pointerupoutside`. But `click` or `pointerup` doesn't work :(
