### ISSUE TITLE
TilingSprite transform.position act on UV ?

### ISSUE THREAD

**Issue by Bouh** [pixijs/pixijs#7166]
### Expected Behavior
An object using a TilingSprite should not bleeding in movement.

### Current Behavior
An object using TilingSprite are 8px tall, but in movement the first pixels on top move on bottom.
The height of the TilingSprite object stay on 8 so I think the transform position of the object act on UV.
roundPixels true does nothing.

### Possible Solution
Idk

### Steps to Reproduce
https://jsfiddle.net/Bouh/xv7a41ws/3/

### Environment

- **`pixi.js` version**:  5.3.7 & v6.0.0-rc.2
- **Browser & Version**: Chrome & Firefox & Edge
- **OS & Version**: win10
- **Running Example**: https://jsfiddle.net/Bouh/xv7a41ws/3/

**Comment by SukantPal** [comment]
A closer up reproduction is [here](https://jsfiddle.net/ShukantPal/gp5hw8jf/). Setting the height to 7 alleviates the problem so a workaround could to add a 1px padding around the sprite.

**Comment by ivanpopelyshev** [comment]
roundPixels does not affect inner, `tileTransform` , you have to round it up yourself, somehow

Also, the lack of different repeats (U-only or V-only) is the problem.
I honestly dont know which way to fix it right now, you guys have any ideas?

**Comment by Bouh** [comment]
I hope the recent changes on scissors will have an effect for solve this problem.
Or just the rounding PR currently opened.

**Comment by ivanpopelyshev** [comment]
@Oxey405 someone has to add support of repeat wrapmodes separately by axises
