### ISSUE TITLE
TilingSprite Gaps Support

### ISSUE THREAD

**Issue by spd789562** [pixijs/pixijs#7189]
TilingSprite seems doesn't have any option to change the sprites margin.
however, I can use the below code to create a new sprite that seems to have margins
```js
function generateGapTexture(texture, gap) {
  const gapBox = new Pixi.Graphics()
  const originSprite = new Pixi.Sprite(texture)
  gapBox.drawRect(0, 0, originSprite.width + gap.x, originSprite.height + gap.y)
  gapBox.addChild(originSprite)
  return gapBox.generateCanvasTexture()
}
```
but, if gaps are negative, this function is no use.
it should be overlapping like this.
![image](https://user-images.githubusercontent.com/20468917/105274161-93298480-5bd7-11eb-988a-1046bc098276.png)

Is this ok to add this feature?

**Comment by ivanpopelyshev** [comment]
TilingSprite does not consists of multiple sprites. Its using extra transform on texture inside of it.

You can make your own implementation that actually spawns many sprites inside or works with internals separately, that's very good way to make tilingSprite, its just nobody did it as plugin for pixi! I already have 10 plugins, i cant supply more, sorry.

**Comment by SukantPal** [comment]
You can add padding around your textures to add margins. The margins would still be consistent for all the tiles in the TilingSprite.

**Comment by spd789562** [comment]
Thanks, I'll looking how mesh-shader work, and try to make one.

**Comment by imfunniee** [comment]
@spd789562 did you found a solution? 👀
