### ISSUE TITLE
'Unloading' a render texture from the GPU means it cannot be rendered again

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixijs#7201]
### Expected Behavior
Calling 'unload' on a render texture should remove it from GPU memory, but not from RAM, so if the renderer requires it again, it's re-uploaded to the GPU to be used.

### Current Behavior
Calling 'unload' on a render texture will forever more make it unrenderable.

### Steps to Reproduce
Create a sprite, and then a render texture from it using a basic pixi playground example and the 'app' class
Now try to call `app.renderer.textureGC.unload(app.stage);` to remove all textures from the GPU memory. This works... but then of course the loaded texture is re-uploaded to the GPU as it needs to be rendered next frame. However, the render texture is just outright destroyed and won't ever display again.

### Environment
- **`pixi.js` version**: 5.3.7 and 6.0.0-rc3 (occurs from 5.3.0 onwards)
- **Running Example**: https://www.pixiplayground.com/#/edit/Vjq-FFuXoo_rLCw5H1pIR

Started not working after https://github.com/pixijs/pixi.js/pull/6710/files#diff-c08d24f02b18b8fbbd0952b9e22ce1808a264f03e958eb52e9bc48fff9b4631e - but looks like that commit just fixed render textures never getting removed from gpu memory at all

Also goes wrong if you use 'dispose' directly on the base texture - https://www.pixiplayground.com/#/edit/YDdt-kspnsj2U9gemkmZw - whose documentation says 
     * Frees the texture and framebuffer from WebGL memory without destroying this texture object.
     * This means you can still use the texture later which will upload it to GPU
     * memory again.

**Comment by ivanpopelyshev** [comment]
What behaviour will you consider correct in that case?

**Comment by SukantPal** [comment]
@themoonrat Render textures are not stored at all in main memory - that is one of the reasons they cannot be used across WebGL contexts. You will have to extract the render texture's data using `readPixels` (or some other API) and store them in a `BufferResource` to achieve that.

Another way of handling this would be to re-generate the render texture whenever you pull it out of the GPU.

**Comment by themoonrat** [comment]
Hmmm, ok. I guess I mis-understood render textures.

As I posted, the `dispose` docs for render texture state that it CAN be re-uploaded without destroying the texture object. But this does not work. 

Question 1: Is it the docs that are incorrect for `dispose` then?

The overall usage (that I've been doing a long time now, so I guess only seen since upgrading from a 5.2.x to 5.3.x recently) is.... imagine there are 'scenes' within a game. 
When I change from scene a, to scene b, I can do a
`app.renderer.textureGC.unload(oldSceneContainer);`
followed by a
`app.renderer.plugins.prepare.upload( newSceneContainer );`

This has been a really good super simple flow.

Now, the bug fix for destroying render textures on the GPU in the `unload` function has meant there is no easy built in solution. If you call `unload` on a container, and any of it's children have a render texture somewhere, you've lost that forever, unless you can know, at some layer within, to re-create it next time it needs to be rendered. It can be done ,but that's going to be a LOT of faff, especially if a render texture created _could_ be shared across multiple scenes.

Question 2: What if I put a PR to change the signature of the unload function from
`unload(displayObject: IUnloadableTexture): void`
to
`unload(displayObject: IUnloadableTexture, skipGeneratedTextures: boolean): void`

So I can chose to either unload _everything_ from the GPU, or I can chose only to unload textures that exist in RAM, via `app.renderer.textureGC.unload(oldSceneContainer, true);`

Would that be a worthwhile endevour?

**Comment by GoodBoyDigital** [comment]
heya, this actually does look like a bug!

`app.renderer.textureGC.unload(oldSceneContainer, true);` should not not nuke any render textures at all.

textureGC should manages regular image based (re-uploadable) textures only.

**Comment by bigtimebuddy** [comment]
This seems like a pretty significant issue. @GoodBoyDigital do you mind looking into this?

**Comment by themoonrat** [comment]
Looks like I was the one who fixed this last time I noticed this! 4 years back: https://github.com/pixijs/pixi.js/pull/3342
Putting up a PR I think covers this again

**Comment by ShukantPal** [comment]
This seem to gave gotten fixed by #7228
