### ISSUE TITLE
pixijs forcecanvas can't support  globalCompositeOperation?

### ISSUE THREAD

**Issue by a6965921** [pixijs/pixijs#7221]
pixijs forcecanvas can't support  globalCompositeOperation?

https://codepen.io/a6965921/pen/vYyNVXR?editors=1010
this mycode

**Comment by ivanpopelyshev** [comment]
You can manipulate it with blend mode

https://github.com/pixijs/pixi.js/blob/dev/packages/canvas/canvas-renderer/src/utils/mapCanvasBlendModesToPixi.ts#L64

`sprite.blendMode = PIXI.BLEND_MODES.SRC_ATOP`

It will even work with webgl

PixiJS does not try to guess which fields of 2d context were modified by you. If it uses a feature, it takes info from its own objects. Its possible to alter that behaviour, of course, but first - you have to clone the repo , open the sources in IDE and start reading the code of every class you are interested in.
