### ISSUE TITLE
WEBGL_lose_context.restoreContext is used for restoring context

### ISSUE THREAD

**Issue by SmiVan** [pixijs/pixijs#7232]
https://github.com/pixijs/pixi.js/blob/78516ba04f3fb59f4de06bd0dee5a609d9f91c19/packages/core/src/context/ContextSystem.ts#L98-L102

I'm fairly certain that `(WEBGL_lose_context).restoreContext()` is not intended to be used to recover from a general loss of context situation, it rather seems to be intended for recovering from `(WEBGL_lose_context).loseContext()` for debugging purposes.

See [the specification](https://www.khronos.org/registry/webgl/extensions/WEBGL_lose_context/) and [the following discussion on StackOverflow](https://stackoverflow.com/questions/28135551).

This is probably directly related to #7206, where it can be seen that the system can't actually handle real context loss, just a simulated one.

**Comment by SukantPal** [comment]
This does seem to be a bug @GoodBoyDigital

**Comment by bigtimebuddy** [comment]
I think our context loss/restore really needs some help.

**Comment by SmiVan** [comment]
This remains an issue in the current master branch, it should not be closed.

**Comment by SupremeTechnopriest** [comment]
I too can confirm that the WebGL renderer doesn't render anything.  I had to switch to pixi.js-legacy and force canvas to get anything to render.  PIXI inspector shows the objects are there, but they aren't being rendered.

**Comment by rj3d** [comment]
Still an issue in master branch and should not be closed.

**Comment by naiteluo** [comment]
Any progress about this? Just want to know the proper way to handle context lost situation, otherwise than recreating the whole applicaiton instances.

**Comment by bigtimebuddy** [comment]
I'm going to put a bounty on this if someone wants to take a stab at working on this.

**Comment by ShukantPal** [comment]
<img width="1219" alt="Screen Shot 2022-04-02 at 1 35 32 PM" src="https://user-images.githubusercontent.com/22450567/161394600-0de51308-050a-40c5-99e6-d726e36f38fe.png">

I think the right solution here is for PixiJS to clear all of its internal state and wait for the `webglcontextrestored` event? wdyt @bigtimebuddy

**Comment by ShukantPal** [comment]
@bigtimebuddy @Altimor has asked for the bounty to be raised to $500 on behalf of @teamflowhq − how can we pay for this bounty?

**Comment by bigtimebuddy** [comment]
Please see https://github.com/pixijs/pixijs/wiki/Bounties for details. Basically, a donation to our Open Collective to cover the bounty. I'll remove the current bounty amount.

**Comment by ShukantPal** [comment]
Thanks @bigtimebuddy. Please see contribution #571998 in the OpenCollective for a bounty of $250!

**Comment by RoboVij** [comment]
Is it fixed? If yes, is it available only on the latest version and we need to upgrade or is it also available on v5 (we're using 5.3.11)? Because there are some breaking changes while migrating and I'm not familiar with pixi. A previous developer did all the coding.

**Comment by bigtimebuddy** [comment]
This bounty has not been claimed or fixed yet.

**Comment by RoboVij** [comment]
Ok. Our website has several menu tabs. Two of them use the pixi based component. When switching to normal tabs from pixi-using tab, it's all fine. But when we switch back to pixi-using tab the crash and context loss happens. Is there a way to destroy the context when leaving the pixi-using tab so that when we come back it doesn't crash? Or is it not possible and that's what this issue is referring to?
