### ISSUE TITLE
pointerdown event delivered to a wrong PIXI.Container object / test case attached

### ISSUE THREAD

**Issue by afarber** [pixijs/pixijs#7233]
Hello,

in the attached simple test case I have a class called Tile which extends PIXI.Container and is instantiated 3 times and stored in the variables: r, g and b.

First I drag the 3 tiles around, horizontally (i.e. I keep the tiles in the 4th row):

![issue1](https://user-images.githubusercontent.com/1884458/107123556-6b584300-689e-11eb-830a-0fce2b68e104.png)

And after some time, when I click the middle tile, then wrongly the onDragStart method of the left tile is called:

![issue2](https://user-images.githubusercontent.com/1884458/107123567-7e6b1300-689e-11eb-9ce4-b62ee19e6f28.png)

So the pointerdown event is called on the wrong object!

I have a feeling that the root cause for this is that the Tile objects are scaled up when clicked and thus Pixi.js thinks that it should deliver the event to the still big object.

But I haven't been able to come up with a fix or a workaround yet.

The bug is always reproducible for me, please just move the tiles around 5-10 times and you will be able to see it:

[pixi-drag-start-bug.zip](https://github.com/pixijs/pixi.js/files/5937167/pixi-drag-start-bug.zip)

- **`pixi.js` version**:  5.3.7
- **Browser & Version**: Edge 88.0.705.56
- **OS & Version**: Windows 10
- **Running Example**: https://stackoverflow.com/q/66078935/165071

Thanks
Alex

**Comment by afarber** [comment]
Things I have tried sofar, which haven't helped:

- Switching Tile base class from PIXI.Container to PIXI.Sprite
- Moving startDragging and stopDragging calls before removeChild and addChild(At)
- Removing removeChild and addChild(At) calls completely
- Removing this.scale.x = 1.6 and this.scale.y = 1.6

To me it looks like a Pixi.js bug, delivering pointerdown event to a wrong DisplayObject

**Comment by afarber** [comment]
Solved my problem by adding the line

        this.hitArea = new PIXI.Rectangle(0, 0, Tile.W, Tile.W);

**Comment by bigtimebuddy** [comment]
That is likely the correct approach here. Because you are scaling and moving the Tile on dragging, having a stable hitArea is a good idea to avoid weird pointer dragging behavior.
