### ISSUE TITLE
Vertex coordinate inconsistency between Filters and SimplePlane/PlaneGeometry 

### ISSUE THREAD

**Issue by nicknack23** [pixijs/pixijs#7239]
### The problem

When you create a geometry using PlaneGeometry (or SimplePlane which calls PlaneGeometry), the constructor also populates the `aVertexPosition` and `aTextureCoord` attributes. As far as I can tell, these attributes are only documented in the context of Filters (e.g. [here](https://pixijs.download/dev/docs/PIXI.Filter.html) or [here](https://github.com/pixijs/pixi.js/wiki/v5-Creating-filters)), where `aVertexPosition` means normalized filter coordinates. However, the `aVertexPosition` values generated by PlaneGeometry use (unnormalized) texture coordinates.

I understand (at least I do now) that shader attributes and uniforms mean whatever you want them to mean, but this inconsistency is unexpected and makes learning shader programming with Pixi unnecessarily difficult for beginners. I just spent 6 hours trying to debug a simple 15-line vertex shader despite putting effort into reading the documentation and getting the coordinates right. This happened because I combined shader code examples from Filters with geometry from SimplePlane... 😰

### Example

```
const geometry = new PIXI.PlaneGeometry(100,100,10,10);
const vertexBuffer = geometry.getBuffer('aVertexPosition');
console.log(vertexBuffer.data.slice(0,19))   # expect normalized coordinates in range 0-1

# Output:
# Float32Array(19) [0, 0, 11.11111068725586, 0, 22.22222137451172, 0, 33.33333206176758, 0, 44.44444274902344, 0, 55.55555725097656, 0, 66.66666412353516, 0, 77.77777862548828, 0, 88.88888549804688, 0, 100]
```

### Possible Solutions

* normalize the coordinates generated by PlaneGeometry 
* change the name of the `aVertexPosition` attribute in either the default shader or the Filter shaders, so that the same name doesn't mean different things
* specify the coordinate system in the documentation

### Environment

- **`pixi.js` version**:  4.7.x, 5.x.x and 6.0.0-rc2
- **Browser & Version**:  Chrome & Firefox
- **OS & Version**:  Windows 10

**Comment by SukantPal** [comment]
@nicknack23 So for filters, the `outputFrame` uniform gives the actual frame and the unnormalized vertices are calculated using it and `aVertexPosition`.

I agree we can improve the docs here.

**Comment by nicknack23** [comment]
No, that's not the issue. Filters already have plenty of docs (I linked two good overviews above). The problem is that PlaneGeometry and SimplePlane have no documentation, and the documentation for Filters doesn't apply since its coordinate system conventions are different from those in PlaneGeometry and SimplePlane.

**Comment by SukantPal** [comment]
I never said filter docs specifically lol. Nevertheless, agree
