### ISSUE TITLE
BitmapText textWidth incorrectly calculated.

### ISSUE THREAD

**Issue by alexbown** [pixijs/pixijs#7245]
### Expected Behavior
Text width should include the full width of the final character in a given line.

### Current Behavior
Only the xAdvance of characters is being considered when calculating textWidth.

### Possible Solution
In PIXI.BitmapText#updateText during the textLength loop when incrementing pos.x and it is the final character in the line it should be incremented by charData.texture.width instead of charData.xAdvance.

### Steps to Reproduce
Create a bitmap font where the characters have an xAdvance that is smaller than the width, draw a line or shape at the position of the text plus the textWidth, notice characters are partially overlapping with the line/shape.

### Environment
- **`pixi.js` version**: tested in 5.3.3 and 6.0.0-rc.2
- **Browser & Version**: Chrome 88.0.4324.150
- **OS & Version**: Windows 10 Pro - Version 10.0.19042 Build 19042
- **Running Example**: https://pixijs.io/examples/#/text/bitmap-text.js go to the example and use the following code
```
const app = new PIXI.Application({ backgroundColor: 0x1099bb });
document.body.appendChild(app.view);

app.loader
    .add('desyrel', 'examples/assets/bitmap-font/desyrel.xml')
    .load(onAssetsLoaded);

function onAssetsLoaded() {
    const bitmapFontText = new PIXI.BitmapText('T\nY\nq\nb', { fontName: 'Desyrel', align: 'left' });

    bitmapFontText.x = 50;
    bitmapFontText.y = 200;

    app.stage.addChild(bitmapFontText);
  
  const graphics = new PIXI.Graphics();

// Rectangle
graphics.beginFill(0xDE3249);
graphics.drawRect(50 + bitmapFontText.textWidth, 0, 100, 10000);
graphics.endFill();

app.stage.addChild(graphics);
}
```
This changes the example to have a red rectangle positioned at the end of the textWidth, and uses the T, Y, q, and b characters (which all have the same xAdvance, but differing widths) to show how some are overlapped

**Comment by SukantPal** [comment]
This does seem like a bug 👍.

I think we need to adjust the lineWidth here. Basically, subtract the last `xAdvance` and add the last character's width.
 
https://github.com/pixijs/pixi.js/blob/6ea4d4077ffc05e8275bb1993ce77727e99da145/packages/text-bitmap/src/BitmapText.ts#L271

**Comment by alexbown** [comment]
I think it might be better handled around here somewhere as my original situation where i noticed the issue was with single line text - it's hard to center it on a background panel due to the width not matching the visual.
https://github.com/pixijs/pixi.js/blob/6ea4d4077ffc05e8275bb1993ce77727e99da145/packages/text-bitmap/src/BitmapText.ts#L307

Consider the following code on the same example page as linked before
```
const app = new PIXI.Application({ backgroundColor: 0x1099bb });
document.body.appendChild(app.view);

app.loader
    .add('desyrel', 'examples/assets/bitmap-font/desyrel.xml')
    .load(onAssetsLoaded);

function onAssetsLoaded() {
    const bitmapFontText = new PIXI.BitmapText('qbTY', { fontName: 'Desyrel', align: 'left' });

    bitmapFontText.x = 50;
    bitmapFontText.y = 200;
  
  const graphics = new PIXI.Graphics();

// Rectangle
graphics.beginFill(0xDE3249);
graphics.drawRect(50, 200, bitmapFontText.textWidth, bitmapFontText.textHeight);
graphics.endFill();

app.stage.addChild(graphics);
app.stage.addChild(bitmapFontText);
}
```
