### ISSUE TITLE
Breaking changes from PIXI.mesh.Plane to PIXI.SimplePlane

### ISSUE THREAD

**Issue by AlexandreRangel** [pixijs/pixijs#7249]
Dear Pixi friends,

It looks like something has changed when moving from PIXI4 class PIXI.mesh.Plane to PIXI5 class PIXI.SimplePlane that makes it unable to distort some kind of textures. 
I used this Pen from Blake Bowen [https://codepen.io/osublake/pen/8785174690eabaf5ba99f785b9d3b64e](https://codepen.io/osublake/pen/8785174690eabaf5ba99f785b9d3b64e) and I changed it just  enough so it works on PIXI5. And I got it working. The changes are:

**- - - Change 1:**

Original Code (Pixi 4):
`  var grid = new Grid(rows, cols, width, height, beach.vertices);`
    
Changed Code (Pixi 5):
```
  const buffer = beach.geometry.getBuffer('aVertexPosition');
  var grid = new Grid(rows, cols, width, height, buffer.data);
```

**- - - Change 2:**

Original Code (Pixi 4):
```
  var tl = new TimelineMax({ 
    repeat: -1,
    onUpdate: grid.update, 
    callbackScope: grid
  });
```

Changed Code (Pixi 5):
```
  var tl = new TimelineMax({ 
    repeat: -1,
    onUpdate: ()=>{buffer.update();grid.update();}, 
    callbackScope: grid
  });
```

And that was enough to get it working:
[https://codepen.io/is2548-the-selector/pen/JjbWjaG](https://codepen.io/is2548-the-selector/pen/JjbWjaG)

But, I discovered something strange that prevents the example from working. If you change the texture for PIXI.Texture.WHITE, it works on PIXI4, but stops working on PIXI5:

PIXI4(working):
[https://codepen.io/is2548-the-selector/pen/eYBvYbq](https://codepen.io/is2548-the-selector/pen/eYBvYbq)
PIXI5(not working):
[https://codepen.io/is2548-the-selector/pen/JjbWojb](https://codepen.io/is2548-the-selector/pen/JjbWojb)

And this does not happen only with this texture. I found out another texture that SimplePlane can't warp, like this texture:
```
const video = document.createElement("video");
video.src = "path/to/video.mp4"
document.body.appendChild(video);
const texture = Texture.from(video);
```
(although this texture works for distorting a video using PIXI.projection.Sprite2s using proj.mapBilinearSprite)

Any clues about how to fix this? Is it a Pixi bug or an error on my side :) ?

Thank you!
Alexandre Rangel
https://www.alexandrerangel.art.br

**Comment by bigtimebuddy** [comment]
Adding this line it works:

```js
beach.textureUpdated();
```

Example: https://jsfiddle.net/bigtimebuddy/9ngx82Ld/

I think the issue is this check:

https://github.com/pixijs/pixi.js/blob/2a47593194043fa86a601cb4282105fa6c3472cc/packages/mesh-extras/src/SimplePlane.ts#L61-L68

Since, MeshMaterial is _already_ using a default texture of `PIXI.Texture.WHITE`, the texture is not updated. I believe this is a bug.

**Comment by AlexandreRangel** [comment]
Thanks a lot, Matt!!
And congratulation for the awesome Pixi project!

**Comment by AlexandreRangel** [comment]
The `beach.textureUpdated();` line made the example work fine with the WHITE texture, but still doesn't work with a video texture. I will try to make a simplified example to demonstrate it.

**Comment by bigtimebuddy** [comment]
Yes, please provide an example for video.

**Comment by AlexandreRangel** [comment]
The following CodePen demonstrates that, although SimplePlane displays the video just fine, it cannot distort a texture that was created from an HTML video tag.
If you comment line 158 and uncomment line 159, it works with PIXI.Texture.WHITE 

[https://codepen.io/is2548-the-selector/pen/MWboBvO](https://codepen.io/is2548-the-selector/pen/MWboBvO)

**Comment by bigtimebuddy** [comment]
I'm not sure if video + mesh is a bug or undefined behavior. Someone want to weigh-in? @SukantPal @ivanpopelyshev

**Comment by danieldourado** [comment]
> I'm not sure if video + mesh is a bug or undefined behavior. Someone want to weigh-in? @SukantPal @ivanpopelyshev

Hi, @bigtimebuddy . I am a developer working with @AlexandreRangel.
I'd like to add to the discussion that it is possible to distort a Texture created from an html video component using pixi-projection (not using bezier curves, though):
https://github.com/pixijs/pixi-projection

**Comment by AlexandreRangel** [comment]
It shows the same behavior on Pixi 4 (it can distort a white texture ok, but now the HTML video texture):
[https://codepen.io/is2548-the-selector/pen/eYBEvqO](https://codepen.io/is2548-the-selector/pen/eYBEvqO)

**Comment by ivanpopelyshev** [comment]
We can also rename it in filters, so `aVertexPosition` could work only in legacy mode, for v7.

As for SimplePlane, yes, docs are not enough.

**Comment by danieldourado** [comment]
Dear @ivanpopelyshev,
After further investigation we discovered that the problem is probably related to SimplePlane not being able to distort a video texture.
In this pen: https://codepen.io/is2548-the-selector/pen/VwmqaQK?editors=0011
We load a texture and use it to create two components, a PIXI.projection.Sprite2s and a PIXI.SimplePlane. At first, both are able to distort the texture.
If you uncomment line 133, the video texture will be loaded. PIXI.SimplePlane won't be able to distort the texture while PIXI.projection.Sprite2s will.

Is there any undocumented feature for SimplePlane that we could use to make it distort video textures?

Thank you very much!

**Comment by AlexandreRangel** [comment]
Hi @bigtimebuddy and @ivanpopelyshev 
Could you please take a look into this post/pen and help us figure it out?
If it's a bug, I could se a bounty for squashing it :)

> After further investigation we discovered that the problem is probably related to SimplePlane not being able to distort a video texture.
> In this pen: https://codepen.io/is2548-the-selector/pen/VwmqaQK?editors=0011
> We load a texture and use it to create two components, a PIXI.projection.Sprite2s and a PIXI.SimplePlane. At first, both are able to distort the texture.
> If you uncomment **line 133**, the video texture will be loaded. PIXI.SimplePlane won't be able to distort the texture while PIXI.projection.Sprite2s will.
> 
> Is there any undocumented feature for SimplePlane that we could use to make it distort video textures?
> Thank you very much!

**Comment by bigtimebuddy** [comment]
There are two issues in this thread. Video textures not working with Mesh and White textures not working with mesh. I think the latter issue is very solvable. Can you create another issue for the video texture so we can deal with these separately? Happy to add a bounty for the video thing.

**Comment by AlexandreRangel** [comment]
Great @bigtimebuddy !
We'll create the video texture issue and let you know ASAP.
How do the bounties work?

**Comment by bigtimebuddy** [comment]
Bounties are assigned by me. First to merge is awarded the bounty, and PRs are considered in the order which they are submitted. Payouts are done with Open Collective.

**Comment by AlexandreRangel** [comment]
Dear @bigtimebuddy ,

we've created the issue:
[https://github.com/pixijs/pixi.js/issues/7302](https://github.com/pixijs/pixi.js/issues/7302)
