### ISSUE TITLE
Visual Artifact on Odd Height

### ISSUE THREAD

**Issue by RPGillespie6** [pixijs/pixijs#7252]
### Expected Behavior
Grid of sprites rendered the same way regardless of canvas dimensions

### Current Behavior
Some sprites appear off by one pixel if the canvas has an odd height.

Even height (correct):
```
const app = new PIXI.Application({width: 640, height: 480, backgroundColor: 0xff0000, resolution: window.devicePixelRatio || 1,});
```
![image](https://user-images.githubusercontent.com/9853156/108545242-8e7aed80-72b5-11eb-881c-ab7fca37c474.png)

Odd height (incorrect):
```
const app = new PIXI.Application({width: 640, height: 481, backgroundColor: 0xff0000, resolution: window.devicePixelRatio || 1,});
```
![image](https://user-images.githubusercontent.com/9853156/108545266-98045580-72b5-11eb-9915-e06a28c03239.png)

Here you can see the red background is leaking through the grid of sprites because some of the sprites seem to be clipped by a pixel. My gut feeling is that this is some kind of coordinate system floating point rounding error?

### Possible Solution
Currently my workaround is to just make sure the initial height is always an even number. The problem though is that this canvas normally has `resizeTo` set, and if the parent container has an odd height, this problem occurs. What's interesting is that this problem occurs even after resizing to an even height, so long as the initial container was an odd height. If the initial container was an even height, I never see any problems, even when resizing to an odd height. 

### Steps to Reproduce
I will post a comment once I can get a jsfiddle working

### Environment

- **`pixi.js` version**:  5.3.3 and 5.3.7
- **Browser & Version**: latest Chrome, Edge
- **OS & Version**: Windows 10

**Comment by bigtimebuddy** [comment]
Thanks for reporting. Definitely need a fiddle to understand more deeply what's happening.

**Comment by RPGillespie6** [comment]
I've confirmed the artifact is coming from the texture clipping a row of pixels from the next tile down in the sprite sheet. The offending lines that seem to trigger this is:

```
app.stage.position.x = app.screen.width / 2;
app.stage.position.y = app.screen.height / 2;
```
If I instead do:
```
app.stage.position.x = Math.floor(app.screen.width / 2);
app.stage.position.y = Math.floor(app.screen.height / 2);
```

The artifact goes away. Fiddle: https://jsfiddle.net/62vxsjkq/4/

(changing height from 200 to 201) will toggle artifact.

Maybe this is expected behavior when using non-integer coordinates? If so maybe the docs should have a caveat because I lifted the code from here: https://pixijs.io/examples/#/demos-basic/container.js

**Comment by pagoru** [comment]
I have the same "problem" with my project, but, I'ts not.

When you work with pixel perfect , you need to think about so many variables... 
- screen dpi
- browser redimension
- floating point
- textures having odd boundaries
My solution is exactly what you write, "Math.floor", but It's not a problem about pixi.

**Comment by RPGillespie6** [comment]
Understood. It's just counterintuitive to me that a texture created from a base texture using integer dimensions:

```js
let tex = new PIXI.Texture(base_texture, new PIXI.Rectangle(0, 0, 16, 16));
```

Can change or clip into adjacent pixels in the base texture later if `app.stage.position` x or y becomes non-integral.

If you are saying it's not pixi.js's fault, well go ahead and close this issue. But it's still a counterintuitive graphical quirk so I feel like it needs to be addressed someone in the stack, if not WebGL, then a note in the docs or something?

**Comment by vassiliskrikonis** [comment]
I think I'm experiencing a similar problem. If you check [this](https://www.pixiplayground.com/#/edit/sBXBUBasCLsOal9FSVRMA) playground, I'm setting integer positions but you can see pixel bleeding on the edges (white lines), possibly due to scaling.

**Comment by ivanpopelyshev** [comment]
Welcome to OpenGL / WebGL. Its always like that - you position something that its 0.5 pixels or just not an integer, you get artifacts on edges because of bleeding.

Two ways to fight that:
1. prepare your atlas, add padding, maybe using texturePacker
2. make sure that shader you use does account for texture frames. like `@pixi/tilemap` does. I did have shader just for simple sprites but i lost it somewhere in pixi v4.. so you have to do it yourself or do 1

**Comment by vassiliskrikonis** [comment]
> you position something that its 0.5 pixels or just not an integer

Actually, I did come into this issue because in the project I'm working on we *have* to offset some sprites by half a pixel and then stumbled upon similar issues here. 

But in the attached playground link I'm positioning the sprites in a sane manner. What gives? Does this really mean that (unless trying the workarounds you've mentioned) I'll have to make sure *everything* is a whole integer, including possible scaling deep down the scene hierarchy?

**Comment by ivanpopelyshev** [comment]
or use linea filter filtering (scaleMode). As i said, Welcome To OpenGL.
