### ISSUE TITLE
Error when GC tries to destroy  a CubeMap BaseTexture and then when it tries to load the texture to GPU again

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixijs#7272]
### Expected Behavior
No error should occur

### Current Behavior
An error occurs when using a CubeMap resource for a BaseTexture and the GC tries to load/unload it. After the error has occured the texture is in a broken state.

### Steps to Reproduce
The entire app code which causes this error:

```javascript
let app = new PIXI.Application({
  backgroundColor: 0xdddddd, resizeTo: window, antialias: true
})
document.body.appendChild(app.view)

let cubeTexture = PIXI.BaseTexture.from([
  "assets/environments/autumn/diffuse_posx.jpg",
  "assets/environments/autumn/diffuse_negx.jpg",
  "assets/environments/autumn/diffuse_posy.jpg",
  "assets/environments/autumn/diffuse_negy.jpg",
  "assets/environments/autumn/diffuse_posz.jpg",
  "assets/environments/autumn/diffuse_negz.jpg",
])

let fs = `
varying vec2 vTextureCoord;
uniform samplerCube uSamplerCube;
void main() {
  gl_FragColor = textureCube(uSamplerCube, vec3(vTextureCoord.x, vTextureCoord.y, 0.0));
}
`

let sprite = app.stage.addChild(new PIXI.Sprite(PIXI.Texture.WHITE))
sprite.width = 256
sprite.height = 256
sprite.filters = [new PIXI.Filter(null, fs, { uSamplerCube: cubeTexture })]

document.addEventListener("keydown", () => {
  sprite.visible = !sprite.visible
})
```

Press any key to hide the sprite, then wait a couple of minutes until the GC has occured. Then press a button again to make the sprite be visible - then we get the error in v5.3: "WebGL: INVALID_OPERATION: bindTexture: textures can not be used with multiple targets.". In PixiJS v6.0 we instead get error "[.WebGL-0x14782ba00]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips" when the textures tries to load back to the GPU.

### Environment
PixiJS v5.3 and v6.0
Chrome 88
MacOS Big Sur

**Comment by jnsmalm** [comment]
I know this is probably not an issue for most users because they don't use CubeResource, but could anyone point in right direction how this could be fixed?

**Comment by ivanpopelyshev** [comment]
Its a bug , it can be fixed. 

Ways to solve that:
1. find yourself how to fix that , make PR later
2. wait for someone 
3. assign a bounty

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev is right. This isn't super high priority which is probably why this hasn't gotten more traction. I'd say that if you want it fixed, sponsoring a bounty has been useful for other folks to get specific things addressed. Here [more info](https://github.com/pixijs/pixijs/wiki/Bounties#--sponsoring) about how that works.

Obviously, would welcome a PR for a fix. Will reopen this.

**Comment by lunarraid** [comment]
The reason this is happening is that the CubeTexture dirty ids are not being updated on context loss or during GC, so the textures never get re-uploaded. I can take a stab at this, but I don't have proper context on why the dirty ID check is set up the way it is, so that would require some insight.
