### ISSUE TITLE
Video texture not working on Firefox mobile (Android)

### ISSUE THREAD

**Issue by madclem** [pixijs/pixijs#7301]
### Expected Behavior
Video texture should show on Firefox mobile.

### Current Behavior
When using a video texture on Firefox mobile, the video doesn't show (but the sound is playing). 
- Updating manually the baseTexture doesn't work.
- width and height are correct (it gets the correct video dimensions)
- The sound works
- This is not a "user interaction" problem (eg: play video on click)

### Possible Solution
ThreeJS video texture works on Firefox Mobile. After going through some issues there, I found this PR that may be helpful (hopefully)
- https://github.com/mrdoob/three.js/pull/19905#issuecomment-662319844

### Steps to Reproduce
- Open Firefox on Android
- Navigate to https://pixijs.io/examples/#/sprite/video.js (or simply create / use a video texture)
- Tap play button and observe that the video is not showing

### Console error
![screenshot](https://user-images.githubusercontent.com/4436266/111295773-abe87080-8643-11eb-9f94-046fb41d087b.png)

### Environment

- **`pixi.js` version**: _^5.3.7_
- **Browser & Version**: _e.g. Firefox Mobile_
- **OS & Version**: _e.g. Android_
- **Running Example**: _https://pixijs.io/examples/#/sprite/video.js_

**Comment by kokotron** [comment]
This problem also happens with BabylonJS engine. I looked into it some more, you can check Mozilla's own website on WebGL Video Textures on Android Firefox: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example/Video_textures
This doesn't play for me either (video texture appears blue).

So, is it safe to say this is an Android Firefox issue with WebGL?

**Comment by fagerbur** [comment]
@bigtimebuddy What is the upstream bug that this is tied to? Seems like this is broken for everything that uses WebGL video textures...
