### ISSUE TITLE
incorrent value of app.screen.width with resizeTo being set to HTML element in v6.0.0

### ISSUE THREAD

**Issue by TeeTeeHaa** [pixijs/pixijs#7320]
### Expected Behavior

When creating a `PIXI.Application` with the option `resizeTo` being set to an HTML element and that element is being resized then `app.screen.width` (or height) should always have the exact same value as `element.clientWidth` (or height).

### Current Behavior

Using Pixi.js v5.2.4 those values are always exactly the same.
Using Pixi.js v6.0.0 those values **can be different**.

### Possible Solution

`¯\_(ツ)_/¯`

### Steps to Reproduce

1. Copy the example code below in an `index.html` file.
2. Open that file in a browser and optionally open the developer console.
3. Resize the browser window (resize window, maximize/minimize window, open/close developer console).
4. See that the green triangle is **not** always pointing exactly to the bottom right corner. Optionally see output in developer console.
5. Change the script source from Pixi.js v6.0.0 to v5.2.4 and reload.
6. Resize the browser window (resize window, maximize/minimize window, open/close developer console).
4. See that the green triangle is always pointing exactly to the bottom right corner. Optionally see output in developer 

### Environment

- **`pixi.js` version**: _6.0.0_
- **Browser & Version**: _Firefox 86.0.1 (64-bit)_, _Chromium Version 87.0.4280.67 (Developer Build) (64-bit)_
- **OS & Version**: _Windows 7 64 Bit_
- **Running Example**: _https://www.teeteehaa.de/pixijs/resize/_

### Example Code

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" href="index.css" />
    <title>Pixi.js Resize Bug</title>
    <!-- note: bug exists in Pixi.js v6.0.0 but not in v5.2.4 -->
    <script defer src="https://pixijs.download/v6.0.0/pixi.min.js"></script>
    <!-- <script defer src="https://pixijs.download/v5.2.4/pixi.min.js"></script> -->
    <script>

      function start () {

        console.log('start')

        // get target div element to which the Pixi.js app shall resize to
        const divElement = document.getElementById('divelement')
        
        // create Pixi.js app
        // https://pixijs.download/v6.0.0/docs/PIXI.Application.html
        const app = new PIXI.Application({
          resizeTo: divElement,
          width: divElement.clientWidth,
          height: divElement.clientHeight,
          autoDensity: true,
          resolution: window.devicePixelRatio,
          backgroundColor: 0x0000ff
        })
        
        // get the canvas element created by the Pixi.js app and put it into target div element
        const canvasElement = document.body.appendChild(app.view)
        divElement.appendChild(canvasElement)
        
        // create triangle pointing to lower right corner of the Pixi.js app
        const triangle = new PIXI.Graphics()
        triangle.beginFill(0x00FF00)
        triangle.drawPolygon([
          -1, -1,
          -25, -100,
          -100, -25
        ])
        triangle.endFill()
        app.stage.addChild(triangle)
        
        function resize () {
          const isDifferent = (app.screen.width !== divElement.clientWidth || app.screen.height !== divElement.clientHeight)
          console.log('app size %i/%i and target element size %i/%i are %s', app.screen.width, app.screen.height, divElement.clientWidth, divElement.clientHeight, isDifferent ? 'different' : 'same')
          triangle.x = app.screen.width
          triangle.y = app.screen.height
        }
        
        window.addEventListener('resize', resize)
        
        // press any key to call resize function manually
        window.addEventListener('keydown', resize)
        
        // resize once at the beginning
        resize()
      }

      // wait for defered external scripts to be loaded before calling start function
      // http://youmightnotneedjquery.com/#ready
      if (document.readyState !== 'loading') {
        start()
      } else {
        document.addEventListener('DOMContentLoaded', start)
      }

    </script>
    <style>

      html {
        height: 100%; /* use full height */
        background-color: cyan;
      }

      body {
        height: 100%; /* use full height */
        box-sizing: border-box; /* use sane box model */
        margin: 0; /* override default value with sane value */
        overflow: hidden; /* avoid scroll bars, could otherwise appear because of resize */
        background-color: magenta;
      }

      #divelement {
        height: 100%; /* use full height */
        box-sizing: border-box; /* use sane box model */
        background-color: yellow;
      }

    </style>
  </head>
  <body>
    <div id="divelement"></div>
  </body>
</html>
```

**Comment by gburlet** [comment]
I also experience this. When pixi app goes fullscreen mode or window is resized I get a dead bar on the side where pixi doesn't snap to the containing DOM element.

**Comment by TeeTeeHaa** [comment]
Issue still exists in Pixi.js v6.2.0.

**Comment by bigtimebuddy** [comment]
Running example: https://jsfiddle.net/bigtimebuddy/w7fuogpL/

This change was introduced here: #7384 and it appears to be breaking. Before, the values passed to `renderer.resize()` were assumed to also be the values of `screen`.

After change:
```ts
this.view.width = Math.round(desiredScreenWidth * this.resolution);
this.view.height = Math.round(desiredScreenHeight * this.resolution);

const screenWidth = this.view.width / this.resolution;
const screenHeight = this.view.height / this.resolution;

this.screen.width = screenWidth;
this.screen.height = screenHeight;
```

Before change:
```ts
this.screen.width = screenWidth;
this.screen.height = screenHeight;

this.view.width = screenWidth * this.resolution;
this.view.height = screenHeight * this.resolution;
```

@dev7355608 what do you think?

**Comment by dev7355608** [comment]
It's not a bug in the new resize method, but the fact that `resizeTo` is throttled: when the resize event is fired, the app resize is queued with `requestAnimationFrame`; the renderer is not resized immediately. So you need to do `app.renderer.on('resize', resize)` instead of `window.addEventListener('resize', resize)`, otherwise your resize code is executed before the renderer/screen is resized.

https://github.com/pixijs/pixijs/blob/793f21c0d0f2d2a423bd4339f40a569e1ea68711/packages/app/src/ResizePlugin.ts#L53-L72

**Comment by TeeTeeHaa** [comment]
Thank you for spending time with this issue.

If I understand @dev7355608 correctly then this is not a bug of Pixi.js v6 but a change of behavior between v5 and v6. The suggested solution is adapt the user's code. 

In my example I should replace the line...
`window.addEventListener('resize', resize)`
...with...
`app.renderer.on('resize', resize)`

Am I correct? If so then this issue can be closed as "not a bug".

**Comment by bigtimebuddy** [comment]
That is correct @TeeTeeHaa, using the renderer `resize` event is more consistent with timing of dispatched events internally.
