### ISSUE TITLE
v8 deoptimization

### ISSUE THREAD

**Issue by cjsjy123** [pixijs/pixijs#7321]
![image](https://user-images.githubusercontent.com/7793438/111896090-0f164080-8a52-11eb-8a18-1d7a80efe13b.png)

There are always some v8 deoptimizations happening every frame, will it be optimized?

**Comment by SukantPal** [comment]
@cjsjy123 Where'd you get those logs?

**Comment by cjsjy123** [comment]
> @cjsjy123 Where'd you get those logs?

"C:\Program Files\Google\Chrome\Application\chrome.exe" --disable-extensions --js-flags="--trace-deopt --trace-ic --logfile=f:/H5_SSJJ/h5trace/v8.log"  --no-sandbox https://127.0.0.1:8888/ --user-data-dir=F:\H5_SSJJ\h5trace

with jsflags --trace-deopt

**Comment by GoodBoyDigital** [comment]
ooh! interesting! noticed you closed this - is this still a thing @cjsjy123 ?

**Comment by cjsjy123** [comment]
> ooh! interesting! noticed you closed this - is this still a thing @cjsjy123 ?

This problem still exists, but because of the performance waste caused by this de-optimization, I am still not sure how much it is, and it is relatively too special, and I have to consider spider monkey engine, so I plan to make specific comparisons. Reopen it again.
