### ISSUE TITLE
Wrong fill on polygons

### ISSUE THREAD

**Issue by Davabgaryan** [pixijs/pixijs#7325]
### Expected Behavior
The fill of the shape should be only inside the polygon

### Current Behavior
It fills some outside parts of the polygon and leaves the inside part transparent

What it looks like:
<img width="184" alt="Screen Shot 2021-03-22 at 15 26 42" src="https://user-images.githubusercontent.com/2950370/111983014-15282200-8b23-11eb-839a-0966082a26fc.png">

What is should look like:
<img width="156" alt="Screen Shot 2021-03-22 at 15 26 46" src="https://user-images.githubusercontent.com/2950370/111983040-1f4a2080-8b23-11eb-912a-6954006c0c23.png">

Working example:
https://www.pixiplayground.com/#/edit/C1ZDPGKV5WPWaXMR41H0g

**Comment by ivanpopelyshev** [comment]
Switch `earcut` to `tess`. #6800 contains playground you need: https://www.pixiplayground.com/#/edit/RPpVUBLDu-4WMLffkvVWR

**Comment by SukantPal** [comment]
@Davabgaryan Yup, `Graphics` doesn't work well with self-intersecting shapes. @pixi-essentials/svg has more libtess.js-based path tessellation implementation:-

https://github.com/SukantPal/pixi-essentials/blob/master/packages/svg/src/utils/buildPath.ts

**Comment by yazbaryan** [comment]
> Switch `earcut` to `tess`. #6800 contains playground you need: https://www.pixiplayground.com/#/edit/RPpVUBLDu-4WMLffkvVWR

@ivanpopelyshev I'm getting error in `Tess2.tesselate` method, checked `Sweep.topRightRegion` and saw that `req` is null

```
Uncaught TypeError: Cannot read property 'eUp' of undefined
    at Object.Sweep.topRightRegion (tess2.js:1575)
    at Object.Sweep.checkForIntersect (tess2.js:2015)
    at Object.Sweep.walkDirtyRegions (tess2.js:2126)
    at Object.Sweep.addRightEdges (tess2.js:1761)
    at Object.Sweep.sweepEvent (tess2.js:2413)
    at Object.Sweep.computeInterior (tess2.js:2641)
    at Tesselator.tesselate (tess2.js:3405)
    at Object.Tess2.tesselate (tess2.js:57)
    at Object.triangulate (index_pixi.js:133)
    at GraphicsGeometry.processFill (graphics.js:1893)
```

**Comment by avpeery** [comment]
I am using tess2 but it eventually breaks down with very long self intersecting contours. Any other recommendations on tessellation libraries? Can't use earcut because I need holes, sigh
