### ISSUE TITLE
Event hierarchy discrepancy of document.body and stage between mobile and web

### ISSUE THREAD

**Issue by sarahayu** [pixijs/pixijs#7328]
I was having issues with event handling in pixijs when I added a pointerdown handler to the body and to certain sprites on the stage. On web versions of pixi, the events fire in the expected order: the Sprite's pointerdown handler, then the body's pointerdown. However, I've found the opposite to occur on mobile: the body's pointerdown is fired first, then the sprite's. I'm not sure if this is a feature of pixi, but the inconsistency across web and mobile versions is inconvenient.

### Expected Behavior

A sprite is added to the PIXI app.stage. The sprite is marked interactive and is given a pointerdown handler that creates an alert indicating it is pressed. The document.body element is also given a pointerdown handler that creates an alert. When the sprite is pressed, the alert indicating it was pressed should pop up first, followed by the body's alert dialog.

### Current Behavior

On mobile, the body's alert message pops up first before the sprite.

### Steps to Reproduce

Run the following playground on mobile
https://www.pixiplayground.com/#/edit/T2G48_gKlANuyvYBLSNb3

### Environment

On web:
HP ProBook 11 G2, Chrome 89

On mobile:
BLU G5, Chrome
an older Samsung Galaxy, Chrome

**Comment by blackbing** [comment]
I have encountered the same issue. It is a big problem on Android browser, could anyone reopen this issue please. the event system could be something wrong.

**Comment by rnike** [comment]
I believe it is because EventSystem is ignoring the pointer event if device is supporting touch events.

https://github.com/pixijs/pixijs/blob/356abaaad852b248f0aa3f6873f5d7d2a56e3a50/packages/events/src/EventSystem.ts#L347-L348

@ShukantPal Do you have any idea about this?
