### ISSUE TITLE
KTXLoader quirks and ASTC support

### ISSUE THREAD

**Issue by hdemmer** [pixijs/pixijs#7329]
I'm delighted to see built-in compressed texture support in 6.0.0, big thanks!

Using KTXLoader I noticed that:
* After load the `resource.texture` field is not populated which breaks atlases (but is fixable with loader middleware)
* mipmaps are not being used, even if they are present. I suppose this line is at the root of this: https://github.com/pixijs/pixi.js/blob/dev/packages/compressed-textures/src/loaders/registerCompressedTextures.ts#L25

MipMaps were lost on BASIS as well, but I suppose that's a different issue. (Sadly the transcoder is too heavy for us)

Additionally, I'd love to see ASTC support, since it's quite widely available and has good tooling around it.

Let me know if there's anything I can help you with.

### Environment
- **`pixi.js` version**: 6.0.0

**Comment by bigtimebuddy** [comment]
Thanks for reporting and letting us know. @SukantPal said he'd take a look at this. Hope to have fixes for this in 6.0.2.

**Comment by qwertywelch** [comment]
> * After load the `resource.texture` field is not populated which breaks atlases (but is fixable with loader middleware)

Trying to use ktx files with atlases, how did you get them to work? Keep getting `Cannot read property 'baseTexture' of null` since `resource.texture` isn't being set.

**Comment by hdemmer** [comment]
@qwertywelch I added the following PIXI.Loader middleware:
```
pixiApp.loader.use((resource, next) => {
      if (resource.name.endsWith(".png") || resource.name.endsWith(".json_image")) {
            resource.texture = PIXI.Texture.from(resource.name);
      }
      next();
});
```
But I really want to get rid of this hack.

**Comment by bigtimebuddy** [comment]
I created an example to test compressed-textures and basis loading:
https://pixijs.io/compressed-textures-example/

**Comment by SukantPal** [comment]
@hdemmer You can enable mipmapping manually:

`texture.baseTexture.mipmap = MIPMAP_MODES.ON_MANUAL`

**Comment by bigtimebuddy** [comment]
Should mipmaps be on by default? And users can opt out? Right now it's the reverse.

**Comment by SukantPal** [comment]
I just found mipmaps to break stuff. Also, the compressed texture must specify **all** levels of detail for it work - otherwise WebGL will fail saying it's incomplete. So enabling it by default would mean detecting if all mips are available all the way to the 1x1 level (in addition, the texture must be POT for it to work).

**Comment by bigtimebuddy** [comment]
So the feature request here would probably be to find a way to auto-detect mipmaps. Otherwise, leaving it off seems like the best option.

**Comment by hdemmer** [comment]
@SukantPal Enabling MipMaps works like a charm and allows me to ship 🚢 Thanks! ✨ 
The KTX format allows to specify only a subset of mip levels, so I see where this can go wrong... Especially with Pixi's 2D focus leaving mips off by default is probably the better solution for now. Maybe we can document this somewhere?
About that ASTC support, is there anything I can do to help with? It's supported on modern Apple devices and quality-wise beats PVRTC by a mile.

**Comment by bigtimebuddy** [comment]
@hdemmer if you want to take a crack at ASTC, we'd gladly welcome a PR! You can follow the lead here on the existing formats to add another.

**Comment by ivanpopelyshev** [comment]
> @hdemmer if you want to take a crack at ASTC, we'd gladly welcome a PR! You can follow the lead here on the existing formats to add another.

Our previous plugin works with ASTC: https://github.com/pixijs/pixi-compressed-textures/tree/master/src/loaders
