### ISSUE TITLE
Rotating an object adds unexpected padding to its bounds

### ISSUE THREAD

**Issue by rizen** [pixijs/pixijs#7346]
<img width="595" alt="Screen Shot 2021-03-27 at 9 15 18 AM" src="https://user-images.githubusercontent.com/170009/112723649-add0f000-8edd-11eb-95c6-6d83b6f86d5f.png">

### Expected Behavior

If you call getBounds() on an object you rightly get it's bounding box parameters. I'd expect the bounds to be tight to the object whether it is rotated or not. 

### Current Behavior

Padding seems to be added to the object.

### Possible Solution

The only thing I can think of is that pixi is generating a raster of the object and using the raster as the dimensions for calculating the bounding box even though it has the actual dimensions of the object and could use those for calculating the dimensions of the bounding box. 

Perhaps this isn't even a bug, but rather just an unexpected side effect. I just thought I should report it in case it wasn't a known issue. 

### Steps to Reproduce

Create an object. Stick it in a container. Rotate the container. getBounds on the container. 

https://jsfiddle.net/en1sx9jr/

### Environment

- **`pixi.js` version**: 6.0.1
- **Browser & Version**: Safari 14.0.3 or Chrome or Firefox
- **OS & Version**: Mac OS 11.2.2
- **Running Example**: https://jsfiddle.net/en1sx9jr/

**Comment by SukantPal** [comment]
I think this is specific to `Graphics`. Each shape's untransformed bounding box is used to calculate the local bounding box.

https://jsfiddle.net/ShukantPal/xkwzjast/

<img width="601" alt="Screen Shot 2021-03-27 at 9 53 32 PM" src="https://user-images.githubusercontent.com/22450567/112739969-e2c55d00-8f46-11eb-8500-0c10e11cd9ec.png">

To calculate the tight bounds of a rotated transformed ellipse, you'd basically have to do the calculation on a generalized 2D conic equation using calculus (you'd get an equation after doing the math by hand).

**Comment by rizen** [comment]
I know what the calculation is, I was just expecting it would happen automatically. So I was reporting what I was expecting. I take it from your comments that how it works now is how it is intended to work?

**Comment by SukantPal** [comment]
I dunno if having a more exact calculation is an enhancement or a bug. @bigtimebuddy ?

**Comment by ivanpopelyshev** [comment]
It works this way in Flash. Please show me 2d renderer that calculates true bounds of objects.

**Comment by rizen** [comment]
@ivanpopelyshev basically every vector program (Illustrator, Inkscape, Corel Draw). I realize Pixi isn't a vector editor. But unlike standard raster programs it actually maintains the properties of the shapes it draws, so it could be more accurate, like vector programs.

**Comment by ivanpopelyshev** [comment]
Flash is the vectorest vector ever :)

**Comment by SukantPal** [comment]
Flash is the past so I we don't need to have the exact same behavior and not fix the flaws. I'm fine with improving the calculations to be tighter here - but somebody's got to make the PR :)

**Comment by rizen** [comment]
I unfortunately do not have the skills with regard to Pixi/Typescript to do this job. I'll see if I can hire someone to contribute a patch.

**Comment by bigtimebuddy** [comment]
My concern is that this is going to be a very slow path because it needs to support not just rotated normal shapes, but also arbitrary polygons and shapes. I'd suggest that we add a new API, like getLocalBoundsTrimmed (not super opinionated on the name). This way the behavior is non-breaking.
