### ISSUE TITLE
NineSlicePlane as a mask

### ISSUE THREAD

**Issue by mmrrnn** [pixijs/pixijs#7363]
Is it possible to use NineSlicePlane as a mask? I wanted to do it like for Graphics but it seems that the sprite always shown as a rectangle even though the mask is rounded rect.

https://codesandbox.io/s/reverent-spence-54y16?file=/src/App.js:1234-1309

**Comment by ivanpopelyshev** [comment]
We dont have implementation for ninesliceplane as an alpha mask. 

I saw full implementations of "anything as alpha mask" in pixi, I guess someone has to add it here, in vanilla :)
