### ISSUE TITLE
API Documentantion on classes should have a "most usefull" section

### ISSUE THREAD

**Issue by Bartvds** [pixijs/pixijs#7379]
The documentation is pretty good but the overview of classes can be overwhelming: https://pixijs.download/release/docs/PIXI.html

Many of the things shown there are very technical and not useful for the beginner or intermediate developer.

I think there should be a section above the full "classes" section that highlights the most used classes, like Container, Sprite, Rectangle, Circle, Spritesheet etc. Ideally no more then one or two dozen.

The section would be on the URL I linked above, or even on the index (https://pixijs.download/release/docs/index.html) and maybe filterable/sortable or in a collapsible section in the left menu.

**Comment by bigtimebuddy** [comment]
Awesome suggestion!

I realize that namespaces uses to be the way we hide more technical classes. But over time we've flattened and removed these namespaces.

I think there are a few possible solutions here. 

The easiest would be a single guide page with a list of these classes/APIs that are most applicable to newbies. I believe our template supports guides but not sure if webdoc does, @SukantPal?

Another idea might be to add a custom tag in webdoc and then add a global filter option in the docs that would toggle/visibility for items in the menu or in the namespace lists. This seems like the idea solution, but probably some work to do in the code and doc template.

**Comment by SukantPal** [comment]
webdoc does have some support for guides. Not robustly tested yet in real world.

**Comment by SukantPal** [comment]
Dunno if classes organized by packages would be helpful https://api.pixijs.io/index.html
