### ISSUE TITLE
Container.removeChild performance issue

### ISSUE THREAD

**Issue by Yuu6883** [pixijs/pixijs#7390]
This method basically calls Array.splice after getting the index of the child, which runs in O(n) runtime. It actually has a huge performance impact when thousands of children are removed from the parent and it has quite a negative impact on Containers like ParticleContainer when it's made for performance (would take 100ms and freeze everything for a bit). It would be nice if there's a method like `filterChildren` method that goes through each child and maybe have a callback to determine if it should be kept for not so this way removing n children only takes a linear time instead of n^2 time. The function would return the array of children removed just like the `removeChildren` function. I tried to write a subclass to achieve this, but since the field `children` is read-only I can not use .filter then set the reference.

**Comment by SukantPal** [comment]
We could just optimize `removeChild` when it has multiple children. Basically, if more than, say, 5 children are being removed the method should behave more like filter:

* For each child to be removed, "mark" it
* Then loop through `children` and splice out any marked children
* Clear the mark on the removed children

**Comment by ivanpopelyshev** [comment]
```js
let n = arr.length, j = 0;
for (let i=0;i<n;i++) {
  if (arr[i].dead) {
    //special destroy or whatever
  } else {
    arr[j]=i;
  }
}
arr.length = j;
```

**Comment by ivanpopelyshev** [comment]
Basically you want this thing as a method :) I use it everywhere I can. I dont think we can add it in default pixi because there are several questions , like "which property to use there" or "what if `remove` event will trigger another removal in this algo, how to notify user", e.t.c.

**Comment by SukantPal** [comment]
Not really. That “mark” property is really just a implementation detail. It’s transient - only relevant inside the removing operation.

On Apr 7, 2021, at 1:17 PM, Ivan Popelyshev ***@***.******@***.***>> wrote:



Basically you want this thing as a method :) I use it everywhere I can. I dont think we can add it in default pixi because there are several questions , like "which property to use there" or "what if remove event will trigger another removal in this algo, how to notify user", e.t.c.

**Comment by Yuu6883** [comment]
> I dont think we can add it in default pixi because there are several questions , like "which property to use there" or "what if remove event will trigger another removal in this algo, how to notify user", e.t.c.
The function would take a callback with a child as parameter and expects it to return a boolean-like value and then emits all the events and etc like other remove function do and wrap it inside a this.children = this.children.filter(....) statement. This way you don't need to make a new member variable to mark it like `removed` or whatever, and you can just leave the decision to the user (subclass etc). Another removal while inside this loop would probably break it as you mentioned and it's probably hard to deal with. 
All I can think of in my scenario is to not remove the child at all, but just setting their visibility to false and store it in a user-space array, and when I make a new child I will just try to pop from this array and set the values etc etc and make it visible again. This way removing is done in a linear time but will require some kind of relatively complex pool-like setup which is quite anti-oop.

**Comment by Yuu6883** [comment]
Well, I ended up ditching this library entirely and writing my own renderer with webgl1. This library does not meet the performance requirement for my use case.

**Comment by SukantPal** [comment]
That's cool, but the feature request is still valid.
