### ISSUE TITLE
Texture Manifest Multiple Non-Compressed Formats

### ISSUE THREAD

**Issue by qwertywelch** [pixijs/pixijs#7397]
### Expected Behavior
Given the following texture manifest JSON:
```json
{
 "cacheID": "interface/sprites-0",
 "textures": [
  {"format":"COMPRESSED_RGBA_S3TC_DXT1_EXT","src":"sprites-0.s3tc.ktx"},
  {"src":"sprites-0.webp"},
  {"src":"sprites-0.png"}
 ]
}
```
If the S3TC format is not supported, but WebP is, it should use the WebP texture.  If WebP is not supported, it should use the PNG texture.

### Current Behavior
When the S3TC format is not supported, the PNG is always used. The [CompressedTextureLoader](https://github.com/pixijs/pixi.js/blob/492688bd2810b95285c7477b4904e88c6aba7691/packages/compressed-textures/src/loaders/CompressedTextureLoader.ts#L89) loops through the `textures`, and since it can't find one with a supported compressed `format`, it falls back to the last item without a format. Only compressed formats can be specified. In the case of the JSON above, it will always use the PNG. 

### Possible Solution
Allow specifying formats for all textures listed in one of these manifest files, so that multiple non-compressed formats can be specified. 

### Environment
- **`pixi.js` version**: 6.0.2

**Comment by bigtimebuddy** [comment]
Good idea!
