### ISSUE TITLE
VideoResource never resets _isConnectedToTicker in dispose?

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixijs#7400]
https://github.com/pixijs/pixi.js/blob/91b0b8fa06d202f4d523b38b80034b1f1e48f11a/packages/core/src/textures/resources/VideoResource.ts#L335

This sometimes is confusing if you wanna check if the resource is properly destroyed.

**Comment by bigtimebuddy** [comment]
Hmm, I'm not sure I understand this. Why do you want to reset _isConnectedToTicker. At the `dispose` method, you don't need the resource anymore. Can you explain more?

**Comment by SukantPal** [comment]
If you're debugging a leak in your application, and you see `_isConnectedToTicker` is still true - you'd assume that it's a problem. It should be false to prevent confusion, and to ensure consistency in the fields - even if destroyed.
