### ISSUE TITLE
Make masks respect the transformation of their target without having to add them to the target

### ISSUE THREAD

**Issue by rubenlg** [pixijs/pixijs#7426]
This is a feature request, not a bug report. It's related to #1978.

Masks are a super powerful feature. Thanks a lot for that! That said, I got bitten by masks ignoring the transformation of their parent twice already (the only two times I used them so far).

In some cases it's possible (although hacky) to add the mask to the parent, as recommended in that other bug. The reason I say this is hacky is that it the intent is confusing. It's unclear whether the intent of some code having the mask as a child is to have the mask follow the transform of the parent, or just have it rendered as well. It can be mitigated with documentation, but with a different API, such documentation wouldn't be necessary.

In other cases, due to design choices, altering the children of the parent to include the mask is not possible or really hard to do. One example is a scene editor that would get confused with that mask being a child. Another example is a library that produces PIXI objects from another representation (e.g. ReactPixi) and fails when the mask is injected as a child because indices no longer match. These are not theoretical, I have both use cases.

The requested feature is a boolean property controlling this mask behavior, so it can be toggled to decide whether the mask should be applied with the parent transformation or without any transformation like it does today. All of this without altering the children list of the parent.

Thank you!

**Comment by rubenlg** [comment]
I found another workaround that does not require modifying the children of the target object:

Every time I suspect the transform of the target might have changed:
`mask.transform = target.transform;`

Still a bit hacky, since it requires hooking to all the ways in which the target transform can change, to copy it over to the mask (not a problem for my use cases), and prevents the mask itself from having a transformation "delta". But unblocks me until Pixi hopefully provides something better.

**Comment by SukantPal** [comment]
Another way is to do something like `mask.transform.setFromMatrix(target.worldTransform.clone())`

**Comment by rubenlg** [comment]
Thanks @SukantPal. What's the advantage of that approach?

**Comment by SukantPal** [comment]
The transform isn't supposed to be reassigned - with this approach you're merely copying data over into the mask.
