### ISSUE TITLE
Firefox Webm videos blink

### ISSUE THREAD

**Issue by rhayes2** [pixijs/pixijs#7457]
Hey guys!

Just been using pixijs and its been awesome! Love it! :D

However there is a issue I've had that I cannot figure out, 

Firefox when using webms will blink when looping.  I've tried many different encodings (as suggested in a passed issue) and I've not found anything that works in that sense,

I've also tried making a pixi-patch which would loop the video without relying on the video tag loop to see if that would help

I've created a small app to test and watch the blink regardless of the webm I put in. (this one takes longer to blink ) 

```

<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <title>pixi.js example - Graphics</title>
    <style>
        body {
            margin: 0;
            padding: 0;
        }
    </style>

  <script src="./pixi.js"></script>
</head>
<body>
<script>
// The application will create a renderer using WebGL, if possible,
// with a fallback to a canvas render. It will also setup the ticker
// and the root stage PIXI.Container
const app = new PIXI.Application({ backgroundColor: 0x1099bb });
document.body.appendChild(app.view);

// create a new Sprite from an image path
const bunny = PIXI.Sprite.from('https://simpl.info/videoalpha/video/soccer1.webm');
bunny._texture.baseTexture.resource.source.muted = true 
bunny._texture.baseTexture.resource.source.loop = true
// center the sprite's anchor point
bunny.anchor.set(0.5);

// move the sprite to the center of the screen
bunny.x = app.screen.width / 2;
bunny.y = app.screen.height / 2;

app.stage.addChild(bunny);
</script>

</body>
</html>
```

### Environment
- **`pixi.js` version**:  6.0.2_
- **Browser & Version**: FF 88.0 (64-bit)

**Comment by a-c-sreedhar-reddy** [comment]
This happens in my project as well.

**Comment by rhayes2** [comment]
There was 2 passed threads about similar issues and last time I checked it just gets blamed on the encoding 👍

**Comment by bigtimebuddy** [comment]
Thanks @a-c-sreedhar-reddy for the example.  I have a couple of thoughts...

I tried transpiling the video to mp4 and ogv formats to see if that had any effect. I saw flicking on both, though it was a lot less for OGV. Here are the examples:

OGV: https://www.pixiplayground.com/#/edit/nJIgPWECpp29s2CufAew2
MP4: https://www.pixiplayground.com/#/edit/hQKr6Z8ycRRj-nH7GT0V0

Here's a pure WebGL implementation of playing the same webm video: https://jsfiddle.net/bigtimebuddy/g0mua2ex/6

As you can see the flickering still happens, so this is not a PixiJS issue and someone should consider reporting an issue to Mozilla about this.

What I think is happening is that the loop happens before Firefox has a chance to upload to the GPU. If we slow down the animation using playbackRate to 10%, you can see the flicker occurs hardly at all:
https://www.pixiplayground.com/#/edit/c0fdLleJ36zvzj0WI3kdc

A workaround might be to set `autoUpdate = false` on the VideoResource object, and then manually call `update()` yourself and maybe not uploading if the currentTime of the video is less than some buffer like 100ms (the amount of time needed up load to the GPU).

**Comment by dev7355608** [comment]
I had a look at this today, and I noticed that every time it flickers, the `video.readyState` is 1, indicating that no frame data is available. The solution seems easy: don't upload if the video isn't ready (i.e., only upload if `readyState >= 2`). That seems to work very well. I couldn't observe any flickering after changing that.
