### ISSUE TITLE
PIXI.Loader cannot load SVG with XML prolog

### ISSUE THREAD

**Issue by lyrerest** [pixijs/pixijs#7460]
### Current Behavior
Any SVG with an XML prolog (such as default exports from Boxy SVG) cannot be used with PIXI.Loader. The SVG data is preloaded via XHR and fails the SVGResource.test() funciton. 

SVGs with XML prologs can still be used as normal with PIXI.Texture.from() because in this case it is the SVG URL and not the file data that is passed to SVGResource.test().

### Possible Solution
Update SVGResource to accept SVGs with XML prologs. The test function will require an additional regex test and the load function will also require updates.

### Steps to Reproduce
Load any SVG file with an XML prolog (see below) included at the start of the file using the PIXI.Loader add function.

![image](https://user-images.githubusercontent.com/22718547/116789224-d0759c00-aa7b-11eb-8f32-2efec77772ec.png)

Tested on Pixi.js 6.0.2

**Comment by bigtimebuddy** [comment]
Thanks for pointing this out. Looks like we just need to tweak the test() method to handle this and probably add a unit-test. PR welcome!
