### ISSUE TITLE
Documentation update needed

### ISSUE THREAD

**Issue by AlexandreRangel** [pixijs/pixijs#7486]
Dear Pixi friends,

I think we have spotted an error on the Pixi documentation in
[https://pixijs.download/dev/docs/PIXI.DisplayObject.html](https://pixijs.download/dev/docs/PIXI.DisplayObject.html)

The functions
**PIXI.DisplayObject.addEventListener / removeEventListener** 
should be updated to
**PIXI.DisplayObject.addListener / removeListener**

as stated on this issue:
[https://github.com/pixijs/pixi.js/issues/2621](https://github.com/pixijs/pixi.js/issues/2621)

**Comment by bigtimebuddy** [comment]
Sorry for the confusion. This is not an error, these APIs were added recently by @SukantPal's new, unreleased `@pixi/events` package. Probably `addEventListener` and `removeEventListener` _should_ indicate in the docs that these are mixins from events.
