### ISSUE TITLE
Sprites are rendered in incorrect positions if canvas size is very large

### ISSUE THREAD

**Issue by taylanken** [pixijs/pixijs#7494]
### Expected Behavior

When I create a PIXI application with a large canvas size (e.g. 10,000 x 5,000) and add sprites to the stage, I would expect the sprites to be rendered at the position that I've specified.

### Current Behavior

For large sizes, PIXI renders the sprites at incorrect positions. To be more specific, the x-value of the rendered sprite is always larger than what I specified, while the y-value is smaller than what I specified.

Interestingly, while the visual sprite is at an incorrect position, for interactive sprites the events are still fired at their correct positions (e.g. if I render a rectangle that has a click event handler, the event handler will fire if I click on the position that I'm expecting the rectangle to be, even if it is rendered somewhere else).

### Steps to Reproduce

I have created a very small reproduction of this issue:

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>PIXI Repro</title>
</head>

<body>

    <style>
        body,
        html {
            margin: 0;
            padding: 0;
        }
    </style>

    <script src="https://pixijs.download/v6.0.4/pixi.min.js"></script>
    <script>
        // size to use
        var width = 8_000, height = 5_000;

        // create application
        var app = new PIXI.Application({
            width: width,
            height: height,
            preserveDrawingBuffer: true,
            sharedLoader: true
        });
        document.body.appendChild(app.view);

        // load some random image
        var imgUrl = 'https://miro.medium.com/max/4800/1*scwcpro6eU-pORVH_Fpc_g.png';
        app.loader.add('test', imgUrl);

        app.loader.load(() => {

            // create 32x32 sprite from image
            var texture = app.loader.resources['test']?.texture;
            var sprite = PIXI.Sprite.from(new PIXI.Texture(
                texture.baseTexture,
                new PIXI.Rectangle(0, 0, 32, 32)
            ));

            // set the sprite to roughly the center of the canvas
            sprite.position.x = width / 2;
            sprite.position.y = height / 2;

            // add to stage
            app.stage.addChild(sprite);

            // for convencience, automatically scroll to center of the page
            setTimeout(() => {
                var vw = Math.max(document.documentElement.clientWidth || 0, window.innerWidth || 0)
                var vh = Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0)
                window.scrollTo((width / 2) - (vw / 2), (height / 2) - (vh / 2))
            });
        });
    </script>
</body>

</html>
```

Just put this in a HTML-file and open it in Chrome browser. The code is supposed to render a rectangle at the center of the canvas. For convenience, it automatically scrolls to the center so that you can immediately check if it is there.

If you set the size for example to 8000x4000 (by modifying the `width` & `height` variables), the rectangle will be at the correct position.

However if you set it to 8000x5000, it will be shifted to the top right. The larger you set these values, the more will the rectangle shift to the top right, although it's position is supposed to be the center of the canvas.

At some point, it shifts so far that it disappears because it is outside of the canvas bounds.

### Environment

- **`pixi.js` version**: `6.0.4`
- **Browser & Version**: `Chrome 90.0.4430.212 (64-bit)`
- **OS & Version**: `Windows 10 (64-bit)`

**Comment by SukantPal** [comment]
Hi, I've tested this and this is probably because of the maximum viewport size your WebGL implementation supports:

```
// [8192, 8192]
console.log([...app.renderer.gl.getParameter(app.renderer.gl.MAX_VIEWPORT_DIMS)])
```

If you increase the canvas above this limit, the rendered area on the canvas will be smaller than the canvas itself. Please check this and let me know if that isn't the issue.

**Comment by taylanken** [comment]
This seems to be the issue, wasn't aware of the maximum viewport size. Thank you!
