### ISSUE TITLE
`DisplayObject.parent` should be a `Container` instead of a `DisplayObject`.

### ISSUE THREAD

**Issue by peacegiverman** [pixijs/pixijs#7500]
The `DisplayObject`'s `parent` property is currently typed as a `DisplayObject`. Seeing that a parent of a display object must always be at least a container in order to contain any children, this type should be changed to `Container`.

As it is now, it leads to issues when using `parent` within a _typescript_ project, e.g:

```typescript
// To add a sibling sprite...
sprite.parent.addChild(PIXI.Sprite.from('assets/sprite.png'));

// Throws a compilation error
// Property 'addChild' does not exist on type 'DisplayObject'
```

In the Pixi documentation, the `parent` property is [still listed](https://pixijs.download/release/docs/PIXI.DisplayObject.html#parent) as a `Container`, which may lead to additional confusion.

https://github.com/pixijs/pixijs/blob/ea9a5ccb2ff3f462ef2a4ee1c083bb2c5c62c3af/packages/display/src/DisplayObject.ts#L210

**Comment by bigtimebuddy** [comment]
Definitely a bug, thanks for pointing this out @peacegiverman
