### ISSUE TITLE
Fill color and outline color are mixed up

### ISSUE THREAD

**Issue by Bouh** [pixijs/pixijs#7503]
### Current Behavior
Fill color and outline color on PIXI.Graphics are mixed up when clear() isn't called.
The context can be loose and the tab can crash.

Not calling clear() is intentional because it is useful for a whiteboard app.
But it's mostly that the colors are mixed.

In GDevelop we use PIXI.graphic and the result in games are visible, especially in [this report](https://github.com/4ian/GDevelop/issues/2644#issuecomment-840638610).

Even with an outline width of zero the colors have a problem.

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/Ucs7etVGwXM5Ko9gi3yJQ

### Environment

- **`pixi.js` version**: 6.0.1
- **Browser & Version**: Chrome 90.0.4430.212
- **OS & Version**: Windows 10
- **Running Example**:  https://www.pixiplayground.com/#/edit/Ucs7etVGwXM5Ko9gi3yJQ

**Comment by bigtimebuddy** [comment]
The crashing here is probably somewhat obvious,  by adding a new shape every 1/60 second, you can quick accumulate memory and cpu usage that's unreasonable. 

The more concerning thing here is the funny rendering of strokes and fills. Tweaked your demo to slow down and spread the graphics over a little more:

https://www.pixiplayground.com/#/edit/Fhll0JAGY9OpjbIFFRajD

One small clue might be if you remove `drawCircle` call, it works fine.
