### ISSUE TITLE
BUG: Uncaught TypeError: Cannot read property 'stencil' of null

### ISSUE THREAD

**Issue by kayac-chang** [pixijs/pixijs#7507]
This issue when create a new instance, after previous renderer instance calling `renderer.destroy()`

### Expected Behavior
Different instance should not be affect each other.

### Current Behavior
Throw `Uncaught TypeError: Cannot read property 'stencil' of null`, after previous renderer instance calling `renderer.destroy()`.

### Steps to Reproduce
This issue when create a new instance, after previous renderer instance calling `renderer.destroy()`

### Environment

- **`pixi.js` version**: 6.0.2
- **Browser & Version**:  Chrome 90

**Comment by bigtimebuddy** [comment]
Unable to reproduce on Chrome 90:
https://jsfiddle.net/bigtimebuddy/gkj8pv1e/

Please create an example that reproduces this issue.
