### ISSUE TITLE
Alpha Filter + Custom Filter giving incorrect result

### ISSUE THREAD

**Issue by melwyn95** [pixijs/pixijs#7508]
### Current Behavior
I have a particular combination of Containers and Sprites in which Alpha Filter and a Custom Filter (Blend filter) are applied on different nodes of the subtree

For this combination I'm getting incorrect result

Container(Alpha Filter)->Container->Sprite(Blend Filter)

JS Fiddle: https://jsfiddle.net/68gnxsmk/31/

Without Alpha Filter:
![Screenshot 2021-05-26 at 9 29 11 AM](https://user-images.githubusercontent.com/14284762/119641557-6d3b1780-be37-11eb-83f2-ed82eceac45b.png)

With Alpha Filter:
![Screenshot 2021-05-26 at 9 29 21 AM](https://user-images.githubusercontent.com/14284762/119641617-7af09d00-be37-11eb-9562-92cec7dfcc0f.png)

- **`pixi.js` version**: 6.0.0
- **Browser & Version**:  Chrome Version 90.0.4430.212
- **OS & Version**: Mac OS (Big Sur)
- **Running Example**: https://jsfiddle.net/68gnxsmk/31/

**Comment by melwyn95** [comment]
If alpha is 0.5 I want something like this
![Screenshot 2021-05-26 at 4 25 08 PM](https://user-images.githubusercontent.com/14284762/119648349-face3580-be3e-11eb-8783-98ef6ca2eb56.png)


So basically in the code `foregroundComposite` will have some opacity, instead of applying the opacity by changing the 
`alpha` property of the container I'm using AlphaFilter

because changing the `alpha` property on container gives me the wrong result

How can I get this result, please suggest

**Comment by ivanpopelyshev** [comment]
add `alpha` uniform to your filter, and do something like

```glsl
gl_FragColor = result * alpha + dstColor * (1.0 - alpha);
```

Alternatively, we should add something like "alpha" param for filter itself, and in FilterSystem when it time to draw filter to screen, use that alpha. However I didnt make this hack in this particular version of pixi, it existed only in my fork.

**Comment by melwyn95** [comment]
@ivanpopelyshev I tried a few things that gave the correct result for me
1. Container -> Container -> Sprite(Alpha Filter, Blend Filter)
2. Container(Alpha Filter, Blend Filter) -> Container -> Sprite
3. Container(Blend Filter) -> Container -> Sprite(Alpha Filter)

Basically If Alpha & Blend filters are applied on the same container it gives the correct result
also If Blend filter is applied before Alpha Filter it gives the correct result

As you pointed out earlier that after the Alpha Filter is applied, 
Inside the Blend Filter the backdrop is empty

Is there anyway to extract the backdrop in the child nodes if Alpha/Any filter is applied on parent node?
So that blend would work correctly in child nodes

**Comment by ivanpopelyshev** [comment]
That's all expected result for me.

The problem is that parent `filter.push()` invocation doesnt know whether there will be a blend filter inside. Either you have to do it from child `filter.push()` invocation, either you scan through the tree in parent one.

**Comment by ivanpopelyshev** [comment]
I'm actually very glad that someone is using my blend filters approach :)

**Comment by melwyn95** [comment]
Yeah this approach is very cool, we took some inspiration from your pixi-picture library and @SukantPal helped us with the code for this

**Comment by melwyn95** [comment]
Thanks a lot @ivanpopelyshev for the answer, As this is the expected behaviour, I'm closing this issue

**Comment by ivanpopelyshev** [comment]
@melwyn95  pixi-picture package is now @pixi-picture , that BlendFilter works with v6.
