### ISSUE TITLE
Hole in masks are not rendered with CanvasRenderer

### ISSUE THREAD

**Issue by myktsk** [pixijs/pixijs#7509]
### Expected Behavior
The hole in mask should be rendered with CanvasRenderer 

### Current Behavior
I've tried making an inverted mask using mask with hole. It works perfectly fine with the normal renderer, but doesn't seem to work with the CanvasRenderer.
Code sandbox: https://codesandbox.io/s/pixi-hole-in-mask-with-canvasrenderer-1jbvs
#### With CanvasRenderer
<img width="316" alt="スクリーンショット 2021-05-26 20 02 59" src="https://user-images.githubusercontent.com/22167483/119649287-6d4e0e00-be5d-11eb-98d0-332da8434dbf.png">

#### With WebGL Renderer(Expected behavior)
<img width="316" alt="スクリーンショット 2021-05-26 20 03 09" src="https://user-images.githubusercontent.com/22167483/119649291-6f17d180-be5d-11eb-8296-874d03a85a77.png">

### Steps to Reproduce
- Create a base object using PIXI.Graphics
- Create mask object using PIXI.Graphics
- Add hole in the mask object
- Set the mask object as the mask to the base object

### Environment

- **`pixi.js` version**:  5.3.8 to latest
- **Browser & Version**: Google Chrome 91.0.4472.77
- **OS & Version**: macOS Catalina 10.15.7
- **Running Example**: https://codesandbox.io/s/pixi-hole-in-mask-with-canvasrenderer-1jbvs

**Comment by ivanpopelyshev** [comment]
That's how it is now: 

https://github.com/pixijs/pixijs/blob/0b9f75555c322402f74ffbb79f36fe0425217070/packages/canvas/canvas-renderer/src/utils/CanvasMaskManager.ts#L117-L133

That's how it should be, code should look like in Graphics:

https://github.com/pixijs/pixijs/blob/0b9f75555c322402f74ffbb79f36fe0425217070/packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.ts#L166-L222

**Comment by ivanpopelyshev** [comment]
Bumping it to ensure that it wont be stale
