### ISSUE TITLE
e.originalEvent.currentTarget.setPointerCapture is undefined

### ISSUE THREAD

**Issue by TomekStaszkiewicz** [pixijs/pixijs#7510]
### Expected Behavior
The `setPointerCapture` should work like [this](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture)
It should be a function I can call on `EventTarget`.  

### Current Behavior
The value of `setPointerCapture` is undefined. Am I missing something?

### Possible Solution
I think that I am missing something, but I am not able to find what. I hope that someone might explain me how to actually call this `setPointerCapture` function :(

### Steps to Reproduce
My code looks like this:
```
this.stage.on('pointerdown', (e) => {
        const originalEvent = e.data.originalEvent;
        console.log(originalEvent.currentTarget);
 });
```
The `this.stage` is just an instance of a  class that extends the Pixi `Container` class. 

### Environment

- **`pixi.js` version**:  5.3.0
- **Browser & Version**: Chrome 91.0.4472.77
- **OS & Version**: MacOS BigSur v11.3.1

**Comment by SukantPal** [comment]
@TomekStaszkiewicz The PixiJS `DisplayObject` is not an `Element`. This would be a feature request.

**Comment by TomekStaszkiewicz** [comment]
@SukantPal Thanks for your response! So the `e.data.originalEvent` does not store the `Element`? Regarding to [documentation](https://pixijs.download/release/docs/PIXI.InteractionData.html) : 
```
OriginalEvent
When passed to an event handler, this will be the original DOM event that was captured
```
It seems like it should work as I described.

**Comment by SukantPal** [comment]
Hmm, my bad I forgot you were using originalEvent. I'll dig into this.

**Comment by TomekStaszkiewicz** [comment]
Hi @ShukantPal, any update on that issue? :)

**Comment by ShukantPal** [comment]
Can you check if the interaction event has `isNormalized` on it? If so, PixiJS has normalized the touch or mouse event and normalized touch events aren't assigned a `currentTarget` by the Interaction API.
