### ISSUE TITLE
Pixi.JS fails to compile / complains about failed export mixins

### ISSUE THREAD

**Issue by cooperate** [pixijs/pixijs#7514]
### Expected Behavior
Pixi.js to compile.
### Current Behavior
Node throws an error:
```
Failed to compile.

./node_modules/pixi.js/lib/pixi.es.js
Attempted import error: 'mixins' is not exported from '@pixi/utils'.
```
### Environment
React / Typescript / pixi.js / react-pixi
- **`pixi.js` version**: 5.0.0-rc

**Comment by bigtimebuddy** [comment]
Please provide a repo that reproduces the issue.

**Comment by bigtimebuddy** [comment]
Actually on second thought, I'm going to close this. This bug is reported on a prerelease version (5.0.0-rc). If this reproduces on a final release, we can re-open.
