### ISSUE TITLE
Array of sampler2D in fragment shader

### ISSUE THREAD

**Issue by thomasfrancisco** [pixijs/pixijs#7523]
### Description
I'm trying to implement a shader that need an array of sampler2D as uniforms, but I don't understand how I should implement it in the uniform declaration in JS code. It only uses the last textures used in the code (meaning there is an error in my uniforms).

How to make a shader work with a sampler2D array as a uniform ?

My fragment shader is :
```
precision mediump float;
varying vec2 vUvs;
uniform sampler2D textures[2];

vec4 addTexture(vec4 base, sampler2D texture, vec2 uv){
   vec4 color = texture2D(texture, uv);
   vec4 ret = color + base;
   ret.rgb -= mix(vec3(0.0), base.rgb, color.a) * step(0.0, color.a) * step(0.0, base.a);
   return ret;
}

void main() {
   vec4 color = vec4(0.0, 0.0, 0.0, 0.0);
     
   color = addTexture(color, textures[0], vUvs);
   color = addTexture(color, textures[1], vUvs);
        
    gl_FragColor = vec4(color);
}
```

And the uniform in the JS code :
```
// loadtexture: PIXI.Texture[]
const uniforms = {
   textures: loadedTextures,
}
```

### Possible Solution
As a workaround, I'm declaring each sampler2D separately, with a small code to bind each declaration with the related textures.
It produces a fragment like:
```
uniform sampler2D textures0;
uniform sampler2D textures1;
```
And something like this in the uniforms:
```
const uniforms = {
   textures0: loadedTextures[0],
   textures1: loadedTextures[1],
}
```
I also tried to use BatchPluginFactory, but I couldn't manage to make the example in the source code to work...

### Steps to Reproduce
Here is two fiddle:
Result expected (with workaround) : https://jsfiddle.net/thofrancisco/65dz8bhw
And with array and failing : https://jsfiddle.net/thofrancisco/zn826k3g

### Environment

- **`pixi.js` version**: 5.2
- **Browser & Version**: Firefox 88.0
- **OS & Version**: Ubuntu 18.04
- **Running Example**: _url_

**Comment by ShukantPal** [comment]
The way texture uniforms work is that you set the uniform to a "texture unit" (number) of the GPU. For a single texture, PixiJS will bind the texture to the texture unit 0. If you try to send two separate textures, it won't work since only one texture can be bound to texture unit 0.

You have to something as follows:

```
renderer.texture.bind(texture0, 0)
renderer.texture.bind(texture1, 1)

uniforms = {
  textures: [0, 1],
}

// OR

uniforms = {
  texture0: 0,
  texture1: 1,
}
```

See [TextureSystem#bind](https://api.pixijs.io/@pixi/core/PIXI/TextureSystem.html#bind)

**Comment by thomasfrancisco** [comment]
Thanks ! It works perfectly !
I didn't know that PIXI handled textures that way with the GPU.

This will also help me to optimize how I load my assets in the game.
