### ISSUE TITLE
How to create 320x200 fullscreen app ?

### ISSUE THREAD

**Issue by djflex68** [pixijs/pixijs#7524]
Hello,

In my old days I was used to create some small games using Qbasic 4.5.
There was a mode called SCREEN 13 that allows drawing some graphics (points, lines) on a 300x200 fullscreen renderer.
What is the easiest way to create a PIXI app that autoscales everything into fullscreen like if we would work on a 300x200 screen ?

Thanks

**Comment by bigtimebuddy** [comment]
For general questions, please create a discussion. Thank you. Transferring this...
