### ISSUE TITLE
Zoom Teleport/Warp Effect

### ISSUE THREAD

**Issue by fleeasura123** [pixijs/pixijs#7533]
Good day! I am very fascinated by this effect. 

![zoom teleport warp](https://user-images.githubusercontent.com/53055963/121692414-a5f71400-cafa-11eb-817e-a2c8f23d2680.gif)

Any tips how can we implement it on PixiJS? 
Or demos I can see.. Or what should I learn to implement such effect?

Any help is appreciated.

**Comment by ivanpopelyshev** [comment]
If its webgl site, dig out the shader, maybe use SpectorJS to do that (capture frame in transition). Then make a pixi filter based on it

**Comment by fleeasura123** [comment]
> If its webgl site, dig out the shader, maybe use SpectorJS to do that (capture frame in transition). Then make a pixi filter based on it

Thank you for the tips! will research on that! nice!
