### ISSUE TITLE
Y axis is flipped for filter when using RenderTexture

### ISSUE THREAD

**Issue by wmike1987** [pixijs/pixijs#7538]
I have a sprite and a filter which colors half of it blue (based on gl_fragCoord).
When I use a RenderTexture to try and copy the stage, including the effect of the filter, the y appears to be flipped.

See this example,
https://www.pixiplayground.com/#/edit/DlT1XDBjY9TlU8ejvfo61

What am I missing here?

**Comment by ivanpopelyshev** [comment]
> based on gl_fragCoord
yes, renderTextures y=0 is actually the top. For Webgl main framebuffer its bottom of screen.
Why we did it like that - our textures are stored that way, we dont use FLIP_Y on upload.

Don't use gl_fragCoord. https://github.com/pixijs/pixijs/wiki/v5-Creating-filters#conversion-functions

`vTextureCoord * inputPixel.xy` is what you need

**Comment by ivanpopelyshev** [comment]
Alternatively, if you use filter on sprite with renderTexture, why not just use mesh-shader?  Sometimes that's the case, just make quad geometry, put your renderTexture there.

https://pixijs.io/examples/#/mesh-and-shaders/triangle-textured.js

**Comment by wmike1987** [comment]
Thanks, it works using that conversion formula. I updated the example in my original post to include a working shader for anyone who sees this in the future.
