### ISSUE TITLE
Text vertical gradient breaks when line height is smaller than font size

### ISSUE THREAD

**Issue by nuthinking** [pixijs/pixijs#7540]
![text-gradient](https://user-images.githubusercontent.com/163635/122174423-02538e00-ce83-11eb-85c3-c9755cb56ede.png)

While a very small line height where characters overlap is expected to inevitably break the rendering, when the line height is marginally smaller and characters don't overlap, it would be desirable if the rendering doesn't break.

[Demo](https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22fill%22%3A%5B%22white%22%2C%22red%22%5D%2C%22fontSize%22%3A86%2C%22lineHeight%22%3A66%2C%22padding%22%3A10%7D%2C%22text%22%3A%22Hello%5CnWorld%22%2C%22background%22%3A%22%23000000%22%7D)

**Comment by qq865738120** [comment]
I think a constant `gradStopLineHeight` calculation in the `_generateFillStyle` function in `Text.ts` is flawed. Can I try to fix it?
