### ISSUE TITLE
PIXIJS downgrade?

### ISSUE THREAD

**Issue by Coder2195Text** [pixijs/pixijs#7542]
From this: ![image](https://user-images.githubusercontent.com/63069499/122609630-52ca1780-d04c-11eb-9b77-5b9f2226b5d9.png)

To this: 
![image](https://user-images.githubusercontent.com/63069499/122609687-637a8d80-d04c-11eb-81d0-9abafc90d650.png)

Downgrade or no?

**Comment by bigtimebuddy** [comment]
GitHub does not allow use to order releases by semantic version or define "latest", these are simply ordered by date. We did a patch release for v5, that is not a recommendation for downgrading.

**Comment by Coder2195Text** [comment]
Oh that’s why
