### ISSUE TITLE
setting interactive to false still trigger parent pointer event

### ISSUE THREAD

**Issue by code945** [pixijs/pixijs#7549]
Hi All,

I just found an issue when using pixi. After i set `interactive = false` of a child object , then click on the child object, the parent still could receive `onpointerdown` event, which seems strange.

### Expected Behavior
setting `interactive = false` of an object will not make the parent to be selected

### Current Behavior
setting `interactive = false` of an object will make the parent to be selected

### Steps to Reproduce
1. add a container set interactive = true
2. add a sprite set interactive = false
3. add "pointerdown" event of container
4. click on sprite 

### Environment

- **`pixi.js` version**: 5.3.0
- **Browser & Version**:  90.0.4430.212 
- **OS & Version**: MacOS 10.15.7 (19H1030)
- **Running Example**: https://www.pixiplayground.com/#/edit/0J5LfGxY9zHQ4UewVBkiv

maybe we should add a check in this code ?

https://github.com/pixijs/pixijs/blob/dev/packages/interaction/src/TreeSearch.ts#L113

```
 for (let i = children.length - 1; i >= 0; i--)
            {
                const child = children[i];

==============================================
                if(child.interactive === true)
==============================================



                // time to get recursive.. if this function will return if something is hit..
                const childHit = this.recursiveFindHit(interactionEvent, child, func, hitTest, interactiveParent);

```

**Comment by andrewstart** [comment]
This is working as intended - the parent's hit area is the combined hit area of its children, so they are checked to see if the interactive parent is clicked. Setting `interactive = false` only prevents events on that particular child, not any of its parents.

**Comment by code945** [comment]
Thanks for your explain, I agree that the parent's hit area is the combined hit area of its children, but does it much better to only include the interactable children?  Or are there any workaround to make some of the children not trigger events? I have tried to set ` interactiveChildren = false` of the parent but that will bypass all of the children's hitTest.

**Comment by andrewstart** [comment]
To make something truly unclickable, you could set it's `hitArea` property to something like `{ contains: () => false }` as a very basic "shape" that always returns false for its hit testing.

**Comment by eXponenta** [comment]
> but does it much better to only include the interactable children? 

Of course this will not working, because you can try listen events for huge tree, but by your logic for this will be needed set Interactive flag for ALL objects under tree.
That impossible in general case.
