### ISSUE TITLE
BaseTexture wrapMode, scaleMode, mipmap should be getters/setters that increment dirtyStyleId

### ISSUE THREAD

**Issue by ShukantPal** [pixijs/pixijs#7550]
## Context

I was using `Graphics` with a texture fill and was surprised when the texture did not tile. I tried reproducing this with a lone `Graphics` but would not (unless you used very large coordinates - which was unrelated).

<img width="394" alt="Screen Shot 2021-06-22 at 6 37 14 PM" src="https://user-images.githubusercontent.com/22450567/123153925-3eaf5d00-d434-11eb-9782-ae5dd0b1487a.png">

Then I tried not rendering the existing tiles as sprites - and the problem went away. It turns out that `GraphicsGeometry` sets the `wrapMode` on the texture here:

https://github.com/pixijs/pixijs/blob/410a49c4f4e938d75a52a5129e98eb771780dc61/packages/graphics/src/GraphicsGeometry.ts#L509

However, if the texture has already been rendered once - the texture style would not be dirty. Since setting wrap-mode doesn't update the `dirtyStyleId`, the texture's wrap-mode wouldn't be updated in WebGL.

### Possible Solution

This can be fixed by

* making `wrapMode` a getter/setter that updates `dirtyStyleId` when you change it
* or calling `texture.baseTexture.update()` in `GraphicsGeometry`

I like the first option.

### Steps to Reproduce

In the following fiddle, I render the stage once with a single sprite (left). Then I add texture-tiling graphics (right) and re-render the scene.

https://jsfiddle.net/ShukantPal/dag0bhq9/

<img width="327" alt="Screen Shot 2021-06-23 at 3 11 30 PM" src="https://user-images.githubusercontent.com/22450567/123154759-4ae7ea00-d435-11eb-9a2c-980269e6b3dd.png">

The "Update texture" button will call `baseTexture.update()` and re-render the scene - and that fixes the problem:

<img width="373" alt="Screen Shot 2021-06-23 at 3 11 52 PM" src="https://user-images.githubusercontent.com/22450567/123154810-5804d900-d435-11eb-813d-d4126d814886.png">

### Environment

- **`pixi.js` version**: 6.0.4
- **Running Example**: [https://jsfiddle.net/ShukantPal/dag0bhq9](https://jsfiddle.net/ShukantPal/dag0bhq9)

**Comment by bigtimebuddy** [comment]
I like your first option too.

**Comment by ivanpopelyshev** [comment]
Agree on first option.
