### ISSUE TITLE
Don't jitter when text changes

### ISSUE THREAD

**Issue by defpis** [pixijs/pixijs#7551]
### Expected Behavior

![屏幕录制2021-06-24 下午5 42 07](https://user-images.githubusercontent.com/48018016/123241305-9a9ce300-d513-11eb-96da-938f1129c7c0.gif)

### Current Behavior

![屏幕录制2021-06-24 下午5 00 03](https://user-images.githubusercontent.com/48018016/123240685-18142380-d513-11eb-846a-a95c8ae3673e.gif)

### Possible Solution

I guess it is caused by the canvas width multiplied by the resolution, so modify the code as follows

> packages/text/src/Text.ts
```
-        this.canvas.width = Math.ceil((Math.max(1, width) + (style.padding * 2)) * this._resolution);
-        this.canvas.height = Math.ceil((Math.max(1, height) + (style.padding * 2)) * this._resolution);
+        this.canvas.width = Math.ceil((Math.max(1, width) + (style.padding * 2))) * this._resolution;
+        this.canvas.height = Math.ceil((Math.max(1, height) + (style.padding * 2))) * this._resolution;
```

Just fixed🎉🎉🎉

### Steps to Reproduce

demo here: https://codesandbox.io/s/charming-framework-ckcf0?file=/src/index.ts

### Environment

- **`pixi.js` version**: 6.0.4
- **Browser & Version**: Chrome 91
- **OS & Version**: MacOS 10.15.7

**Comment by ShukantPal** [comment]
I made an additional reproduction since your sandbox link gives a 404: https://jsfiddle.net/ShukantPal/29Lz8xej/
