### ISSUE TITLE
Jest tests showing console.error related to WebGL and compressed textures v6.0.0+

### ISSUE THREAD

**Issue by mimshwright** [pixijs/pixijs#7554]
Since upgrading to v6.0.0 I'm seeing errors pop up in my Jest tests any time I import "pixi.js". 

Related repo: [pixi-tagged-text](https://github.com/mimshwright/pixi-tagged-text/pull/77)

### Current Behavior

Tests throw an error **WebGL not available for compressed textures. Silently failing.**

Sample test output:
```
 PASS  test/pixiUtils.test.ts
  ● Console

    console.error
      WebGL not available for compressed textures. Silently failing.

    > 1 | import * as PIXI from "pixi.js";
        | ^
      2 | import * as pixiUtils from "../src/pixiUtils";
      3 |
      4 | describe("pixiUtils", () => {

      at Function.Object.<anonymous>.CompressedTextureLoader.add (node_modules/@pixi/compressed-textures/src/loaders/CompressedTextureLoader.ts:171:21)
      at Function.Object.<anonymous>.Loader.registerPlugin (node_modules/@pixi/loaders/src/Loader.ts:157:20)
      at Object.<anonymous> (node_modules/pixi.js/src/index.ts:38:8)
      at Object.<anonymous> (test/pixiUtils.test.ts:1:1)
```

### Possible Solution

Not sure but here are some ideas:

- If it's possible, disable compressed textures or explicitly disable them through some option?
- Perhaps suppress these errors - either through some option or by making them real errors that require a try/catch block? 
- Find a better mock for the Canvas (currently using `canvas` package) or some other tweak to my node setup

If there is a standard way to test pixi elements using node-based tools, please point me in that direction. Maybe there is interest to add this to the official docs if it's not already.

### Steps to Reproduce

Check out latest code from [this pull request](https://github.com/mimshwright/pixi-tagged-text/pull/77) and run `yarn test`.  

### Environment

- **`pixi.js` version**: 6.0.4
- **Browser & Version**: node 16.2.0
- **OS & Version**:  MacOS 11.4
- **Running Example**: https://github.com/mimshwright/pixi-tagged-text/pull/77
- **Relevant packages**: "jest": "^26.6.3", "ts-jest": "^26.5.6", "canvas": "^2.8.0", "jsdom": "^16.6.0",
- **Jest Config**: 
```
module.exports = {
  preset: "ts-jest",
  testEnvironment: "jsdom",
};
```

**Comment by ShukantPal** [comment]
You can use [floss](http://www.cse.chalmers.se/~uffe/xjobb/BrushPaintingAlgorithms.pdf), although that uses mocha underneath the hood. If you do not want to move away from Jest, you can try integrating with [gl](https://www.npmjs.com/package/gl) so that WebGL available in Node.

**Comment by mimshwright** [comment]
@ShukantPal , good suggestions! I've just spent about an hour trying to make this work with `gl` or `node-webgl` but so far have been unsuccessful. 

I will consider switching over to floss but I have about 500 assertions written already. I wonder if it might even  be easier to fork floss and add Jest support maybe?

**Comment by bigtimebuddy** [comment]
@ShukantPal What do you think about making this `warn` or `info` instead of `error`? It's confusing as an `error`. If we're hitting this point it usually means the context we're running in doesn't contain WebGL, as in this case with `jsdom`. Seems reasonable.

https://github.com/pixijs/pixijs/blob/3ec6e7e6d68bb70bc9c55b24d8bdf327bba1e523/packages/compressed-textures/src/loaders/CompressedTextureLoader.ts#L168-L175

**Comment by ShukantPal** [comment]
Sure
