### ISSUE TITLE
Best way to use Graphics for large quantity of polygons that move/rotate

### ISSUE THREAD

**Issue by cookieJarYum** [pixijs/pixijs#7560]
Hello I am new to Pixi.js and Github, I am simulating a group of 1000+ regular polygons of static size/shape/color (# sides <= 11) that rotate and move with high frequency in small clusters. Each polygon moves/rotates independently even within the cluster. I am currently instantiating one Graphics object per polygon and after using drawPolygon once in the setup function, and I update the x/y/rotation fields of each Graphics object each tick

Is there a better way to do this? I thought maybe I could use one Graphics object to manage everything but I am unsure if this is possible while rotating/moving every single polygon independently

I tried using one ParticleContainer per cluster but ParticleContainer does not accept Graphics children; this issue https://github.com/pixijs/pixijs/issues/4315 mentioned there may be other optimizations possible

- **`pixi.js` version**: 5.04
- **Browser & Version**: latest chrome
- **OS & Version**:  win 10, latest

**Comment by ivanpopelyshev** [comment]
You can re-use graphics geometry, `new Graphics(graphics1.geometry)` that'll be a little faster. however you need to switch off batching for this.

Instanced renderer for graphics with same geometry is definitely a thing, i know that several people coded it for their projects but no one shared. 

> Is there a better way to do this?

Draw each cluster with mesh-shader.
