### ISSUE TITLE
Canvas2D renderer faster than WebGL for sprites?

### ISSUE THREAD

**Issue by mudcube** [pixijs/pixijs#7565]
### Expected Behavior

WebGL rendering would be faster than Canvas2D

### Current Behavior

Canvas2D appears faster than WebGL rendering.

I'm noticing ~21FPS on WebGL and ~32FPS on Canvas2D
My friend is noticing ~22FPS on WebGL and ~45FPS on Canvas2D

### Steps to Reproduce

1. Visit the following demo:  https://codepen.io/mudcube/pen/RwVNvLb
2. See benchmark FPS on top left of screen.
3. Toggle `forceCanvas` to true (at top of demo), and repeat step two.

### Environment

- **`pixi.js` version**: 5.3.10
- **Browser & Version**: 91.0.4472.114 
- **OS & Version**: MacOS Big Sur 11.4
- **Running Example**: https://codepen.io/mudcube/pen/RwVNvLb

**Comment by photonstorm** [comment]
Absolutely no difference for me, both run at 55fps (iMac M1, Chrome)

**Comment by ivanpopelyshev** [comment]
remove "antialias:true" and repeat.

**Comment by themoonrat** [comment]
With 10000 rather than 1000 (to push this PC)
28fps canvas
42fps webgl

You've also got antialiasing on, which does nothing on canvas but can be a strain on some hardware for WebGL

**Comment by mudcube** [comment]
Thanks for the suggestions!  I've updated the demo with `antialias: false` by default. 

I tried `antialias: false` and am seeing:  24FPS WebGL and 32FPS Canvas

I tried `antialias: false` with `10000` sprites and am seeing:  3FPS WebGL and 4FPS Canvas

Could this have to do with my platform or GPU?

**Comment by ryanreece** [comment]
With `antialias: false`, I get a consistent 45 FPS on both Canvas and WebGL.

With `antialias: true`, I get 22 FPS on WebGL and 45 FPS on Canvas.

It seems like @themoonrat's comment regarding strain on some hardware when using antialias with WebGL is accurate for me.

My specs: 2019 MacBook Pro, 2.4 GHz i9, 32 GB RAM, Radeon Pro Vega 20 4GB.

**Comment by eXponenta** [comment]
In real world this is fully random.

I have a lot of devices with different browsers and all results looks like random, with deviations ~10% between results.

**Comment by GoodBoyDigital** [comment]
I believe this is a fill rate issue. Canvas and WebGL are likely going to behave roughly the same as nothing too complex is happening for either to really shine. 

The objects are just massive :) so there is loads of pixels being written - which is a GPU bottleneck. In then end the Canvas + WebGL hitting the same GPU issue here and so both slowing down in roughly the same way

I bet if you make those elements smaller - you will start to see differences in perf.

**Comment by mudcube** [comment]
I created a new test with smaller elements, and 10,000 sprites, and WebGL definitely had the advantage!

Closing this issue, as it sounds like this is a non-issue, due to my graphics card, and Sprite being a feature which has similar parity between implementations.  Thanks again for all the great comments / suggestions :)
