### ISSUE TITLE
mask alpha make the page blinking

### ISSUE THREAD

**Issue by iaiayou** [pixijs/pixijs#7580]
In a high performance computer, set mask.alpha value by more than 2 decimal places，makes the page blinking.
eg: mask.alpha = 0.001. (page blinking)
eg: mask.alpha = 0.01. (this is ok)

**Comment by eXponenta** [comment]
Please, provide a FULL working demo and hardware/software info.

If you cannot reproduce on all devices - record a video

OS, Browser, GPU Info from chrome://gpu/

**Comment by ivanpopelyshev** [comment]
Yes, that's very strange thing I hear for the first time. Need reproduction.

**Comment by iaiayou** [comment]
> Please, provide a FULL working demo and hardware/software info.
> 
> If you cannot reproduce on all devices - record a video
> 
> OS, Browser, GPU Info from chrome://gpu/

’VGA Drivers 27.21.14.5256‘ the version I used before, made the page blinking.
There are two ways to solve this problem:
1. chrome: Disable hardware acceleration mode
2. update VGA Drivers

**Comment by ivanpopelyshev** [comment]
If its pixi-v5, it uses `transparent:false` by default, in v6 its `transparent:true`. the type of renderbuffer format, RGB or RGBA , actually can affect rendering backend bugs that depend on hardware.

**Comment by eXponenta** [comment]
> > Please, provide a FULL working demo and hardware/software info.
> > If you cannot reproduce on all devices - record a video
> > OS, Browser, GPU Info from chrome://gpu/
> 
> ’VGA Drivers 27.21.14.5256‘ the version I used before, made the page blinking.

Please, follow this steps:
1. Open chrome and write `chrome://gpu`
2. Click `copy to clipboard`
3. Open notepad and past to it
4. Save file as `report.html`
5. Attach to reply on this comment
6. Profit!

This is MUST BE  included when there are a device specific bug.

**Comment by iaiayou** [comment]
@eXponenta
[report.txt](https://github.com/pixijs/pixijs/files/6778411/report.txt)

**Comment by eXponenta** [comment]
Nothing strange, should be ok.

Can you create simple demo and record video how this is reproduced?

**Comment by iaiayou** [comment]
> Nothing strange, should be ok.
> 
> Can you create simple demo and record video how this is reproduced?


https://user-images.githubusercontent.com/44062370/124797719-2b98a300-df85-11eb-91c2-0bedc1e3ab7a.mov
