### ISSUE TITLE
getProgramParameter makes PixiJS slow in a product env

### ISSUE THREAD

**Issue by arrowzheng** [pixijs/pixijs#7583]
### Current Behavior
![image](https://user-images.githubusercontent.com/52522758/124902342-6a763980-e015-11eb-8f7c-b552d109264f.png)
getProgramParameter cost 4.9ms 

### Possible Solution
do not call getProgramParameter in a product env
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices
![image](https://user-images.githubusercontent.com/52522758/124901870-fc317700-e014-11eb-8b32-08a7ef06b36c.png)

### Environment

- **`pixi.js` version:6.0.4 on npm
- **Browser & Version**: _e.g. Chrome 91.0.4472.114
- **OS & Version**: _e.g. macOS big sur 11.4

**Comment by ivanpopelyshev** [comment]
That should be called only one time, do you happen to see multiple calls of it from Graphics?

**Comment by eXponenta** [comment]
There are not way to remove `getProgramParameter`, it always will be presented, because need to validate attribute/uniform types and indexes and grab binding locations.
For different drivers shader parameters is different.

**Comment by arrowzheng** [comment]
> That should be called only one time, do you happen to see multiple calls of it from Graphics?

it is called only one time

**Comment by arrowzheng** [comment]
> There are not way to remove `getProgramParameter`, it always will be presented, because need to validate attribute/uniform types and indexes and grab binding locations.
> For different drivers a shader parameters is different.
> 
> Anyway `getProgramParameter` will be called once for every shader, if it callings multiple time per program - this js bug.

it is not called multiple time, only once

**Comment by ivanpopelyshev** [comment]
> it is not called multiple time, only once

draw single Graphics before you actually show the program to user. No way to get rid of that :(

**Comment by ivanpopelyshev** [comment]
Also, most probably that thing is just waits for shader to compile. You'll have to wait that time before first frame anyway, whether its sync or async way.

**Comment by ShukantPal** [comment]
I think we can close this - feel free to reopen if needed. The `getProgramParameter` call shouldn't be a performance concern since it's called once during initialization.
