### ISSUE TITLE
Scalemode not fixed?

### ISSUE THREAD

**Issue by Coder2195Text** [pixijs/pixijs#7606]
### Expected Behavior
The scalemode to pixi nearest to work
### Current Behavior
Still does texture bleed
### Steps to Reproduce
Use a texture sheet with no padding between the img 
### what I have tried
I told my friend @giilbert, he saids this was a issue about 5 years ago, and it seems like it hasn’t been fixed
- **`pixi.js` version**: 6.0.2
- **Browser & Version**: Chrome 89
- **OS & Version**:  Chrome OS
- **Running Example**: N/A

**Comment by Coder2195Text** [comment]
So scale mode is no longer available in settings?

**Comment by ivanpopelyshev** [comment]
Its available in settings. 

Actually `no padding between the img` - scaleMode wont save you :( 

Either
1. make a padding
2. make custom shader that does clamping inside.

2 is actually easy when you know how to make mesh-shader or hack AbstractBatchRenderer, parts of code can be taken from TilingSprite or pixi-tilemap plugin. However, so far no one actually published it in public. Do you want to request this feature?

**Comment by bigtimebuddy** [comment]
This works before loading any textures:

```js
PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;
```

Example: https://pixijs.io/examples/#/interaction/click.js

**Comment by Coder2195Text** [comment]
Sure I want to request the feature

**Comment by Coder2195Text** [comment]
> This works before loading any textures:
> 
> ```js
> PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;
> ```
> 
> Example: https://pixijs.io/examples/#/interaction/click.js

This is only one texture, I want to work with a texture sheet

**Comment by bigtimebuddy** [comment]
Oh I understand now. Why not use padding?

**Comment by Coder2195Text** [comment]
Padding is fine, but when making skins for my game, you don’t want to go, “PLEASE USE 1 BORDER OF PADDING WITH EACH PART” that’ll just make it more difficult for the skin maker

**Comment by Coder2195Text** [comment]
You don’t expect your gamers to have such complicated rules making skins do you?

**Comment by bigtimebuddy** [comment]
@Coder2195Text could you please provide an example of this issue?

**Comment by Coder2195Text** [comment]
I’m making paper TS Craft and it’s in the planning stage right now
A prior experience with no padding texture sheet made me realize that adding customized skins more difficult for the user as he has to do everything exactly 1 pixel padding

**Comment by giilbert** [comment]
Just make a template of the skin (and generate the spritesheet.json)
... plus the 1px padding

Then the average player can modify the skin only changing the places where the template is colored.

The positions of the different pieces didn't change, only the textures of the different pieces did.

So, the average player wont have to mess with spritesheets.

![illustration](https://user-images.githubusercontent.com/40220369/125854684-69954356-a324-4fe9-a10f-1ecd89a675ba.png)

**Comment by Coder2195Text** [comment]
I’d like a more compact way like Minecraft

**Comment by ivanpopelyshev** [comment]
If you supply them with spritesheet for reference sheets - its possible.

If you want to pirate rpgmaker skins - nope, need to make a shader :) Do you want to place a bounty on this issue?

**Comment by Coder2195Text** [comment]
What do you mean bounty?

**Comment by giilbert** [comment]
> I’d like a more compact way like Minecraft

The 1px padding will:
1. Make the skin creator more visibly see where each body part start and end
2. Save you from having to write a shader to color the body parts correctly (@\ivanpopelyshev's possible solution) or update the texture inside the GPU (@\bigtimebuddy's solution)

And:
- its literally a couple more bytes of storage space and memory

**Comment by miltoncandelero** [comment]
> What do you mean bounty?

You offer a monetary bounty (reward) for somebody solving your problem (e.g. writing a shader that clamps).

**Comment by Coder2195Text** [comment]
I want to try that clamping solution
How do you do it?

**Comment by Coder2195Text** [comment]
Nah I don’t have money

**Comment by ivanpopelyshev** [comment]
> I want to try that clamping solution
> How do you do it?

with batching or without? How many sprites on screen you have with that shader?

Here's triangle: https://pixijs.io/examples/#/mesh-and-shaders/triangle-textured.js 
but you need a quad: https://pixijs.io/examples/#/mesh-and-shaders/shadertoy-mesh.js
and you have to pass texture matrix there: https://github.com/pixijs/pixijs/blob/d298eb8fc3ab2c5fc8a1bf62238b09af772ba776/packages/sprite-tiling/src/TilingSpriteRenderer.ts#L136 - Do it in mesh update, dont forget to create that texture matrix if it doesnt exist, creation is also somewhere in that function

Here's a clamp in shader: https://github.com/pixijs/pixijs/blob/d298eb8fc3ab2c5fc8a1bf62238b09af772ba776/packages/sprite-tiling/src/tilingSprite.frag#L12-L13 , pass uMapCoord uniform 

=====

Actually, there's an easy way. pixi-heaven already have clamp in mesh, though its not clamping - its discarding. You can take its fragment shader, change discard to clamp, pass it to 

https://github.com/pixijs/pixi-heaven/blob/master/src/twotint/mesh/MeshH.ts
