### ISSUE TITLE
TextMetrics crashes when fontSize  is equal to 0

### ISSUE THREAD

**Issue by miltoncandelero** [pixijs/pixijs#7607]
When setting the `fontSize` of a `Text` to 0, `TextMetrics` crashes with a dom exception.

Granted, a `fontSize` of 0 might fall into the _unspecified behavior_ territory so I am not entirely sure if this is a bug or not.

---

### Expected Behavior
Not to crash

### Current Behavior
**Chrome:**
- Uncaught DOMException: Failed to execute 'getImageData' on 'OffscreenCanvasRenderingContext2D': The source width is 0.

**Firefox:**
- Uncaught DOMException: Index or size is negative or greater than the allowed amount

### Possible Solution
(I don't have the time to dig deeper into the cause of this right now 😬 )

### Steps to Reproduce
Create a text and set the `style.fontSize` to zero.
https://www.pixiplayground.com/#/edit/9Wo5tD7Wp_W9P2wzGw6OT

### Environment

- **`pixi.js` version**: 5.x ~ 6.x
- **Browser & Version**: Chrome  & Firefox
- **Running Example**: https://www.pixiplayground.com/#/edit/9Wo5tD7Wp_W9P2wzGw6OT

**Comment by bigtimebuddy** [comment]
We've had numerous similar issues (e.g., #6321, #6748), and this is undefined behavior. `fontSize` should be greater than zero. A value of zero, Infinity, NaN, etc wouldn't be reasonable to handle internally.
