### ISSUE TITLE
Link to Guides in docs

### ISSUE THREAD

**Issue by domis86** [pixijs/pixijs#7617]
Those guides seems useful: https://github.com/pixijs/guides/tree/main/docs ( https://pixijs.io/guides )
but there is no link to them in pixi.js docs - at least i cant find such link.
IMO it should be linked somwhere - for example in "Learn" part: https://github.com/pixijs/pixijs#learn

**Comment by bigtimebuddy** [comment]
You're right! The guides project is newer and hasn't been linked anywhere yet, but these are all great suggestions.

**Comment by skirianov** [comment]
This one should be easy! Can I get it done?
