### ISSUE TITLE
Graphics drawn with `lineTo()` are not calculated for interaction events if their parent is not renderable

### ISSUE THREAD

**Issue by ericente** [pixijs/pixijs#7620]
### Expected Behavior
Interaction calculations for Graphics should have the same results regardless of how they were drawn. Graphics drawn with `moveTo()` and `lineTo()`, should be used to calculate area for interaction events, even when their parent has alpha=0 or renderable=false.

### Current Behavior
Graphics drawn with `moveTo()` and `lineTo()`, when inside of a Container with alpha=0, or renderable=false are not recognized for interaction events.

Graphics drawn with `drawPolygon()`, `drawRect()`, etc are still calculated for interaction events when their parent Container has alpha=0 or renderable=false.

### Possible Solution
Calling `finishPoly()` after `closePath()` resolves the issue, but this should not be required.

### Steps to Reproduce
Example with correct behavior:
```
var graf = new PIXI.Graphics();
graf.beginFill(0x000000, 1);
graf.drawPolygon([20, -91, -21, -91, -21, 91, 20, 91, 20, -91]);

var cont = new PIXI.Container();
cont.x = 100;
cont.y = 100;
cont.addChild(graf);

cont.interactive = true;
cont.cursor = 'pointer';
cont.renderable = false;
app.stage.addChild(cont);
```

Example with incorrect behavior:
```
var graf = new PIXI.Graphics();
graf.beginFill(0x000000, 1);
graf.moveTo(20, -91);
graf.lineTo(-21, -91);
graf.lineTo(-21, 91);
graf.lineTo(20, 91);
graf.lineTo(20, -91);
graf.closePath()

var cont = new PIXI.Container();
cont.x = 100;
cont.y = 100;
cont.addChild(graf);

cont.interactive = true;
cont.cursor = 'pointer';
cont.renderable = false;

app.stage.addChild(cont);
```

### Environment

- **`pixi.js` version**: 6.0.4
- **Browser & Version**: Chrome 91.0.4472.114
- **OS & Version**: Mac OS X 10.15.6
- **Running Example**: https://www.pixiplayground.com/#/edit/gGVCwRaSp6Adi3RPUV39B

**Comment by eXponenta** [comment]
This is because when you not close Graphics shape - it still is `wait` state until render.
render automatically call `finishPoly`.

**Comment by ivanpopelyshev** [comment]
Yep, and that's the problem, its not finishing if `alpha=0`, and i dont know what to do about that. Should `containsPoint` finish it automatically?

**Comment by andrewstart** [comment]
Calling `finishPoly` in `closePath` sounds like the best solution, as I can't think of a reason where you wouldn't want to finish your polygon any time that it is called.
