### ISSUE TITLE
Capturing texture from video element results in slight stuttering

### ISSUE THREAD

**Issue by fairbairn** [pixijs/pixijs#7624]
### Expected Behavior

Was hoping we could capture a texture live from a video source element and it render the same as a native video element.

### Current Behavior

Pixi performs great overall, but in comparing the display of a `<video>` element with a stock src (mp4 file) on playback, vs rendering a Sprite with a Texture generated from the video source using Pixi, we've noticed that there is a slight stutter in the Pixi playback.  It's slight, but noticeable.  

From a visual analysis, it appears that it hiccups about every second, but that's just a visual approximation.  When it does hiccup, it appears to lose several frames.

The `<video>` element displayed shows no stutter at all.  Perfectly smooth, so wondering if the timing or capturing priority is potentially an issue.  The source we're using is 1280x720 at 30fps.

### Possible Solution

We tried the obvious options, namely altering the updateFPS on the Texture creation, but it didn't produce a change.  We also tried forcing canvas mode vs webgl mode, but got the same results.

### Steps to Reproduce

Our configuration is pretty basic...
```

        this.app = new PIXI.Application({
            view: this.stage_canvas.current,
            forceCanvas: false,
            backgroundAlpha: 0,
            resizeTo: this.pixi_canvas_container.current,
            autoResize: true
        });

        let resource1 = new PIXI.VideoResource(this.video_source1.current, {updateFPS: 30});
        this.texture1 = new PIXI.Texture.from(resource1);

        this.sprite1 = new PIXI.Sprite(this.texture1);

        this.app.stage.addChild(this.sprite1);
.
.
.
```
This content is in the body of the DOM... we're using React, so pulling out the element here.
```
<video ref={this.video_source1} style={video_canvas} loop={true} src="/media/videos/matrix5.mp4" autoPlay={true} muted={true} />

```

Not much to it.  The content doesn't seem to matter.  We've tried multiple videos.  What we did not try is a video that does not have an audio stream in it, but that would not be applicable to our use-case.

### Environment

        "pixi.js": "^6.0.4",

Chrome Version 91.0.4472.164
Mac OS/X Big Sir

**Comment by bigtimebuddy** [comment]
The hiccup sounds like a classic garbage collection issue. I would suggest you to profile the memory in devtools to verify. 

Also, could you provide a running example using live video? It's hard to tell without having something to debug. That code snippet is not enough information.
