### ISSUE TITLE
Multisample to generateTexture doesn't work without blit

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixijs#7628]
Related to #7440 

That PR adds a multisample parameter to `generateTexture` on AbstractRenderer, however, it does not render without calling `blit`. This seems like a bad API choice, and we should handle the blit within `generateTexture`.

Works: https://jsfiddle.net/bigtimebuddy/ftd2caj9/
Doesn't work: https://jsfiddle.net/bigtimebuddy/1wmp06na/

@dev7355608 could you fix this?

**Comment by dev7355608** [comment]
Technically the blit is missing in `Renderer.render`, but, if I remember it correctly, @ivanpopelyshev wanted it this way. Not sure, if `generateTexture` should get it then, or if it's always the responsibility of the user to manually call the final blit.

**Comment by bigtimebuddy** [comment]
`generateTexture` is largely a convenience function, it's rolls up the bounds and RenderTexture stuff to make it easier on users. My expectation is that this high-level function should handle the blit, which is probably pretty easy because we can check for multisample. I understand not wanting to put it in `render`, but we'll see what @ivanpopelyshev says.

**Comment by ivanpopelyshev** [comment]
`generateTexture` should do the blit.
