### ISSUE TITLE
@pixi/events fires pointerout right before pointerover

### ISSUE THREAD

**Issue by miltoncandelero** [pixijs/pixijs#7638]
Playing arround with the new events I found something interesting. A `pointerout` event gets fired right before the `pointerover` event

### Expected Behavior
- To fire only `pointerover`

### Current Behavior
- `pointerout` fires when entering an object, right before `pointerover`

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/SDTzsalMJlbizKIcAWFS1

### Environment

- **`pixi.js` version**: 6.1.0-rc.5
- **`@pixi/events` version**: 6.1.0-rc.5
- **Browser & Version**: Chrome
- **Running Example**: https://www.pixiplayground.com/#/edit/SDTzsalMJlbizKIcAWFS1

---

I don't know if `@pixi/events` is receiving issues yet, I'm sorry if not 😅

**Comment by ShukantPal** [comment]
I'm in mobile so couldn't test the playground. I wanted to point out that pointer over/ out events now bubble. This matches the Pointer Events API used in the DOM. As such, if you move the pointer from child to parent element, for example, this is the intended behavior.

The target on the events should be different.

**Comment by ShukantPal** [comment]
pointer enter / leave events don't bubble so they might be what you are looking for.

**Comment by miltoncandelero** [comment]
I might have jumped to conclusions
Closing this and doing my homework next time 😅
