### ISSUE TITLE
Render upside down in Safari gets fixed in Pixi v6 but not in Pixi v5

### ISSUE THREAD

**Issue by Feifan17** [pixijs/pixijs#7640]
### Expected Behavior
the screenshot of canvas doesn't get flipped in pixi v5 when using Safari with WebGL.

### Current Behavior
When using pixi v5, the screenshot of canvas gets flipped in Safari. However, if switching to pixi v6, the screenshot is displayed correctly. In both cases, the WebGL renderer is used.

### Steps to Reproduce
1. open the following example in Safari and test it using both pixi v5 and pixi v6 with WebGL enabled:
[https://www.pixiplayground.com/#/edit/iCvjart4azj1COVJD-7Sn](https://www.pixiplayground.com/#/edit/iCvjart4azj1COVJD-7Sn)。

2. check the screenshot using Safari developer tools (JS console -> Canvas):

pixi v5 shows the following flipped screenshot:
<img width="429" alt="pixi v5" src="https://user-images.githubusercontent.com/31830203/126896026-465fec3d-99e8-4166-97d0-ba0853fd1107.png">

whereas pixi v6 shows the correct one:

<img width="147" alt="pixi v6" src="https://user-images.githubusercontent.com/31830203/126896467-b01cedec-15be-4f5f-a23f-6912750a2819.png">

I am curious to know what kind of changes has pixi v6 made to fix this bug? Any help would be much appreciated!

### Environment

- **`pixi.js` version**: 5.4.0
- **Browser & Version**: _e.g. Safari 13.1.3_
- **OS & Version**: _e.g. MacOs Catalina 10.15.7
- **Running Example**: [https://www.pixiplayground.com/#/edit/iCvjart4azj1COVJD-7Sn](https://www.pixiplayground.com/#/edit/iCvjart4azj1COVJD-7Sn)。

**Comment by ShukantPal** [comment]
<img width="634" alt="Screen Shot 2021-07-25 at 8 59 23 PM" src="https://user-images.githubusercontent.com/22450567/126919798-d164ebb9-f479-4569-b91e-5cd3afefb4aa.png">

The playground link you posted doesn't have any code that takes a "screenshot". Did you forget to save it?

**Comment by Feifan17** [comment]
> <img alt="Screen Shot 2021-07-25 at 8 59 23 PM" width="634" src="https://user-images.githubusercontent.com/22450567/126919798-d164ebb9-f479-4569-b91e-5cd3afefb4aa.png">
> I simply use the Safari developer tools to examine the screenshot. So if you go to the JS console in Safari, select the `Canvas` tab and find the corresponding canvas that renders our stage, you should see the stage gets vertically flipped.
> The playground link you posted doesn't have any code that takes a "screenshot". Did you forget to save it?

**Comment by eXponenta** [comment]
> > <img alt="Screen Shot 2021-07-25 at 8 59 23 PM" width="634" src="https://user-images.githubusercontent.com/22450567/126919798-d164ebb9-f479-4569-b91e-5cd3afefb4aa.png">
> 
> > The playground link you posted doesn't have any code that takes a "screenshot". Did you forget to save it?
> 
> I simply use the Safari developer tools to examine the screenshot. So if you go to the JS console in Safari, select the `Canvas` tab and find the corresponding canvas that renders our stage, you should see the stage gets vertically flipped.

This is not a bug, this is Safari case, i not think that this possible to solve in v5 without extra checks.

**Comment by Feifan17** [comment]
> > > <img alt="Screen Shot 2021-07-25 at 8 59 23 PM" width="634" src="https://user-images.githubusercontent.com/22450567/126919798-d164ebb9-f479-4569-b91e-5cd3afefb4aa.png">
> > 
> > 
> > > The playground link you posted doesn't have any code that takes a "screenshot". Did you forget to save it?
> > 
> > 
> > I simply use the Safari developer tools to examine the screenshot. So if you go to the JS console in Safari, select the `Canvas` tab and find the corresponding canvas that renders our stage, you should see the stage gets vertically flipped.
> 
> This is not a bug, this is Safari case, i not think that this possible to solve in v5 without extra checks.
I have been testing v5 and v6 using the same version of Safari. Since the results I obtained are different, I guess it might be the case that v6 did something to make the problem go away? If so, I would like to know where I can find this change.

**Comment by ivanpopelyshev** [comment]
what about `transparent:true` by default ? Its enabled in v6, disabled in v5

**Comment by eXponenta** [comment]
This is Safari bug
https://trac.webkit.org/changeset/279424/webkit/
