### ISSUE TITLE
Support for Adobe Animate Atlas

### ISSUE THREAD

**Issue by animald** [pixijs/pixijs#7644]
I was disheartened to find a stale issue regarding this from 2018... #4273

It's now 2021, please tell me someone has cracked this and found a way to use Adobe Animate atlas animations within Pixi?

**Comment by miltoncandelero** [comment]
I think the biggest problem is that there is no docs on how the json works. I even remember Adobe changing the name of the keys in the json to one letter in order to "minify" the json 🤔🤦‍♀️

**Comment by bigtimebuddy** [comment]
We have our own support for Animate with a custom extension. This is not Atlas, but will allow you to export content for Pixi.

Runtime: https://github.com/pixijs/pixi-animate
Animate Extension: https://github.com/pixijs/pixi-animate-extension
