### ISSUE TITLE
Totally random "ReferenceError: self is not defined" in "isMobile.ts" during tests

### ISSUE THREAD

**Issue by hood** [pixijs/pixijs#7657]
### Expected Behavior
Tests should run fine

### Current Behavior
A totally normal test (I have many more similar tests set up using `tap` in the same codebase running smoothly) triggers a `ReferenceError: self is not defined` error in `@pixi/settngs/utils/isMobile.ts` despite the code in the test not even referring to PIXI at all.

### Possible Solution
No idea whatsoever.

### Steps to Reproduce
No idea whatsoever.

### Environment
- **`pixi.js` version**:  6.0..4
- **Browser & Version**:  Chrome 92
- **OS & Version**:  Linux arch 5.13.5-arch1-1

**Comment by bigtimebuddy** [comment]
Can you please provide a reproduction?

**Comment by hood** [comment]
I'm encountering this issue in a private personal project. I can invite you to the repo if it can help.

**Comment by bigtimebuddy** [comment]
We are a small team of volunteers that maintain Pixi and do not have the ability to provide support to debug other peoples projects. It is more useful if you can make a minimal example the reproduces the issue. We need to establish that this is a Pixi issue and not a project-specific or third-party tooling issue. A repro is the best way to do that.
