### ISSUE TITLE
Texture rotate property doesn't work as expected

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixijs#7658]
### Expected Behavior
Texture rotate property to function as expected

### Current Behavior
Having two different sprites with two different textures. Setting one of the textures to rotate = 8 makes the other texture (in the other sprite) to also rotate.

### Steps to Reproduce
```javascript
let logo1 = app.stage.addChild(new PIXI.Sprite(PIXI.Texture.from("assets/logo.png")))
logo1.position.set(10, 10)

let logo2 = app.stage.addChild(new PIXI.Sprite(PIXI.Texture.from("assets/logo.png")))
logo2.position.set(10, 100)
logo2.texture.rotate = 8 // This will also make logo1 to be flipped vertically
```

### Environment
PixiJS v5.3
Chrome 92
Mac OS

**Comment by a-c-sreedhar-reddy** [comment]
Both of them use the same texture. Can try setting angle to the sprite instead of rotation?

**Comment by jnsmalm** [comment]
They both use the same base texture, but not the same texture right?

**Comment by ivanpopelyshev** [comment]
I dont know how did you get `false` here, it should print `true`, because `from()` return the same. you have to `clone()` it.

**Comment by jnsmalm** [comment]
You are right, I must have done something and forgot to save before running it or something.

**Comment by jnsmalm** [comment]
In either case I though this was a problem with regular sprites, but it seems it isn't. My real problem is when I first render a sprite which has a render texture as a texture and I set that texture to rotate = 8. Then I create another sprite which uses a regular texture, that one gets rotated as well.

**Comment by ivanpopelyshev** [comment]
yes, because clone() does not reset rotation you already applied :)

**Comment by ivanpopelyshev** [comment]
You have to use clone() first time too

**Comment by jnsmalm** [comment]
But the rotation is set for a completely other texture (a render texture) - does rotate impact other regular textures? Is rotate like a global thing? Do you mean I should clone the render texture or regular texture? I use it like this:

```javascript
let sprite1 = app.stage.addChild(new PIXI.Sprite(PIXI.RenderTexture.create({ width:256, height:256 })));
sprite1.texture.rotate = 8

let sprite2 = app.stage.addChild(new PIXI.Sprite(PIXI.Texture.from("assets/logo.png")))
```

After this, sprite2 is rotated as well, is that expected?

**Comment by ivanpopelyshev** [comment]
No, that measn you have bug somewhere else in code that you dont share with me :) please post full or minimal demo

**Comment by jnsmalm** [comment]
Yes, probably did wrong somewhere. I'll try to find another solution for it. Thanks.
