### ISSUE TITLE
Can i get PIXI.text text every letter position x,y?

### ISSUE THREAD

**Issue by lichspace** [pixijs/pixijs#7660]
Hi i need every letter pisiton to do some animation. 
i read the code, the Text.drawLetterSpacing have use the position.
please save it in a public variable.

**Comment by ivanpopelyshev** [comment]
Workaround. Make custom `updateText`:

```js
myText.updateText = function() { 
   //updateText code, but changed by you
   this.letterPositions = ...;
}
```

If you manage to do it, you can try make a PR to this repo, we'll look at it :)

**Comment by lichspace** [comment]
thankyou i try it~
