### ISSUE TITLE
TypeScript Node types "leak" into a project using PIXI with v6.1.0

### ISSUE THREAD

**Issue by qtiki** [pixijs/pixijs#7674]
### Expected Behavior

Adding PIXI to a TypeScript project should not add Node types to the project.

### Current Behavior

Node types are included from `@pixi/core` `index.d.ts` which contains the following line:
```ts
/// <reference types="node" />
```

The actual NPM package `@types/node` is not anywhere in the dependencies, so while the end result is similar to #7283 this is not a straight regression but seems to be a bit different issue this time.

### Possible Solution

Not sure why that line is added there nor which part of the build pipeline does it.

### Steps to Reproduce

Install the latest (6.1.0) `@pixi/core` package to a project and observe the `index.d.ts` contain the node type reference.

### Environment

- **`pixi.js` version**: _6.1.0_

**Comment by bigtimebuddy** [comment]
This is in deed a bug. 

This was introduced in v6.1.0-rc (quite awhile ago). Here's the comparison of these two version, 6.0.4 doesn't have it.

[v6.1.0-rc](https://unpkg.com/@pixi/core@6.1.0-rc/index.d.ts) index.d.ts
[v6.0.4](https://unpkg.com/@pixi/core@6.0.4/index.d.ts) index.d.ts

There's probably something that was introduced here https://github.com/pixijs/pixijs/compare/v6.0.4...v6.1.0-rc that's adding implicit node types.

**Comment by bigtimebuddy** [comment]
I bisected and narrowed it to this commit https://github.com/pixijs/pixijs/commit/2c9275da55a866de6268ed5ebfefc0c8dd4868a8 from this PR: https://github.com/pixijs/pixijs/pull/7096

Calling @GoodBoyDigital
