### ISSUE TITLE
CanvasRenderer should not be a type dependency of accessibility and mixin-cache-as-bitmap

### ISSUE THREAD

**Issue by zz5840** [pixijs/pixijs#7683]
### Current Behavior
After commit 402ee9a has moved dependencies to peerDependencies, `@pixi/canvas-renderer` is only the dependency of `pixi.js-legacy` and will not be automatically installed by running `npm install pixi.js`. However `@pixi/accessibility` and `@pixi/mixin-cache-as-bitmap` are still using `PIXI.CanvasRenderer` as type.

https://github.com/pixijs/pixijs/blob/01a69a1465b875cb7b97a10caa9c35d9505397ff/packages/accessibility/src/AccessibilityManager.ts#L48
https://github.com/pixijs/pixijs/blob/01a69a1465b875cb7b97a10caa9c35d9505397ff/packages/mixin-cache-as-bitmap/src/index.ts#L29
https://github.com/pixijs/pixijs/blob/01a69a1465b875cb7b97a10caa9c35d9505397ff/packages/mixin-cache-as-bitmap/global.d.ts#L15

These error will not be reported when compiling typescript but running TypeDoc.

![image](https://user-images.githubusercontent.com/16662647/128637051-21e59976-74ac-4e72-ab54-3b859e272558.png)

### Steps to Reproduce
Run `typedoc`

### Environment

- **`pixi.js` version**: 6.1.1

**Comment by bigtimebuddy** [comment]
I agree, this is a bug. Thanks for pointing it out. cache-as-bitmap and accessibility should not require canvas-renderer.
