### ISSUE TITLE
From 6.1.0, Property 'name' does not exist on type 'Graphics'

### ISSUE THREAD

**Issue by famibee** [pixijs/pixijs#7685]
From version 6.1.0, name property etc. will cause build error.
If you revert to version 6.0.4, no error will occur.

　バージョン 6.1.0 から、nameプロパティなどがビルドエラーになるようになった。
　バージョン 6.0.4 に戻せばエラーが発生しない。

TS2339: Property 'name' does not exist on type 'Graphics'.
<img width="332" alt="スクリーンショット 2021-08-09 08-09 月 09 39" src="https://user-images.githubusercontent.com/16816132/128651059-16d0a8e0-a2aa-42bb-b1aa-b9fae9461529.png">
<img width="751" alt="スクリーンショット 2021-08-09 08-09 月 09 39 1" src="https://user-images.githubusercontent.com/16816132/128651066-d6c56ef6-b382-44b3-928c-925c261db985.png">

 Similarly,
　同様に、
TS2339: Property 'name' does not exist on type 'DisplayObject'.
TS2339: Property 'name' does not exist on type 'Sprite'.
TS2339: Property 'interactiveChildren' does not exist on type 'Sprite'.
TS2339: Property 'interactive' does not exist on type 'Container'.
TS2339: Property 'buttonMode' does not exist on type 'Container'.

- **`pixi.js` version**: _e.g. 4.7.1_
- **VSCode & Version**: _e.g. 1.59.0_
- **Node.js & Version**: _e.g. 14.16.0_
- **OS & Version**: _e.g. macOS Big Sur 11.5.1_
- **Running Example**: _url_

**Comment by miltoncandelero** [comment]
Are you using `pixi.js` or are you manually importing the `pixi/*` packages? You night need the `getChildByName` mixin

**Comment by famibee** [comment]
using...
npm i -S pixi.js
import {Sprite, DisplayObject, Graphics, Container, Renderer} from 'pixi.js';

What is the method getChildByName? There is no description in the manual, and I don't want to get a child.
getChildByName というメソッドはなんですか？　マニュアルにも記載がないですし、子を取得したいわけでもありません。
- https://pixijs.download/v6.1.1/docs/PIXI.DisplayObject.html

**Comment by ivanpopelyshev** [comment]
Most probabyl two pixies in node_modules again. Do you have any plugins there, like `pixi-spine` ?

**Comment by famibee** [comment]
Thank you for your support!
対応ありがとうございます！

- package.json
	"dependencies": {
		"@pixi/sound": "^4.0.4",
		"@tweenjs/tween.js": "^18.6.4",
		"devtools-detect": "^3.0.1",
		"electron-store": "^8.0.0",
		"fs-extra": "^10.0.0",
		"gamepad.js": "^1.0.4",
		"moveable": "^0.26.0",
		"parsimmon": "^1.18.0",
		"pixi.js": "^6.0.4",
		"platform": "^1.3.6",
		"socket.io-client": "^4.1.3",
		"store": "^2.0.12",
		"tar-fs": "^2.1.1",
		"xml2js": "^0.4.23"
	},
	"devDependencies": {
		"@semantic-release/changelog": "^5.0.1",
		"@semantic-release/git": "^9.0.0",
		"@types/electron-json-storage": "^4.5.0",
		"@types/fs-extra": "^9.0.12",
		"@types/mocha": "^9.0.0",
		"@types/node": "^16.4.13",
		"@types/parsimmon": "^1.10.6",
		"@types/platform": "^1.3.4",
		"@types/store": "^2.0.2",
		"@types/tar-fs": "^2.0.1",
		"@types/xml2js": "^0.4.9",
		"electron": "^13.1.8",
		"mocha": "^9.0.3",
		"power-assert": "^1.6.1",
		"semantic-release": "^17.4.4",
		"ts-loader": "^9.2.5",
		"ts-node": "^9.1.1",
		"typescript": "^4.3.5",
		"webpack": "^5.49.0",
		"webpack-cli": "^4.7.2",
		"webpack-dev-server": "^3.11.2"
	},

Is there a problem with the combination of [pixi.js] and [@pixi/sound]?
　もしかして【pixi.js】と【@pixi/sound】の組み合わせに問題があるのでしょうか？

**Comment by bigtimebuddy** [comment]
I was unable to reproduce using this. 

### package.json

```json
{
  "name": "pixi-name-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "tsc"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@pixi/sound": "^4.0.4",
    "pixi.js": "^6.1.1"
  },
  "devDependencies": {
    "typescript": "^4.3.5"
  }
}
```

### tsconfig.json

```json

{
  "compilerOptions": {
    "outDir": "./dist/",
    "noImplicitAny": true,
    "sourceMap": true,
    "module": "ESNext",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "target": "es5",
    "esModuleInterop": true
  },
  "include": [
    "src/*.ts"
  ]
}
```

### src/index.ts

```ts
import { Application, Graphics } from "pixi.js";

const app = new Application();
document.body.appendChild(app.view);

const shape = new Graphics();
shape.name = 'myname';

app.stage.addChild(shape);
```

Please provide a repro that reproduces this error. I suggest, like @ivanpopelyshev suggested, that you remove your lock and node_modules and try to npm install again.

**Comment by famibee** [comment]
Thank you for your continued reply.
　引き続きの回答ありがとうございます。

You can reproduce it with just three files!
Or rather, you can create a small project with just three files. From now on, I would like to show you how to reproduce it by the means you taught me.
　たった三ファイルで再現できるんですね！
　というか、たった三ファイルで小さなプロジェクトが作れるんですね。これからは教えていただいた手段で再現できる方法をお示ししたいと思います。

 The sample shown worked fine in this environment as well.
 However, the cause could be identified due to the difference from tsconfig.json in this project.
　お示しいただいたサンプルは、こちらの環境でも正常に動作しました。
　ただ、こちらのプロジェクトでの tsconfig.json との差異により、原因が特定できました。

//		"allowSyntheticDefaultImports": true,	// This
//		"esModuleInterop": true	// This

Reproduce by commenting out "allowSyntheticDefaultImports" and "esModuleInterop" in tsconfig.json.
　tsconfig.json 内の「allowSyntheticDefaultImports」と「esModuleInterop」をコメントアウトすると再現します。
<img width="1808" alt="スクリーンショット 2021-08-10 08-10 火 10 56 1" src="https://user-images.githubusercontent.com/16816132/128796716-aee830b2-8247-4ccf-bbbb-1854f44cf12d.png">


My project also got rid of the error with "" esModuleInterop ": true". (AllowSyntheticDefaultImports is unused)
Is it okay to say that this support is available from version 6.1.0?
　私のプロジェクトでも「"esModuleInterop": true」でエラーがなくなりました。（allowSyntheticDefaultImports は未使用）
　バージョン 6.1.0 からはこの対応、ということでよいでしょうか？


(postscript)
　（追記）
I have tried "lock and node_modules and try to npm install again" by @ivanpopelyshev several times. However, this is also reasonable to point out.
　@ivanpopelyshev さんに教えていただいた「 lock and node_modules and try to npm install again」は何度か試しております。ですがこちらも指摘ごもっともです。

**Comment by bigtimebuddy** [comment]
allowSyntheticDefaultImports and esModuleInterop are required for building With Pixi because it has external dependencies that cannot be bundled without it.

**Comment by famibee** [comment]
I understand this. Then I will correspond like that.
Thank you for your answers so far!
こちら了解です。それではそのように対応させて頂きます。
ここまでご回答、ありがとうございました！
