### ISSUE TITLE
SVG cropped when scaled

### ISSUE THREAD

**Issue by Apeopex** [pixijs/pixijs#7686]
When scaling an SVG before rasterization, it get's cropped. ~~if it exceeds the default canvas size.~~

I've come across the same issue listed here:

https://github.com/pixijs/pixijs/issues/6265#issuecomment-668159566

Demo: 
https://jsfiddle.net/ThievingSix/cr5fmxnL/66/

Uncomment line 5 for what may be a potential fix on this line:
https://github.com/pixijs/pixijs/blob/dev/packages/core/src/textures/resources/SVGResource.ts#L195

I'm not entirely sure why the original code doesn't work, since the width and height of the source image are accurate.

**Comment by eXponenta** [comment]
data-image can be used for this, because there are not easy way read width/height values.

**Comment by Apeopex** [comment]
Ah, that makes sense. I incorrectly assumed that the viewbox would be sufficient. Thank you
