### ISSUE TITLE
Should Ticker's listener be triggered in next tick?

### ISSUE THREAD

**Issue by huaguzheng** [pixijs/pixijs#7691]
As shown in the code below, if I switch back from other tabs, deltaTimeA will be very large, and deltaTimeB will always be the same as deltaTimeA.

```
app.ticker.add((deltaTimeA) => {
     console.log(deltaTimeA);
     app.ticker.addOnce((deltaTimeB) => {
          console.log(deltaTimeB);
     });
});
```

**Comment by bigtimebuddy** [comment]
This is working as intended. Tickers, when added, are added immediately (for the current frame). 

If you're expending addOnce to be the name frame you can wait for the next JS frame using setTimeout(func, 0), or setting addOnce (3rd param) to be a lower priority than the current ticker handler.
