### ISSUE TITLE
Update static canvas infinitely

### ISSUE THREAD

**Issue by YES-Lee** [pixijs/pixijs#7700]
### Expected Behavior
Don't update canvas when it is static.
### Current Behavior
Undate(re-render) every frame even if canvas is empty.
![image](https://user-images.githubusercontent.com/19748456/129171086-d14c9356-0825-4240-ad50-086be469b0c7.png)

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by eXponenta** [comment]
This is impossible.

You can only disable internal render loop, and runs it when required manually.


app.stop()
