### ISSUE TITLE
When use smooth graphic, the stroke color is displayed incorrectly

### ISSUE THREAD

**Issue by guoqiangmin** [pixijs/pixijs#7706]
Hi,

I wanted to display think stroke of shapes in drawing canvas using smooth graphic.
But it shows me wrong color when I set the line color with black, and it looks blurry.
I settled up the line width to 0.5, because compared fabric.js, pixi shows thicker border when I set 1px of line width.

Following screenshot is one of using Pixi
<img width="915" alt="Screen Shot 2021-08-16 at 15 03 35" src="https://user-images.githubusercontent.com/83385309/129561582-c23f9641-a7ef-411e-99fc-f8df65e8889d.png">

Below is showing fabric.js
<img width="1500" alt="Screen Shot 2021-08-16 at 15 10 32" src="https://user-images.githubusercontent.com/83385309/129561715-65d4950f-6d47-4ec1-8455-4727dac112ff.png">

### Expected Behavior
Show thin border with correct color when set the line width as 1px

### Current Behavior
It shows wrong color when set line color with black and set line width as 0.5 , and it looks blurry
When use normal graphic class, if I set the line width 0.5, the borders cut off.

### Steps to Reproduce
- Initialize smooth graphics (or graphics), 
- Drawing rectangle or any shape with 0.5px of line width, and black line color.

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment]
0.5 line width means its less than a pixel, how do you want it to be complete black?

**Comment by guoqiangmin** [comment]
Thanks for your reply. Yes, you're right. But at least, the 1px of border is thicker than normal canvas line width.
You can see the difference by comparing with fabric.js.
Here I've attached 2 screenshots. One is just for Pixi.js, and another one is drawing shape using fabricjs.
You can see how it looks different in same 1px border.

<img width="378" alt="Screen Shot 2021-08-16 at 15 22 43" src="https://user-images.githubusercontent.com/83385309/129563233-3016a466-afe0-4479-81b2-1875570c1871.png">
<img width="1500" alt="Screen Shot 2021-08-16 at 15 10 32" src="https://user-images.githubusercontent.com/83385309/129563246-d9f83742-b603-44cc-807b-7ff8bbc029bf.png">

**Comment by ivanpopelyshev** [comment]
This is the usual problem "how to draw a width=1 stroke". It goes between pixels.

canvas2d: https://jsfiddle.net/Hackerham/s6pvgjuL/6/ 

canvas2d but with stroke: https://jsfiddle.net/Hackerham/s6pvgjuL/4/

Because people dont know the details, that integer coords are corners of pixels, Fabric does something: its movos corners a bit.

Workaround: use lineAlignment 0 or 1 for usual pixi graphics or smooth, or use half-integer coords for rect corners.

If you have to use half-round coordinates, we need to add roundPixels in our Graphics, which is not there at the moment.

**Comment by guoqiangmin** [comment]
But what is the reason the border width looks different even I settled in same pixel (1px).
Why Pixi shows thicker border than Fabric? Is it related with corners of pixels?

**Comment by ivanpopelyshev** [comment]
> But what is the reason the border width looks different even I settled in same pixel (1px).

If you move corner a bit, by 0.5, it should be the same as Fabric. If its not , please give the reproduction case. It should be easy to make in codesandbox.

PixiJS has same behaviour as canvas2d, which is the actual standard. Adobe Flash shown the same behaviour.

**Comment by guoqiangmin** [comment]
Great! Thank you @ivanpopelyshev . It worked for me when I adjust corners.
Thanks for your quick turn around.

**Comment by ivanpopelyshev** [comment]
alternative: lineAlignment
