### ISSUE TITLE
SpritesheetLoader - improve multi-pack support

### ISSUE THREAD

**Issue by Gawlas** [pixijs/pixijs#7715]
Hi,

Currently, when we are loading sprite-sheet that uses the multi-pack feature, the only thing loader does is to add the rest sprite sheets (JSON files) to the loader queue. Loaded textures from all loaded sprite-sheets are not gathered in any place. We just have multiple sprite-sheets resources and we have to manually manage and remember on which spritesheet given image is placed (if we don't want to use TextureCache). The problem is even more visible when we are using animations, as animation frames may be placed around all sprite sheets.

I think that would be very useful to improve multi-pack support to combine all textures and animations (from all multi-pack sprite-sheets) and keep them in a single place (1st sprite-sheet resource or additional field) so we don't have to remember on which sprite sheet given image is.

What do you think about this improvement? Do you think that it could be handled inside SpritesheetLoader, or do you want to keep the loader simple and leave it to be handled manually?

I'm happy to try to develop a solution if you think it will be usefull.

### Current Behavior

```
loader.add("fantasy_multi_pack_0", "assets/fantasy_multi_pack_0.json");
loader.load((loader, resources) => {
  // I need to know that armor texture is on 1st sprtitesheet
  const armor = resources["fantasy_multi_pack_0"].textures["armor.png"];

  // I need to know that backpack texture is on 2nd sprtitesheet
  const backpack = resources["fantasy_multi_pack_1"].textures["backpack.png"];
});
```

### Expected Behavior

```
loader.add("fantasy_multi_pack_0", "assets/fantasy_multi_pack_0.json");
loader.load((loader, resources) => {
  // textures from all spritesheets available in main resource
  const armor = resources["fantasy_multi_pack_0"].textures["armor.png"];
  const backpack = resources["fantasy_multi_pack_0"].textures["backpack.png"];
});
```

### Environment
- **`pixi.js` version**: 6.1.2

**Comment by ivanpopelyshev** [comment]
> do you want to keep the loader simple and leave it to be handled manually?

Doesnt actually matter because of #7639

If you want to try something, make a PR and lets discuss it

**Comment by bigtimebuddy** [comment]
This sounds reasonable. My biggest concern would be how to implement without breaking existing users. Not sure what the path looks like.

**Comment by miltoncandelero** [comment]
I implemented this with the idea of having all the images inside the TextureCache (`Sprite.from(...)`, `Texture.from(...)`, etc) and never crossed my mind to reference all the sprites inside the first resource.

Since resources added by other resources keep a reference to their _parent_ resource, it should be possible to link the child to the parent 🤔 

Not sure how breaking would be to change the size of the `textures` object inside the resource 🤔

**Comment by Gawlas** [comment]
The main issue with TextureCashe is name collision when 2+ sprite sheets have images with the same names, that's why I prefer to use loader resources.

For now, I created util that is called after loader load which processes all multi-pack sprite sheets (add all textures and animations to parent resource).

And now I'm thinking if there is an elegant way to do that on loader level. But unfortunately, I would consider adding all textures to the parent resource as BREAKING CHANGE.
