### ISSUE TITLE
Stopping propagation of click/pointertap event stops propagation of mouseup/pointerup

### ISSUE THREAD

**Issue by jaskp** [pixijs/pixijs#7730]
Hi, I've come across an inconsistency with DOM events that makes using [`pixi-viewport`](https://github.com/davidfig/pixi-viewport) a bit awkward. I've included an example that doesn't depend on any third-party libraries.

### Expected Behavior
Stopping propagation of `click` doesn't affect `mouseup` (like DOM).
Stopping propagation of `pointertap` doesn't affect `pointerup`.

### Current Behavior
Stopping propagation of `click` stops propagation of `mouseup` (**unlike DOM**).
Stopping propagation of `pointertap` stops propagation of `pointerup`.

### Environment

- **`pixi.js` version**: 6.1.2
- **Browser & Version**: Edge 92, Firefox 91, Safari 14
- **OS & Version**: macOS 11.2.3
- **Running Example**: [click/mouseup example](https://codepen.io/jaskp/pen/abwoBKw?editors=1010)

In the above example, all squares should trigger an alert, but the blue one doesn't.

**Comment by eXponenta** [comment]
There are not real click/tap events.
click is alias onto mouseup, tap on touchend/ pointerup.

**Comment by ShukantPal** [comment]
This will be fixed when using @pixi/events.
