### ISSUE TITLE
Camera stream capture bug in Android Webview

### ISSUE THREAD

**Issue by AleXNoD** [pixijs/pixijs#7743]
Hello!

I have an annoying problem with a camera stream capture in Android Webview (Cordova application) that makes me really sad.

Look at this code please.

```
const app = new PIXI.Application({ backgroundColor : 0xFFFFFF, antialias : false, forceFXAA : false, width : 600, height : 600});
document.getElementById('pixi').appendChild(app.view);
navigator.mediaDevices.getUserMedia({ video : { width : 300, height : 300 } }).then((stream) => {
   const htmlvideo = document.createElement('video');
   htmlvideo.srcObject = stream;
   htmlvideo.style.position = 'absolute';
   htmlvideo.style.top = '300px';
   document.body.appendChild(htmlvideo);
   const pixivideo= new PIXI.Sprite();
   pixivideo.texture = PIXI.Texture.from(htmlvideo);
   app.stage.addChild(pixivideo);
});
```

All Android permissions are ok.

We can see HTML "htmlvideo" element that streams a camera signal. It's OK everywhere.
But we can not see PIXI "pixivideo" object in Android Webview. It's empty. 
The Webview example is: https://alexnod.com/example/2.jpg

So I think that the PIXI Sprite fails with a capturing of the HTML video element. But why?

This problem is NOT actual in mobile Chrome and Opera browsers. Also everything is OK in iOS Safari.
The example of correct work is: https://alexnod.com/example/1.jpg

Tested Android devices are Pixel 5 and ZTE with the latest Webview version.

**Comment by eXponenta** [comment]
How i know, WebView permission is limited and disallow upload video data from stream to WebGL or canvas2D.

You should try to up https server inside WebView host application if you run application locally.

This is not a pixi problem, this is browser restrictions.

For iOS restricted disallowed use a camera stream outside Safari.
