### ISSUE TITLE
`trackedPointers` undefined on object that extends Container

### ISSUE THREAD

**Issue by adam-savard** [pixijs/pixijs#7750]
I'm actually using pixi-viewport, and ever since the move to Typescript it will cause an error where `trackedPointers`, a property that's supposed to be part of Containers, is undefined rather than an array.

See the below image for where this occurs.

![image](https://user-images.githubusercontent.com/49501626/130675075-6e0f5f05-8722-4bf9-af2c-256eb83edb84.png)

I found that by adding `viewport.trackedPointers = []` or by adding a line to initialize the property inside the viewport code it alleviates the issue; however, I think this is due to something odd happening in the main pixi project rather than viewport itself, since navigating to `this.trackedPointers` brought me directly to pixi code. If I'm mistaken, though, I apologize.

### Environment

- **`pixi.js` version**: _6.1.0_
- **Browser & Version**: _Chrome 92_
- **OS & Version**: _Linux Mint 20.1_

Pixi uses the standalone JS file (minified) and pixi-viewport is browserified

**Comment by ivanpopelyshev** [comment]
The usual: you have two pixies in your node_modules somehow.

**Comment by adam-savard** [comment]
Not saying this isn't the issue, but we don't actually browserify pixi; we use the production script as a standalone script. I will say I'm by no means a browserify wizard and it would make sense to me if it decided to include pixi as a dependency of viewport, culling, etc, so we could be including two pixis and not know it.

**Comment by adam-savard** [comment]
We were having issues for a long time with some plugins not liking the newer versions of pixi, for some reason, unless pixi was not browserified. A few days ago the issues magically resolved itself and we were able to force the update, which has since resolved the issue above.

So you were right, it was that issue, but I couldn't tell you what fixed our problems haha. I chalk it up to a solar flare.

**Comment by EmmittJ** [comment]
For anyone in the future, I was loading in modules in a mixed fashion: cjs (require) vs esm (from). I ended up switching to esm syntax everywhere in the application, and it resolved my issue. For whatever reason, webpack was loading up both the cjs and esm exports for only some of the packages in pixi when I had a require import for a completely different, unrelated library.
