### ISSUE TITLE
Improving Performance by reusing graphics objects

### ISSUE THREAD

**Issue by krnbatta** [pixijs/pixijs#7755]
Hi I am using Pixi.js to visualise pathfinding algorithms. Link: https://pf-algo-viz.org/ 
Now this involves drawing lot of similar graphics objects(circle, rectangle, etc) at same position(with different colours). Currently, I am generating a new graphics objects against each node. To optimise this, I am thinking of reusing the graphics objects at same position and only changing its attributes. This would ensure that fewer graphics objects are created. 
But the problem is as per current implementation, each node has graphics container which in turn has children(rectangles, circles, lines, etc) 
If I reuse the graphics object in another node's graphics container, it would first remove it from the previous container(since pixi objects can only stay at one place - looked into source code). 

I am confused whether to use different container for different nodes or just add everything in stage and update attributes(colours, borders) of graphic objects(rectangle, circle) there since then, I won't be using `addChild` and only updating attributes of existing object. This would decrease maintainability of the code. But I think this would significantly improve performance. I have following questions:

1. Would calling of `removeChild` whenever `addChild` is called would slow the performance?
2. I read that it is better to use containers to have separate context. Should I continue keeping separate containers for each node or just draw everything on one main canvas? I want to avoid this as this would cause serious refactoring of project.
3. Are there other ways in which I can improve the performance like reusing texture or anything else?

I would really appreciate suggestions for improving performance. 

P.S. This is an open-source project. Please feel free to look into it.

**Comment by eXponenta** [comment]
Or like this, when you have a lot of similar graphics
https://www.pixiplayground.com/#/edit/zmyXmtxKTXFZsFc1MSu4u

**Comment by krnbatta** [comment]
Hi @ivanpopelyshev 
Now I won't be using any Container in between. My stage will have only one container and it will have all the graphic objects(created from white texture geometry differentiated by tinting)
However, I have a question. When I am trying to jump couple of steps of the search algorithm, I want to quickly draw all those objects in one go rather than showing animation(while playing) Is there any faster way to do that? 

Currently, I am creating a PIXI.Container object and adding all those nodes(graphic objects) as children and then adding that container object to the stage to finally draw. I believe this helps in improving speed as much of the work is being done off screen and drawing is happening in the end. Is my speculation correct?

Is there any other way to speed up this process?

**Comment by krnbatta** [comment]
> Or like this, when you have a lot of similar graphics
> https://www.pixiplayground.com/#/edit/zmyXmtxKTXFZsFc1MSu4u

@eXponenta  Why did you create `geometry` and `graphicObject`. You could have simply used `texture` and `sprite`? Does that make any difference?

**Comment by krnbatta** [comment]
Also, I read in the documentation that PIXI has render loop and we can use ticker callbacks. I saw that in your code you did the same @eXponenta. Here is how I am running code on my play:
```
      // recursively play the animation
      loop() {
        let self = this;
        (function loop(){
          if(!PlaybackService.is("running")){
            return;
          }
          self.stepForward();
          // If each node requires drawing of complex structure apart from simple circle or rectangle primitives
          // This occurs when the trace has stateStructure and each node represents a corresponding state in pathfinding
          // the animation is delayed by half a second.
          if(self.tracer.stateStructure){
            setTimeout(loop, 500);
          }
          // If only node drawing is required, draw next node at browser next available frame.
          else{
            window.requestAnimationFrame(loop);
          }
        })();
      },
```

Is this anti-pattern? Is this slowing things? How to use ticker for the same thing? How will that be beneficial?

**Comment by eXponenta** [comment]
You cannot create rounded rectangle on regular sprite, or more complex shape like circle/star/polygone.
Bunny texture for example only, because it by default in playground.

And there are nor difference between a rectangular graphics and simple sprite.
Both produce same geometry structure and renders by same renderer.

**Comment by eXponenta** [comment]
> Also, I read in the documentation that PIXI has render loop and we can use ticker callbacks. I saw that in your code you did the same @eXponenta. Here is how I am running code on my play:
> 
> ```
>       // recursively play the animation
>       loop() {
>         let self = this;
>         (function loop(){
>           if(!PlaybackService.is("running")){
>             return;
>           }
>           self.stepForward();
>           // If each node requires drawing of complex structure apart from simple circle or rectangle primitives
>           // This occurs when the trace has stateStructure and each node represents a corresponding state in pathfinding
>           // the animation is delayed by half a second.
>           if(self.tracer.stateStructure){
>             setTimeout(loop, 500);
>           }
>           // If only node drawing is required, draw next node at browser next available frame.
>           else{
>             window.requestAnimationFrame(loop);
>           }
>         })();
>       },
> ```
> 
> Is this anti-pattern? Is this slowing things? How to use ticker for the same thing? How will that be beneficial?

Pixi ticker use same RAF but has time correction mechanism ( RAF not guaranteed that framerate will be  stable, for example, for screens on 120Ghz it will tick 120 times per sec, and without correction game will updating faster that needed), and there are priority order (render is always has low priority for valid update-visualisation order)
Then PIXI.Application already provide a required components for simple application.

@bigtimebuddy can you move to discussion?

**Comment by krnbatta** [comment]
> > Easy to reuse.
> > ```
> > g = new Graphics (graphicsTemplate.geometry)
> > g.tint = 0xff00ff
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Of course you cannot change anything inside geometry for refered graphics. If you want use new color/alpha on stroke - use isolated graphics template for fill and stroke isolated and change their tinting.
> > Nad you should not use a graphics for everything, for rectangular elements is Sprite can be used without overhead from graphics.
> 
> Sprite can be used using the following code as suggested by @bigtimebuddy
> 
> ```
> const rect = Sprite.from(Texture.WHITE);
> rect.width = 200;
> rect.height = 300;
> rect.tint = 0xffcc00;
> ```
> 
> Can we use similar technique for other graphics objects like circle or line or polygon?

This link suggests a way to draw circles: https://www.html5gamedevs.com/topic/46193-fastest-way-to-render-50k-circles-of-varying-radius-and-colors/

```
Draw a single big white circle (2048x2048) into a RenderTexture (or use a Bitmap asset if preferred).  Then use that Texture for each new Circle (as a Sprite) ... x 50,000.  Add them to a Container, then Position, Scale, and Tint the 50k Sprites accordingly.  Cache the container to save redrawing it every update (e.g. cacheAsBitmap).
```
So, we can use texture and sprite, right? But how to do that?

**Comment by ivanpopelyshev** [comment]
1. make it in a photoshop
2. use generateCanvasTexture , make sure you use `pixi.js-legacy` somewhere or you wont see that method in list
3. draw circle in canvas, use `Texture.from(canvas)`
3. MSAA stuff with regular generateTexture

if you want multiple shape models, put them in the same renderTetxure, make regions out of Texture's, that will reduce number of drawcalls.

**Comment by krnbatta** [comment]
> P.S. Obligatory comment after this was asked for 100 times. If you want complete explanation with all the code of possible ways - sponsor a book. If you want just simple API - sponsor the plugin.

I really liked PIXI.js and you guys support. I don't understand graphics much but still trying to wrap my head around. I am donating to PIXI. This is the first time I have ever donated to any open source project :)

**Comment by eXponenta** [comment]
Or use a Mesh with instancing, write shader that will clip rectangles onto dots.

Easy :) 

There are not more easiest way to render huge ammount of shapes.

https://www.pixiplayground.com/#/edit/5bWjCjL70izwdVOncfzoM

**Comment by ivanpopelyshev** [comment]
We told you what to do several times. You have to look at examples of those things we mentioned. 

What you describe is "task of 100k bunnies". Its something that everyone solves themselves. Its what distinguishes a coder from a stupid google neural net. PixiJS gives you low-level part of solution, you have to code high-level one. When you achieve it, you join our club :)

If you want someone else to do it for you, or you want complete code for parts of your task, ask people at https://discord.gg/kPrbTaRY at pixijs channel :) There were hundreds of discussions "how to draw 50k circles" there because of many agar-io clones.

**Comment by humbleCoder1990** [comment]
@ivanpopelyshev  How to join discord Pixi group?
