### ISSUE TITLE
Autocomplete in pure JavaScript projects, impacted by Documentation Reformatting

### ISSUE THREAD

**Issue by jasonsturges** [pixijs/pixijs#7763]
Per changes in v6, and including the Reformatting Documentation initiative (https://github.com/pixijs/pixijs/issues/7159), how does this affect pure JavaScript projects?

Since upgrading to v6, neither IntelliJ nor VS Code can autocomplete anything in the PIXI space.

IntelliJ has the ability to parse classical JSDoc style comments for type declarations.

- Left: Pixi V5 autocompletion
- Right: Pixi V6 unable to autocomplete

![pixi](https://user-images.githubusercontent.com/1213591/131574879-93e59bb5-e142-43b5-9966-2b1780fa74bf.gif)

Works great in TypeScript, but there are a lot of projects that won't be moving to TypeScript.

**Comment by ShukantPal** [comment]
For VS Code at least, isn't it supposed to use the `index.d.ts` file shipped with the package instead of JSDoc comments?

**Comment by jasonsturges** [comment]
Main issue is I'm not receiving autocompletion, secondary is what impact purging JSDoc comments will have.

**Comment by eXponenta** [comment]
JSDoc deprecated and will be completely droped.

Now a index.d.ts is main autocomplete source, without supporting a TS in IDE will not working yet.
You should enable TS for WebStorm manually.

**Comment by bigtimebuddy** [comment]
In a super bare-bones JS-only project in VSCode with pixi.js@6.1.3, I'm not seeing this. Autocomplete works using types.

![Screen Shot 2021-09-13 at 1 09 46 PM](https://user-images.githubusercontent.com/864393/133127160-af178777-04e8-4cf0-b94d-f422d880313d.png)

Also, type docs work here too (those it's not complete for all APIs, as the doc reformatting is a WIP).

![Screen Shot 2021-09-13 at 1 12 54 PM](https://user-images.githubusercontent.com/864393/133127539-81fa0f7f-eb19-4238-9ed7-b8728c9b6df2.png)

**Comment by jasonsturges** [comment]
VS Code has some IntelliSense.

Pixi v5.3.3 in VS Code:

![image](https://user-images.githubusercontent.com/1213591/133335600-f5bb54f9-9b54-46af-82e3-c25407a45f81.png)

Pixi v6.1.3 in VS Code:

![image](https://user-images.githubusercontent.com/1213591/133335621-fb266782-f85a-49e7-86ac-6e11aaaa85a4.png)

**Comment by bigtimebuddy** [comment]
I cannot reproduce this in VScode and 6.1.3. Could you provide a reproduction @jasonsturges? I'm curious to see if there are any issues in package-lock.

![Screen Shot 2021-09-16 at 8 01 14 AM](https://user-images.githubusercontent.com/864393/133608554-f1b53f8d-025c-4f71-9124-4cd2808f5335.png)

**Comment by jasonsturges** [comment]
So strange... wonder if GitHub Copilot beta program is messing with this.

IntelliJ IDEA still has zero functionality since version 6, which is strange - never had issues with any other library in a wide collection of 2D/3D libraries.

**Comment by bigtimebuddy** [comment]
I also have GitHub Copilot installed too. Are you up-to-date with VSCode? I'm running 1.60.1.

**Comment by jasonsturges** [comment]
Yeah, VS Code v1.60.1.

Just using it for comparison, as my main IDE is IntelliJ IDEA 2021.2 Ultimate Edition.
