### ISSUE TITLE
Extending AbstractBatchRender with custom uniforms

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixijs#7764]
Hello,

Im trying to extend AbstractBatchRenderer and add custom uniforms which I want to use in the vertex shader. But the uniform `custom_projectionMatrix` is always an array with just zeros (which I can debug using Spector).

How can I fix this?

```javascript
class SpriteRenderer extends PIXI.AbstractBatchRenderer {
  constructor(renderer) {
    super(renderer)

    this.shaderGenerator = new PIXI.BatchShaderGenerator(vertex, fragment);
    this.geometryClass = PIXI.BatchGeometry;
    this.vertexSize = 6;
  }

  start() {
    super.start()

    this._shader.uniforms.custom_projectionMatrix = [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  }
}```

**Comment by jnsmalm** [comment]
Thanks, I'll look into these resources!

**Comment by ShukantPal** [comment]
I would definitely encourage you to look at the [pixi-batch-renderer](https://github.com/pixijs/batch/tree/master/packages/batch-renderer) plugin that I authored. To add an additional uniform, you shouldn't have to write a lot of code.
