### ISSUE TITLE
Extending sprite

### ISSUE THREAD

**Issue by Pi-Bouf** [pixijs/pixijs#7771]
Hello ! Today I found an issue (strange issue).
When I use a simple "Sprite", with Texture.WHITE, I have an UC consumtption of ~10% for 2000 square.
But if I extend this class "class Graphic extends Sprite", my UC is doomed (80%)

How to properly extend this class, I code in TypeScript :)

### Expected Behavior
![image](https://user-images.githubusercontent.com/7634794/131985794-e5a04908-1416-42b3-aa74-2d21b3279280.png)
![image](https://user-images.githubusercontent.com/7634794/131985845-b62d876a-16c3-4652-aa85-f578ce667a61.png)

### Current Behavior
![image](https://user-images.githubusercontent.com/7634794/131985956-ec79e0d6-394d-4465-ae44-5c21c48960fb.png)
![image](https://user-images.githubusercontent.com/7634794/131985989-f18fd7ae-4d7c-42d7-acdd-7d31db002013.png)
![image](https://user-images.githubusercontent.com/7634794/131986015-62f4a518-ec73-4e83-a25a-72d85ba32a93.png)

### Possible Solution
IDK !

### Steps to Reproduce
Make a simple class extending Sprite

### Environment

- **`pixi.js` version**: _6.1.2_
- **Browser & Version**: _ Lastest Edge // Latest Chrome_
- **OS & Version**: _Win 10_

**Comment by ivanpopelyshev** [comment]
which target do you use for TS, es5? Do you use babel?

**Comment by Pi-Bouf** [comment]
@ivanpopelyshev this is my tsconfig.json :)
```
{
  "compilerOptions": {
    "isolatedModules": true,
    "noImplicitAny": true,
    "target": "ES2016",
    "module": "commonjs",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "sourceMap": true,
    "noEmitHelpers": false,
    "moduleResolution": "node"
  }
}
```

I am on parcel, who use babel (with a the basic .babelrc and typescript transform runtime)

I just tried on the Parcel V2, with TSC and not babel, it doesn't change anything, same issue !

When I just chrome's javascript profiler, I have that:
(With Sprite)
![image](https://user-images.githubusercontent.com/7634794/131995012-1fcca27c-df88-4a98-8ab2-7d2279039eaa.png)

(With Graphic extends Sprite)
![image](https://user-images.githubusercontent.com/7634794/131994979-221e3c33-dce3-4e6b-9989-c321812e7d60.png)

On second screen, we have a lot of time here:
![image](https://user-images.githubusercontent.com/7634794/131995061-ae682df1-1751-4881-973c-26e34144b4f7.png)


Do you have any idea ?
If you try, what is the result ? O.o

**Comment by Pi-Bouf** [comment]
OK, just tried to change "ES2016" to "es5", it works... that's really strange !

**Comment by ivanpopelyshev** [comment]
> OK, just tried to change "ES2016" to "es5", it works... that's really strange !

Pixi is built with es5. When you extend classes with two different ways, something strange happens. We don't know why.

**Comment by eXponenta** [comment]
Before V8 v9 super call was a SUPER SLOW

https://v8.dev/blog/fast-super

Same and for Spidermonkey (FF) and JSC (Safari)
