### ISSUE TITLE
Pixi is broken in IE 11

### ISSUE THREAD

**Issue by skystedt** [pixijs/pixijs#7775]
### Current Behavior
The latest versions of Pixi is broken in IE 11.
_Object doesn't support property or method 'startsWith'_

### Additional information
Works in version 6.0.4 but broken in 6.1.0 and forwards

IE 11 does not support string.startsWith
Which is getting called here: https://github.com/pixijs/pixijs/blob/v6.1.2/packages/core/src/shader/utils/getAttributeData.ts#L24
https://github.com/pixijs/pixijs/pull/7527 seems to be the culprit of the error

### Example repro
https://jsbin.com/puxuhamari/edit

### Steps to Reproduce
```
var app = new PIXI.Application();
app.loader
  .add("red", "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFBQIAX8jx0gAAAABJRU5ErkJggg==")
  .load(function() {
    var sprite = new PIXI.Sprite(app.loader.resources["red"].texture);
    sprite.width = 100;
    sprite.height = 100;
    app.stage.addChild(sprite);
  }
);
document.body.appendChild(app.view);
```

### Environment
- **`pixi.js` version**: 6.1.2
- **Browser & Version**: Internet Explorer 11
- **OS & Version**: Windows 10

**Comment by bigtimebuddy** [comment]
@eXponenta could you fix this?

**Comment by bigtimebuddy** [comment]
Fix is merged, closing this.
