### ISSUE TITLE
Incorrect transform.worldTransform on first render 

### ISSUE THREAD

**Issue by AStaroverov** [pixijs/pixijs#7785]
### Expected Behavior

``DisplayObject`` has correct ``transform.worldTransform`` on first render

### Current Behavior

``DisplayObject``(In my case it's ``Mesh``) has default(incorrect) ``transform.worldTransform`` on first render,  cause
``Container.prototype.updateTransform`` will be called only after first render ``Mesh``.

### Possible Solution

I think after ``addChild`` we should trigger updateTransform;
My workaround is ``this.on('added', () => this.updateTransform());``.

### Environment

- **`pixi.js` version**: 6.0.1
- **Browser & Version**: Chrome 93
- **OS & Version**: _e.g. Mac os 11.5.1
- **Running Example**: -

**Comment by ivanpopelyshev** [comment]
Please provide the demo. If you are doing something like:
```js
container.addChild(mesh)
doSomethingWith(mesh.transform.worldTransform)
```
it wont work.

There's special method in DisplayObject called `_recursivePostUpdateTransform` https://github.com/pixijs/pixijs/blob/5bd4c5bb683dca5a33e511277273a832342fb804/packages/display/src/DisplayObject.ts#L479-L491

this method is caled whenever pixi needs worldTransform when there's no guarantee that its already calculated, for example in `toLocal`: https://github.com/pixijs/pixijs/blob/5bd4c5bb683dca5a33e511277273a832342fb804/packages/display/src/DisplayObject.ts#L675

Welcome to lazy computations 101. Yes, pixi method isn't as verbose as ThreeJS `updateWorldMatrix ` that asks whether you want to update parents or children or both

**Comment by ivanpopelyshev** [comment]
then something else is wrong, it should work.

**Comment by ShukantPal** [comment]
@AStaroverov What other methods did your override? And what's going on in the render method of MyMesh?

**Comment by AStaroverov** [comment]
@ShukantPal no one else.

Ok, I can't reproduce it standalone.
But it is reproducing on an internal project.

I don't know what I could make incorrect. The code looks absolutely legal. 

So I'll try to collect more information and find the problem.

**Comment by AStaroverov** [comment]
I understood where I made mistake.
I am making append child inside render method parent's component.
```
class MyMesh extends Mesh {
  render(renderer) {
    ...
    super.render(renderer)
  }
}

class Root extends Container {
  render(renderer) {
    if (...) this.addChild(new MyMesh);
    super.render(renderer)
  }
}
```
I don't think that there is PIXI problem.
