### ISSUE TITLE
Graphic ignores custom shader unless you set lineStyle with a min value of 1

### ISSUE THREAD

**Issue by sketchpunk** [pixijs/pixijs#7798]
### Expected Behavior
Graphic should use the shader that its set with to handle it's rendering. In the example I provided, I expect there to be two red circles. Its a basic shader that just colors things red, it completely ignores the fill color of the graphic.

### Current Behavior
Without lineStyle, graphic gets colored by what was set by beginFill, not possible if it was running the shader it was set with. If you add lineStyle with a thickness of at least 1, it then gets colored red which means its using the set shader.

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/1d1vhhAM16Nk9YW3lnte6

**Comment by ivanpopelyshev** [comment]
It sees geometry as batchable. `graphics.geometry.isBatchable = () => { return false } ` should do the trick.

**Comment by bigtimebuddy** [comment]
This seems addressed. Closing.
