### ISSUE TITLE
TS2339: Property 'source' does not exist on type 'Resource'.

### ISSUE THREAD

**Issue by onetrickwolf** [pixijs/pixijs#7810]
### Steps to Reproduce

When trying to access the source on a video texture I am getting `Property 'source' does not exist on type 'Resource'.`

Have to add `// @ts-ignore` to compile but works just fine other than TypeScript error.

```ts
const texture = PIXI.Texture.from('examples/assets/video.mp4');
const video = new PIXI.Sprite(texture);

// Without @ts-ignore: TS2339: Property 'source' does not exist on type 'Resource'.
// @ts-ignore
video.texture.baseTexture.resource.source.loop = true;
```

I tried casting the type as a `VideoResource` as seen [here](https://github.com/pixijs/pixijs/issues/6611):

```ts
(texture.baseTexture.resource as PIXI.VideoResource).source.loop = true;
```

But am now getting this error:
```bash
Property 'loop' does not exist on type 'ImageSource'.
Property 'loop' does not exist on type 'HTMLCanvasElement'.
```

Been looking through PixiJS source but honestly am getting a bit lost if anyone has any ideas on what is going on here. Not sure if a bug or just something I am missing. Thanks!

### Environment

- **`pixi.js` version**: 6.1.3
- **Browser & Version**: N/A
- **OS & Version**: Ubuntu 20.04
- **Running Example**: https://github.com/onetrickwolf/pixijs-intro-example/tree/pixijs-minimal-property-error

**Comment by ivanpopelyshev** [comment]
> Been looking through PixiJS source but honestly am getting a bit lost if anyone has any ideas on what is going on here. 

Usual TS stuff. There are resources that dont have `source` and VideoResource does have `source` from its parent, without re-declaration of type. 

There's a way to fix those things - add generics, everywhere. Which will make code unreadable.

**Comment by onetrickwolf** [comment]
@ivanpopelyshev ah got thanks yeah `(texture.baseTexture.resource as any).source.loop = true;` is fine! Just wanted to make sure there wasn't some better way. I am newer to using TypeScript with PixiJS just double checking.

**Comment by bigtimebuddy** [comment]
The "proper" (non-any) way to do this is to cast like this using generics, which @ivanpopelyshev mentioned.

```typescript
(texture.baseTexture as BaseTexture<VideoResource>).resource.source
```

The problem with VideoResource is that there's a bug in the typings. We should be overriding `source` as a video element, instead this is an HTMLImageElement. I will work on a fix for this.

**Comment by onetrickwolf** [comment]
@bigtimebuddy ah got it okay that makes sense now I get it. Thanks for quick PR too!
