### ISSUE TITLE
GL_INVALID_OPERATION: Level of detail outside of range.

### ISSUE THREAD

**Issue by serjrd** [pixijs/pixijs#7822]
### Expected Behavior
This code to draw a picture:

```
bgSprite = PIXI.Sprite.from(img, {width: 1920, height: 1080})
container.addChildAt(bgSprite, 0)
```

### Current Behavior
It works fine like 9/10 times.
But sometimes no image is shown and I get `GL_INVALID_OPERATION: Level of detail outside of range.` message in my Chrome console.

### Environment

- **`pixi.js` version**: 6.1.3
- **Browser & Version**: Chome Version 93.0.4577.82 (Official Build) (64-bit)
- **OS & Version**: _e.g. Ubuntu 20.04

**Comment by serjrd** [comment]
Looks like the reason is the `PIXI.Sprite.from` code, which doesn't always work right.

Changed code to: 

```
loader = PIXI.Loader.shared
loader.reset()
loader.add 'bg', img
loader.load (loader, resources) ->
  bgSprite = new PIXI.Sprite(resources.bg.texture)
  container.addChildAt(bgSprite, 0)
```

And it seems to be working fine. 
Any ideas why this may be happening?

**Comment by ShukantPal** [comment]
Can you create a minimal reproduction on JSFiddle / CodePen / PixiJS Playground / Replit / etc?
