### ISSUE TITLE
Bool uniforms sync is broken

### ISSUE THREAD

**Issue by dev7355608** [pixijs/pixijs#7823]
Bool uniforms are not properly synchronized as the linked playground example shows: the color of the square should switch from red to green but it doesn't.

I checked and this bug is fixed by #7808.

### Environment

- **`pixi.js` version**: 6.1.3
- **Running Example**: https://www.pixiplayground.com/#/edit/UgduWfXFk6XRwZRcD9oNu

**Comment by bigtimebuddy** [comment]
So this should be fixed in the next release.

**Comment by dev7355608** [comment]
Fixed in 6.2.0.
