### ISSUE TITLE
Video .webm textures not clearing alpha, causing artifacts

### ISSUE THREAD

**Issue by Haxxer** [pixijs/pixijs#7836]
Hello,

After [Issue 3526](https://github.com/pixijs/pixijs/issues/3526) was closed, it appeared as if this was fixed for a time, but it has since returned. Perhaps an update to the way Chromium handles playing .webm files causes this, but in any case this issue still remains.

As per [this discussion](https://github.com/pixijs/pixijs/discussions/7175), various people have tried to raise the issue after it was marked as stale in [Issue 4089](https://github.com/pixijs/pixijs/issues/4089), and after it was missed in a related [issue on the Pixi GL Core Repo](https://github.com/pixijs/pixi-gl-core/issues/27).

From my experimentations, it appears that the current implementation simply does not clear the alpha after rendering frames, causing these rendering artifacts:

![Image](https://i.imgur.com/T2352WF.jpg)

- **Playground examples:** - white background added to demonstrate alpha difference
     - With fix: https://www.pixiplayground.com/#/edit/BSOldwbSTNfJ7e3WRSltM
     - Without fix:  https://www.pixiplayground.com/#/edit/wgmg-EQcyLdFX8EKLWpwV
     - **Credit to JB2A [https://jb2a.com/](https://jb2a.com/) for allowing me to use their asset as an example**
     - Note: I do **not** expect my makeshift patch to be thought of actual implementation, it is **only** for demonstration purposes.

- **`pixi.js` version**: 6.0.4

- **Tested Environments**
     - **Browsers & Versions**:
          - Google Chrome Version 94.0.4606.61 (Official Build) (64-bit)
          - Google Chrome Version 93.0.4577.82 (Official Build) (64-bit)
          - Edge Version 94.0.992.31 (Official build) (64-bit)
     - **OS & Versions**:
          - Windows 10 Pro (64-bit) : Version 20H2, Build 19042.1237
          - Windows 10 Home (64-bit) : Version 10.0.19042, Build 19042
          - Windows 10 Enterprise (64-bit) : Version 19041.1237

**Comment by Haxxer** [comment]
My apologies, this is not due to Pixi at all, but rather the encoding of the .webm asset.

https://www.pixiplayground.com/#/edit/xiB6wlEPquEwU8FFoWQjb

As you can see in this playground example, I'm toggling between:

`baseTexture.alphaMode = PIXI.ALPHA_MODES.NO_PREMULTIPLIED_ALPHA;`

and

`baseTexture.alphaMode = PIXI.ALPHA_MODES.PREMULTIPLY_ALPHA;`

The difference is staggering.

**Comment by ivanpopelyshev** [comment]
in filter everything is premultiplied anyway, the video is re-renderedd in temp framebuffer before it goes to filter. 

There's a trick to get non-premultipleid info there, but are you sure you need it? You can use mesh-shader instead of filter and it'll get non-premultiplied info from texture , though you still have to output premultiplied in it

**Comment by colinbouvry** [comment]
Too many artefact with filter.blendMode = PIXI.BLEND_MODES.NORMAL_NPM
It's like with premultiplied alpha !
Do you have examples of mesh-shader ?

**Comment by ivanpopelyshev** [comment]
https://pixijs.io/examples/#/mesh-and-shaders/shadertoy-mesh.js

**Comment by colinbouvry** [comment]
quad.blendMode = PIXI.BLEND_MODES.NORMAL_NPM; 
PIXI.BLEND_MODES.NORMAL does not work !

**Comment by ivanpopelyshev** [comment]
`gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA)` - that's NPM blendmode, it takes npm from texture and produces pma for blending.

At this point , I have to ask you to post whole demo in a separate issue, because this thing is not easy. I told you what we did with other project and its possible, i cant proceeed without a demo i can just hack into

**Comment by colinbouvry** [comment]
Artefact :
![image](https://user-images.githubusercontent.com/985676/137478887-d045848b-9896-4ee9-8ae5-29b3bb05e2a8.png)

**Comment by colinbouvry** [comment]
With filter.blendMode = PIXI.BLEND_MODES.NORMAL_NPM, it works fine !
Thanks a lot
