### ISSUE TITLE
Antialias is not working in AMD's video card

### ISSUE THREAD

**Issue by KKzLEO** [pixijs/pixijs#7837]
Hi, thanks for creating this library, I encountered an unknown issue recently that is when we enable `antialias`, some computers will fail to render whole PIXI application on Chrome but work fine on Firefox in MacOS, I am not sure it's due to the recent updates of MacOS or Chrome, but it's working fine on my computer (same version but different graphics), the only difference is their video card is AMD and mine is Intel, could it be a problem? I am wondering if you could give me some tips to do trouble shooting, I'm desperate :(

### Expected Behavior
Render PIXI App successfully with anti-alias

### Current Behavior
Failed to render PIXI App when enabling anti-alias

### Possible Solution
Disable anti-alias

### Environment

- **`pixi.js` version**: 5.3.7
- **Browser & Version**: Version 94.0.4606.61 (Official Build) (x86_64) Chrome
- **OS & Version**: 
     MacOS Big Sur, version 11.6
     AMD Radeon Pro 5300M 4 GB
- **Running Example**: 
![image](https://user-images.githubusercontent.com/26006239/135589708-89db97f6-3963-4722-a403-1a4956b5b95d.png)
(the blue square and line are from pixi debug extension, as we can see there is some weird broken gray rectangle displayed on the top, it looks like broken textures)

**Comment by amuzalevskiy** [comment]
We caught same behaviour

PIXI 5.2.4

Issue is reproduced on
  MacOS Catalina 11.5.2
  AMD Radeon Pro 5300M 4 GB

And it is NOT reproduced with
  MacOS Catalina 10.15.7
  AMD Radeon Pro 5500M 4 GB

**Comment by ivanpopelyshev** [comment]
"antialias" is a feature of webgl context, pixi cant do anything about that.

Workaround for lines and basic shapes: https://github.com/pixijs/graphics-smooth/ . Works with v6, maybe works with v5 if you put file separately (UMD)

**Comment by eXponenta** [comment]
> We caught same behaviour
> 
> PIXI 5.2.4
> 
> Issue is reproduced on MacOS BigSur 11.5.2 AMD Radeon Pro 5300M 4 GB
> 
> And it is NOT reproduced with MacOS Catalina 10.15.7 AMD Radeon Pro 5500M 4 GB

Safari 15 is very bugged.
If you use Safari 15 - report onto apple forum with simple reproduction.

**Comment by Ericlm** [comment]
Thank you very very **very** much @ivanpopelyshev for the Smooth Graphics, we had the same issue in our project, with antialiasing making our app completely stuck on Safari, but now, using Smooth Graphics, it's perfect on all the browsers we target. Thank you so much! 😊

**Comment by RewriteH** [comment]
Faced same behavior on electron v22.0.0
