### ISSUE TITLE
PREMULTIPLY_ALPHA or PREMULTIPLIED_ALPHA

### ISSUE THREAD

**Issue by dev7355608** [pixijs/pixijs#7845]
I noticed that in the `ALPHA_MODES` enum it's `PREMULTIPLY_ALPHA`, but in the documentation it says `PREMULTIPLIED_ALPHA`. The latter would make certainly more sense.

**Comment by ivanpopelyshev** [comment]
yep, it should be `PREMULTIPLIED_ALPHA`
