### ISSUE TITLE
PIXI.Loader cannot load SVG with XML prolog

### ISSUE THREAD

**Issue by zero41120** [pixijs/pixijs#7854]
### Expected Behavior
Search showed that #7460 and its merge request #7478 suppose to fix the issue, it doesn't.
The merge request only fix the detection, but the conversion RegExp was not update accordingly.
Expecting the SVG to base64 conversion should work with XML prolog.

### Current Behavior
#7478 correctly detected the resource is a SVG with XML prolog, thus reaching the SVG conversion code here.
L120 is the conversion code, which does not check with XML prolog.
https://github.com/pixijs/pixijs/blob/2ee8e90f3edd3384beb57e2c50f7d9a780ccf599/packages/core/src/textures/resources/SVGResource.ts#L118-L129
![image](https://user-images.githubusercontent.com/10471270/136623675-4afa4b6f-c62c-4032-ab02-94652e41de63.png)

It will eventually be set as `image.src` as raw string when calling `_loadSvg`
https://github.com/pixijs/pixijs/blob/2ee8e90f3edd3384beb57e2c50f7d9a780ccf599/packages/core/src/textures/resources/SVGResource.ts#L140-L145
![image](https://user-images.githubusercontent.com/10471270/136625099-2221c2c4-9386-4f87-96cf-249bce9c260d.png)

Image will then trigger an network request with that exact string, thus fail to load resource.
![image](https://user-images.githubusercontent.com/10471270/136624482-479554a5-a7bf-48ec-8c03-63fc7c458ff0.png)

### Possible Solution
Update the base64 conversion code to ensure XML Prolog should work.
Not sure if it is applicable, but inline comment before `<svg` should also be ignored.

### Steps to Reproduce
`script.js`:
```
let loader = new Loader();
loader.add('image', 'circle.svg');
loader.load(() => { ... });
```
`circle.svg`:
```
<?xml version="1.0" encoding="utf-8"?>
<svg width="48" height="48" xmlns="http://www.w3.org/2000/svg">
  <path d="M24 1C11.281 1 1 11.281 1 24s10.281 23 23 23 23-10.281 23-23S36.719 1 24 1z" fill="#fff" fill-rule="nonzero"/>
</svg>
```

### Environment

- **`pixi.js` version**: _e.g. 6.1.0_
- **Browser & Version**: _e.g. Chrome 94_
- **OS & Version**: _e.g. Windows 10 20H2

**Comment by bigtimebuddy** [comment]
You're right, thank for looking into this. Should be an easy fix. PR welcome.
