### ISSUE TITLE
Nested masked objects break when going outside viewport (in certain conditions)

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/pixijs#7855]
The included playground demo explains it best, but to sum it up, when the following conditions are true, the mask on container C will be disabled when it moves out of the viewport:

 * scissor masking is enabled
 * masked container (C) is a child of a masked object (P)
 * the parent container (P) contains at least one other object

This feels somewhat similar to #5974 (which was fixed a long time ago) but is obviously not exactly the same case.

### Expected Behavior
Mask will never disable
### Current Behavior
Mask disables when object leaves viewport

### Possible Solution
Disable scissor masking

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/2qJVNoyRHDVPMtaTJ4hCY

### Environment
- **`pixi.js` version**: 6.0.0 and up
- **Browser & Version**: Tested in Windows 10 on FF, Chrome, and Edge, all have the same issue
- **Running Example**: https://www.pixiplayground.com/#/edit/2qJVNoyRHDVPMtaTJ4hCY

**Comment by jmlee2k** [comment]
I've tried it on a few windows machines, here's how it looks:
![pixi6-mask-issue](https://user-images.githubusercontent.com/7396545/136977370-db9a480b-af84-474f-965d-08cf0d1b52fe.gif)

**Comment by robertswan** [comment]
This also impacts all iPhones with iOS 15 (so all the latest iPhone 13s and anyone else upgrading their OS).
Confirmed with the running example link above across various iOS 15 vs non 15 iphones.

**Comment by eXponenta** [comment]
@robertswan 
can you provide a 100% reproduced bug?

iOS 15.1b4 (dev) not reproduced:
https://youtu.be/VhTxJptVs4Q

You should check a your bug on unstable version of iOS too, because stable (haha) ios 15 is not stable for some devices.
Same and with Safari 15, i know a lot of hates around it.

**Comment by jmlee2k** [comment]
@eXponenta - Sure, it makes sense that it was introduced in Safari 15.  In terms of Windows, I've tried disabling ANGLE, and the same result occurs (at least in Firefox), so maybe more than one issue is at play here.

**Comment by ivanpopelyshev** [comment]
> > @robertswan can you provide a 100% reproduced bug?
> 
> My apologies as I wish I could. Our products are complicated and I don't have source for the games that are bugged. I might try hacking in the PR changes manually. I'm also working across language and time zone barriers while managing this.
> 
> FWIW: https://assets.sldfx42.net/badges/GHG/SL2/v105.0.2/?token=token&gameCode=GHG_BATTLE_DWARF&play_mode=FUN shows the error on iOS 15. The loading screen has an incorrectly clipped middle section and renders only the BG once the game is loaded.

can you please host a build that takes pixi from https://exponenta.games/games/pixi-versions/pixi.js ? That way we can debug the solution.

**Comment by ivanpopelyshev** [comment]
Interesting. I thought there are more bugs. Yeah, gonna make more tests for this thing and then we can finish it.

**Comment by ivanpopelyshev** [comment]
Oh, right , its 4.5.3 , and i gave you updated 4.8.9, let me see list of old changes, just in case

**Comment by ivanpopelyshev** [comment]
so its something like double-destroy, that worked in 4.5.3 but not working in 4.8.9, let me try

**Comment by robertswan** [comment]
> so its something like double-destroy, that worked in 4.5.3 but not working in 4.8.9, let me try

So since I mentioned this it went from 100% over 10 attempts to 0% repro. So I assumed maybe youve changed something?
The bonus game now starts, but I get a similar issue at the end of the bonus game. You mention double delete - is there something fundamentally wrong our code is doing?

**Comment by robertswan** [comment]
So 4.8.9 + fix for scissor area <= 0 + patch for different destroy behaviour works so far. I'll add these pixi changes into our other projects but it's likely any other issues are from our codebase and not the scissor issue. I could always patch the 4.8.9 scissor fix into 4.5.3 if necessary to minimise risk to our projects. 

Last question is will the scissor update will have an appreciable impact on render speed on mobile?

If you pass your own internal PR process then I'm guessing the v4.5.3 bug bounty should be claimed. The v6.0.0 work could presumably be verified by @jmlee2k.
