### ISSUE TITLE
Plesase do better wirte the document, otherwise no matter how good the tool is, no one goes use it 

### ISSUE THREAD

**Issue by mxm-web-develop** [pixijs/pixijs#7887]
### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment]
Thanks for the feedback. PRs always welcome to continually improve API documentation, user guides (github.com/pixijs/guides) or the website (github.com/pixijs/pixijs.com).
