### ISSUE TITLE
PIXI.Graphics multiple arcs results in continuous drawings

### ISSUE THREAD

**Issue by Vardner** [pixijs/pixijs#7893]
### Expected Behavior
Behold 2 independent arc curves at the stage.
### Current Behavior
Arc curves are connected to each other

### Steps to Reproduce
1. Open playground with Pixi (I've used your own examples web site https://pixijs.io/examples/#/graphics/advanced.js)
2. Insert this: 

```javascript
const app = new PIXI.Application({ antialias: true, backgroundColor: 0xffffff });
document.body.appendChild(app.view);

// // ARC ////
const arc = new PIXI.Graphics();

arc.lineStyle({width: 3, color: 0x15B22F, alignment: 1});
arc.arc(400, 200, 50, Math.PI, 2 * Math.PI);
arc.arc(400, 400, 50, Math.PI, 2 * Math.PI, true);

app.stage.addChild(arc);
```

### Environment
No environment required

- **`pixi.js` version**: _6.1.3_
- **Browser & Version**: Chrome latest
- **OS & Version**: Windows

![image](https://user-images.githubusercontent.com/36897869/138078963-2e4c2a60-0343-417b-a4cb-ef60685b628d.png)

**Comment by Vardner** [comment]
> > > Using `moveTo()` https://www.pixiplayground.com/#/edit/XMcmPXAq_hq9szep1_J0i
> > 
> > 
> > Thank you, this helps but I still find this behavior strange
> 
> Not strange. By default primitive drawing operations is streamed (following each other)
> 
> and arcTo implemented over arc:)
> 
> https://github.com/pixijs/pixijs/blob/dev/packages/graphics/src/Graphics.ts#L552

Yeah, my bad, I've tried the same with canvas2d and it behaves the same way as PIXI does.
Although we have the same behavior, canvas2d has a method (stroke) to end the current path and start new whereas PIXI doesn't have.

Maybe it is possible to implement some kind of method that could stop continuous drawing?

**Comment by eXponenta** [comment]
Canvas2D API stroke not close path.
It execute draw operations for active path.
Pixi Graphics not do anything until `render` call.

You only can `closePath`, or call `moveTo`.

Then you must know that you can't use continuous drawing between frames, rendere always will close Graphics between before call render.

PIXI Graphics API and Canvas2D is different.
You can't stroke and fill isolate. For this there are a `beginFill`, `endFill`, `closePath` or internal methods `finisPoly` https://pixijs.download/dev/docs/PIXI.Graphics.html#finishPoly


PIXI Api is Flash Like API.
