### ISSUE TITLE
PREFER_ENV default

### ISSUE THREAD

**Issue by dev7355608** [pixijs/pixijs#7899]
The doc says that webgl2 is disabled by default for all *non-apple* mobile devices, but it's actually disabled for all mobile devices.

Also the referenced bug has been fixed two years ago. Maybe we can remove this exception for mobile devices?

https://github.com/pixijs/pixijs/blob/234f39d998a20e7928772a784e664c0b7c0b9c02/packages/core/src/settings.ts#L5-L21

**Comment by Zyie** [comment]
Fixed in #7899 and will be released in v7
