### ISSUE TITLE
PixiJS fails to bootstrap when using only named imports

### ISSUE THREAD

**Issue by maritaria** [pixijs/pixijs#7936]
### Expected Behavior

The following Pixi.JS sample should produce a black square, but instead the rendering does not seem to be performed at all.

```typescript
import { Application } from '@pixi/app'

const app = new Application({width:100,height:100, backgroundColor: 0x000000});
document.body.appendChild(app.view);
```

This particular sample is part of https://github.com/kittykatattack/learningPixi#creating-the-pixi-application-and-stage.
The tutorial itself is advertised on https://pixijs.com/tutorials/.

### Current Behavior

The canvas for the app mounts, but it is blank and never renders the scene.

### Possible Solution

I noticed that adding `import 'pixi.js';` was sufficient to get the code to work.

1. Document the requirement to perform `import 'pixi.js';` specifically when using named imports in the new setup (`@pixi/*`).
2. Have a dedicated package with side-effects for setting up pixi.js (e.g. `@pixi/init`).
3. Do (2) automatically from core pixi packages, specifically those that require the setup (`@pixi/app`).

### Steps to Reproduce

1. Create an empty project. For example, using a vitejs typescript template
2. Add pixi.js as package dependency
3. Use the sample from earlier
4. Run the app
5. If correct you will observe "Current Behavior"

### Environment

- **`pixi.js` version**: `PixiJS 6.1.3 - ✰ WebGL 2 ✰`
- **Browser & Version**: Chrome 95
- **OS & Version**: Win10
- **Running Example**: https://codesandbox.io/s/happy-cloud-fbzk6?file=/src/index.ts

**Comment by bigtimebuddy** [comment]
Try this:

```js
import { Application } from 'pixi.js'
```

Not this:

```js
import { Application } from '@pixi/app'
```

Importing the sub packages directly is fine, but there's some "glue" code that needs to be imported to wire up all the plugins. Importing only app will not include these important bits. Check out https://pixijs.ui/customize to see what the glue code looks like.

I suggest you import names exports from the pixi.js package instead.

**Comment by maritaria** [comment]
> Check out https://pixijs.ui/customize to see what the glue code looks like.

You probably meant https://pixijs.io/customize?

In the meantime I happen to come across the glue code that was missing, it was the absence of the https://github.com/pixijs/pixijs/blob/dev/packages/ticker/src/TickerPlugin.ts.
Thanks for the tip on the customizer, but the behavior remains undocumented.

**Comment by miltoncandelero** [comment]
> Have a dedicated package with side-effects for setting up pixi.js (e.g. @pixi/init).

That is exactly what `pixi.js` is, look at it by yourself: https://github.com/pixijs/pixijs/blob/dev/bundles/pixi.js/src/index.ts

**Comment by bigtimebuddy** [comment]
Yeah, the packages are a newer feature and we don't have a lot of documentation on that yet. But we'd welcome if someone wanted to write a guide about packages here: github.com/pixijs/guides
