### ISSUE TITLE
AddChild in DisplayObject doesn't allow spreading anymore

### ISSUE THREAD

**Issue by MercurialUroboros** [pixijs/pixijs#7938]
Hello, after updating to 6.2.0 I'm experiencing this behavior.

### Expected Behavior

When using a spread operator to add to a DisplayObject like
`const containers = [new Container(), new Container()]`
`a.stage.addChild(...containers)`
I expect no ts issues
### Current Behavior

Currently getting
A spread argument must either have a tuple type or be passed to a rest parameter.ts(2556)

### Possible Solution

Possibly it is due to this change in addChild

addChild<T extends DisplayObject>(...children: [T, ...DisplayObject[]]): T; (6.2.0)
addChild<T extends DisplayObject[]>(...children: T): T[0]; (6.1.3) 

### Environment

- **`pixi.js` version**:  6.2.0
- **OS & Version**:  Mac OS Big Sur

**Comment by bigtimebuddy** [comment]
Related PR #7868

Summoning @ShukantPal

**Comment by bigtimebuddy** [comment]
Here's a reproduction [TypeScript playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAiCWEAO4CeB5ARgKwKbABdoBvAXwFgAoUSGAYQHsA7AseJ3AJ2lwA8DcTACYwEyNFjyESVaHOhghQugAt4IIQB4AKj36CRcRCjAYc+AgD4AFMDUaAXNG0AaaADpPd9UM6CnYiZmUgQA2gC6AJROusSy8gl+BACunEzQ3hp+TKEADOEKMNoA3PFyFJQVNFDQAMpInPACegLC9Mys7FwkFVTAzBBE-SxsHNwAvNAcAO7QjCNdnNaRpdQDRH4QySAEudCTw51j7orK9kLLq8OD0JvbBACM+xkdo1wnSqo+1jN1DU24ZYrPrrW64LY7ABMz0Ob04HzO31+gQk5kIyzcyOMqJCGKmuFmKNMkgsQKuoLuOwAzDDXosEV8ND8CX9GgI8VjxMS0QQOSyicFSZFgZQQUwbplfIJnqFfvU2YDIpiWfKActwuTxRtwfcACy0hbHU6Mi6edyS7IrIA)

I think if we can't get this typing to work, we should revert the change in 6.2.0 and just include docs that say at least one child is required.

**Comment by ShukantPal** [comment]
Hmm I guess we'd need two separate arguments to fix this.

**Comment by bigtimebuddy** [comment]
This is [the workaround](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAiCWEAO4CeB5ARgKwKbABdoBvAXwFgAoUSGAYQHsA7AseJ3AJ2lwA8DcTACYwEyNFjyESVaHOhghQugAt4IIQB4AKj36CRcRCjAYc+AgD4AFADp7wNRs6CAXNADa2gDTR7tsRMzKQIPAF0wgEp3XWJZeQSXAgBXTiZoR3UhFyYPAAYwgG54uQpKMpooaABlJE54AT0BYXpmVnYuEjKqYGYIIl6WNg5uAF5oDgB3aEYhjs5rSOLqPqIXCGSQAjzoccH2kdtFZSchReXB-uh1zYIARl2MtuGuI6VVLOspmrqG3EWlj1VtdcBstgAmR77F6cN4nT7fQIScyERa+RHGZEhNETXDTJGmSQWAEXYE3LYAZihz3mcI+Gi+eJ+9QEOIx4kJKIIbKZBOCxMigMoQKYV0yzjcnlqLNwvmlfzCjw833lrMi6KZqv+kSKIqu5IIABZqXNDsd6Wd-OLsoIlkA) for the type error.

```ts
const containers: [Container, Container] = [new Container(), new Container()];
app.stage.addChild(...containers);
```

In this case, because we tweaked the typing slightly, you need to be explicit about the type for `containers`.

**Comment by MercurialUroboros** [comment]
Thanks, I'm aware of the workarounds, I will be waiting for something more succinct.

> This is [the workaround](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAiCWEAO4CeB5ARgKwKbABdoBvAXwFgAoUSGAYQHsA7AseJ3AJ2lwA8DcTACYwEyNFjyESVaHOhghQugAt4IIQB4AKj36CRcRCjAYc+AgD4AFADp7wNRs6CAXNADa2gDTR7tsRMzKQIPAF0wgEp3XWJZeQSXAgBXTiZoR3UhFyYPAAYwgG54uQpKMpooaABlJE54AT0BYXpmVnYuEjKqYGYIIl6WNg5uAF5oDgB3aEYhjs5rSOLqPqIXCGSQAjzoccH2kdtFZSchReXB-uh1zYIARl2MtuGuI6VVLOspmrqG3EWlj1VtdcBstgAmR77F6cN4nT7fQIScyERa+RHGZEhNETXDTJGmSQWAEXYE3LYAZihz3mcI+Gi+eJ+9QEOIx4kJKIIbKZBOCxMigMoQKYV0yzjcnlqLNwvmlfzCjw833lrMi6KZqv+kSKIqu5IIABZqXNDsd6Wd-OLsoIlkA) for the type error.
> 
> ```ts
> const containers: [Container, Container] = [new Container(), new Container()];
> app.stage.addChild(...containers);
> ```
> 
> In this case, because we tweaked the typing slightly, you need to be explicit about the type for `containers`.
