### ISSUE TITLE
Loader XHR request ignores crossOrigin option

### ISSUE THREAD

**Issue by sergaks** [pixijs/pixijs#7947]
### Expected Behavior
When specified crossOrigin attribute 'use-credentials' for XHR requests are expected the same behavior as for image requests (attaching cookies to http requests)
loader.add({'some-img.svg', crossOrigin: 'use-credentials' })

### Current Behavior
crossOrigin attribute ignored in XHR request

### Possible Solution
 LoaderResource.ts
 private _loadXhr(): void {
....
        const xhr = this.xhr = new XMLHttpRequest();
        if(this.crossOrigin === 'use-credentials') {
            xhr.withCredentials = true;
        }
...

### Steps to Reproduce
Add 2 resources to load:
loader.add({'some-img.jpg', crossOrigin: 'use-credentials' })
loader.add({'some-img.svg', crossOrigin: 'use-credentials' })
Check request header:
1 - cookie header attached
2 - cookie header is not attached

### Environment
- **`pixi.js` version**:  6.1.3
- **Browser & Version**:  Chrome 95

**Comment by Pi-Bouf** [comment]
Good idea ! Thanks for the fix ! :D
