### ISSUE TITLE
Problem on getting results

### ISSUE THREAD

**Issue by ilovepixi** [pixijs/pixijs#7950]
I maked a copy of your [slot game](https://pixijs.io/examples/#/demos-advanced/slots.js) in [here](https://stackblitz.com/edit/js-62ikpj?file=index.js), when you click on the spin button, then all image names is **not correct**. can you tell me why the **results** are not correct?

![image](https://user-images.githubusercontent.com/93175255/140184076-f61b1697-7bca-4317-b7d9-0268aa4ae32a.png)

I have been involved in this issue for few months. 
I am waiting for you. Thanks

**Comment by ivanpopelyshev** [comment]
line 171-184 in your. Texture is changed, taken new random. "s.name" isnt changed. That's why names dont update.

Btw, you should `s.removeChildren();` to not add more texts as children. or change `s.children[0].text = 'newName';` , because you dont have to re-create Text when you just change it ;)

**Comment by ilovepixi** [comment]
> 
> 
> line 171-184 in your. Texture is changed, taken new random. "s.name" isnt changed. That's why names dont update.
> 
> Btw, you should `s.removeChildren();` to not add more texts as children. or change `s.children[0].text = 'newName';` , because you dont have to re-create Text when you just change it ;)

Sometimes I get really confused for simple things.
Really thanks.
