### ISSUE TITLE
CanvasRenderingContext2D not defined error in SSR application

### ISSUE THREAD

**Issue by mkpoli** [pixijs/pixijs#7958]
### Current Behavior
Cannot compile even with a dynamic import and shims.
( ReferenceError: CanvasRenderingContext2D is not defined )
![image](https://user-images.githubusercontent.com/3502597/140498635-6cc48c5d-8046-4a97-a382-5c04ec92f186.png)

### Possible Solution
This is occured when it upgrades from pixi.js 6.1.3 to pixi.js 6.2.0. It is caused by the following check for letterSpacing / textLetterSpacing in line 1391 from @pixi/text/dist/cjs/text.cjs

`var supportLetterSpacing = 'letterSpacing' in CanvasRenderingContext2D.prototype || 'textLetterSpacing' in CanvasRenderingContext2D.prototype;`

It maybe resolved by check if CanvasRenderingContext2D is undefined beforehand.

### Steps to Reproduce
1. Make a svelte-kit skeleton project. 
2. Install ``pixi.js`` 6.2.0.
2. Import PixiJS dyanamically.

### Environment
- **`pixi.js` version**:_6.2.0_
- **`@sveltejs/kit`**: _1.0.0-next.178_

**Comment by bigtimebuddy** [comment]
We do not support SSR rendering so you'll need to add a global shim for that DOM API.

**Comment by mkpoli** [comment]
Just for who arrived here:

This issue is already resolved by #8045 thanks to #8039, and been released to [pixi.js@6.2.1](https://github.com/pixijs/pixijs/releases/tag/v6.2.1).

So you can still use the original [mszu/pixi-ssr-shim](https://github.com/mszu/pixi-ssr-shim). [My pull request](https://github.com/mszu/pixi-ssr-shim/pull/2) there are still not merged anyway (by the time of this comment
