### ISSUE TITLE
Items outside masks cause crash on windows+chrome+webGL2

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/pixijs#7960]
I *believe* this has something to do with items being completely outside of a mask, but I'm not 100% sure.

### Current Behavior
After a few minutes, chrome hangs and the webGL context is lost

### Possible Solution
disable scissor masking

### Steps to Reproduce
https://jmlee2k.github.io/pixi6-mask-test/ - breaks
https://jmlee2k.github.io/pixi6-mask-test/?noscissor - doesn't break

Here's what shows up in the console when the test case fails:
![image](https://user-images.githubusercontent.com/7396545/140582480-34b2623e-74a8-4af1-9396-416f03bf0b31.png)

### Environment

- **`pixi.js` version**: 6.2.0
- **Browser & Version**: chrome, edge
- **OS & Version**:  windows

- **Running Example**: https://jmlee2k.github.io/pixi6-mask-test/

More info at https://github.com/jmlee2k/pixi6-mask-test

**Comment by ivanpopelyshev** [comment]
So, #7896 might have consequences?

**Comment by jmlee2k** [comment]
@ivanpopelyshev - possibly, but it also happens before #7896 (6.0.0).

**Comment by eXponenta** [comment]
You should present GPU info feom chrome://gpu

Looks like that you run on swift.

Than you should know, that latest chrome drop context when tab is inactive a lot of time.

**Comment by jmlee2k** [comment]
Here's the chrome gpu info from my machine:
[chrome-gpu-info.txt](https://github.com/pixijs/pixijs/files/7497868/chrome-gpu-info.txt)
 
Thanks for the information.
FWIW, it drops the context regardless of whether the tab is inactive or not - it happens when a single tab is open, and the window is focused or unfocused.

**Comment by nz771202** [comment]
Hi, here is another test that causes chrome to hang and lose context. You might have to wait several seconds before it happens.

https://codepen.io/nz771202/pen/qBXwmwQ

First a container is created with a rectangular mask that I suppose Pixi will use as scissor by default. Then several objects are added to that container and a shape mask is applied to them.
