### ISSUE TITLE
GIF Not Supported

### ISSUE THREAD

**Issue by ilovepixi** [pixijs/pixijs#7962]
### Expected Behavior

It is possible to use gif ?

### Possible Solution

`PIXI.Sprite.from('image.gif');`

### Current Behavior

No reaction

**Comment by ivanpopelyshev** [comment]
Here's demo: https://pixiplayground.com/#/edit/wjAO30L8ch8q4RH17uRuS but it doesnt work because `gifuct-js` was changed , author removed UMD version of package. You have to include it through `npm i gifuct-js`, and there you'll get GIF class

**Comment by ilovepixi** [comment]
T

> 
> 
> Here's demo: https://pixiplayground.com/#/edit/wjAO30L8ch8q4RH17uRuS but it doesnt work because `gifuct-js` was changed , author removed UMD version of package. You have to include it through `npm i gifuct-js`, and there you'll get GIF class
> 
> There's no other way of doing this.

I can use gif images with other packages, but this is strange why pixijs can't support this.
