### ISSUE TITLE
scaled images have rough edges

### ISSUE THREAD

**Issue by rizen** [pixijs/pixijs#7973]
### Expected Behavior

I would like my textures to be scaled with smooth edges.

### Current Behavior

I have tried setting antialiasing on, and using SCALE_MODE. I tried round pixels. None of it seems to have any change at all actually. Which makes me think that perhaps there's something wrong with these features, or I'm using them wrong.

I noted that my texture.baseTexture._scaleMode does seem to change between 1 and 0, so the setting is being set, but not sure it's doing anything.

### Possible Solution

No clue.

### Steps to Reproduce

I've created a fiddle to show a full size image and a scaled down one so you can see the edges.

https://jsfiddle.net/plainblackguy/1eg2hqbL/14/

<img width="297" alt="Screen Shot 2021-11-08 at 2 01 40 AM" src="https://user-images.githubusercontent.com/170009/140705012-dbdaa856-8c20-4526-b865-6cb7db81fc53.png">

### Environment

- **`pixi.js` version**: 6.2.0
- **Browser & Version**: Safari 14.2 and Chrome 95.0.4638.54
- **OS & Version**: Mac OS 11.6
- **Running Example**: https://jsfiddle.net/plainblackguy/1eg2hqbL/14/

**Comment by eXponenta** [comment]
AA not working on texture.
I see that texture is 300x300 - bad idea.
Use POT textures or enable mipmaps - all will ok.
By default mipmaps enabled only for POT textures.

Note that for Webgl1 mipmap supported only on POT textures.

POT - power of two, 128x12, 256x256 etc

**Comment by rizen** [comment]
Thank you so much for this info.
