### ISSUE TITLE
When using 2 TilingSprites with separate textures, the second appears as a single pixel

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/pixijs#7976]
### Expected Behavior
Both TilingSprites should be fully visible
### Current Behavior
Second TilingSprite shows as a single pixel

### Test cases
in 6.1.0, both TilingSprites display as expected: https://jmlee2k.github.io/pixi6-tilingsprite-test/index-610.html

in 6.2.0, the second tiling sprite only shows as a single pixel: https://jmlee2k.github.io/pixi6-tilingsprite-test/index-620.html

### Environment

- **`pixi.js` version**: 6.2.0
- **Browser & Version**: Chrome, Firefox
- **OS & Version**: windows 10, macOS
- **Running Example**: https://jmlee2k.github.io/pixi6-tilingsprite-test/index-620.html

**Comment by jmlee2k** [comment]
@ShukantPal  - I tried it with #7792 reverted, and it appears as expected, so the issue is either there, or something else in 6.2.0 not playing nicely with it.

https://jmlee2k.github.io/pixi6-tilingsprite-test/index-620-revert-7792.html

**Comment by jmlee2k** [comment]
While doing further tests, I found that the second TilingSprite **WILL** render properly if it's not a power-of-2 texture.

**Comment by eXponenta** [comment]
This is device specific bug.
Plz, attache a screen because i again cannot reproduce a bug.

**Comment by jmlee2k** [comment]
Thanks for looking into this.  My colleagues and I have tried it on several desktop machines (including macOS, win integrated graphics, win discrete AMD) in different browsers, and we are always able to produce the issue.  It does **NOT** appear to occur on firefox or chrome on android.

Here's the chrome GPU info for a machine with discrete AMD gfx where I'm able to produce the issue: [chrome-webgl-info.txt](https://github.com/pixijs/pixijs/files/7505060/chrome-webgl-info.txt)

**Comment by domis86** [comment]
I confirm this on Ubuntu 20 with Chrome 95 and Firefox 86

**Comment by jramstedt** [comment]
Windows 10, Chrome Version 95.0.4638.69 also.
GeForce GTX 1060 3GB, 466.77 drivers.

**Comment by jmlee2k** [comment]
Confirmed on a brand new machine (Intel(R) Alderlake-S Mobile Graphics Controller).
[chrome-gpuinfo.txt](https://github.com/pixijs/pixijs/files/7534617/chrome-gpuinfo.txt)

**Comment by GoodBoyDigital** [comment]
hey all! poking around on this now. An immediate fix is to switch to WebGL 1, this seems to fix the issue! Will look for a proper fix now though...

**Comment by bigtimebuddy** [comment]
This had been fixed in #7827 

https://jsfiddle.net/bigtimebuddy/t8u03n4x/

Thanks @dev7355608 bounty for this issue is your's if you'd like.
