### ISSUE TITLE
Character from text not being rendered correctly in Chrome

### ISSUE THREAD

**Issue by ramako** [pixijs/pixijs#7982]
Using the font Carter One,  the T character is  incorrectly rendered in chrome, but rendered correctly in Safari. I have tried using lineJoin and miterLimit just in case they would solve this, but does not.

### Expected Behavior
 T character is rendered correctly like in iOs safari
![image](https://user-images.githubusercontent.com/8879857/141132033-7cde6952-48f1-42e1-a62b-3b022c9c64ba.png)

### Current Behavior
![image](https://user-images.githubusercontent.com/8879857/141131057-567633fb-b02b-4732-9835-d3cf886c0bb4.png)

### Steps to Reproduce
Create the text with an uppercase T using Carter One font. It is not rendered correctly on chrome, but using iOs safari, it gets rendered correctly.
### Environment

- **`pixi.js` version**: _6.1.3_
- **Browser & Version**: _Chrome 95.0.4638.69_
- **OS & Version**: _Windows 10 _

**Comment by eXponenta** [comment]
Because pixi use a Canvas2D for Text - this is bug with font in Chrome.

Plz, create a minimal reproduced demo for this bug.
