### ISSUE TITLE
ticker cant stop

### ISSUE THREAD

**Issue by YangLG-7** [pixijs/pixijs#7988]
In my project

I have some coexisting tickers on different occasions。

But when I stop one of tickers，All of tickers is stop。

like `  let i =0;
    const tickerX =  app.ticker.add(()=>{
      i += 0.1
    });
    let j =0;
    const tickerY =app.ticker.add(()=>{
      j += 0.1
    });`

If I use `tickerY .stop()` ，All of My tickers is stop；

This is a simple version[https://codepen.io/yanglg-7/pen/MWvBXrY?editors=1111](url)

Is it the wrong way I use it?

My version `pixi.js:6.1.3 @pixi/events:6.2.0`

**Comment by bigtimebuddy** [comment]
For support, please use discussions. I see you already created #7987, closing this.

**Comment by YangLG-7** [comment]
@bigtimebuddy  Is it the wrong way I use it? I really want to know

**Comment by YangLG-7** [comment]
@bigtimebuddy   hi~，Thanks Reply，could you help me solve this problem ? Is the way I use the ticket wrong?
