### ISSUE TITLE
HOW TO USE pixijs Create sprites based on pixels

### ISSUE THREAD

**Issue by a6965921** [pixijs/pixijs#8001]
`let d = new PIXI.Sprite('#F00’)`

**Comment by jramstedt** [comment]
You can draw filled rectangle with https://pixijs.download/dev/docs/PIXI.Graphics.html

**Comment by a6965921** [comment]
> You can draw filled rectangle with https://pixijs.download/dev/docs/PIXI.Graphics.html

i want add to particlecontainer

**Comment by angiagia** [comment]
> > You can draw filled rectangle with https://pixijs.download/dev/docs/PIXI.Graphics.html
> 
> i want add to particlecontainer
Try this one 
var sprites = new PIXI.particles.ParticleContainer(10000, {
    scale: true,
    position: true,
    rotation: true,
    uvs: true,
    alpha: true
});
