### ISSUE TITLE
pixi.js load image from IndexedDB Blob not work

### ISSUE THREAD

**Issue by hsinyu-chen** [pixijs/pixijs#8014]
for some reason I store texture image Blob in the `IndexedDB`
but when I try to load it to Texture use `PIXI.Loader` by following code

```typescript
import {  Loader} from 'pixi.js';

async readTexture(texturekey: string, blob: Blob) {
    if (Loader.shared.resources[texturekey]) {
        return Loader.shared.resources[texturekey].texture;
    }
    return await new Promise<Texture | undefined>(ok => {
        const url = URL.createObjectURL(blob);
        Loader.shared.add(texturekey, url, () => {
            URL.revokeObjectURL(url);
        }).load((ldr, res) => {
            ok(res[texturekey].texture); // res[texturekey].texture is undefined
        });
    })
}
```

code executed without exception but `res[texturekey].texture` is undefined,
same code with real image url works fine,
is the `Pixi` can't loading Texture from ObjectURL or I'm doing something wrong?

I also tried another way
```typescript
import { BaseTexture, Texture } from 'pixi.js';

var img = new Image();
img.addEventListener("load", event => {
    URL.revokeObjectURL(img.src)
    new PIXI.Texture((new PIXI.BaseTexture(img));
})
img.src = URL.createObjectURL(blob);
```

this works fine if I use loaded Texture with static Sprite
but if I use it with `AnimatedSprite` it throw exception
`Unhandled Rejection (TypeError): Cannot read properties of undefined (reading '_uvs')` on `AnimatedSprite` constructor, I dig it a bit and I found this is cause by `AnimatedSprite.ts`
```typescript
set textures(value: Texture[]|FrameObject[])
    {
        if (value[0] instanceof Texture) // this line return false 
        {
            this._textures = value as Texture[];
            this._durations = null;
        }
        else
        {
            this._textures = [];
            this._durations = [];

            for (let i = 0; i < value.length; i++)
            {
                this._textures.push((value[i] as FrameObject).texture);
                this._durations.push((value[i] as FrameObject).time);
            }
        }
        this._previousFrame = null;
        this.gotoAndStop(0);
        this.updateTexture();
    }
```
but I check the parameter and it is `Texture[]` , and I also check I'm imported `Texture` from 'pixi.js' everywhere  , which is very wired

**Comment by bigtimebuddy** [comment]
If you have a Blob, the easiest way to load it with PIXI is to do this. Loader isn't designed to accommodate Blob URLs.

```js
const url = URL.createObjectURL(blob);
const texture = await PIXI.Texture.fromURL(url);
URL.revokeObjectURL(url);
```

I [cannot reproduce](https://jsfiddle.net/bigtimebuddy/krfegp4u/) your second issue with AnimatedSprite, you'll need to provide a reproduction.

```js
const sprite = new PIXI.AnimatedSprite([texture]);
sprite.textures = [texture];
```

I've seen issues like this (e.g. `instanceof`) in some cases where a project has multiple copies of`@pixi/core` because of an upgrade issue or because of a plugin adding dependencies. Please double check your package-lock.json and make sure you only have a single version.

**Comment by hsinyu-chen** [comment]
I checked all `@pixi/core` version in package-lock.json is all `6.2.0` , for now I'm checking other things may cause this issue,
I'll post what cause this if I found it.

**Comment by hsinyu-chen** [comment]
turn out is a react or react/craco related issue, combine with `npm install <local folder>`   cause this ,
temporary move my helpers to `src` folder fix this .
