### ISSUE TITLE
Black textures for some users sometimes

### ISSUE THREAD

**Issue by mikecann** [pixijs/pixijs#8018]
Hi, 

We have a popular web game that uses PixiJS: https://battletabs.io/

Ever since the start we have had occasional reports from users about sometimes seeing black textures in the game.

For example:

![image](https://user-images.githubusercontent.com/215033/143510885-ae64b52a-1fa6-4dae-be67-b5a9eb127a58.png)

![image](https://user-images.githubusercontent.com/215033/143510891-47ff87fe-f2fa-4b33-9012-72519ed8ab94.png)

![image](https://user-images.githubusercontent.com/215033/143510894-ca1f75f1-e6bc-4eb2-8cc4-50228f4839e7.png)

This only happens to some users and only sometimes. It seems like refreshing the page generally fixes it. 

I have Googled for this issue a few times and from what I can gather it is the browser / GPU running out of memory or it is a memory corruption issue of some sort.

Has anyone else experienced this? Is there anything that can be done about it?

**Comment by eXponenta** [comment]
So, look like as memory issues.
GPU can't upload textures that required for render or kill already existed.

This is one of problem on Safary 15 on all platforms and there are not a easy solution.

1. Up PIXI version to latest stable minor version.
2. Reduce texture resolution, use compresed texture formats
3. Use manual managed textures (destroy/unload manually what you not required at this moment)
4. Reduce filters count, use pre-cached filters

See:
https://github.com/pixijs/pixijs/discussions/7928
https://github.com/pixijs/pixijs/discussions/8000
https://github.com/pixijs/pixijs/issues/7983
https://github.com/pixijs/pixijs/issues/7864

And some bugs on latest chrome:

https://github.com/pixijs/pixijs/issues/7960

**Comment by mikecann** [comment]
Okay thanks :)
