### ISSUE TITLE
How to run in the built-in browser of facebook for android

### ISSUE THREAD

**Issue by js-zahgn** [pixijs/pixijs#8023]
My pixijs applicatiion does not work in android facebook app browser

**Comment by js-zahgn** [comment]
- **`pixi.js` version**: _e.g. 6.1.3_
- **Browser & Version**: _e.g. facebook browser 67_
- **OS & Version**: _e.g. android 18.04_
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment]
Please provide more details

**Comment by js-zahgn** [comment]
The problem has been solved

**Comment by bigtimebuddy** [comment]
When closing your issue, it's helpful to provide the resolution of how you solved it. Makes it more useful for people searching later.
