### ISSUE TITLE
InteractionManager mouseover/out bug

### ISSUE THREAD

**Issue by s-r-x** [pixijs/pixijs#8027]
Check the video first:

https://user-images.githubusercontent.com/41614937/144700573-2c6268d2-d421-4aa5-a479-80a57283fbee.mp4

Mouseup/down and other events works fine, but mouseover/out is completely stuck. After hours of debugging i've noticed that some browsers(probably, all of them, but i tested  only chrome) are triggering mouseover event, when you move the mouse for the first time, after the page was loaded. In this case, interaction works fine. But this one only happens after reloading the page(not all the time, though). When you visit  the url for the first time - there is no such event, and interaction stucks forever, until you trigger this event manually, by moving the mouse outside of the element(which, in my case, was the whole viewport)

```javascript
document.body.onmouseover = () => console.log("over");
```

https://user-images.githubusercontent.com/41614937/144700544-8408e413-4d7b-4c92-a7a8-71a5a95c8519.mp4

Somehow everything starts to work when you manually call interaction.onPointerOver with a new MouseEvent after initializing the app:
```javascript
app.renderer.plugins.interaction.onPointerOver(
  new MouseEvent("mouseover")
);
```

### Possible Solution
see above
### Steps to Reproduce

- clone the [repo](https://github.com/s-r-x/pixi-mouseover-bug-reproduction)
- run the example in your favorite browser, hover over the text
- if it works, open the same url in a new tab, repeat the previous step

### Environment

- **`pixi.js` version**:  6.2.0
- **Browser & Version**:  Chrome 95.0.4638.69, Firefox 94.0
- **OS & Version**: Ubuntu 20.04

**Comment by andrewstart** [comment]
Hmm, it seems like a case where the canvas is visible before the interaction plugin is initialized - the browser already dispatched the `mouseover` event when there was no listener for it, and once we add one it is too late, you have to `mouseout` before you can get a new one. 
Another solution would be to hide the canvas until you have initialized your `Application` (I imagine a lot of people do something like this with a loading animation). @ShukantPal do you know if would be problematic in either the current interaction package or the events package to have a one time document level `mousemove` listener to set the initial `mouseOverRenderer` state?
