### ISSUE TITLE
Graphics: transparent lines with bezier curves have overlapping area at join

### ISSUE THREAD

**Issue by carefree0910** [pixijs/pixijs#8032]
### Expected Behavior
No overlapping area at join

### Current Behavior
<img width="921" alt="截屏2021-12-07 上午9 33 32" src="https://user-images.githubusercontent.com/15677328/144952649-53705f2d-3817-402c-9c0d-5784f3991650.png">

### Possible Solution
Not sure, this might be something deeeeep XD

> A workaround is to draw lines without opacity and then apply filters to them, but it seems to have some side effects (e.g. it's hard to tell what the `filterArea` should be)

### Steps to Reproduce
The line shown in the above picture is constructed by two lines and a bezier curve connecting them, please refer to the link below for details

### Environment

- **`pixi.js` version**: _latest_
- **Browser & Version**: _Chrome_
- **OS & Version**: _MBP M1_
- **Running Example**: [fiddle](https://jsfiddle.net/dkv9bywj/5/)

**Comment by GoodBoyDigital** [comment]
heya! this is the nature of WebGL im afraid! You can always use AlphaFilter to make this alpha out in as a solid block. OR render the line to a texture and alpha that in and out!  Hope that helps
