### ISSUE TITLE
Checking for modern letterSpacing API breaks throws an error

### ISSUE THREAD

**Issue by JoshuaPelealu** [pixijs/pixijs#8039]
### Expected Behavior
The app to not throw an error at the beginning of the runtime

### Current Behavior
On runtime, when Javascript does a little evaluation, the app will throw a `ReferenceError: CanvasRenderingContext2D is not defined`
This will cause the canvas to not render anything.
![image](https://user-images.githubusercontent.com/45566099/145698805-cec17aac-3220-45a5-8b41-44574a00a8f2.png)

### Possible Solution
 I encountered this when I was trying to refactor my project into a new one, and this error came up. After hours of debugging, I realised that it's on different versions of pixi.js and surely enough. The 6.2.0 version broke my app and after a little digging, that's what's caused it and I found the commit that caused me trouble which is [b52a1bed75735fdfe6bc9c30e0783c2bdd0224de](https://github.com/pixijs/pixijs/commit/b52a1bed75735fdfe6bc9c30e0783c2bdd0224de). 

A possible solution maybe check if it exists in the first place so it wouldn't throw the reference error. Or check it when the browser environment is fully running

### Steps to Reproduce
Clone this repository:
https://github.com/JoshuaPelealu/seatingchart

run `npm i`
then `npm run dev`
and boom, the error pops up, and the app wouldn't work

I know that this app is SSR, but in my code, I have used a shim for the DOM, and again, I have made a working version of this app just using 6.1.3 and here's the repository: 
https://github.com/JoshuaPelealu/pixijstest/blob/main/package.json#L21

running working example: 
https://toce-canvas.vercel.app

### Environment

- **`pixi.js` version**: 6.2.0
- **Browser & Version**: Firefox Developer Edition 96.0b3
- **OS & Version**: Ubuntu 20.04
- **Running Example**:  https://github.com/JoshuaPelealu/seatingchart

**Comment by bigtimebuddy** [comment]
Cc @eXponenta

**Comment by eXponenta** [comment]
This is because SSR execute text module server side.

You should move this:
https://github.com/pixijs/pixijs/blob/dev/packages/text/src/Text.ts#L32

Onto this:
https://github.com/pixijs/pixijs/blob/dev/packages/text/src/Text.ts#L326

**Comment by bigtimebuddy** [comment]
@JoshuaPelealu We do not support SSR in Pixi right now. Either add this to your shim or PR welcome for @eXponenta suggestion to not have this run at load time.
