### ISSUE TITLE
Should I clear FilterSystem.texturePool  manually ?

### ISSUE THREAD

**Issue by TripleTre** [pixijs/pixijs#8054]
I found some RenderTexture  not destroyed after I destroy Application,  which create at 

[FilterSystem.ts#L214](https://github.com/pixijs/pixijs/blob/dev/packages/core/src/filters/FilterSystem.ts#L214)

and the destroy method sayed 

> Those textures has to be destroyed by RenderTextureSystem or FramebufferSystem

[FilterSystem.ts#L484](https://github.com/pixijs/pixijs/blob/dev/packages/core/src/filters/FilterSystem.ts#L484)

But RenderTextureSystem and FramebufferSystem there destroy method just set this.renderer to null.

[RenderTextureSystem.ts#L248](https://github.com/pixijs/pixijs/blob/dev/packages/core/src/renderTexture/RenderTextureSystem.ts#L248)
[FramebufferSystem.ts#L729](https://github.com/pixijs/pixijs/blob/dev/packages/core/src/framebuffer/FramebufferSystem.ts#L729)

before I call `app.renderer.filter.texturePool.clear(true)`, there is 22 BaseTexture not destroyed.

![image](https://user-images.githubusercontent.com/15083905/146495340-f527d38b-f03b-4928-a61c-a53e711f66c1.png)

and if I call `app.renderer.filter.texturePool.clear(true)` manually,  they has destroyed

![image](https://user-images.githubusercontent.com/15083905/146495471-5ad8e9b4-a867-45f7-8478-2323c41e421b.png)

**Comment by GoodBoyDigital** [comment]
Closing out - in v8  The textures are reused across all render instances as TexturePool is global. It can be cleared via `TexturePool.clear()` 👍
