### ISSUE TITLE
How does pixijs scale its view?

### ISSUE THREAD

**Issue by SlimEconomy** [pixijs/pixijs#8063]
When I scale the view using the built in `scale` attribute and then compare it with me scaling the entire view by hand, the application is much more zoomed in when I am doing it by hand compared to pixi doing it. I am using the same zoom factor for both but pixijs doesn't seem to just multiply x and y values by that value, it must be doing something else as well. Is there a way for me to replicate the scale behaviour of pixi?
### Expected Behavior
pixi to scale both x and y both a value
### Current Behavior
seems to be doing something else as well

**Comment by bigtimebuddy** [comment]
Not sure I completely understand your description. Could you give a code or runnable example that illustrates the two types of scaling you're trying to do?

**Comment by SlimEconomy** [comment]
https://www.pixiplayground.com/#/edit/2VM_cq7XKFhKZ-SS78ON8

Here there is a rectangle being drawn. After one second the green rectangle is scaled using pixis scaling. After another second the rectangle (purple) gets scaled by hand. They should be overlapping but they aren't. Am I missing something here?

**Comment by domis86** [comment]
@SlimEconomy  i modified your example : https://www.pixiplayground.com/#/edit/2VM_cq7XKFhKZ-SS78ON8

this part:

```

let rectanglePixi = drawRectangle(2676254, 1);

//draw zoomed by pixi
setTimeout(() => {
    // app.stage.scale.x = zoom;
    // app.stage.scale.y = zoom; 
    rectanglePixi.scale.x = zoom;
    rectanglePixi.scale.y = zoom; 
}, 1000)

```

^ the `app.stage.scale.x = zoom;` was scaling whole `app.stage` container - but IMO what you wanted to do is scale only the rectangle. I modifed it to scale only rectangle and now both rectangles overlap :)

**Comment by SlimEconomy** [comment]
> @SlimEconomy i modified your example : https://www.pixiplayground.com/#/edit/2VM_cq7XKFhKZ-SS78ON8
> 
> this part:
> 
> ```
> 
> let rectanglePixi = drawRectangle(2676254, 1);
> 
> //draw zoomed by pixi
> setTimeout(() => {
>     // app.stage.scale.x = zoom;
>     // app.stage.scale.y = zoom; 
>     rectanglePixi.scale.x = zoom;
>     rectanglePixi.scale.y = zoom; 
> }, 1000)
> ```
> 
> ^ the `app.stage.scale.x = zoom;` was scaling whole `app.stage` container - but IMO what you wanted to do is scale only the rectangle. I modifed it to scale only rectangle and now both rectangles overlap :)

Thank you for that but let me explain, why it is important to have the stage scaling overlap with each elements scaling. I am using the scale method from pixi to zoom into the image. After that is done, I am redrawing all elements by hand (removing all children and drawing again) by zooming each of them by hand by multiplying them by the zoomfactor. I am redrawing the stage simply for resolution, so the picture doesn't appear blurry after it's being scaled. And the problem I am facing is like shown in the playground example. I have a rectangle in the original view which I scale first by using pixi. Then I am redrawing the rectangle in the background by using the zoom factor that was also used for the pixi scaling. What I want to achieve is the user to not realize that the stage was first scaled and then redrawn for better resolution. But since the image is not overlapping but moving, it doesn't achieve that effect

**Comment by domis86** [comment]
Ok, please consider another variant: https://www.pixiplayground.com/#/edit/xBo8sbv5cEnYqtVJ72s86
* i added 2 "layers" (which are PIXI.Container) to stage: `layer1`, `layer2`
* first rectangle (the "pixi scaled" one) is drawn in `layer1`
* second rectangle (the "hand scaled" one) is drawn in `layer2`
* then in first timeout the `layer1` is scaled using "pixi scaling"
* and in second timeout the second rectangle is drawn using "hand scaling" 
* they both overlap

What you think about this approach?

**Comment by domis86** [comment]
Why i used 2 layers? 
Because if you have only one layer (the `app.stage`) then if you scale it then you scale all objects in it - so you scale both rectangles. Then if you draw second rectangle with bigger (manually multiplied) height and width then of course it is drawn bigger on the screen (because it has bigger dimensions from manual multiplying and additionally from the scale).

**Comment by SlimEconomy** [comment]
You are right, but then I would always need to have all elements drawn twice. First in the second layer and then their manually scaled versions in the second. That would decrease the performance.

**Comment by domis86** [comment]
It seems i dont understand the problem then.
Can you create/modify your working example including "PIXI.Viewport" and "redrawing" aspects as you described it in previous comment? : https://github.com/pixijs/pixijs/issues/8063#issuecomment-1000282758

Maybe then would be easier to see what is the real problem we are trying to solve.

**Comment by SlimEconomy** [comment]
I have fixed the issue: https://www.pixiplayground.com/#/edit/2VM_cq7XKFhKZ-SS78ON8

You can simply just set the scale back to 1 after you have manually scaled and redrawn the stage.
