### ISSUE TITLE
Canvas is black when using cdn provided in guide

### ISSUE THREAD

**Issue by austinthetaco** [pixijs/pixijs#8068]
I'm following the guide on the [PixiJS website](https://pixijs.io/guides/basics/getting-started.html), using the cdn provided `<script src="https://pixijs.download/release/pixi.js"></script>`.
Without implementing any other changes other than initializing the canvas:
```js
let app = new PIXI.Application({ width: 640, height: 360 });
document.body.appendChild(app.view);
```
And here is what I see:

![image](https://user-images.githubusercontent.com/7856196/147289281-029d766d-1db4-4d08-9003-4bc092d00477.png)

I initially thought it was the inclusion of the sprite from the guide (I've heard images can cause canvas transparency issues), but after removing it the issue still persists (as in the screenshot). Hopefully I haven't missed any crucial info in the guide. 

- **`pixi.js` version**: PixiJS 6.2.1
- **Browser & Version**: Chrome Version 96.0.4664.110
- **OS & Version**:  Windows 10

**Comment by domis86** [comment]
This looks like correct behaviour: canvas with default (black) color.
If you want to change background color then you can do like this: https://www.pixiplayground.com/#/edit/RzdxdPiRHGKqEpi-nLA3N

(btw: next time you can use https://www.pixiplayground.com to prepare working example and paste link to it in issue/discussion here on github. This way people will be able to help you faster)
