### ISSUE TITLE
require is not defined ("URL") only in browser 

### ISSUE THREAD

**Issue by nonodev96** [pixijs/pixijs#8070]
Hi, I do not know if this is the correct place to write this, I am using pixi together with angular and electron, but when building for the web version it does not find "URL"

Uncaught ReferenceError: require is not defined ("URL")
This not works in browser, but yes with the electron app 😕 

### Steps to Reproduce
clone [maximegris/angular-electron](https://github.com/maximegris/angular-electron)
install pixi.js
ng g c component view/pixi
add pixi to component
npm run build:prod

### Environment
- **`pixi.js` version**: _e.g. 5 and 6
- **Angular Version**: _e.g. 12
- **angular-builders/custom-webpack Version**: _e.g. 12
- **OS & Version**: _e.g. MacOS monterey
- **Running Example**: [Angular-PIXI-web](https://angular-electron-tests.netlify.app/)

**Comment by cjackson234** [comment]
@nonodev96 did you ever get this solved?

**Comment by nonodev96** [comment]
Hi, yes, you can close this issue.

I don't remember exactly what happened in that version, I remember that I solved it using services and modifying the `window` in index.html
 
Thx ✌

This is the [project](https://github.com/nonodev96/THUMDER/tree/dev/src/app/components/pixi-cycle-clock-diagram) where you had the problem and I solved it
