### ISSUE TITLE
`notMultiplied` for `useContextAlpha` renderer option missing in the docs

### ISSUE THREAD

**Issue by bencresty** [pixijs/pixijs#8073]
'By accident' I bumped into an example that turns of pre-multiply from the renderer (`transparent: 'notMultiplied'`), so I was wondering what else is possible to set the `transparent` option of the renderer to.

I couldn't find the option in the docs, so looked in the code. To find out the `useContextAlpha` seem to do the same thing, so looks like an alias. 

`useContextAlpha` is in fact mentioned in the docs. However it tells us nothing about a `'notMultiplied'` value and only tells us to not fiddle around with the setting.
![image](https://user-images.githubusercontent.com/69322733/147466922-97430e20-4de7-4674-9959-f12984734b76.png)

IMO the `'notMultiplied'` option is an important option to know for people understanding the difference between straight and pre-multiplied and should at least be mentioned there in the docs as a possible value to put in there. 
According to the docs the option accepts only boolean values, but obviously this particular string is accepted too. 
It might be me, but it looks like this option is ONLY useful to use with the `notMultiplied` value in it, as when setting `useContextAlpha` to `false` it looks like the same thing as setting the `backgroundAlpha` to `0`, which would make the option obsolete IMO. But I didn't deep dive in the code, so I might be missing something here.

IMO the `notMultiplied` option should be mentioned in the docs.

- **`pixi.js` version**: 6.2.1

**Comment by ryushar** [comment]
> Pass-through setting for the the canvas' context `alpha` property. Passing 'notMultiplied' will set the canvas' context `alpha` property to true and `premultipliedAlpha` to false. This is typically not something you need to fiddle with. If you want transparency, use `backgroundAlpha`.

If this definition is fine then I can make a PR for it

**Comment by terekite** [comment]
@bigtimebuddy Since this is a 6.x issue - does it make sense to update the documentation for `useContextAlpha` in the 6.x version, since it doesn’t get updated on the PixiJS homepage?

**Comment by bigtimebuddy** [comment]
Doc changes for v6 are fine! PR still welcome here

**Comment by MasonJason23** [comment]
Hey @bencresty @bigtimebuddy ,
@terekite and I are trying to get an example running to understand what @bencresty meant by his new definition for `useContextAlpha` but at the same time, we are having some trouble.
How/where are you passing the string `notMultiplied`? Are you simply just giving the `useContextAlpha` member that value?
I tried to pass values into `useContextAlpha` via something like...
`renderer.useContextAlpha = 'notMultiplied'`
I noticed no changes. I am not sure what we are supposed to be looking for and also whether my running code is a good example to see any results.

@terekite tried doing this: `const app = new PIXI.Application({ useContextAlpha: 'notMultiplied'})`, however, it didn't look to me that passing that string was doing anything to change the default value of `backgroundAlpha`. Also, we couldn't find where the member `premultipliedAlpha `was accessed from − is it from `app.renderer`?

**Comment by sunveer2001** [comment]
Hi @bencresty, it seems like useContextAlpha does not function the same way as transparent based on my testing. While changing useContextAlpha I found that it does not have any effect on backgroundAlpha but, any changes to transparent are mirrored in useContextAlpha. Ex. changing transparency to true/false/"notMultiplied" results in useContextAlpha being changed to true/false/"notMultiplied". This leads me to believe that useContextAlpha is a pass thru variable as stated in the documentation and has no significance in changing the background. Hope this helps!
