### ISSUE TITLE
Unexpected line appears on overlapping textures when antialiasing is turned on

### ISSUE THREAD

**Issue by Redgeioz** [pixijs/pixijs#8086]
It may look like this when the textures partially overlap:
![)_ 8V$7@HB_ %Y0K`A6U1G](https://user-images.githubusercontent.com/52198272/148336564-956ee747-afef-49d9-bcf5-afc23ede9e26.png)

When the textures completely overlap:
![I N}3S2 0Q)(V5VBHD@Y E](https://user-images.githubusercontent.com/52198272/148336653-1ce88970-7ef7-440e-a88a-26c13c9b421d.png)

Example:
```jsx
const app = new PIXI.Application({
    antialias: true,
    backgroundColor: 0xffffff,
    height: 2048,
    width: 2048,
});

document.body.appendChild(app.view);

const r = 256;
const canvas = document.createElement('canvas');
canvas.width = canvas.height = r * 2;
const ctx = canvas.getContext('2d');
ctx.fillStyle = '#ffffff';
ctx.beginPath();
ctx.arc(r, r, r, 0, Math.PI * 2);
ctx.fill();

const texture = PIXI.Texture.from(canvas);

let container = new PIXI.Container();

let a = new PIXI.Sprite(texture);
a.tint = 0x0000ff;
a.position.set(128, 128);

let b = new PIXI.Sprite(texture);
b.tint = 0x00ffff;

container.addChild(a, b);
app.stage.addChild(container);

let m = 1.004
app.ticker.add(() => {
    if (container.scale.x > 1.1) {
        m = 0.996;
    } else if (container.scale.x < 0.25) {
        m = 1.004;
    }
    
    container.scale.x *= m;
    container.scale.y *= m;
});
```

**Comment by ivanpopelyshev** [comment]
Depends on device. Welcome to webgl.

**Comment by bigtimebuddy** [comment]
@Redgeioz Could you provide more information about your environment (browser, os)?

Here's a working reproduction: https://jsfiddle.net/bigtimebuddy/hkLnz5o2/

I'm not reproduce this on latest Chrome on macOS or iOS.

**Comment by Redgeioz** [comment]
> @Redgeioz Could you provide more information about your environment (browser, os)?
> 
> Here's a working reproduction: https://jsfiddle.net/bigtimebuddy/hkLnz5o2/
> 
> I'm not reproduce this on latest Chrome on macOS or iOS.

### Environment
* **`pixi.js` version**:  6.2.1
* **Browser & Version**: Egde 96.0.1054.62
* **OS & Version**: Windows 10

**Comment by GoodBoyDigital** [comment]
closing out as stale! I don't have edge, but it this looks ok on chrome and safari!
