### ISSUE TITLE
extract API side effect

### ISSUE THREAD

**Issue by bchevalier** [pixijs/pixijs#8115]
Let's considering the following code:

```js
const globalTransformBeforeExtract = container.transform.globalTransform.clone();
const image = renderer.plugins['extract'].image(myContainer);

console.log(container.transform.globalTransform, globalTransformBeforeExtract);
```

### Expected Behavior
To have the 2 transformation matrices identical

### Current Behavior
The 2 transformation matrices are different

### Possible Solution
I fixed it by manually calling `myContainer.parent.updateTransform();` right after the call to the extract API.

My guess is that `myContainer`'s global transformation is modified by the extract API for rendering purposes. But it is not reset properly.

I would suggest either documenting the behavior as normal, or resetting properly the global transformation of containers within the extract API.

**Comment by GoodBoyDigital** [comment]
this should be fixed in v8 - transforms should always remain the same even after extract.
