### ISSUE TITLE
pointermove always triggers, even when out of bounds

### ISSUE THREAD

**Issue by bchevalier** [pixijs/pixijs#8117]
This is to suggest an improvement.

The `pointermove` event always triggers, even when the cursor is out of the bounds of the container.

I understand that this is the expected behavior for performance purposes. However, this does not correspond to equivalent HTML behavior where the `pointermove` event only triggers when hovering over the given element.

My suggestion is simply to specify this particularity in the documentation. Along with the Pixi-way of replicating the default HTML behavior:
```js
let isInside = false;

myContainer.on('pointerup', () => {
    isInside = true;
});

myContainer.on('pointerupoutside', () => {
    isInside = false;
});

myContainer.on('pointermove', (event: InteractionEvent) => {
    if (isInside) {
        // cursor is inside
    }
});

```

**Comment by bigtimebuddy** [comment]
Can you specify if you're using `@pixi/events` or the old InteractionManager?

**Comment by Zyie** [comment]
Closing this as it was using pixi 6 which was the correct behaviour for v6

In v7 `pointermove` now behaves like the DOM and `globalpointermove` was added to replicate the v6 behaviour

**Comment by Amansaxena001** [comment]
@Zyie the issue still persists on pixi v7 where the pointermove is always triggering even when hovering over a html modal over the canvas
