### ISSUE TITLE
4K sprite on mobile

### ISSUE THREAD

**Issue by Nawarius** [pixijs/pixijs#8120]
Hello!

I have code like this

```
const tiling = new PIXI.TilingSprite(texture, texture.orig.width, texture.orig.height)
```
The texture is taken from `app.loader.resources["textureName"].texture`

Everything works great until `texture.orig.width` and `texture.orig.height` are greater than 2048

When I use 4k textures and log in from a mobile device, I see a black screen

I have several questions about this:
1) Is this a PIXI problem? If tomorrow, magically, all phones in the world start supporting 4k textures, will I not have to change anything in the code to make everything work?
2) I read in other questions on a similar topic that it is possible to somehow cut 4K textures into parts of 1024 and 2048 pixels. Then glue them somehow. Pixie has functionality for this? Could you tell us more about this?
3) Maybe there is some way to compress textures from 4k to 2k on the fly? Does such an idea have a right to life? PIXI has functionality for this?
4) Maybe there are some other solutions to this problem that I did not come up with?

Thanks!

**Comment by jasonsturges** [comment]
With iOS, I believe the WebGL max texture size is 4,096 - it would happen with any WebGL based framework.

Use a site like https://webglreport.com on the device to inspect capabilities.

To exceed that, you'd need a tile sprite implementation.

**Comment by GoodBoyDigital** [comment]
closing as this has a good answer! 👍
