### ISSUE TITLE
TypeError: Cannot read properties of null (reading '_batchEnabled')

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [pixijs/pixijs#8123]
I could not replicate this issue during development. But on the user's machine this typeerror occurs. I have attached the stack screenshot.
![image](https://user-images.githubusercontent.com/16081083/150482732-66026c8e-66f8-4103-9e10-8f230993d99a.png)

### Environment

- **`pixi.js` version**: 6.1.1
- **Browser & Version**: Chrome 97.0.4692
- **OS & Version**: Windows
Version:10

**Comment by domis86** [comment]
> this typeerror occurs

What error? Image which you posted shows only partial screenshot of some stack trace. Is hard to know whats happening.

Please post full error, full stack trace (best would be text version, not image) and related source code fragment(s) (where the error is happening).
