### ISSUE TITLE
PixiJS-Legacy unknown error

### ISSUE THREAD

**Issue by SlimEconomy** [pixijs/pixijs#8126]
Since PixiJS doesn't support a canvas fallback out of the box, I had to shift the code from pixijs to pixijs-legacy. But I am receiving the following error when trying to create a new Application when WebGL is not supported and canvas is used. The application works fine when WebGL is supported in the browser. I could not figure out what the reason for this is. 

The Error
```
Uncaught TypeError: displayObject.renderCanvas is not a function
    at CanvasRenderer.render (canvas-renderer.js:505)
    at Application.render (app.js:92)
    at TickerListener.emit (ticker.js:97)
    at Ticker.update (ticker.js:481)
    at Ticker._tick (ticker.js:232)
 ```
It is pointing to the line of me creating the application:
```
//Create a Pixi Application
-->       const app = new Application({
            width: this.width,
            height: this.height,
            backgroundAlpha: 0,
            antialias: true,
            resizeTo: window,
        });
```

I have included 2 console.logs before and after I draw the picture but both of these logs happen before the error occurs. So the error must be happening asynchronously.

versions: 6.0.4

**Comment by ivanpopelyshev** [comment]
as usual, two pixies. Check your packagejson, make sure you have same version of `pixi.js` and `pixi.js-legacy`, then `rm -rf node_modules` `rm package.lock` or whatever is used by npm at the moment, `npm i`.

**Comment by bigtimebuddy** [comment]
☝️ what @ivanpopelyshev said

**Comment by SlimEconomy** [comment]
> as usual, two pixies. Check your packagejson, make sure you have same version of `pixi.js` and `pixi.js-legacy`, then `rm -rf node_modules` `rm package.lock` or whatever is used by npm at the moment, `npm i`.


They both have the same major version. pixijs 6.0.4 and pixi.js-legacy 6.2.1. Do they need to be exactly the same version? Also I got pixi.js in the dependencies whereas pixijs-legacy is in the devdependencies. Does this make a difference?

**Comment by SlimEconomy** [comment]
> as usual, two pixies. Check your packagejson, make sure you have same version of `pixi.js` and `pixi.js-legacy`, then `rm -rf node_modules` `rm package.lock` or whatever is used by npm at the moment, `npm i`.

I removed pixi from the package.json and kept pixijs-legacy. I deleted the node_modules and reinstalled them. The problem still persists.

**Comment by SlimEconomy** [comment]
> as usual, two pixies. Check your packagejson, make sure you have same version of `pixi.js` and `pixi.js-legacy`, then `rm -rf node_modules` `rm package.lock` or whatever is used by npm at the moment, `npm i`.

Fixed it, thank you
