### ISSUE TITLE
IOS/Safari 15 Performance issue

### ISSUE THREAD

**Issue by FlorentMasson** [pixijs/pixijs#8133]
I had a lot of performance issue after upgrading to ios 15.2.1 to the point it's unplayable, I get something like 1 frame every 10s. y device id iPad Air 2.

I had the idea to test all Pixi.js [examples](https://pixijs.io/examples) (pixi 6.2.1 for reference) and here are the examples that break, ie the browser hangs to the point I can't even refresh or click any example without waiting a lot. Often the browser does not even recover or the screen begins to flicker and I have to kill safari.

```
graphics
- simple
- advanced
- dynamic

Masks
- graphics

Events
- Logger
- Nested boundary
- pointer tracker

Plugin-dragonbones
- robot
- eye tracking

plugin-projection
- 3d cards

Plugin-compressed-textures
- not-premultiplied alpha : DDS files do not show
```

Note that plugin-graphics-smooth does work fine

I know there are lots of regression with IOS 15 but I don't know how to proceed further. Ideally, I would like to pinpoint the problem and find a workaround that could work until apple fixes all their regressions.

Related issues: 
https://github.com/pixijs/pixijs/issues/7983
https://github.com/pixijs/pixijs/issues/7864
https://github.com/pixijs/pixijs/issues/7850

Probably related webkit issue:
https://bugs.webkit.org/show_bug.cgi?id=232357

Here's a workaround that worked for three.js but I don't know how it could work with pixi
https://discourse.threejs.org/t/textures-in-gltf-sometimes-display-black-but-only-on-ios/30520/26

Edit: I posted a webkit bug https://bugs.webkit.org/show_bug.cgi?id=235515

**Comment by ivanpopelyshev** [comment]
DDS shouldnt work in iOS, there's no s3tc compression there

**Comment by FlorentMasson** [comment]
Here's the webkit bug I posted for this https://bugs.webkit.org/show_bug.cgi?id=235515
Apparently, only some devices are impacted.

**Comment by Bonkles** [comment]
We're rewriting an app using PIXI and also saw horrendous slowdowns exclusive to safari 15.2 on macOS Monterey.

It is fixed and the slowdowns go away once we disable `Develop->Experimental Features->WebGL Via Metal`. 

(This is the MacOS equivalent of the iOS workaround one user suggested in the bug chat thread  at https://bugs.webkit.org/show_bug.cgi?id=235515)

**Comment by GoodBoyDigital** [comment]
closing as this is an upstream bug.
