### ISSUE TITLE
Pixi.js typings problem 

### ISSUE THREAD

**Issue by yordan-kanchelov** [pixijs/pixijs#8144]
Hey guys, 

First I want to thank you for your work and continuous improvements. 

In the last months, @ivanpopelyshev was really helpful for me in fixing some typing issues after being pointed out with @pixi/layers.

I kinda want to raise a discussion about the pixi.js plugins and their typings support. 

What I notice is that the typings between some of the "non-breaking" versions of pixi.js are breaking changes for some pixi.js related packages like @pixi/layers, pixi-spine ( those two are the major ones I am using. I guess that it happens to other packages as well ). 

Currently, the latest version of pixi-spine ( v3.0.13) is not running with the latest version of pixi - v6.2.2. It's working okay with pixi .js v6.1.3. It can be seen easily [here](https://github.com/yordan-kanchelov/pixi-typescript-boilerplate). 

I think this could be an issue that stops people from trying to update to the latest version.

One of my suggestions is a repo that uses most of the core additional packages and test against it if their typings work well with the latest version of pixi before publishing.

**Comment by bigtimebuddy** [comment]
PixiJS can be fickle when upgrading. I checked out your boilerplate project and changed the package.json pixi.js dependency to be `^6.2.2` and did an install and got the following errors:

```
> pixi-typescript-boilerplate@1.0.0 type-check
> tsc --noEmit

node_modules/@pixi/loaders/global.d.ts:26:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'loader' must be of type 'Loader', but here has type 'Loader'.

26         loader: import('@pixi/loaders').Loader;
           ~~~~~~

  node_modules/pixi.js/node_modules/@pixi/loaders/global.d.ts:26:9
    26         loader: import('@pixi/loaders').Loader;
               ~~~~~~
    'loader' was also declared here.

src/index.ts:36:24 - error TS2345: Argument of type 'Spine' is not assignable to parameter of type 'DisplayObject'.
  Property '_maskRefCount' is missing in type 'Spine' but required in type 'DisplayObject'.

36     app.stage.addChild(spineExample);
                          ~~~~~~~~~~~~

  node_modules/pixi.js/node_modules/@pixi/display/index.d.ts:602:13
    602     private _maskRefCount;
                    ~~~~~~~~~~~~~
    '_maskRefCount' is declared here.


Found 2 errors.
```

Maybe that is similar to what you're seeing??

Pixi heavily relies on peerDependencies and I think we are hitting some issue with upgrading a package that heavily relies on peers. When I removed the package-lock.json and did a clean install (with the same 6.2.2 dependency bump), everything went fine.  So I don't think this is typings issue or compatibility. I think we are seeing something else related to package management and how the intra-dependencies are designed.

**Comment by bigtimebuddy** [comment]
Here's the workaround (and correct) way to upgrade pixi.js in your project:

```
npm uninstall @pixi/layers pixi-spine
npm install pixi.js @pixi/layers pixi-spine
```

Those type errors are caused my multiple instances of core packages.

**Comment by yordan-kanchelov** [comment]
Pardon me and thanks for the explanation... I was so convinced that I tried deleting the package.lock and go with a clean install, but I guess I got carried out.
