### ISSUE TITLE
Modyfing pixi.findBone('boneName').x does nothing

### ISSUE THREAD

**Issue by jacobdab** [pixijs/pixijs#8176]
Modyfing bone `x` or `y` does nothing, only modyfing bone.data.x makes impact, but it's diffrent work than spine runtimes creators stating on their forum. This probably causing me unstable calculations of `worldToLocal`. By unstable I mean that it sometimes calculates it right and place `targetBone` of vfx on enemy character and sometimes it goes randomly over screen or in diffrent direction that suppose to.

```
vfx.skeleton.findBone("target-bone").x
vfx.skeleton.findBone("target-bone").updateWorldTransform()
vfx.skeleton.findBone("root").updateWorldTransform()
```

As [ivanpopelyshev](https://github.com/ivanpopelyshev) instructed somebody in diffrent post. I making here issues of pixi.spine.
Original link: [issue on pixi.spine github](https://github.com/pixijs/spine/issues/434)

**Comment by bigtimebuddy** [comment]
I'm going to close this, since it's squarely a spine issue. This issue on spine repo is better place for that.
