### ISSUE TITLE
TreeSearch findHit void function return value used - InteractionManager hit is never set

### ISSUE THREAD

**Issue by jasonsturges** [pixijs/pixijs#8179]
It appears that a void function return value is used.  In `InteractionManager` function `processInteractive()`, `hit` is `void` and never set because `findHit()` returns nothing - it does not return `recursiveFindHit()` 

- `InteractionManager.processInteractive()` - sets `hit` to `void` and returns `void`
  - `TreeSearch.findHit()` - returns `void`, does not return value despite JSDocs stating a `boolean` return
    - `TreeSearch.recursiveFindHit()` - returns `boolean`, but value is not used by caller `findHit()`

`InteractionManager` function `processInteractive()` is setting `hit` to `TreeSearch` class `findHit()` function:

![image](https://user-images.githubusercontent.com/1213591/153121305-f667a369-da9e-4f51-b294-59b4cdcf13fa.png)

However, `TreeSearch` class `findHit()` signature is `void` and returns nothing, despite docs specifying a return:

![image](https://user-images.githubusercontent.com/1213591/153121669-a76cedec-c71f-4917-81de-af6ab3592ec3.png)

Note that the `recursiveFindHit()` function returns a `boolean`:

```ts
    /**
     * @return - Returns true if the displayObject hit the point
     */
    public recursiveFindHit(interactionEvent: InteractionEvent, displayObject: DisplayObject,
        func?: InteractionCallback, hitTest?: boolean, interactive?: boolean
    ): boolean
    {
        let hit = false;
        // ...
        return hit;
    }
```

Not sure what this means for `processInteractive()`, which specifies `void` function signature but is returning `hit`:

```ts
    /**
     * This function is provides a neat way of crawling through the scene graph and running a
     * specified function on all interactive objects it finds. It will also take care of hit
     * testing the interactive objects and passes the hit across in the function.
     *
     * @protected
     * @param interactionEvent - event containing the point that
     *  is tested for collision
     * @param displayObject - the displayObject
     *  that will be hit test (recursively crawls its children)
     * @param func - the function that will be called on each interactive object. The
     *  interactionEvent, displayObject and hit will be passed to the function
     * @param hitTest - indicates whether we want to calculate hits
     *  or just iterate through all interactive objects
     */
    public processInteractive(interactionEvent: InteractionEvent, displayObject: DisplayObject,
        func?: InteractionCallback, hitTest?: boolean
    ): void
    {
        const hit = this.search.findHit(interactionEvent, displayObject, func, hitTest);

        const delayedEvents = this.delayedEvents;

        if (!delayedEvents.length)
        {
            return hit;
```

This only passed checks previously because `hit` was `void` in the return of this function.

I attempted to address this in pull request #8178, but was unsure what to do with `processInteraction()` - I presume it should also return `boolean`.  If that sounds correct, I will try to put together a new pull request and assure checks pass.

Pixi.js dev branch, @pixi/Interaction package v6.2.1

**Comment by bigtimebuddy** [comment]
Yeah, this seems wrong. Not sure why the return values are void.

**Comment by jasonsturges** [comment]
Not sure if it's related, but I (and others https://github.com/davidfig/pixi-viewport/issues/366) have been experiencing issues from TreeSearch and processInteractive:

<img width="1266" alt="Screen Shot 2022-02-15 at 2 55 20 PM" src="https://user-images.githubusercontent.com/1213591/154147923-bcacf710-6e90-4261-ad66-886519698c22.png">

In the above, `displayObject` is valid, but `trackedPointers` is null here:

```js
        let trackingData = displayObject.trackedPointers[id];
```

Therefore, throws the exception:

```
InteractionManager.ts:1723 Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at InteractionManager.processPointerOverOut (InteractionManager.ts:1723:1)
    at InteractionManager.processPointerMove (InteractionManager.ts:1653:1)
    at TreeSearch.recursiveFindHit (TreeSearch.ts:173:1)
    at TreeSearch.recursiveFindHit (TreeSearch.ts:113:1)
    at TreeSearch.findHit (TreeSearch.ts:200:1)
    at InteractionManager.processInteractive (InteractionManager.ts:1256:1)
    at InteractionManager.onPointerMove (InteractionManager.ts:1620:1)
```

**Comment by Zyie** [comment]
Closing this as we have moved to the events package in v7 which does not have this issue
