### ISSUE TITLE
ParticleContainer batchSize issue with 16384

### ISSUE THREAD

**Issue by Lusito** [pixijs/pixijs#8184]
### Expected Behavior

ParticleContainer should work correctly with the defined maximum

### Current Behavior

If you max out the batch size, the last particle only draws one triangle instead of two.

### Possible Solution

Setting batchSize to 16383 fixes the issue, so maybe that should be the new maximum?
I noticed a similar issue with pixi/tilemap.

### Steps to Reproduce

Draw 16384 particles and look at the last one.

### Environment

- **`pixi.js` version**: 6.2.2
- **Browser & Version**: Any browser, but for reference: Chromium 96.0.4664.110
- **OS & Version**: _e.g. Manjaro

**Comment by scott-cornwell** [comment]
Still no fix for this in 7.2.4. I'm testing my tile engine with a map size of 240x240 so max of 57.600 Sprites in a ParticleContainer. Even if I set the maxCount to 60,000 I get the triangle artifact. It seems to happen somewhere around 30k Sprites being visible at once. I also get a huge frame rate drop around that number and above, not sure if it just can't handle that many or something is broken. I'm constantly adding and removing Sprites as I pan around and pooling them so I never create more than maxCount. 
![image](https://user-images.githubusercontent.com/4692594/235311504-866505e4-60d2-4577-8aa2-aa6bebdd54f6.png)

**Comment by GoodBoyDigital** [comment]
v8 removes the limit as we use Uint32Array  after a certain size! 👍
