### ISSUE TITLE
Garbled PIXI Banner in DevTools

### ISSUE THREAD

**Issue by 7ombie** [pixijs/pixijs#8185]
For years now, using PIXI v4, v5 and now v6, the PIXI banner that is logged to the console has been garbled on my machine. Instead of hearts and stuff, I get this:

<img width="701" alt="screenshot" src="https://user-images.githubusercontent.com/80077603/153768158-2de99061-1504-4268-87d0-7bd62a1d82dc.png">

In case it's useful, here are the actual characters:

```
 PixiJS 6.2.2 - âœ° WebGL 2 âœ°      http://www.pixijs.com/    â™¥â™¥â™¥ 
```

I put this down to something I must have personally done to my browser (Chrome), but it's still happening, even though I have a new Mac, and am using Electron.

My setup is not especially novel. I'm not using *Keyboard Maestro*, *Hammerspoon*, *Karabiner* or anything like that. Everything is normal. I'm using a UK Mac with the US keyboard setting, but it's normal to use the US layout with non-US keyboards, as ANSI is ASCII. Besides, the only difference between the layouts is that `#` and `£` swap layers (between Shift and Option), so I doubt that is the issue. I just can't think of anything else non-standard about my setup that would be true for both of my laptops, years apart, but not true for anyone else's.

+ PIXI Version: 4, 5 and 6
+ Browser: Chrome & Electron (many versions, including both current stables)
+ OS: OS X and macOS (many versions, including Monterey)

**Comment by bigtimebuddy** [comment]
I always thought the hearts and stars were a little goofy, so maybe we can streamline this. 

If I had to guess it's probably a build issue and/or we need to encode this symbols. 

Also, the URL should also be https.

**Comment by photonstorm** [comment]
@7ombie does it do it when you browse the samples on the Pixi site, or only when you test local projects? I imagine the HTML encoding drives this, rather than a system setting.

**Comment by 7ombie** [comment]
@photonstorm - Sorry. I saw the notification, but then forgot to respond.

Good thinking: The problem is local. The banner renders correctly when I visit the examples on the website.

It's garbled when I'm developing in Chrome with a static file server, and when working on Electron apps (using PIXI as an ES6 module, within a renderer process), but works fine when I load PIXI from a remote server.

I'm happy for this to be closed (or left open). It's up to you whether this is really your issue at all, and whether you really want to spend time on it. I always silence the banner in development, it works fine in production, and nobody else seems affected by this issue??

**Comment by photonstorm** [comment]
Yeah, I think that pretty much confirms it's just a charset / HTML encoding issue locally then. Likely easily resolved with a tweak of your build process, but as you said, not really worth doing if you hide it anyway.

**Comment by 7ombie** [comment]
Yeah; I'm not personally worried about it then. Thanks for taking the time.
