### ISSUE TITLE
any Property 'interactive' does not exist on type 'Sprite'

### ISSUE THREAD

**Issue by jmatte123** [pixijs/pixijs#8186]
I am getting an error in typescript where there is no property Interactive on a Sprite.  Looking at the type definition in my node modules I can't even find the field on the DisplayObject.  Am I missing something here?
![Screen Shot 2022-02-13 at 2 00 18 PM](https://user-images.githubusercontent.com/24372751/153772738-f46deefe-6bd6-475f-ba67-3d6c917c93d9.png)
![Screen Shot 2022-02-13 at 2 02 49 PM](https://user-images.githubusercontent.com/24372751/153772747-40a09e03-5fe8-4721-b18d-02112e7eeac7.png)
```
// tsconfig.json

{
  "compilerOptions": {
    "strict": true,
    "target": "ES6",
    "outDir": "dist",
    // Required for PixiJS
    "esModuleInterop": true,
    "moduleResolution": "node",
    "baseUrl": "./",
    "paths": {
      "mini-signals": [
        "./node_modules/resource-loader/typings/mini-signals.d.ts"
      ]
    }
  },
  "include": [
    "src/**/*.ts",
    "node_modules/@types"
  ],
}
```

```
// package.json

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "jest",
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html --public-url ./",
    "build_serve": "npm run build && http-server ./dist",
  },
  "author": "tester",
  "dependencies": {
    "parcel-bundler": "^1.12.5",
    "pixi.js": "^6.2.2"
  },
  "devDependencies": {
    "http-server": "~0.12.3",
    "typescript": "~4.0.5"
  }
}

```

- **`pixi.js` version** 6.2.2

**Comment by bigtimebuddy** [comment]
Did you recently upgrade pixi.js?

**Comment by jmatte123** [comment]
I just started playing around with it a couple of days ago, I did `npm i pixi.js`

**Comment by jmatte123** [comment]
`"allowSyntheticDefaultImports": true` worked!  Thank you!

**Comment by gterminator** [comment]
problem still persist on 7.2.4

**Comment by gterminator** [comment]
> As you are using angular aside, maybe you could try adding `"allowSyntheticDefaultImports": true` into `angularCompilerOptions` in `tsconfig.json`. The result `tsconfig.json` should like here below.
> 
> ```json
> {
>   // Some settings
>   "compilerOptions": {
>       // Some settings
>   },
>   "angularCompilerOptions": {
>     // Some settings
>     "allowSyntheticDefaultImports": true
>   }
> }
> ```

"esModuleInterop": true 

had to be in compilerOptions. That was the error.
