### ISSUE TITLE
CanvasRenderingContext2D requirement breaks tests in node environment

### ISSUE THREAD

**Issue by mimshwright** [pixijs/pixijs#8197]
I don't know if I would call this a real "issue" but since version 6.2.0, my tests have not been able to run under node with `jsdom`, probably related to PR #7748. 

I get the following error: 

```
layout module > alignJustify() > whitespace and alignJustify() (Issue #171) > Should not throw when align is justify and text is only whitespace.
-----
Error: expect(received).not.toThrow()

Error name:    "ReferenceError"
Error message: "CanvasRenderingContext2D is not defined"

      21 | ): IFontMetrics => {
      22 |   if (forceUpdate) {
    > 23 |     textField.updateText(false);
         |               ^
      24 |     return measureFont(textField.context);
      25 |   } else {
      26 |     const props = measureFont(textField.context);

```
- 6.1.3 works fine
- If I reconfigure my tests to include `jest-canvas-mock` the error goes away but the measurements are all wrong. 
- When I run the tests under `@jest-runner/electron`, everything works fine. 
- This is only really an issue because I can no longer rely on a simple setup without electron to run my jest tests. It also basically renders the vscode-jest extension useless. 

For now I plan to use the slightly older version 6.1.x for my development, but if there's a simple fix, like an option whether to use the CanvasRenderingContext2D, I wonder if we can possibly add it?

### Environment

- **`pixi.js` version**:  6.2.0+
- **Browser & Version**: node@16.13.1, jsdom@^19.0.0, canvas@^2.9.0
- **OS & Version**:  MacOS 12.1

**Comment by bigtimebuddy** [comment]
We unfortunately do not support running Pixi in node. If you want to test, you'll need to find a solution on your own or there are a few third party shims for making this possible (Eg pixi-shim)

I think you're right about that PR. If you add a global object named CanvasRenderingContext2D it might silence that error? Just a guess but that's the only thing that was added recently that added a new global reference to that object.

**Comment by mimshwright** [comment]
@bigtimebuddy Thanks for the clarification!

I realize you said that you don't support running Pixi in node so I'm not holding out a lot of hope that my PR gets approved,  but this does solve my issue and pass the tests! 😉

**Comment by mimshwright** [comment]
I can confirm that after adding the following to my tests, I'm able to run this in node...

```typescript
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
globalThis.CanvasRenderingContext2D = { prototype: {} };
```
