### ISSUE TITLE
@pixi/math-extras is missing Point.divide() implementation

### ISSUE THREAD

**Issue by emlai** [pixijs/pixijs#8200]
@pixi/math-extras defines divide() in the TypeScript definitions:

https://github.com/pixijs/pixijs/blob/d1e9cf2a069f07d355b09b84afbb250bb8cc8817/packages/math-extras/global.d.ts#L39

But the function doesn't have an actual definition: https://github.com/pixijs/pixijs/blob/dev/packages/math-extras/src/pointExtras.ts so trying to use it will result in a runtime error.

**Comment by bigtimebuddy** [comment]
Looks like an oversight. Good catch.

@miltoncandelero do you want to add the method or removing the typing?

**Comment by bigtimebuddy** [comment]
Given that, let's remove the types for now.
