### ISSUE TITLE
Resizing Sprite only possible sometimes if using Base64 Encoded Data URL

### ISSUE THREAD

**Issue by Neversate** [pixijs/pixijs#8201]
Hey there!

We are experiencing crazy issues when we are trying to load images from a data url that has its data encoded in base64.
We are unable to resize the sprite after it has been loaded. 

Please see the minimal, reproducible example:
```javascript
import imageDataURL from "./image"; // 'data:image/png;base64,iVBORw0KGgo....'
import * as PIXI from "pixi.js";

let app = new PIXI.Application({
  width: 256,
  height: 256,
  antialiasing: true,
  transparent: false,
  resolution: 1
});

document.body.appendChild(app.view);

app.renderer.backgroundColor = "0xFFFFFF";

function onSpriteLoad(sprite, callback) {
  if (sprite.texture.baseTexture.hasLoaded !== true) {
    sprite.texture.baseTexture.on("loaded", callback);
  } else {
    callback();
  }
}

var sprite = PIXI.Sprite.from(imageDataURL);

onSpriteLoad(sprite, () => {
  sprite.width = 50;
  sprite.height = 50;
});

app.stage.addChild(sprite);
```

### Expected Behavior
<img width="282" alt="Screenshot 2022-02-23 um 13 44 31" src="https://user-images.githubusercontent.com/100286593/155321958-8209f662-6497-406f-84b0-d633b26d71b3.png">
It should be possible to resize the instance of the sprite after it has been loaded.

### Current Behavior
<img width="313" alt="Screenshot 2022-02-23 um 13 44 36" src="https://user-images.githubusercontent.com/100286593/155322019-8bfe53f1-c7a9-4bdc-9479-4b58d9948c3a.png">
It does not respect the size we set. It does not respect any size we choose for `.width` and `.height`.

**We noted, that this works the first time when you open the example. But on every refresh, the sprite's dimensions are broken.**

### Possible Solution
Yet to be determined.

### Steps to Reproduce
```bash
git clone https://github.com/Neversate/pixi-base64-issue
cd pixi-base64-issue
npm install
npm start
# Use your browser to visit http://localhost:1234
```

### Environment

- **`pixi.js` version**: _6.2.2_
- **Browser & Version**: _Chrome 98, Safari 15.1_
- **OS & Version**: _e.g. Mac OS Monetery_
- **Running Example**: https://github.com/Neversate/pixi-base64-issue

**Comment by Neversate** [comment]
Oh my god. I wasted many hours for this issue.

By programming this minimal reproducible example, I noticed, that the event `loaded` is not fired when refreshing the browser.

`.hasLoaded` has been deprecated, apparently long ago. As an alternative`.valid` can be used.
I will be closing this issue, since it was kinda an issue with my code.

**Comment by bigtimebuddy** [comment]
No problem and thanks for tracking this down! This issue is a good example of why we ask folks to create minimal reproductions.

**Comment by Neversate** [comment]
Absolutely!

It was just very weird because in our codebase we tried to modify the
sprite size using setTimeout, which didn‘t work out for us so we thought
this must be an issue with the Sprite class.

Nevermind and have a great week!
