### ISSUE TITLE
RenderTexture.create() throws with missing options argument, despite types/documentation stating it's optional

### ISSUE THREAD

**Issue by adamsmasher** [pixijs/pixijs#8203]
### Expected Behavior

Invoking `RenderTexture.create()` constructs a new `RenderTexture` with the default options (`width` 100, `height` 100, etc.)
This is indicated by both [the documentation](https://pixijs.download/dev/docs/PIXI.RenderTexture.html#create), which states that `options` is optional, and the types.

### Current Behavior

Invoking `RenderTexture.create()` throws a `TypeError` exception: `Cannot read properties of undefined (reading 'width')` on line 82 of `src/renderTexture/BaseRenderTexture.ts`.

### Possible Solution

Check to see if `options` is defined when reading from it - TypeScript's `?.` operator could be used here. TypeScript's `strictNullChecks` would catch this, if it's possible to turn on.

### Environment

- **`pixi.js` version**: 6.2.2
- **Browser & Version**: Chrome 98.0.4758.102 (Official Build) (arm64)
- **OS & Version**: macOS 11.4

**Comment by bigtimebuddy** [comment]
Thanks for reporting @adamsmasher
