### ISSUE TITLE
dose pixijs support reverse mask feature ?

### ISSUE THREAD

**Issue by liujinxiao** [pixijs/pixijs#8207]
is there any plan to achieve **mask reverse feature** ? thanks !

now our team is using pixi.js to achieve mask feature and mask reverse feature, like this

1、this is the original sprite
![image](https://user-images.githubusercontent.com/26742095/156516226-839cb912-7355-4cd6-bb25-a88c88a53aaf.png)

2、this is the sprite with circle mask 
![image](https://user-images.githubusercontent.com/26742095/156516388-edb21475-94d5-46e2-9e98-b4370f148295.png)

3、this is the sprite with circle reverse mask
![image](https://user-images.githubusercontent.com/26742095/156516516-3db0d608-33d6-409c-9693-01cf7ccc4937.png)

**Comment by liujinxiao** [comment]
https://github.com/liujinxiao/pixijs/pull/1/files

edit packages/core/src/filters/spriteMask/spriteMaskFilter.frag file,  maybe resolve the issue?
![image](https://user-images.githubusercontent.com/26742095/156958733-4d0bdffd-9b62-44ce-ace5-cefe565f910e.png)

**Comment by liujinxiao** [comment]
>

**Comment by liujinxiao** [comment]
> You can use custom sprite mask filters like so:
> 
> ```js
> object.mask = new PIXI.MaskData(sprite);
> object.mask.filter = new MyCustomSpriteMaskFilter();
> ```
> 
> But you shouldn't use a mask for reverse masking. That doesn't work. Use a filter:
> 
> ```js
> object.filters = [new MyReverseSpriteMaskFilter()];
> object.filters[0].maskSprite = sprite;
> ```

mask is actually a filter, so i want to edit mask filter to achieve mask reverse feature。this does work.

**Comment by dev7355608** [comment]
Try this:
```js
object.filters = [new PIXI.SpriteMaskFilter(undefined, `\
varying vec2 vMaskCoord;
varying vec2 vTextureCoord;

uniform sampler2D uSampler;
uniform sampler2D mask;
uniform float alpha;
uniform float npmAlpha;
uniform vec4 maskClamp;

void main(void)
{
    float clip = step(3.5,
        step(maskClamp.x, vMaskCoord.x) +
        step(maskClamp.y, vMaskCoord.y) +
        step(vMaskCoord.x, maskClamp.z) +
        step(vMaskCoord.y, maskClamp.w));

    vec4 original = texture2D(uSampler, vTextureCoord);
    vec4 masky = texture2D(mask, vMaskCoord);
    float alphaMul = 1.0 - npmAlpha * (1.0 - masky.a);

    original *= 1.0 - (alphaMul * masky.r * alpha * clip);

    gl_FragColor = original;
}
`)];
object.filters[0].maskSprite = sprite;
```

**Comment by liujinxiao** [comment]
> 

this is same as my method, and it does work.  but i think support reverse mask feature may be easy for users, thanks.
anyway, we can achieve this feature  :)

**Comment by katmai7** [comment]
Pixi 8.5.0 now supports inversed mask out of the box.
[documentation](https://pixijs.download/dev/docs/scene.Container.html#setMask)

**Comment by GoodBoyDigital** [comment]
closing as we have support. Thanks @katmai7 !
