### ISSUE TITLE
Sprite rendering delayed

### ISSUE THREAD

**Issue by matt-farrell** [pixijs/pixijs#8214]
Hi,

I'm creating an online multiplayer browser game and using pixijs to display things in the browser client. I'm having an issue when trying to render some sprites.

When a player dies 10 sprites should render at the location of the dead player. 
Here is a demo video of what I expect to see:
https://user-images.githubusercontent.com/8869778/156839729-12706913-a5c1-4af6-84e1-e7b5154a0817.mp4

Here is a demo video of the issue I'm seeing sometimes:
https://user-images.githubusercontent.com/8869778/156839755-335d5afb-4a1b-4cac-9910-b9afa910f3bf.mp4

As you can see the 10 sprites that should render at the location of the dead player don't all show up right away. They also sometimes flicker or take even longer than this to show up.

I'm using chrome version 99.0.4844.51

I realize that without seeing my client code you would mostly be guessing why this is happening but I'd rather not share my code here publicly. I'd be happy to show my client code privately to somebody who can help out.

-Matt

**Comment by bigtimebuddy** [comment]
The best way to verify the issue (and not a bug in your code) is to provide a minimal reproduction of your case. Please user codepen.com, jsfiddle.net or pixiplayground.com to reproduce the issue you're seeing.

**Comment by matt-farrell** [comment]
I tried to create a minimal reproduction of my case but I was not successful. I'm not exactly sure what is causing this to happen. However it does happen quite frequently with my code. Is there any way I can share that code with you privately?

**Comment by bigtimebuddy** [comment]
Sorry but we do not provide support for projects. It's your responsibility when you post an issue to make sure it's reproducible outside your code.

If you cannot reproduce, we kindly ask you close the issue. You can reopen or create a new issue if you're able to isolate the underlying issue.

**Comment by matt-farrell** [comment]
No problem. Closing the issue. I found the problem on my side.
