### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'stencil') on mobile render

### ISSUE THREAD

**Issue by shalokhin-artur** [pixijs/pixijs#8216]
### Expected Behavior
On mobile render
when i am destroying pixi app and creating new instance on same canvas element i have last frame without errors;

### Current Behavior
For mobile render:
when i am destroying pixi app and creating new instance on same canvas element i have clean canvas and error
 **Uncaught TypeError: Cannot read properties of null (reading 'stencil')**
For desktop render:
when i am destroying pixi app and creating new instance on same canvas element i have last frame;

### Steps to Reproduce
open https://codesandbox.io/s/crazy-snow-i0e7p3?file=/src/index.js
click on open in new tab
in new tab toggle device toolbar 
then reload page
and you will get error  **Uncaught TypeError: Cannot read properties of null (reading 'stencil')**
### Environment

- **`pixi.js` version**: _e.g. 6.0.4 - 6.2.2_
- **Browser & Version**: _e.g. Chrome 98_ (mobile render)
- **OS & Version**: _e.g. MacOS BigSur 11.3.1
- **Running Example**: https://codesandbox.io/s/crazy-snow-i0e7p3?file=/src/index.js

**Comment by jaxreiff** [comment]
It looks like the only piece of code causing this error is a condition wrapping a warning log, it's a simple fix. I've opened a pull request here: https://github.com/pixijs/pixijs/pull/8344

**Comment by Julien-Marcou** [comment]
I just came across this error, I can see the fix has been merged but not yet release, is there an ETA for it ?
