### ISSUE TITLE
Display object width / height versus bounds

### ISSUE THREAD

**Issue by jasonsturges** [pixijs/pixijs#8230]
While I understand width and height are property accessors / modifiers of scale, I'd expect width and height to operate differently - calculating scale. 

When a sprite is created, `width` and `height` reflect the initial scale and not bounds of the object:

| Property | Value |
|---|---|
| scale | 0.1 |
|  width  | 0.1  | 
|  height  | 0.1  | 
|  bounds.width  | ~62  | 
|  bounds.height  | ~94  | 

<img width="492" alt="Screen Shot 2022-03-18 at 3 21 09 PM" src="https://user-images.githubusercontent.com/1213591/159079318-d32331fd-8ed9-41e8-bd6d-2e1dbe989cb4.png">

Also setting width / height after initial creation acts as scale.  If I set `width` to `10`, I get 10x scale instead of a calculated scale for 10-pixels.

<img width="596" alt="Screen Shot 2022-03-18 at 3 23 12 PM" src="https://user-images.githubusercontent.com/1213591/159079383-4f554f0c-bbb9-46ab-b4da-7a5ae0d22c20.png">

Code:

```ts
import { Graphics, Sprite } from "pixi.js";

export class TestSprite extends Sprite {
  private readonly _graphics: Graphics;

  constructor() {
    super();

    this._graphics = new Graphics();
    this._graphics.beginFill(0xff00ff);
    this._graphics.drawRect(0, 0, 512, 512);
    this.addChild(this._graphics);

    this.scale.set(0.1, 0.1);
  }
}

const t = new TestSprite();
viewport.addChild(t);
t.width = 200;
```

CodeSandbox: https://codesandbox.io/s/charming-wind-rffgp4

Maybe I'm doing something weird here... I always use scale having faced this multiple times.

### Expected Behavior

I'd expect width and height to reflect size in pixels, and compute scale when accessed or modified.

### Environment

- **`pixi.js` version**: 6.2.2
- **Browser & Version**: Version 99.0.4844.74 (Official Build) (arm64)
- **OS & Version**: macOS Monterey 12.3, MacBook Pro 16", Apple M1 Pro
- **Running Example**:  https://codesandbox.io/s/charming-wind-rffgp4

**Comment by andrewstart** [comment]
Height and width of Sprite is intended to be based on its texture size - if you make one without a loaded texture it is just the scale, as you have found. Following from that, setting the height and width won't take into account the bounds of its children when calculating the new scale. If you want to set size while including children in the calculation, try using the `Container` class instead of `Sprite`.

**Comment by jasonsturges** [comment]
@andrewstart Thanks, that answers several things I haven't fully understood.  Really appreciate your time.
