### ISSUE TITLE
Stacked sprites are leaking through each other

### ISSUE THREAD

**Issue by UltraCakeBakery** [pixijs/pixijs#8248]
### Current Behavior
I think I am dealing with floating point precission issues, but I am not sure. 

I've got a bunch of containers that each contain only two sprites: a random colored `square`, and a `coin`. When you click on a `square`, it dissapears revealing the `coin`. As you can see in the images below, the `coin` is leaking through the `square`

![image](https://user-images.githubusercontent.com/12383587/160415141-9c5d88f1-3d4d-4df8-9d88-8c6206ff5587.png)
![image](https://user-images.githubusercontent.com/12383587/160415317-1466aa51-58ed-4d1f-89ca-3290e8394043.png)

My guess is that in pixi sprites are made up of triangles and due to float point precission the other sprite is leaking through the seams? 

Is there a clever filter or option that can prevent this kind of leakage?

### Possible Solution
A nice filter or option in webgl?

### Steps to Reproduce
Lay two sprites on top of each other and scale their parent container

### Environment

- **`pixi.js` version**: 6.3.0
- **Browser & Version**: _e.g. Edge latest_
- **OS & Version**: _e.g. Windows 11_

**Comment by UltraCakeBakery** [comment]
For now I am just going to make these coins invisible till the square is removed, but I rather not have leakage at all if possible

**Comment by ivanpopelyshev** [comment]
Disable antialias?

**Comment by UltraCakeBakery** [comment]
That does not make a difference for me. I'm going to close this issue since i'm pretty sure this is a floating point error which is pretty much unavoidable unless you want to give up a ton of performance. Thanks for the suggestion ivanpopelyshev!

**Comment by dev7355608** [comment]
This is odd. A sprite consists of two triangles that perfectly share an edge. Therefore there shouldn't be a gap. I suspect the hardware or driver must be faulty. Did you test your app on other devices?

**Comment by ivanpopelyshev** [comment]
Some devices are cursed )

**Comment by UltraCakeBakery** [comment]
> This is odd. A sprite consists of two triangles that perfectly share an edge. Therefore there shouldn't be a gap. I suspect the hardware or driver must be faulty. Did you test your app on other devices?

GTX 1060 with latest drivers, Nokia 7.2 plus, google pixel 5, iphone 6. On all of them I have the issue

**Comment by ivanpopelyshev** [comment]
Interesting . do you use canvas scaling like "width=100%" ?
