### ISSUE TITLE
Inconsistency when setting undefined to BitmapText

### ISSUE THREAD

**Issue by miltoncandelero** [pixijs/pixijs#8252]
Creating a BitmapText with an `undefined` text results in a crash but setting `undefined` after creation doesn't (it assigns an empty string)

### Expected Behavior
Either we crash both or we don't crash on only one

### Current Behavior
`undefined` crashes because we store it directly in the `._text` variable. `.text` is a setter that protects against undefined.

### Possible Solution
Super simple: make the constructor write to `.text` instead of `._text`

### Steps to Reproduce
try rendering this object (provide a font)
`const bitmapFontText = new PIXI.BitmapText(undefined, { fontName: 'Desyrel', fontSize: 55, align: 'left' });`

### Environment

- **`pixi.js` version**: 5+, 6+
- **Browser & Version**: All
- **OS & Version**: All
- **Running Example**: https://www.pixiplayground.com/#/edit/cJevxhf0TXH-N9a1OYkWQ

---

## My biggest question: Do we want to fix this? I can PR this in a couple of days or so
For the record: `Text` doesn't crash when creating and passing `undefined` as text. It assigns an empty string.
This looks like an oversight/bug. I will start working on a PR

**Comment by Zyie** [comment]
Fixed in #8253 

Released in `v6.3.1`
