### ISSUE TITLE
Argument of type 'Sprite' is not assignable to parameter of type 'DisplayObject'.

### ISSUE THREAD

**Issue by WillPoulson** [pixijs/pixijs#8268]
### Expected Behavior
You can add sprites as children.

### Current Behavior
When attempting to add a sprite as a child it throws the error `Argument of type 'Sprite' is not assignable to parameter of type 'DisplayObject'.`

### Possible Solution
Not sure here - This has occurred in 6.3.0 and was not an issue in 6.2.x

### Steps to Reproduce
In a typescript project upgrade to V6.3.0, attempt to add a `Sprite` as a child to the stage with `.addChild(sprite)`

### Environment

- **`pixi.js` version**: 6.3.0

**Comment by bigtimebuddy** [comment]
When upgrading completely uninstall pixi.js first, then install the latest version. There can be issues, like this, with partial upgrades.

If it still persists please post a reproduction.

**Comment by hdemmer** [comment]
Had something similar. Deleting node_modules and reinstalling helped. Same issue as here: https://github.com/inlet/react-pixi/issues/332

**Comment by bigtimebuddy** [comment]
Try this solution: https://github.com/pixijs/pixijs/issues/8144#issuecomment-1025169555

**Comment by WillPoulson** [comment]
Thanks for the suggestions everyone.
Sadly removing and installing hasn't resolved it for me.

I've also tried:
- Deleting node modules and reinstalling.
- Clearing NPM cache, deleting modules and reinstalling.
- Removing angulars serve cache just in case that was messing with anything.

Is there any base online reproduction template I could start from to see if I can replicate there?

**Comment by WillPoulson** [comment]
Ah. Deleting `package-lock.json` and doing a clean install resolved the issues for me 🤷‍♂️ .

Weird, anyway thanks all for the help, I'll close this now!

**Comment by nebsar** [comment]
I have the same problem with pixijs version 7.3.3. Nothing helped to clean the issue.

**Comment by bigtimebuddy** [comment]
@nebsar please file a new issue with a reproduction

**Comment by imaxs** [comment]
> I have the same problem with pixijs version 7.3.3. Nothing helped to clean the issue.

I have the same problem too.

> @nebsar please file a new issue with a reproduction

I just took these examples and pixi.js v.7.3.3:
https://github.com/pixijs/open-games

After running  **npx tsc -noEmit** I see 88 errors in 25 files
"...  is not assignable to parameter of type 'DisplayObject'."

![12312](https://github.com/pixijs/pixijs/assets/9829425/b888c506-be3d-428d-a9a5-94b2bb3a1d48)

**Comment by talhaozdemir** [comment]
I have upgraded the typescript version to 5.3.3 and problem is solved. The PixiJS version is 7.3.3

**Comment by darotar** [comment]
Is there any workaround to run it on typescript@^4.9.5? I have no possibility to upgrade that, so should I downgrade pixi.js and is this the only resolution?

**Comment by CornHpp** [comment]
> I have upgraded the typescript version to 5.3.3 and problem is solved. The PixiJS version is 7.3.3
thank you , i have been trying to  solve this problew for a long time,but finally i solved it

**Comment by TimAstier** [comment]
Same here, upgraded TS from v4 to v5 solved it. Thanks!
