### ISSUE TITLE
Feature Request (+example): Load textures at lower resolution

### ISSUE THREAD

**Issue by andrewdevcup** [pixijs/pixijs#8277]
It's actually possible to do this, use the createImageBitmap API (with an HTMLImageElement) as input to resize the Image by a certain percent.
It has to be a HTMLImageElement, looking at the code for creating an ImageBitmap for a texture, it uses fetch => blob to do it, but it loads the image at full size.
Instead, use HTMLImageElement which loads the image more efficiently, resizing it in the process, requiring less memory.
This can be an option for ImageResource, along with the resolution and quality:
```
ImageResource.bitmapFromImageSource = true; //createImageBitmap from ImageResource.source, if false use blob
ImageResource.resolution = 1;
ImageResource.resizeQuality = PIXI.BITMAP_QUALITY.LOW; //New enum: "pixelated|low|medium|high"

//Code for ImageBitmap with Image
createImageBitmap(Image, 0, 0, Image.width, Image.height,
{ 
  premultiplyAlpha: ImageResource.alphaMode,
  resizeWidth: (Image.width * ImageResource.resolution) + .5|.5, //Round
  resizeHeight: (Image.height * ImageResource.resolution) + .5|.5,
  resizeQuality: ImageResource.resizeQuality
});
//Resize the ImageResource to resized bitmap when it's created.
```

Got some code working (modified pixi.min.js) and the memory usage is lowered quite significantly!
[Working example on Pixi Playground](https://pixiplayground.com/#/edit/LC-lfRUmGnuij0KK1qAfR)

**Comment by miltoncandelero** [comment]
You can already do this with the `@` prefix.
It's up to you to know which one to load, but after that pixi will hide the fact that you are using a smaller or larger texture from you. 🤔

**Comment by andrewdevcup** [comment]
> You can already do this with the `@` prefix. It's up to you to know which one to load, but after that pixi will hide the fact that you are using a smaller or larger texture from you. 🤔

What if you don't want to create different textures with different resolutions only to increase you app size?
Load the one you have at lower resolution, then based on that resolution scale, adapt your Spritesheet, Sprites and BitmapFont, which can be done internally by PIXI.

**Comment by ShukantPal** [comment]
You will need to use an image CDN like [Imgix](https://www.imgix.com) that automatically generates different resolutions of an image based on the URL being used; a client-side application like PixiJS cannot determine the resolution of an image being fetched over the network.

**Comment by andrewdevcup** [comment]
> You will need to use an image CDN like [Imgix](https://www.imgix.com) that automatically generates different resolutions of an image based on the URL being used; a client-side application like PixiJS cannot determine the resolution of an image being fetched over the network.

For the main purpose of PixiJS, that might be the best way of doing it.
So what if an image is loaded from the storage of the device, in a native webapp? In that case the processing should be done on the client-side.
In the example, the full image is still loaded, but it's converted into a lower resolution ImageBitmap to be uploaded to the GPU.

**Comment by ShukantPal** [comment]
If the goal is to reduce the resolution of the texture, as uploaded to the GPU, then I see the point. It would seem wasteful to fetch the image at full resolution (in the normal use case for `ImageResource`). It seems like a bespoke use case if you are doing it for client-side stored images.

**Comment by GoodBoyDigital** [comment]
closing this one out! [AssetPack](https://github.com/pixijs/assetpack) can help here as it can generate loads of different resolution images and load the most appropriate one for ya!. That way we only load what we need! Thanks
