### ISSUE TITLE
Wrong hit area in shadow DOM

### ISSUE THREAD

**Issue by pwalczyszyn** [pixijs/pixijs#8281]
### Expected Behavior

Hit area should be properly calculated when `pixi` is embedded in custom elements with shadow DOM enabled.

### Current Behavior

Hit area is not taking into consideration pixi app position when hosted in custom elements with shadow DOM enabled. This also impacts `click` and `pointerup` events which are missing.

### Steps to Reproduce

In the link below I included a demo that shows custom element with and without shadow DOM enabled. In the first example you can see (some not all) pointer events are registered above the bunny.

### Environment

- **`pixi.js` version**: 6.3.0
- **Browser & Version**: Chrome  100.0.4896.75 
- **OS & Version**: macOS 12.0.1
- **Running Example**: https://stackblitz.com/edit/pixi-shadow-dom-bug?file=src%2Fmy-element.ts

**Comment by da411d** [comment]
Same issue

**Comment by Zyie** [comment]
Fixed in #8406 

Will be released with `v6.5.0`
