### ISSUE TITLE
Option resizeTo incorrect with Angular

### ISSUE THREAD

**Issue by matndev** [pixijs/pixijs#8282]
resizeTo option behaviour is incorrect when moving the developer tools panel on browser.

### Expected Behavior

The height of the canvas remains the same when I extends the developer tools from left to the right / right to the left.

### Current Behavior

When I apply the option resizeTo: this.elementRef.nativeElement to the Application constructor the canvas height increases infinitely.

![image](https://user-images.githubusercontent.com/46798367/162848424-d1744727-0c03-450f-887a-fbd9eb0037e9.png)

### Possible Solution

No idea. Intern mechanism of PixiJS of resize function

### Steps to Reproduce

Create a basic angular project, and add a div as a container for the canvas.
Then get this container with ViewChild decorator and initialize PIXI.Application

### Environment

Angular 10.2.0

- **`pixi.js` version**: 6.3.0
- **Browser & Version**: Last version of Chrome & Firefox
- **OS & Version**:  Windows 11
- **Running Example**:  Not able to build a basic Angular/PIXIJS example with stackblitz (modules not loaded properly)

**Comment by bigtimebuddy** [comment]
@matndev it's customary to post your resolution if you close. Other folks will find this useful when searching old issues.
