### ISSUE TITLE
Discord Invite Link broken

### ISSUE THREAD

**Issue by andyfleming** [pixijs/pixijs#8287]
The Discord server invite link on https://github.com/pixijs/pixijs/wiki/v6-Resources#community no longer works.

**Comment by miltoncandelero** [comment]
I will replace it. Meanwhile you can use this
https://discord.gg/QrnxmQUPGV

**Comment by andyfleming** [comment]
Thanks!

**Comment by miltoncandelero** [comment]
Link updated in the wiki 👍
