### ISSUE TITLE
Error when creating sprite with spritesheet texture

### ISSUE THREAD

**Issue by mthomas24** [pixijs/pixijs#8295]
I am trying to create a sprite from a texture that I loaded from a spritesheet, but I am getting this error:
![image](https://user-images.githubusercontent.com/55769391/164126566-1b759d53-71ec-4c1a-955c-4514a5e8f4bd.png)

Here is where I load the spritesheet:
```js
// main.js
Loader.shared.add("assets/tiledata.json").load(setup);

let game;

function setup() {
  const sheet = Loader.shared.resources["assets/tiledata.json"].spritesheet;
  // console.log(textures);
  console.log(sheet);
  game = new Game(sheet);
  game.start();
}
```

Here is where I try to create the sprite:
```js
let s = Sprite(this.sheet.textures[tName]);
```

If it helps, here is a the `Texture` object I am passing into the `Sprite` constructor:
![image](https://user-images.githubusercontent.com/55769391/164127286-be2e8b23-9147-4448-80f1-c8dd609a4431.png)

Here is the error message again:
```
Uncaught TypeError: Cannot set properties of undefined (setting '_events')
    at EventEmitter (pixi.mjs:1611:16)
    at DisplayObject (pixi.mjs:7984:28)
    at Container (pixi.mjs:9156:28)
    at Sprite (pixi.mjs:31106:28)
    at Game.renderBoard (main.js:131:17)
    at TickerListener.fn (main.js:190:20)
    at TickerListener.emit (pixi.mjs:10361:22)
    at Ticker.update (pixi.mjs:10742:37)
    at Ticker._tick (pixi.mjs:10493:23)
```

I have searched online but I could not find this particular error. All the files I mentioned and the spritesheets are in [this repository](https://github.com/mthomas24/tetris).

- **`pixi.js` version**: v6.3.0
- **Browser & Version**: Chrome 100.0.4896.127
- **OS & Version**: Windows 10
- **Running Example**: https://github.com/mthomas24/tetris

**Comment by bigtimebuddy** [comment]
This is not a loading error, it's a syntax issue:

```js
let s = Sprite(this.sheet.textures[tName]);
```
Should be this
```js
let s = new Sprite(this.sheet.textures[tName]);
// or
let s = Sprite.from(this.sheet.textures[tName]);
```

**Comment by mthomas24** [comment]
Sorry I should have realized that silly mistake. I was up late writing the code. 🙃 Thank you for the help.

**Comment by bigtimebuddy** [comment]
No problem, it happens. Good luck with your project.
