### ISSUE TITLE
graphics-extras not working with Graphics when imported from pixi.js

### ISSUE THREAD

**Issue by amir-arad** [pixijs/pixijs#8305]
I've encountered this breaking change when migrating from 6.2.2 to 6.3.0. 

### Expected Behavior
```
import '@pixi/graphics-extras';
import { Graphics } from 'pixi.js';

const g= new Graphics();

g.drawStar(...);
```
should not throw
### Current Behavior
`g.drawStar` is undefined

### My Workaround
replace `import { Graphics } from 'pixi.js';` with `import { Graphics } from '@pixi/graphics';`

### Environment

- **`pixi.js` and `graphics-extras` version**: 6.3.0
- **Browser & Version**:chrome latest
- **OS & Version**: windows

**Comment by bigtimebuddy** [comment]
Can you provide a repo? This sounds like an upgrade npm upgrading issue. Try uninstalling `pixi.js` completely and then installing 6.3.0 and see if that fixes.

**Comment by amir-arad** [comment]
unfortunately the repo is private (and very, very cluttered). 
I scanned the lockfile and it only refers to version 6.3.0.
this issue also happens after clean install locally, and in CI environment (running circleci node orb environment for building, with no funny stuff)

**Comment by amir-arad** [comment]
yes, I see it now. I have duplicate modules, including `@pixi/graphics`. one group in the root `node_modules` (these are `@pixi/graphics-extras` and its dependencies), the others under `node_modules/pixi.js/node_modules`.
