### ISSUE TITLE
how to set text-decoration like 'underline', 'line-throuth'?

### ISSUE THREAD

**Issue by claudewowo** [pixijs/pixijs#8322]
### Expected Behavior
how to set text-decoration like 'underline', 'line-throuth'?
### Current Behavior
can't set text decoration
### Possible Solution
no text decoration API
### Environment
pixi.js  version: 6.3.2

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by claudewowo** [comment]
thank you!

**Comment by Elon-Yan** [comment]
how to set text-decoration, not use html-text?

**Comment by bigtimebuddy** [comment]
This is not possible. PixiJS uses the CanvasRenderingContext2D which does not support these text-decoration styles. The only want to support it is to manually draw it yourself or use html-text (or a similar approach).

If you want to draw the text-decoration yourself, consider `Text.nextLineHeightBehavior = true` which will make it easier to figure out the baseline position.
