### ISSUE TITLE
Renderer.generateTexture used wrong default region

### ISSUE THREAD

**Issue by Keyang** [pixijs/pixijs#8323]
### Expected Behavior
render.generateTexture(Obj) should create texture with exact bounds of the obj even the obj is a root element with translation of position

### Current Behavior
If an obj is root element and it has tx or ty in transformation, getLocalBounds(null,true) is not the correct default region for its content thus creating wrong texture

### Steps to Reproduce
Here is a playground for reproduce: https://www.pixiplayground.com/#/edit/R5sqRDgqDm4pqdjNOc3-G

### Environment

- **`pixi.js` version**: 6.3.2
- **Browser & Version**: Chrome
- **OS & Version**: MacOS
- **Running Example**:  https://www.pixiplayground.com/#/edit/R5sqRDgqDm4pqdjNOc3-G

**Comment by Zyie** [comment]
Fixed in #8349 

Will be released in v7 as this is a breaking change
