### ISSUE TITLE
Cannot find name 'OffscreenCanvas' (inside an angular app)

### ISSUE THREAD

**Issue by kevincentius** [pixijs/pixijs#8328]
Hello, I have the same symptoms of this issue: https://github.com/pixijs/pixijs/issues/8174

But the problem isn't fixed for me yet, and the solution there (installing @types/offscreencanvas) did not help either.

### Expected Behavior

Angular app should start even after adding pixi.js.

### Current Behavior

Starting the application gives the following error:
```

Error: node_modules/@pixi/core/index.d.ts:1534:45 - error TS2304: Cannot find name 'OffscreenCanvas'.

1534     static test(source: unknown): source is OffscreenCanvas | HTMLCanvasElement;
                                                 ~~~~~~~~~~~~~~~


Error: node_modules/@pixi/text/index.d.ts:306:105 - error TS2304: Cannot find name 'OffscreenCanvas'.

306     static measureText(text: string, style: TextStyle, wordWrap?: boolean, canvas?: HTMLCanvasElement | OffscreenCanvas): TextMetrics_2;
                                                                                                            ~~~~~~~~~~~~~~~


Error: node_modules/@pixi/text/index.d.ts:444:47 - error TS2304: Cannot find name 'OffscreenCanvas'.

444     static get _canvas(): HTMLCanvasElement | OffscreenCanvas;
                                                  ~~~~~~~~~~~~~~~


Error: node_modules/@pixi/text/index.d.ts:450:55 - error TS2304: Cannot find name 'OffscreenCanvasRenderingContext2D'.

450     static get _context(): CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D;

```

### Steps to Reproduce

- create an angular app (`ng new my-project`)
- `npm install pixi.js`
- call `new Application()` on startup

It is reproduced here: https://github.com/kevincentius/angular-pixi-bug-reproduce

Running `npm install` and `npm start` should start the project and trigger the error

### Environment
- pixi.js 6.3.2
- angular 13.3.0
- Windows 10

**Comment by kevincentius** [comment]
I just tested and found pixi to work on Angular 12, but does not on Angular 13.

**Comment by bigtimebuddy** [comment]
Doing a [quick GitHub search](https://github.com/search?q=offscreencanvas+angular&type=issues) this seems more like an issue with TypeScript + Angular than something Pixi is doing.

**Comment by kevincentius** [comment]
Ooooooo

[8182](https://github.com/pixijs/pixijs/issues/8182) is exactly the same problem and the solution there worked for me. I should've found it.

The solution was adding `"types": ["offscreencanvas"]` in compilerOptions in tsconfig.app.json.

```
{
    "extends": "../tsconfig.base.json",
    "compilerOptions": {
        "outDir": "../out-tsc/app",
        "types": ["offscreencanvas"]
    },
    "files": [
        "main.ts",
        "polyfills.ts"
    ],
    "include": [
        "src/**/*.d.ts"
    ]
}
```

Thanks a lot!

**Comment by elgerm** [comment]
make sure you add `@types/offscreencanvas` to _devDependencies_ and not _dependencies_

then no more build error.

**Comment by kevincentius** [comment]
I did try that and did not work. Did you get it to work with Angular 13 without the compiler option?

**Comment by Crefelder** [comment]
Installed packages for pixijs and ng 13.3.7 version:
![image](https://user-images.githubusercontent.com/7198153/171193549-8766877a-f4b6-4010-b53c-963f8658adf7.png)

TWO different ideas that are working for me:
1. -------------------------------------------------------------
Add type offscreencanvas to tsconfig.app.json:
![image](https://user-images.githubusercontent.com/7198153/171197295-fbf65c28-6340-4d84-8a06-fc1158b0cf8b.png)

Add allowSyntheticDefaultImports in compilerOptions in tsconfig.json
![image](https://user-images.githubusercontent.com/7198153/171197843-da6c840b-f498-4e96-9382-fabc81ea2515.png)


OR
2. -------------------------------------------------------------
In the src folder of angular I´ve added a empty file called typings.d.ts with this content:
declare type OffscreenCanvas = any;
declare type OffscreenCanvasRenderingContext2D = any;
![image](https://user-images.githubusercontent.com/7198153/171192420-a3f76357-0678-4712-9fec-a5e5a3e561c1.png)

add this to tsconfig.json
![image](https://user-images.githubusercontent.com/7198153/171194565-c36c6acf-0209-4731-a77a-7bb304e09098.png)

--------------------------------------------------------
For getting rid of this message:
![image](https://user-images.githubusercontent.com/7198153/171192555-3f05d5fa-bf12-4b58-a7a7-8ed9d6f8251d.png)
I've added allowedCommonJsDependencies: - url
![image](https://user-images.githubusercontent.com/7198153/171192819-880b2f6f-54a4-4995-ae07-e1be3d73ec56.png)

if you have max size warnings you can change them in angular.json
![image](https://user-images.githubusercontent.com/7198153/171195142-f83d6784-6075-4246-8d49-dc88d1e11684.png)
