### ISSUE TITLE
Incorrect PIXI.Graphics size and its' bounds

### ISSUE THREAD

**Issue by Vardner** [pixijs/pixijs#8333]
The calculation of graphics size (width and height) was broken since version 6.3.0 due to this "improvement"^

> Fix lineWidth calculation in Graphics.calculateBounds (https://github.com/pixijs/pixijs/pull/8225) @dev7355608

From my small investigation, it happens because now GraphicsGeometry.prototype.calculateBounds now incorrectly works with bounds update therefore minX of bounds contains a wrong value. 
I don't know how to fix it so came here

### Environment

- **`pixi.js` version**: 6.3.0
- **Browser & Version**: doesn't matter
- **OS & Version**: doesn't matter
- **Running Example**: [_url_](https://codepen.io/Vardner/pen/wvyzpPP)

**Comment by dev7355608** [comment]
This has been addressed by #8343. Graphics bounds are going to be 100% accurate in 6.5.0.
