### ISSUE TITLE
Remove Abstract renderer in favour of a new set of shared systems

### ISSUE THREAD

**Issue by GoodBoyDigital** [pixijs/pixijs#8336]
**Problem**
Pixi uses systems to compose its logic and inheritance (abstract renderer). Two methods of sharing functionality is a very good code structure. 

**Solution**
We remove the abstract render, and replace it with a set of new systems. These systems can be shared by both the canvas and the WebGL renderer. (And webGPU in the future!)

**Comment by Zyie** [comment]
implemented in #8331
