### ISSUE TITLE
Bring back Stage

### ISSUE THREAD

**Issue by GoodBoyDigital** [pixijs/pixijs#8339]
**Problems**
When we render a scene, we have no way of knowing what happened from one render to the next. This means we cannot do things like optimize our draw calls or our scene graph optimisation, as we have no idea what changed.

**Solution**
Having a Stage object will allow us to track changes in the scene at a higher level. This means we can heavily optimize the scene graph and the render pipeline. WebGPU will allow us to cache and just rerun draw commands if nothing changes. We can also do the same with batch building - we can just update what changes per frame - rather than the whole thing

**A\* developer route:**
Any object passed to renderer, will automatically have a stage created and associated with it. Could also just be a component that gets added to the object.

**Comment by ivanpopelyshev** [comment]
I can revise what i did in #4586 and how its progressed in years in my private projects :)

**Comment by nat42** [comment]
Just a random thought (and I haven't really looked at PixiJS yet, peeking at the open issues was part of an initial look at the current state of the project) but I'm not sure that the "stage" concept is justified by problem statement? I know Flash had a "stage", and I presume there is still some thinking in making things Flash-like, but it sounds a bit like some kind of hook system for the graphics pipeline / objects might be a better way to support tracking changes?

Perhaps I can imagine for an imGui-like HUD you might want to explicitly declare that everything under some root element of it might use a separate command buffer, to allow reuse when it doesn't change without walking the entire hierarchy to check for changes or trying to track them, perhaps such an entity with a changed/dirty flag that can be set and is cleared by the pipeline is stage-like in a way, but it needn't be a stage in the sense that there be only one or that it couldn't be a decendant?

**Comment by GoodBoyDigital** [comment]
closing this as we have somthing that offers all the benefits of the stage concept and some in v8 - render groups!
