### ISSUE TITLE
PIXI.TEXT does not supports text-decoration and '@pixi/text-html' does not supports custom fonts

### ISSUE THREAD

**Issue by 1156958090** [pixijs/pixijs#8350]
### Expected Behavior
I want to set text-decoration attributes and custom font-family at the same time. but actually PIXI.TEXT do not supports text-decoration and '@pixi/text-html' do not supports custom fonts

### Current Behavior
Neither PIXI.TEXT nor HTMLTEXT can solve my problem at the same time

### Possible Solution
no text decoration API or custom fonts

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_
pixi.js version: 6.3.2

**Comment by claudewowo** [comment]
You can see this: https://jsfiddle.net/bigtimebuddy/zm1m797m/

**Comment by bigtimebuddy** [comment]
This is correct. 

Text decoration is not support in Context2D rendering (Text), and loaded fonts in the DOM cannot cross the foreignObject boundary (HTMLText). 

There are two options:

1). You can manually draw the text decoration (line) using canvas APIs. This is unlikely to be a feature we add to Text, as it is already a complicated class.

2). The workaround for foreignObject is to load the font and inline as base64 (last time I checked). This is likely a feature we could add to that plugin.

**Comment by 1156958090** [comment]
> This is correct.
> 
> Text decoration is not support in Context2D rendering (Text), and loaded fonts in the DOM cannot cross the foreignObject boundary (HTMLText).
> 
> There are two options:
> 
> 1). You can manually draw the text decoration (line) using canvas APIs. This is unlikely to be a feature we add to Text, as it is already a complicated class.
> 
> 2). The workaround for foreignObject is to load the font and inline as base64 (last time I checked). This is likely a feature we could add to that plugin.

Thank you. I used the second way to solve my problem
