### ISSUE TITLE
Graphics.cullable does not work for lines < 1 pixel thick

### ISSUE THREAD

**Issue by davidfig** [pixijs/pixijs#8351]
```
const g = app.stage.addChild(new PIXI.Graphics())
    g.cullable = true;

    // culled
    g.lineStyle(0.5, 0xffffff).moveTo(10, 10).lineTo(100,10)

    // not culled
    g.lineStyle(1, 0xffffff).moveTo(10, 20).lineTo(100,20)
```

See: https://www.pixiplayground.com/#/edit/wHCNMjWKAu5uigVueKkV4

- **`pixi.js` version**: 6.3.0

**Comment by bigtimebuddy** [comment]
@dev7355608 what do you think?

**Comment by dev7355608** [comment]
The line is not visible because antialiasing is disabled. It doesn't show up either if you set cullable to false. Also cullable doesn't cull each path/shape of the graphics separately.

**Comment by bigtimebuddy** [comment]
Yup, thank you @dev7355608.

https://www.pixiplayground.com/#/edit/YvGNDDQahMRkpMlY5v1PH

Closing.

**Comment by davidfig** [comment]
Thanks! 

My sample code was not a good replication of the issue in my app. In the app, the renderer had antialias=true, and the Graphics element was a single horizontal or vertical line w/original width < 1. The line would disappear (or occasionally flicker when zooming in and out). Changing the cullArea to a minimum width/height of 1 fixed the bug. 

I'll see if I can do a better job of replicating the bug here.
