### ISSUE TITLE
pixels from render to texture don't match render to stage

### ISSUE THREAD

**Issue by bradedelman** [pixijs/pixijs#8360]
### Expected Behavior
Render Output from Type 0 looks exactly the same as Type 1

### Current Behavior
They are slightly different - very hard to see if you look one at a time, so the example code flips back and forth between them.

### Possible Solution
No ideas... need help finding a fix or workaround.

### Steps to Reproduce
Here's a PIXI Playground that shows the issue:
https://www.pixiplayground.com/#/edit/A59BNNukCQl8K1Q5DsK6C

### Environment

- **`pixi.js` version**: 6.3.2
- **Browser & Version**: Chrome, Version 101.0.4951.64 (Official Build) (arm64)
- **OS & Version**: macOS Monterey Version 12.0
- **Running Example**: https://www.pixiplayground.com/#/edit/A59BNNukCQl8K1Q5DsK6C

key is to watch the wiggling 
examples: right edge moves in/out
the text "Shutterstock" wiggles around / squishes vertically 

here's the code from the Playground (which can get edited, so just in case..)

```javascript
// Create our application instance
var app = new PIXI.Application({
    width: window.innerWidth,
    height: window.innerHeight,
    backgroundColor: 0x2c3e50
});
document.body.appendChild(app.view);

const W = 800;
const H = 600;
const URL = 'https://media.snry.io/protected/us-west-2:f19449c4-cfaf-4c0d-9c6b-00b0250ccbe0/ucpeniw6e7/jpg/maxsize_640x640.jpg';

function makeContainer()
{
    const container = new PIXI.Container();

    const graphics = new PIXI.Graphics();
    graphics.beginFill(0x00FF00);
    graphics.drawRect(0, 0, W, H);
    graphics.endFill();
    container.addChild(graphics);

    const sprite = PIXI.Sprite.from(URL);
    sprite.x = Math.ceil((W - sprite.width)/2);
    container.addChild(sprite);

    return container;
}

function type0()
{
    // get the container we are drawing
    const container = makeContainer();

    // just use it directly
    return container;
}

function type1()
{
    // get the container we are drawing
    const container = makeContainer();

    // render to texture
    const renderTexture = PIXI.RenderTexture.create({width: W, height: H});
    app.renderer.render(container, {renderTexture: renderTexture});

    // read the rendered pixels
    const pixels = new Uint8ClampedArray(W * H * 4);
    const gl = app.renderer.gl;
    gl.readPixels(0, 0, W, H, gl.RGBA, gl.UNSIGNED_BYTE, pixels);

    // IN THE REAL USE CASE THE PIXELS ARE PROCESSED HERE BY OTHER CODE
    
    // create texture from the pixels
    const pixiTexture = PIXI.Texture.fromBuffer(pixels, W, H, {format: PIXI.FORMATS.RGBA});

    // create a sprite with the texture
    const sprite = new PIXI.Sprite(pixiTexture);
    return sprite;
}

// result is very sensitive to the scale
// if scale if 1.0, it works as desired
// different scales have different amounts of horizontal and/or vertical "wiggle"
// this scale is a good example of bad wiggle
const SCALE = 0.98765;
let type = 0;
function tick()
{
    app.stage.removeChildren(0);

    let o;
    switch (type) {
        case 0: o = type0(); break;
        case 1: o = type1(); break;
    }

    const container = new PIXI.Container();
    container.scale = {x: SCALE, y: SCALE};
    container.addChild(o)
    app.stage.addChild(container);
    container.addChild(new PIXI.Text('Type ' + type));

    type = (type+1)%2;
    setTimeout(tick, 250);
}
tick();
```

**Comment by bigtimebuddy** [comment]
We should find a way to document those defaults, because these defaults are different from BaseTexture's defaults.

**Comment by bradedelman** [comment]
Awesome! Thank you.  I had experimented a lot with the options to render, but not with Texture.fromBuffer.

**Comment by bigtimebuddy** [comment]
I'm going to keep this open, just as a reminder on the doc fix. But glad that solved your issue @bradedelman

**Comment by bradedelman** [comment]
thanks again!

**Comment by bradedelman** [comment]
@bigtimebuddy I have a follow-up question.

https://www.pixiplayground.com/#/edit/G1ve43yaOcRfk7fw-xXsS
includes the SCALE_MODE.LINEAR fix
but adds one more wrinkle - putting the sprite at a non-integer x coordinate.

and, unfortunately, it wiggles again (though without the sampling disparity), it just moves a little left to right.

is there a similar mode to set on something else? I think the app default to LINEAR...

**Comment by dev7355608** [comment]
@bradedelman You render your sprite at a non-integer coordinate, which slightly blurs the resulting image.

A slight difference at the edges is expected when zooming in or out though: type 1 has soft edges, because it is interpolated with the green outer region that is part of the rendered texture; type 0 has sharp edges, because the sprite and the green region are separate objects.

**Comment by bradedelman** [comment]
hmm, but in Type 0, I still draw the image at the fractional coordinates... why doesn't it blur in that case?  The idea here is that the direct to screen render and the render to texture render both render EXACTLY the same things at the same coordinates, so I'd expect the RenderTexture to end up with the same exact pixels as the screen, blurred equally.  Can you explain any further why that isn't true?

**Comment by dev7355608** [comment]
Type 1 is slightly blurred when rendered to the render texture and this blurred image is sampled again, while type 0 samples from the original texture directly. Here I built you an example that should be pretty clear (https://www.pixiplayground.com/#/edit/YT9etP9e1uoHlp5V4_-zX). The texture is striped 1 pixel black, 1 pixel white, 1 pixel black, etc. If you render that at X.5 to a texture, the resulting image is completely gray: the stripes are gone. Of course regardless of how much you scale it stays gray. Type 0 is obviously going to show the stripes. https://www.pixiplayground.com/#/edit/o63qU0G0ObopdRFhU86AV

**Comment by bradedelman** [comment]
Thanks. I understand better what is happening.
