### ISSUE TITLE
@pixi/math-extras is missing in bundle

### ISSUE THREAD

**Issue by aj8k** [pixijs/pixijs#8361]
### Expected Behavior
I could use `@pixi/math-extras` content without additional package installation.

### Current Behavior
There is no `@pixi/math-extras` package in `pixi.js` bundle.

I'm not sure if it is intended behaviour or not, but looks like regular `pixi.js` bundle contains all the packages except this one. Maybe it could be added to the bundle? Or extra packages should be imported separately? I just noticed that there is `@pixi/mesh-extras` package that is still inside common bundle, so maybe this extra package also should be included?

### Environment

- **`pixi.js` version**: 6.3.2

**Comment by bigtimebuddy** [comment]
That's correct! **math-extras**, **graphics-extras**, **events** and a few other packages are not added by default and you must add these package explicitly.  As you pointed out, **mesh-extras** _is_ included by default for historical reasons (sorry for the naming confusion!). **mesh-extras** contains Rope, NineSlicePlane and other Mesh-based objects. 

If you want to create your own bundle with custom packages use this: https://pixijs.io/customize

**Comment by aj8k** [comment]
Got it, thanks!
