### ISSUE TITLE
Images not showing in Pixijs Android webview

### ISSUE THREAD

**Issue by dijitaletkinlikler** [pixijs/pixijs#8366]
Hello. Pixijs not showing images in webview. Createjs is fine with what I'm doing with konvajs. Only with pixijs the images are not visible. It works fine when there is only graphics when there is a picture. Is this problem caused by pixijs?

**Comment by Julien-Marcou** [comment]
This is probably a problem with your code and not PixiJS, but you'll have to explain your problem and give us a clear code example if you want more help.

**Comment by dijitaletkinlikler** [comment]
Ok. I got it. Thanks it was related to my code
