### ISSUE TITLE
Re-enable WebGL2 by default on mobile devices

### ISSUE THREAD

**Issue by Julien-Marcou** [pixijs/pixijs#8367]
As we can see in the [documentation](https://pixijs.download/dev/docs/PIXI.settings.html#PREFER_ENV), 3 years ago, WebGL 1 has been made the default rendering context for mobile devices (https://github.com/pixijs/pixijs/pull/5502) due to a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=934823) in Chromium browsers on mobile devices.

This bug has since been marked as fixed in Chromium, but the original change made to PixiJS (https://github.com/pixijs/pixijs/pull/5502) seems to have never been revised.

It would be nice to test and see if this behavior can be safely removed for a futur breaking change release.

WebGL 2 is now [widely supported](https://caniuse.com/webgl2) and can really improve performance in some scenarios (e.g. when using big textures with dimensions that are not pow2, as they can't be mipmapped in WebGL 1).

Unfortunately, I'm not able to test WebGL 2 on many mobile devices, but I have not seen any issue on a Pixel 3.

### Expected Behavior

I expect mobile devices to use WebGL 2 when it is supported.

### Current Behavior

Mobile devices fall back to WebGL 1 by default even when WebGL 2 is supported.

### Environment

- **PixiJS version**: 6.3.2
- **Browser & Version**: Chrome 101
- **OS & Version**: Android 12

**Comment by bigtimebuddy** [comment]
I think this has been addressed in #7974. Will be changed in 7.0.0 as it was a breaking change.

**Comment by Julien-Marcou** [comment]
Oh, nice 😅 I thought it wasn't tracked anywhere
