### ISSUE TITLE
Module not found after upgrading to Pixi v6.4.0

### ISSUE THREAD

**Issue by Julien-Marcou** [pixijs/pixijs#8379]
### Current Behavior

After upgrading from PixiJS v6.3.2 to v6.4.0, when building/serving an Angular project, I got the following error:
`Error: Module not found: Error: Default condition should be last one`

The problem seems to occur with WebPack and/or TypeScript, not only with Angular

### Expected Behavior

There should be no error

### Possible Solution

Downgrading PixiJS to v6.3.2 fixes the problem

### Environment

- **`PixiJS` version**: 6.4.0
- **`Angular` version**: 13.3.11
- **`TypeScript` version**: 4.6.4

### TSConfig

`module` is set to `es2020` and setting it to `esnext` doesn't solve the problem

**Comment by jramstedt** [comment]
Problem is in package.json files. (#8371)
"default" should be the last one in "import" and "require".

**Comment by bigtimebuddy** [comment]
Fixed by #8381

**Comment by bigtimebuddy** [comment]
Making the release now

**Comment by zwade** [comment]
@Julien-Marcou when you get some time, can you confirm that 6.4.2 fixes this for you? Thanks!

**Comment by Julien-Marcou** [comment]
Yes, everything works fine now 👍
