### ISSUE TITLE
`graphics.lineStyle()` should take a `LineStyle` but it doesn't

### ISSUE THREAD

**Issue by notexplosive** [pixijs/pixijs#8384]
Hi there! I'm new to Pixi (and new to webdev in general). I'm trying to setup a basic primitive renderer and I got tripped up by this quirky behavior.

Here's a TypeScript sample, I have 3 "options" for how to render a line, options 1 and 2 work, but option 3 doesn't. But it really feels like it should!

```ts
import * as PIXI from "pixi.js";

let app = new PIXI.Application({
  width: 800,
  height: 600,
  backgroundColor: 0x111111,
});

// setup a lineStyle to my liking
var lineStyle = new PIXI.LineStyle();
lineStyle.color = 0xFF0000;
lineStyle.width = 1;
lineStyle.join = PIXI.LINE_JOIN.ROUND;

var graphics = new Graphics();

// The following presents 3 options that should be equivalent

// option 1: pass primitives into lineStyle(), this works but is missing some properties of lineStyle (join, cap, matrix, etc)
graphics.lineStyle(lineStyle.width, lineStyle.color, lineStyle.alpha, lineStyle.alignment, lineStyle.native);

// option 2: pass all properties of LineStyle to lineStyle() in one big object, implementing ILineStyleOptions, very cumbersome
graphics.lineStyle({
            color: lineStyle.color,
            alpha: lineStyle.alpha,
            width: lineStyle.width,
            alignment: lineStyle.alignment,
            native: lineStyle.native,
            cap: lineStyle.cap,
            join: lineStyle.join,
            miterLimit: lineStyle.miterLimit,
            matrix: lineStyle.matrix
        });

// option 3: pass the whole value of LineStyle, this _should_ work, but doesn't.
graphics.lineStyle(lineStyle);

graphics.moveTo(100, 100);
graphics.lineTo(200, 200);
app.stage.addChild(graphics);
```

### Expected Behavior
Option 3 described above should work.

### Current Behavior
Option 3 does not render anything.

### Possible Solution
I'm not a TypeScript expert (I'm actually using pixi as an excuse to really dig into TypeScript/JS) but it seems like LineStyle should be allowed to implement `ILineStyleOptions`. The clunky (but workable) solution would be to wrap Option 2 into an overload for `lineStyle()` that takes a `LineStyle`.

### Steps to Reproduce
- Copy above snippet.
- Comment out each "option" but option 1, line should render
- Comment out each "option" but option 2, line should render
- Comment out each "option" but option 3, line no longer renders

### Environment

- **`pixi.js` version**: 6.4.2
- **Browser & Version**: 102.0.5005.63 
- **OS & Version**: Windows 10
- **Running Example**: none sorry!

**Comment by bigtimebuddy** [comment]
LineStyle is not a public class it is only used internally to apply line changes. It is not meant to be used this way.
