### ISSUE TITLE
Different types for getter and setter in display package

### ISSUE THREAD

**Issue by Keycher** [pixijs/pixijs#8385]
I found an error in this commit
[link](https://github.com/pixijs/pixijs/commit/2c2b605239420c24417bd244e2e4bf4837619590#diff-c429f6e13dead1384160eb15715b80784269464d75f89543f9a77021aba2e618)

Currently pixijs have different types for getter and setter. 
And cause of this, spine v3.0.14 have an error too. d.ts file is missing and I cannot to build it manually.

it will throw the error like this:
_error TS2380: 'get' and 'set' accessor must have the same type._

### Expected Behavior
No error during building types for spine.
### Current Behavior
![image](https://user-images.githubusercontent.com/6191357/171829762-5475ac2e-2738-48ab-bccd-921c0588abce.png)

### Steps to Reproduce

- clone [release spine repo](https://github.com/pixijs/spine/tree/release)
- do _rush build:types_

### Environment

- **`pixi.js` version**: _6.4.2_
- **OS & Version**: _Windows 10_

**Comment by bigtimebuddy** [comment]
Maybe either upgrade your typescript where this getter/setter type issue is supported, or don't parse libs in your tsconfig.

**Comment by ivanpopelyshev** [comment]
interesting. is it the same for spine v.3.0.13?

**Comment by Keycher** [comment]
@ivanpopelyshev, yep the same for pixi spine v.3.0.13. I'm looking at problem and trying to fix it from spine repo.
@bigtimebuddy, it's not a problem in my config. This is the issue in pixi-spine. I can't build declaration files, and they are missing in package. So, if you update your spine to new version - it be broken(

**Comment by ivanpopelyshev** [comment]
Do you mean UMD declarations or what?

**Comment by Keycher** [comment]
nope, index.d.ts, they are missing

**Comment by Keycher** [comment]
yep, I found the problem. Will send the PR into spine repo, it's not a problem of pixi.js

**Comment by ivanpopelyshev** [comment]
Good. i'll merge it today then. Also I forgot to push 3.0.14 in repo, it exists only on my pc :)
