### ISSUE TITLE
Feat: Add option to disable inline CSS style for the cursor

### ISSUE THREAD

**Issue by Julien-Marcou** [pixijs/pixijs#8387]
### Description

PixiJS adds default inline CSS style on the canvas, which makes it difficult to override the cursor style.

In my case, I want the cursor style to be based on a data attribute I set on the canvas (which I change on the fly when the user make different interactions with the canvas), but because the cursor is already defined inline, I either have to set `!important` everywhere or remove the inline cursor property first.

It would be nice to have this as an option to set when creating the Pixi Application.

### Current behavior

```js
new Application({
  view: canvas,
});
requestAnimationFrame(() => {
  canvas.style.removeAttribute('cursor');
});
```

### Possible implementation

```js
new Application({
  view: canvas,
  inlineCssCursor: false,
});
```

**Comment by bigtimebuddy** [comment]
My alternative suggestion is a much more local change in InteractionManager. Maybe having a property `disableInlineCursor`:

```js
app.renderer.interaction.disableInlineCursor = true;
```

Adding Application options for very small cases like this isn't great, but you could create your own Application plugin (i.e., `Application.registerPlugin`) to support your own convenient option.

Here is the flag to set the styles internally in InteractionManager:

https://github.com/pixijs/pixijs/blob/a87bb87036d5fb9119ee92fd9c3da23b5bb9424b/packages/interaction/src/InteractionManager.ts#L943

Could be changed to:

```js
let applyStyles = !this.disableInlineCursor;
```

**Comment by andrewstart** [comment]
The cursor capabilities of the InteractionManager are underdocumented (which is really my fault), but if you set `app.renderer.interaction.plugins.interaction.cursorStyles.default = null;` it will stop applying the `"inherit"` cursor style to the canvas.

**Comment by Julien-Marcou** [comment]
I thought the default style applied was just here because of some sort of CSS/UX improvements for the end user (like a mainstream CSS reset). I didn't know it was there for Interactions.

So I was tinkering a bit with the source code to see how it works and maybe make a PR, but now that I know how it works, I agree that it would be better to handle this through a new property for the `InteractionManager.ts`, but because `app.renderer.plugins.interaction.cursorStyles.default = null;` does the trick, I think this is no longer necessary 😄.

Because of the ESLint config that I use, I need to write it like that:
`((this.application.renderer.plugins['interaction'] as InteractionManager).cursorStyles['default'] as any) = null;`

Also, in my case, I don't need Interactions at all. I have several overlapping sprites procedurally generated from random bezier curves and I need to detect if the user is interacting with a sprite through transparent pixels of other sprites.
I have my own interaction logic on top of PixiJS using the `toLocal()` method from PixiJS and `PointerEvent` from the canvas.

So, I ended up just disabling the Interaction plugin:
`(this.application.renderer.plugins['interaction'] as InteractionManager).destroy();`
