### ISSUE TITLE
PIXI 6.4.2 produces issues in @pixi/display  while compile angular 11 

### ISSUE THREAD

**Issue by thangaraj80** [pixijs/pixijs#8393]
### Expected Behavior
in Angular 11 typescript 4.1.6, while ng serve @pixi/display needs to compile without error 

### Current Behavior
is throwing an error --- ** 'get' and 'set' accessor must have the same type.**  in the following set get @pixi/display/index.d.ts
accessor is different

get skew(): ObservablePoint;
set skew(value: **IPointData**);

 get position(): ObservablePoint;
 set position(value: **IPointData**);

get scale(): ObservablePoint;
set scale(value: **IPointData**);

get pivot(): ObservablePoint;
set pivot(value: **IPointData**);

### Environment

- **`pixi.js` version**: _e.g. 6.4.2_
- **`Angular` version**: _e.g. 11.1.2_
- **`Typescript` version**: _e.g. 4.1.6_

**Comment by bigtimebuddy** [comment]
You must upgrade to TypeScript 4.3+ to support the getter/setter different types.

**Comment by thangaraj80** [comment]
Thanks bigtimebuddy
