### ISSUE TITLE
TextureCache and BaseTextureCache are always empty after 6.4.2

### ISSUE THREAD

**Issue by legman** [pixijs/pixijs#8398]
I recently updated to PIXI legacy 6.4.2 from PIXI legacy 6.2.2. I have noticed that although my images and texture sheets were loading fine, they were not being added to the TextureCaches. This results in `PIXI.Texture.from` not working as I am using `STRICT_MODE`.

Not doing anything clever, this is just a barebones project start. If I revert back to 6.2.2, everything works as intended. Has something changed in 6.4.2 and this is expected behaviour?

Thanks!

**Comment by bigtimebuddy** [comment]
Could you provide a clean reproduction of this, if you don't mind? 

This sounds like an issue we have had with upgrading in v6 and peer dependencies. Try completely uninstalling first, then install 6.4.2.

**Comment by legman** [comment]
Sorry, I won't be able to provide a reproduction right now. Thanks for the heads up - I thought I was going crazy!

I am fine using 6.2.2 for now but out of curiosity, which peer dependencies are potentially causing the issue?

**Comment by andrewstart** [comment]
It's not any particular dependency, but sometimes when upgrading you might end up with an incomplete update, where you have a version mixture (of 6.22 and 6.4.2 in your case) and end up with two copies of a given package where one is getting used internally and the other is being directly accessed by you.

**Comment by ambuddy** [comment]
Got the same issue after updating from 6.3.0 to 7.0.2

**Comment by Zyie** [comment]
We now have an [Upgrading PixiJS](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS) wiki that should help anyone running into issues like this when changing pixi version
