### ISSUE TITLE
displacementFilter problem

### ISSUE THREAD

**Issue by a6965921** [pixijs/pixijs#8402]
![image](https://user-images.githubusercontent.com/1198840/173559867-e544d356-2635-4f9c-9df1-7f5a7412aedf.png)
![image](https://user-images.githubusercontent.com/1198840/173559964-44fd8ca4-f719-4d96-b67a-885c15febd2e.png)
![image](https://user-images.githubusercontent.com/1198840/173560000-676c3c87-6e67-4632-8e7c-f5f91603f740.png)

**Comment by bigtimebuddy** [comment]
Please create a reproduction so that we can debug.

**Comment by Zyie** [comment]
Closing as it seems this is not an issue with pixi
