### ISSUE TITLE
drawPolygon() alignment misbehaves when the points are counter-clockwise

### ISSUE THREAD

**Issue by getkey** [pixijs/pixijs#8409]
### Expected Behavior

The ordering of the vertices in `graphics.drawPolygon()` shouldn't affect its alignment.

The red element, which is bigger than the orange polygon should be visible.
![image](https://user-images.githubusercontent.com/6908397/174449706-9669dd7c-bb0c-4a78-95f1-4d05712aeef8.png)

### Current Behavior

When the vertices are counter-clockwise, the polygon is drawn as if it had `alignment` set to `1`. It behaves as expected when its vertices are clockwise.

The orange polygon is covering up the red element below.
![image](https://user-images.githubusercontent.com/6908397/174449669-5be3310e-4dd9-4bc8-bc26-dee51db8e39c.png)

### Possible Solution

Possibly related issues: #5064 #5242

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/6qib2R7ShmUZ26PzRSxdQ

### Environment

- **`pixi.js` version**: 6.4.2
- **Browser & Version**: Firefox 101.0.1
- **OS & Version**: NixOS 22.05
- **Running Example**: https://www.pixiplayground.com/#/edit/6qib2R7ShmUZ26PzRSxdQ

This bug was discovered in https://github.com/getkey/ble/pull/79.

**Comment by dev7355608** [comment]
The playground is always 5.3.0 by default for some reason. I changed it to 6.4.2. Now the alignment is the same regardless of the polygon's orientation.

**Comment by bigtimebuddy** [comment]
Thanks for looking into this. This is the expected behavior in v5 and it won't be fixed.
