### ISSUE TITLE
 Property 'click' does not exist on type 'Sprite'.

### ISSUE THREAD

**Issue by Tai3324** [pixijs/pixijs#8412]
I am getting a problem in TS. It say "Property 'click' does not exist on type 'Sprite'".Is there something missing?
![appe](https://user-images.githubusercontent.com/93297971/174569206-c05d343d-0d33-4dad-a356-a919fec7b1eb.png)

**Comment by domis86** [comment]
please add more info:
- relevant code fragment(s)
- description of your setup (version of pixi, typescript / webpack config etc)
- ideally: minimal reproduction of this problem on [pix](https://www.pixiplayground.com/) or similar page

**Comment by Tai3324** [comment]
![image](https://user-images.githubusercontent.com/93297971/174581166-eabf5bfc-04eb-4b83-8b6b-6c2043e643d0.png)


tsconfig.json
![image](https://user-images.githubusercontent.com/93297971/174581594-2b2c7eb3-a444-4ca9-bfb1-cb95027b39ee.png)

package.json
![image](https://user-images.githubusercontent.com/93297971/174582162-200846c7-869a-4f5a-8fb2-c650b1b4b826.png)

- pixi.js version 6.4.2

**Comment by bigtimebuddy** [comment]
Thanks for the answer @domis86
