### ISSUE TITLE
Bitmap font is shaking/jittering on newer pixi versions

### ISSUE THREAD

**Issue by tsopeh** [pixijs/pixijs#8432]
### Expected Behavior

I expect for bitmap text to be rendered without shaking, as in previous pixi versions (e.g. 5.3.12). The bitmap font is guaranteed to be monospaced since every glyph has the same `xadvance`.

### Current Behavior

The text appears to be slightly shaking when changing the value. In the demo I provided, I used the version `6.4.2` as a reference, but I believe that the issues started appearing from the version `6.3.0`.

This is possibly related to #8246.

### Steps to Reproduce

The demo code can be found here: https://drive.google.com/file/d/1IVs3gt8ImxiDDhxTLMRyzzx56nr0SXIa/view?usp=sharing
You can toggle pixijs version in the `index.html`.

### Environment

- **`pixi.js` version**: _6.3.0 – 6.4.2_

**Comment by lazarljubenovic** [comment]
We're also experiencing this issue upon trying to upgrade from `6.0.0-rc.2` to the newest version.

**Comment by tsopeh** [comment]
Here's some video samples that illustrates the issue in a real application:

1. Without jittering (good behaviour on older versions)

https://user-images.githubusercontent.com/37545996/178275581-7b8d2c0e-0976-41d2-bb16-0ea89d2c816d.mp4

2. With jittering (bad behaviour on newer versions)

https://user-images.githubusercontent.com/37545996/178275651-32038511-f1e1-472e-8903-d87ede9a22bf.mp4

**Comment by tsopeh** [comment]
Thanks for the explanation and a workaround @bigtimebuddy.

**Comment by grebinka** [comment]
xOffset and xAdvance are added while calculating lastLineWidth. But only xAdvance should be.
That's why everything works with xOffset = 0
I've added pull request to fix this problem (#8536)
