### ISSUE TITLE
Is there a way to have a mask only affect shape and not colour?

### ISSUE THREAD

**Issue by MiGongOrg** [pixijs/pixijs#8451]
```javascript
const filter = new PIXI.SpriteMaskFilter(mask)
sprite.filters = [filter]
```
Similar problems：

https://www.html5gamedevs.com/topic/35812-is-there-a-way-to-have-a-mask-only-affect-shape-and-not-colour/

https://www.html5gamedevs.com/topic/33919-clipping-one-sprite-with-other-using-pixijs-mask-while-keeping-masked-one-original-colors/

No solution was found after checking the document

Could you please provide an example?

"pixi.js": "^6.2.2"

**Comment by ivanpopelyshev** [comment]
Copy original `SpriteMaskFilter.ts` and its shader, remove multipication

Alternative: use https://pixijs.io/examples/#/plugin-picture/mask-blur.js , pass VoidFilter to pixi-picture's MaskFilter , and tell MaskFilter to ignore colors, there's an option

**Comment by MiGongOrg** [comment]
Thank you for your help
