### ISSUE TITLE
Importing CanvasRenderer does not override DisplayObject classes

### ISSUE THREAD

**Issue by Axolotl778** [pixijs/pixijs#8453]
I'm having an issue with using `CanvasRenderer`, specifically, it's `generateCanvasTexture()`

To start with, what I'm trying to achieve is semitransparent rectangle covering the whole screen with transparent holes in it.

To do so, I create rectangle with `PIXI.Graphics` and apply a mask to it. But since inverse masking is not supported, I'm using `SpriteMaskFilter` with custom shader, and since it requires a texture, I was generating it with `Renderer.generateTexture`, but due to [this issue](https://github.com/pixijs/pixijs/issues/3260) I'm trying to switch to `CanvasRenderer` in this particular case.

The problem is importing CanvasRenderer [does not override DisplayObject and Graphics classes](https://github.com/pixijs/pixijs/issues/6069#issuecomment-528772758), and I can't seem to find a way to do it properly. When running code in example, I'm getting `Uncaught TypeError: displayObject.renderCanvas is not a function` (visible only in browser console since it's coming from package).

To be clear, I'm using WebGL renderer in my project and need canvas renderer only to generate a texture. I also [tried](https://codepen.io/axolotl778/pen/MWVWPaY) to use Graphics with children as black and white mask, but it doesn't seem to work without transparency.  

### Environment
- **pixi.js 6.4.2**
- **Browser & Version**: Firefox (DE) 95.0b11
- **OS & Version**: MacOS 10.14.6
- **Running Example**: [Codepen](https://codepen.io/axolotl778/pen/PoRodWJ)

**Comment by zero41120** [comment]
I got exactly the same problem with generate texture today. So I did some digging in the source code.

It appears that you need to register those legacy plugins. 

You can use Pixi customize tool, just select everything in the canvas section: https://pixijs.io/customize/
![image](https://user-images.githubusercontent.com/10471270/184733409-ba4ece95-b657-4bfe-9fbc-afacc2840ebb.png)

For the `generateTexture`, I think you just need graphics (and perhaps sprite)

```
import { CanvasRenderer, CanvasGraphicsRenderer, CanvasSpriteRenderer } from 'pixi.js-legacy';

CanvasRenderer.registerPlugin('graphics', CanvasGraphicsRenderer);
CanvasRenderer.registerPlugin('sprite', CanvasSpriteRenderer);
const application = new Application({ forceCanvas: true });
```

**Comment by bigtimebuddy** [comment]
Use `pixi.js-legacy`. You do not need to register any of the canvas plugins if you use that bundle.

**Comment by Zyie** [comment]
Closing as [this](https://github.com/pixijs/pixijs/issues/8453#issuecomment-1215991205) comment should solve the issue.

Feel free to open back up if it does not help
