### ISSUE TITLE
The source separation by require/import breaks non-esm dependencies

### ISSUE THREAD

**Issue by lunarraid** [pixijs/pixijs#8467]
Pixi's package.json now separates output sources depending on whether `import` or `require` was used to import it. This causes issues in webpack with dependencies that were transpiled to umd, as umd will use `require` statements. If the primary project uses `import`, then the primary project will load the esm dist, and the dependency will load the cjs dist, causing two different pixi runtimes to be imported and breaking the dependency.

### Expected Behavior
Only the /cjs/ or /esm/ sources should be imported into the project.

### Current Behavior
Both /cjs/ and /esm/ sources will be imported into the project.

### Steps to Reproduce
Create a barebones Webpack 5 project.
import both pixi.js and pixi3d.
/cjs/ and /esm/ modules are now both loaded into the project.

### Environment

- pixi.js version 6.4.2

**Comment by bigtimebuddy** [comment]
@jnsmalm Pixi3D should probably be outputting ESM/module format not just UMD. That would resolve this issue. This is not really possible with Webpack, so I suggest transitioning to Parcel or Rollup internally which have much better output for modules for libraries.

As for this general issue, sorry that you are bumping into this @lunarraid. The support for Node's new `exports` field was added #8371 and #8381 largely to support a better typing experience in TypeScript with ESM. We likely underestimated the disruption this would cause and apologize for the inconvenience. The JS ecosystem is constantly transitioning around distribution formats and tooling and we are trying our best to keep up.

It is our recommendation that developers making third-party Pixi dependencies provide both esm and commonjs formats for compatibility across a diverse set of tools.

**Comment by lunarraid** [comment]
As this is a rather nasty surprise for anyone relying on 3rd party libs, can we add to the documentation that UMD modules are no longer supported?

**Comment by lunarraid** [comment]
@jnsmalm It helps for pixi3d, but not any other libraries currently built on pixi v6 that don't have esm exports. I do agree that the ecosystem as a whole should start transitioning over, but umd is still a very common default export for npm libs.

**Comment by bigtimebuddy** [comment]
> UMD modules are not longer supported

This isn't quite specific enought. Something more accurate would be:

> If you're using a tool that respects Node.js's `exports` field in the package.json (e.g. Webpack), using 3rd party plugins that _only_ provide a UMD or CommonJS output will not bundle correctly. Please contact the plugin maintainer and ask them to provide an ESM output.

I tried the latest pixi.js and pixi3d with Parcel and it worked fine: https://github.com/bigtimebuddy/pixi3d-example But I believe that Parcel hasn't added support for `exports` yet.

Also, @lunarraid have you tried setting a resolve path for "pixi.js" to be the CommonJS unbundle instead? Wondering what the guidance is for folks also bumping into this.

**Comment by lunarraid** [comment]
I did try aliasing it and that allowed my barebones repo to function, though that was only if modules use `pixi.js`. I'd imagine that if you're importing dependencies, you would have to alias every single subpackage. I ran into some other issues with this method in my larger package but haven't tracked them down yet. I'm not 100% certain `alias` is the best way to go as you need to manually alias any possible variation of the imports, but also haven't yet found the proper way to _force_ either esm or cjs for a dependency. Still digging.

**Comment by bigtimebuddy** [comment]
How does `mainFields` interact (if at all) with import/require exports?
```
module.exports = {
  //...
  resolve: {
    mainFields: ['browser', 'main', 'module'],
  },
};
```

**Comment by lunarraid** [comment]
> How does `mainFields` interact (if at all) with import/require exports?
> 
> ```
> module.exports = {
>   //...
>   resolve: {
>     mainFields: ['browser', 'main', 'module'],
>   },
> };
> ```

This was the first thing I tried. It stops some of it, but not all. Something was still importing from module even when I excluded it from `mainFields`.

**Comment by bigtimebuddy** [comment]
I think this is an issue you should also consider raising on Webpack.

**Comment by lunarraid** [comment]
> I think this is an issue you should also consider raising on Webpack.

I thought about this too, but I don't even know what they're doing _wrong_ here, as they are simply following the instructions that the package.json is giving them.

**Comment by bigtimebuddy** [comment]
I created another simple example for a workaround of folks discovering this:
https://github.com/bigtimebuddy/webpack-esm-cjs-mix-example
