### ISSUE TITLE
Text Rendering Issues on Brave Browser

### ISSUE THREAD

**Issue by diegomachado** [pixijs/pixijs#8473]
### Expected Behavior
Text rendering should be the same across all browsers 

### Current Behavior
![pixi-text-rendering-browser-comparison](https://user-images.githubusercontent.com/104657/178015670-beddf57e-2f2c-48ba-a213-594e0764a40f.png)

- All texts are rendered at a little lower Y value;
- On a multiline text, line height is much bigger than expected;
- This behavior does not happen when using BitmapText; (at least when using https://pixijs.io/examples/#/text/bitmap-text.js)

### Steps to Reproduce
Using the official Text Example

### Environment
- **`pixi.js` version**: 6.4.2 - WebGL 2
- **Brave** - Version 1.40.113 Chromium: 103.0.5060.114 (Official Build) (64-bit)
- **Firefox** - Version 102.0.1 (64-bit)
- **Chrome** - Version 103.0.5060.114 (Official Build) (64-bit)
- **OS & Version**: Windows 11
- **Running Example**: https://pixijs.io/examples/#/text/text.js

**Comment by bigtimebuddy** [comment]
What happens if you explicitly set the lineHeight? Does that normalize the rendering? I'm guessing that the default value of `0` is getting interpreted differently.

**Comment by bigtimebuddy** [comment]
If I had to guess, this seems to be a bug in Brave about how it measures text (e.g. `context.measureText`). Must of this functionality is wrapped up in the [`PIXI.TextMetrics`](https://github.com/pixijs/pixijs/blob/dev/packages/text/src/TextMetrics.ts). One thing that would be helpful @diegomachado would be to output values from `TextMetrics.measureText` to see if there are any differences. That may help track down what's going on.

**Comment by diegomachado** [comment]
Confirming that I'm getting completly different values between browsers, still can't pinpoint the root of the issue yet:

![pixi-text-metrics-comparison](https://user-images.githubusercontent.com/104657/178072677-6a7a7b3c-e364-4787-94e9-595f291b9326.png)

These outputs are from my own game, using a custom font using a `fontSize: 40` property. As you can see, `height` and `lineHeight` are the only ones really affected and it's totally breaking my text formating with a `20` pxs difference.

Any tips for further debugging are welcome :)

**Comment by diegomachado** [comment]
Ok, I think I found the issue, but not a solution.

This seems to be the root cause:
https://github.com/brave/brave-browser/issues/1738

When I disabled Brave default Block fingerprinting (clicking on the Brave Logo on the right of the address bar), text rendering worked as expected:
![brave-fingerprint](https://user-images.githubusercontent.com/104657/178073998-51c96cb5-eaef-4a0c-99af-25a0f679214e.png)

**Comment by miltoncandelero** [comment]
Yeah, it's a feature of brave.
Brave randomizes the canvas text rendering to prevent fingerprinting

Learn more: https://en.wikipedia.org/wiki/Canvas_fingerprinting

Fingerpint test: https://browserleaks.com/canvas

**Comment by diegomachado** [comment]
For anyone experiencing the same issue, I've solved mine with a "pre-made" BitmapFont, using https://snowb.org/

BitmapFonts generated with https://pixijs.download/dev/docs/PIXI.BitmapFont.html#from caused the same rendering issues on my project.
