### ISSUE TITLE
ReferenceError: Can't find variable: ImageBitmap (not supported)

### ISSUE THREAD

**Issue by CarlosLleraMartin** [pixijs/pixijs#8498]
Hello PixiJS people!

I think I've found a bug that luckily could have an easy fix. It's blocking us from using PixiJS on browsers with no support for the `ImageBitmap API`, so I hope it can be addressed soon (if it's a problem in the end...).

I don't know very well the flow of actions that lead us to the error, but I was able to narrow it to the specific problematic line in the library, and I found a simple solution out there. Here are the fields describing the situation. Thanks for the great work guys!

### Expected Behavior

PixiJS should work correctly in the listed [supported browsers](https://github.com/pixijs/pixijs/wiki/FAQs#what-browsers-are-supported) even though they don't support the `ImageBitmap API`: https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap and the [createImageBitmap()](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap) is polyfilled in the application.

### Current Behavior

When in a browser that doesn't support _ImageBitmap API_ and has the _createImageBitmap()_ method polyfilled, a PixiJS app is run and it loads assets in a way that `ImageBitmapResource.test()` is called (excuse me for not being more specific here), the following error is encounter and the app crashes:

```
ReferenceError: Can't find variable: ImageBitmap
```

### Possible Solution

I found the error exactly in this line:

```ts
// pixijs/packages/core/src/textures/resources/ImageBitmapResource.ts:25

return !!globalThis.createImageBitmap && source instanceof ImageBitmap;
```

Usually because of the lazy evaluation in JS, when `createImageBitmap` is not available the static `test()` function would stop there and directly return false, **but if you polyfill it**, the second checking will be reached, causing the error.

The guys from three.js solved this just by checking if the ImageBitmap is defined:
https://github.com/mrdoob/three.js/issues/15885
https://github.com/mrdoob/three.js/pull/15900/files

```ts
// Fix example in ImageBitmapResource.ts
// ...
    static test(source: unknown): source is ImageBitmap
    {
        return !!globalThis.createImageBitmap && typeof ImageBitmap !== 'undefined' && source instanceof ImageBitmap;
    }
```

**IMPORTANT:** This error could be happening in other places as well. I'd make sure that other calls to `... instanceof ImageBitmap` and other possibly non-available vars because of compatibility issues are protected by this previous checking.

### Steps to Reproduce

The easiest way to reproduce this error is to directly call the `ImageBitmapResource.test()` function (see _Running example_).

### Environment

- **`pixi.js` version**: 5.3.0 (but potentially with any?)
- **Browser & Version**: e.g. Safari 14.6 (tecnically any browser not supporting [ImageBitmap API](https://caniuse.com/?search=ImageBitmap))
- **OS & Version**: e.g. iOS 14.6 (tecnically any OS)
- **Running Example**: https://www.pixiplayground.com/#/edit/5L5izJzsxbcCUJXttMJQJ

**Comment by bigtimebuddy** [comment]
Thanks for reporting. We can get this into our coming release if someone wants to make a PR.

**Comment by CarlosLleraMartin** [comment]
Thank you very much for considering this. Here is the PR: https://github.com/pixijs/pixijs/pull/8499
I couldn't take the time to go through all checkings but I hope it's safe and simple enough to be merged.
Thanks again!
