### ISSUE TITLE
v6.5.0-rc.4: Unable to import `Assets` from `pixi.js`

### ISSUE THREAD

**Issue by Julien-Marcou** [pixijs/pixijs#8514]
I wanted to give it a try to the new `assets` package.

### Expected Behavior

In PixiJS I'm able to import pretty much everything from `pixi.js`.

e.g. `import { Application } from 'pixi.js';`

But the new `Assets` package is only accessible through its respective package.

i.e. `import { loadSpritesheet } from '@pixi/assets';`

Which means I have to run `npm install @pixi/assets` in addition of the `npm install pixi.js`

### Current Behavior

`import { loadSpritesheet } from 'pixi.js';` gives the error `Module '"pixi.js"' has no exported member 'loadSpritesheet'.ts(2305)`

Not sure if this is a bug or not, but I wanted to clarify this before the final release 😅 I understand if the goal is to provide a lighter `pixi.js` package with optional dependencies that I have to install myself.

### Environment

- **`pixi.js` version**: `6.5.0-rc.4`

**Comment by bigtimebuddy** [comment]
Yes, this is as-designed. Assets is being introduced as an opt-in. It will become the default in v7 (much like events). So you must import this package separately from the main bundle.

**Comment by Julien-Marcou** [comment]
Good to me 🙂
