### ISSUE TITLE
v6.5.0-rc.4 `pixi.js` package has invalid `@pixi/canvas-renderer` dependency

### ISSUE THREAD

**Issue by Julien-Marcou** [pixijs/pixijs#8516]
### Expected Behavior

After upgrading a project from the v6.4.2 to the v6.5.0-rc.4 I shouldn't have any errors.

### Current Behavior

```sh
Error: node_modules/@pixi/app/index.d.ts:4:37 - error TS2307: Cannot find module '@pixi/canvas-renderer' or its corresponding type declarations.

4 import type { CanvasRenderer } from '@pixi/canvas-renderer';
                                      ~~~~~~~~~~~~~~~~~~~~~~~
```

```sh
Error: node_modules/@pixi/settings/index.d.ts:3:37 - error TS2307: Cannot find module 'ismobilejs' or its corresponding type declarations.

3 import type { isMobileResult } from 'ismobilejs';
                                      ~~~~~~~~~~~~
```

`@pixi/app` has a dependency to `@pixi/canvas-renderer` that was not present in the `v6.4.2`, as `pixi.js` is described `PixiJS without the CanvasRenderer fallback, modern browsers only` I think this dependency should not be present.

As for the `isMobileResult`, I think it is related to #8502 that is not fully fixed yet.

### Steps to Reproduce

```sh
git clone git@github.com:Julien-Marcou/puzzle.git
cd puzzle/front
git checkout pixi-6.5
npm install
npm run start

```

### Environment

- **`pixi.js` version**: `v6.5.0-rc.4`

**Comment by bigtimebuddy** [comment]
These should be easy to sort. Thanks for reporting.
