### ISSUE TITLE
Is it possible to check current PixiJS version when not using the bundle?

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixijs#8519]
My plugin to PixiJS is only using @pixi/core, @pixi/display, @pixi/loaders and so on as dependencies (not using the PixiJS bundle which have the VERSION property).

Is it then possible to check current PixiJS version somehow?

**Comment by jnsmalm** [comment]
Right now I'm thinking about doing this:

```
import * as PixiCore from "@pixi/core"

export namespace PixiVersion {
  export function isLaterThan6() {
    // @ts-ignore
    return PixiCore["ArrayResource" + ""] !== undefined
  }
}
```

**Comment by bigtimebuddy** [comment]
Added a fix for this. You'll be able to do this instead:
```js
import { VERSION } from '@pixi/core';
```

**Comment by bigtimebuddy** [comment]
But, you're right, there's no way to get this other than doing a feature detection. Will probably not help you with older versions.

**Comment by jnsmalm** [comment]
Cool, It will be useful in the future :)
