### ISSUE TITLE
Documentation is wrong for module import

### ISSUE THREAD

**Issue by nnnnnhal** [pixijs/pixijs#8521]
### Expected Behavior
Documentation to be accurate 

### Current Behavior
Uncaught TypeError: PIXI.Application is not a constructor

### Steps to Reproduce
```
    <script type="module">
    
    import * as PIXI from './imported/v6.5.0-rc.4.pixi.min.js'
    let app = new PIXI.Application({ width: 200, height: 200 });

```

also
```
import {Application} from './imported/v6.5.0-rc.4.pixi.min.js'
    let app = new PIXI.Application({ width: 200, height: 200 });

```

### Environment

- **`pixi.js` version**:  v6.5.0-rc.4
- **Browser & Version**: _e.g. Firefox 102

Apologizes if im stupid here and missed something. I can run Pixi fine when not doing modules but this is the unexpected behavior. I see the export in the code base  l:42721 exports.Application = Application;

**Comment by bigtimebuddy** [comment]
Checkout this example: https://github.com/bigtimebuddy/pixi.js-browser-module-example

**Comment by nnnnnhal** [comment]
Cool, that looks right, I do notice you are using version : pixi.js - v5.3.2 however
Is the 6 series different somehow?

**Comment by bigtimebuddy** [comment]
Should be the same, just use the mjs file in dist/browser

**Comment by bigtimebuddy** [comment]
Closing this, please start a discussion if you need more help.
