### ISSUE TITLE
6.5.0 Application.start() / app.stop() removed ?

### ISSUE THREAD

**Issue by Makio64** [pixijs/pixijs#8522]
Hi,

I just bump the version and discover the Application.start() / Application.stop() have been remove, whats the recommend way to replace it ? It was quite usefull..

Thanks

D

- **`pixi.js` version**: _e.g. 6.5.0_

**Comment by bigtimebuddy** [comment]
This has not been removed, see here: https://jsfiddle.net/bigtimebuddy/wo0s64t2/

Could you please provide some more information or a reproduction? Unexplained issues like this are usually the result of [upgrading](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS).

**Comment by bigtimebuddy** [comment]
I believe that #8527 took care of this. If you're still experience in 6.5.1, we can re-open.
