### ISSUE TITLE
Bundle size increase two times from 6.4.2 to 6.5.0

### ISSUE THREAD

**Issue by dmitriyzhirma** [pixijs/pixijs#8526]
Hi,

After update from 6.4.2 to 6.5.0 my build size increate two times. I check bundle size pixi on: 

https://bundlephobia.com/package/pixi.js@6.5.0

### Environment

- **`pixi.js` version**: _6.5.0_

**Comment by Julien-Marcou** [comment]
I can confirm, looks like the entire `@pixi/core` package (with its imports) is re-bundled within the `@pixi/ticker` package.

There might be other problems.

**Comment by bigtimebuddy** [comment]
Thanks @dmitriyzhirma (and thanks for that link too, I haven't used that site before, very handy).

This is why I like releasing on Friday, we will get this sorted by tomorrow.

**Comment by dmitriyzhirma** [comment]
Thanks!
