### ISSUE TITLE
Request: new Asset Manager base64 support

### ISSUE THREAD

**Issue by talhaozdemir** [pixijs/pixijs#8529]
### Expected Behavior
Loading assets with base64 string like
`await Assets.load('data:image/png;base64,iVBORw0....')`

### Current Behavior
A warning appears in the console like;
data:image/png;base64,iVBO... could not be loaded as we don't know how to parse it, ensure the correct parser has being added

### Environment

- **`pixi.js` version**: 6.5.0
- **Browser**: Chrome
- **OS & Version**:  Windows 11

**Comment by bigtimebuddy** [comment]
That's a good suggestion. We do have a base64 plugin for assets, but it's part of `@pixi/node`. Perhaps we can move this up to `@pixi/assets`...

https://github.com/pixijs/pixijs/blob/dev/bundles/pixi.js-node/src/adapter/loadNodeBase64.ts

**Comment by talhaozdemir** [comment]
It would be good because sometimes it is needed to bundle all assets in a single html file. We cannot use URL loader because of CORS issues.

**Comment by Zyie** [comment]
Added in #8559
