### ISSUE TITLE
Texture.frame doesn't appear to work when passed to glsl fragment shader in normal map example

### ISSUE THREAD

**Issue by BeebBenjamin** [pixijs/pixijs#8532]
I am using this example: https://codepen.io/ivanpopelyshev/pen/jOWLjKd as a template for rendering a normal map and changing the direction of the lighting.  I have this example translated and working in my react application using a different texture and normal map for the whole image.  However, I would like to choose what portion of the texture and normal map is being rendered by the glsl shader by specifying the x,y start coordinates followed by the width and height.  From the Pixijs docs it seems that PIXI.Texture.frame should select a portion of the texture to pass to the shader. However, when I use the shader from the linked example, I get the whole texture being rendered despite whatever frame I specify for the texture, is this because the glsl shader is ignoring the frame and just taking the whole base texture?

### Environment

- **`pixi.js` version**: ^6.4.2
- **Browser & Version**: Chrome 103
- **OS & Version**: Ubuntu 20.04

**Comment by ivanpopelyshev** [comment]
you have to pass x,y,width,height of texture region to uniforms. Sorry, I have no time to explain it further, please ask in our discord :)

**Comment by BeebBenjamin** [comment]
Thanks, I guess my issue is I don't know enough glsl to fix this.  Closing as won't fix.
