### ISSUE TITLE
Can't get @pixi/node to install 

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixijs#8537]
Downloaded https://github.com/bigtimebuddy/pixi-node-example and run `npm install` gives an error:

npm ERR! code 1
npm ERR! path /Users/jensmalmborg/Downloads/pixi-node-example-main-2/node_modules/gl
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install warn install No prebuilt binaries found (target=16.15.1 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.15.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/usr/local/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/jensmalmborg/Downloads/pixi-node-example-main-2/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jensmalmborg/Downloads/pixi-node-example-main-2/node_modules/gl/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jensmalmborg/Downloads/pixi-node-example-main-2/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jensmalmborg/Library/Caches/node-gyp/16.15.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/jensmalmborg/Library/Caches/node-gyp/16.15.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/jensmalmborg/Downloads/pixi-node-example-main-2/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/jensmalmborg/Library/Caches/node-gyp/16.15.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/jensmalmborg/Downloads/pixi-node-example-main-2/node_modules/gl',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: python: command not found
npm ERR! gyp: Call to 'python commit_id.py check ..' returned exit status 127 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/jensmalmborg/Downloads/pixi-node-example-main-2/node_modules/node-gyp/lib/configure.js:284:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/jensmalmborg/Downloads/pixi-node-example-main-2/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/jensmalmborg/Downloads/pixi-node-example-main-2/node_modules/gl
npm ERR! gyp ERR! node -v v16.15.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jensmalmborg/.npm/_logs/2022-07-27T13_56_53_750Z-debug-0.log

**Comment by bigtimebuddy** [comment]
[node-canvas](https://github.com/Automattic/node-canvas) requires some things when it's trying to build. Try installing these dependencies:

```
brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman
```

**Comment by bigtimebuddy** [comment]
I wonder if this is Python related. [Dependency documentation](https://www.npmjs.com/package/gl/v/4.5.3-win64.0#system-dependencies) for the `gl` package says it requires Python 2.7. You could try to install 2.7 and I think you can pass `PYTHON` environment variable:

```
PYTHON=/path/to/python2 npm install
```

**Comment by jnsmalm** [comment]
Thanks, I'll try that
