### ISSUE TITLE
Missing example how to use the new extensions API

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixijs#8538]
I tried to write a some extension, but couldn't figure out how it works. Could you provide a simple example how to use it?

**Comment by bigtimebuddy** [comment]
I threw this together very quickly: https://github.com/pixijs/pixijs/wiki/Create-PixiJS-Extensions

**Comment by bigtimebuddy** [comment]
Closing this, will continue to add the the extensions wiki page as needed.
