### ISSUE TITLE
v6.5.1 interaction events has not properties '1'

### ISSUE THREAD

**Issue by appleguardu** [pixijs/pixijs#8542]
### Current Behavior

![image](https://user-images.githubusercontent.com/41320113/181684693-e79399b9-74ba-463b-a828-7976638a47b0.png)

### Environment

- **`pixi.js` version**: _e.g. v6.5.1_
- **Browser & Version**: _e.g. Chrome 99_
- **OS & Version**: _e.g. mac os_
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment]
This is an insufficient issue. Please provide a minimal example that reproduces. Thanks.

**Comment by Zyie** [comment]
Closing this as no example has been provided. Feel free to open back up if anyone has more info on the issue
