### ISSUE TITLE
Graphics.beginTextureFill repeats texture on desktop but not on mobile

### ISSUE THREAD

**Issue by davidye** [pixijs/pixijs#8543]
### Expected Behavior

When rendering a texture that is smaller the the shape of PIXI.Graphics, mobile and desktop should render the texture consistently.

### Current Behavior

On desktop the texture is repeated:

<img width="342" alt="Screen Shot 2022-07-29 at 1 43 05 PM" src="https://user-images.githubusercontent.com/17462763/181840306-b641b5bd-5bd7-4c37-8a8f-d4c6d5f880a6.png">

On mobile the texture is not:

![IMG_2926](https://user-images.githubusercontent.com/17462763/181840423-82e440d7-5730-4dbe-9efe-270c4aa8a8c8.png)

### Steps to Reproduce

I tried this on Windows, Mac, iOS, and Android. Desktop consistently rendered as repeat but mobile did not.

See https://www.pixiplayground.com/#/edit/Te4e3aETnRB5LvSe0shGf

### Environment

- **`pixi.js` version**: 6.5.1
- **Running Example**: https://www.pixiplayground.com/#/edit/Te4e3aETnRB5LvSe0shGf

**Comment by bigtimebuddy** [comment]
Seems like a bug. Thanks for reporting.

**Comment by davidye** [comment]
Can also be triggered on desktop by setting device profile to iPhone in dev tools, but haven't dug through the PIXI code base enough to figure out why.

**Comment by ivanpopelyshev** [comment]
webgl1, non-pow2 texture.

**Comment by bigtimebuddy** [comment]
That's right, we force webgl1 in v6. So either prefer webgl2 or use a power of two texture size. Seems like it would be useful to generate a warning for this

**Comment by davidye** [comment]
OK - forcing webgl2 did fix this. There still appears a bug with mobile detection though since I see comments that iPhones should be defaulting to WebGL2 but definitely possible to work around this. Thanks!

**Comment by bigtimebuddy** [comment]
This will be resolved by #7974 in coming v7.
