### ISSUE TITLE
Missing DisplayObject properties types?

### ISSUE THREAD

**Issue by rachoac** [pixijs/pixijs#8545]
After upgrading from pixijs version 6.2.2 to the latest (6.5.1 at time of writing), i've noticed several typescript errors relating to the `interactive` and `name` attributes on DisplayObject:

https://pixijs.download/release/docs/PIXI.DisplayObject.html#interactive
https://pixijs.download/release/docs/PIXI.DisplayObject.html#name

The Graphics object extends DisplayObject, but now the type definitions seem to no longer encompass these attributes, leading to errors like this in my codebase:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/334520/181925166-47b412e7-f428-456e-996b-245dcfbae8df.png">

<img width="549" alt="image" src="https://user-images.githubusercontent.com/334520/181925567-05d37418-eb92-4af2-be9c-5fce5500b665.png">

(DyanmicTextContainer extends Graphics)

These attributes do seem to exist however when I inspect the object runtime. Is this a matter of outdated types? Or are these attributes now deprecated and are going away? If so, is there an upgrade path?

**Comment by bigtimebuddy** [comment]
Sounds like #8186 or #7816? This can also happen from an improper upgrade with npm.

**Comment by rachoac** [comment]
It total ways @bigtimebuddy ! thank you
