### ISSUE TITLE
Object prototype may only be an Object or null: undefined at setPrototypeOf 

### ISSUE THREAD

**Issue by talhaozdemir** [pixijs/pixijs#8555]
### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment]
Closing this because of insufficient information. If you have a bug, please provide as much context as possible in the fields above. This will help us understand the problem better. Thanks.
