### ISSUE TITLE
Object prototype may only be an Object or null: undefined (PIXI Compressed Textures)

### ISSUE THREAD

**Issue by talhaozdemir** [pixijs/pixijs#8556]
### Current Behavior
I got error in the title when I upgraded pixi.js from 6.3.0 to 6.5.1, you can check the screenshots about the error in the attachments.

### Environment
Webpack 4.43.0

- **`pixi.js` version**: 6.5.1
![Untitled](https://user-images.githubusercontent.com/37840852/183245567-828b77ee-6528-40a9-9ca6-225887194034.jpg)
![Untitled2](https://user-images.githubusercontent.com/37840852/183245570-febbebc1-977f-45ce-95e4-edd969f74193.jpg)

**Comment by talhaozdemir** [comment]
Sorry for the previous report. I submitted it by mistake.

**Comment by bigtimebuddy** [comment]
Please checkout this [wiki post](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS) about upgrading and see if that helps first.

**Comment by talhaozdemir** [comment]
Yes I saw this before and applied but didn't work for me. 
I have tried with "webpack": "^5.73.0" right now. It is working.

**Comment by bigtimebuddy** [comment]
Closing this as it seems resolved with webpack@5

**Comment by talhaozdemir** [comment]
By the way,  running 'npm update' command has resolved the issue for webpack v4
