### ISSUE TITLE
Assets loader fails to load non-XML bitmap fonts from bundle

### ISSUE THREAD

**Issue by qwertywelch** [pixijs/pixijs#8557]
In the new Assets loader, documentation and the code's list of supported bitmap font types are listed as `['.xml', '.fnt']`. In the `loadBitmapFont` code, it appears to support both formats in `testParse` and `parse`, but `load` is only passing the data loaded into the XML parser, producing undefined results for non-XML .fnt bitmap fonts.

https://github.com/pixijs/pixijs/blob/fd9c9305b5722e09d8e9b0927dd2b093668ced60/packages/assets/src/loader/parsers/loadBitmapFont.ts#L64-L73

**Steps to reproduce**
Use Assets.addBundle, then Assets.loadBundle referencing a bundle that includes a non-XML .fnt bitmap font.
It errors, trying to reference bitmap font properties on an undefined object returned from the asset loader.

**Environment**
pixi.js v6.5.1

**Comment by bigtimebuddy** [comment]
I think this is a simple oversight. Thanks for reporting it.

**Comment by Zyie** [comment]
@bigtimebuddy 

I'm not super familiar with fnt files. I've only seen what is in our test suite

Can they be anything other than xml? If so i guess the fix is to check all 3 supported parsers?

```
if (TextFormat.test(data))
{
    data = TextFormat.parse(text);
}
else if (XMLFormat.test(data))
{
    data = XMLFormat.parse(new window.DOMParser().parseFromString(text, 'text/xml'));
}
else
{
    data = XMLStringFormat.parse(text);
}

return await _loadBitmap(url, data, loader);
```

**Comment by bigtimebuddy** [comment]
Yes, fnt file can be either text or xml.
