### ISSUE TITLE
Migration Loader to Assets ( feedbacks & bug )

### ISSUE THREAD

**Issue by Makio64** [pixijs/pixijs#8566]
Hello,

I saw the warning about Loader being deprecated in favor of Assets so I switched.

Assets is really nice but I got confuse by fews points : 

- Assets is not part of 'pixi.js' and I have to install extra repo '@pixi/assets' + '@pixi/basis' ( I'm wondering if I should used from 'pixi.js' at all actually.. )
- Assets.add / load works a bit differently from Loader.add / load and it tooks me fews minuts to figure it out
- There is a bug out of the box : if I load '/bunny.png' from 'https://mysite/page1/' it try to load 'https://mysite/page1/bunny.png' when I expected 'https://mysite/bunny.png', It was the previous behavior with Loader. So we have to manually do something like : `Assets.resolver.basePath = window.location.origin+'/'`

Maybe a Migration guide would be nice ?

For the rest, I'm very happy with this new Assets API, very clean, congrats! 

### Environment

- **`pixi.js` version**: 6.5.1

**Comment by bigtimebuddy** [comment]
I think the root-relative pathing issue is a bug. @Zyie what do you think?

**Comment by Zyie** [comment]
> I think the root-relative pathing issue is a bug. @Zyie what do you think?

Yeah i don't think root relative pathing was ever accounted for
