### ISSUE TITLE
Is there a way to use VideoFrame (from the WebCodec API) directly in Pixijs?

### ISSUE THREAD

**Issue by kalradivyanshu** [pixijs/pixijs#8591]
Hey,

Is there a way to use a [VideoFrame](https://developer.mozilla.org/en-US/docs/Web/API/VideoFrame) directly in pixiJS? VideoFrame is part of the new WebCodec API (which is currently only supported in Chromium 94 and above). In supported browser, VideoFrame can be directly painted to HTML canvas, as [`ctx.drawImage`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) supports taking VideoFrame as an input.

So I was wondering whether I can convert it into a Texture/Sprite to use in pixijs. The complete pipeline would be:

[`MediaStream`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream) ->[ `MediaStreamTrackProcessor`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrackProcessor/MediaStreamTrackProcessor) -> [`ReadableStream<VideoFrame>`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) -> ??? -> Pixi

The usecase is taking a Video from MediaStream(live video, or output of a [VideoDecoder](https://developer.mozilla.org/en-US/docs/Web/API/VideoDecoder)), and then using it in a Pixi App.

What would be the most performant way of doing this? I couldnt find anything in the docs, or github issues. Is it even possible?

Thanks.

### Environment

- **`pixi.js` version**: 6.5.1
- **Browser & Version**:  Chrome Version 105.0.5195.28 (Official Build) beta (64-bit)
- **OS & Version**: Windows 11

**Comment by bigtimebuddy** [comment]
@kalradivyanshu could you provide some more context about how you resolved this?

**Comment by kalradivyanshu** [comment]
In the [Insertable Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Insertable_Streams_for_MediaStreamTrack_API) there is a [MediaStreamTrackGenerator](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrackGenerator), that takes in VideoFrames and the object itself can be used as a [MediaStreamTrack](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack), converted that to MediaStream, put that in a DOM element, and used the DOM in pixijs.

So the pipe becomes:

[MediaStream](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream) ->[ MediaStreamTrackProcessor](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrackProcessor/MediaStreamTrackProcessor) -> [ReadableStream<VideoFrame>](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) -> [MediaStreamTrackGenerator](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrackGenerator) -> [MediaStream](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream) -> VideoDOM -> Pixijs

It is working, there might be a better way, but for now, this is the solution we had, if you have a better solution, would love to know.

Thanks.
