### ISSUE TITLE
@pixi/assets not support SVG

### ISSUE THREAD

**Issue by devinterx** [pixijs/pixijs#8592]
New @pixi/assets not support SVG loader

```js
Assets.add('logo', './assets/logo/logo.svg');
const logo = await Assets.load('logo');
const _logoSprite = new Sprite(logo);
```

> [Assets] `./assets/logo/logo.svg` could not be loaded as we don't know how to parse it, ensure the correct parser has being added

- **`pixi.js` version**: 6.5.1
- **Browser & Version**: Chrome/104.0.5112.81 Electron/20.0.2

**Comment by bigtimebuddy** [comment]
We just added this functionality. It will be in the next release 6.5.2, hopefully this week. Thanks for reporting.

**Comment by MattTreichelYeah** [comment]
PIXI.Assets docs don't mention SVG support: https://pixijs.download/dev/docs/PIXI.Assets.html

**Comment by MattTreichelYeah** [comment]
I notice that other parsers add themselves to `extensions` https://github.com/pixijs/pixijs/blob/4177cf7306fa8b072349c891fa1742e82a7288f6/packages/compressed-textures/src/loaders/loadKTX.ts#L72 but `loadSVG` is missing that line https://github.com/pixijs/pixijs/blob/2194fe5c5d28130837ca2e3572b81fc4737732ea/packages/assets/src/loader/parsers/textures/loadSVG.ts

I added `extensions.add(loadSVG);` and my project appeared to load correctly.

**Comment by SuperSodaSea** [comment]
@MattTreichelYeah Seems that this is a mistake. Would you like to make a PR to add `extensions.add(loadSVG);` at the end of `loadSVG.ts`?

**Comment by MattTreichelYeah** [comment]
> @MattTreichelYeah Seems that this is a mistake. Would you like to make a PR to add `extensions.add(loadSVG);` at the end of `loadSVG.ts`?

Yeah, I just decided to open one 👍
