### ISSUE TITLE
Broken edges when adding twists / turns in SimpleRope 

### ISSUE THREAD

**Issue by aphares** [pixijs/pixijs#8593]
I'm not sure if this is a bug or intended behavior, but would like any insight if this issue is avoidable:

### Expected Behavior
To have a smooth line without a breaks / jagged edges along the rope

### Current Behavior
When I'm using SimpleRope and setting each point with pawn movement, any points that cause the rope to twist / turn cause breaks along the rope:

![image](https://user-images.githubusercontent.com/33185379/184722318-bf27feab-ed98-452f-a0c3-05d34b46b2b9.png)
This screenshot uses the same png as in the SimpleRope example here:
https://pixijs.io/examples/#/demos-advanced/mouse-trail.js

### Steps to Reproduce
Dynamically set points x,y for SimpleRope on each frame

### Environment
- **`pixi.js` version**: 5.3.0
- **Browser & Version**: Chrome Version 100.0.4896.127 (Windows 10)

**Comment by rnike** [comment]
Same here, the rope texture seems to be twisted on a certain angle

![Screenshot 2024-05-08 at 5 17 56 PM](https://github.com/pixijs/pixijs/assets/48589760/265f0c84-c37c-448d-80ba-0889ea3687d2)

 
<img width="1079" alt="Screenshot 2024-05-08 at 5 20 36 PM" src="https://github.com/pixijs/pixijs/assets/48589760/4f62bc05-d1ac-41db-8ce1-a3e99946d941">

**Comment by GoodBoyDigital** [comment]
hey there! this is not really a bug. I can see how it might feel like one in your case though! 
If you add many more points - this would start to look closer to the expected result! hope that helps
