### ISSUE TITLE
Interactive sprite - Can't tell if left or middle click is clicked

### ISSUE THREAD

**Issue by 8o8inCodes** [pixijs/pixijs#8603]
Whenever I set the sprite to be interactive, and apply "click" event listener, there is no way to tell which mouse button is triggering the event. The `event.button` returns -1, Even the original event has "which" field that always says "0". Doesn't matter which button I press.

However if I do pure javascript events listener, it works as it should, with the "which" field.

### Expected Behavior
When clicking on the sprite, the event should have a field of which button was pressed correctly.

### Current Behavior
It always shows the same value of which mouse button is clicked regardless of which one is clicked.

### Steps to Reproduce
Here's a playground that demonstrates the issue, you can see the console log outputs of the events.
Try clicking on the bunny with the left and middle mouse buttons
https://www.pixiplayground.com/#/edit/pMfNwIP0-RRJkJ3hPuNb0

### Environment

- **`pixi.js` version**: 6.5.1
- **Browser & Version**: 104.0.5112.82 (Official Build) (64-bit)
- **OS & Version**: Windows 10
- **Running Example**: [_url_](https://www.pixiplayground.com/#/edit/pMfNwIP0-RRJkJ3hPuNb0)

**Comment by bigtimebuddy** [comment]
For performance reasons, the InteractionEvent objects are recycled. If you get the `e.data.button` in the callback, it returns 0 or 1, but if you are expanding the InteractionEvent in the console it will show -1. Updated [your playground](https://www.pixiplayground.com/#/edit/pMfNwIP0-RRJkJ3hPuNb0).

**Comment by 8o8inCodes** [comment]
Ah thank you very much! @bigtimebuddy 
Sorry for the false alarm then!
