### ISSUE TITLE
'ExtensionType' is not exported from '@pixi/core' (imported as 'ExtensionType')

### ISSUE THREAD

**Issue by dimitrisx** [pixijs/pixijs#8606]
After updating to 6.5.1 I get the following error message when building my project:

```
./node_modules/@pixi/app/dist/esm/app.mjs
Attempted import error: 'ExtensionType' is not exported from '@pixi/core' (imported as 'ExtensionType').
```
Note that I'm importing PIXI stuff using a custom `pixi.ts` file which has been created using the [PIXI Customize Tool](https://pixijs.io/customize/)

The contents of this file are the following:

```js
export * from "@pixi/constants";
export * from "@pixi/math";
import "@pixi/math-extras";
export * from "@pixi/runner";
export * from "@pixi/settings";
export * from "@pixi/ticker";
import * as utils from "@pixi/utils";
export { utils };
export * from "@pixi/display";
export * from "@pixi/core";
export * from "@pixi/extract";
export * from "@pixi/particle-container";
export * from "@pixi/sprite";
export * from "@pixi/app";
export * from "@pixi/graphics";
import "@pixi/graphics-extras";
export * from "@pixi/text";
export * from "@pixi/interaction";

// Renderer plugins
import { Renderer } from "@pixi/core";
import { BatchRenderer } from "@pixi/core";
Renderer.registerPlugin("batch", BatchRenderer);
import { Extract } from "@pixi/extract";
Renderer.registerPlugin("extract", Extract);
import { InteractionManager } from "@pixi/interaction";
Renderer.registerPlugin("interaction", InteractionManager);
import { ParticleRenderer } from "@pixi/particle-container";
Renderer.registerPlugin("particle", ParticleRenderer);

// Application plugins
import { Application } from "@pixi/app";
import { TickerPlugin } from "@pixi/ticker";
Application.registerPlugin(TickerPlugin);

```

I have already tried to install @pixi/extensions (`yarn add @pixi/extensions`) and then export it from my custom pixi.ts file but it makes no difference.

Any help would be greatly appreciated.

Thanks

**Comment by bigtimebuddy** [comment]
Here's an example running the latest 6.5.1 that works:
https://github.com/bigtimebuddy/pixi-custom-example

I imagine this issue is because of [upgrading](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS). Please read the wiki post and try again.

**Comment by dimitrisx** [comment]
Thanks for the reply @bigtimebuddy 

I've tried removing all pixi.js modules using:

`yarn remove @pixi/app @pixi/constants @pixi/core @pixi/display @pixi/extract @pixi/graphics @pixi/graphics-extras @pixi/interaction @pixi/math @pixi/math-extras @pixi/particle-container @pixi/runner @pixi/settings @pixi/sprite @pixi/text @pixi/ticker @pixi/utils pixi-viewport`

(At this point, package.json contains no pixi references)

And then re-adding them:

`yarn add @pixi/app @pixi/constants @pixi/core @pixi/display @pixi/extract @pixi/graphics @pixi/graphics-extras @pixi/interaction @pixi/math @pixi/math-extras @pixi/particle-container @pixi/runner @pixi/settings @pixi/sprite @pixi/text @pixi/ticker @pixi/utils pixi-viewport`

But I still get the same error.

I also tried the following (without success):
- Removing the `node_modules` directory (after `yarn remove ...` and before `yarn add ...`)
- Adding the @pixi/extensions module

**Comment by bigtimebuddy** [comment]
Can you make a repository that recreates your issue please?

**Comment by dimitrisx** [comment]
I switched from installing individual packages (as shown above) to `yarn add pixi.js` and the problem is fixed.
