### ISSUE TITLE
 Error: semantic error TS2305: Module '"pixi.js"' has no exported  member 'Container'.

### ISSUE THREAD

**Issue by JusticHentai** [pixijs/pixijs#8612]
### Expected Behavior
no error
### Current Behavior
Error: semantic error TS2305: Module '"pixi.js"' has no exported  member 'Container'.
### Steps to Reproduce
`git clone git@github.com:JusticHentai/pixijs-utils.git`

`pnpm i`

`pnpm build`

### Environment

- **`pixi.js` version**: 6.5.2
- **Browser & Version**: Chrome
- **OS & Version**: window 10
- **Running Example**: https://github.com/JusticHentai/pixijs-utils

**Comment by bigtimebuddy** [comment]
I was able to reproduce this error with `pnpm`, but curiously though using `npm` did not give me any problems. If you run `pnpm tsc -noEmit` you can see there are no type errors reported. If I had to guess, I think this may be an issue with `rollup-plugin-typescript2` and `pnpm`'s unique symlinking. You may try upgrading to `@rollup/plugin-typescript` or something else for compliation.

I do not believe this is an issue with the pixi.js package.

**Comment by JusticHentai** [comment]
> I was able to reproduce this error with `pnpm`, but curiously though using `npm` did not give me any problems. If you run `pnpm tsc -noEmit` you can see there are no type errors reported. If I had to guess, I think this may be an issue with `rollup-plugin-typescript2` and `pnpm`'s unique symlinking. You may try upgrading to `@rollup/plugin-typescript` or something else for compliation.
> 
> I do not believe this is an issue with the pixi.js package.

I think -noEmit just ignore the ts error but not fix it;
In `pixi.js: 5.3.12` all the types in `pixi.js.d.ts` , so it doesn't report any error;
But `pixi.js: 6.5.2` use `<reference>` or `import` in 'd.ts', it will have some problem in `pnpm`, user should add the dependencies like `@pixi/app` to aviod type error or use the types in pixi.js;
I recommend maintaining a full `d.ts` in the most external library

**Comment by bigtimebuddy** [comment]
Thanks for clarifying. The use of `<reference>` and `imports` are how we resolve cross-package mixins. If someone can come up with better solution to auto-generate a single typing file for the bundle packages and work with mixins, we would definitely want that.
