### ISSUE TITLE
recall PIXI.Assets.load(...) get warning in console

### ISSUE THREAD

**Issue by littleboarx** [pixijs/pixijs#8613]
### Expected Behavior
as the recommended usage shown in the doc, recalling PIXI.Assets.load(...)  should be no warning here
### Current Behavior  &Steps to Reproduce & Environment
warning BaseTexture added to the cache with an id [examples/assets/bunny.png] that already had an entry
![image](https://user-images.githubusercontent.com/59130959/186643615-8f6bc7ce-c988-427f-8413-af0c3e838777.png)

**Comment by driuqzy** [comment]
Same issue here. Per the docs: https://pixijs.download/dev/docs/PIXI.Assets.html "**Do not be afraid to load things multiple times** - under the hood, it will NEVER load anything more than once." 

And it works as desired. We just **need a way to suppress this warning** to now blow up the console logs.

**Comment by bigtimebuddy** [comment]
Some of this was added for debugging as we were building. We should either have a verbose logging flag on Assets, or remove these. This at least shouldn't be a warning, since it's the intended behavior to load things more than once.
