### ISSUE TITLE
Typings for displayobject/interaction seems broken

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixijs#8621]
Something has happened with typings for DisplayObject/Interaction.

I have this in typescript, and it doesn't compile:

```
let object = new Container()
object.interactive = true
```

Getting error: Property 'interactive' does not exist on type 'Container<DisplayObject>'

PixiJS 6.5.1

**Comment by bigtimebuddy** [comment]
Cannot reproduce this. Here's the example:
https://github.com/bigtimebuddy/pixi-typescript-webpack-example

```
npm install
npm run types
```

Please make sure you [upgrade correctly](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS).

**Comment by jnsmalm** [comment]
Sorry about that, I was missing "esModuleInterop": true in the tsconfig.
