### ISSUE TITLE
Starting with 6.5.x, graphics behave differently than before

### ISSUE THREAD

**Issue by adam-savard** [pixijs/pixijs#8623]
I've attached a JS Fiddle to show what can go wrong in existing codebases:

https://jsfiddle.net/awn97mop/9/

The gist of this is, starting with 6.5.x, `PIXI.Graphics` calculate height/width differently than they did before, which I believe is due to [this pull request](https://github.com/pixijs/pixijs/pull/8343) (though I could be wrong about the cause, it feels like a bounds calculation thing!). When graphics are passed a fill of alpha 0 and no line style, they assume the graphics object has a height/width of 0.

I'm not suggesting that this be changed, as _technically_ this does make sense to me. But, it did make upgrading to the newest version of PIXI a little frustrating today as I had to figure out what had changed between versions enough to cause this. 

I'm putting this out there so that perhaps this can be spread through the official channels, or so that anyone else that decides to upgrade to the latest version and experiences a similar "what happened" moment has a point of reference.

The solution for us was to not use a fill with alpha 0 when there was also no linestyle. Not a complicated solution, and probably better in the longrun.

**Comment by dev7355608** [comment]
The bounds determine the width and height of the object including the scale of the object. The bounds should be minimal and contain the entire graphics always. Neither was true before 6.5.x. Now it's based on the actual geometry that is generated. But no geometry is and was generated for 0 alpha parts of a graphic. So any full transparent parts are not included in the bounds. Maybe they should, but then we would need to compute geometry for those parts that don't need to be rendered.

**Comment by adam-savard** [comment]
@dev7355608 I don't really have a horse in this race since library-side, we just do whatever we need to do. Is this changed behavior documented anywhere beyond the PR and this ticket? Just thinking about anyone else that does an upgrade that might run into similar issues.

**Comment by bigtimebuddy** [comment]
There probably should be a note about this new behavior in the API docs (probably in the constructor doc). Maybe something like this:

> Since 6.5.0, shapes or strokes drawn with full transparency (`alpha: 0`) are _not_ considered when calculating bounds for the Graphics. Transparent shapes/strokes are not rendered and therefore ignored when generate geometry.

Suggestions or PR welcome!
