### ISSUE TITLE
`resizeTo` should call `render`

### ISSUE THREAD

**Issue by plurry** [pixijs/pixijs#8629]
Right now, `resizeTo` makes the canvas flicker noticeably when there are several resize events in succession, like when the browser gradually hides the address bar in fullscreen.

To fix this, `ResizePlugin` should call `render` after it calls `renderer.resize`. That's what Pixi demos written without `resizeTo` do. Take a look at `DemoApplication.js` in the filter demo for example.

https://codesandbox.io/s/resizeto-flickering-kv1w2r
https://codesandbox.io/s/no-resize-flickering-85e1vo

**Comment by bigtimebuddy** [comment]
This is working as designed. 

The reason it is designed this way and we don't automatically re-render is that rendering is pretty expensive especially for large projects. If you have a Ticker running, a window resize will constantly spam extra frame renders hurting performance. A developer may want to avoid doubling up on frame renders or debounce rendering and decoupling the resizing and the rendering allows for it.

If you don't care about this optimization and you want to remove the frame flicker, add this line:

```js
app.renderer.on('resize', () => app.render())
```

**Comment by plurry** [comment]
It still should be smart enough to render after a resize, even if it doesn't resize (or render) more than once per frame, right? Just glancing at the code, I would have thought that's what `queueResize` was supposed to do.

As it stands now, `resizeTo` visibly glitches when it resizes, without a single note or explanation in the docs (at least that I could find).

**Comment by tgrajewski** [comment]
Actually I would recommend resizing canvas and rendering updated contents being done always inside requestAnimationFrame to obtain the best performance and void flickering. It should be done inside Pixi too, to save game developers a lot of time fixing this again and again.
