### ISSUE TITLE
Asset loading fails when URL contains hashtag

### ISSUE THREAD

**Issue by omenansiemen** [pixijs/pixijs#8633]
### Expected Behavior
http://localhost:8080/images/asset.json

### Current Behavior
http://localhost:8080/#test/images/asset.json

### Steps to Reproduce
Load the application with a hashtag (http://localhost:8080/#test)

### Environment

- **`pixi.js` version**: _6.5.2_
- **Browser & Version**: _Edge 105.0.1343.27_
- **OS & Version**: _Windows 10_

**Comment by Zyie** [comment]
This should be fixed with this PR #8614

**Comment by Zyie** [comment]
v6.5.3 has now been released with this fix
