### ISSUE TITLE
Graphics permanently changes the wrap mode of the texture to REPEAT

### ISSUE THREAD

**Issue by dev7355608** [pixijs/pixijs#8636]
Also the wrap mode isn't successfully changed if the texture was already bound and isn't dirty: https://pixiplayground.com/#/edit/qKbwGLPkoY2VNAZc8Gr-a

Here the wrap mode is changed:
https://github.com/pixijs/pixijs/blob/28e6b2841a65837a5e2873a3d5a9c27cabbe795a/packages/graphics/src/GraphicsGeometry.ts#L393

But the `wrapMode` setter doesn't increase `dirtyId`, so the changes to not take effect unless the texture is already dirty:
https://github.com/pixijs/pixijs/blob/9b724f289118ebbf9b4500fa3faab1e7aaaabd02/packages/core/src/textures/BaseTexture.ts#L364-L371
https://github.com/pixijs/pixijs/blob/db824181dc3dfffa0951fb8579282ba8e654cb3b/packages/core/src/textures/TextureSystem.ts#L154-L162

---

1. Should the graphics change the wrap mode of a texture permanently or even at all?
2. Should the `wrapMode` setter increase `dirtyId`? Or is `TextureSystem.bind` missing the follow branch so that increasing `dirtyStyleId` does update style without increasing `dirtyId`:
```ts
            if (glTexture.dirtyId !== texture.dirtyId)
            {
                if (this.currentLocation !== location)
                {
                    this.currentLocation = location;
                    gl.activeTexture(gl.TEXTURE0 + location);
                }
                this.updateTexture(texture);
            }
            // update the texture style if necessary
            else if (glTexture.dirtyStyleId !== texture.dirtyStyleId)
            {
                this.updateTextureStyle(texture);
            }
```

**Comment by bigtimebuddy** [comment]
Merged in fix
