### ISSUE TITLE
Type Error when building against Assets

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixijs#8646]
Version: v7.0.0-alpha

The reference is included in Asset's index.d.ts in the but I'm not sure how it is included. It this api-extractor magic, @Zyie? Do we need to add `@types/css-font-loading-module` to the dependencies of Assets?

```
node_modules/@pixi/assets/index.d.ts:1:23 - error TS2688: Cannot find type definition file for 'css-font-loading-module'.

1 /// <reference types="css-font-loading-module" />
                        ~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error in node_modules/@pixi/assets/index.d.ts:1
```

**Comment by Zyie** [comment]
It seems that `api-extractor` is doing some magic and adding it in

The `@types/css-font-loading-module` was added to the root `package.json` instead of `Assets` `package.json`
