### ISSUE TITLE
Loader does not load avif image  with the .avif extension

### ISSUE THREAD

**Issue by shaoahs** [pixijs/pixijs#8647]
### Expected Behavior

display avif image

### Current Behavior

skip avif image

### Possible Solution
      LoaderResource._loadTypeMap = {
          // images
          avif: LoaderResource.LOAD_TYPE.IMAGE,
          gif: LoaderResource.LOAD_TYPE.IMAGE,
          png: LoaderResource.LOAD_TYPE.IMAGE,

### Steps to Reproduce

```
loader.add('test.avif');
```
### Environment

- **`pixi.js` version**: _e.g. 6.5.3_
- **Browser & Version**: _e.g. last
- **OS & Version**: _e.g. any
- **Running Example**: null

**Comment by SuperSodaSea** [comment]
Will fix in #8736.
By the way, I recommand you to use `Assets` instead of `Loader`, since the `Loader` will be removed in PixiJS v7.

**Comment by bigtimebuddy** [comment]
Merged!
