### ISSUE TITLE
node CI link broken

### ISSUE THREAD

**Issue by aradhyatiwari** [pixijs/pixijs#8657]
### Expected Behavior
Should go to https://github.com/pixijs/pixijs/actions?query=workflow%3A%22Node.js+CI%22
### Current Behavior
It goes to https://github.com/pixi.js/pixi.js/actions?query=workflow%3A%22Node.js+CI%22
### Possible Solution
change the address

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment]
Thanks for reporting this!
