### ISSUE TITLE
Cannot add EventSystem Extension

### ISSUE THREAD

**Issue by mcdenhoed** [pixijs/pixijs#8668]
Hello!

I'm trying to follow the [v7 migration guide](https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide) on the wiki, but I'm hitting a snag on the events package.

The wiki says to run the following to opt into the new events system:

```typescript
import { InteractionManager, extensions } from 'pixi.js';
import { EventSystem } from '@pixi/events';

extensions.remove(InteractionManager);
extensions.add(EventSystem);
```

However, when I insert that code into my app, I get the following runtime error:

```
index.ts:73 Uncaught Error: Extension class must have an extension object
    at normalizeExtension (index.ts:73:1)
```

I've confirmed that the `@pixi/events` is installed and `tsc` can see it. When I inspect the `EventSystem` that's getting passed into `extensions.add` at runtime, it looks like it's a function, the [constructor for `EventSystem`](https://github.com/pixijs/pixijs/blob/dev/packages/events/src/EventSystem.ts#L98) specifically. I see that the `EventSystem` class itself has the `extension` object that `normalizeExtension` is complaining about. Am I not invoking `extensions.add` correctly?

### Environment

- **`pixi.js` version**: 6.5.4

**Comment by bigtimebuddy** [comment]
Good catch, I think this is an oversight in v6. 

Could you try this:

```js
import { InteractionManager, extensions, ExtensionType } from 'pixi.js';
import { EventSystem } from '@pixi/events';

EventSystem.extension = {
    name: 'events',
    type: [
        ExtensionType.RendererSystem,
        ExtensionType.CanvasRendererSystem
    ],
};
extensions.remove(InteractionManager);
extensions.add(EventSystem);
```

**Comment by bigtimebuddy** [comment]
Thanks for reporting this. Here's the correct way in v6.5.4 to install EventSystem:
https://codesandbox.io/s/laughing-haze-ke6u3q
