### ISSUE TITLE
How to use hitTest with v7 events

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixijs#8675]
Before v7, we could do `renderer.plugins.interaction.hitTest(point)`, do we have something similar in v7?

**Comment by domis86** [comment]
Probably EventSystem:

https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide#-replaces-interactionmanager-with-eventsystem

https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide#%EF%B8%8F-suggestions-for-upgrading

**Comment by jnsmalm** [comment]
I understand that part :) But I need the function `hitTest` which previously returned the displayobject at that x, y.

**Comment by bigtimebuddy** [comment]
Try this @jnsmalm 
```js
renderer.events.rootBoundary.hitTest(x, y)
```

**Comment by jnsmalm** [comment]
Thanks, I did try that but not sure it's working correctly. The code below only works if I continuously move the mouse in the window, otherwise I get an error.

```
let app = new PIXI.Application({
  backgroundColor: 0xdddddd, resizeTo: window, antialias: true
})
document.body.appendChild(app.view)

let sprite = app.stage.addChild(new PIXI.Sprite(PIXI.Texture.WHITE))
sprite.scale.set(10)
sprite.interactive = true

setTimeout(() => {
  console.log(app.renderer.events.rootBoundary.hitTest(0, 0))
}, 1000)
```

**Comment by jnsmalm** [comment]
Actually it seems I only need to move the mouse once before the setTimeout runs.

**Comment by bigtimebuddy** [comment]
@ShukantPal could you clarify around the behavior of hitTest?

**Comment by bigtimebuddy** [comment]
@jnsmalm this worked for me:
https://codesandbox.io/s/pixijs-examples-events-hit-test-roxywk?file=/src/index.ts

```ts
const boundary = app.renderer.events.rootBoundary;
boundary.rootTarget = app.stage;
```
or 
```ts
const boundary = new EventBoundary(app.stage);
const result = boundary.hitTest(0, 0);
```

The `rootBoundary` target is not assigned until the first mouse event happens. Maybe there's a faster way to set the rootTarget reference?

**Comment by jnsmalm** [comment]
Thanks @bigtimebuddy, that worked.

**Comment by ShukantPal** [comment]
Yeah, the `rootBoundary.rootTarget` is set by the `EventSystem` and is the lastObjectRendered:

https://github.com/pixijs/pixijs/blob/e5cc328a2374fac1cb21915e8029d8a9bddb038c/packages/events/src/EventSystem.ts#L203

That's because you could render something other than `app.stage`. If you want to do a synthetic hit test, I would suggest having your own EventBoundary.

**Comment by bigtimebuddy** [comment]
I added this information to the migration guide.

**Comment by Snowblaze** [comment]
Hey @bigtimebuddy. Does your code sandbox example still work? I get module error.

```
Could not find module in path: '@pixi/settings/lib/node_modules/ismobilejs/esm/index.js' relative to '/node_modules/@pixi/settings/lib/utils/isMobile.js'
```

**Comment by bigtimebuddy** [comment]
@Snowblaze not sure what's going on with that error. The [file](https://unpkg.com/@pixi/settings@7.0.3/lib/node_modules/ismobilejs/esm/index.js) is definitely in the package.

But I fixed the example so it runs.
