### ISSUE TITLE
pixi/mesh-extras could not be built

### ISSUE THREAD

**Issue by fheryfebrians** [pixijs/pixijs#8682]
can anyone explain what happened?

### Environment

- **`pixi.js` version**: 6.5.4
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_
- 
![image](https://user-images.githubusercontent.com/40177882/193233195-52df13ff-f4b1-4c98-83e3-f8b3842fb1d0.png)

**Comment by bigtimebuddy** [comment]
Could you please provide more information? Preferable something that reproduces the issue.

**Comment by fheryfebrians** [comment]
![image](https://user-images.githubusercontent.com/40177882/193249118-0e9c4005-5c2b-4377-b4ed-2a6ad39e42af.png)
I just imported the pixi from skypack and it happened, last month there was no problem, the error came this week

> Could you please provide more information? Preferable something that reproduces the issue.

**Comment by bigtimebuddy** [comment]
There were no changes made to mesh-extras between 6.5.3 and 6.5.4, so this seems unlikely to be a problem with pixi.js. 

https://cdn.skypack.dev/@pixi/mesh-extras@v6.5.3 [okay]
https://cdn.skypack.dev/@pixi/mesh-extras@v6.5.4 [error]

I posted an error on skypack-cdn, hopefully someone can provide more specific information.

**Comment by bigtimebuddy** [comment]
I did a new release and this went away. Not entirely sure why.

https://cdn.skypack.dev/@pixi/mesh-extras@v6.5.5
https://cdn.skypack.dev/pixi.js

**Comment by fheryfebrians** [comment]
> https://cdn.skypack.dev/pixi.js

ok, it now works for version 6.5.5 but not for version 6.5.4
