### ISSUE TITLE
Pixi uses PVRTC when ASTC is supported (basis)

### ISSUE THREAD

**Issue by vforsh** [pixijs/pixijs#8688]
### Current Behavior
I created a bunch of basis textures with `-uastc` setting. When I run it on my iPhone 12 mini the image quality is poor. I have done some digging and found out that even though my device supports ASTC the pixi uses ETC1 and PVRTC textures. I believe it is an issue with supported formats detection in @pixi/basis.

![2022-10-01_11-59-30](https://user-images.githubusercontent.com/190223/193397432-aa58e44e-07cd-448e-837f-97ff4161d7ac.png)

### Expected Behavior
Pixi will choose the best supported format.

### Possible Solution
Make ASTC a priority when detecting supported formats.

- **`pixi.js` version**:  6.5.1
- **Browser & Version**: Safari WKWebView
- **OS & Version**: iOS 15.6

**Comment by vforsh** [comment]
@eXponenta Thanks for the PR but it doesn't fix the issue. Device still uses PVR/ETC with this fix applied.
![2022-10-01_16-55-28](https://user-images.githubusercontent.com/190223/193408417-863e8cd3-f86c-48f3-9541-82a15529f4ca.png)

**Comment by vforsh** [comment]
I suppose the root of the issue is that [INTERNAL_FORMATS enum](https://github.com/pixijs/pixijs/blob/dev/packages/compressed-textures/src/const.ts#L34) is missing [ASTC formats](https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_astc)

**Comment by eXponenta** [comment]
Yep, basis has invalid linkage to ATC instead of ASTC
https://github.com/pixijs/pixijs/pull/8691/commits/8471b03bf0163c03c6f1921b3879eb307b3d93f4
