### ISSUE TITLE
Changing the height or width of a view canvas can cause strange behavior with masked sprites

### ISSUE THREAD

**Issue by spacefluff432** [pixijs/pixijs#8697]
This only seems to affect some devices. It may be dependant on the graphics manufacturer, but I'm not sure. After having sent beta builds to several beta testers, builds which implemented code with this bug, only some of them reported issues.

### Expected Behavior
Both of the below code snippets should work in the exact same way with regards to masked sprites.
```js
const app = new PIXI.Application();
app.renderer.view.width = 320;
app.renderer.view.height = 240;
```
```js
const app = new PIXI.Application({ width: 320, height: 240 });
```

### Current Behavior
Setting the width or height of the view causes masked sprites to render wrongly.

### Possible Solution
I suspect the solution might involve refreshing the canvas context. In a previous engine prototype, I found that changing the canvas's width and height meant I needed to create a new rendering context. I don't know if PIXI has a method to re-generate it, so perhaps one could be added or an option could be specified in the app constructor to watch for changes in the canvas's width and height props.

### Steps to Reproduce
**This can be pasted into the "code" section of the basic sprite example:** https://pixijs.io/examples/#/sprite/basic.js

On devices with the issue, the masked sprite will render at the wrong position and with the wrong scale. For a control test, which works correctly for all devices I've tested, comment out the `sprite.mask = graphics` line.

```js
const app = new PIXI.Application();

app.renderer.view.width = 320;
app.renderer.view.height = 240;

const container = new PIXI.Container();
app.stage.addChild(container);

const a = 0.5; // anchor x
const b = 0.5; // anchor y
const x = 10; // crop x
const y = 10; // crop y
const w = 30; // crop w
const h = 30; // crop h

const sprite = PIXI.Sprite.from('examples/assets/bunny.png');
container.addChild(sprite);

const graphics = new PIXI.Graphics();
container.addChild(graphics);

app.ticker.add(delta => {
   container.angle += 0.1;
   container.position.set(50, 50);
   sprite.anchor.set(
      (x + w * a) / sprite.texture.width,
      (y + h * b) / sprite.texture.height
   );
   graphics.pivot.set(w * a, h * b);
   graphics.beginFill(0xff0000, 1).drawRect(0, 0, w, h).endFill();
   sprite.mask = graphics;
});

document.body.appendChild(app.renderer.view);
```

### Environment

- **`pixi.js` version**: 6.5.4
- **Browser & Version**: Electron 21.0.1 & Firefox 105.0.2
- **OS & Version**: Windows 10
- **Running Example**: See "steps to reproduce"

**Comment by bigtimebuddy** [comment]
Manually setting width and height of the canvas is not the best way to resize. There is a method that you should use instead:

`app.renderer.resize(width, height)`

**Comment by bigtimebuddy** [comment]
Correct! Width and height of the canvas are managed by Pixi. If you want to change the canvas size it's safe to use CSS.
