### ISSUE TITLE
Error importing `Assets`

### ISSUE THREAD

**Issue by FractalHQ** [pixijs/pixijs#8701]
- **`pixi.js` version**: `v6.5.5` & `v7.0.0-alpha.3`

I'm attempting to use the named import for `Assets` to take advantage of tree shaking in my `vite` app, but it gives me an error.

```ts
//  Module '"pixi.js"' has no exported member 'Assets'.
import { Application, Sprite, Filter, Assets } from 'pixi.js' 
```

![Screenshot 2022-10-07 at 1 57 10 PM](https://user-images.githubusercontent.com/55504972/194620331-1c51c7ab-d55b-4505-8222-ded2fcc00e45.png)

**Comment by bigtimebuddy** [comment]
Assets is only available in **pixi.js** for v7.  Here's an example of using it: https://codesandbox.io/s/pixijs-examples-container-forked-loz4tm?file=/src/index.ts

If you want Assets in v6, you need to add `@pixi/assets` to your project.

**Comment by FractalHQ** [comment]
Ah thanks, worked like a charm!
