### ISSUE TITLE
WebGL Buffer in WebWorker

### ISSUE THREAD

**Issue by jbwaring** [pixijs/pixijs#8702]
Dear Pixi.js, 
We would like to generate a buffer that contains a WebGL Render from Pixi.js in a WebWorker and pass it to the main thread. Is there a way to create a PIXI.Application() with a particular configuration to achieve that ?

- **`pixi.js` version**: 7 alpha3

**Comment by bigtimebuddy** [comment]
We are working on that right now #8698 actually! This will be in the next v7 release.

**Comment by jbwaring** [comment]
Thanks very much for the quick answer. My team and I are delighted and looking forward to the release of v7!
