### ISSUE TITLE
MSDF Bitmapfont broke after 6.5.4

### ISSUE THREAD

**Issue by miltoncandelero** [pixijs/pixijs#8703]
### Expected Behavior (6.5.3)
![image](https://user-images.githubusercontent.com/15253010/194714328-18b0941f-78b6-4cec-98d9-a16e53434782.png)

### Current Behavior (6.5.5)
![image](https://user-images.githubusercontent.com/15253010/194714228-1400995a-40a4-496a-a026-7ab11a24c8cd.png)

### Steps to Reproduce
Try rendering this font at 200 size
```ts
const aux = new BitmapText("Hello World!", { fontName: "TitlingGothicFBCompRegular", tint: 0xffffff, fontSize: 200 });
this.addChild(aux);
```
[msdf font.zip](https://github.com/pixijs/pixijs/files/9739575/msdf.font.zip)

### Environment

- **`pixi.js` version**: >6.5.5
- **Browser & Version**: Chrome
- **OS & Version**: Windows

**Comment by bigtimebuddy** [comment]
#8699 is the fix for this. Can you verify?

**Comment by bigtimebuddy** [comment]
FIxed with the above PR https://codesandbox.io/s/elated-dijkstra-z9md8j
