### ISSUE TITLE
Webcam video randomly stop working on Firefox

### ISSUE THREAD

**Issue by salamanders** [pixijs/pixijs#8707]
When I passed in an video source (from the phone's webcam), it only displays a still on the object.  Do I need to enable something to get the video-ness to show up?  Is having a streaming video even an option?

My. stack:
1. Webcam 
2. navigator.mediaDevices.getUserMedia
3. HTMLVideoElement
4. `.play()`
5. PIXI.Texture
6. PIXI.Sprite
7. app.stage.addChild

**Comment by SuperSodaSea** [comment]
Reproduce: https://pixiplayground.com/#/edit/hs370jqjbQ8pw_dO196Tr

This code always works fine on my Chrome (105.0.5195.102), but it *randomly* broken on my Firefox (105.0.3): The canvas (on the top) freeze while the video from camera (on the bottom) is actually playing. I reload it many times, in most of the time it is broken, but sometimes it can work. No error in console.

@bigtimebuddy Would you like to try this code?

**Comment by bigtimebuddy** [comment]
I added a manual update to the texture: 
https://pixiplayground.com/#/edit/C8EDbid-AksmDqbUb5aMI

This is probably a good place to debug to understand why Firefox isn't auto-updating.

https://github.com/pixijs/pixijs/blob/8055ae1c16d4c0f8dabda86cafd8e68c356450e8/packages/core/src/textures/resources/VideoResource.ts#L324-L341

**Comment by bigtimebuddy** [comment]
The problem seems to be that `currentTime` is 0 immediately after starting play on Firefox, so `this._isSourcePlaying()` is returning false. Waiting for the first `timeupdate` event seems to resolve the issue. Not sure what the correct fix, if any, for Pixi.

**Comment by domis86** [comment]
https://github.com/pixijs/pixijs/issues/8707#issuecomment-1277942847 - this version works for me (Firefox 105, Windows 10)

**Comment by bigtimebuddy** [comment]
I'm not sure what `source.currentTime > 0` accomplishes here. If you're checking if something is non-paused, not finished, and ready, that extra condition doesn't seem useful. There's little Git history except this commit d06388a2d90da3249a03aa4ba8ba39d4723ee9ce from 2017 where @GoodBoyDigital introduced it.

I'd be in favor of removing that condition and do some testing to verify.
