### ISSUE TITLE
Add "removeFromParent" to DisplayObject

### ISSUE THREAD

**Issue by astrocreep** [pixijs/pixijs#8716]
This is just an easy way to remove a DisplayObject from it's parent. There is already a pull request from @arnovanoordt here: https://github.com/pixijs/pixijs/pull/5021 But it was closed back then. So no need to make a new one. Code is straightforward and doesn't break any existing funtionality.
Maybe now is the right time?

**Comment by SuperSodaSea** [comment]
Not too late for v7 I think. Implemented in #8728.
