### ISSUE TITLE
New Assets Loader is not Working in Unity IOS Ad Testing App

### ISSUE THREAD

**Issue by talhaozdemir** [pixijs/pixijs#8738]
We are making playable ads with PixiJS, after I updated loader system to pixi's new asset manager, the application cannot pass loading state. So I put console's in the assets.mjs file and I get different results with IOS and Android.

### Steps to Reproduce

Step 1- This is how I load image in my loader function
![image](https://user-images.githubusercontent.com/37840852/196030401-9a5bb085-5a87-4a86-8549-34e1f23ed0d5.png)

Step 2- I put some console messages for debugging
![image](https://user-images.githubusercontent.com/37840852/196030466-964ba22e-32f3-4686-8cb9-b50a1032a728.png)
and in __generator function
![image](https://user-images.githubusercontent.com/37840852/196030500-34251851-9912-48cf-88f6-004387dd0a88.png)

Step 3- I got different results with IOS and Android
For IOS
![image](https://user-images.githubusercontent.com/37840852/196030555-c77f3caa-0cd4-4dda-a318-ca16f14040bf.png)
For Android
![image](https://user-images.githubusercontent.com/37840852/196030573-e80f4919-edeb-40a8-aee4-3833975ef716.png)
And this is the Windows Chrome console
![image](https://user-images.githubusercontent.com/37840852/196030609-8a6db4db-8b31-4888-a103-d26329629adc.png)

The problem appears from the sent function in __generator, what IOS doesn't like is the question

### Environment
PixiJS v6.5.6

**Comment by bigtimebuddy** [comment]
What is the error it throws? 

Also, that __generator function is usually from transpiling/bundling to support older JS. Can you provide details about how your building your project?

**Comment by talhaozdemir** [comment]
There is no error, 
![image](https://user-images.githubusercontent.com/37840852/196033446-a42cfe04-9899-450e-aa41-cfd6a9638af0.png)
Cannot pass await in IOS here.
The IOS version is 15.7

I use webpack to build the project. 
I use this testing tool from appstore:
https://apps.apple.com/app/ad-testing/id1463016906

when I try to load an asset, it enters this if block
![image](https://user-images.githubusercontent.com/37840852/196033640-24630c28-8954-45b9-9ea3-132d052b8d8d.png)

**Comment by bigtimebuddy** [comment]
Can you please provide more details about your webpack configuration? What plugins, etc you're using. This doesn't seem like a Pixi issue since all the code you cite isn't in Pixi.

**Comment by talhaozdemir** [comment]
I don't think that it is about webpack, because everything is working with old asset loading code, if I use Assets.load, problem occurs. 

Previously I load images like
![image](https://user-images.githubusercontent.com/37840852/196036855-9e355895-92f4-4848-a7c8-d172f5c7988e.png)

and now I load images like
![image](https://user-images.githubusercontent.com/37840852/196036869-181cc085-9bb7-4a0a-9988-598591683d2a.png)

If I continue using old loading code, everything is ok for both IOS and android.

If you want to look webpack files. I share below.
[webpack.zip](https://github.com/pixijs/pixijs/files/9794571/webpack.zip)

**Comment by SuperSodaSea** [comment]
Maybe you can try `console.log(t[1].toString())` to reveal the Error?

**Comment by talhaozdemir** [comment]
@SuperSodaSea 
![image](https://user-images.githubusercontent.com/37840852/196037767-d56fe458-34c4-422d-af01-3feb43c02c57.png)

**Comment by SuperSodaSea** [comment]
Sounds like code here:

https://github.com/pixijs/pixijs/blob/e30b88657c184183b3d9b81cc9c5552df24d55dc/packages/assets/src/loader/parsers/textures/loadTexture.ts#L91-L96

**Comment by talhaozdemir** [comment]
yes it is, but I don't understand why it can't load texture in unity testing app. It is working in localhost for both android and ios.

**Comment by bigtimebuddy** [comment]
I created a simple example loading base64 png with assets on 6.5.6:
https://codesandbox.io/embed/serene-satoshi-1kko9k?fontsize=14&hidenavigation=1&theme=dark

I'm personally not familiar with Unity IOS Ad Testing App environment, but will that simple example run? Maybe this development environment has restricted content security policy?

**Comment by talhaozdemir** [comment]
Interestingly, the issue is resolved after I comment the line 1107
![image](https://user-images.githubusercontent.com/37840852/196043247-47cc5be9-ad69-43cc-9066-3ac306616466.png)
![image](https://user-images.githubusercontent.com/37840852/196043257-e9f1b787-9b86-4d56-9dab-d00782209df8.png)

What do you think @bigtimebuddy

**Comment by bigtimebuddy** [comment]
Can you verify what `src` is in the previous line?

**Comment by talhaozdemir** [comment]
![image](https://user-images.githubusercontent.com/37840852/196043534-6a84800f-417c-41d1-ae0b-d48095d12653.png)

**Comment by bigtimebuddy** [comment]
Yea, in the unity app, what is that `src`

**Comment by SuperSodaSea** [comment]
Maybe you can try something like `console.log(src.toString())` on iOS.

**Comment by talhaozdemir** [comment]
Nothing prints on the screen but `base.resource.src` is undefined in chrome's console

**Comment by talhaozdemir** [comment]
![image](https://user-images.githubusercontent.com/37840852/196044910-0c616c5e-950f-4c29-888f-d828af08c3bb.png)
I print like that and both console's are null

**Comment by SuperSodaSea** [comment]
https://github.com/pixijs/pixijs/blob/e30b88657c184183b3d9b81cc9c5552df24d55dc/packages/assets/src/loader/parsers/textures/loadTexture.ts#L65-L70
https://github.com/pixijs/pixijs/blob/e30b88657c184183b3d9b81cc9c5552df24d55dc/packages/assets/src/loader/parsers/WorkerManager.ts#L23-L29
https://github.com/pixijs/pixijs/blob/e30b88657c184183b3d9b81cc9c5552df24d55dc/packages/assets/src/loader/parsers/WorkerManager.ts#L83-L89

I guess there is something wrong with `WorkerManager.loadImageBitmap(url)`, it may fail silently and return `null`. Can you confirm the code goes here, and what is the `error`?

**Comment by bigtimebuddy** [comment]
You could also set `loadTexture.config.preferWorkers` to be `false`. Some environments restrict the use of browser functionality, in this case there might be a problem with Workers. That's just a guess.

**Comment by talhaozdemir** [comment]
![image](https://user-images.githubusercontent.com/37840852/196046155-3227ed74-63d2-4bda-bec4-21c7c30b58d7.png)
I put a console in the catch but it is not triggered, no error I think

**Comment by talhaozdemir** [comment]
where to set `loadTexture.config.preferWorkers`? I can't find it.

**Comment by SuperSodaSea** [comment]
https://github.com/pixijs/pixijs/blob/e30b88657c184183b3d9b81cc9c5552df24d55dc/packages/assets/src/loader/parsers/WorkerManager.ts#L83-L89

Try `console.log(event.data)` before `complete()`?

**Comment by SuperSodaSea** [comment]
![image](https://user-images.githubusercontent.com/8724868/196046343-72698dc7-838e-4390-8cff-f431aa419ff7.png)

Seems that `createImageBitmap` is not supported in workers for `Safari`.

**Comment by bigtimebuddy** [comment]
Try this:
```js
Assets.loader._parsers[0].config.preferWorkers = false;
```

**Comment by talhaozdemir** [comment]
![image](https://user-images.githubusercontent.com/37840852/196046551-10e7573b-a873-4539-8e07-a99554d6abc9.png)

this is from chrome
![image](https://user-images.githubusercontent.com/37840852/196046567-61978f2e-efe6-4da9-9b99-7808efd70f05.png)

and in the unity ios only prints `loadImageBitmap`, after the first console there is an error I think

**Comment by talhaozdemir** [comment]
`Assets.loader._parsers[0].config.preferWorkers = false;`

@bigtimebuddy  this is solved the issue.

**Comment by SuperSodaSea** [comment]
So I think we need to check whether `createImageBitmap` is supported in workers before we use `WorkerManager.loadImageBitmap` to load image. @bigtimebuddy Any idea about where to do this check?

**Comment by talhaozdemir** [comment]
@bigtimebuddy @SuperSodaSea thanks for help by the way 👋🏼

**Comment by bigtimebuddy** [comment]
Hmm, not sure. It should probably be a static check in `loadTextures` and is considered here:
https://github.com/pixijs/pixijs/blob/e30b88657c184183b3d9b81cc9c5552df24d55dc/packages/assets/src/loader/parsers/textures/loadTexture.ts#L67

WorkerManager should probably manage the detection and have a property or method (e.g., `isBitmapSupported`) to check. Since the implementation details are owned by the WorkerManager.
