### ISSUE TITLE
when a graphic becomes a mask, it no longer takes effect

### ISSUE THREAD

**Issue by bcq028** [pixijs/pixijs#8743]
### Expected Behavior
I expect the code between line31~line36 make no difference as maskContainer never been associated with app
### Current Behavior
after uncomment the code, the mask seems takes no effect.
### question
Is this a expected behavior? when a sprite or a graphic becomes mask of other object, what inside it is changed?
### Steps to Reproduce
https://www.pixiplayground.com/#/edit/lSKQbzkZfKsvqBnQvNZ45 
and attach it here:
```javascript
    let frame = new PIXI.Graphics();
    frame.beginFill(0x666666);
    frame.drawRect(0, 0, 208, 208);
    frame.endFill()
    frame.position.set(320 - 100, 180 - 100);
    app.stage.addChild(frame);

    let mask = new PIXI.Graphics();
    mask.beginFill(0x333333);
    mask.drawRect(0,0,200,200);
    mask.endFill();

    // with the following lines uncomment,the 0x333333 color cannot be rendered!
    
    // let maskContainer = new PIXI.Container();
    // maskContainer.addChild(mask);
    // maskContainer.mask=mask;
    // maskContainer.position.set(4,4);

    frame.addChild(mask);
```
the code after line31 can cause behavior out of my expect
### Environment
- **`pixi.js` version**: 6.5.6
- **Browser & Version**: Chrome 106.0.5249.119
- **OS & Version**: windows10
- **Running Example**: [_url_](https://www.pixiplayground.com/#/edit/lSKQbzkZfKsvqBnQvNZ45)

**Comment by SuperSodaSea** [comment]
I think it is the expected behavior. Setting the `mask` of a `DisplayObject` will set the `mask`'s `renderable` to `false`, so it won't be rendered:

https://github.com/pixijs/pixijs/blob/e30b88657c184183b3d9b81cc9c5552df24d55dc/packages/display/src/DisplayObject.ts#L997

Maybe we can document this behavior more clearly. If you want to use the same `Graphics` as a mask and as a rendered object, you can just `clone()` it.

**Comment by bcq028** [comment]
> I think it is the expected behavior. Setting the `mask` of a `DisplayObject` will set the `mask`'s `renderable` to `false`, so it won't be rendered:
> 
> https://github.com/pixijs/pixijs/blob/e30b88657c184183b3d9b81cc9c5552df24d55dc/packages/display/src/DisplayObject.ts#L997
> 
> Maybe we can document this behavior more clearly. If you want to use the same `Graphics` as a mask and as a rendered object, you can just `clone()` it.

thanks!
