### ISSUE TITLE
Chrome Warning on TextMetrics

### ISSUE THREAD

**Issue by Makio64** [pixijs/pixijs#8745]
On the latest Chrome version we got this warning : 
```
TextMetrics.ts:623 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
```

### Expected Behavior
No warning in console

### Current Behavior
Warning on Chrome console

### Possible Solution
using willReadFrequently

### Steps to Reproduce
use text and change his content regulary ( like a score ) 

### Environment

- **`pixi.js` version**: 6.5.6
- **Browser & Version**: Chrome latest
- **OS & Version**: MacOS (not metal )

**Comment by bigtimebuddy** [comment]
Thanks for reporting. I recently fixed that [here](https://github.com/pixijs/gif/commit/dee26abb1eb327c5c321950e28fcbedaab336341) in `@pixi/gif`. This should be an easy fix.
