### ISSUE TITLE
[bezierCurveTo] Line cap/join not applied when line segments are drawn in opposite direction 

### ISSUE THREAD

**Issue by mmmintdesign** [pixijs/pixijs#8751]
### Expected Behavior
_'it should render a line cap if a line turns by 180°'_
### Current Behavior
This behavior was issued in an earlier issue https://github.com/pixijs/pixijs/issues/8288 , which was fixed. 
But the solution didn't apply to **bezierCurveTo**
### Possible Solution
https://github.com/pixijs/pixijs/pull/8325

### Environment

- **`pixi.js` version**: _e.g. 6.5.6_
- **Browser & Version**: _e.g. Chrome 106_
- **OS & Version**: _e.g. Windows 10_
- **Running Example**: https://www.pixiplayground.com/#/edit/mr1KrSdvWUI5WR7Pk1luL

**Comment by SuperSodaSea** [comment]
Seems to be problem here:

https://github.com/pixijs/pixijs/blob/c8e736c4257cb60c1ca01d8c789c8f3d532f2635/packages/graphics/src/utils/buildLine.ts#L329-L344

```diff
  /* +ve if internal angle counterclockwise, -ve if internal angle clockwise. */
+ const dot = -(dx0 * dx1 + dy0 * dy1);
  const cross = (dy0 * dx1) - (dy1 * dx0);
  const clockwise = (cross < 0);
  
  /* Going nearly straight? */
- if (Math.abs(cross) < 0.1)
+ if (dot > 0 && Math.abs(cross) < 0.1)
  {
```

What's more, it seems that the `cross` here is not normalized, so the `Math.abs(cross) < 0.1` can be incorrect.
