### ISSUE TITLE
The size of bitmap text can't be updated after regenerating bitmap font

### ISSUE THREAD

**Issue by Redgeioz** [pixijs/pixijs#8758]
### Expected Behavior
A resized bitmap text after regenerating bitmap font.

### Current Behavior
The size of old bitmap text can't be updated while new bitmap text can be created with a correct size.

### Steps to Reproduce
```jsx
var app = new PIXI.Application({
    width: window.innerWidth,
    height: window.innerHeight,
    backgroundColor: 0x000000
});

document.body.appendChild(app.view);

PIXI.BitmapFont.from("Arial", {
  fontFamily: "Arial",
  fontSize: 50,
  fill: 0xffffff,
}, {
  chars: ['1'],
});
let bitmapText = new PIXI.BitmapText("1", {
  fontName: "Arial",
});
bitmapText.position.set(500, 500);
app.stage.addChild(bitmapText);

setTimeout(() => {
    PIXI.BitmapFont.from("Arial", {
        fontFamily: "Arial",
        fontSize: 100,
        fill: 0xffffff,
    });
    let bitmapText2 = new PIXI.BitmapText("1", {
        fontName: "Arial",
    });
    bitmapText2.position.set(400, 400);
    app.stage.addChild(bitmapText2);
    bitmapText.updateText();
}, 1000);
```

### Environment

- **`pixi.js` version**: _above 5.3.0_
- **Browser & Version**: _Chrome 106.0.5249.119 & Edge 106.0.1370.47 & Firefox 106.0_
- **OS & Version**: _Windows 10_

**Comment by SuperSodaSea** [comment]
`BitmapText` has its own `fontSize`, which is initialized when `BitmapText` is constructed, and won't be changed when the `BitmapFont` is changed.
I think we can change this behavior to "If `BitmapText.fontSize` is not specified, the fontSize will be obtain from the `BitmapFont` dynamically"。
