### ISSUE TITLE
BitmapText issue upgrading to v7 Beta 3

### ISSUE THREAD

**Issue by Bonkles** [pixijs/pixijs#8759]
### Expected Behavior
In v7 beta, I should be able to instantiate and destroy multiple BitmapText objects. This same code worked in v6, the breakage happened when I updated my app to use the v7.0.0-beta.3 release. 

### Current Behavior
After calling `destroy({children: true})` on a BitmapText object, the next time a BitmapText is created with the same font, when `updateText()` is called a stack trace is generated, app freezes. 

### Possible Solution
If the usage of the BitmapText destroy method has changed in v7, the migration guide should call it out (https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide). I didn't see anything there, so this difference in behavior was unexpected. 

Not sure about the solution- I suspect a bug with destruction. I traced the issue down to the BitmapText::updateText() method, and found that it errors out here:

https://github.com/pixijs/pixijs/blob/ab35d96171d25a833e95c7f0d8e6a531948325c1/packages/text-bitmap/src/BitmapText.ts#L424

pageMeshData.mesh.texture is trying to get set here, but the `mesh` itself now has the `_destroyed` flag set to true and the shader is null, which causes the texture setter in this line to explode. 

### Steps to Reproduce

Here's a codesandbox link that generates the failure: https://codesandbox.io/s/pixi-playground-forked-mrkxxq?file=/src/index.js

Basic steps are:
1) Instantiate any BitmapText. 
2) Destroy that BitmapText with the `children: true` option. 
3) Instantiate another BitmapText with the same bitmap font. 
4) Call 'updateText' manually (or change the bitmapText properties to set its dirty flag, which in turn causes the code to call updateText) and observe the stack trace. 

Note: the behavior was unaffected if I called `destroy` with different texture or baseTexture options, only `children:true` caused it. 

### Environment

- **`pixi.js` version**:  7.0.0-beta.3
- **Browser & Version**: Chrome 105
- **OS & Version**: _e.g. MacOS 12.6 Montery (Intel chip) 
- **Running Example**: https://codesandbox.io/s/pixi-playground-forked-mrkxxq?file=/src/index.js

**Comment by bigtimebuddy** [comment]
I believe this was fixed #8735.

I'm making release to v6 and v7-beta today.

**Comment by SuperSodaSea** [comment]
Seems to be duplicated with #8732. It is already fixed by #8735 in the latest dev branch, but not released yet.

**Comment by Bonkles** [comment]
Terribly sorry for filing the dupe- I did search for other issues but somehow didn't see #8735!
