### ISSUE TITLE
Blocking local test failure after merging non-RGBA8 multisampled framebuffers

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixijs#8761]
Since merging #7619 I'm consistently getting this error. It's blocking me from making a new v7 release. This isn't failing on CI.

```
Summary of all failing tests
 FAIL  packages/core/test/RenderTexture.tests.ts
  ● Test suite failed to run

      ● RenderTexture › FloatRenderTexture › should render correctly with mask, multisampling, and format RED / type FLOAT

        expect(received).toEqual(expected) // deep equality

        Expected: 1
        Received: 0.30000001192092896

          387 |             gl.readPixels(0, 0, 1, 1, gl.RED, gl.FLOAT, pixel);
          388 |
        > 389 |             expect(pixel[0]).toEqual(1.0);
              |                              ^
          390 |
          391 |             pixel.set([0.1]);
          392 |

      at Object.<anonymous> (packages/core/test/RenderTexture.tests.ts:389:30)
        ● RenderTexture › FloatRenderTexture › should resize multisampled framebuffer with format RED / type FLOAT
          expect(received).toEqual(expected) // deep equality
          Expected: 1
          Received: 0.30000001192092896
            430 |             gl.readPixels(1, 1, 1, 1, gl.RED, gl.FLOAT, pixel);
            431 |
          > 432 |             expect(pixel[0]).toEqual(1.0);
                |                              ^
            433 |         });
            434 |     });
            435 | });
      at Object.<anonymous> (packages/core/test/RenderTexture.tests.ts:432:30)
```

**Comment by bigtimebuddy** [comment]
@SuperSodaSea do you think I should revert #7619 or is that something you might be able to look at?

**Comment by SuperSodaSea** [comment]
@bigtimebuddy I guess this is caused by different WebGL capability of different environments, the tests passed on my computer. Can you try to insert the code below after this line?

https://github.com/pixijs/pixijs/blob/8c0ede7f5caf1b67a8a82be2866f3c172448e809/packages/core/test/RenderTexture.tests.ts#L9

```js
const gl = temporaryRenderer.gl;
throw gl.getInternalformatParameter(gl.RENDERBUFFER, gl.R32F, gl.SAMPLES);
```

On my computer it shows `[16, 8, 4, 2, 1]`.

**Comment by bigtimebuddy** [comment]
I'm seeing `[4, 3, 2, 1]`

**Comment by SuperSodaSea** [comment]
> I'm seeing `[4, 3, 2, 1]`

The tests are using `MSAA_QUALITY.HIGH = 8`, which is invalid. The `FramebufferSystem` get the `msaaSamples` tested with `gl.RGBA8`, which may be different from the result of `gl.R32F`. I wondered what is the result on your computer with `gl.RGBA8`. (By the way, what GPU are you using?)

https://github.com/pixijs/pixijs/blob/8c0ede7f5caf1b67a8a82be2866f3c172448e809/packages/core/src/framebuffer/FramebufferSystem.ts#L102

As a quick fix, you can try to change the `MSAA_QUALITY` to `MEDIUM` int these two lines.

https://github.com/pixijs/pixijs/blob/8c0ede7f5caf1b67a8a82be2866f3c172448e809/packages/core/test/RenderTexture.tests.ts#L360
https://github.com/pixijs/pixijs/blob/8c0ede7f5caf1b67a8a82be2866f3c172448e809/packages/core/test/RenderTexture.tests.ts#L408

**Comment by bigtimebuddy** [comment]
I'm on an new-ish M1 Pro Mac, so Apple/Metal GPU.

**Comment by bigtimebuddy** [comment]
Changing MSAA_QUALITY didn't seem to work 🤔

**Comment by SuperSodaSea** [comment]
I tested in browser and the tests seems to be invalid:

https://pixiplayground.com/#/edit/c6W9zsKXta9-jEC4apKXs

```
GL_INVALID_OPERATION: Attempt to blit from a multisampled framebuffer and the bounds or format of the color buffer don't match with the draw framebuffer.
GL_INVALID_OPERATION: Invalid operation on multisampled framebuffer
```

**Comment by bigtimebuddy** [comment]
Same here.

**Comment by SuperSodaSea** [comment]
Seems that there is some problem `renderer.framebuffer.blit()`. Let me see if I can fix this...

**Comment by SuperSodaSea** [comment]
Oh I forgot to apply the latest dev version!

https://pixiplayground.com/#/edit/c6W9zsKXta9-jEC4apKXs

This works fine on my computer.

**Comment by bigtimebuddy** [comment]
That works for me too, which is weird. This might be an Electron issue which is running Chrome 87, maybe it's a GPU compatibility with that older version of Chrome and M1. Personally, I'm okay skipping those tests locally. What do you think it's a good check for skipping those tests?

**Comment by SuperSodaSea** [comment]
`npm run test:debug RenderTexture.tests.ts` can show the Electron window. Is there any warning in console?

**Comment by bigtimebuddy** [comment]
This is what I'm getting: `[.WebGL-0x1268ef600]GL ERROR :GL_INVALID_OPERATION : glReadPixels: format and type incompatible with the current read framebuffer`

**Comment by SuperSodaSea** [comment]
I found these pages:

[https://stackoverflow.com/questions/53562825/glreadpixels-fails-under-webgl2-in-chrome-on-mac](https://stackoverflow.com/questions/53562825/glreadpixels-fails-under-webgl2-in-chrome-on-mac)
[https://github.com/KhronosGroup/WebGL/issues/2747](https://github.com/KhronosGroup/WebGL/issues/2747)

Seems that we can workaround it by reading with `gl.RGBA` instead of `gl.RED`:

https://github.com/pixijs/pixijs/blob/8c0ede7f5caf1b67a8a82be2866f3c172448e809/packages/core/test/RenderTexture.tests.ts#L385-L395

Replace with:

```js
const pixel = new Float32Array([0.1, 0.2, 0.3, 0.4]);

gl.readPixels(0, 0, 1, 1, gl.RGBA, gl.FLOAT, pixel);

expect(pixel).toEqual(new Float32Array([1.0, 0.0, 0.0, 1.0]));

pixel.set([0.1, 0.2, 0.3, 0.4]);

gl.readPixels(1, 1, 1, 1, gl.RGBA, gl.FLOAT, pixel);

expect(pixel).toEqual(new Float32Array([0.5, 0.0, 0.0, 1.0]));
```

And:

https://github.com/pixijs/pixijs/blob/8c0ede7f5caf1b67a8a82be2866f3c172448e809/packages/core/test/RenderTexture.tests.ts#L428-L432

Replace with:

```js
const pixel = new Float32Array([0.1, 0.2, 0.3, 0.4]);

gl.readPixels(1, 1, 1, 1, gl.RGBA, gl.FLOAT, pixel);

expect(pixel).toEqual(new Float32Array([1.0, 0.0, 0.0, 1.0]));
```

@bigtimebuddy Does this work?

**Comment by bigtimebuddy** [comment]
Yes, that works :+1: Wanna do a PR for those changes?

**Comment by SuperSodaSea** [comment]
Sure!
