### ISSUE TITLE
PIXI app missing properties when upgrading from 6.4.2 to >= 6.5.0

### ISSUE THREAD

**Issue by Ericlm** [pixijs/pixijs#8786]
## Issue
I'm developing a Nuxt app where I use Pixi version 6.4.2. So far, everything has been working perfectly when creating the app, executing update loop etc. But when upgrading to Pixi >= 6.5.0, I get a crash at initialisation, because the Pixi application's ticker is undefined. As you can see, there seems to be some properties and methods missing when using pixi 6.5.0 (same with 6.5.7) : 

<img width="551" alt="Capture d’écran 2022-10-25 à 20 48 53" src="https://user-images.githubusercontent.com/19361503/197859309-82aeaa6d-7fd7-428b-a751-754a3bebbe17.png">
Which is not the case in the version 6.4.2:
<img width="560" alt="Capture d’écran 2022-10-25 à 20 54 29" src="https://user-images.githubusercontent.com/19361503/197859292-4dd8af0a-2ccd-42c0-b37f-074d009e56b5.png">

## Possible Solution
I need to keep the version under 6.5.0 to have the application working fine. I also created a vanilla js app with pixi and it's working fine:
<img width="544" alt="Capture d’écran 2022-10-25 à 21 05 28" src="https://user-images.githubusercontent.com/19361503/197860165-8eef3895-4030-4c62-9b9b-81a3418d3532.png">

I think it may be due to packages or something like that ; I'll try to make a code sandbox so you can test it.

### Environment
- Application using Nuxt 2 with the following pixi packages : 
  "pixi.js": "~6.4.0",
   "@pixi-essentials/cull": "^1.1.0",
    "@pixi/events": "^6.2.1",
    "@pixi/filter-drop-shadow": "^4.1.5",
    "@pixi/graphics-smooth": "^0.0.20",
    "@pixi/picture": "^3.0.5",
- Pixi version 6.4.2 **VS** > 6.5.0
- Firefox
- macOS Ventura M1 iMac

Thank you for your help!

**Comment by bigtimebuddy** [comment]
When upgrading, can you please [follow this advice](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS). Common issue for v6.

**Comment by Ericlm** [comment]
Thank you for the advice, I did not know that. Unfortunately, I could not make it work, I still have the issue. 
I created a [sandbox](https://codesandbox.io/s/nifty-galileo-9k0egu?file=/pages/index.vue) with pixi 6.4.2 where it was working fine, but I tried to upgrade it to 6.5.8 and I had a bunch of ENOENT errors (like `ENOENT: no such file or directory, open '/sandbox/node_modules/@pixi/core/dist/esm/core.js'`) 😅 I don't understand what happened between 6.4.2 and 6.5 versions. Thank you again for your help!

**Comment by bigtimebuddy** [comment]
One clue with the error message:
```
ENOENT: no such file or directory, open '/sandbox/node_modules/@pixi/core/dist/esm/core.js'
```
The file name should be `core.mjs` (see [package.json of @pixi/core](https://unpkg.com/@pixi/core@6.5.8/package.json)). I'm not sure why the extension is changing.

Maybe this version of Nuxt has issues with mjs? I don't know enough about this bundling tool to debug.

**Comment by Ericlm** [comment]
Sorry, I'm using Nuxt everyday, and I forget that people may not know about it 😅. This is basically a wrapper around webpack, vuejs, and some cool frameworks around vuejs. So, to make the code sandbox work, I added the following into the webpack config so it can "understand" mjs files: (it's inside `nuxt.config.json`)
```
extend(config, ctx) {
      config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: "javascript/auto"
      });
    }
```
Maybe I'm missing something here, but at least the issue is now exactly the one I have in my code ; the console will print out the pixi app, but without some properties.

**Comment by bigtimebuddy** [comment]
I don't understand why when I touch some of the pixi dependencies, this shows a mix of cjs and esm. It should all be esm. This mix is going to have unpredictable behaviors.

![Screen Shot 2022-10-26 at 11 38 30 AM](https://user-images.githubusercontent.com/864393/198072307-50cd065d-bc72-4974-bc8a-cec106414553.png)

**Comment by Ericlm** [comment]
I tried to set the config type to `javascript/esm` instead of `javascript/auto`, but it gives me a lot of errors like `Can't import the named export 'ALPHA_MODES' from non EcmaScript module (only default export is available)`. It may be due to the webpack version, or something else... I don't want to waste your time on an issue that most pixi users don't have ; it's ok if we need to stick to 6.4.2 🙂

**Comment by bigtimebuddy** [comment]
Try this in your nuxt.config.js

```
import { readdirSync } from 'fs';
import path from 'path';

const rootPath = path.resolve(__dirname, 'node_modules/@pixi');
const aliases = readdirSync(rootPath).reduce((acc, folder) => {
    const { name, module } = require(path.join(rootPath, folder, 'package.json'));
    acc[name] = path.join(rootPath, folder, module);
    return acc;
}, {});

export default {
  build: {
    loaders: {
      imgUrl: {
        limit: 1000000000
      }
    },
    extend(config) {
      Object.assign(config.resolve.alias, aliases);
      config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: "javascript/auto"
      });
    }
  }
};
```

**Comment by Ericlm** [comment]
It works ! I have no idea what this JS magic is doing, but thank you very very much! 🙏
