### ISSUE TITLE
index.d.ts is missing for @pixi/unsafe-eval

### ISSUE THREAD

**Issue by SuperSodaSea** [pixijs/pixijs#8791]
It seems that the `index.d.ts` for `@pixi/unsafe-eval` is missing since [`7.0.0-beta.5`](https://unpkg.com/browse/@pixi/unsafe-eval@7.0.0-beta.5/). Maybe something is wrong in #8769?
(Maybe other packages have the same problem, I didn't check all of them.)

**Comment by bigtimebuddy** [comment]
For some reason that package didn't generate typings, the others look fine. I'll look into it.
