### ISSUE TITLE
New EventSystem in v7 is conflicting with zone.js in Angular projects

### ISSUE THREAD

**Issue by Julien-Marcou** [pixijs/pixijs#8794]
### Expected Behavior

I should be able to use PixiJS in an Angular Project

### Current Behavior

I get the following error when importing `pixi.js` v7.0.0 in an Angular projet:

```sh
Error: node_modules/@pixi/events/lib/FederatedEventTarget.d.ts:11:18 - error TS2320: Interface 'FederatedEventTarget' cannot simultaneously extend types 'EventEmitter<string | symbol, any>' and 'EventTarget'.
  Named property 'removeAllListeners' of types 'EventEmitter<string | symbol, any>' and 'EventTarget' are not identical.

11 export interface FederatedEventTarget extends utils.EventEmitter, EventTarget {
                    ~~~~~~~~~~~~~~~~~~~~
```

It turns out `zone.js` is monkey patching the native EventTarget interface (https://github.com/angular/angular/blob/37ba6104498202b671f5a5a6bbfacc4df501788b/packages/zone.js/lib/zone.api.extensions.ts#L29) to add a `removeAllListeners?(eventName?: string): void;` method, which conflicts with the `removeAllListeners(event?: EventEmitter.EventNames<EventTypes>): this;` method on the EventEmitter from the `eventemitter3` package.

In an Angular projects (or any project using zone.js), it's impossible to create an interface that extends `EventEmitter` (from `eventemitter3`) and `EventTarget` at the same time.

It's possible to disable the monkey patch by adding this line to the Angular project `(window as ZoneGlobalConfigurations).__Zone_disable_EventTarget = true;` but the typing would still make the compilation fail.

### Possible Solution

Still searching for one, does the `FederatedEventTarget` interface need to extend the `EventTarget` ?

Right now I can bypass the problem by not using the new EventSystem. So I have to avoid importing `pixi.js` or `@pixi/events` and only import the other packages individually (`@pixi/core`, `@pixi/sprite`, ...)

### Steps to Reproduce

- Create an angular project
- Install `pixi.js`
- Import `pixi.js` or `@pixi/events` somewhere
- Serve the project

Here is a reproduction repository: https://github.com/Julien-Marcou/angular-pixijs-issue-8794

### Environment

- **`pixi.js` version**: 7.0.0
- **`angular` version**: 14.2.8
- **`zone.js` version**: 0.11.8

**Comment by bigtimebuddy** [comment]
Is this not a zone.js bug since they are doing the monkey patch, not Pixi?

**Comment by Julien-Marcou** [comment]
There is a debate indeed, but it's supposed to be a feature of zone.js, I'm not using it but if other developers are using `removeAllListeners` on their projects, then the new EventSystem is incompatible with zone.js.

It is working with PixiJS v6 that's why I'd rather open an issue here, but may be there is a better solution.

**Comment by bigtimebuddy** [comment]
@ShukantPal you want to weigh-in on this?

**Comment by ShukantPal** [comment]
I would suggest using patch-package to override the type definition file in @pixi/events to remove the conflict just for yourself. It's best if the conflict is solved downstream.

**Comment by Julien-Marcou** [comment]
IMO, this should be fixed on PixiJS's side, as it would be a huge blocker for developers to have to do a custom patch to get PixiJS to work in an Angular project, or specifically never import `pixi.js` or `@pixi/events`.

Developers are lazy, they would not read the entire doc, and struggle before they find out they need to patch something that is expected to work out of the box 😅

---

It turns out it only is a typing issue, as `DisplayObject`s implement the `EventTarget` but are not `EventTarget`s themself, Angular does not monkey patch them.

So I'm able to fix the problem by overriding the declaration of the `FederatedEventTarget` interface in `packages/events/src/FederatedEventTarget.ts`.

`eventemitter3`'s `EventEmitter` can accept 3 types of events `string`, `symbol` or `object`, by default it is configured with `string` and `symbol` only.

When it is configured with an `object`, you can call the `removeAllListeners` method only using a key from the object.
This typing is done through:

```ts
export type EventNames<T extends string | symbol | object> = T extends string | symbol
    ? T
    : keyof T;
```

So by default, `EventEmitter`'s `removeAllListeners` method matches this signature:

```ts
removeAllListeners(event?: EventNames<string | symbol>): this;
```

Which is equivalent to this signature:

```ts
removeAllListeners(event?: string | symbol): this;
```

Which is compatible with `zone.js`'s `removeAllListeners` signature.

So as long as we don't use an `object` to configure the `EventEmitter` we can override the `removeAllListeners` signature in the `FederatedEventTarget` interface:

```diff
/**
 * Describes the shape for a {@link FederatedEvent}'s' `eventTarget`.
 * @memberof PIXI
 */
export interface FederatedEventTarget extends utils.EventEmitter, EventTarget
{
    /** The cursor preferred when the mouse pointer is hovering over. */
    cursor: Cursor | string;

    /** The parent of this event target. */
    readonly parent?: FederatedEventTarget;

    /** The children of this event target. */
    readonly children?: ReadonlyArray<FederatedEventTarget>;

    /** Whether this event target should fire UI events. */
    interactive: boolean;

    /** Whether this event target has any children that need UI events. This can be used optimize event propagation. */
    interactiveChildren: boolean;

    /** The hit-area specifies the area for which pointer events should be captured by this event target. */
    hitArea: IHitArea | null;
+
+    /* Remove all listeners, or those of the specified event. */
+    removeAllListeners(event?: string | symbol): this;
}
```

Another solution if we want to be able to configure the `EventEmitter` with an `object` in the future, is to let both signatures live together in the interface, and let the choice for the developers to specify witch events are supported by the `utils.EventEmitter`.

The only problem with this solution is that if a developer restricts the events to an `object` or a `symbol`, then he would still be able to call `removeAllListeners` with an incorrect `string` and not get a typing error.

```diff
/**
 * Describes the shape for a {@link FederatedEvent}'s' `eventTarget`.
 * @memberof PIXI
 */
- export interface FederatedEventTarget extends utils.EventEmitter, EventTarget
+ export interface FederatedEventTarget<EventTypes extends utils.EventEmitter.ValidEventTypes = string | symbol>
+    extends utils.EventEmitter<EventTypes>, EventTarget
{
    /** The cursor preferred when the mouse pointer is hovering over. */
    cursor: Cursor | string;

    /** The parent of this event target. */
    readonly parent?: FederatedEventTarget;

    /** The children of this event target. */
    readonly children?: ReadonlyArray<FederatedEventTarget>;

    /** Whether this event target should fire UI events. */
    interactive: boolean;

    /** Whether this event target has any children that need UI events. This can be used optimize event propagation. */
    interactiveChildren: boolean;

    /** The hit-area specifies the area for which pointer events should be captured by this event target. */
    hitArea: IHitArea | null;
+
+    /* Remove all listeners, or those of the specified event. */
+    removeAllListeners(event?: utils.EventEmitter.EventNames<EventTypes>): this;
+    removeAllListeners(event?: string): this;
}
```

---

I'm willing to make a PR for the first solution if that's ok with you.
Maybe with a comment above the signature that links to this issue so that we know why it's overridden.

**Comment by bigtimebuddy** [comment]
Option 1 seems the less complicated. I'm slightly less concerned about `removeAllListeners`, but are you sure this error isn't masking other EventEmitter conflicts? Is the extent of this problem just about `removeAllListeners`?

**Comment by bigtimebuddy** [comment]
Feel free to make a PR. Also, the change should include a note about _why_ we're re-declaring a looser type here.

**Comment by Julien-Marcou** [comment]
It's not masking other `EventEmitter` conflicts as it's only overriding the signature for `FederatedEventTarget` which is already working with a `string | symbol` event emitter.

Here is what we get right now:
![image](https://user-images.githubusercontent.com/4369075/199213056-9de0e9c1-c904-432a-ac73-a824bf04ed1c.png)

And here is what we would get if we implement the fix:
![image](https://user-images.githubusercontent.com/4369075/199214752-b30842f0-ef5d-4479-9ee8-a06c337bc3e1.png)
