### ISSUE TITLE
Packages aren't declaring their dependencies

### ISSUE THREAD

**Issue by ASDFGerte** [pixijs/pixijs#8798]
A package should declare its dependencies. E.g. `@pixi/sprite` clearly depends on `@pixi/display`: [`import { Bounds, Container } from '@pixi/display';`](https://github.com/pixijs/pixijs/blob/dev/packages/sprite/src/Sprite.ts#L2), but doesn't declare this in its [manifest](https://github.com/pixijs/pixijs/blob/dev/packages/sprite/package.json). Instead, since https://github.com/pixijs/pixijs/pull/8630 even the declaration as `peerDependencies` got removed, in favor of a non-standard `pixiDependencies`, which no tool in existence will recognize. Note: to me, it should have been a normal dependency to begin with, although there may have been some odd reason, which I missed, why these were `peerDependencies`.

While ~~a package manager stuck in bureaucracy and technical debt~~ our friendly default choice npm ignores this (at least last time I checked), such isn't the case for yarn under strict pnp:
> Because the hoisting heuristics aren't standardized and predictable, PnP operating under strict mode will prevent packages from requiring dependencies that are not explicitly listed; even if other dependencies also depend on it.

This leads to TS not compiling, because it cannot find the related types (imports fail, e.g. `Sprite` then misses all properties from `DisplayObject` - "Argument of type 'Sprite' is not assignable to parameter of type 'DisplayObject'."). I didn't try, but squelching the TS errors would likely lead to a runtime error, where yarn refuses the import on the code.

- **`pixi.js` version**: 7.0.0
- **`yarn`** under strict pnp (though my guess is a "properly" setup pnpm would also error)

**Comment by bigtimebuddy** [comment]
Okay, let's dig-in...

* We tried dependencies, but that didn't work and has similar problem as peers in terms of upgrading, see #7559
* We tried peerDependencies, but that was more of the same but worse #8630 

The relationship between `@pixi/sprite` and `@pixi/display` isn't as clear as you describe. `@pixi/display` is an up-stream dependency, which are usually describe as peers or transitive dependencies (like babel vs babel plugins). We want to make sure that `@pixi/display` is installed _along-side_ `@pixi/sprite`, not as a child dependency. When you start to introduce other plugins, sometimes the package managers nest these dependencies, resulting in double installs of things like `@pixi/display`, which is bad. Package manager also struggle with upgrading a network of things with peer dependencies, though most get them right when installing for the first time.

Using the bundles (`pixi.js`, `pixi.js-legacy`, `@pixi/node`, `@pixi/webworker`) is now _MUCH_ easier to upgrade. This has always been the priority. pnpm, npm, yarn all had slightly differing fits about how to upgrade our network of packages. Most users are using one of these bundles and that is the recommended path for most users.

The field `pixiDependencies` was added for the future to be able to do some validation check on your local Pixi setup (potentially to auto-install), however, you're right it is non-functional with any tools right now.

If you're _not_ using a bundle, you will need to declare all missing packages explicitly. We will be upgrading our tooling to help support v7, but that hasn't quite happened yet: https://pixijs.io/customize

**Comment by bigtimebuddy** [comment]
Also, I forgot to add: I cannot speak to strict pnp. If you could provide an example repo that reproduces the issue, that would be helpful. Thanks.

**Comment by ASDFGerte** [comment]
After reading some of the linked PRs and issues, I'd still choose `dependencies`. I couldn't see a clear case, where pixi's setup was at fault<sup>1</sup>. It's nice, that you are trying to make things as comfortable as possible for the users, but bending core concepts of the ecosystem might start causing more trouble than good.

To me, the relationship still looks as clear. The `dependencies` field was made for package-managers to parse, and form a dependency-graph on the package-level. Fetching and storing the minimal amount of packages, de-duplicating, is their job (primarily, with all the complexity that arises).

As already mentioned, `@pixi/sprite` imports code from `@pixi/display`, and builds further up from it - the stereotypical plain and simple case for `dependencies`. It's imho not something special like a plugin either, although a `peerDependency` would at least tell the package-manager the demand.

If you could show a case, where a package-manager duplicates packages for no valid reason, that would be useful. If there is such a case, it might be interesting to analyze (but at least for me, upgrading, and even downgrading, worked without any problems). That would probably be a bug in the related package-manager. I'd understand a temporary work-around, until the issue is fixed, but not abolishing `dependencies` altogether.

---

For the reproduction, I did the simplest possible: no typescript, only yarn and pixi. You'll need `yarn` somehow though, for the commands. Easiest is having it installed, node's corepack comes to mind. Perhaps it's also possible to run the yarn file directly, but I have no experience doing so.

As I did not commit the whole yarn cache, a `yarn install` (`--immutable` parameter should be unnecessary here) is necessary, to fetch the required packages from npm.

https://github.com/ASDFGerte/pixirepro

Running `yarn node index.mjs` will then cause the following error:
> Error: @pixi/mixin-cache-as-bitmap tried to access @pixi/core, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

For a more complex setup, with typescript and all, the problem arises earlier, when typescript cannot resolve the types. This results in errors like:
> Argument of type 'Sprite' is not assignable to parameter of type 'DisplayObject'.
However, I wanted to keep it as simple as possible.

In case of interest, steps taken to produce that project were:
 - Run `yarn init -2`.
 - Remove unnecessary files editorconfig and README.
 - Change gitignore to exclude yarn cache.
 - Run `yarn add pixi.js`.
 - Add `index.mjs` with some import to pixi, and change to `"type": "module"` in manifest (although the same would happen with cjs).
 - Run `yarn install` after editing the manifest, to get the esm pnp loader.

---

[1]: One got closed by the author, but no statement was made, what the cause or solution was. Another seemed like user-error, where a not yet compatible plugin was installed. Obviously, if there are dependencies on disjoint ranges, multiple versions of pixi will get added, but the fault here lies in telling the package-manager to install packages which aren't compatible (yet).

**Comment by SuperSodaSea** [comment]
I wondered how other multi-package projects solve this dependency problem?

**Comment by ASDFGerte** [comment]
I've mentioned this elsewhere already: yarn does offer an easy user-side way to [patch dependencies into projects missing dependency declarations](https://yarnpkg.com/configuration/yarnrc#packageExtensions), allowing for a user-side "fix":
> Some packages may have been specified incorrectly with regard to their dependencies - for example with one dependency being missing, causing Yarn to refuse it the access. The `packageExtensions` fields offer a way to extend the existing package definitions with additional information. [...]

However, all this setting does is add the missing dependency declarations as a patch. This leaves the question, why they weren't there in the first place.

As an example, with [`GlobalMixins` seemingly fixed now](https://github.com/pixijs/pixijs/issues/8799) :tada:, the following arises: `@pixi/math-extras` has a `normalize(): import('@pixi/math').Point;`, and you guessed it, the import fails, the return becomes `any`, and errors are piling on top of another. Adding the following to the yarn config solves the problem (followed by a `yarn install`, and restarting TS language services):
```yaml
packageExtensions:
  "@pixi/math-extras@^7.0.2":
    dependencies:
      "@pixi/math": "^7.0.2"
```

**Comment by bigtimebuddy** [comment]
@ASDFGerte I've been working an an alternative strategy here that fixes this problem (and solve other future problems for us). Basically, I created a new package called `pixijs`. This basically ships a _single_ package with multiple submodules imports for all the PixiJS packages. 

https://www.npmjs.com/package/pixijs

#### Advantages

* Way simpler to ship
* Easier to consume, one package!
* Easier to author plugins against, one peerDependency
* Easier to transition from bundles to individual packages
* No complicated package dependency relationships
* Aligns better with our strategy to have webgl/canvas/webgpu flavors for display objects

#### Disadvantages

* Includes all the node-bundle dependencies, which are heavy to install first time
* Sourcemaps may not be 100% accurate
* Doesn't include browser builds

With your example, I swap `pixi.js` with `pixijs`, and I now get this:

```
yarn node index.mjs
[class Sprite extends Container]
```

**Comment by bigtimebuddy** [comment]
We've already tried `dependencies` and we had issues (e.g., https://github.com/pixijs/pixijs/issues/7209, https://github.com/pixijs/pixijs/issues/7294). Getting double core packages, for example, produces all sorts of weird , unintuitive side effects and lots of GitHub issues where the solution is to re-install your node_modules, nuke your lock file. Take this very simple example:

* node_modules/@pixi/sprite
* node_modules/@pixi/sprite/node_modules/@pixi/core
* node_modules/@pixi/display
* node_modules/@pixi/display/node_modules/@pixi/core

☝️  this is bad

When we used `dependencies` this can be valid. Most package manager hoist shared dependencies with shared semver ranges, but it still happens occasionally.

**Comment by ASDFGerte** [comment]
Having departed from npm for various reasons (imho it's bad), and therefore not having had trouble with it for a while, I'll need to research, whether this can still happen on modern versions. I was under the impression, that unless the version ranges are disjoint, such behavior cannot happen, unless it was a clear bug.

Double checking, I noticed that perfect hoisting was an advertisement point for pnp in yarn, and perhaps took it too much for granted. Personally, I depend on this, and would not deviate from `dependencies` for fear of this occurring, but can understand, that should such a problem exist with npm, that would be a valid reason.

As mentioned before, the issues sadly don't give much insight. At a glance, both got resolved, without discovering the underlying issue, which caused the packages to be duplicated and nested to begin with. I suspect user-error, but am not sure anymore. I'll research a bit about the current state of npm tomorrow, if i find the time. Perhaps I can find out, whether this is allowed to happen in npm, or would also be considered a clear bug there.

**Comment by bigtimebuddy** [comment]
@luxaritas see this for more context https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS

PeerDependencies _should_ be the correct relationship (to avoid nesting) but often failed with npm when trying to upgrade with other plugins with less specific semver range.

**Comment by luxaritas** [comment]
Thanks! The issues linked there are much clearer. And yeah, the relationship does make sense since those packages aren't being used in a fully encapsulated way, but are in some fashion exposed to/tied in with other packages.

Just in case it's interesting/useful for anyone else: I was curious what could cause an issue in this case, so I took at #8144 since that issue has a clear repro case.
* Indeed, even though pixi was using peer dependencies, there are still duplicate packages (`@pixi/loaders` and `pixi.js/node_modules/@pixi/loaders`).
* The `@pixi-spine` packages had a peer dep to pixi packages of `^6.1.0`, `@pixi/layers` had a peer dep to pixi packages of `^6.0.4`, and `pixi.js` had regular dependencies to pixi packages of `6.2.2` (well, `6.5.8`, given I just did the test now where pixijs was set to `^6.2.2`, so the newer version of `pixi.js` was validly included according to that rule).
*It is interesting that npm prefers adding new dependencies under `pixi.js` with the new version rather than removing the old top-level versions since the new versions are also compatible. I imagine there may be some optimization where it prefers not removing old packages since that may require additional downloads/"unrequired" package updates that aren't predicted, and it assumes it's safe since `pixi.js` declares them as true dependencies, so therefore shouldn't need to interoperate with the versions required as peers by other packages
* I'm wondering if making `pixi.js`'s dependencies peer dependencies would fix this issue (assuming this would indicate these packages should be provided at the top level in the same way as other packages). However, something interesting I encountered is that if I added a dependency of `@pixi/core` of `^6.2.2` (another thing which I hypothesized could force the correct versions to be installed, since it would move that package into the top-level scope as opposed to purely being resolved transitively), npm actually failed to resolve entirely due to conflicting peer dependencies. That seems like an npm bug, as it should be able to resolve just fine by top-level package version (and works correctly when you clear the node_modules and package-lock).

**Comment by ASDFGerte** [comment]
So I swept under the carpet, that versions need to be exactly the same, and indeed, the guarantee is pnp specific (oops):

> When I say undefined behavior, I mean it in the C/C++ sense: it's undefined in the sense that nothing defines what happens when two packages from the dependency tree overlap[1]. They might be resolved to the same version, but maybe not. And the behavior can change if we need to.
> 
> [1] Except in Plug'n'Play, where it is standardized that regardless of the position of the dependent package in the dependency tree, the exact same range absolutely must resolve to the exact same version (we can afford to do it there because we're not restricted by the hoisting anymore). Still not guarantees on overlapping-but-different ranges, though (because of the two points I detailed above).

([link](https://github.com/yarnpkg/yarn/issues/6695#issuecomment-442363829))

This would catch the [given example](https://github.com/pixijs/pixijs/issues/8798#issuecomment-1316072830), where pixi packages dupe their dependencies internally, but not cases of external plugins, or anything outside of pnp, e.g. all usage on npm. You are correct, that generally `peerDependencies` is the better path.

---

So I second the thought of

> I'm wondering if making pixi.js's dependencies peer dependencies would fix this issue

As with the path of `peerDependencies`, this should probably be the case (otherwise you have normal dependencies at one point again)? That would be similar to requiring an install of all the pixi packages individually. A bit cumbersome - perhaps there is a better way to install a bundle of packages?
