### ISSUE TITLE
Packages self-reference with mismatching exports declaration

### ISSUE THREAD

**Issue by ASDFGerte** [pixijs/pixijs#8799]
In version 7.0.0 the folder structure of packages changed. Along with it, for reasons unknown to me, the type reference changed from a relative path `/// <reference types="./global" />` to a self-reference `/// <reference types="@pixi/core/global" />`.

Since the packages declare an `exports` field in their manifest, which doesn't list this entry, conforming tools won't resolve it:
```json
  "exports": {
    ".": {
      "import": {
        "types": "./lib/index.d.ts",
        "default": "./lib/index.mjs"
      },
      "require": {
        "types": "./lib/index.d.ts",
        "default": "./lib/index.js"
      }
    }
  },
```
This is the case e.g. for [typescript since version 4.7](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing). Along potential other issues, this breaks `GlobalMixins`, causing e.g. type errors for `@pixi/math-extras`. Imho, the simplest fix would be reverting to a relative path (`/// <reference types="../global" />`, note the extra dot due to the changed folder structure), although I did not investigate the reasons for this change.

- **`pixi.js` version**: 7.0.0
- **`typescript`**: ^4.7

**Comment by bigtimebuddy** [comment]
Makes sense, thanks for reporting. Added a PR for this.

**Comment by ASDFGerte** [comment]
This went partially right, but `\w+` doesn't match `-`: `@pixi/math-extras` now has a `/// <reference types="packages/math-extras/global" />`. I'm not sure what names are all allowed, but at least the `-` needs to be there.
