### ISSUE TITLE
pivot cannot set center of sprite

### ISSUE THREAD

**Issue by bcq028** [pixijs/pixijs#8801]
### Expected Behavior
I hope line33 behave the same as line32.. I'm confused of the usage of pivot
I think if an image with width 100 and height 100, set pivot to 50,50 and then set position to 200,200, then its center point will be at 200,200. But it seems when i want to move 50px away from its left top point, it moves over 150px
![image](https://user-images.githubusercontent.com/108849949/198936434-c64885d6-fbe7-4ffe-9072-93190cc057f0.png)
### Steps to Reproduce
https://www.pixiplayground.com/#/edit/lSKQbzkZfKsvqBnQvNZ45

**Comment by SuperSodaSea** [comment]
Should be `bunny.pivot.set(bunny.texture.width / 2, bunny.texture.height / 2)`. Setting the width & height of a `Sprite` will change its scale (something like `scale = newWidth / texture.width`), and the `pivot` is applied before scale, so the value of `pivot` should refer to the `Sprite`'s original size (the size of its texture).

**Comment by bcq028** [comment]
I make two mistakes, thanks for point out the first. but I still cannot get proper result with set texuture.width. I tried to log the texture.width and find it was set to 1
I tried to add a loader
```js
const loader = new Loader()
let texture2
loader.add('bunny', 'assets/bunny.png')
    .load((_, res) => {
        texture2 = res['bunny'].texture
    })
    .onComplete.add(() => {
        const bunny = new PIXI.Sprite(texture2);
        bunny.x = app.view.width / 2
        bunny.y = app.view.height / 2
        // bunny.anchor.set(0.5)
        bunny.pivot.set(bunny.texture.width / 2, bunny.texture.height / 2)
        app.stage.addChild(bunny)
    })
```
and now I can get texture.width. 
Without a loader the `bunny.texture.width` will return 1, and it's not the real width.
