### ISSUE TITLE
sprite.cursor not work

### ISSUE THREAD

**Issue by Starsky-Type** [pixijs/pixijs#8802]
I'm using the latest version : v7.0.0 on Windows 11 Edge

The cursor property does not work:

```
        const circle = PIXI.Sprite.from('logo.png');
        circle.x = 500;
        circle.y = 200;
        circle.interactive = true;

        console.log(circle.cursor); //undefined
        
        circle.cursor = 'pointer';

        app.stage.addChild(circle);
```

The cursor did not change when I moved over this sprite and when I printed out this property, it said :' undefined'

**Comment by SuperSodaSea** [comment]
https://www.pixiplayground.com/#/edit/L6Ux_HbiZB1_arUn84_wx

This example works fine on my computer (Chrome / Edge). `cursor === undefined` is fine before you give it a value.

**Comment by Starsky-Type** [comment]
Ok, it works, thanks.
