### ISSUE TITLE
WARNING: Too many active WebGL contexts. Oldest context will be lost.

### ISSUE THREAD

**Issue by juztinlazaro** [pixijs/pixijs#8814]
Having an issue, rendering 12 contexts in one page

### Environment

- **"pixi.js": "^6.0.4",
- **Chrome 
- **Windows 10

**Comment by bigtimebuddy** [comment]
This is a browser limitation with WebGL. Some approaches: use Canvas rendering (No browser limit), reuse renderers, or render one larger context instead.

**Comment by changeyoucant** [comment]
> This is a browser limitation with WebGL. Some approaches: use Canvas rendering (No browser limit), reuse renderers, or render one larger context instead.
whats  Canvas rendering ?

**Comment by changeyoucant** [comment]
> This is a browser limitation with WebGL. Some approaches: use Canvas rendering (No browser limit), reuse renderers, or render one larger context instead.

how to use Canvas rendering ? i have a component like this drag vue . in every darg file , i init app. then i need map this component many times . over 12 contexts its error . with pixi 8 . i cant find the Canvas rendering
