### ISSUE TITLE
trimCanvas: use better algorithm

### ISSUE THREAD

**Issue by maximgavrilov** [pixijs/pixijs#8815]
Current trim detection go through all pixels, but the better algorithm is to crop rows/columns by there sides.

Example implementation: https://gist.github.com/timdown/021d9c8f2aabc7092df564996f5afbbf

https://github.com/pixijs/pixijs/blob/978eb26fd693cc1c66e164cfd987d072c358b319/packages/utils/src/media/trimCanvas.ts#L20

**Comment by SuperSodaSea** [comment]
Looks great, would you like to make a PR for this?
