### ISSUE TITLE
why 'Cannot read properties of undefined (reading 'shared')'

### ISSUE THREAD

**Issue by zhichao8756** [pixijs/pixijs#8818]
![image](https://user-images.githubusercontent.com/24514251/199670532-df378288-ef7c-4eb9-affc-d1e0e82360bf.png)
I I refer to the plugin dragonBones Example

### Environment

- **`pixi.js` version**: 7.0.2
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: WIndows 11

**Comment by SuperSodaSea** [comment]
`Loader` is removed in PixiJS v7, you can use `Assets` instead.
For more information, see [v7 Migration Guide / Replaces Loader with Assets](https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide#-replaces-loader-with-assets).
