### ISSUE TITLE
Assets progress callback reports 1 before finished loading assets

### ISSUE THREAD

**Issue by smjnab** [pixijs/pixijs#8819]
I'm working on migrating to 7.x from 6.5.8 and started with the assets. I noticed that when the onProgress callback reports 1, the assets are not yet ready to be used. Unsure if this is the intended behaviour or not.

In my class where I have assigned Assets to property assets:

```
// A texture json from TexturePacker
this.assets.addBundle("base", {
    textures: "assets/textures/textures.json"
});

this.assets.loadBundle("base", (progress) => {
    if(progress == 1) console.log(this.assets.get("textures"));
});
```
Doing this will print: undefined

However if I change the test to wait for next frame, it works fine.
```
this.assets.loadBundle("base", (progress) => {
    if(progress == 1) requestAnimationFrame(() => console.log(this.assets.get("textures")));
});
```
Doing this will print: Spritesheet {...}

- **`pixi.js` version**: 6.5.8 and @pixi/assets 6.5.8

**Comment by SuperSodaSea** [comment]
The `await this.assets.loadBundle()` returns after calling the callback `progress === 1`, so your `base` is not ready in the callback until next frame. I think if you want to do something when the whole bundle is loaded, you can simply change your code into this:
```js
const test = async () => {
    const base = await this.assets.loadBundle('base');
    console.log(base);
};
```

**Comment by smjnab** [comment]
Thanks for reply, I updated the sloopy example to be more to the point. The question of the issue was if the intended behaviour of the state of the assets when onProgress reports 1 is as it should be.

**Comment by bigtimebuddy** [comment]
I would say that this is as-designed. I don't think there's an expectation that when progress is 1 that the assets are available. The progress handler is designed for the purpose of tracking files that have been downloaded (for easily doing a progress bar). If you're looking for a complete event, waiting until the Promise is resolved is best option.
