### ISSUE TITLE
BitmapText - Non-breaking space

### ISSUE THREAD

**Issue by Ericlm** [pixijs/pixijs#8821]
### Expected Behavior
I'm trying to display a BitmapText where the text contains a non-breaking space, and I was expect it to be displayed juste like a regular space.

### Current Behavior
The issue is that there is no space at all displayed, so a text like `29 hours` is displayed as `29hours`.

### Possible Solution
Would it be possible to consider a non-breaking-space juste like a regular space, to allow spacing between characters ?

### Steps to Reproduce
- create a BitmapText, with the text containing a non-breaking-space
- display it, and the space won't be visible, while a regular space is

### Environment

- **`pixi.js` version**: 6.5.8
- **Browser & Version**: Firefox 
- **OS & Version**: macOS Ventura (13.0)

**Comment by bigtimebuddy** [comment]
Try this: 
https://jsfiddle.net/bigtimebuddy/mL2bcrdy/

It helps if you use the unicode character in the string and make sure it's included in the list of `chars` for creating the font:

```js
const nbsp = '\u00A0';
```

**Comment by Ericlm** [comment]
Okay, I'll take a look at it, thank you!
