### ISSUE TITLE
Asset.load(image) gets "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by ivan-work** [pixijs/pixijs#8824]
I've stuck with loading even a simple asset, could you please help with that?

I've started fresh react-scripts project: npx create-react-app my-app --template typescript

Then I placed 'bunny.png' to /public folder

And wrote Assets.load('bunny.png'); somewhere in the app.

I keep getting error:

```
Uncaught (in promise) Error: [Loader.load] Failed to load http://localhost:3000/bunny.png.
RangeError: Maximum call stack size exceeded
    at Loader.ts:148:1
    at async Promise.all (:3000/index 0)
    at async Loader.load (Loader.ts:153:1)
    at async AssetsClass._mapLoadToResolve (Assets.ts:689:1)
    at async AssetsClass.load
```

Based on my research it happens because for some reason the "ImageBitmapResource" class constructor somehow has recursion and it keeps calling itself.

I've checked it both on my local big project and separate example project: https://github.com/ivan-work/pixi-bug-test

### Environment
- Fresh react-scripts project (npx create-react-app my-app --template typescript)
- **`pixi.js` version**: _e.g. 7.0.2_
- **Browser & Version**: _e.g. Chrome / Firefox_
- **Running Example**: [_url_](https://github.com/ivan-work/pixi-bug-test)

**Comment by SuperSodaSea** [comment]
Seems to be duplicated with #8733. `create-react-app` have [some problems](https://github.com/pixijs/pixijs/issues/8733#issuecomment-1278953941) while transpiling conditional `super` call...

**Comment by SuperSodaSea** [comment]
There's one thing I'm curious about, the `ImageResource` should be used in preference to `ImageBitmapResource` in `Assets.load`... Need some investigation.

**Comment by ivan-work** [comment]
yeah, I think it's a duplicate, thanks for the link

**Comment by SuperSodaSea** [comment]
I found a workaround for this: just delete the `"last 1 safari version"` in `package.json`.
