### ISSUE TITLE
ERROR in ./node_modules/@pixi/accessibility/lib/AccessibilityManager.mjs 27:8-29 export 'utils' (imported as 'utils') was not found in '@pixi/core'

### ISSUE THREAD

**Issue by aram88888** [pixijs/pixijs#8830]
### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment]
This issue is insufficient. Please provide the details in the template and steps to reproduce the error.

**Comment by aram88888** [comment]
I have a project with pixie.js-legacy 6.5.2. It worked before. Now when I
install packages from scratch it installs @pixi version 7 and I got many
errors. When I install legacy 6.5.2 shouldn't it install all dependency
packages as before and work?

**Comment by bigtimebuddy** [comment]
That question cannot be answered unless you provide an example or reproduction of the issue.
