### ISSUE TITLE
Sprite sheet loader checking the wrong url here when checking if the other multipacks have already been added

### ISSUE THREAD

**Issue by MartinScottTombola** [pixijs/pixijs#8831]
https://github.com/pixijs/pixijs/blob/bce3b3e5b51ad28527e6284dc02c8e46eff113dd/packages/spritesheet/src/SpritesheetLoader.ts#L76

Feels like it should be doing

url.format(url.parse(r.url.replace(loader.baseUrl, '')));
rather than
url.format(url.parse(r.url));

**Comment by miltoncandelero** [comment]
`itemUrl` already has the `baseUrl` removed so if it was added before, it was added without it. I think that's why we don't check if it was removed.

Are you having issues with it? 🤔

**Comment by MartinScottTombola** [comment]
Yeah it looked like `r.url` still contained the baseUrl. I can get around it on my side tweaking a few things, but if what I'm seeing is right, anyone using basePath would be having the same issue.
