### ISSUE TITLE
Adding custom loaders in Assets.init doesn't work in Pixi 6.5.8

### ISSUE THREAD

**Issue by mterczynski** [pixijs/pixijs#8836]
### Expected Behavior
It's possible to add a custom loader by calling Assets.init

### Current Behavior

It's not possible to add a custom loader by calling Assets.init (tested on DDS loader)

### Possible Solution

Maybe there's some missing code for adding loaders in Assets.init

### Steps to Reproduce

- Download this repository with this branch: https://github.com/mterczynski/pixi-assets-testing/tree/pixi_6
- Run npm install
- Run npm start
- Take a look at the console

### Environment

- **`pixi.js` version**:  6.5.8
- **Browser & Version**: Brave
- **OS & Version**:  Windows

### Screenshots

<img width="525" alt="image" src="https://user-images.githubusercontent.com/27309340/200595732-ead30c7c-d245-4faf-95ca-538758a0b5ef.png">

<img width="449" alt="image" src="https://user-images.githubusercontent.com/27309340/200595611-3df79df0-9fd4-48af-817c-9a7bf22bdb1a.png">

### Extra thoughts

This works on PixiJS version 7 (main branch in the linked repository) but the DDS loader is added there by default so I'm not able to test if Assets.init is fixed on PIXI 7

**Comment by mterczynski** [comment]
If Assets.init works correctly on Pixi 7, please feel free to close this issue unless someone plans to add a patch to version 6.

**Comment by mterczynski** [comment]
@Giacom thanks for the solution!

**Comment by bigtimebuddy** [comment]
@mterczynski that is the correct way to install `loadDDS`

**Comment by mterczynski** [comment]
@bigtimebuddy Thanks for the reply

Which way do you mean? Do you mean that `extensions.add` is the correct way?

https://pixijs.download/dev/docs/PIXI.AssetInitOptions.html says: _"loader options to configure the loader with, currently only parsers!"_ so I thought that you can choose which parsers to use with `Assets`

**Comment by bigtimebuddy** [comment]
Yes `extensions.add`

**Comment by mterczynski** [comment]
I'm closing this issue then
Thanks for the help!
