### ISSUE TITLE
`pointertap` differences when upgrading to v7

### ISSUE THREAD

**Issue by adam-savard** [pixijs/pixijs#8837]
When upgrading from v6.5.3 to v7.0.3, I've noticed that the way our codebase has used the `pointertap` event has changed.

Previously, we would set `object.pointertap = function(){}`, which would ensure that only a single pointertap would exist at a time. From the docs, it looks like we're now supposed to do `.on('pointertap', function(){})`? Does this mean that there's no way to reproduce the behavior that existed in v6 and previous?

If the answer is "no", then that's fine, we'll find a way to refactor things, but the docs aren't super clear about this, nor can I find anything in the migration guide for v7!

- **`pixi.js` version**: 7.0.3
- **Browser & Version**: 107.0.5304.91
- **OS & Version**: Fedora 36

**Comment by bigtimebuddy** [comment]
Thanks for pointing this out. I can't find in the code for v6 where that behavior is happening or anywhere in the documentation. Anyone know where the property handlers are?

I'm pretty sure the answer here is no, but I'd like to get some clarity on where this originated so I can included it in the Migration Guide.

**Comment by bigtimebuddy** [comment]
I'm open to doing this for v7. My preference would be 1) to use `on` prefix (e.g. `onmouseover`) to be closer to the DOM, and 2) to make sure this is documented properly.

**Comment by adam-savard** [comment]
Using the `on` prefix would be nice to have; it would certainly make migration a little less painful for existing projects. 

Thanks for the quick answer, @bigtimebuddy , we'll discuss how to proceed with our codebase!

**Comment by adam-savard** [comment]
I'm on vacation until next week, so if no one else has submitted a PR by then, I'll likely look into it!
