### ISSUE TITLE
Missing DisplayObject getGlobalPosition types

### ISSUE THREAD

**Issue by FuriousTsunami** [pixijs/pixijs#8843]
PIXI.DisplayObject.getGlobalPosition's types look to be undefined in the code.

[https://pixijs.download/release/docs/PIXI.DisplayObject.html#getGlobalPosition](https://pixijs.download/release/docs/PIXI.DisplayObject.html#getGlobalPosition)

![Screenshot (1)](https://user-images.githubusercontent.com/69990380/201229405-d1397afc-542d-4021-98f7-3d66381de648.png)

The actual code has the getGlobalPosition method, but it isn't defined in the global.d.ts file (within @pixi/mixin-get-global-position)

Pixi version 7.0.3 (using npm)

**Comment by bigtimebuddy** [comment]
This worked without errors:
https://codesandbox.io/s/priceless-bell-2wmv8f?file=/src/index.ts

Could you please create a reproduction of this issue?

**Comment by FuriousTsunami** [comment]
It seems that when you disable "esModuleInterlop" this error occurs.

https://codesandbox.io/s/condescending-heyrovsky-xbv7hy

**Comment by bigtimebuddy** [comment]
`esModuleInterop` is required for PixiJS and it's 3rd-party dependencies

**Comment by FuriousTsunami** [comment]
Ok, thanks!
