### ISSUE TITLE
Unable to auto-detect a suitable renderer.

### ISSUE THREAD

**Issue by PierreTurnbull** [pixijs/pixijs#8853]
### Expected Behavior

Not to bug

### Current Behavior

The PIXI app bugs in a hard to describe way, quite choatically and randomly.
Here is a video to show the bug:

https://user-images.githubusercontent.com/33256529/202049293-492caef5-3c79-4d8b-8ff1-9a7767fd8afd.mp4

The navigator shakes chaotically and when I refresh the page, I get a white page with the following error in the console:
```
Uncaught Error: Unable to auto-detect a suitable renderer.
    at autoDetectRenderer (autoDetectRenderer.ts:67:1)
    at new _Application (Application.ts:107:1)
    at new Game (Game.js:11:1)
    at ./src/game/Game.js (Game.js:97:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/components/Game.js (App.js:11:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
```

It seems to appear when I save my changes, after an extended period of staying in my IDE.
Also, it disappears after some time, and the app works again, until it breaks yet another time.

### Possible Solution

🤷‍♂️ 

### Steps to Reproduce

I can give the source code of my project privately if needed.

### Environment

- **`pixi.js` version**: 7.0.4
- **Browser & Version**: Chrome 107.0.5304.110 
- **OS & Version**: MacOS Monterey 12.4
- **Running Example**: N/A

**Comment by bigtimebuddy** [comment]
Can you please create a minimal reproduction that reproduces this? There's a lot of things that could go wrong here. Hot module replacement and repeated React rendering might be creating too many WebGL contexts causing your browser to choke. Try creating your PixiJS Application outside of the React rendering. So far, I'm not convinced this is a PixiJS issue.

**Comment by PierreTurnbull** [comment]
Hi @bigtimebuddy , thank you for your answer. I dug a lot since last time and managed to get you a minimalist reproduction of the bug. You can paste the following code in an html file and open the latter on your browser. The bug will occur in a few seconds.

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	
</body>
<script src="https://pixijs.download/release/pixi.js"></script>
<script>
	let app = new PIXI.Application({ width: 640, height: 360 })
	document.body.appendChild(app.view)

	let graphics = null
	let texts = []

  app.ticker.add((delta) => {
		app.stage.removeChild(graphics)

		graphics = new PIXI.Graphics()
		addTextsToGraphics()
		graphics.endFill()

		graphics = graphics
		app.stage.addChild(graphics)
  });

	function addTextsToGraphics() {
		for (let i = 0; i < 100; i++) {
			let text = new PIXI.Text(`test ${new Date().getTime()}`, {
				fontFamily: "Arial",
				fontSize: 12,
				fontWeight: "bold",
				fill: 0xffffff,
				align: "center",
			})
			text.y = i * 20
			graphics.addChild(text)
		}
	}
</script>
</html>

**Comment by SuperSodaSea** [comment]
This code don't show any error on my browser even after waiting for a few minutes :thinking: (Chrome 106.0.5249.119, Windows 10)

**Comment by PierreTurnbull** [comment]
Here's the error I usually get (the bug does not trigger the same effects each time...) after refreshing the page:
<img width="394" alt="Capture d’écran 2022-11-19 à 13 47 29" src="https://user-images.githubusercontent.com/33256529/202851584-e5620d28-6d5e-450c-bb33-293a92ec7bcd.png">
And here is the video of an occurrence of the bug:

https://user-images.githubusercontent.com/33256529/202851659-9a32d888-a9f7-4aaa-ad11-ef351557766a.mp4

Is that enough? I'm not sure what a backtrace is.

**Comment by SuperSodaSea** [comment]
It seems that creating too many canvas (created by `Text`) will crash your graphics driver. I think it is not a PixiJS bug.

**Comment by SuperSodaSea** [comment]
Maybe you can try:

```diff
- app.stage.removeChild(graphics);
+ if(graphics) {
+     app.stage.removeChild(graphics);
+     graphics.destroy(true); // true means destroy all children
+ }
```

To destroy unused `Text`, preventing potential leak.

**Comment by bigtimebuddy** [comment]
You are creating a new Graphics for every frame @ 60fps (ticker.add => new PIXI.Graphics). This is allocating memory for every Graphic instance, which, overtime can add up! The crash you are experiencing is likely because of memory running out. 

This is not a bug. This is a memory leak. It is important, like anything JavaScript to be mindful of new objects you are creating.

**Comment by PierreTurnbull** [comment]
Oh that's right, it works fine now. I could have found the solution in the guide or API doc about Graphics. I thought the problem was about the Texts, which do not need explicit destruction.
Thanks for your help.

**Comment by Amansaxena001** [comment]
@bigtimebuddy if you GPU acceleration is disabled on your browser the you will get this error ( on mac ) and on windows it wont throw the error.
