### ISSUE TITLE
Renderers not created in PIXI.Application cannot render particle containers after v7

### ISSUE THREAD

**Issue by Redgeioz** [pixijs/pixijs#8855]
### Current Behavior
![image](https://user-images.githubusercontent.com/52198272/202343093-376e0eb2-aa9b-49d9-8297-d9fcf0d1baca.png)

### Steps to Reproduce
```jsx
let renderer = PIXI.autoDetectRenderer();

// undefined
console.log(renderer.plugins.particle);
```

### Environment

- **`pixi.js` version**: _above 7.0.0_

**Comment by SuperSodaSea** [comment]
I tried it on all 7.0.x and 7.1.0-alpha and nothing wrong happened. Can you provide more detail?

![image](https://user-images.githubusercontent.com/8724868/202346646-bbf610f9-3a8f-41af-8a67-bc60e64c37ff.png)

**Comment by Redgeioz** [comment]
Seems like installing @pixi/filter-glow 5.0 and pixijs will cause this problem. But in 7.0.4 it works normally.
