### ISSUE TITLE
Extract not available in renderer plugins

### ISSUE THREAD

**Issue by hilmia** [pixijs/pixijs#8858]
I'm using https://pixijs.download/release/pixi-legacy.min.js

### Expected Behavior
`const image = app.renderer.plugins.extract.image(graphic);` should return an image, by using the extract in plugins as advised in the documentation.

This was working before version 6

### Current Behavior
There is no extract in renderer.plugins

**Comment by SuperSodaSea** [comment]
https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide#extract-and-prepare-systems
https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide#new-async-extract-methods

In PixiJS v7 you need `await app.renderer.extract.image(...)`.

**Comment by bigtimebuddy** [comment]
Seems answered, closing.
