### ISSUE TITLE
Text stroke is not fully displayed after v7

### ISSUE THREAD

**Issue by Redgeioz** [pixijs/pixijs#8860]
### Expected Behavior
![image](https://user-images.githubusercontent.com/52198272/202779278-b1d578cd-8fea-450f-bdfc-852ceb8b314c.png)

### Current Behavior
![image](https://user-images.githubusercontent.com/52198272/202779195-013da2ca-9507-43f2-a742-94a51b3aee7f.png)

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/Nc4-XqFejJ_Yefndcogxj

### Environment

- **`pixi.js` version**: _above 7.0.0_
- **Browser & Version**: _Chrome 106.0.5249.119 & Edge 106.0.1370.47 & Firefox 106.0_
- **OS & Version**: _Windows 10_

**Comment by SuperSodaSea** [comment]
It seems to be caused by #8501:

```diff
- if (!Text.nextLineHeightBehavior || lineHeight - fontProperties.fontSize < 0)
+ if (lineHeight - fontProperties.fontSize < 0)
```

https://github.com/pixijs/pixijs/blob/702940412d05160fafa362066bdc280181f6fc49/packages/text/src/Text.ts#L264-L269

Removing the `if` and directly set `linePositionYShift` to 0 can get the correct result.

@bigtimebuddy Do you have any idea?

**Comment by bigtimebuddy** [comment]
This is also an issue in 6.5.x if `nextLineHeightBehavior` is enabled:
https://www.pixiplayground.com/#/edit/dOhIpfXlsJMAo2TPKvFkK

Workaround is to use `padding`:
https://www.pixiplayground.com/#/edit/Suh_Op__2Hdf7vnt5bwG7

This seems like a bug. We should be accounting for the stroke width for the canvas height.

**Comment by bigtimebuddy** [comment]
This as introduce here #7386

**Comment by Thugwife1111** [comment]
> ### Expected Behavior
> ![image](https://user-images.githubusercontent.com/52198272/202779278-b1d578cd-8fea-450f-bdfc-852ceb8b314c.png)
> 
> ### Current Behavior
> ![image](https://user-images.githubusercontent.com/52198272/202779195-013da2ca-9507-43f2-a742-94a51b3aee7f.png)
> 
> ### Steps to Reproduce
> https://www.pixiplayground.com/#/edit/Nc4-XqFejJ_Yefndcogxj
> 
> ### Environment
> * **`pixi.js` version**: _above 7.0.0_
> * **Browser & Version**: _Chrome 106.0.5249.119 & Edge 106.0.1370.47 & Firefox 106.0_
> * **OS & Version**: _Windows 10_
