### ISSUE TITLE
useContextAlpha not marked as deprecated in docs

### ISSUE THREAD

**Issue by terekite** [pixijs/pixijs#8861]
### Current Behavior

The constructors for `Application`, `Renderer`, `CanvasRenderer`, etc. have a boolean option flag `useContextAlpha` . Usage of this flag is deprecated and is marked as such in the code itself ([CanvasRenderer.ts](https://github.com/pixijs/pixijs/blob/2e78ba20e4bb33f2a5e63b379811582d7f67ed26/packages/canvas-renderer/src/CanvasRenderer.ts#:~:text=boolean%7D%20%5Boptions.-,useContextAlpha,-%3Dtrue%5D%20%2D%20Pass%2Dthrough), in the getter for `useContextAlpha`) but isn't marked as such in any of the documentation of options for those constructors.

### Possible Solution

Since @deprecated can't be used for parameters, the simplest fix would be to note `useContextAlpha` as deprecated in the text. 

- **`pixi.js` version**: 7.x
- **Browser & Version**: N/A
- **OS & Version**: N/A
- **Running Example**: N/A

**Comment by bigtimebuddy** [comment]
Thanks for reporting this @terekite. This option definitely needed a little clean-up from a big refactor we did in 7.0.0 for the Renderers. Added a PR to fix.
