### ISSUE TITLE
`BitmapText` has its own `fontSize`, which is initialized when `BitmapText` is constructed, and won't be changed when the `BitmapFont` is changed.

### ISSUE THREAD

**Issue by Thugwife1111** [pixijs/pixijs#8862]
![11734FC3-E815-406A-9FD5-054AB8B430EA](https://user-images.githubusercontent.com/118017144/202838872-24854daa-24c6-4a78-8e12-353e4357a51f.jpeg)
![948933E5-F61C-4831-9A7E-322BECA30D97](https://user-images.githubusercontent.com/118017144/202838873-f14aaa5b-73d9-4871-8957-0c448b89841e.jpeg)
        `BitmapText` has its own `fontSize`, which is initialized when `BitmapText` is constructed, and won't be changed when the `BitmapFont` is changed.
I think we can change this behavior to "If `BitmapText.fontSize` is not specified, the fontSize will be obtain from the `BitmapFont` dynamically".
Perhaps we can also auto detect the change of `BitmapFont` and no need to call `updateText()` manually.

_Originally posted by @SuperSodaSea in https://github.com/pixijs/pixijs/issues/8758#issuecomment-1285504728_

**Comment by Thugwife1111** [comment]
var app = new PIXI.Application({
    width: window.innerWidth,
    height: window.innerHeight,
    backgroundColor: 0x000000
});

document.body.appendChild(app.view);

PIXI.BitmapFont.from("Arial", {
  fontFamily: "Arial",
  fontSize: 50,
  fill: 0xffffff,
}, {
  chars: ['1'],
});
let bitmapText = new PIXI.BitmapText("1", {
  fontName: "Arial",
});
bitmapText.position.set(500, 500);
app.stage.addChild(bitmapText);

setTimeout(() => {
    PIXI.BitmapFont.from("Arial", {
        fontFamily: "Arial",
        fontSize: 100,
        fill: 0xffffff,
    });
    let bitmapText2 = new PIXI.BitmapText("1", {
        fontName: "Arial",
    });
    bitmapText2.position.set(400, 400);
    app.stage.addChild(bitmapText2);
    bitmapText.updateText();
}, 1000);

**Comment by SuperSodaSea** [comment]
Please describe the problem you are facing more clearly.
