### ISSUE TITLE
I can't add my own loader parser to PIXI.Assets

### ISSUE THREAD

**Issue by famibee** [pixijs/pixijs#8870]
PixiJS API Documentation https://pixijs.download/dev/docs/PIXI.Assets.html
  > More types can be added fairly easily by creating additional loader parsers.
  > （追加のローダーパーサーを作成することで、より多くのタイプをかなり簡単に追加できます。）

I tried to create a .sn load parser, but
　　（と書かれているので .sn ロードパーサーを作ろうとしたが）

export class AssetsClass
public async init(options: AssetInitOptions = {}): Promise<void>

I haven't even looked at options.loader in No implementation exists.
It doesn't even exist as of v7.0.0.
https://github.com/pixijs/pixijs/tree/cd075fa935fa5b988f0874f39222c673840553dc
　　（で options.loader を見もしていない。実装が存在しない。）
　　（v7.0.0 時点でも存在しない。）

"At least, please put a note such as [Under implementation] in the document." I didn't notice until I looked at the source.
　　（せめてドキュメントに【実装中】などと注意書きをして下さい。ソースを見るまで気付きませんでした。）

- **`pixi.js` version**: _e.g. 7.0.4_

**Comment by SuperSodaSea** [comment]
You can learn from other LoaderParser, just like [loadJson](https://github.com/pixijs/pixijs/blob/702940412d05160fafa362066bdc280181f6fc49/packages/assets/src/loader/parsers/loadJson.ts):

```ts
import { settings, utils, extensions, ExtensionType } from '@pixi/core';
import { LoaderParserPriority } from './LoaderParser';

import type { LoaderParser } from './LoaderParser';

export const loadSN = {
    extension: {
        type: ExtensionType.LoadParser,
        priority: LoaderParserPriority.Low,
    },

    test(url: string): boolean
    {
        return (utils.path.extname(url).includes('.sn'));
    },

    async load<T>(url: string): Promise<T>
    {
        const response = await settings.ADAPTER.fetch(url);

        const arrayBuffer = await response.arrayBuffer();
        
        // Do whatever you want with the arrayBuffer...
    },
} as LoaderParser;

extensions.add(loadSN);
```

**Comment by famibee** [comment]
こちらでも簡単に動作確認できました、動作例の提示ありがとうございました。
PIXI.Assets ページにも loadJson へのリンクなどを貼っておくと同じように詰まった人が助かると思います。

**Comment by bigtimebuddy** [comment]
If you or others finding this issue need more examples of using this API, I created both these extensible asset loaders:

* https://github.com/pixijs/gif/blob/main/src/AnimatedGIFAsset.ts
* https://github.com/pixijs/sound/blob/main/src/soundAsset.ts

We've discussed creating a guide for usage, but haven't gotten to it yet.

**Comment by famibee** [comment]
Maybe it's okay without a polite explanation. If you have TypeScript / JavaScript code, I think everyone will understand.
Because the code crosses borders!
　　（たぶん懇切ていねいな解説はなくても大丈夫です。TypeScript / JavaScript のコードがあれば、みんな分かると思います。）
　　（コードは国境を越えるので！）
