### ISSUE TITLE
The example hacks which are hosted on pixiplayground.com are all editable by anyone

### ISSUE THREAD

**Issue by AndreRoelofs** [pixijs/pixijs#8878]
I noticed that the demos weren't doing what they were supposed to which is fine. But then I decided to alter the demo in the browser and found out that I could not open the original code as the code had now changed. These changes were also made on different browsers, when using a VPN and even after clearing all my cookies. By editing the code I had changed the source stored on the server which is obviously not ideal. The 2 demo's in question are under the header PIXI.Sprite for version 5, called "First demo" and "Second demo". These are the only ones I've checked.

https://github.com/pixijs/pixijs/wiki/v5-Hacks

**Comment by bigtimebuddy** [comment]
I highly recommend to _not_ using pixiplayground for this reason. Anyone that is making examples should use jsfiddle, codepen, codesandbox, etc.

@ivanpopelyshev added all these perhaps he could fix or convert to something that immutable.

**Comment by bigtimebuddy** [comment]
I'm going to close this as _won't fix_ since support for v5 hacks page isn't a priority. If someone wants to fix the examples, feel free!
