### ISSUE TITLE
events.resolution not working like Interactions.resolution

### ISSUE THREAD

**Issue by pagoru** [pixijs/pixijs#8895]
### Expected Behavior

6.x.x version: 
![image](https://user-images.githubusercontent.com/1551265/203851455-57f063c6-6e4a-43b4-b748-de131b7f7907.png)

### Current Behavior

7.x.x version:
![image](https://user-images.githubusercontent.com/1551265/203851395-9edaa7ae-b101-45ec-bb49-882dcc23a87a.png)

### Steps to Reproduce

`app.renderer.events.resolution = 3` does not work like `app.renderer.plugins.interaction.resolution = 3` (in previous versions)

### Environment

- **`pixi.js` version**: _e.g. 7.0.4_
- **Browser & Version**: _e.g. Firefox 107_
- **OS & Version**: _e.g. Win 11_

**Comment by bigtimebuddy** [comment]
Can you provide a runnable example (not just a screenshot)? That would be helpful. Thanks.

**Comment by pagoru** [comment]
Sure @bigtimebuddy https://pagoru-physics-preview-crfsvg2g6ch0.deno.dev/

**Comment by bigtimebuddy** [comment]
Can you please provide some un-minified code? It's hard to tell what's going on there.

It looks like you are not adjusting the Renderer's resolution to match events. Try setting `renderer._view.resolution = 3` as well. In a future release, we added a setter on Renderer and CanvasRenderer that handles both the events and the renderer resolution.

**Comment by pagoru** [comment]
Sorry for the minified version. I tried everything that I know on the book... Working perfect with `renderer._view.resolution`, thanks!
![image](https://user-images.githubusercontent.com/1551265/204129318-7d29159f-a0a0-4e71-810c-e54ff21529cc.png) 🚀

**Comment by bigtimebuddy** [comment]
Great, glad that worked!
