### ISSUE TITLE
BitmapText doesn't work in worker

### ISSUE THREAD

**Issue by ImAwesome** [pixijs/pixijs#8901]
Problem is that PIXI.Assets.load for fonts `fnt` and `xml` uses `globalThis.DOMParser()` inside, which does not exist in worker's context

```
class XMLStringFormat {
    static test(data) {
      if (typeof data === "string" && data.includes("<font>")) {
        const xml = new globalThis.DOMParser().parseFromString(data, "text/xml");
        return XMLFormat.test(xml);
      }
      return false;
    }
    static parse(xmlTxt) {
      const xml = new globalThis.DOMParser().parseFromString(xmlTxt, "text/xml");
      return XMLFormat.parse(xml);
    }
  }
```

- **`webworker.js` version**:  7.0.4
- **Browser & Version**: all
- **OS & Version**: _e.g. all

**Comment by bigtimebuddy** [comment]
My suggestion is that we add a new DOMParser entry to the ADAPTER. For webworker and node bundles and use xmldom package instead of window.DOMParser. These things should be roughly equivalent.

**Comment by ImAwesome** [comment]
Thank you for fast response, you are georgeous!
