### ISSUE TITLE
Asset Loader: Could not be loaded as we don't know how to parse it, ensure the correct parser has being added

### ISSUE THREAD

**Issue by driuqzy** [pixijs/pixijs#8907]
Using https://pixijs.io/guides/basics/assets.html I get console warning:

"[Assets] https://imagedelivery.net/AS_oRD30zjCHIwJTbRDRrw/023d2eb0-fa3d-4043-5548-06b1b72fab00/700 could not be loaded as we don't know how to parse it, ensure the correct parser has being added"

I'm assuming it expects a file extension in the url like ".png" or ".webp". However I'm using cloudflare for CDN image delivery, and it doesn't allow for file extensions. It sends the most efficient format per their docs: https://developers.cloudflare.com/images/cloudflare-images/serve-images/ 

Any suggestions? i.e.

a) Can I give pixi.js asset loader a hint as to what the file format will be?
b) Can pixi.js figure out the format based on the response the way a browser would if this image url was in the `<img src={}>`?

**Comment by bigtimebuddy** [comment]
Assets doesn't yet provide a way to define the file type/format. But it's a good feature suggestion. The old loader had a way to force a type.

There are a couple ideas for workarounds. 

First, you could use HTMLImageElement.

```js
import { Texture } from 'pixi.js';

const texture = await new Promise(resolve => {
  const img = new Image();
  img.onload = () => Texture.from(img);
  img.src = 'https://imagedelivery.net/AS_oRD30zjCHIwJTbRDRrw/023d2eb0-fa3d-4043-5548-06b1b72fab00/700';
});
```

That's nice, but doesn't get the integration with Assets. 

Another workaround, would be to create your on load parser plugin for Assets, which would automatically handle these requests maybe by detecting anything from imagedelivery.net and basically do the same thing as above. _I have not tested this code, it's just a starting point._

```js
import { extensions, ExtensionType, Texture } from 'pixi.js';

const imageDelivery = {
  extension: ExtensionType.LoadParser,
  test: (url) => url.startsWith('https://imagedelivery.net'),
  async load(src) {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => resolve(Texture.from(img));
      img.onerror = reject;
      img.src = src;
    });
};

extensions.add(imageDelivery);
```

**Comment by driuqzy** [comment]
Nice, that 2nd option did the trick!

Here's what worked for me with the addition of cross-origin.

```javascript
  const imageDelivery = {
    extension: ExtensionType.LoadParser,
    test: (url) => url.startsWith('https://imagedelivery.net'),
    async load(src) {
      return new Promise((resolve, reject) => {
        const img = new Image()
        img.crossOrigin = 'anonymous'
        img.onload = () => resolve(Texture.from(img))
        img.onerror = reject
        img.src = src
      })
    },
  }

  extensions.add(imageDelivery)
```

**Comment by GoodBoyDigital** [comment]
hey! so was thinking about this a little... really what are looking for is the ability to directly say what parser to use rather than running any kind of tests to determine what to do.

With that in mind rather than being able to override the format (which is used in _some_ tests) we add a new property to a `LoadAsset` which directly lets you specify the plugin by name. Eg:

```
Assets.load({
   src: 'https://path/to/image',
   parser: 'texture' // or `loadTexture'
});
```

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital the only tough think about that, is we currently don't have IDs associate with each parser. But forcing a parser (skipping test) makes a ton of sense.
