### ISSUE TITLE
A ttf font with a space in the basename results in an error when loading it with Assets.load()

### ISSUE THREAD

**Issue by Giacom** [pixijs/pixijs#8910]
### Expected Behavior

Assets.load() should be able to handle a font file with a space in its name, which is a very common occurrence for TTF files.

### Current Behavior

```typescript
    PIXI.Assets.add("font_space", "assets/Air Americana.ttf");
    PIXI.Assets.load("font_space").then(() => {
       // Never reached due to error printed below
        app.stage.addChild(new PIXI.Text("Hello world - Font with space!", {
            fontFamily: "Air Americana"
        }));
    });

    // Works though:
    PIXI.Assets.add("font_nospace", "assets/AirAmericana.ttf");
    PIXI.Assets.load("font_nospace").then(() => {
        app.stage.addChild(new PIXI.Text("Hello world - Font no space!", {
            fontFamily: "AirAmericana"
        }));
    });
```

When you load a font with Assets.load() it results in this error: 

```
        Uncaught (in promise) Error: [Loader.load] Failed to load http://localhost:8080/assets/Air Americana.ttf.
        SyntaxError: The source provided ('url(http://localhost:8080/assets/Air Americana.ttf)') could not be parsed as a value list. (at game.bundle.js:1301:17)
            at game.bundle.js:1301:17
            at async Promise.all (:8080/index 0)
            at async Loader.load (game.bundle.js:1306:5)
            at async AssetsClass._mapLoadToResolve (game.bundle.js:713:26)
            at async AssetsClass.load (game.bundle.js:638:17)
        (anonymous) @ game.bundle.js:1301
        Promise.then (async)
        main @ game.bundle.js:34470
        ./src/index.ts @ game.bundle.js:34482
        __webpack_require__ @ game.bundle.js:37515
        (anonymous) @ game.bundle.js:38599
        (anonymous) @ game.bundle.js:38601
```

### Possible Solution

Might be caused by the font loading extension, probably due to the fact that it doesn't escape the spaces.

### Steps to Reproduce

1. Download, extract and run the barebones demo project linked below ("npm i", "npm run local:buildRun")
2. Open the webpage and see that there is an error when the `index.ts` file tries to load the font with a space in it.
3. Note it successfully loads the same font without a space in its name just fine.

### Environment

- **`pixi.js` version**: 7.0.4
- **Browser & Version**:  107.0.1418.56
- **OS & Version**: Windows 11
- **Running Example**:  [font_with_space_bug_demo.zip](https://github.com/pixijs/pixijs/files/10123136/font_with_space_bug_demo.zip)

**Comment by SuperSodaSea** [comment]
I'll fix this later.
