### ISSUE TITLE
Reaction to pointer events of children contained in interactive containers

### ISSUE THREAD

**Issue by MasatoMakino** [pixijs/pixijs#8922]
- [x] Before opening an issue, I checked if a similar issue exists by searching existing issues.

I report that I have discovered a change in the behavior of interactive containers.

### Expected Behavior

Display Objects that are interactive will respond to pointer events regardless of the parent container settings.

### Current Behavior

Display Objects may not respond to pointer events if the parent container is interactive.

### Steps to Reproduce

- Create interactive containers
- Create a rectangle 1 with interactive = false on the front.
- Create a rectangle 2 with interactive = true on the back.
- Add rectangles 1 and 2 to the interactive container.

![](https://www.evernote.com/l/AAkWKBk9D7FFuqbqh7-PhlrsTXtsSkGcqNAB/image.png)

When I click on the overlapping area of rectangles 1 and 2, rectangle 2 responds in v6.5.7, but not in v7.0.4.

Here is the code for reproduction.
[jsfiddle v6.5.7](https://jsfiddle.net/MasatoMakino/ocxm3s7j/14/)
[jsfiddle v7.0.4](https://jsfiddle.net/MasatoMakino/ysgdfk83/5/)
Open the console and check the pointer event listener.

### Question

Is this change a planned change in EventSystem? Or is it an unintended bug?

If it is a planned change, I would be happy to leave this issue as a record for users to understand. If this is an unintended bug, I'd be happy to help you resolve it.

### Environment

- **`pixi.js` version**: v6.5.7 and v7.0.4
- **Browser & Version**:  Chrome 107.0.5304.121
- **OS & Version**:  macOS 12.6.1

**Comment by pagoru** [comment]
It doesn't occur anymore on `7.0.5`!

**Comment by MasatoMakino** [comment]
[jsfiddle v7.0.5](https://jsfiddle.net/MasatoMakino/suentbzj/1/)

The problem was reproduced in Pixi.js 7.0.5

**Comment by bigtimebuddy** [comment]
This is an intentional change in PixiJS to bring the interaction behavior more consistent with the DOM.

Here's the same example with DOM elements:

https://jsfiddle.net/bigtimebuddy/k08xsfdt/

**Comment by MasatoMakino** [comment]
Thanks for your investigations.

The default value of the interactive property in Pixi.js is false.
https://pixijs.download/dev/docs/PIXI.DisplayObject.html#interactive

With that in mind, if we were to reproduce this issue with DOM elements, we would assume that #box2's `pointer-events` should be `false`.
https://jsfiddle.net/MasatoMakino/sfjq7zr2/2/
In this case, the behavior is the same as in Pixi.js v6.5.7.

I think the behavior of v6.5.7 is consistent in terms of reproducing the behavior of DOM elements. What do you think about it?

**Comment by miltoncandelero** [comment]
> This is an intentional change in PixiJS to bring the interaction behavior more consistent with the DOM.
> 
> Here's the same example with DOM elements:
> 
> https://jsfiddle.net/bigtimebuddy/k08xsfdt/

I understand the feeling but making a button with a background + text and icon on top is the simplest way to make them and have them look good. Having those elements which were set to ignore interactions to block interactions seems counter intuitive. 

Maybe we need another flag that is something like "ignoreInteraction"?

**Comment by Zyie** [comment]
Hey @MasatoMakino 

I have made this PR #9089 which should help unblock you here once it lands in Pixi

We now have `interactive = 'none'` and `interaction = 'passive'`. 

- `none` would ignore all interaction. So in your demo you could set `box2.interactive = 'none'`
- `passive` ignores interaction on itself and on non-interactive children. So alternatively you could just set `interactiveContainer = 'passive'`
