### ISSUE TITLE
cannot appear canvas if forceCanvas: true and view specified as PIXI.Application option

### ISSUE THREAD

**Issue by azarakko** [pixijs/pixijs#8924]
cannot appear canvas if forceCanvas: true and view specified as PIXI.Application option

It happens in code like below

```js
const app = new PIXI.Application({
  view: document.querySelector("#cv"),
  forceCanvas:true 
});
```

### Expected Behavior
appearing canvas if forceCanvas: true and view specified as PIXI.Application option

### Current Behavior
cannot appear canvas if forceCanvas: true and view specified as PIXI.Application option

### Possible Solution

maybe missing `view: options.view `to startupOptions for CanvasRenderer

https://github.com/pixijs/pixijs/blob/7151ba78400056e54805c9dd7bffb1f422b73ad6/packages/canvas-renderer/src/CanvasRenderer.ts#L232-L237

### Steps to Reproduce

following reproduction code
https://jsfiddle.net/bwrg8j6o/11/

### Environment
lib:
pixi.js 7.0.4
pixi-legacy.js 7.0.4

browser:
Chorme  108.0.5359.71

OS:
Windows 11 21H2

**Comment by bigtimebuddy** [comment]
Good catch @azarakko :+1:
