### ISSUE TITLE
PIXI.Mesh can not switcing textures on Canvas

### ISSUE THREAD

**Issue by oretti** [pixijs/pixijs#8929]
### Expected Behavior
Succeed in switching textures under the following conditions.
- use Canvas. PIXI.Application({ forceCanvas:true })
- use PIXI.Mesh and change tint property.

### Current Behavior
Can not switching textures.
(I found when using PIXI.BitmapText.)

### Possible Solution
I think the following is probably the cause.
https://github.com/pixijs/pixijs/blob/a984e4cfde0b5c6579ddd085a2bb6361b4350b36/packages/canvas-mesh/src/CanvasMeshRenderer.ts#L118-L129
CanvasMeshRenderer caches images when changing tints, but does not re-cache images when changing textures.

### Steps to Reproduce
See jsfiddle
https://jsfiddle.net/pegta1Lr/1/
- **Canvas**: Image X -> X (1 sec.)
- **WebGL(Expected Behavior)**: Image X -> Y (1 sec.)

### Environment

- **`pixi.js` version**: v6.5.8 / v7.0.4
- **Browser & Version**: Chrome 107.0.5304.123 / Firefox 107.0.1
- **OS & Version**: Windows 11

**Comment by bigtimebuddy** [comment]
Thank you @oretti for reporting. And the example was extremely helpful making a fix.
