### ISSUE TITLE
In worker environment not support CanvasRenderingContext2D

### ISSUE THREAD

**Issue by laochen** [pixijs/pixijs#8938]
In worker environment，error info："Uncaught ReferenceError: CanvasRenderingContext2D is not defined "
relevant code location：
1. bundle/pixi-webworker/src/adapter.ts
line 14: 
    getCanvasRenderingContext2D: () => CanvasRenderingContext2D,
probably should use
    getCanvasRenderingContext2D: () => OffscreenCanvasRenderingContext2D,
2. packages/settings/src/adapter.ts
line 43:
    getCanvasRenderingContext2D: () => CanvasRenderingContext2D,
probably should use
    getCanvasRenderingContext2D: () => OffscreenCanvasRenderingContext2D,

### Environment

`pixi.js` version:  v7.1.0-alpha

**Comment by SuperSodaSea** [comment]
It's my fault, I will fix it later.
