### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by Simon-He95** [pixijs/pixijs#8939]
Do you want to do some code tidying and refactoring?
For example, use find to replace for and break, some if conditions return early, etc.
I'd be happy to try it out if needed.

**Comment by bigtimebuddy** [comment]
@Simon-He95 we welcome any opportunities to improve the code! For superficial changes (style improvements, organization), if you could bucket those into a single PR, that would be helpful. For other refactor changes that impact the logic significantly, it's preferable to keep the PRs small and provide some validation that it didn't break (example, codepen, etc). 

We appreciate the willingness to help! Thanks.
