### ISSUE TITLE
The loadBitmapFont parser does not work with URLs that contain GET params, e.g: examples/assets/bitmap-font/desyrel.xml?version=1.0.0

### ISSUE THREAD

**Issue by Giacom** [pixijs/pixijs#8942]
### Expected Behavior

I should be able to load any assets with a URL that contains GET params.

### Current Behavior

The [loadBitmapFont](https://github.com/pixijs/pixijs/blob/dev/packages/text-bitmap/src/loadBitmapFont.ts) parser currently checks and tests to use the parser by seeing if the extension of the URL is inside a list. This fails with URLs with GET params since `extname` will not remove the params.

__Another possible issue__, other parsers only work since they do LIKE / includes() checks, this means it works but it can result in issues where a GET param contains a ".json" string for example.

### Possible Solution

Change all parsers to use a new helper function that properly strips the GET params from the URL to check for.

### Steps to Reproduce

1. Open https://pixijs.io/examples/#/text/bitmap-text.js
2. Add a GET param to the URL, e.g: `examples/assets/bitmap-font/desyrel.xml?version=1.0.0`

### Environment

- **`pixi.js` version**: 7.0.4
- **Browser & Version**: Edge
- **OS & Version**: Windows 11
- **Running Example**: 

```typescript
const app = new PIXI.Application({ background: '#1099bb' });
document.body.appendChild(app.view);

PIXI.Assets.load('examples/assets/bitmap-font/desyrel.xml?version=1.0.0').then(() => {
    const bitmapFontText = new PIXI.BitmapText(
        'bitmap fonts are supported!\nWoo yay!', {
            fontName: 'Desyrel',
            fontSize: 55,
            align: 'left',
        },
    );

    bitmapFontText.x = 50;
    bitmapFontText.y = 200;

    app.stage.addChild(bitmapFontText);
});
```

**Comment by SuperSodaSea** [comment]
https://github.com/pixijs/pixijs/blob/960476fc60883470b093f1e629a0df4ba225a249/packages/utils/src/path.ts#L518

We should start searching before the first `?` or `#` in `path.extname()`. Other methods like `path.basename()` and `path.parse()` may also needed to be rewritten.

**Comment by bigtimebuddy** [comment]
Our path.basename, path.ext, etc are support to normalize either URLs or native paths (to support browsers and node). I think we need some more normalization around searchParams and hash.
