### ISSUE TITLE
Property 'addEventListener' does not exist on type 'Container<DisplayObject>'.ts(2339)

### ISSUE THREAD

**Issue by twincle** [pixijs/pixijs#8943]
### Current Behavior
![image](https://user-images.githubusercontent.com/12149017/205916483-9fe32b05-783b-49dd-bef8-f43e2e222a5b.png)

These three have the same issue. Property 'addEventListener' does not exist on type 'Container<DisplayObject>'.ts(2339)

```
import { Event } from '@pixi/events';
import { EventEmitter } from '@pixi/utils';

const app = new Application();

app.stage.addEventListener('click', () => {});
app.stage.addListener('click', () => {});
app.stage.on('click', () => {});

```

### Environment

- **`pixi.js` version**: _6.5.8_
- **other**: _webpack  typescript_
- **Browser & Version**: _edge 107.0.1418.62 (x64)_
- **OS & Version**: _Windows 11_

**Comment by bigtimebuddy** [comment]
This can happen if you recently upgraded and types are messed up. Can you completely uninstall Pixi and reinstall? If that doesn't work, please provide a reproduction.

**Comment by twincle** [comment]
[this repository](https://github.com/twincle/pixi-test), I try completely uninstall Pixi and reinstall, no use...

**Comment by robfuscator** [comment]
I have some related issues.

**1.**

The `generateTexture()` method should return a `RenderTexture`, but according to the type system returns `void`.

```ts
app.renderer.generateTexture(someGraphic); // Returns nothing
```

**2.**

Somehow, it's not possible for me to append objects of type `ICanvas` to the DOM.

```ts
someContainer.appendChild(app.view);

// Fails with:
// Argument of type 'ICanvas' is not assignable to parameter of type 'Node'.
```

---

The underlying JavaScript code appears to work fine, since I can workaround the errors by using `@ts-ignore`, but that kind of defeats the purpose. This happens in a freshly created project using `pixi.js` version 7.0.4.

If I should create a new issue because it's too loosely related, please tell me.

**Comment by SuperSodaSea** [comment]
@robfuscator:

> **1.**
> 
> The `generateTexture()` method should return a `RenderTexture`, but according to the type system returns `void`.
> 
> ```ts
> app.renderer.generateTexture(someGraphic); // Returns nothing
> ```

https://github.com/pixijs/pixijs/blob/4177cf7306fa8b072349c891fa1742e82a7288f6/packages/core/src/IRenderer.ts#L119

This seems to be a mistake. Can you create a new issue for this? I will fix it later.

> **2.**
> 
> Somehow, it's not possible for me to append objects of type `ICanvas` to the DOM.
> 
> ```ts
> someContainer.appendChild(app.view);
> 
> // Fails with:
> // Argument of type 'ICanvas' is not assignable to parameter of type 'Node'.
> ```

See #8820:

```ts
const app = new Application<HTMLCanvasElement>();
document.body.appendChild(app.view);
```

**Comment by robfuscator** [comment]
Thank you, @SuperSodaSea, will do.

**Comment by SuperSodaSea** [comment]
@twincle Adding `"esModuleInterop": true` to your `tsconfig.json` can solve your problem.

> https://github.com/pixijs/pixijs/issues/8843#issuecomment-1311782429
> `esModuleInterop` is required for PixiJS and it's 3rd-party dependencies

**Comment by twincle** [comment]
> @twincle Adding `"esModuleInterop": true` to your `tsconfig.json` can solve your problem.
> 
> > [#8843 (comment)](https://github.com/pixijs/pixijs/issues/8843#issuecomment-1311782429)
> > `esModuleInterop` is required for PixiJS and it's 3rd-party dependencies

THIS WILL WORK! THANKS!
