### ISSUE TITLE
IRenderer.generateTexture() returns void according to type system

### ISSUE THREAD

**Issue by robfuscator** [pixijs/pixijs#8947]
### Expected Behavior

`IRenderer.generateTexture()` returns a `RenderTexture` according the [docs](https://pixijs.download/release/docs/PIXI.Renderer.html#generateTexture). I would expect the TypeScript definitions to reflect that.

### Current Behavior

`IRenderer.generateTexture()` indeed does return a `RenderTexture`, but according to TypeScript definitions, it returns `void` which confuses my editor (VSCodium) & build system (Vite).

### Possible Solution

The problematic line of code was already identified by @SuperSodaSea in #8943:

https://github.com/pixijs/pixijs/blob/4177cf7306fa8b072349c891fa1742e82a7288f6/packages/core/src/IRenderer.ts#L119

### Steps to Reproduce

Use `IRenderer.generateTexture()` in a TypeScript environment and check the returned object.

### Environment

- **`pixi.js` version**: _7.0.4_
- **Browser & Version**: _Not applicable_
- **OS & Version**: _Fedora 37_

**Comment by znorman-harris** [comment]
I noticed this too. Not sure if it was right or not, but I managed to use the `GenerateTextureSystem` to make textures which worked great (at least no type errors from TypeScript). It was another thing I needed to track for my PIXI viewer, but was pretty easy to implement. Here's a snippet of my code to make it if that helps.

```typescript
    this.app = new Application({
      ...{
        antialias: true,
        resizeTo: this.el,
        backgroundColor: 0x4e4e52,
        width: this.el.clientWidth,
        height: this.el.clientHeight
      },
      ...options
    });
    this.stage = this.app.stage;
    this.stage.interactive = true;

    // create texture system
    this.texture = new GenerateTextureSystem(this.app.renderer);

   // ------------------------------

    // how i used it
    const texture = this.texture.generateTexture(this.app.stage, {
      scaleMode: SCALE_MODES.LINEAR,
      region: rect,
      resolution: this.getScale()
    });
```

I didn't see this in the V7 migration, so not sure if there is a bug with the types or if this is the new way to do it.
