### ISSUE TITLE
PIXI-v7 `DisplayObject.on(...)`  typing not allow to dispatch custom event

### ISSUE THREAD

**Issue by cuire** [pixijs/pixijs#8957]
I had code from pixiv6 code, that still works.
```ts
class Test extends Graphics {
    constructor() {
        super();
        this.interactive = true;
        this.on('init', (event) => {
          console.log('init', event);
        });
        this.emit('init', 'Tets event');
    }
}
```
But my IDE doesnt want this to happen.
![image](https://user-images.githubusercontent.com/81014305/206548805-626861b4-6b5a-4424-b333-7d1fac5a8c33.png)
Why it was locked, and if its planned how to handle it now?

**Comment by bigtimebuddy** [comment]
We added type-hinting for events to make it easier on users. But the good news is this is extensible:

```ts
declare namespace GlobalMixins {
  interface DisplayObjectEvents {
    init: [string];
  }
}
```

You just need to add your `init` event to the DisplayObjectEvents global mixins.

**Comment by cuire** [comment]
That approach is suitable. 
But its create a huge problem, programmer doesnt know if event is related to that class. 

Isn't it be better to use generic types for events and pass it down the class tree? Like so:

```ts
type TestEvents = {
    init: [string];
}

class Test extends Graphics<TestEvents> {
    constructor() {
        super();
        this.interactive = true;
        this.on('init', (event) => {
          console.log('init', event);
        });
        this.emit('init', 'Tets event');

        this.on('pointerdown', (event) => {console.log(event)});
    }
}
```
I see that package relies heavily on mixins, and its not an easy task and breaks a lot of code. But maybe in future releases it'll make code cleaner.

**Comment by SuperSodaSea** [comment]
I prefer to add examples for how to add custom event types in the document, rather than modify the existing types.

**Comment by bigtimebuddy** [comment]
Yeah, GlobalMixins is more of a workaround. We need a per-object way to do this.

**Comment by miltoncandelero** [comment]
The workarround explodes further down the line
using something like this:
```
declare namespace GlobalMixins {
	interface DisplayObjectEvents {
		[key: string]: any;
	}
}
```

results in 
```
Argument of type 'Sprite' is not assignable to parameter of type 'DisplayObject'.
  Types of property 'children' are incompatible.
    Type 'DisplayObject[]' is not assignable to type 'readonly FederatedEventTarget[]'.
      Type 'DisplayObject' is not assignable to type 'FederatedEventTarget'.
        The types of 'parent.removeAllListeners' are incompatible between these types.
          Type '(event?: keyof DisplayObjectEvents) => Container<DisplayObject>' is not assignable to type '(event?: string | symbol) => FederatedEventTarget'.
            Types of parameters 'event' and 'event' are incompatible.
              Type 'string | symbol' is not assignable to type 'keyof DisplayObjectEvents'.
                Type 'symbol' is not assignable to type 'keyof DisplayObjectEvents'.ts(2345)
```

![image](https://user-images.githubusercontent.com/15253010/207069207-bb22b108-175e-45fb-8d37-0180f1477673.png)

**Comment by TyroTheFox** [comment]
I'm having issues getting either of these to work. For the Global Mixin thing, do you just plonk it anywhere in the code or do you have to do something with it? Not something I've had to work with much and I've not been successful looking up more on what you're doing here specifically.

The approach where I add in the events through generics doesn't appear to be helping much either as I am in the situation where objects have been built on top of each other, inheriting from Container most commonly. Even adding in the event name as a type from the bottom of the inheritance tree doesn't appear to have helped with objects down the line. Do I need to extend the generics up through each layer of inheritance to allow for custom events to work for every object?

It's genuinely looking easier and simpler to just plumb a second Event Emitter just for my stuff and separate the two.

**Comment by Dunnings** [comment]
Does anyone have a better alternative? I have 100s of event strings in many files for many classes and adding all of them to a mixin isn't a feasible option. At the moment, I'm thinking of just forking pixi.js and removing the typing where needed.

**Comment by bigtimebuddy** [comment]
Thanks for the feedback. Will bump this priority to get sorted ASAP. Allowing any strings is probably easiest solution. Allowing string event-maps per class is going to be a little trickier but will look into it.

**Comment by xevrem** [comment]
should be easy to fix, just adjust anything that extends `EventEmitter` to be written like this:

```typescript
class Foo<T extends string> extends utils.EventEmitter<T & EVENT_TYPES> {
  ...
}
const foo = new Foo();
foo.on() // will now accept any string, and will list known valid strings per the `EVENT_TYPES` union type

// in this case, `EVENT_TYPES` looks like this
type EVENT_TYPE = "pointertap" | "pointerdown" | "pointerenter" ... 
```

now your IDE will display all `EVENT_TYPES` by default, as well as accept any given string as an `emit` or `on` binding. Below is how my Emacs IDE sees the `on` class:

```typescript
on(event: "pointertap" | "pointerdown" | "pointerenter" | "pointerleave" | "pointermove" | "pointerout" | "pointerup" | "pointerupoutside" | "pointerover" | "touchend" | ... 8 more ... | "removed", fn: (...args: any[]) => void, context?: any): Foo<string>
```

**Comment by SuperSodaSea** [comment]
@xevrem We will lost the type of `fn` if we do so.

**Comment by littleboarx** [comment]
Unfortunately, sub-class event expansion can not work as you expect. the main reason is that (Event&T)[eventKey] is not safe enough to not change the original event map and typescript can not infer the correct args type until the Until generic is instantiated. 
like dom API, I suggest custom events instead of allowing all event names to solve this problem. 
in addition for migration build, there should be a global flag to support any string events, while still keeping a strict type check for a new project.

**Comment by datrinh** [comment]
This has been quite a problem for migrating to v7. Will likely put this endeavour on hold

**Comment by bigtimebuddy** [comment]
I upped the bounty, would like to see some hero address this.

**Comment by zatx-private** [comment]
overriding this two type-hinting solved both problems for me
`declare namespace GlobalMixins {
    interface DisplayObjectEvents extends FederatedEventEmitterTypes {
        [x: string | number | symbol]: any;
    }

    interface DisplayObject extends Omit<FederatedEventTarget, keyof IFederatedDisplayObject>, IFederatedDisplayObject {
        [x: string | number | symbol]: any;
    }
}`

**Comment by kresli** [comment]
@miltoncandelero wouldn't be just easier to force any in this case?
`this.on("mycustomevent" as any, callback)`
