### ISSUE TITLE
Unable to run tests on Manjaro

### ISSUE THREAD

**Issue by Emobe** [pixijs/pixijs#8966]
### Expected Behavior
Tests run
### Current Behavior
Tests hang
### Steps to Reproduce
`npm run test` or any form of `npx jest path/to/file`
### Environment

- **`pixi.js` version**: 7.1.0-alpha
- **OS & Version**: 5.10.157-1-MANJARO

![image](https://user-images.githubusercontent.com/9289227/206859518-27ca6441-8c6d-4926-b992-d37b662097dc.png)

I pretty much just see the above output indefinitely. I assume it's something on my end but I'm pretty stumped.

**Comment by SuperSodaSea** [comment]
Can you set environment variable `DEBUG_MODE=1` (This will show the Electron window) then run the test to see what happened?

**Comment by Emobe** [comment]
A blank window opens and then closes a few seconds later and the test command just ends with no other output.

**Comment by SuperSodaSea** [comment]
That's strange. In theory, the normal result should be displaying a window with the test results:

![image](https://user-images.githubusercontent.com/8724868/206861257-01e39b01-b717-46e9-a5c2-2e0260869fce.png)
(Testing on Windows 11)

I guess this might be a compatibility issue between `jest-electron` and Manjaro.

**Comment by Emobe** [comment]
I'll try take a deeper dive into this. It _shouldn't_ be a compatibilty issue as electron apps run fine. Manjaro is based on arch linux so I'm not entirely sure but I shall see if I can uncover anything.

**Comment by Emobe** [comment]
Well, first off I have found it is definitely jest-electron. The tests run fine if I comment out the `runner` and `environment` lines in the config.

 At least for now I have some way of running the tests locally but I will continue to look into this at some point.

**Comment by SuperSodaSea** [comment]
Not all the tests can be run successfully without `jest-electron`, so we definitely need it. Maybe you can try to create a new empty project that use `jest-electron` and see if it works?

**Comment by Emobe** [comment]
Think I've found something https://github.com/hustcc/jest-electron/issues/46 :grimacing: 

This person used a fork and then just gave up though :sweat_smile:

**Comment by Emobe** [comment]
I've just tried running `jest-electron` on a boilerplate I have and yes, I get the same problem.

**Comment by SuperSodaSea** [comment]
It seems that `jest-electron` has been inactive for quite some time. Maybe we can consider using other runner such as [`@kayahr/jest-electron-runner`](https://www.npmjs.com/package/@kayahr/jest-electron-runner), which is more active.

**Comment by Emobe** [comment]
I was thinking of this as I just saw this issuue https://github.com/kayahr/jest-electron-runner/issues/8

Seems someone was already trying to do this before. I could have a look into doing this if you want.

**Comment by SuperSodaSea** [comment]
@Zyie Are you still interested in the `jest-electron` -> `@kayahr/jest-electron-runner` migration?

**Comment by bigtimebuddy** [comment]
I recently did this migration on @pixi/text-html and found the new package to be sufficient to jest-electron. It also allows for a newer Electron version.

**Comment by Emobe** [comment]
I'm pretty stumped with this one.

I keep getting this error

```
Error: Cannot find module 'node:fs'
Require stack:
- /home/emobe/projects/pixijs/node_modules/@kayahr/jest-electron-runner/lib/main/electron/runTest.js
- /home/emobe/projects/pixijs/node_modules/@kayahr/jest-electron-runner/lib/main/electron/rpc/JestWorkerRPC.js
- /home/emobe/projects/pixijs/node_modules/@kayahr/jest-electron-runner/lib/main/electron/electron_process_injected_code.js
- /home/emobe/projects/pixijs/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:261:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

Which doesn't make much sense to me because Jest supports node prefixes on ESM modules as it was fixed a while ago - https://github.com/facebook/jest/pull/11331

I've tried running it on the latest Jest version and still get the same issue.

I've ran the tests on @bigtimebuddy's work from @pixi/text-html on the custom-fonts branch and it works fine locally.


My only assumption is that something is mixing CJS and ESM? I'm not so sure.

I could be doing something completely wrong too.

**Comment by bigtimebuddy** [comment]
If it makes you feel any better, I'm just now getting the same thing after having tried to upgrade this project.

**Comment by bigtimebuddy** [comment]
I got past this error by removing `electron` and letting it peer install the most recent version. However, when running test, I'm now getting: 
```
 TypeError: Class extends value undefined is not a constructor or null
```
whenever trying to `extends EventEmitter`... digging in...

**Comment by Emobe** [comment]
Makes me feel a lot better as I've been stuck on this for a few days and haven't got much further

I tried it in one of my personal projects the other day and got the exact same error you mentioned here.

I had also opened an [issue](https://github.com/kayahr/jest-electron-runner/issues/12) but no response yet.

**Comment by bigtimebuddy** [comment]
Okay, I think I worked through most of the issues.
Try this branch: https://github.com/pixijs/pixijs/tree/chore/upgrade-jest

**Comment by bigtimebuddy** [comment]
The `node:fs` issue makes some sense. That's a newer feature of node, previously you had to do `fs`. Electron has a version of node embedded. If you aren't using a recent version, it will barf on that import. Double check your 'electron' version in your project's package-lock.json/package.json and upgrade as needed.

**Comment by Emobe** [comment]
Ahhh that makes sense then.

Good news. It's running tests for me now! Thanks a lot.
