### ISSUE TITLE
`WheelEvent.deltaMode` changed with Pixi7 only on FireFox

### ISSUE THREAD

**Issue by joergplewe** [pixijs/pixijs#8970]
We use a `"wheel"` event listener directly on the `<canvas>` (for UI zooming).

When upgrading from PIXI6->7 we noticed that the wheel-handler (only) on FireFox gets different event settings.
`deltaMode` changed from `0` (`DOM_DELTA_PIXEL`) with PIXI6 to `1` (`DOM_DELTA_LINE`) with PIXI7.

The listener seems not to be connected to PIXI at all? Why only on FireFox? We cannot spot the reason.

```
var app = new PIXI.Application({
    width: window.innerWidth,
    height: window.innerHeight,
    backgroundColor: 0x2c3e50
});
document.body.appendChild(app.view);

console.log("version", PIXI.VERSION);

app.view.addEventListener("wheel", (e) => {
    console.log(e.deltaY, e.deltaMode);
});
```

### Possible Solution
Evaluating `deltaMode` and scaling `deltaY` by a heuristic constant works around the effect, but we'd love to understand the reason.

### Steps to Reproduce
Run the code above in the PIXI playground and switch PIXI version in the settings.
Observe console log in the DevTools when scrolling with the mouse wheel.

*Note* that it only holds when using a mouse-wheel; using the touchpad also triggers the listener but does not show the effect (`deltaMode` is always `0`). 

### Environment

- **`pixi.js` version**: 7.x vs. 6.x
- **Browser & Version**: FireFox 107.0.1 (64-Bit)
- **OS & Version**: seen on MacOS 13.0.1
- **Running Example**: https://www.pixiplayground.com/#/edit/lSDZVVwcTjAf0p1AruozD

**Comment by SuperSodaSea** [comment]
This looks weird, `document.body.addEventListener('wheel', (e) => { console.log(e.deltaMode); })` will also print `1` with v7, but `0` for previous versions or without PixiJS.

**Comment by bhousel** [comment]
Oh!  Yeah this wheel delta thing is a tricky problem - I spent some time on it a few months ago.

Here's a link to our `_normalizeWheelDelta` function.
Hope the comments and code are helpful to someone.

```
   * _normalizeWheelDelta
   * This code performs some adjustment of the wheel event delta values.
   * The values may be given in PIXEL, LINES, or PAGE and we want them in PIXEL.
   *
   * Great summaries here:
   *   https://dev.to/danburzo/pinch-me-i-m-zooming-gestures-in-the-dom-a0e
   *   https://github.com/w3c/uievents/issues/181#issuecomment-392648065
   *
   * Note that Firefox will now change its behavior depending on how you look at the delta values!
   *   https://github.com/mdn/content/issues/11811
   *   https://bugzilla.mozilla.org/show_bug.cgi?id=1392460#c33
   * (Because Pixi's `normalizeWheelEvent` code in `EventSystem.ts` reads `deltaMode` before `deltaX/Y`,
   *   we get LINES sometimes in Firefox, particularly when using a physical mouse with a wheel)
   *
   * Also see https://github.com/basilfx/normalize-wheel/blob/master/src/normalizeWheel.js
   *   for an older version of this sort of code.
   *
   * And this great page for testing what events your browser generates:
   *   https://domeventviewer.com/
   * 
```

https://github.com/facebook/RapiD/blob/fe19995687e5dffb2182ec939c75fc917c8e001c/modules/pixi/PixiEvents.js#L304-L371

**Comment by joergplewe** [comment]
Wow ... that's weird.
Ok, in FF the order of lines 7/8 make a huge difference!

```
<html>
  <body>
    <canvas style="width: 200; height: 200; border: 2px solid blue;"></canvas>
  </body>
  <script>
    document.addEventListener("wheel", (event) => {
      const mode = event.deltaMode;
      const deltaY = event.deltaY;
      console.log(deltaY,  mode);
    });
  </script>
</html>
```

But does that mean, in PIXI7 there is an always-active `"wheel"` listener asking for `deltaMode` too early?

**Comment by SuperSodaSea** [comment]
https://github.com/pixijs/pixijs/blob/38750ee745ac7c6c33186158650f13094e88dca3/packages/events/src/EventSystem.ts#L595-L598

I can move `deltaMode` after `deltaZ` to make its behavior more consistent across browsers.

**Comment by joergplewe** [comment]
That would be kind. :)

But can you briefly elaborate, why this code is executed, even if no event listeners are actually registered?
Is it so the event system registers for any kind of events to convert them to `FederatedEvent`?

**Comment by SuperSodaSea** [comment]
@joergplewe In PixiJS v7, when `EventSystem` is initialized, all the event callbacks including `PIXI.EventSystem.onWheel` will be automatically registered (see code in [`EventSystem.addEvents`](https://github.com/pixijs/pixijs/blob/38750ee745ac7c6c33186158650f13094e88dca3/packages/events/src/EventSystem.ts#L411)), which will be called before your own callback. If you add `PIXI.EventSystem.prototype.onWheel = () => {};` before everything, you can get `e.deltaMode === 0` on Firefox.

**Comment by zcorpan** [comment]
The weird behavior in Firefox was implemented to improve web compat. But I agree it's not great. The relevant spec issue is https://github.com/w3c/uievents/issues/181

**Comment by trusktr** [comment]
This is more complicated than it seems: and even in cases where deltaMode is `DOM_DELTA_PIXEL` across all browser/OS combos, the detal values still vary wildly, making it nearly impossible to make the same behavior across all the browser/OS combos.

Related:

- https://github.com/w3c/uievents/issues/181
