### ISSUE TITLE
Vite: No matching export in "node_modules/@pixi/core/dist/esm/core.mjs" for import "settings"

### ISSUE THREAD

**Issue by Milesssssss** [pixijs/pixijs#8977]
Version information:
Vite version: 3.0.7
pixi.js version: 7.0.5

btw 6.5.2 is fine.

> 17:32:12 [vite] error while updating dependencies:
Error: Build failed with 20 errors:
node_modules/@pixi/assets/lib/detections/parsers/detectAvif.mjs:1:24: ERROR: No matching export in "node_modules/@pixi/core/dist/esm/core.mjs" for import "settings"
node_modules/@pixi/assets/lib/detections/parsers/detectWebp.mjs:1:24: ERROR: No matching export in "node_modules/@pixi/core/dist/esm/core.mjs" for import "settings"
node_modules/@pixi/assets/lib/loader/Loader.mjs:1:9: ERROR: No matching export in "node_modules/@pixi/core/dist/esm/core.mjs" for import "utils"
node_modules/@pixi/assets/lib/loader/parsers/loadJson.mjs:1:24: ERROR: No matching export in "node_modules/@pixi/core/dist/esm/core.mjs" for import "utils"
node_modules/@pixi/assets/lib/loader/parsers/loadJson.mjs:1:31: ERROR: No matching export in "node_modules/@pixi/core/dist/esm/core.mjs" for import "settings"
...
    at failureErrorWithLog (E:\Web\meta-map-webgl\node_modules\esbuild\lib\main.js:1624:15)
    at E:\Web\meta-map-webgl\node_modules\esbuild\lib\main.js:1266:28
    at runOnEndCallbacks (E:\Web\meta-map-webgl\node_modules\esbuild\lib\main.js:1046:63)
    at buildResponseToResult (E:\Web\meta-map-webgl\node_modules\esbuild\lib\main.js:1264:7)
    at E:\Web\meta-map-webgl\node_modules\esbuild\lib\main.js:1377:14
    at E:\Web\meta-map-webgl\node_modules\esbuild\lib\main.js:678:9
    at handleIncomingPacket (E:\Web\meta-map-webgl\node_modules\esbuild\lib\main.js:775:9)
    at Socket.readFromStdout (E:\Web\meta-map-webgl\node_modules\esbuild\lib\main.js:644:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)

**Comment by SuperSodaSea** [comment]
`node_modules/@pixi/core/dist/esm/core.mjs`

Seems that you are mixing PixiJS v6 and v7 packages. Can you uninstall all PixiJS packages and reinstall them?

https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS

```bash
npm uninstall pixi.js
npm install pixi.js
```

**Comment by Milesssssss** [comment]
Solved, thank you!

**Comment by mtsee** [comment]
To remove all dependencies related to pixijs, because dependencies of older versions of pixijs will depend on @pixi/core v6
