### ISSUE TITLE
7.0.5 webworker: global variables error

### ISSUE THREAD

**Issue by Milesssssss** [pixijs/pixijs#8979]
![image](https://user-images.githubusercontent.com/6835957/207900314-fcd7c8e9-5c1c-4edf-9a8d-b512e1cf06a7.png)

**Comment by SuperSodaSea** [comment]
You need to import `@pixi/webworker` package instead of `pixi.js` in Web Workers.

**Comment by Milesssssss** [comment]
@pixi/webworker usage is correct, and I have tested that @pixi/webworker@7.0.4 works fine.

**Comment by bigtimebuddy** [comment]
@Milesssssss then please provide a reproduction

**Comment by SuperSodaSea** [comment]
<https://pixijs.io/examples/?v=v7.0.5#/offscreen-canvas/web-worker.js> and my local project works just fine. Did you import `pixi.js` or `@pixi/accessibility` anywhere in the worker?

**Comment by Milesssssss** [comment]
Sorry for my mistoken， one component use pixi.js
Why is 7.0.4 available in the process， I haven’t found the reason yet. It may be related to the mixed use of 6.5.2 and 7 versions
Thank you for your response
