### ISSUE TITLE
Bug: Webfont loader checks for navigator.onLine before downloading fonts

### ISSUE THREAD

**Issue by miltoncandelero** [pixijs/pixijs#8990]
### Current Behavior

Webfont loader checks for `navigator.onLine` before downloading fonts  
This prevents cached apps (PWAs) or local servers (developing) from working.

### Expected Behavior

Webfont loader shouldn't check navigator.`onLine`.  
No other loader does it, `navigator.onLine.` is not used in the entire codebase except there.

### Steps to Reproduce

offending code is here

https://github.com/pixijs/pixijs/blob/dev/packages/assets/src/loader/parsers/loadWebFont.ts#L68

### Environment

- **`pixi.js` version**: *7.0.5*

### Possible Solution

This is a super easy fix but I am traveling right now and on a limited dataplan. I can't clone the pixijs repo to fix it. Feel free to assign it to me and on january I will PR.

**Comment by Zyie** [comment]
Hey @miltoncandelero are you still looking into this? 

I can deal with it if you are busy!

**Comment by SuperSodaSea** [comment]
I agree with this change, there is no need to check `navigator.onLine` when loading font.
