### ISSUE TITLE
Bug:undefined property _uvs when instanciating PIXI.AnimatedSprite from textureArray

### ISSUE THREAD

**Issue by BuyMyBeard** [pixijs/pixijs#9023]
### Current Behavior

trying to instantiate an AnimatedSprite by giving a texture array in constructor throws this error in my pixi-hotwire dev build:

Uncaught TypeError: Cannot read properties of undefined (reading '_uvs')
    at AnimatedSprite.updateTexture (@pixi.sprite-animated.v7.0.5.js:11775:30)
    at set textures [as textures] (@pixi.sprite-animated.v7.0.5.js:11824:10)
    at new AnimatedSprite (@pixi.sprite-animated.v7.0.5.js:11691:19)
    *at line in my code*

### Expected Behavior

Instanciating an AnimatedSprite correctly

### Steps to Reproduce

https://jsfiddle.net/BuyMyBeard/aL9hcdk4/1/

### Environment

- **`pixi.js` version**:  7.0.5
- **Browser & Version**:  Chrome 108.0.5359.125
- **OS & Version**: Windows 11 V.22H2
- **Running Example**: https://jsfiddle.net/BuyMyBeard/aL9hcdk4/1/

**Comment by SuperSodaSea** [comment]
> Access to image at 'https://cdn.discordapp.com/attachments/1046481806209331290/1057737059814608946/bdice1.png' from origin 'https://fiddle.jshell.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

It seems that your example have some CORS problems.

**Comment by BuyMyBeard** [comment]
seems like it works perfectly fine in a fiddle, but not in my solution

**Comment by manongguai** [comment]
I also have this issue installing dependencies using NPM, but using Yarn does not have this issue
version: 7.1.1
