### ISSUE TITLE
Feature Request: Please restore @pixi/interaction in v7

### ISSUE THREAD

**Issue by md5crypt** [pixijs/pixijs#9029]
### Description

Over that last weekend I had some time free and decided to finally port some pixi projects I work on to v7. Unfortunately the current state of EventSystem forces me to stay on v6.

First of all the issue already reported here #8922. This breaks almost all UI buttons with text as suddenly text (that has interactive = false) for some reason prevents click events on the button sprites. Probably breaks much more, it was just the first thing I noticed during testing.

Second of all the new EventSystem no longer re-fires the recursive hit testing each frame. This breaks hover support for objects moving over a static cursor.

Now, if I do the following:

```json
{
  "dependencies": {
    "@pixi/interaction": "^6.5.0"
  },
  "overrides": {
    "@pixi/interaction": {
      "@pixi/core": "^7.0.0",
      "@pixi/display": "^7.0.0",
      "@pixi/math": "^7.0.0",
      "@pixi/ticker": "^7.0.0",
      "@pixi/utils": "^7.0.0"
    }
  }
}
```

```typescript
declare module "@pixi/core" {
    interface AbstractRenderer extends BatchRenderer {}
}
(InteractionManager.extension as any).name = "interaction2"
Object.defineProperty(Renderer.prototype, "_lastObjectRendered", {
    get() {
        return (this as Renderer).objectRenderer.lastObjectRendered
    }
})
```

I can use the old interaction manager with v7 with absolutely no issue, so I see no reason why to remove it. Rename it to interactionLegacy or something, but for the time being leave it in so I can just move on to v7 and revisit the issue in some time when EventSystem will be fixed, tested and working.

I believe more ppl will be blocked by this and will remain on v6 instead of moving on to v7.

**Comment by Zyie** [comment]
Hey @md5crypt

I've been working on allowing the events system to be more powerful and able to reproduce many of the behaviour of v6

- Global move events #9067
  - This PR added the ability to subscribe to `globalpointermove` which mimic the behaviour of v6's `pointermove` event

- Interactive Changes #9089
  - This PR expands the definition of what interactive means in Pixi. So for your use case of UI buttons you could either set the parents container to `interactive = 'passive'` which ignores all none interactive children, or set the children to be `interactive = 'none'` themselves

- Hover events #9092
  - This PR added the mocked events that fires each frame when the cursor is not moving. All you need to do is set `interactive = 'dynamic'`

Hopefully these PR's when released is enough for you to be unblocked using v7 events!
