### ISSUE TITLE
Bug: LINE_JOIN.ROUND fails when MiterLimit is <= 4.0

### ISSUE THREAD

**Issue by mudcube** [pixijs/pixijs#9030]
### Current Behavior

Applying LINE_JOIN.ROUND with a MiterLimit of <= 4.0 results in LINE_JOIN.BEVEL.

### Expected Behavior

LINE_JOIN.ROUND to be applied.

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/SMsc63jIec6ge6m5bhrlF

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

### Possible Solution

It appears removing `|| pdist / widthSquared > miterLimitSquared` from the `buildNonNativeLine` method resolves this issue, however, I'm not confident removing this won't result in other unexpected issues. @ShukantPal might know the answer to this?

**Comment by SuperSodaSea** [comment]
Seems that it is similar to #8288, but #8325 only fixed part of it. I'd like to fix this later.
