### ISSUE TITLE
Bug: Inappropriate document for `arcTo`

### ISSUE THREAD

**Issue by liskysun** [pixijs/pixijs#9049]
### Current Behavior

![image](https://user-images.githubusercontent.com/34642451/211290212-58d4652d-231f-4d7f-9651-d00cca0fe24c.png)
![image](https://user-images.githubusercontent.com/34642451/211290441-af7e6084-fdea-4da0-a3de-a5ef1a201051.png)

### Expected Behavior

Fillet arc will appear in the middle

### Steps to Reproduce

  let pointerCircle = new PIXI.Graphics()
    .beginFill(0xFFCC00, 1)
    .moveTo(0, 0)
    .lineTo(45, 0)
    .arcTo(45, 0, 60, 15, 15)
    .lineTo(60, 60)
    .lineTo(0, 60)
    .endFill()

### Environment

- **`pixi.js` version**: *e.g. 7.0.5*
- **Browser & Version**: *e.g. Chrome 108.0.5359.125
- **OS & Version**: *e.g. Ubuntu windows11*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by SuperSodaSea** [comment]
It seems that this is not the correct way to call [`PIXI.Graphics.arcTo`](https://pixijs.download/dev/docs/PIXI.Graphics.html#arcTo) in PixiJS. The first two arguments of `arcTo` should be the coord of its *tangent point*, not the start point (the start point is the last coord you `lineTo`), similar to the [`CanvasRenderingContext2D.arcTo`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/arcTo) in browser's native 2D canvas API.

Here is an working demo (<https://pixiplayground.com/#/edit/IEjLsXQ_cjBqT5P17nl3m>):
```js
const graphics = new PIXI.Graphics()
    .beginFill(0xFFCC00, 1)
    .moveTo(0, 0)
    .lineTo(45, 0)
    .arcTo(60, 0, 60, 15, 15)
    .lineTo(60, 60)
    .lineTo(0, 60)
    .endFill();
```
![image](https://user-images.githubusercontent.com/8724868/211301814-185de80e-ca2c-4305-8ef0-aba983afe06b.png)

**Comment by liskysun** [comment]
Are you sure it is tangent coordinate?

The first point should be the intersection of two tangents of the arc (control point).

Now we need to find the control point according to the two tangent points

**Comment by liskysun** [comment]
![image](https://user-images.githubusercontent.com/34642451/211455734-813eca67-e9c9-4772-a34e-46fdb6f61c76.png)

**Comment by liskysun** [comment]
![image](https://user-images.githubusercontent.com/34642451/211456159-c5100772-f6f8-4f0e-8663-2f2443983e19.png)
For the current arc AB

arcTo(Cx, Cy, Bx, By, r)

**Comment by liskysun** [comment]
![image](https://user-images.githubusercontent.com/34642451/211456394-5f0b6ba6-8b12-464d-9542-06fa2ab33a5f.png)
![image](https://user-images.githubusercontent.com/34642451/211456478-f130774a-a100-4bf6-bc97-011ba5b8c7cc.png)

Note：arcTo(Ax, Ay, Bx, By, r)

**Comment by liskysun** [comment]
Similarly, quadraticCurveTo has similar annotation problems
![image](https://user-images.githubusercontent.com/34642451/211457167-92d904d6-eb1e-4a79-8c46-f20d70fd4261.png)

**Comment by SuperSodaSea** [comment]
You are right, *control point* is a better name for it. I will fix that later.

```ts
/**
 * arcTo()
 * @param x1 - The x-coordinate of the first control point of the arc
 * @param y1 - The y-coordinate of the first control point of the arc
 * @param x2 - The x-coordinate of the second control point of the arc
 * @param y2 - The y-coordinate of the second control point of the arc
*/
```

---

`quadraticCurveTo` is different from `arcTo`. The second point for `quadraticCurveTo` is always the end point, but for `arcTo` it may not end at the second point, for example `p0 = (0, 0), p1 = (10, 0), p2 = (10, 100), r = 10` will create an arc end at (10, 10). So for `arcTo` it is `(control point 1, control point 2)`, and for `quadraticCurveTo` it is `(control point, end point)`.
