### ISSUE TITLE
Bug: Assets which load other assets, such as spritesheets, do not append defaultSearchParams to the assets they're loading

### ISSUE THREAD

**Issue by Giacom** [pixijs/pixijs#9052]
### Current Behavior

When you load an asset data file, such as a spritesheet JSON or a bitmap XML file, it will attempt to load the assets listed in there, such as the spritesheet PNG. Problem is, is that it doesn't load it with the defaultSearchParams appended to it.

Here is a network log example, my-numbers.json is a multi spritesheet file.

![image](https://user-images.githubusercontent.com/1524810/211795899-b87eb6a7-421f-4c71-9385-90e86aab843a.png)

```typescript
  PIXI.Assets.init({
    defaultSearchParams: { version: "1.0.0" },
    manifest: {
      bundles: [
        {
          name: "test_bundle",
          assets: [
            {
              name: "spritesheet",
              srcs: "assets/all-my-numbers.json", // Will load its related image file without the version param
            },
            {
              name: "spritesheet-multi",
              srcs: "assets/my-numbers-0.json", // Will load other spritesheets through the relative_multi property without the version param
            },
            {
              name: "bitmapfont",
              srcs: "assets/bonus_special_highlight_export.xml", // Will load the font image related to this XML without the version param
            },
          ],
        },
      ],
    },
  });

  PIXI.Assets.loadBundle("test_bundle");
```

### Expected Behavior

The network requests should be appending the version to all requests being made by the Assets system.

### Steps to Reproduce

1. Open https://www.pixiplayground.com/#/edit/TEmwE_ExPjqNlkr-NboRO
2. Open the network log
3. Refresh the game
4. See that it append the `version` param to the bitmap font's data file but not to the PNG.

OR

1. Download, extract, and install the example NPM project: [defaultSearchParamIssue.zip](https://github.com/pixijs/pixijs/files/10391882/defaultSearchParamIssue.zip)
5. Run `npm run local:buildRun` to build and run the project.
6. Open the browser and open the network tab to note that the defaultSearchParam is not appended to everything loaded.

### Environment

- **`pixi.js` version**: *7.1.0*
- **Browser & Version**: *All Latest Browsers*
- **OS & Version**: *Windows 11*
- **Running Example**: *https://www.pixiplayground.com/#/edit/TEmwE_ExPjqNlkr-NboRO & [defaultSearchParamIssue.zip](https://github.com/pixijs/pixijs/files/10391882/defaultSearchParamIssue.zip)*

### Possible Solution

Maybe the resolver should not be handling the defaultSearchParam and it should be appended to every single URL that is used to fetch assets.

**Comment by Giacom** [comment]
Added a playground link as an example.

**Comment by GoodBoyDigital** [comment]
on this one now! thanks for sharing @Giacom !
