### ISSUE TITLE
Feature Request: Add the ability to add metadata to assets in bundles like you can with PIXI.Assets.add

### ISSUE THREAD

**Issue by Giacom** [pixijs/pixijs#9053]
### Description

Currently you can add meta data to the Assets you want to load with `PIXI.Assets.add`:

```typescript
//                                      v Meta-data
PIXI.Assets.add("hero", "player.png", { animations: ["jump", "run", "attack"] } });
```

This is useful for passing data about the file to the related loader, such as adding a list of different animations a spritesheet has or for embedding a Spine .atlas file.

But sadly for bundles there is no way to add meta-data, it would be most useful if there was a new optional property for `ResolverAssetsArray` that would let you pass in meta data from the manifest itself. This will allow people to customise their manifests more to suit their development needs.

Here is what it could look like:

```typescript
const manifest = {
    bundles: [
        {
            name: "game-screen",
            assets: [
                {
                    name: "character",
                    srcs: "robot.png",
                    data: { // New property
                        animations: ["run", "jump", "shoot"]
                    }
                },
            ]
        }
    ]
};
```

**Comment by GoodBoyDigital** [comment]
taking a looksi now

**Comment by GoodBoyDigital** [comment]
hey, so dumb question.. how would the meta data b accessed?

**Comment by GoodBoyDigital** [comment]
would it be attached to the texture?

**Comment by GoodBoyDigital** [comment]
or would this only be accessable from loader functions?

**Comment by GoodBoyDigital** [comment]
ok, my brain has finally arrived to this conversation...

Good news! we have this already :D Just need to adjust the format a little and it will be accessable:

```
const manifest = {
    bundles: [
        {
            name: "game-screen",
            assets: [
                {
                    name: "character",
                    srcs: {src:"robot.png", animations: ["run", "jump", "shoot"]}
                },
            ]
        }
    ]
};
```

**Comment by GoodBoyDigital** [comment]
ok so noooooow its fixed. 

```
const manifest = {
    bundles: [
        {
            name: "game-screen",
            assets: [
                {
                    name: "character",
                    srcs: "robot.png",
                    data: { // New property
                        animations: ["run", "jump", "shoot"]
                    }
                },
            ]
        }
    ]
};
```

this will work as you suggested! I got there in the end 🙃

**Comment by Giacom** [comment]
Oh great! Yeah it was just the format blocking me on this :P
