### ISSUE TITLE
Bug: Link goes to a 404 page

### ISSUE THREAD

**Issue by tansanDOTeth** [pixijs/pixijs#9058]
### Current Behavior

Link goes to a 404

### Expected Behavior

Link to goes to the expected page

### Steps to Reproduce

1. Go to https://pixijs.io/guides/basics/getting-started.html
2. Click "how to work with PixiJS and packers"

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

### Additional Information

Happy to edit the guide, but not sure where the link is supposed to go.

**Comment by domis86** [comment]
Im not sure but maybe to https://pixijs.io/guides/basics/sprite-sheets.html  ?

**Comment by SuperSodaSea** [comment]
Seems to be duplicated with pixijs/guides#40.

**Comment by bigtimebuddy** [comment]
Thanks for reporting. Closing this as it's a duplicate.
