### ISSUE TITLE
Bug: Doesn't work with a CRA 5.0.1 project

### ISSUE THREAD

**Issue by tansanDOTeth** [pixijs/pixijs#9064]
### Current Behavior

After installing pixi and importing it, this is the following error I am getting:

```
ERROR in ./node_modules/@pixi/core/lib/textures/resources/ImageBitmapResource.mjs
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /projects/test-project/node_modules/@pixi/core/lib/textures/resources/ImageBitmapResource.mjs: When using '@babel/plugin-transform-parameters', it's not possible to compile `super()` in an arrow function with default or rest parameters without compiling classes.
Please add '@babel/plugin-transform-classes' to your Babel configuration.

   6 |   constructor(source, options) {
   7 |     var __super = (...args) => {
>  8 |       super(...args);
     |       ^^^^^^^^^^^^^^
   9 |     };
  10 |     options = options || {};
  11 |     if (typeof source === "string") {
```

### Expected Behavior

I expect it to run without errors.

### Steps to Reproduce

1. npx create-react-app pixi-test
2. cd pixi-test
3. npm install pixi.js
4. Import pixi
```
import * as PIXI from 'pixi.js';
```
5. npm run start
7. Error shows

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

### Possible Solution

Not really sure

### Additional Information

Seems like babel added this change relatively recently and it was to prevent infinite recursion.

https://github.com/babel/babel/issues/15148
https://github.com/babel/babel/pull/15163

Here is the transpiled code:
```
class ImageBitmapResource extends BaseImageResource {
    constructor(source, options) {
      var __super = (...args) => {
        super(...args);
      };
      options = options || {};
      if (typeof source === "string") {
        __super(ImageBitmapResource.EMPTY);
        this.url = source;
      } else {
        __super(source);
        this.url = null;
      }
      this.crossOrigin = options.crossOrigin ?? true;
      this.alphaMode = typeof options.alphaMode === "number" ? options.alphaMode : null;
      this._load = null;
      if (options.autoLoad !== false) {
        this.load();
      }
    }
```

**Comment by SuperSodaSea** [comment]
Duplicated with #8733 and #8824. This is a limitation of transcription.
Workaround: Delete the `"last 1 safari version"` in your `package.json`.

**Comment by tansanDOTeth** [comment]
Ah, that workaround makes a lot of sense if you don't need to explicitly support it. Thanks for replying so quickly!

I'll close this since it's a duplicate.
