### ISSUE TITLE
Bug: Adjust BitmapFont xadvance calculation

### ISSUE THREAD

**Issue by vpmedia** [pixijs/pixijs#9082]
### Current Behavior

BitmapFont.from() generated font character positions are slightly different compared to a pixi.js text or native html text

### Expected Behavior

Character positions should match compared to a pixi.js text or native html text

### Steps to Reproduce

Create a BitmapText with font created by BitmapFont.from() and a Pixi.js Text and/or HTML Text than compare the character positions

### Environment

- **`pixi.js` version**: *v7.1.0*

### Possible Solution

Remove Math.ceil() from https://github.com/pixijs/pixijs/blob/dev/packages/text-bitmap/src/BitmapFont.ts#L510

### Additional Information

If I remove Math.ceil() from the xadvance calculation I got the same character positions

**Comment by bigtimebuddy** [comment]
This was introduced #6600

I'm not sure what the intention was using `Math.ceil`, but if it solves your issue, make a PR. We'll have to see a few examples but that sounds reasonable. I'm not sure what the ceil is solving. @ShukantPal do you remember why you added that?

**Comment by bigtimebuddy** [comment]
Also, do you think you could create an example using pixiplayground/jsfiddle/codepen etc that shows the difference between Text and BitmapText?

**Comment by vpmedia** [comment]
> Also, do you think you could create an example using pixiplayground/jsfiddle/codepen etc that shows the difference between Text and BitmapText?

@bigtimebuddy Sure, will create an example soon

**Comment by vpmedia** [comment]
@bigtimebuddy Here we go: https://www.pixiplayground.com/#/edit/a3kN2b7T9p-y1zWfj_ShZ

**Comment by vpmedia** [comment]
I think this comment explains the intention why it is rounded ("The xAdvance being created for..."):
https://github.com/pixijs/pixijs/pull/6600#pullrequestreview-409822373

**Comment by bigtimebuddy** [comment]
Dev Branch:
https://jsfiddle.net/bigtimebuddy/xot0qn1c/

Without Math.ceil on xadvance:
https://jsfiddle.net/bigtimebuddy/jekt7vyn/

Here's a screenshot at 200%, top HTML, middle PIXI.Text, bottom PIXI.BitmapText w BitmapFont

You can see that some other character are much blurrier (see "5", "A", "q")

![Screen-Shot-2023-01-20-at-9 39 06-AM](https://user-images.githubusercontent.com/864393/213725356-63457531-b34e-41de-b5a7-8d6c59892b72.png)

**Comment by bigtimebuddy** [comment]
Here's a version with `Math.round` instead of `Math.ceil`, which I think it's a little better, but still not perfect.
![round](https://user-images.githubusercontent.com/864393/213726402-88b15caf-f9d3-49fe-ab1d-3e4fdd21674c.png)

**Comment by bigtimebuddy** [comment]
Here's the same `Math.round` but at 52px (double the size). The large the font size, likely the more accurate it'll be.
![Screen Shot 2023-01-20 at 9 48 24 AM](https://user-images.githubusercontent.com/864393/213727289-60a95706-a0c8-4ebe-a53b-e4e4c735acd7.png)

**Comment by bigtimebuddy** [comment]
I think I found a good solution. This version leaves xadvance alone (no Math operations) but rounds when drawing each character so we don't get weird subpixel rendering.

![round-draw](https://user-images.githubusercontent.com/864393/213730902-edb153c6-8bff-4122-8ccb-fb2069aa853d.png)

**Comment by vpmedia** [comment]
@bigtimebuddy Excellent, thank you!
