### ISSUE TITLE
Bug: TS1362: 'Loader' cannot be used as a value because it was exported using 'export type'.

### ISSUE THREAD

**Issue by divSelector** [pixijs/pixijs#9098]
### Current Behavior

I cannot access the `PIXI.Loader` class due to this TypeScript error.

```
[tsl] ERROR in /mnt/hdd/js/webgl1/src/scenes/LoadTilemap.ts(15,28)
      TS1362: 'Loader' cannot be used as a value because it was exported using 'export type'.
```

### Expected Behavior

I should be able to access the class like this without the above error.

```js
import { Loader } from "pixi.js"
const loader = Loader.shared;
// or
const loader = new Loader(); 
```

### Steps to Reproduce

I uploaded the project in its current problem state. It's very boilerplate.

https://github.com/divSelector/goty-web/blob/main/src/scenes/LoadTilemap.ts

I have not gotten very far due to this issue.

### Environment

- **`pixi.js` version**: *e.g. 7.1.1*
- **Browser & Version**: *e.g. Firefox 109*
- **OS & Version**: *e.g. Ubuntu 22.04.1 LTS*

### Additional Information

 It's possible this is not a bug and I am just stupid. In any case, some help figuring it out would be good.

**Comment by SuperSodaSea** [comment]
You can get the `Loader` instance with `Assets.loader`.

**Comment by divSelector** [comment]
That seems to work. Is that the same thing as `Loader.shared`?

**Comment by SuperSodaSea** [comment]
`Loader.shared` was from `@pixi/loaders` in PixiJS v6.x. In PixiJS v7.x we replaced it with `@pixi/assets`, and `Loader.shared` no longer exists.

**Comment by divSelector** [comment]
Ah, I see. 

Ultimately I had been hoping to use this <https://github.com/riebel/pixi-tiledmap>, since I had started making maps with tiled map editor before I looked Pixi. But it hasn't been updated in three years and that probably explains it. Thanks.
