### ISSUE TITLE
Bug: Intermittently failing test on CI 

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixijs#9101]
### Current Behavior

This test is occasionally failing CI (probably 10% of the time).

```
FAIL packages/app/test/Application.tests.ts
  ● Test suite failed to run

      ● Application › resizeTo › should throttle multiple resizes

        expect(jest.fn()).toBeCalledTimes(expected)

        Expected number of calls: 1
        Received number of calls: 0

          137 |             setTimeout(() =>
          138 |             {
        > 139 |                 expect(spy).toBeCalledTimes(1);
              |                             ^
          140 |                 app.destroy();
          141 |                 done();
          142 |             }, 50);

      at packages/app/test/Application.tests.ts:139:29
```

### Expected Behavior

This test should not fail on CI

### Steps to Reproduce

Happens intermittently on GitHub Actions. 

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

### Possible Solution

Probably re-work the setTimeout to measure resizes?

**Comment by SuperSodaSea** [comment]
Similar to #8468?

**Comment by bigtimebuddy** [comment]
Maybe? I think setTimeout or measuring time is not reliable on CI (which is much more resource constrained).

**Comment by SuperSodaSea** [comment]
In fact, I sometimes get random test failures even when I run tests locally.

**Comment by SuperSodaSea** [comment]
There is a [`jest.retryTimes`](https://jestjs.io/docs/jest-object#jestretrytimesnumretries-options) that may solve this problem, however it only works with the default [jest-circus](https://github.com/facebook/jest/tree/main/packages/jest-circus) runner.

**Comment by GoodBoyDigital** [comment]
closing this as we have had pretty stable tests for the last year or so 👍
