### ISSUE TITLE
Bug: plugins stopped installing or working correctly after 6.5.9 release

### ISSUE THREAD

**Issue by aram88888** [pixijs/pixijs#9108]
### Current Behavior

@pixi/sound, pixi-viewport plugins can't be installed at all. Please find attached installation log files. 
If we install exact versions pixi.js@6.5.8 and @pixi/sound@4.0.5 package installation errors are gone.
If we install exact versions pixi.js@6.5.8 and @pixi/display@6.5.8 and pixi-viewport package installation errors are gone.
pixi-spine logs only peer dependency errors but have run time issues.
[pixiSound.txt](https://github.com/pixijs/pixijs/files/10500631/pixiSound.txt)
[pixiVieport.txt](https://github.com/pixijs/pixijs/files/10500632/pixiVieport.txt)
[pixiSpine.txt](https://github.com/pixijs/pixijs/files/10500633/pixiSpine.txt)

### Expected Behavior

plugins installed and worked successfully

### Steps to Reproduce

install packages as described in current behaviour

### Environment

pixi.js` version**: *e.g. 6.5.9
npm 8.1.3

### Possible Solution

roll back changes to 6.5.8 :)

**Comment by SuperSodaSea** [comment]
@bigtimebuddy Seems that some packages like `@pixi/interaction`, `@pixi/loaders` and `@pixi/polyfill` that were removed in v7 are not released as `latest` for 6.5.9.

**Comment by aram88888** [comment]
Thank you for your response. When it will be fixed?

**Comment by bigtimebuddy** [comment]
I'm looking into it. Will fix asap

**Comment by bigtimebuddy** [comment]
All packages were published fine, but for v6.x branch, we release using the dist tag `latest-6.x`. I'm not 100% sure, but I think having latest on these discontinued packages be _lower_ semver than the `latest-6.x` might be giving us issues.

To try to fix, I ran these commands:

```
npm dist-tag add @pixi/loaders@6.5.9 latest
npm dist-tag add @pixi/polyfill@6.5.9 latest
npm dist-tag add @pixi/interaction@6.5.9 latest
```

Can you try again?

**Comment by SuperSodaSea** [comment]
Seems to work well with me. These packages themselves do not have a 7.x version, and are not used by other v7.x packages, so I think that's fine. Maybe we should consider adding this to our publish workflow.

**Comment by bigtimebuddy** [comment]
I agree, we could use a fix for this. I think we'll be maintaining v6 for bugs for a little bit and I know I'll definitely forget this next time I need to push a release.

**Comment by SuperSodaSea** [comment]
@aram88888 Any feedback?

**Comment by aram88888** [comment]
Yes, it is working. Thank you.
