### ISSUE TITLE
Bug: `Color` still keeps its original `value` after it is modified

### ISSUE THREAD

**Issue by SuperSodaSea** [pixijs/pixijs#9146]
### Current Behavior

`Color` still keeps its original `value` (The `ColorSource` that created it) after it is modified.

### Expected Behavior

`Color.value` should be set to `null` after it is modified by `multiply` or `round`.

### Steps to Reproduce

```js
const color = new PIXI.Color(0xFFFFFF);
console.log(color.toRgbaString()); // rgba(255,255,255,1)
color.multiply(0xFF0000);
console.log(color.toRgbaString()); // rgba(255,0,0,1)
color.setValue(0xFFFFFF);
console.log(color.toRgbaString()); // rgba(255,0,0,1) (The correct result should be rgba(255,255,255,1))
```

### Environment

- **`pixi.js` version**: dev
- **Browser & Version**: (Any)
- **OS & Version**: (Any)
- **Running Example**: <https://pixiplayground.com/#/edit/YoeXFeZ1mzbKy-BCUJnte>

### Possible Solution

The issue is caused by the code below:

https://github.com/pixijs/pixijs/blob/a4409c20d757aaf6a17b5af58362437a87314120/packages/color/src/Color.ts#L163-L167

`Color.value` is meaningless after the `Color` is modified by `multiply` or `round`, so in my opinion it should be set to `null`.

**Comment by bigtimebuddy** [comment]
I agree with this API choice. I'd consider multiply/round to be destructive operations. We also want to add premultiply, which would be similar.
