### ISSUE TITLE
Feature Request: Add a method to Disable Image loading via WebWorker

### ISSUE THREAD

**Issue by Makio64** [pixijs/pixijs#9158]
### Description

**Feature :**
Add the possibility to load img ressources the old way ( no webworker )

**Reason :**
Of course loading via WebWorker is great but some edge case environment can raise security issue doing so. Therefore it should be an easy way to disable it. 

**Example :** 
When in a WKWebview(Swift/iOS) loading an image in a webworker using a customSchemeURL(custom url protocol like pixijs://myimg.png) raise a security error.

Adding a property to disable the loading via WebWorker would solve this issue and probably other edge cases.

Thanks !

**Comment by bigtimebuddy** [comment]
There's already an option for that: `Assets.preferWorkers = false`

**Comment by Makio64** [comment]
Ok, my bad i found the "preferWorkers" the issues was then coming from even with preferWorkers = false it user createImageBitmap, if I want to load the old way I have to do something creepy like : 

`window.createImageBitmap = null`

this is from the logic in loadTexture 
```
    async load(url: string, asset: LoadAsset<IBaseTextureOptions>, loader: Loader): Promise<Texture>
    {
        let src: any = null;

        if (globalThis.createImageBitmap)
        {
            if (this.config.preferWorkers && await WorkerManager.isImageBitmapSupported())
            {
                src = await WorkerManager.loadImageBitmap(url);
            }
            else
            {
                src = await loadImageBitmap(url);
            }
        }
        else
        {
            src = await new Promise((resolve) =>
            {
                src = new Image();
                src.crossOrigin = 'anonymous';

                src.src = url;
                if (src.complete)
                {
                    resolve(src);
                }
                else
                {
                    src.onload = (): void =>
                    {
                        resolve(src);
                    };
                }
            });
        }

```

**Comment by bigtimebuddy** [comment]
Let's add an option to opt out of createImageBitmap. Good idea.

PR welcome for this!

**Comment by Makio64** [comment]
And apparently in this case the request should also not be "anonymous", should it be another option too?

**Comment by bigtimebuddy** [comment]
Sure crossOrigin too
