### ISSUE TITLE
Bug: graphics linestyle width do not effect by scale of matrix

### ISSUE THREAD

**Issue by Mrluobo** [pixijs/pixijs#9176]
### Current Behavior

hi,

I try to use PIXI.Graphics  draw a simple shape like this:

```
const app = new PIXI.Application({ antialias: true });
document.body.appendChild(app.view);

const graphics = new PIXI.Graphics();

const matrix = new PIXI.Matrix();
matrix.scale(1,2);
graphics.setMatrix(matrix);

graphics.lineStyle(10, 0xFFBD01, 1);
graphics.beginFill(0xC34288);
graphics.drawRect(50, 50, 100, 100);
graphics.endFill();

app.stage.addChild(graphics);
```

i got result like this:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/9135512/219354236-19a71b34-ec3c-457c-92a2-94ca2346e9e3.png">

this stroke line width do not scale like I expected.

is there a way I can scale the stroke line width?

hope for your help!

### Expected Behavior

the stroke line width scale like shape width and shape height.

### Steps to Reproduce

```
const app = new PIXI.Application({ antialias: true });
document.body.appendChild(app.view);

const graphics = new PIXI.Graphics();

const matrix = new PIXI.Matrix();
matrix.scale(1,2);
graphics.setMatrix(matrix);

graphics.lineStyle(10, 0xFFBD01, 1);
graphics.beginFill(0xC34288);
graphics.drawRect(50, 50, 100, 100);
graphics.endFill();

app.stage.addChild(graphics);
```

### Environment

- **`pixi.js` version**: *7.1.0*
- **Browser & Version**: *Chrome 108*
- **OS & Version**: *mac*
- **Running Example**: *<https://pixiplayground.com/#/edit/uGjUFk3mWXOUKRDTmzm-G>*

**Comment by SuperSodaSea** [comment]
`graphics.scale.set(1, 2)` [works](https://pixiplayground.com/#/edit/dpR26FzIN2B5hDTaWWdL7). `PIXI.Graphics.setMatrix()` only applies to the coordinates of the points in the graphics data.

![image](https://user-images.githubusercontent.com/8724868/219367597-c4098c4c-c412-4b4f-a86b-91e8e3832a47.png)

**Comment by Mrluobo** [comment]
> `graphics.scale.set(1, 2)` [works](https://pixiplayground.com/#/edit/dpR26FzIN2B5hDTaWWdL7). `PIXI.Graphics.setMatrix()` only applies to the coordinates of the points in the graphics data.
> 
> ![image](https://user-images.githubusercontent.com/8724868/219367597-c4098c4c-c412-4b4f-a86b-91e8e3832a47.png)

thx for your help,but :
I want to draw many shapes in one Graphics,  the scale of shapes is different form each other. how to make this?

**Comment by SuperSodaSea** [comment]
Just create multiple `Graphics`, and Pixi will do the batching for you when rendering.
