### ISSUE TITLE
Bug: Triangle generated suddenly from trail effect's SimpleRope on mobile chrome

### ISSUE THREAD

**Issue by neizzz** [pixijs/pixijs#9179]
### Current Behavior

I implemented a trail effect based https://pixijs.io/examples/#/gsap3-interaction/gsap3-trail.js

But **only on mobile (not problem on PC)** , when the circle is start to move or stopped the movement, a triangle (having a point that is a middle point of view port) is suddenly generated at the moment.

https://user-images.githubusercontent.com/97387461/219869147-f9d2c864-86a1-46cb-9dcb-21c660ae93bc.mp4

### Expected Behavior

the triangle is not generated.

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/80Nf5kQ4IfIFgoCCy9gqA

(if the video below not started, copy its link from mouse right click, then paste new browser tab)
galaxy s21

https://user-images.githubusercontent.com/97387461/219874814-cf053864-b19e-4e84-ae63-bd9b80dd8969.mp4

galaxy note10

https://user-images.githubusercontent.com/97387461/219874817-8740a038-8ae9-43a7-a4be-1eea16eb5674.mp4

### Environment

pixi js vertion: 6.5.9
mobile(Galaxy S21) chrome version: 110.0.5481.65

**Comment by SuperSodaSea** [comment]
I can't reproduce this on my own mobile Chrome 110, so this might be a Galaxy-specific issue. However I do find some code that can probably cause this problem:

<https://github.com/pixijs/pixijs/blob/c2b79ef4e640267ffbabad189c1c00b88a4c1757/packages/mesh-extras/src/geometry/RopeGeometry.ts#L169-L208>

If `lastPoint` and `nextPoint` have the same coordinate, this can lead to NaN in vertices data.

**Comment by neizzz** [comment]
I touched above reproduced code (https://www.pixiplayground.com/#/edit/80Nf5kQ4IfIFgoCCy9gqA) on what you said.

I tried that elements in `this.buffers[0].data` in `RopeGeometry` was modified `0` when `NaN`, from adding below code to top of the editor.

```javascript
/** added(2023-03-01) */
const tmpUpdateVertices = PIXI.RopeGeometry.prototype.updateVertices;
PIXI.RopeGeometry.prototype.updateVertices = function() {
  tmpUpdateVertices.apply(this);
  this.buffers[0].data = this.buffers[0].data.map(num => isNaN(num) ? 0 : num);
  console.log(this.buffers[0].data);
  this.buffers[0].update();
};
/**********/
```

Then, the problem was reproduced on the PC.

If you go into that site, you can see the reproduction.

**Comment by SuperSodaSea** [comment]
I will create a PR to fix this soon :)
