### ISSUE TITLE
Bug: Property 'getChildByName' does not exist on type 'DisplayObject

### ISSUE THREAD

**Issue by DemoorBug** [pixijs/pixijs#9186]
Writing it this way works, but why does it report an error?
![2023-02-20 4 38 28](https://user-images.githubusercontent.com/18387615/219973932-d442e2a0-13fc-4068-8b13-0782df36caa1.png)
or
![2023-02-20 4 41 08](https://user-images.githubusercontent.com/18387615/219974014-622301c8-923f-44f6-84c1-5bcb4ac22e36.png)

This will be a pain in the ass. Is there a good way to write it?
![2023-02-20 4 50 43](https://user-images.githubusercontent.com/18387615/219974423-8731507d-437e-4349-85fd-718eb9f0ab50.png)
or

![2023-02-20 5 01 29](https://user-images.githubusercontent.com/18387615/219974938-12839e70-c7c5-4dac-a64d-bb1e65d9c5af.png)

"typescript": "^4.9.4"
"pixi.js": "7.1.2"

**Comment by miltoncandelero** [comment]
The thing is, nothing guarantees that the child you found is a container.
That's why it's nagging you.

**Comment by DemoorBug** [comment]
Whether it's Container or Graphics or Sprite, they all have getChildByName.
I'm just using pixijs, can you tell me more about it?

**Comment by SuperSodaSea** [comment]
The inheritance hierarchy is `DisplayObject` -> `Container` -> `Graphics` / `Sprite` / ..., so one can create a `DisplayObject` that is not a `Container` (although not very common).
Maybe you can use `app.stage.getChildByName<Container>('name')`?

**Comment by DemoorBug** [comment]
```tyepscript
app.stage.getChildByName<Container>('spriteGroupSences').getChildByName<Container>('sencel1').getChildByName<Container>('name')
```
thank you.
