### ISSUE TITLE
Bug: EventEmitter#once triggers handlers multiple times (like on) in PixiJS v7

### ISSUE THREAD

**Issue by Feu-Secret** [pixijs/pixijs#9195]
### Current Behavior

- The handler is triggered multiple times.

### Expected Behavior

- The handler should only be triggered once.
- Was working with PIXI v6.

### Steps to Reproduce

See the fiddle. Basically, create events with `once` and see the handler be called multiple times.

### Environment

- **`pixi.js` version**: *7.2.0-beta*
- **Browser & Version**: *Chrome 110.0.5481.104 (Official Build) (64-bit)*
- **OS & Version**: *Window 11*
- **Running Example**: *[https://jsfiddle.net/c09xvy27/6/](https://jsfiddle.net/c09xvy27/6/)*

**Comment by SuperSodaSea** [comment]
It seems that the problem started with `pixi.js@7.0.0-alpha`. On `pixi.js@6.5.9` it works fine.

<https://www.pixiplayground.com/#/edit/rFPYP7h9hrdUlc_s4TEf->

**Comment by SuperSodaSea** [comment]
It seems that we are using the internal storage of `EventEmitter` directly instead of `EventEmitter.emit`, causing this issue.

<https://github.com/pixijs/pixijs/blob/28bc3f775fbb28babb354dd57269dce09ac23f26/packages/events/src/EventBoundary.ts#L1361-L1389>
