### ISSUE TITLE
Bug: Pixi@7.1.2 renderer.extract is missing in type declarations

### ISSUE THREAD

**Issue by Oikio** [pixijs/pixijs#9207]
### Current Behavior

VSCode:

```ts
import * as PIXI from 'pixi.js'

const app = new PIXI.Application()
app.renderer.extract // Property 'extract' does not exist on type 'IRenderer<ICanvas>'.ts(2339)
app.renderer.prepare // Same issue

```
It is only type issue, `extract` is present in runtime.

### Expected Behavior

`renderer.extract` and `render.prepare` should be defined according to https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide#extract-and-prepare-systems.

### Steps to Reproduce

Code above in VSCode.

### Environment

- **`pixi.js`**: 7.1.2
- **OS & Version**: MacOS 12.6
- **Running Example**: not reproducible in playground https://pixiplayground.com/#/edit/r-0u8TgLNRyU5thWn2i5K
- **Typescript** 4.9.5

### Possible Solution

Looking through types, found `extract` only here:
```ts
// @pixi/extract/global.d.ts
declare namespace GlobalMixins
{
    interface Renderer
    {
        readonly extract: import('@pixi/extract').Extract;
    }
}
```
Including it via tsconfig does not solve the issue, could it be that declaration merging fails somewhere down the line?

### Additional Information

My `tsconfig.json` for reference:
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ESNext", "DOM"],
    "moduleResolution": "Node",
    "jsx": "react-jsx",
    "strict": true,
    "noImplicitAny": true,
    "noImplicitOverride": true,
    "noImplicitThis": true,
    "noUncheckedIndexedAccess": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "skipLibCheck": true
  },
  "include": ["src"]
}
```

**Comment by SuperSodaSea** [comment]
Yeah, this can be confusing for users. We have two different `Extract`s:

- `Extract` for (WebGL)`Renderer`
- `CanvasExtract` for `CanvasRenderer`

So `Extract` is for `Renderer` but not `IRenderer`. Since `Extract` and `CanvasExtract` have the same interface, I think we can add an `IExtract` interface for `IRenderer`. As for now, you can use `(app.renderer as Renderer).extract` as a workaround.

**Comment by Oikio** [comment]
Thank you, that's what ended up with.
