### ISSUE TITLE
Bug: Load Web Font Warning

### ISSUE THREAD

**Issue by meghe2000** [pixijs/pixijs#9231]
### Current Behavior

![image](https://user-images.githubusercontent.com/85949855/222721239-03853599-2f13-4560-a321-fd16be04b7ad.png)

in: node_modules/pixijs/assets/loader/parsers/loadWebFont.mjs?

### Expected Behavior

I don't want this warning to be displayed.

### Steps to Reproduce

`
    Assets.addBundle('fonts', { f1: loader('f1.woff2'), f2: loader('f2.ttf'), f3: loader('f3.otf') })
`

--------------
`
    Assets.loadBundle('fonts').then(e => {
        title.style.fontFamily = text.style.fontFamily = ok.style.fontFamily = e.f3.family
        setTimeout(() => all.addChild(title, text, ok), 110)
    })
`

### Environment

- **`pixi.js` version**: *e.g. 7.1.1*
- **Browser & Version**: *e.g. Chrome 109*
- **OS & Version**: *e.g. Windows 11*

**Comment by bigtimebuddy** [comment]
Could you create a minimal reproduction of this? Would help us be able to verify.

**Comment by SuperSodaSea** [comment]
I have also encountered this warning when loading large fonts (enabling slow network in Chrome's console can better reproduce this issue).
It seems that setting `display` option in the `FontFace`'s constructor to a value other than `'auto'` (`'block'`, `'swap'`, `'fallback'`, `'optional'`) can suppress this warning. Not very sure which value is the best one.

Here are some related links:
- <https://chromestatus.com/feature/5636954674692096>
- <https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display>
- <https://stackoverflow.com/questions/40143098/why-does-this-slow-network-detected-log-appear-in-chrome/51872074#51872074>

**Comment by meghe2000** [comment]
> I have also encountered this warning when loading large fonts (enabling slow network in Chrome's console can better reproduce this issue). It seems that setting `display` option in the `FontFace`'s constructor to a value other than `'auto'` (`'block'`, `'swap'`, `'fallback'`, `'optional'`) can suppress this warning. Not very sure which value is the best one.
> 
> Here are some related links:
> 
> * https://chromestatus.com/feature/5636954674692096
> * https://developer.mozilla.org/en-US/docs/Web/API/FontFace/display
> * https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
> * https://stackoverflow.com/questions/40143098/why-does-this-slow-network-detected-log-appear-in-chrome/51872074#51872074

how set font-display in pixijs loader?

**Comment by SuperSodaSea** [comment]
> how set font-display in pixijs loader?

Need to modify the source code of PixiJS (loadWebFont.ts)

**Comment by meghe2000** [comment]
This issue must be fundamentally resolved.

**Comment by SuperSodaSea** [comment]
Well, I rechecked the code and it seems we don't need to modify the PixiJS source code to suppress these warnings. You can try the following code to add the `display` option:

```js
Assets.addBundle('fonts', {
    f1: { src: 'f1.woff2', data: { display: 'swap' } },
    f2: { src: 'f2.woff2', data: { display: 'swap' } },
    f3: { src: 'f3.woff2', data: { display: 'swap' } },
});
```

**Comment by meghe2000** [comment]
This issue has been successfully resolved, thank you very much
