### ISSUE TITLE
Bug: Initializing application with transparent property set is not working since 7.0.0

### ISSUE THREAD

**Issue by CristianVladescu** [pixijs/pixijs#9239]
### Current Behavior

This snippet shows a black canvas even though the application was initialized with transparent property set.
https://codepen.io/CristianVladescu/pen/YzOQVeM

### Expected Behavior

The canvas should be transparent, and it was until 7.0.0.

### Steps to Reproduce

https://codepen.io/CristianVladescu/pen/YzOQVeM

### Environment

https://codepen.io/CristianVladescu/pen/YzOQVeM

**Comment by bigtimebuddy** [comment]
The option transparent was deprecated in v7. Please use backgroundAlpha instead (0-1).
