### ISSUE TITLE
Bug: angular 15 offscreen canvas not found

### ISSUE THREAD

**Issue by ovord** [pixijs/pixijs#9240]
### Current Behavior

Hi, 

build a project from scratch and realized angular 15 is missing things like an off-screen canvas and i cant set the app view in the dom. getting the following error msg:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/12304483/222952885-6247dff9-ecbf-4906-9231-b1540cb5eecd.png">

any ideay, should i better avoid to use angular with pixi-js?

thanks, great project, love it!

### Expected Behavior

view should be settable in DOM.

### Steps to Reproduce

``create an angular app
ng new
npm install pixi.js
npm install rxjs
Go to the tsconfig.json and add allowSyntheticDefaultImports: true

```export class AppComponent implements OnInit {
  private app: PIXI.Application = new PIXI.Application({
    width: window.innerWidth,
    height: window.innerHeight
  });

  ngOnInit(): void {
    document.body.appendChild(this.app.view);
  }
}
```

and import 
import * as PIXI from 'pixi.js'; 

### Environment

-   "pixi.js": "^7.1.4",
- **OS & Version**: osx

**Comment by SuperSodaSea** [comment]
`new PIXI.Application<HTMLCanvasElement>()`

**Comment by ovord** [comment]
thanks dude for the quick one.

you have also a solution for this:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/12304483/222953577-0c0400fc-675c-46be-bfb5-052796080037.png">

Oliver

**Comment by SuperSodaSea** [comment]
> thanks dude for the quick one.
> 
> you have also a solution for this: <img alt="image" width="923" src="https://user-images.githubusercontent.com/12304483/222953577-0c0400fc-675c-46be-bfb5-052796080037.png">
> 
> Oliver

This is very similar to #9234, maybe you can try to add `"types": ["offscreencanvas"]` in tsconfig.app.json?

**Comment by ovord** [comment]
duplicate https://github.com/pixijs/pixijs/issues/9234
