### ISSUE TITLE
Bug: `FederatedPointerEvent.shiftKey` always set to false

### ISSUE THREAD

**Issue by jakerdy** [pixijs/pixijs#9241]
### Current Behavior

When you try to access `shiftKey` property directly it alway will be set to false. Even when you actually hold shift.
But, if you access it via `(ev as any).originalEvent.shiftKey`, you get correct shiftKey state.

### Expected Behavior

It should work as altKey or ctrlKey

### Steps to Reproduce

Just add simple event handler on stage `pointerdown` event, and print shiftKey to console, it wont work.

### Environment

- **`pixi.js` version**: *7.1.4*
- **Browser & Version**: *Chrome 110*
- **OS & Version**: *Windows 10*

### Possible Solution

Reimplement `shiftKey` property, so that it retrieves data from originalEvent, and not from nativeEvent

### Aditional information

Also i've found that if shift wasn't pressed, originalEvent will be undefined.
So that workarround using originalEvent could break in a bad way if you not expecting true and undefined in your logic...

**Comment by bigtimebuddy** [comment]
Thanks for reporting. Seems like a bug.

Reproduction: https://pixiplayground.com/#/edit/f8EPRf3qJ9NGiyxMo01og
