### ISSUE TITLE
Bug: unsafe-eval regression, new Function call

### ISSUE THREAD

**Issue by skystedt** [pixijs/pixijs#9248]
### Current Behavior

`unsafe-eval` will try to test CSP for `new Function` before patching, this is a regression of #7545
This was introduced when making `unsafe-eval` self-installed, #8805

Additionally if Trusted Types are enabled, there will be console errors in the browser
![image](https://user-images.githubusercontent.com/14965238/223847384-2d32453b-4663-4766-87aa-90d051de2b81.png)

### Expected Behavior

Remove testing for `unsafeEvalSupported`
It wasn't used while manually installing so shouldn't be needed for self-installing

Or if it's preferred to keep it, provide an alternative way to install `unsafe-eval` without first testing for `unsafeEvalSupported`

### Steps to Reproduce

The documented example for `unsafe-eval` can be used to reproduce this.
https://github.com/pixijs/pixijs/blob/dev/packages/unsafe-eval/README.md#usage

Trusted Types can be enabled by adding:
`<meta http-equiv="Content-Security-Policy" content="script-src 'self'; require-trusted-types-for 'script'" />`

### Environment

- **`pixi.js` version**:  7.1.0 and later

**Comment by SuperSodaSea** [comment]
Thanks for reporting this issue, I will fix this ASAP.
