### ISSUE TITLE
Feature Request: Support loading SVG / JSON / TXT assets in data URLs

### ISSUE THREAD

**Issue by SuperSodaSea** [pixijs/pixijs#9256]
### Description

Currently `loadSVG`, `loadJson` and `loadTxt` doesn't support data URLs yet, so we can't do something like `PIXI.Assets.load('data:image/svg+xml,...')`. I will make a PR for this later.

**Comment by bigtimebuddy** [comment]
I agree, it would be nice to handle this automatically. I think the workaround would be to use #9226.

```js
PIXI.Assets.load({
  src: 'data:image/svg+xml,...'
  loadParser: 'loadJson'
})
```

**Comment by MannySVK** [comment]
Sorry in advance if i'm off topic but is there any way how to load `.webm` files via `PIXI.Assets.load('https://someurl.com/video.webm')`? When i try it, i get an error `could not be loaded as we don't know how to parse it, ensure the correct parser has being added`.

**Comment by SuperSodaSea** [comment]
@MannySVK It seems that `PIXI.Assets` do not support loading video yet, you can try to use `PIXI.Texture.from('https://someurl.com/video.webm')` as a workaround. If you really want `PIXI.Assets` to support video, you are welcomed to make a [Feature Request](https://github.com/pixijs/pixijs/issues/new?assignees=&labels=Feature+Request&template=feature_request.yml&title=Feature+Request%3A+)!
