### ISSUE TITLE
Bug: Custom hitArea with v7 trigger wrong event targets

### ISSUE THREAD

**Issue by rwampler** [pixijs/pixijs#9257]
### Current Behavior

`pointerup` events are fired with different `target` sprites than immediately preceding `pointerdown` events, when dealing with multiple containers and custom hit areas.

### Expected Behavior

`pointerup` events are fired for the same `target` as `pointerdown` events, even for sprites with custom hit areas in separate containers

### Steps to Reproduce

https://jsfiddle.net/r5L128j0/

1. Click and hold down on a sprite, to see it change color (tint)
2. On release, a different sprite will then change color (when different containers)

### Environment

- **`pixi.js` version**: 7.2.0-rc.2
- **Browser & Version**: Chrome 109
- **OS & Version**: Windows 10
- **Running Example**: https://jsfiddle.net/r5L128j0/

### Additional Information

Believe I was able to debug and trace flow:

1. A native `pointerup` event fired: https://github.com/pixijs/pixijs/blob/4dc31fc9e77c357b3c1b52ec60c7e2f01b102c9c/packages/events/src/EventSystem.ts#L411
3. Eventually internal event is created and pixi target set: https://github.com/pixijs/pixijs/blob/4dc31fc9e77c357b3c1b52ec60c7e2f01b102c9c/packages/events/src/EventBoundary.ts#L1118
4. To set target, search recursively through all items: https://github.com/pixijs/pixijs/blob/4dc31fc9e77c357b3c1b52ec60c7e2f01b102c9c/packages/events/src/EventBoundary.ts#L390
5. A first step of searching is to prune, including for hitArea, but are hitting the bail case right before check: https://github.com/pixijs/pixijs/blob/4dc31fc9e77c357b3c1b52ec60c7e2f01b102c9c/packages/events/src/EventBoundary.ts#L505
6. A final step is to confirm hit, but logic only checks existence of hitArea, assuming previous prune would handle non-matching case: https://github.com/pixijs/pixijs/blob/4dc31fc9e77c357b3c1b52ec60c7e2f01b102c9c/packages/events/src/EventBoundary.ts#L547

As a result of not doing hitArea prune in 4), wrong sprite is selected with 5). When checking `_hitElements[0]`, the value was the desired clicked on sprite, but would not match the actual `target` or `currentTarget` chosen for event

Was wondering if behavior tied to potentially skipping `mapPointerMove` logic (with new Application-level event flags), but seem to see behavior regardless of flags (https://github.com/pixijs/pixijs/blob/4dc31fc9e77c357b3c1b52ec60c7e2f01b102c9c/packages/events/src/EventBoundary.ts#L643)

**Comment by Zyie** [comment]
Oh interesting, thanks for digging into this!

I will try to fix it
