### ISSUE TITLE
Bug: `globalpointermove` now works like `pointermove`

### ISSUE THREAD

**Issue by jakerdy** [pixijs/pixijs#9271]
### Current Behavior

If you add `globalpointermove` event handler to displayobject, it will behave like `pointermove`. If object 'dragged' outside of it's hit area events wouldn't be received.

### Expected Behavior

Events should be received like it was at 7.1.1 when `globalpointermove` was introduced.

### Steps to Reproduce

Check [sandbox](https://pixiplayground.com/#/edit/wdkmY-Us0tP53ld6_Y3QU).
Or:
Subscribe to `globalpointermove` at some specific displayobject and print/visualize event handling somehow.

### Environment

- **`pixi.js` version**: 7.2.0
- **Browser & Version**: Chrome 108
- **OS & Version**: Windows 10
- **Running Example**: https://pixiplayground.com/#/edit/wdkmY-Us0tP53ld6_Y3QU

### Possible Solution

🤔

### Additional Information

Somewhat i uderstand why that was happend (thanks for release notes). But i couldn't say that i am completeley happy with proposed solution.

The main inconvenience is that single page (html document) could conatain multiple PIXI applications.
And if with html document you could just use global `document`, with pixi you should pass reference to specific pixi application that has ownership of target "draggable" displayobject. It isn't alway convenient, and introduces aditional dependencies to "outside world".

Well, if you are decided to drop this behaviour, why not just remove `globalpointermove` from displayobject completely and/or put some explicit warning like it was made to `interactive: boolean` property?

**Comment by Zyie** [comment]
This seems to be an issue with setting `rect.hitArea`. If that is removed from your example then it works

I will look into fixing this asap
