### ISSUE TITLE
Bug: mouseover stopped working 7.1.0 → 7.1.1/7.2.0

### ISSUE THREAD

**Issue by reececomo** [pixijs/pixijs#9274]
### Current Behavior

Hi there 👋  after upgrading from 7.1.0 to 7.1.1 or 7.2.0/7.2.0-rc2, the behaviors of `cursor = 'pointer'` and `.on('mouseover')` / `.on('mouseleave')` (and their pointer equivalents) has stopped working in our projects. Had a dig through the docs and the recent PRs and can't quite see what the issue is. Guessing it's a change to do with how the ancestors settings are inherited?

Tried setting the new `eventMode` to `static` and `dynamic` with no luck.

Seems to also be some big performance drops. Not sure what's been happening with PIXI recently but its been a bit unstable version-to-version since v6.

### Expected Behavior

Would expect it to work, or for there to be an easy-to-find upgrade guide

### Steps to Reproduce

Add objects nested a few deep with `cursor = 'pointer'` and `.on('mouseover')`. Events do not fire and cursor does not change to a pointer.

### Environment

- **`pixi.js` version**: 7.1.0
- **Browser & Version**: Chrome / Safari
- **OS & Version**: MacOS / Windows 10

**Comment by bigtimebuddy** [comment]
Can you please provide a reproduction?

**Comment by reececomo** [comment]
In a standalone project? Maybe if I get some time next week 👍

**Comment by bigtimebuddy** [comment]
Yeah, like a minimal reproduction of the issue. Jsfiddle, codepen, codesandbox are good options (or a stand-alone repo). It gives us something to validate the bug and verify it's been fixed.

**Comment by bigtimebuddy** [comment]
One thing to check: if you're upgrading, could you please refer to this [upgrading doc](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS) and see if that has any impact. Check your package-lock.json, yarn.lock etc for duplicate instances of "@pixi/*". Everything _should_ be the same version.
