### ISSUE TITLE
Bug: New 🌈 Color change broke pixi-spine tint

### ISSUE THREAD

**Issue by SerG-Y** [pixijs/pixijs#9277]
### Current Behavior

It's hard to explain :) Actually, it's better to compare the images.
I am pretty sure it's related to these two lines in SpineBase:
https://github.com/pixijs/spine/blob/7903e9dae81a855a6725d13789f31ca70260ede8/packages/base/src/SpineBase.ts#L328
https://github.com/pixijs/spine/blob/7903e9dae81a855a6725d13789f31ca70260ede8/packages/base/src/SpineBase.ts#L386
Do you have any idea why it broke pixi-spine? 

<img width="299" alt="image" src="https://user-images.githubusercontent.com/12532719/225968027-2140ad80-4793-4c65-b9de-92157875d1d2.png">

### Expected Behavior

<img width="340" alt="image" src="https://user-images.githubusercontent.com/12532719/225968253-417f5f88-e9d7-4a84-9119-f3bf3fbd6d30.png">

### Steps to Reproduce

I think it's easy to reproduce with any spine project that has tint stuff

### Environment

- **`pixi.js` version**: *7.2.0*
- **`pixi-spine` version**: *4.0.3*

**Comment by bigtimebuddy** [comment]
@SerG-Y we need a repo on this. I tried using the public examples and applying a tint and it did what I would expect.

**Comment by SerG-Y** [comment]
@bigtimebuddy I will try to investigate it a bit more if not I will back with repo.
but changing `core.utils.rgb2hex` to old `rgb2hex` made a trick
`function rgb2hex(rgb) {
  return (((rgb[0] * 255) << 16) + ((rgb[1] * 255) << 8) + (rgb[2] * 255 | 0));
}`

**Comment by SerG-Y** [comment]
Hi @bigtimebuddy, can you please tag someone who can take a look at my PR. Thanks!

**Comment by bigtimebuddy** [comment]
I think the better fix here is replace `this._value !== value` with a deep-equality. It seems totally reasonable to re-use an object, liken an array and re-set the Color value.

**Comment by SerG-Y** [comment]
@bigtimebuddy I think a deep-equality will not help here. Because `this._value` is a reference to an array and when you change a value in an array it also will be changed in `this._value` as it's a reference. So, with deep-equality result will be the same. Did I miss something?

**Comment by SuperSodaSea** [comment]
Maybe we can deep copy the value when setting it.

**Comment by SerG-Y** [comment]
@SuperSodaSea sounds good!

**Comment by SerG-Y** [comment]
@miltoncandelero in this case can you please revert my commit from pixi-spine as it's not needed anymore.

**Comment by FloodGames** [comment]
Deprecates the following color utilities (https://github.com/pixijs/pixijs/pull/9061) @bigtimebuddy
utils.rgb2hex => new Color(rgb).toNumber()
