### ISSUE TITLE
Bug: Wrong hit area in shadow DOM (7.2.2 too)

### ISSUE THREAD

**Issue by naramdash** [pixijs/pixijs#9291]
### Current Behavior

Event occurs in weird position.

https://user-images.githubusercontent.com/24370799/227459296-bedddf41-7085-404f-9aa7-0425b4ae00a9.mp4

### Expected Behavior

Hit area should be properly calculated when pixi is embedded in custom elements with shadow DOM enabled.

### Steps to Reproduce

Append Pixi.view inside shadowRoot.

and

Give the body a margin, but not the custom element.

### Environment

- **`pixi.js` version**: *7.2.2*
- **`@pixi/events` version**: *7.2.2*
- **Browser & Version**: *Chrome 111*
- **OS & Version**: *Windows 11*

### Possible Solution

Maybe https://github.com/pixijs/pixijs/issues/8281/ was same issue of version 6.

**Comment by Zyie** [comment]
Hey!

The code that fixed this last time is still present so it could be a new issue. However we do currently have a few bugs with events in 7.2.2 that will be fixed in the next release

Could you provide a minimal reproduction of the issue. Jsfiddle, codepen, codesandbox etc to give us something to validate the bug and verify it's been fixed

**Comment by naramdash** [comment]
[codesandbox](https://codesandbox.io/p/github/naramdash/test-pixi-7.2-shadowdom-event/main?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clfn8v75n0008g1etb4gr9mae%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfn8vc5f00153n6iqa3lek4p%2522%253A%257B%2522key%2522%253A%2522clfn8vc5f00153n6iqa3lek4p%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clfn8ygsa00153n6is39p1l8s%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clfn8vffx007h3n6iyv3wi3yv%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clfn8vedh004n3n6i7jd53wdc%2522%252C%2522isMinimized%2522%253Atrue%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clfn8vc5f00153n6iqa3lek4p%2522%252C%2522spacesOrder%2522%253A%255B%2522clfn8vc5f00153n6iqa3lek4p%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)
[github repo](https://github.com/naramdash/test-pixi-7.2-shadowdom-event)

this is tiny reproduction of issue.

**Comment by Zyie** [comment]
should be fixed with #9354
