### ISSUE TITLE
Container add Text will be scale ?

### ISSUE THREAD

**Issue by jingyuLin1999** [pixijs/pixijs#9297]
### Current Behavior

I add text to container, container be scale. like below

abnormal:

![image](https://user-images.githubusercontent.com/30433062/227701262-1a334ca1-a782-4187-abd0-7f3c189de172.png)

normal:

![image](https://user-images.githubusercontent.com/30433062/227701232-e93a7b10-ec6e-4b03-899a-ff6e4919dcac.png)

### Expected Behavior

fix this bug

### Steps to Reproduce

```js
    let vm = {
    _ui2Attrs: {
         globalTooltip:{}
      }
    };
    vm._ui2Attrs._axisArea = new pixi.Container()
    vm._ui2Attrs._axisArea.name = "_axisArea"
    vm._ui2Attrs._axisArea.sortableChildren = true
    vm._app.stage.addChild(vm._ui2Attrs._axisArea)

    vm._ui2Attrs.globalTooltip.container = new pixi.Container()
    vm._ui2Attrs.globalTooltip.container.visible = true
    vm._ui2Attrs.globalTooltip.container.sortableChildren = true
    vm._ui2Attrs.globalTooltip.container.zIndex = 9
    vm._ui2Attrs._axisArea.addChild(vm._ui2Attrs.globalTooltip.container)
    vm._ui2Attrs.globalTooltip.tooltipText = new pixi.Text("", vm.tooltip.textStyle)
    vm._ui2Attrs.globalTooltip.tooltipText.name = "_text"
    vm._ui2Attrs.globalTooltip.tooltipText.scale.y = -1;
    // LOOK THIS
    // when i remove it, it work ok
    vm._ui2Attrs.globalTooltip.container.addChild(vm._ui2Attrs.globalTooltip.tooltipText)  
```

### Environment

- **`pixi.js` version**: *6.3.2*
- **Browser & Version**: *Chrome  111.0.5563.111*
- **OS & Version**: *win10*
- **Running Example**: *none*

**Comment by SuperSodaSea** [comment]
I can't reproduce your issue in PixiJS 6.3.2: <https://www.pixiplayground.com/#/edit/IyyUaQTBX1-CBLPaz0Lr9>. Can you create a minimal reproduction?

**Comment by jingyuLin1999** [comment]
Thanks for your reply.  This issue is caused by me updating the length and width of the container  with high-frequency.  Thanks again!
