### ISSUE TITLE
Bug: Some mouse events not triggered in certain situations Pixi 7.2.3

### ISSUE THREAD

**Issue by daserra** [pixijs/pixijs#9299]
### Current Behavior

After migrating from PIXI 7.1.1 to 7.2.3 some of my buttons do not work anymore.

What I have is a Container that receives all the listeners also where I set 
`container.cursor = "pointer";
  container.eventMode = "dynamic";`
Then I add a spine animation as child of this container. The button click works but mouse over and mouse out won't.

### Expected Behavior

All the button listeners including mouse over and mouse out work correctly.

### Steps to Reproduce

You can reproduce the issue here https://codesandbox.io/s/blissful-benji-fjsf70

### Environment

- **`pixi.js` version**: *7.2.3*
- **Browser & Version**: *Chrome Version 111.*
- **OS & Version**: * MacOS 13.2.1*

**Comment by Zyie** [comment]
Thanks for reporting this!
It could be related to this issue as well #9274 but now we have an example

It seems that over/out only fire when starting outside of the stage

**Comment by Zyie** [comment]
woops
