### ISSUE TITLE
Bug: Default ticker runs on every animation frame

### ISSUE THREAD

**Issue by romgrk** [pixijs/pixijs#9306]
### Current Behavior

Pixi seems to be adding a default ticker even if I'm not adding one myself. I'd like that there is no ticker running so I can conserve my CPU cycles for other stuff.

![image](https://user-images.githubusercontent.com/1423607/228134740-3f22401f-8388-4557-a083-8c85390c3c55.png)

![image](https://user-images.githubusercontent.com/1423607/228134662-71aeedc6-b405-4af6-94e4-792b20681883.png)

![image](https://user-images.githubusercontent.com/1423607/228134876-cffd0bba-eedc-434c-9f61-e2e06f236391.png)

### Expected Behavior

No default ticker

### Steps to Reproduce

I'm using the canvas renderer, don't have a reproducible case to show here but I feel like the issue would happen on any example that runs pixi code. Let me know if you need more here.

### Environment

- **`pixi.js` version**: `"pixi.js-legacy": "^7.1.1"`
- **Browser & Version**: `1.49.128 Chromium: 111.0.5563.110 (Official Build) (64-bit) `
- **OS & Version**: `archlinux`

**Comment by bigtimebuddy** [comment]
Use Ticker.system.stop() to disable.
