### ISSUE TITLE
Feature Request: TypeScript: ParticleContainer should support Generic Sprite type

### ISSUE THREAD

**Issue by volodalexey** [pixijs/pixijs#9348]
### Description

I followed the history and [found](https://github.com/pixijs/pixijs/pull/8433#issuecomment-1165549672) that `ParticleContainer` should use only `Sprite` as children.
```typescript
export declare class ParticleContainer extends Container<Sprite> {
```

However it is very uncovenient to iterate through `Sprite`s only if I have custom functions:
```typescript
class Particle extends Sprite {
  handleUpdate(): void {
  }
}
const container = new ParticleContainer(100, { position: true, scale: true })

container.children.forEach(child => {
  (child as Particle).handleUpdate()
})
```

I suggest to improve TS type:
```typescript
export declare class ParticleContainer<T extends Sprite = Sprite> extends Container<T> {
```
So it will be similar to regular `Container` and I can use it with my custom `Sprite`s:
```typescript
const container = new ParticleContainer<Particle>(100, { position: true, scale: true });
container.children.forEach(child => {
  child.handleUpdate()
})
```

**Comment by bigtimebuddy** [comment]
Good improvement. Feel free to make PR for this change.
