### ISSUE TITLE
Bug: pointerout triggers when moving to a Container's child within it's hit area

### ISSUE THREAD

**Issue by Beastly418** [pixijs/pixijs#9383]
### Current Behavior

When moving the mouse over an interactive container's child it fires the parent's "pointerout" event even while it's still within the bounding box of the parent.

### Expected Behavior

Moving the mouse over the child of a container would not fire the parent's "pointout" event even while it's still within the bounding box of the parent.

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/BQoC4m7WT5oyTbC0CDmJ9

### Environment

- **`pixi.js` version**: *7.1.2*
- **Browser & Version**: *Firefox 111.01*
- **OS & Version**: *Windows 10 22H2 19045.2846*
- **Running Example**: *[e.g. <https://pixiplayground.com/>](https://www.pixiplayground.com/#/edit/BQoC4m7WT5oyTbC0CDmJ9)*

**Comment by Beastly418** [comment]
My immediate work around that seems to be working is using pointerleave instead of pointerout.

Still might be a bug though?

**Comment by Zyie** [comment]
This should be resolved in the latest version of pixi `7.2.4`

Feel free to reopen if updating doesn't solve your issue
