### ISSUE TITLE
Feature Request: Support colors with alpha for TextStyle fill, stroke, etc

### ISSUE THREAD

**Issue by lichspace** [pixijs/pixijs#9384]
### Current Behavior

rgba not work

### Expected Behavior

rgba work~

### Steps to Reproduce

```
new Text('hello world', {
  fontSize: 80,
  fill: 'rgba(243, 33, 22, 0.3)',
});
```

equal 

```
const text = new Text('hello world', {
  fontSize: 80,
  fill: 'rgba(243, 33, 22)',
});
```

### Environment

latest version

**Comment by bigtimebuddy** [comment]
This is the intended behavior not a bug. `stroke, `fill` and  `dropShadowColor` TextStyle properties do not support alpha, they take the input and normalize the color into a non-alpha hex string (e.g., `#ffcc00`). This shouldn't be too difficult to support here:

https://github.com/pixijs/pixijs/blob/00009c14d64e3b15b900977ee188c3613f1ffa04/packages/text/src/TextStyle.ts#L867

**Comment by lichspace** [comment]
thanks @bigtimebuddy , i will pull request this feature.
