### ISSUE TITLE
Bug: Can't modify the color of a particular character in the text

### ISSUE THREAD

**Issue by mcclove** [pixijs/pixijs#9397]
### Current Behavior

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>PIXI.js Demo</title>
    <link rel="stylesheet" href="style.css"> 
</head>
<body>
    <div id="pixi-container"></div>
    <script src="pixi.min.js"></script>
    <script>
        let renderer = PIXI.autoDetectRenderer(800, 600);
        let stage = new PIXI.Container();

        let text = new PIXI.Text('Hello PIXI!', {
            fill: 0xFFFFFF,   // 白色
            fontSize: 64
        });
        text.style.fill[2] = 0xFFFF00;   // 设置第3个字符为黄色

        stage.addChild(text);
        document.getElementById("pixi-container").appendChild(renderer.view);
        renderer.render(stage);   // 渲染
    </script>
</body>
</html>

### Expected Behavior

 text.style.fill[0]not execute

### Steps to Reproduce

How should I modify the color of a particular text in the text

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by SuperSodaSea** [comment]
`Text` don't support specifying colors for specific characters. You can use `HTMLText` instead (supported in PixiJS 7.2.0+):

```js
const text = new PIXI.HTMLText(
    'Hello, <span style="color: #F10061">PixiJS</span>!',
    { fontSize: 32, fill: 0xFFFFFF });
app.stage.addChild(text);
```

Demo: <https://pixiplayground.com/#/edit/xm3ONb8ibfvpZU2tH5rRt>
