### ISSUE TITLE
Bug: Creating a Sprite from an ImageBitmap used to create a previously destroyed Sprite results in an empty Sprite

### ISSUE THREAD

**Issue by rj3d** [pixijs/pixijs#9403]
### Current Behavior

If I create a Sprite from an ImageBitmap, destroy that Sprite with the options `{ children: true, texture: true, baseTexture: true }`, and then try to create a new Sprite from the same ImageBitmap, the new Sprite will be empty when rendered.

### Expected Behavior

I expect to be able to create a new sprite using an ImageBitmap that was used to create a previously destroyed sprite. Some of the ImageBitmaps I am working with are large, and I need to remove them from the graphics card when not in use to prevent context losses. 

### Steps to Reproduce

Here is a playground that replicates the issue: [https://www.pixiplayground.com/#/edit/cW1MglcpTHTH_ViEEj4YJ](https://www.pixiplayground.com/#/edit/cW1MglcpTHTH_ViEEj4YJ)

If that doesn't work, here is a repo that reproduces the issue in a React component: [pixi-bitmap-error-example](https://github.com/rj3d/pixi-bitmap-error-example). If you download the repo you can run `npm install` and then `npm run dev` to start a local development server.

All of the pixi stuff takes place in the file [PixiTest](https://github.com/rj3d/pixi-bitmap-error-example/blob/main/src/pages/PixiTest.tsx) in the following section:

```
const bunnyDel = PIXI.Sprite.from(bitmap);
bunnyDel.destroy({ children: true, texture: true, baseTexture: true })

const bunny = PIXI.Sprite.from(bitmap);

bunny.x = 0;
bunny.y = 0;
        
this.stage.removeChildren()
        
this.stage.addChild(bunny);
        
this.renderer.render(this.rootContainer)
```

If you comment out the two lines that create and destroy the bunnyDel sprite then the bunny sprite renders as expected. However, with the bunnyDel lines in place the bunny sprite renders as empty.

### Environment

- **`pixi.js` version**:7.2.4
- **Browser & Version**: Chrome 112
- **OS & Version**: macOS 12.6.5

**Comment by rj3d** [comment]
I managed to reproduce this in the playground as well [https://www.pixiplayground.com/#/edit/cW1MglcpTHTH_ViEEj4YJ](https://www.pixiplayground.com/#/edit/cW1MglcpTHTH_ViEEj4YJ)

**Comment by SuperSodaSea** [comment]
Seems to be caused by this:

<https://github.com/pixijs/pixijs/blob/a02b2385fdff763a6b188c7635355ac38ccdd92f/packages/core/src/textures/resources/ImageBitmapResource.ts#L168-172>

When `BaseTexture` is destroyed, the `dispose()` is called on its underlying `ImageBitmapResource`, disposing the `ImageBitmap`.

**Comment by SuperSodaSea** [comment]
Need to add a flag to `ImageBitmapResource` to indicate whether it owns the underlying `ImageBitmap`.
