### ISSUE TITLE
Feature Request: Add an explanation of the buttonMode property to the API documentation. 

### ISSUE THREAD

**Issue by Gerocer** [pixijs/pixijs#9405]
### Description

The buttonMode cannot be found in the documentation.

**Comment by SuperSodaSea** [comment]
`buttonMode` is removed in PixiJS v7, see [v7 Migration Guide](https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide#property-buttonmode-has-been-removed). You can still find it in PixiJS v6 document: <https://pixijs.download/v6.x/docs/PIXI.DisplayObject.html#buttonMode>.

**Comment by Gerocer** [comment]
好的谢谢。那现在官网文档默认的是v7吗？但是例子里用的不是v7？

**Comment by SuperSodaSea** [comment]
<https://pixijs.download/dev/docs/index.html> 上的文档默认是最新的。具体是哪一个例子？

**Comment by Gerocer** [comment]
是文档guides里插入的例子，刚在新标签页打开才看到是v5的。这两个：https://pixijs.io/examples-v5/#/interaction/click.js和
https://pixijs.io/examples-v5/#/interaction/custom-hitarea.js。我觉得Guides里插入的例子是不是也更新为v7的比较好呀，不然像我这样的初学者可能会懵。

**Comment by SuperSodaSea** [comment]
Guides 里的 Interaction 部分确实已经完全过时了，之前其他人也有提到过（pixijs/guides#39），后面应该需要完全重写。有需要的话可以先参考下 v7 版的示例代码，例如 <https://pixijs.io/examples/#/events/interactivity.js>。(其实这些例子代码也不是最新的，7.2.0 版本开始建议将 `displayObject.interactive = true` 改成新的写法 `displayObject.eventMode = 'static'`，后面这些例子也需要更新。）

**Comment by Gerocer** [comment]
好的，谢谢你。
