### ISSUE TITLE
Bug: NineSlicePlance not working correctly with trimmed textures

### ISSUE THREAD

**Issue by astrocreep** [pixijs/pixijs#9417]
### Current Behavior

When using a trimmed texture for a nine slice plane, the neighbouring textures are displayed in the area that should be transparent.

### Expected Behavior

Only show the selected texture.

### Steps to Reproduce

Create an atlas with some trimmed sprites. Create a nine slice plane and use one of the textures in the atlas.

### Environment

- **`pixi.js` version**: *7.2.4*
- **Browser & Version**: *any*
- **OS & Version**: *macOS Ventura 13.3.1*

**Comment by bigtimebuddy** [comment]
I don't doubt this is try, but could you provide a running example so that we can have a simple case to verify?

**Comment by astrocreep** [comment]
> I had this too...
> I had to uncheck the trim in the texture packer to sprite sheets that I use textures to nine slices.

Sure, that works. But this is more of a temp fix than a solution...

**Comment by thundermarek** [comment]
https://github.com/pixijs/pixijs/issues/6451#issuecomment-936669985 my old fix still should work

**Comment by md5crypt** [comment]
https://github.com/pixijs/pixijs/issues/6451#issuecomment-936669985
my old fix should still work

**Comment by GoodBoyDigital** [comment]
fixed in v8 👍
