### ISSUE TITLE
Bug: Application no longer uses the global `resolution` setting (after updating from v7.1.3 to v7.2.4)

### ISSUE THREAD

**Issue by Julien-Marcou** [pixijs/pixijs#9429]
### Current Behavior

In v7.2.4, I have to do:

```ts
settings.RESOLUTION = window.devicePixelRatio; // I have an hi-dpi screen with a devicePixelRatio of 1.25
settings.RENDER_OPTIONS!.autoDensity = true; // I have to use a "!", otherwise I get an error about RENDER_OPTIONS potentially being undefined, it was not the case before

const application = new Application({
  resolution: settings.RESOLUTION,
});
```

If I don't set the application's resolution option to `1.25`, then the application's renderer has a resolution set to `1` and everything is blurry on my screen.

### Expected Behavior

In v7.1.3, I was able to do:

```ts
settings.RESOLUTION = window.devicePixelRatio; // I have an hi-dpi screen with a devicePixelRatio of 1.25
settings.RENDER_OPTIONS.autoDensity = true;

const application = new Application();
```

Here, the application's renderer has a `resolution` of `1.25` and nothing is blurry on my screen.

### Steps to Reproduce

- Set the global `settings.RESOLUTION` to a value different than 1
- Create a new application

The application's renderer has a resolution of 1 instead of the global resolution value (you can `console.log` the application to see the internal resolution value of the renderer).

### Environment

- **`pixi.js` version**: *7.2.4*
- **Browser & Version**: *Firefox 113* & *Chrome113*
- **OS & Version**: *Windows 11*

### Possible Solution

Manually set the resolution in the application's options.

### Additional Information

I don't know if it's an intended change or not, but I was not able to figure that out by looking at the changelog between the v7.1.3 & v7.2.4, so I'd rather report it as a bug so people may find this information somewhere while it's being clarified 😅

**Comment by bigtimebuddy** [comment]
Curious. I can definitely reproduce this. We did move around a bunch of things related to RENDER_OPTIONS in 7.2.x, so not a huge surprise.

I think there are a few minor issues going on here.

* RENDER_OPTIONS is set before the settings.RESOLUTION assignment, not exactly sure why this worked before, but should be easy to resolve
* Typing issue is making RENDER_OPTIONS optional, because `settings` is now `ISettings & Partial<GlobalMixins.Settings>`. there's probably a better way to do this without making optional

This does work:

```js
settings.RESOLUTION = window.devicePixelRatio;
settings.RENDER_OPTIONS.resolution = window.devicePixelRatio;
settings.RENDER_OPTIONS.autoDensity = true;

const application = new Application();
```

**Comment by hmpthz** [comment]
> Curious. I can definitely reproduce this. We did move around a bunch of things related to RENDER_OPTIONS in 7.2.x, so not a huge surprise.
> 
> I think there are a few minor issues going on here.
> 
> * RENDER_OPTIONS is set before the settings.RESOLUTION assignment, not exactly sure why this worked before, but should be easy to resolve
> * Typing issue is making RENDER_OPTIONS optional, because `settings` is now `ISettings & Partial<GlobalMixins.Settings>`. there's probably a better way to do this without making optional
> 
> This does work:
> 
> ```js
> settings.RESOLUTION = window.devicePixelRatio;
> settings.RENDER_OPTIONS.resolution = window.devicePixelRatio;
> settings.RENDER_OPTIONS.autoDensity = true;
> 
> const application = new Application();
> ```

Hi Matt,
I've compared the difference between v7.1 and v7.2. you can see how they initialize RENDER_OPTIONS in settings.ts:
v7.1: https://github.com/pixijs/pixijs/blob/39c67e00abe2dd592bf43d23b2559e646ab9791b/packages/settings/src/settings.ts
v7.2: https://github.com/pixijs/pixijs/blob/9ce9bd2c80837265b986e1fa7af37a3d9fb4393d/packages/core/src/settings.ts

v7.1 does not set resolution in RENDER_OPTIONS at all. Thus ViewSystem will look for settings.RESOLUTION instead.
While v7.2 initialize it with ViewSystem.defaultOptions.

As far as I'm concerned the settings in current state is really messed up, perhaps your team could clean it up some time in the future? 😃
