### ISSUE TITLE
Bug: Upgrading from 7.2.3 to 7.2.4 breaks Spine Loader

### ISSUE THREAD

**Issue by RichardGale** [pixijs/pixijs#9459]
### Current Behavior

With 7.2.4 using

import 'pixi-spine'; // Do this once at the very start of your code. This registers the loader!

to initialize the Spine Loader (you can set a breakpoint on InstallLoader and have it fire).

Later, when loading a URL with a ".skel" extension (setting a breakpoint in the test function does not fire) and the resources entry for that key is NULL.

### Expected Behavior

With 7.2.3 using

import 'pixi-spine'; // Do this once at the very start of your code. This registers the loader!

to initialize the Spine Loader (you can set a breakpoint on InstallLoader and have it fire).

Later, when loading a URL with a ".skel" extension (setting a breakpoint in the test function should fire) and the resources entry for that key have spine data.

### Steps to Reproduce

No code changes.

npm install pixi.js@7.2.3 or npm install pixi.js@7.2.4

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*
pixi.js ^7.2.4
pixi-spine ^4.0.4
webpack ^5.77.0
OSX 13.3.1
Brave 1.51.114

**Comment by miltoncandelero** [comment]
Are you getting an error saying there is no loader for skel files?

**Comment by RichardGale** [comment]
No. There is no error. The key in the returned resources is null in 7.2.4 and populated in 7.2.3

**Comment by RichardGale** [comment]
Deleted node_modules and package-lock.json with 7.2.4, reinstalled, works ok.
Deleted node_modules and package-lock.json with 7.2.3, reinstalled, works ok.
Deleted node_modules and package-lock.json with 7.2.3, reinstalled, upgraded to 7.2.4, works ok.

Unfortunately did not keep the broken state to debug this further.

For additional context I recently upgraded from 6.x to 7.x and then 7.2.3
