### ISSUE TITLE
Bug: Discord Link is once again expired

### ISSUE THREAD

**Issue by arvalaan** [pixijs/pixijs#9479]
### Current Behavior

Discord link under resources points to invalid link

### Expected Behavior

Discord link under resources points to valid link

### Steps to Reproduce

Browse to https://pixijs.com/, hover over Resources, click Discord

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by miltoncandelero** [comment]
I remember reading something about discord links no longer being forever? 🤔

**Comment by arvalaan** [comment]
I can still create an invite link that never expires:

<img width="439" alt="image" src="https://github.com/pixijs/pixijs/assets/9444629/1eba0b05-6614-4769-ba63-b32398afe0e1">

**Comment by arvalaan** [comment]
@miltoncandelero Would you happen to have a temp invite if possible?

**Comment by miltoncandelero** [comment]
I think this still works? https://discord.com/invite/apfqCs3b

**Comment by arvalaan** [comment]
<img width="441" alt="image" src="https://github.com/pixijs/pixijs/assets/9444629/1e1af795-73f2-4c7c-a69b-fe81620b3b94">

**Comment by domis86** [comment]
> I think this still works? https://discord.com/invite/apfqCs3b

It shows page with error (invalid invite)

**Comment by bigtimebuddy** [comment]
I'm seeing the same when opening in incognito mode on my Chrome browser.

**Comment by miltoncandelero** [comment]
https://discord.com/invite/zqbXQAADuM

https://discord.com/invite/QrnxmQUPGV

any of those two working?

**Comment by domis86** [comment]
> https://discord.com/invite/zqbXQAADuM
> 
> https://discord.com/invite/QrnxmQUPGV
> 
> any of those two working?

both working

**Comment by miltoncandelero** [comment]
Good, the second is the one already in the readme 😅

https://github.com/pixijs/pixijs/blob/dev/README.md?plain=1#L6

**Comment by GoodBoyDigital** [comment]
closing as we have updatd all the links 👍
