### ISSUE TITLE
Bug: Significant Performance Degradation in BitmapFont.from Function Between v5 and v6/v7

### ISSUE THREAD

**Issue by yordan-kanchelov** [pixijs/pixijs#9489]
### Current Behavior

In the latest versions of pixi.js (v6, v7), the execution time for the PIXI.BitmapFont.from function when creating multiple character sets significantly increases when compared to v5. Specifically, the code execution takes around 9 seconds.

### Expected Behavior

The execution time for the PIXI.BitmapFont.from function should not significantly differ between different versions of pixi.js. In v5, the execution time for the same operation was around 55 milliseconds.

### Steps to Reproduce

1. Run the provided script using pixi.js v5 - execution time is approximately 55 milliseconds.
2. Run the same script using pixi.js v6 or v7 - execution time is approximately 9 seconds.

This behavior can be observed through the provided JSFiddle links:

For v7: https://jsfiddle.net/v7uegcbf/2/
For v5: https://jsfiddle.net/hukqwxj9/8/

### Environment

Version of pixi.js: v6 and v7
Browser: All tested browsers
Operating System: All tested operating systems, including MacOS, Windows, Mobile iOS, and Android

### Additional Information

The issue is noticed when creating multiple character sets with the PIXI.BitmapFont.from function. Here's the code that reproduces the issue:

```js
function testBitmapFrom(): void {
    const charSet  = [
            ["a", "z"],
            ["A", "Z"],
            ["а", "я"],
            ["А", "Я"],
            [" ", "?"],
            ["α", "ω"],
            ["Α", "Ω"],
            ["ა", "ჰ"],
            ["Ა", "Ჰ"],
            ["ã", "ç"],
            ["є", "і"],
            ["Ü", "ü"],
            ["Ú", "ú"],
            ["Έ", "έ"],
            ["Ί", "ί"],
        ];
		
    const startTime = new Date().getTime();
    
    for(let i = 0; i < 10; i++) {
    
    	PIXI.BitmapFont.from("BANANA", {
                fontFamily: "Arial",
                fontSize: 21,
                fill: "white",
                fontWeight: "400",
            }, {chars: charSet})
    }
    
    return new Date().getTime() - startTime;
}

document.querySelector("#app").innerHTML = testBitmapFrom();
```

**Comment by Zyie** [comment]
Looks like this was introduce with this PR #6888

It was also mentioned in this issue [#8246](https://github.com/pixijs/pixijs/issues/8246#issuecomment-1183285413) that we should add an option to skip kernings

**Comment by yordan-kanchelov** [comment]
#9496 closing this with a link to the PR
