### ISSUE TITLE
Feature Request: Typescript Event Type Declarations (interactive & .on)

### ISSUE THREAD

**Issue by ufukbakan** [pixijs/pixijs#9506]
### Description

Sprite, Container etc. classes should have event types declared in typescript

**Comment by gterminator** [comment]
Question here, how do you add a eventlistener? The API docs state that there is a onmousemove attribute. But on 7.2.3 there isnt any function on container.

**Comment by ufukbakan** [comment]
You are able to do it but some people who is bad at typescript forget to define its type definitions:
```
import { Container, Sprite, Texture } from "pixi.js";

export default class extends Container{
    texture: Texture;
    sprite: Sprite;

    constructor(textureSource: string){
        super();
        this.texture = Texture.from(textureSource);
        this.sprite = Sprite.from(this.texture);
        this.interactive = true;
        this.on("pointerdown", () => {
            console.log("hello world");
        })
        this.addChild(this.sprite);
    }
}
```

this code works even though it gives typescript errors (because of missing event & listener type definitions)

**Comment by ufukbakan** [comment]
> Question here, how do you add a eventlistener? The API docs state that there is a onmousemove attribute. But on 7.2.3 there isnt any function on container.

You are able to do it but some people who is bad at typescript forget to define its type definitions:
```
import { Container, Sprite, Texture } from "pixi.js";

export default class extends Container{
    texture: Texture;
    sprite: Sprite;

    constructor(textureSource: string){
        super();
        this.texture = Texture.from(textureSource);
        this.sprite = Sprite.from(this.texture);
        this.interactive = true;
        this.on("pointerdown", () => {
            console.log("hello world");
        })
        this.addChild(this.sprite);
    }
}
```

this code works even though it gives typescript errors (because of missing event & listener type definitions)

**Comment by miltoncandelero** [comment]
Can you copy the error that code gives you?

**Comment by gterminator** [comment]
@ufukbakan you are 100% right.

**Comment by bigtimebuddy** [comment]
Did you make sure you have `"esModuleInterop": true` in your typescript compiler config? This option is needed for the event-emitter dependency.

**Comment by ufukbakan** [comment]
> Did you make sure you have `"esModuleInterop": true` in your typescript compiler config? This option is needed for the event-emitter dependency.

yes this fixes it
