### ISSUE TITLE
Bug:  determine the environment before use globalThis

### ISSUE THREAD

**Issue by HomyeeKing** [pixijs/pixijs#9518]
### Current Behavior

I am using pixi in mobile device, but some Android devices can't support globalThis

### Expected Behavior

for example, use fallback function to get gloablThis, copy from vue source code:
```
let _globalThis: any
export const getGlobalThis = (): any => {
  return (
    _globalThis ||
    (_globalThis =
      typeof globalThis !== 'undefined'
        ? globalThis
        : typeof self !== 'undefined'
        ? self
        : typeof window !== 'undefined'
        ? window
        : typeof global !== 'undefined'
        ? global
        : {})
  )
}
```

### Steps to Reproduce

browse whatever demo page in an Android phone

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by SuperSodaSea** [comment]
In my opinion it is better to add polyfills like <https://www.npmjs.com/package/globalthis> or <https://www.npmjs.com/package/babel-plugin-transform-globalthis> to your own project rather than adding these polyfill code for compatibility in Pixi.JS.

> ### [v7 Migration Guide](https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide#-output-es2020-modules-and-es2017-browser)
> #### Output ES2020 (modules) and ES2017 (browser)
> ... If your project needs to have backward compatibility, you can use Babel to transpile or polyfill.

**Comment by bigtimebuddy** [comment]
Yes, consider adding these polyfill for your projects when needed. We have made the decision to remove them from this project after dropping IE support. Here's the support for [globalThis](https://caniuse.com/mdn-javascript_builtins_globalthis).
