### ISSUE TITLE
Bug: Asset loader didn't load the correct URL

### ISSUE THREAD

**Issue by Bigaston** [pixijs/pixijs#9533]
### Current Behavior

Hello!
When I try to upload my game on Newgrounds (witch host the game on https://uploads.ungrounded.net/[...]/file/alternate/alternate_2_r14.zip/), the Assets Loader cannot load correctly all of the ressources.

In example, for and asset in img/profiles/1.jpg (declared like this `Profile_1: "./img/profiles/1.jpg",` in the manifest), he will not load it on /alternate/alternate_2_r14.zip/img/profiles/1.jpg, but on /alternate/img/profiles/1.jpg.

It work on itch.io, on WebView2, and on Newgrounds when I replace the Assets.init or Assets.load with Texture.from(url).

### Expected Behavior

Load the assets on the correct relative path event if there is an extension on the file (like .zip or anything else)

### Steps to Reproduce

Already described

### Environment

- **`pixi.js` version**: *7.2.4*
- **Environment**: Newgrounds

**Comment by Zyie** [comment]
I believe this is the same issue as #9393

**Comment by Bigaston** [comment]
Oh yeah! Sorry I search for a duplicating as my problem but I didn't see anything. Sure it's the same problem!
