### ISSUE TITLE
The behavior of addChildAt is surprising when moving a child inside the same parent

### ISSUE THREAD

**Issue by rubenlg** [pixijs/pixijs#9542]
### Description

I'm using `addChildAt` to move children around within the same parent. The documentation doesn't warn against using `addChildAt` for that purpose, and the implementation doesn't warn/error on that use case either.

However, the implementation is very surprising, because in some cases, the child isn't inserted where I want. The reason is that indices aren't stable through the implementation of `addChildAt`. The first thing the method does is remove the child from its current parent (that invalidates the index if I'm moving the child forward).

Some proposals. Not sure which one the community/maintainers prefer:
1. Change the implementation of `addChildAt` to make sure the index is stable, and the child is added exactly where the client asks even if it already belonged to that parent (i.e, changing its location in the array). This is a breaking change. Some clients might be relying on the current behavior.
2. Change the implementation of `addChildAt` to warn when the client is asking to move a child within the same parent, and recommending that the client removes the child first and computes the index after that. This doesn't break existing workarounds, and tells new clients what to do in order to deal with this cleanly (React Pixi does this in its reconciler, for example).
3. Don't touch the implementation and just add a warning to the method documentation clarifying that moving a child within the same parent is not supported and the behavior in that case is undefined, with the same recommendation from 2 (but in a comment rather than a `console.warn`).

Any preference? Happy to send a PR if we decide on one of them.

**Comment by bigtimebuddy** [comment]
> the child isn't inserted where I want.

Can you please create a reproduction of the problem? Would be helpful to see something concrete to validate.

I created this example and could not reproduce issues with addChildAt using the same parent:
https://pixiplayground.com/#/edit/LkKLG72NK3St9pJEodqKL

**Comment by rubenlg** [comment]
Looking at your example I realize that there are two ways to interpret the `index` argument:
1. Relative to siblings, i.e: make sure the child ends up between the nodes `index - 1` and `index`.
2. Absolute, i.e: make sure the child ends up holding position `index`.

These are two different outcomes. I was expecting 1, while your asserts are expecting 2. When working with absolute indices like in your example, I would also expect the current behavior.

Here is the use case in which 1 makes sense: when you are working with relative indices (indices relative to other siblings):
https://pixiplayground.com/#/edit/yVOAx3PfhUyZ1o-oQ7GQr

And here is the workaround for that case to work:
https://pixiplayground.com/#/edit/19Jyo7JWaEtvmZVCujNUY

At this point I think the best course of action would be to update the documentation of `addChildAt` to somehow clarify that when it's used to position a child relative to its siblings, it's advisable to remove it before checking the location of the siblings.

Another option would be to have an `insertBefore` method, but this was already discussed in #1065 and rejected.

Should I send the documentation PR?

**Comment by bigtimebuddy** [comment]
That issue was from a long time ago. In 2023, I would reconsider some more convenience Container utilities like `insertBefore`, `insertAfter`, `bringToTop`, `sendToBack`, etc as an optional plugin (e.g.,, `@pixi/display-extras`). I could see that being useful for some users and is convenience built _on-top_ of the existing methods.

Looking at your demo, I believe that `addChildAt` is working as designed.

> it's used to position a child relative to its siblings, it's advisable to remove it before checking the location of the siblings

I would probably not recommend that to people, it is confusing advice. It is true if you want to add it _before_ another child, but that isn't how the `addChildAt` works. The place where I believe we could clarify in the docs would be to indicate that the index parameter is the absolute position where the new child will be (right now it says "The index to place the child in").
