### ISSUE TITLE
Bug: AVIF gets loaded on iOS 14.8

### ISSUE THREAD

**Issue by jakobbouchard** [pixijs/pixijs#9547]
### Current Behavior

The assets loader tries to load an AVIF image while the browser doesn't support it. I am unsure if it happens when loading in any other way, but in the project I am working on, I load my assets with bundles, and I use the `{avif,webp}` syntax. While iOS 14.8 doesn't support AVIF, it seems the detection fails, and Pixi tries to load it anyways. This fails silently, making it quite hard to debug, and the JavaScript stops executing after the `await Assets.loadBundle` call. Interestingly, BrowserStack does give an error, which I have joined in the below screenshots.

<img width="200" alt="IMG_2C33506E6DD1-1" src="https://github.com/pixijs/pixijs/assets/24767889/074187ec-a066-40ac-8a62-a1a7a644c8f3">
<img width="200" alt="Screenshot 2023-07-13 at 19 25 40" src="https://github.com/pixijs/pixijs/assets/24767889/6833d1ef-ee7b-4f40-9518-4892d8680d68">
<img width="400" alt="Screenshot 2023-07-13 at 19 25 54" src="https://github.com/pixijs/pixijs/assets/24767889/d0cbc4cb-d5ae-4909-b486-d3ad210bbe93">
<img width="400" alt="Screenshot 2023-07-13 at 19 28 03" src="https://github.com/pixijs/pixijs/assets/24767889/9870939b-599e-4679-b04d-24615da8a698">

### Expected Behavior

Lack of AVIF support is detected correctly, and it falls back to WebP (or another format).

### Steps to Reproduce

1. Create a manifest with AVIF images.
2. Load the project on iOS 14.8 or lower.
3. See the browser try to load an AVIF file and fail silently.

### Environment

- **`pixi.js` version**: 7.2.4
- **Browser & Version**: Safari 14.8
- **OS & Version**: iOS 14.8
- **Running Example**: [Stackblitz Project](https://stackblitz.com/edit/vitejs-vite-5b2hn1?file=main.js)

### Possible Solution

PR #9537 most likely fixes it, since it gets rid of [`createImageBitmap`](https://caniuse.com/createimagebitmap), which isn't supported in iOS 14. I haven't had the time to verify, but my method is very similar and detects AVIF compatibility correctly. Considering it probably does fix it (as I use a similar function myself), I'd love to know when it comes out, as my current workaround is to detect the file extension myself instead, and it's not as clean or maintainable.

**Comment by bigtimebuddy** [comment]
Could you try with 7.3.0-rc?

**Comment by jakobbouchard** [comment]
I updated to 7.3.0-rc yesterday and should be testing today. I’m not the one with the device, so I need to wait for an answer. I’ll be able to confirm Tuesday at the latest.

**Comment by bigtimebuddy** [comment]
Thank you @jakobbouchard for the help

**Comment by jakobbouchard** [comment]
Hmm, it still seems to be trying to load AVIF files for some reason. I'll check if [detectAvif.ts#L10](https://github.com/pixijs/pixijs/blob/87b381a73dbe6b2544f3dd89cda7919712270dfd/packages/assets/src/detections/parsers/detectAvif.ts#L10) correctly returns false.

**Comment by jakobbouchard** [comment]
It does seem to return false correctly, so the loader must be using the wrong extension for some other reason. Maybe another unsupported function is used.

**Comment by jakobbouchard** [comment]
I can't confirm right now, but I _think_ it's only happening with json files (e.g. when loading spritesheets)

**Comment by bigtimebuddy** [comment]
I was able to replicate this issue with Electron v9.x, which is Chrome 83 (prior to the introduction of AVIF).

@jakobbouchard are you trying to use the resolve format syntax (e.g, `example.{avif,webp}`) for the image path within a spritesheet JSON? That is not supported and would need to be a feature request. This is the recommended way to handle different formats:

```js
// define preferences for loading textures
await Assets.init({
    texturePreference: {
        format: ['webp', 'avif'],
        resolution: 2
    },
});

// Add the spritesheet and define various resolutions/formats
Assets.add({
    alias:'atlas',
    src: [
        {
            resolution: 2,
            format: 'webp',
            src: 'atlas@2x.webp.json',
        },
        {
            resolution: 2,
            format: 'avif',
            src: 'atlas@2x.avif.json',
        },
    ]
});

// Load the atlas
const data = await Assets.load('atlas');
```

**Comment by jakobbouchard** [comment]
Ah I see, yes I was indeed trying to do this:

```
{
	name: "creation_pink_reaction",
	srcs: "creation/pink-reaction.{avif,webp}.json",
}
```

And the `pink-reaction.avif.json` file has `meta.image` set to `pink-reaction.avif`. I will change our code to use your recommended way instead. The original bug is still valid in 7.2.4 however, as it tried to load AVIF images, even other than spritesheets.

**Comment by bigtimebuddy** [comment]
Yeah, use 7.3.0-rc for now, and we'll be pushing a final release soon. I don't think I'm going to be doing a 7.2.x update.

**Comment by jakobbouchard** [comment]
Sounds good! Thanks for the timely replies by the way!

**Comment by Zyie** [comment]
This should be fixed in the latest release
