### ISSUE TITLE
Bug: Could not initialize shader

### ISSUE THREAD

**Issue by redexp** [pixijs/pixijs#9549]
### Current Behavior

Nothing renders

### Expected Behavior

render graphics

### Steps to Reproduce

1. Open pixijs.com with Chrome 114 on Ubuntu
2. see that "clouds effect" is not working

### Environment

- **`pixi.js` version**: 7.*
- **Browser & Version**: Chrome 114.0.5735.198 (Official Build) (64-bit)
- **OS & Version**: Ubuntu 20.04.6 LTS
- **Running Example**: pixijs.com

**Comment by bigtimebuddy** [comment]
Seems like a hardware issue. Are you sure your hardware drivers are updated?

**Comment by redexp** [comment]
I think it's because of 114 chrome version. On Firefox works good.

**Comment by SuperSodaSea** [comment]
It works fine on my computer :thinking: (Windows 11 Version 22H2, Chrome 114.0.5735.199)

**Comment by SuperSodaSea** [comment]
Is there more detailed error reporting information in the console?

**Comment by bigtimebuddy** [comment]
I'm also on 114 on Mac, no issues

**Comment by redexp** [comment]
Sorry, it's ok now. Probably it's was something with my Nvidia driver on Ubuntu

**Comment by Lazy-poet** [comment]
> Sorry, it's ok now. Probably it's was something with my Nvidia driver on Ubuntu

Currently having same issue and I have tried different drivers. What did you to to your driver to fix this? and what version of driver? My current driver version is 535.104.05

**Comment by redexp** [comment]
@Lazy-poet nvidia driver version 525.125.06

I just restarted my laptop :) Maybe it was some chrome issue which fixes with quick update...
