### ISSUE TITLE
Bug: error Couldn't find package "@pixi/core@7.2.4" required by "pixi.js" on the "npm" registry.

### ISSUE THREAD

**Issue by CryptaBean** [pixijs/pixijs#9550]
### Current Behavior

error Couldn't find package "@pixi/core@7.2.4" required by "pixi.js" on the "npm" registry.
Was able to install few hours ago but now no!

### Expected Behavior

To install

### Steps to Reproduce

run yarn install pixi,js

### Environment

- **`pixi.js` version**: *e.g. 7.2.4*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. WINDOWS 10 NODE*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by takumus** [comment]
Hello!
I'm having the same problem.
I think it's probably caused by npm.
https://twitter.com/npmstatus/status/1679957928294649858
https://status.npmjs.org/

**Comment by matheuscscp** [comment]
Hello! PixiJS is amazing, thank you so much for this product!

I've also just noticed this missing version on my CI builds as well. I was shipping new versions just minutes ago and then this error just started showing up, would definitely appreciate a fix.

In the meantime I will try to fix my problem upgrading to the newly released `7.3.0-rc`, I hope there are not breaking API changes :crossed_fingers: 

Thanks in advance for the help! :pray:

**Comment by matheuscscp** [comment]
Similar problem for `7.3.0-rc`:

```
➜  ~ git:(main) npm i pixi.js@7.3.0-rc 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pixi%2fapp - Not found
npm ERR! 404 
npm ERR! 404  '@pixi/app@7.3.0-rc' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'pixi.js'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pimenta/.npm/_logs/2023-07-14T21_16_43_555Z-debug.log
➜  ~ git:(main) npm i pixi.js@7.3.0    
npm ERR! code ETARGET
npm ERR! notarget No matching version found for pixi.js@7.3.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pimenta/.npm/_logs/2023-07-14T21_16_53_387Z-debug.log
➜  ~ git:(main) 
```

**Comment by matheuscscp** [comment]
Looks like this was an NPM outage:
https://status.npmjs.org/incidents/jglnklhspsnm

**Comment by bigtimebuddy** [comment]
Seems resolved. Thanks for reporting.

**Comment by CryptaBean** [comment]
still unable to access type definitions since this happened! see https://github.com/pixijs/pixijs/issues/9552#issue-1805807758
