### ISSUE TITLE
Bug: Namespace '"c:...../node_modules/pixi.js/lib/index"' has no exported member 'IPoint'.ts(2694) type PIXI.IPoint = /*unresolved*/ any

### ISSUE THREAD

**Issue by CryptaBean** [pixijs/pixijs#9552]
### Current Behavior

Since NPM when down earlier today I'm getting this error Bug: Namespace '"c:...../node_modules/pixi.js/lib/index"' has no exported member 'IPoint'.ts(2694) type PIXI.IPoint = /*unresolved*/ any

### Expected Behavior

to be able to use types

### Steps to Reproduce

try to download yarn add pixijs and import types since NPM problems

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by bigtimebuddy** [comment]
Could you please provide more details? This issue is incomplete. Steps to reproduce?

**Comment by CryptaBean** [comment]
its literally this download yarn add pixijs and import types since NPM problems yesterday. I was unable to download pixijs code from NPM. 


`import * as PIXI from 'pixi.js'

export interface ElementData {
  type: ElementType
  options: ElementOptions
}

export type ElementType = 'text' | 'shape' | 'line' | 'image'

export interface ElementOptions {
  // Define the options specific to each element type
  // For example, for a 'text' element:
  text?: string
  fontSize?: number
  // For a 'shape' element:
  shapeType?: 'rectangle' | 'circle'
  width?: number
  height?: number
  // For a 'line' element:
  points?: PIXI.IPoint[]    <------- **THIS IS RED IS MY IDE since NPM problems...**
  lineWidth?: number
  // For an 'image' element:
  imageUrl?: string
}
`

**Comment by CryptaBean** [comment]
Im closing this out as im able to access types again. Very strange but we live and learn!

**Comment by miltoncandelero** [comment]
You have pixi.js and pixi.js-legacy. you only need one or them. Both will give you these kind of errors
