### ISSUE TITLE
Bug: cannot use `Assets.load()` to load a blob URL

### ISSUE THREAD

**Issue by UlyssesZh** [pixijs/pixijs#9568]
### Current Behavior

Cannot use `Assets.load()` to load a blob URL created by `URL.createObjectURL()`.

### Expected Behavior

Loads just as fine as HTTP URLs or data URLs.

### Steps to Reproduce

```js
const url = URL.createObjectURL(await fetch('https://i.imgur.com/7XS7NLZ.jpeg').then(r => r.blob()));
const texture = await Assets.load(url);
```

### Environment

- **`pixi.js` version**: 7.2.4
- **Browser & Version**: Chrome 114.0.5735.198
- **OS & Version**: Ubuntu 20.04
- **Running Example**: https://jsfiddle.net/UlyssesZhan/zdvbowny/

### Possible Solution

There are two spots that need fixing.

First, in `utils.path.toAbsolute`, we need to handle the case of blob URL.
https://github.com/pixijs/pixijs/blob/9ce9bd2c80837265b986e1fa7af37a3d9fb4393d/packages/utils/src/path.ts#L215C3-L234

Second, in various implementations of `LoaderParser.test`, add logic about getting the type of the blob represented by the blob URL.
https://github.com/pixijs/pixijs/blob/9ce9bd2c80837265b986e1fa7af37a3d9fb4393d/packages/assets/src/loader/parsers/LoaderParser.ts#L56C11-L56C11

**Comment by UlyssesZh** [comment]
> since we cannot get the format information easily from the blob URLs.

Yes, this is a problem. Actually, in my opinion, the whole logic about `Assets.load()` should be refactored. The key is that **the load parser should be determined *after* the binary contents of the asset is actually fetched instead of *before* that**. Then, the determination of load parser should be based on `Content-Type` header and/or the binary body of the response (MIME sniffing). Two benefits:

- `Content-Type` header and MIME sniffing is much more reliable than just looking at the URL.
- This handles blob URLs elegantly automatically.

**Comment by SuperSodaSea** [comment]
I'm trying to fix `utils.path` first: #9634

Also I found an issue with specifying `loadParser`: #9633

**Comment by Zyie** [comment]
Seems like this has now been fixed. Feel free to reopen if you still have issues

**Comment by hulkyuan** [comment]
i got this issue ,i need choose a mp3 file,and draw a sound waveform.check [this](https://pixijs.io/sound/examples/#section-utils). how to do ?

**Comment by yunsii** [comment]
pixi.js@v8 usage:

```ts
Assets.load({
  src: 'blob:http://localhost:3000/3e9f04ea-4309-4e39-b13b-d32be0e1d563',
  format: 'png',
  loadParser: 'loadTextures',
})
```

**Comment by AlenAbrahamyan** [comment]
This worked!
Thanks )

**Comment by AlenAbrahamyan** [comment]
> pixi.js@v8 usage:
> 
> Assets.load({
>   src: 'blob:http://localhost:3000/3e9f04ea-4309-4e39-b13b-d32be0e1d563',
>   format: 'png',
>   loadParser: 'loadTextures',
> })

This worked!
Thanks )
