### ISSUE TITLE
Bug: TilingSprite performance issues on iPad

### ISSUE THREAD

**Issue by BOTDan** [pixijs/pixijs#9569]
### Current Behavior

Numerous TilingSprites seem to perform poorly on iPad. I believe this is also happening on iPhones, and maybe Macs, but I don't have a device to confirm.

With around 40 TilingSprites on-screen, FPS drops from 60 to around 35, while with regular sprites the FPS remains at 60.

### Expected Behavior

No/minimal performance difference between Sprites and TilingSprites.

### Steps to Reproduce

Use around 40 TilingSprites in a scene. Seemingly no special steps needed.

https://pixiplayground.com/#/edit/K5Qt496pP_nStnLwc_GxQ

Click to toggle between Sprites/TilingSprites. Generally seeing a drop from 60FPS -> 35FPS

### Environment

- **`pixi.js` version**: *7.2.4*
- **Browser & Version**: *Safari 16.3.1*
- **OS & Version**: *iPadOS 16.3.1*
- **Running Example**: *https://pixiplayground.com/#/edit/K5Qt496pP_nStnLwc_GxQ*

### Possible Solution

As the `TilingSpriteRender` re-uses the same `QuadUV` for every `TilingSprite`, rather than invalidating it each render, we're passing an extra matrix to the vertex shader to manipulate the quaduv into position. Not sure if this is the best solution, or if it works for every use-case.

### Additional Information

The performance drop seems to come from the `quad.invalidate()` call within the `TilingSpriteRenderer`. The function is marked as legacy, so I don't know if there's a more up-to-date way this should be done.

https://github.com/pixijs/pixijs/blob/9ce9bd2c80837265b986e1fa7af37a3d9fb4393d/packages/sprite-tiling/src/TilingSpriteRenderer.ts#L103-L103

**Comment by ndee85** [comment]
Hey all,
we are also having issues with the TilingSprite. It seems that TilingSprite also breaks the drawcall batch. Each new TilingSprite introduced another drawcall.

Is there a possible solution, or workaround?

We are running pixi.js 7.4.2

**Comment by anvoevodin** [comment]
We are struggling with the same problem.

**Comment by ndee85** [comment]
We ended up writing a custom TilingSprite class based on a mesh.
That way we got performance manageable again and the seams between tiles were even better.

But it works only in wegbl.

**Comment by GoodBoyDigital** [comment]
hey there, this should be all good in v8.  As long as a texture is not part of a sprite sheet - it will be as fast as rendering a sprite!

**Comment by GoodBoyDigital** [comment]
if it _is_ part of a sprite sheet, we need to render it with a custom shader. Which unfortunatly is much slower than the regular batch rendering we can do with whole textures. 👍
