### ISSUE TITLE
Bug: The attribute align='justify' of Text does not take effect

### ISSUE THREAD

**Issue by trouvaille2023** [pixijs/pixijs#9574]
### Current Behavior

When I set the property align of Text to justify, it has no effect

<img width="249" alt="image" src="https://github.com/pixijs/pixijs/assets/44250675/6d23406f-d7d2-4621-a58d-20e77af90de0">

When I searched the source code, I found that the method updateText in class Text did not implement align='justify'

<img width="1467" alt="image" src="https://github.com/pixijs/pixijs/assets/44250675/96195b5f-7cc4-4f28-b8b4-8bf3b13ea5c3">

### Expected Behavior

Ability to correctly set align='justify' like Microsoft Word and css stylea

<img width="730" alt="image" src="https://github.com/pixijs/pixijs/assets/44250675/b74fab60-16fe-4f6d-9184-8c43a571164e">

### Steps to Reproduce

```javascipt
const text = new IText(txt, {
      fontFamily: ['Helvetica', 'Arial', 'sans-serif', '微软雅黑'],
      // fontName: '微软雅黑',
      align: 'justify',
      fontSize: 16,
      breakWords: true,
      wordWrap: true,
      wordWrapWidth: 794
      // maxWidth: 794
    })
app.stage.addChild(text)

```

### Environment

pixi.js version : 7.2.4
Browser & Version  Chrome 115
OS & Version: MacOS 13 and Windows 10

**Comment by bigtimebuddy** [comment]
Justify is not supported with Text but is with HTMLText.
