### ISSUE TITLE
Feature Request:  how to event Graphics

### ISSUE THREAD

**Issue by mzx16822** [pixijs/pixijs#9590]
### Description

`const graphics = new PIXI.Graphics();

 
graphics.lineStyle(2, 0x0000FF, 1);
graphics.drawRect(-10,-10 ,bunny.width+20, bunny.height+20, 18);
graphics.zIndex=9
graphics.endFill();

graphics.lineStyle(1); // draw a circle, set the lineStyle to zero so the circle doesn't have an outline
graphics.beginFill(0xe8e8e8, 1);
graphics.drawCircle(-10,-10, 10);
graphics.endFill();

graphics.lineStyle(1); // draw a circle, set the lineStyle to zero so the circle doesn't have an outline
graphics.beginFill(0xe8e8e8, 1);
graphics.drawCircle(bunny.width+10,-10, 10);
graphics.endFill();

graphics.lineStyle(1); // draw a circle, set the lineStyle to zero so the circle doesn't have an outline
graphics.beginFill(0xe8e8e8, 1);
graphics.drawCircle(bunny.width+10,bunny.height+10, 10);
graphics.endFill();

graphics.lineStyle(1); // draw a circle, set the lineStyle to zero so the circle doesn't have an outline
graphics.beginFill(0xe8e8e8, 1);
graphics.drawCircle(-10,bunny.height+10, 10);
graphics.endFill();

graphics.on('pointerdown',async (e)=>{
  console.log(lastPoint)
  lastPoint.x=e.global.x-bunny.position.x
   lastPoint.y=e.global.y-bunny.position.y
}).on('pointermove', async (e)=>{
  bunny.width+=(e.global.x-lastPoint.x)
  bunny.height+=(e.global.y-lastPoint.y)
  graphics.width+=bunny.position.x
  graphics.height+=bunny.position.y
})`
graphics.on dont work

**Comment by SignDawn** [comment]
pixi6 ？
graphics.interactive = true

**Comment by mzx16822** [comment]
> pixi6 ？ graphics.interactive = true

thanks guy！ i got ！pixi 7
it should be
`const graphics= app.stage.addChild(new PIXI.Graphics());
graphics.eventMode = 'static';
graphics.on('pointerdown',async (e)=>{
  console.log(e)

 
})
`
