### ISSUE TITLE
Feature Request: BLEND_MODES.SUBTRACT does nothing on ALPHA 

### ISSUE THREAD

**Issue by DexYang** [pixijs/pixijs#9598]
### Description

BLEND_MODES.SUBTRACT  only subtract RGB but no effect on ALPHA

and i need ↓ .... thank you...

SRC's ALPHA is 255, DST's ALPHA is 100, the result's ALPHA is 155

**Comment by bigtimebuddy** [comment]
Can you please provide a reproduction? Thanks.

**Comment by DexYang** [comment]
now I rething it, BLEND_MODES.SUBTRACT shouldn't effect on Alpha, otherwise two untransparent sprite will always be transparent after SUBTRACT....

but i still need a way to handle alpha throw blend...

can you provide a new blend mode like MAX and it works RGBA or just Alpha...
