### ISSUE TITLE
Bug: @pixi/assets doesn't export all types

### ISSUE THREAD

**Issue by jakubmazanec** [pixijs/pixijs#9609]
### Current Behavior

Package `@pixi/assets` doesn't export types that are defined in https://github.com/pixijs/pixijs/blob/dev/packages/assets/src/types.ts.

### Expected Behavior

Types like `ResolvedAsset` are exported by `@pixi/assets`.

### Steps to Reproduce

Install `@pixi/assets` and try to import `ResolvedAsset`. Or simply download the package and search all its files for `ResolvedAsset`.

### Environment

- **`@pixi/assets` version**: *e.g. 7.2.4*

**Comment by bigtimebuddy** [comment]
PR welcome to fix. Externalize access to some of types seems helpful.

**Comment by hyeewooon** [comment]
@jakubmazanec @bigtimebuddy 

#9267 
It seems that the issue has been resolved in this PR. It works well in version >=7.3.0-rc.

**Comment by bigtimebuddy** [comment]
Thanks for clarifying.
