### ISSUE TITLE
Bug: image too large can't show

### ISSUE THREAD

**Issue by SignDawn** [pixijs/pixijs#9611]
### Current Behavior

Sprite is black

### Expected Behavior

Sprite can show

### Steps to Reproduce

codesandbox: https://codesandbox.io/s/zealous-fast-n3v4zf?file=/src/index.js

### Environment

- **`pixi.js` version**: *e.g. 7.2.4*
- **Browser & Version**: *e.g. Chrome 108*

### Additional Information

What can I do to display the pictures? Can I give you a demo?

**Comment by linlang171** [comment]
不同设备gpu支持的纹理大小受限于设备gpu本身，可访问这个链接查看自己浏览器的支持能力https://webglreport.com/?v=2

**Comment by SignDawn** [comment]
那大图就一定无法加载吗？是否能通过什么 api 来加载图片吗？哪怕损失一些清晰度。

**Comment by SignDawn** [comment]
可以是可以，但那需要重新计算图片的位置。
我觉得降低清晰度比较好，因为这个图片已经很大了，最好能够有 api 直接控制

**Comment by SuperSodaSea** [comment]
一种解决方案是使用 `pixi.js-legacy` 这个包并在 ·PIXI.Application· 的选项中指定 `forceCanvas: true` 来使用 Canvas 2D API 而非 WebGL 进行绘制，这样做就不会受到 WebGL 的纹理大小限制，不过就不能同时在 Pixi.JS 里使用某些 WebGL 才能支持的复杂效果了。也可以手动用 Canvas 2D API 把你的图片裁剪或者缩小后再丢给 Pixi.jS / WebGL 绘制。

**Comment by SignDawn** [comment]
谢谢，最后一个方案我可能会尝试一下，感谢

**Comment by GoodBoyDigital** [comment]
closing this one as this will be down to the limits of the hardware / browser rather than Pixi its self unfortunatly!
