### ISSUE TITLE
Bug: Creating multiple PIXI.Application without removing old instances causes endless loop in chromium

### ISSUE THREAD

**Issue by mychrisbi** [pixijs/pixijs#9637]
### Current Behavior

Creating multiple PIXI.Application without removing old instances causes endless loop in chromium:
![image](https://github.com/pixijs/pixijs/assets/64278649/365cc5a4-527d-462a-864a-11bf819ee0a1)

### Expected Behavior

In Firefox, no endless loop is created: 

![image](https://github.com/pixijs/pixijs/assets/64278649/065446ef-f5b7-47a2-80de-388098e123a7)

### Steps to Reproduce

- Start the attached HTML file in Chrome --> Endless loop in browser console
- Start the attached HTML file in Firefox --> No endless loop in browser console

### Environment

- **`pixi.js` version**: *7.2.4*
- **Browser & Version**: *Chromium 116*
- **OS & Version**: *Ubuntu 22.04*
- **Running Example**: *see Additional info for HTML file or https://jsfiddle.net/s81gL7mj/*

### Additional Information

```<!DOCTYPE html>
<html lang="">
  <head>
    <script src="https://cdn.jsdelivr.net/npm/pixi.js@7.x/dist/pixi.min.js"></script>
  </head>
  <body>
    <script>
      let i=0;
      loop()
      function loop(){
        if(i>32) return
        const app = new PIXI.Application({hello:true});
        const app2 = new PIXI.Application({hello:true});
        const app3 = new PIXI.Application({hello:true});
        document.body.appendChild(app.view);
        app.destroy(true, {children: true})
        app2.destroy(true, {children: true})

        i++
        loop()
      }
    </script>
  </body>
</html>

**Comment by SuperSodaSea** [comment]
```js
for(let i = 0; i < 17; ++i)
    new PIXI.Application({ hello: true });
```

This is enough to reproduce this issue. Maybe Chrome & Firefox have different behavior when restoring context? (Limit is 16, so restoring one context causes another context to be lost, causing an infinite loop.)

**Comment by bigtimebuddy** [comment]
We have seen similar issues (#8814, #2233). Browsers behave differently when you've reached the maximum number of WebGL contexts. This is not a Pixi bug but expected browser behavior. 

Creating and destroying Renderer or Application is also a bad idea. We see this a lot with React, for instance, when an Application is created on mount of a React Component. It is better to save reference to your Application and reuse it than recreate it. It's more memory efficient and works within the browser limit to do this.
