### ISSUE TITLE
Bug: Antialiasing artifacts when resolution > 1

### ISSUE THREAD

**Issue by monkeyroar** [pixijs/pixijs#9651]
### Current Behavior

When displaying Graphics with `resolution > 1` and `antialias: true` the lines are looking jagged. However when I save canvas as image and open it in image editor there are no artifacts and lines are looking smooth.
You can see the difference between saved image (left) and canvas on the page (right):
![image](https://github.com/pixijs/pixijs/assets/95053773/e32a73a3-32e8-407e-81be-ad3baffc952d)

### Expected Behavior

Canvas looks the same as exported image

### Steps to Reproduce

```js
const app = new Application({
  width: 1000,
  height: 1000,
  resolution: 5,
  antialias: true,
  autoDensity: true,
  background: "white",  
})
document.body.appendChild(app.view as HTMLCanvasElement)
const g = app.stage.addChild(new Graphics())
g.beginFill("black").drawPolygon([
  { x: 0, y: -250 },
  { x: -50, y: 250 },
  { x: 50, y: 250 },
])
app.stage.setTransform(500, 500)
```

### Environment

- **`pixi.js` version**: 7.2.4
- **Browser & Version**: Reproducible in Firefox 117.0.1, Arc 1.7.0 and Electron 24.6.5
- **OS & Version**: Mac OS Ventura 13.5.2
- **Running Example**: https://jsfiddle.net/anhb6vkf/1/

**Comment by SuperSodaSea** [comment]
This is not a bug, you need to use `resolution: window.devicePixelRatio` to get the correct anti-aliasing result in the browser. That is, each pixel on the canvas will be mapped to exactly one pixel on your monitor, otherwise the canvas will be scaled up or down, resulting in incorrect anti-aliasing results.

**Comment by monkeyroar** [comment]
@SuperSodaSea Thanks for a quick reply! What I'm really trying to achieve is render Graphics as a high res image (say 5000x5000) but display it in a smaller canvas on a page. What's the preferable way to do that? Is there some way to make it scale down using the same algorithm as my stock os image viewer app uses?

**Comment by SuperSodaSea** [comment]
You can create a [PIXI.RenderTexture](https://pixijs.download/dev/docs/PIXI.RenderTexture.html) and enable its mipmap, render the Graphics to the RenderTexture, then render the RenderTexture to your canvas.

```js
const app = new PIXI.Application({
    width: 1000,
    height: 1000,
    resolution: window.devicePixelRatio,
    antialias: true,
    autoDensity: true,
    background: "white",  
})
document.body.appendChild(app.view);

const graphics = new PIXI.Graphics();
graphics.beginFill("black").drawPolygon([
    { x: 0, y: -250 },
    { x: -50, y: 250 },
    { x: 50, y: 250 },
]);
graphics.setTransform(500, 500);

// Render the Graphics to the RenderTexture (5000 x 5000)
const renderTexture = PIXI.RenderTexture.create({
    width: 1000,
    height: 1000,
    resolution: 5,
});
renderTexture.baseTexture.mipmap = PIXI.MIPMAP_MODES.ON; // Enable mipmap
app.renderer.render(graphics, { renderTexture });

// Render the RenderTexture to your canvas
const renderTextureSprite = PIXI.Sprite.from(renderTexture);
renderTextureSprite.width = 1000;
renderTextureSprite.height = 1000;
app.stage.addChild(renderTextureSprite);
```
