### ISSUE TITLE
Bug: [iOS] Safari 17.0 - WebGL: context lost. Error: Unable to auto-detect a suitable renderer.

### ISSUE THREAD

**Issue by vonscriptor** [pixijs/pixijs#9676]
### Current Behavior

Pixi.js is not running on iOS Safari 17.0 (haven't tested in macOS Sonoma).

Console:
`WebGL: context lost.` — isWebGLSupported.mjs:14
`Error: Unable to auto-detect a suitable renderer.` — autoDetectRenderer.mjs:8

Works in iOS Chrome w/iOS 17.0.

### Expected Behavior

Pixi.js should be able to detect support and the proper renderer.

### Steps to Reproduce

Test pixi.js on iOS 17.0 Safari.

### Environment

- **`pixi.js` version**: *7.3.0*
- **Browser & Version**: *iOS Safari 17.0*
- **OS & Version**: *iOS 17.0*

### Possible Solution

With all of the updates (https://webkit.org/blog/14445/webkit-features-in-safari-17-0/) it's likely that something in isWebGLSupported() and/or autoDetectRenderer() is no longer compatible.

**Comment by vonscriptor** [comment]
Good ole, turning it off and back on again fixed the issue—just had to restart my iPhone after the update. 😆 Sorry for the false alarm!

**Comment by Alexander-0x80** [comment]
I would not say that this is a false alarm. Multiple users of our application are facing same error and as a result stuck in an unusable state. For me as a developer a phone restart is acceptable in this case, but for our users this is a "deal breaker" situation.

We are investigating on our side.

**Comment by ygnh-leo** [comment]
> I would not say that this is a false alarm. Multiple users of our application are facing same error and as a result stuck in an unusable state. For me as a developer a phone restart is acceptable in this case, but for our users this is a "deal breaker" situation.
> 
> We are investigating on our side.

Is there any new progress? I've also found a lot of ios17 users have problems.

**Comment by ygnh-leo** [comment]
Maybe it has something to do with this.
https://developer.apple.com/forums/thread/737042
