### ISSUE TITLE
Bug: @pixi/webworker

### ISSUE THREAD

**Issue by matjazPrijatelj** [pixijs/pixijs#9697]
### Current Behavior

Error occurs while loading assets in webworker.
It works with version 7.2.4

### Expected Behavior

Assets gets loaded and application work using @pixi/webworker with version 7.3.1

### Steps to Reproduce

Define some assets like:

        Assets.addBundle("jackpot", {
          atlas: `${RESOURCES_PATH}/roulette/images/jackpot-sign/jackpot-atlas-${
            OPTIONS?.window?.width > 1920 ? "bigger" : "small"
          }.json`,
          mask: `${RESOURCES_PATH}/roulette/images/jackpot-sign/mask-black-120x10-outset.png`
        });

        assets = {
          fonts: await Assets.loadBundle("fonts"),
          jackpot: await Assets.loadBundle("jackpot")
        };

The error appears in loadBundle:

roulette-gd-multigame.html:1 Uncaught (in promise) ReferenceError: Image is not defined
    at chunk-CVBU3X63.js?v=574f49ec:3145:20
    at new Promise (<anonymous>)
    at Object.test (chunk-CVBU3X63.js?v=574f49ec:3144:12)
    at AssetsClass._detectFormats (chunk-CVBU3X63.js?v=574f49ec:3089:49)
    at async AssetsClass.init (chunk-CVBU3X63.js?v=574f49ec:2774:197)
    at async AssetsClass.loadBundle (chunk-CVBU3X63.js?v=574f49ec:2917:26)

### Environment

- **`pixi.js` version**: *e.g. 7.3.1*
- **Browser & Version**: *Electron 26.2.0*
- **OS & Version**: *Windows 10*

**Comment by matjazPrijatelj** [comment]
Problematic is:

// node_modules/.pnpm/@pixi+assets@7.3.1_@pixi+core@7.3.1/node_modules/@pixi/assets/lib/detections/parsers/detectAvif.mjs

var detectAvif = {
  extension: {
    type: ExtensionType.DetectionParser,
    priority: 1
  },
  test: async () => {
    const avifData = "data:image/avif;base64,AA...";
    return new Promise((resolve) => {
      **const avif = new Image();**
      avif.onload = () => {
        resolve(true);
      }, avif.onerror = () => {
        resolve(false);
      }, avif.src = avifData;
    });
  },
  add: async (formats2) => [...formats2, "avif"],
  remove: async (formats2) => formats2.filter((f) => f !== "avif")
};
extensions.add(detectAvif);

If I remove detections with Assets.detections.splice(1) it works since I believe avif is first one.

**Comment by SuperSodaSea** [comment]
Thank you for reporting this issue, I will fix it soon.
