### ISSUE TITLE
Bug: Artifacts around small text with white fill (v8)

### ISSUE THREAD

**Issue by NotAmaan** [pixijs/pixijs#9701]
### Current Behavior

The Text rendered with canvas & html, in a small size, with a white fill is not readable in pixi.js v8 beta
It was fine in pixi.js v8 alpha

<img width="737" alt="Screenshot 2023-09-26 at 5 13 14 PM" src="https://github.com/pixijs/pixijs/assets/7458155/ba584ab2-d768-4e13-bc3c-f38c517e237c">

Note:
For some reason, the HTML text's `text` was not what I provided it in the first instance

### Expected Behavior

White text should render similar to black text

### Steps to Reproduce

Fiddle v8.0.0-alpha.3:  https://jsfiddle.net/notamaan/aecum0g5/

Fiddle v8.0.0-beta.1: https://jsfiddle.net/notamaan/omk89uhs/

### Environment

- **`pixi.js` version**: *v8.0.0-beta.1*
- **Browser & Version**: *Chromium 117*
- **OS & Version**: *MacOS*

**Comment by GoodBoyDigital** [comment]
thanks for reporting @NotAmaan - will take a look!
