### ISSUE TITLE
Bug: TilingSprite in WebGL masks other Sprites (v8)

### ISSUE THREAD

**Issue by NotAmaan** [pixijs/pixijs#9706]
### Current Behavior

TilingSprite in WebGL appears to replace the texture other sprites with its own.

- Works fine in v8.0.0-alpha.3
- Only happens in WebGL mode, after the "tiling" begins

<img width="1384" alt="Screenshot 2023-09-27 at 2 17 10 AM" src="https://github.com/pixijs/pixijs/assets/7458155/5f5c7d00-fc57-4879-87d8-85bab84bf4f6">

### Expected Behavior

Shouldn't affect other sprites

### Steps to Reproduce

https://jsfiddle.net/notamaan/dwxzteyk/

### Environment

- **`pixi.js` version**: *v8.0.0-beta.1*
- **Browser & Version**: *Chromium 117*
- **OS & Version**: * MacOS*

**Comment by GoodBoyDigital** [comment]
thanks! PR is up 👍
