### ISSUE TITLE
Feature Request: Customizable Parsing Behavior in Asset Loading

### ISSUE THREAD

**Issue by Sioyth** [pixijs/pixijs#9719]
### Description

I'm attempting to load a Spine asset in the form of a JSON file to dynamically generate an atlas at runtime and perform additional tasks. However, when using Asset.Load(), instead of providing me with the JSON file, attempts to automatically create a Spine and load the atlas, which is not the desired behavior.

- - -

In the Loader.ts _getLoadPromiseAndParser I can fix it by simple doing:

```ts
  private _getLoadPromiseAndParser(url: string, data?: ResolvedAsset): PromiseAndParser
    {
        ...
            // first check to see if the user has specified a parser
            if (data.loadParser)
            {
                // they have? lovely, lets use it
                parser = this._parserHash[data.loadParser];

                if (!parser)
                {
                    if (process.env.DEBUG)
                    {
                        // eslint-disable-next-line max-len
                        console.warn(`[Assets] specified load parser "${data.loadParser}" not found while loading ${url}`);
                    }
                } 
                // New Code
                else
                {
                     asset = await parser.load(url, data, this);
                     return asset;
                }
        ...
    }
```

I suppose this is not the best way but I just wanted to skip the additional parsing tests that are done so that I could simply return the JSON. This ones here:

```ts
for (let i = 0; i < this.parsers.length; i++)
            {
                const parser = this.parsers[i];

                if (parser.parse)
                {
                    if (parser.parse && await parser.testParse?.(asset, data, this))
                    {
                        // transform the asset..
                        asset = await parser.parse(asset, data, this) || asset;

                        result.parser = parser;
                    }
                }
            }
```

I think this functionality can be useful if you wanna force it to load as one type like in this case just a JSON file, there could be for example a forceLoadParser in data and that can be checked at the beginning.

```ts
   if(data.forceLoadParser) {
        parser = this._parserHash[data.loadParser];
        asset = await parser.load(url, data, this);
        return asset;
}
```

Other ways I thought about this could be some global or flag variable for when we load that would simply:

```ts
if(data.LoadParser & flag) {
        parser = this._parserHash[data.loadParser];
        asset = await parser.load(url, data, this);
        return asset;
      }
```

- - -
Some benefits:

**Customization**: Users can tailor the asset loading process to their specific needs. For instance, they can force loading a JSON file without additional parsing tests.

**Optimization**: By skipping unnecessary parsing tests when the desired parsing behavior is known in advance, the asset loading process can be more efficient.

**Improved User Experience**: This feature provides flexibility and control, enhancing the overall user experience when working with assets. (For example my case where I'm trying to just load the JSON and it tried to load a spine)

Before I forked and made a pull request I wanted to hear your thoughts and see what you guys think about this.

**Comment by Zyie** [comment]
Hey @Sioyth you should be able to choose which parser is used like this

```ts
Assets.load({
    alias: 'bunny',
    src: 'bunny.png',
    loadParser: 'your-parser'
});
```

**Comment by Sioyth** [comment]
@Zyie Thank you that works!

**Comment by Sioyth** [comment]
Say I use that first to load the spine JSON, and later on I create the atlas dynamically and want to now load it as a spine I used to simple do before:

```ts
  let spineAsset: UnresolvedAsset = {};
        spineAsset.alias = convertToList<string>(id);
        spineAsset.src = this.fileNames[id];
        spineAsset.data = {spineAtlas: atlas}
        spineAsset.loadParser = "loadJson";
        
         return Assets.load<Spine>(spineAsset).then( (res) =>
        {
            this.skeletons[id] = res.spineData;
            return Promise.resolve(res.spineData);
        });
```

Do we have access to the Spine Load Parser?        

So i could do: 
```
    spineAsset.loadParser = "loadSpine";
```

**Comment by Zyie** [comment]
Yeah I think you will need to open an issue on the spine repo to add a name to the parsers 

here
https://github.com/pixijs/spine/blob/bda2e19cb28a0df2187451bad8ccc14f1e20da23/packages/loader-base/src/atlasLoader.ts#L19

and here
https://github.com/pixijs/spine/blob/bda2e19cb28a0df2187451bad8ccc14f1e20da23/packages/loader-base/src/SpineLoaderAbstract.ts#L39-L40

**Comment by Sioyth** [comment]
Thank you again @Zyie I figured that might had been the case have a good weekend!
