### ISSUE TITLE
Bug: Pixi.js ESM doesn't work with jsDelivr because of non existant ESM module @pixi/colord@2.9.5

### ISSUE THREAD

**Issue by Feavy** [pixijs/pixijs#9725]
### Current Behavior

Hello, there is a problem with pixi.js ESM on jsDelivr that makes it unusable.
```html
<script type="module">
import pixiJs from 'https://cdn.jsdelivr.net/npm/pixi.js@7.3.1/+esm'
</script>
```
It tries to load `@pixi/colord@2.9.5` but cannot find it

![image](https://github.com/pixijs/pixijs/assets/34109688/e79f5d8e-9874-457d-b1a4-099f324fff14)

[https://cdn.jsdelivr.net/npm/@pixi/colord@2.9.5/+esm](https://cdn.jsdelivr.net/npm/@pixi/colord@2.9.5/+esm)

### Expected Behavior

@pixi/colord ESM should be found.

### Steps to Reproduce

[https://jsfiddle.net/dobgky65/1/](https://jsfiddle.net/dobgky65/1/)

Open the dev tools and notice the error.

### Environment

- **`pixi.js` version**: 7.3.1
- **Example**: [https://jsfiddle.net/dobgky65/1/](https://jsfiddle.net/dobgky65/1/)

### Possible Solution

Use the new @pixi/colord@2.9.6 version which has an ESM module. See [https://cdn.jsdelivr.net/npm/@pixi/colord@2.9.6/+esm](https://cdn.jsdelivr.net/npm/@pixi/colord@2.9.6/+esm)

**Comment by bigtimebuddy** [comment]
Version 7.3.1 is [not strict](https://github.com/pixijs/pixijs/blob/v7.3.1/packages/color/package.json#L35) so it should be getting the latest `@pixi/colord` but I believe jsdelivr is caching the request. Probably worth us bumping that version anyways.
