### ISSUE TITLE
Bug: svg method doesn't draw path commands after first Z or z (8.0.0-beta.3)

### ISSUE THREAD

**Issue by naramdash** [pixijs/pixijs#9743]
### Current Behavior

It appears that all commands after the first Z or z command in path d are ignored.

![image](https://github.com/pixijs/pixijs/assets/24370799/1faaf61b-9eb7-4722-abe7-dfa521ff9191)

### Expected Behavior

Correctly interpret and represent with Graphics the d attribute of SVG PATH elements.

### Steps to Reproduce

call svg method on Graphics with svgString that has path like 

`'m 10 10 l 10 10 z m 20 20 l 20 20 z m 30 30 l 30 30 z'`

has more commands after first z command

### Environment

- **`pixi.js` version**: *8.0.0-beta3*
- **Browser & Version**: *Edge 117*, *Chrome 117*
- **OS & Version**: *Windows 11 Pro*
- **Running Example**: *https://codesandbox.io/p/github/naramdash/test-pixi-8.0.0-beta3-svg-path/main*  

- **Example GitHub Repo**: *https://github.com/naramdash/test-pixi-8.0.0-beta3-svg-path*

### Possible Solution

- refresh or store `closedLineStartX` and `closedLineStartY` when M m started
- refresh `lastX` and `lastY` when Z z called

### Additional Information

code `customParseD.ts`  that parsing d  in https://github.com/naramdash/test-pixi-8.0.0-beta3-svg-path,

codes are mixed codes from  [pixi.js@8.0.0-beta.3](https://github.com/pixijs/pixijs/tree/v8.0.0-beta.3) and [pixi-svg](https://github.com/bigtimebuddy/pixi-svg)

and added some code

**Comment by Zyie** [comment]
should be fixed in latest release!
