### ISSUE TITLE
Bug: Empty @math-extract pointExtras.d.ts since v7

### ISSUE THREAD

**Issue by roxas1533** [pixijs/pixijs#9746]
### Current Behavior

Install @math-extracts using npm
The pointExtras.d.ts only lists ``` export {}; ```, and the extension methods of the Point class are not available.
Is this intended to be stated?

### Expected Behavior

Allows the use of extended methods of the Point class

### Steps to Reproduce

- ```npm install @pixi/math-extras```
- check node_modules/@pixi/math-extras/lib/pointExtras.d.ts

### Environment

- **`pixi.js` version**: 7.3.1

### Additional Information

https://registry.npmjs.org/@pixi/math-extras/-/math-extras-7.3.1.tgz

I checked the tar.gz of my installation, and everything after 7.0.0 was empty.

**Comment by bigtimebuddy** [comment]
You need to import the package:

```js
import * as PIXI from 'pixi.js';
import '@pixi/math-extras';
```

There are no exports for that package. The mixins are added to the relevant classes.
