### ISSUE TITLE
Bug: Argument of type 'Container<DisplayObject>' is not assignable to parameter of type 'DisplayObject'.

### ISSUE THREAD

**Issue by singher-k** [pixijs/pixijs#9747]
### Current Behavior

Argument of type 'Container<DisplayObject>' is not assignable to parameter of type 'DisplayObject'.

app.stage.addChild(sprite)  the above error occurs 

### Expected Behavior

 let sprite = PIXI.Sprite.from("url");
   
 app.stage.addChild(sprite)

Works perfectly

### Steps to Reproduce

 let sprite = PIXI.Sprite.from("url");
   
 app.stage.addChild(sprite)

### Environment

- **`pixi.js` version**: *e.g. 7.3.1*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by bigtimebuddy** [comment]
Please provide a reproduction.

**Comment by nz771202** [comment]
Hi. To reproduce this, create these files:

package.json:
```
{
    "devDependencies": {
        "@pixi/core": "7.3.1",
        "@pixi/display": "7.3.1",
        "@pixi/events": "7.3.1",
        "typescript": "4.8.4"
    }
}

```
tsconfig.json:
```
{
    "compilerOptions": {
        "moduleResolution": "Node",
        "esModuleInterop": true,
        "module": "es6",
        "target": "es6",
        "skipLibCheck": true
    }
}
```
index.ts:
```
import "@pixi/events";
import {Container} from "@pixi/display";
const parent = new Container();
parent.addChild(new Container());
```
then:
```
npm i
npx tsc
```

Removing `esModuleInterop` from tsconfig fixes it. But I'm still wondering if there is any way to make this work regardless of that setting.

**Comment by bigtimebuddy** [comment]
Thank you for that! I was able to track it down to this change #9492 introduced in 7.3.0. 

The issue is this syntax doesn't support TypeScript 4.x. I was able to workaround it by upgrading `typescript` to v5 _or_ by removing `& { [K: ({} & string) | ({} & symbol)]: any; }` from the end of **node_modules/@pixi/events/lib/FederatedEventMap.d.ts**. Both changes suppressed the issue.

Upgrading `typescript` seems like the most sensible solution. Is that a blocker for you @singher-k?

cc @miltoncandelero

**Comment by miltoncandelero** [comment]
Interesting, I didn't know that magical syntax was typescript 5 exclusive 😅

Can we find a way to only run that if typescript>5?

I never checked if typescript has some sort of preprocessor macros 🤔

**Comment by bigtimebuddy** [comment]
Me either. I will add a note in the release for TS 5. Reverting the change (and removing support for generic dispatched events) is definitely not my preference.

**Comment by singher-k** [comment]
谢谢你，我已经换了一个版本的pixiJs解决此问题
