### ISSUE TITLE
Bug: event.defaultPrevented behaves incorrectly on consecutive events

### ISSUE THREAD

**Issue by CaptainTux** [pixijs/pixijs#9749]
### Current Behavior

When `app.renderer.events.autoPreventDefault = false;` is set and an event listener on some element calls `event.preventDefault()`, all subsequent events always have `event.defaultPrevented` set to `true`.

### Expected Behavior

`event.defaultPrevented` should initially be `false` for every event

### Steps to Reproduce

```ts
const app = new Application({
  width: 900,
  height: 600,
  background: "#00ff00"
});

app.renderer.events.eventMode = "static";
document.body.appendChild(app.view);

const text = new Text("TEST", { fontSize: 60 });
text.eventMode = "static";
text.onmousedown = (event) => {
  console.log("text listener", event.defaultPrevented);
  if (!event.defaultPrevented) {
    event.preventDefault();
  }
}
```

### Environment

- **`pixi.js` version**: *7.3.1*
- **Browser & Version**: *FF118.0.1*
- **OS & Version**: *Win 10*
- **Running Example**: *https://codesandbox.io/s/pixi-js-forked-q6ng6s?file=/src/index.js*

### Possible Solution

investigate and fix event dispatch logic

**Comment by dev7355608** [comment]
This would be nice to have fixed in v7 if v7 is still being updated.
