### ISSUE TITLE
Bug: Assets: Query parameters break resolver priority

### ISSUE THREAD

**Issue by zOadT** [pixijs/pixijs#9758]
### Current Behavior

When loading an asset, pixi.js will respect the configured priority, but if query params are present, pixi.js will always load the first string variation
```js
const resolver = PIXI.Assets.resolver;

resolver.prefer({
    params: {
       format: ['webp', 'png'],
    },
});

resolver.add('bunny', 'https://pixijs.io/examples/examples/assets/bunny.{png,webp}')
resolver.add('bunny2', 'https://pixijs.io/examples/examples/assets/bunny.{png,webp}?abc')

// https://pixijs.io/examples/examples/assets/bunny.webp
console.log(PIXI.Assets.resolver.resolveUrl('bunny'));
// https://pixijs.io/examples/examples/assets/bunny.png?abc
console.log(PIXI.Assets.resolver.resolveUrl('bunny2'));
```

### Expected Behavior

`https://pixijs.io/examples/examples/assets/bunny.{png,webp}?abc`should be resolved to `https://pixijs.io/examples/examples/assets/bunny.webp?abc`

### Steps to Reproduce

https://pixiplayground.com/#/edit/NNZdTcoluXTs2hyDA8aJv

### Environment

- **`pixi.js` version**: 7.3.1

### Possible Solution

I think the reason for this is that the `extname` function from the path utils does not recognise query params

### Additional Information

This issue can lead to sound being broken in Safari because `example.{ogg,mp3}?abc` would always result in the ogg being loaded even though Safari does not support oggs.

**Comment by bigtimebuddy** [comment]
Thanks for the example @zOadT. I was able to create a unit-test with your example and track down the underlying issue.

**Comment by zOadT** [comment]
@bigtimebuddy Thank you very much for creating a fix!
