### ISSUE TITLE
Types Bug

### ISSUE THREAD

**Issue by codercatdev** [pixijs/pixijs#9759]
### Current Behavior

When using `Renderer` in Svelte for version 8.

```
Type of property 'accessibility' circularly references itself in mapped type 'ExtractSystemTypes<(typeof BackgroundSystem | typeof FilterSystem | typeof GraphicsContextSystem | typeof GlobalUniformSystem | typeof HelloSystem | ... 19 more ... | typeof BindGroupSystem)[]>'.
```
<img width="1094" alt="image" src="https://github.com/pixijs/pixijs/assets/3102249/05e79762-f649-40ea-85e9-ff74c5c2f317">

### Expected Behavior

I would expect there to be no error.

### Steps to Reproduce

```
git clone https://github.com/CodingCatDev/codingcat.dev.git &
cd codingcat.dev/apps/dojo/ &
```

Either run svelte-check using `npx svelte-check` or `pnpx svelte-check`

### Environment

- **`pixi.js` version**: *8.0.0-beta.5*
- **Browser & Version**: *Chromium 117*
- **OS & Version**: *Mac 13.4.1*
- **Running Example**: *<https://dojo.codingcat.dev>*

### Possible Solution

I believe that this

```
    "./accessibility": {
      "import": {
        "default": "./lib/accessibility/init.mjs"
      },
      "require": {
        "default": "./lib/accessibility/init.js"
      }
    },
```
is causing issues

**Comment by Zyie** [comment]
Hey @codercatdev i just cloned your repo and did `cd ./apps/dojo && npm i && npm run check` and got no errors on the latest v8 beta

Can you check if you still have any issues

**Comment by Zyie** [comment]
Going to close this out for now, feel free to reopen if you still have any issues
