### ISSUE TITLE
Bug: Pixi fails silently / shows black screen in specific environment

### ISSUE THREAD

**Issue by Lixus** [pixijs/pixijs#9762]
### Current Behavior

Our pixi container works great under normal circumstances, but shows only a black screen when loaded into our website.

Our website is relatively resource intensive, we have big graphics that are moving, etc. and we had a black screen like this in the past _from time to time_ when trying the game on a weak laptop, so my question is, could Pixi be failing silently when the browser uses too much resources / it's too much for the graphics processor / something like that?

### Expected Behavior

The Pixi app should load in all provided examples.

### Steps to Reproduce

We use Pixi in a customizable advent calendar. Everything works fine under 'normal' circumstances. To test, please click on _Games_, then _Play_ inside the _Puzzle_ container :

https://tuerchen.app/beispiel-tuerchen?l=EN

The calendar can be embedded into other websites. We use a shadow root to separate the calendar from the website. This, too, works fine normally:

https://tuerchen-embed-test.preview.schittigs.dev/

Now when we embed it into our own website in the exact same way, the Pixi container only shows a black screen. No console logs or anything.

https://tuerchen.com/en/enterprise/

(Please scroll down a bit to see the calendar)

### Environment

- **`pixi.js` version**: *7.2.4*
- **Browser & Version**: *Chrome 118*, *FireFox 118*, *Safari 16.6*
- **OS & Version**: *MacOS*, *Linux*, *Windows*, *Android*

**Comment by tgrajewski** [comment]
> WARNING: Too many active WebGL contexts. Oldest context will be lost.

It seems that your website uses too many WebGL contexts, so the browser drops the oldest one freeing some GPU resources.

**Comment by Lixus** [comment]
Very interesting. I don't get that warning in any browser, where do you see it? 
Besides, that should definitely help debugging, thanks a lot!

**Comment by Lixus** [comment]
OK, this was no issue with Pixi (except that it did not show me the warning about too many active WebGL contexts)

The problem was coming from portal-vue which seems to have spawned multiple instances of the component that had the pixi container in the background.
