### ISSUE TITLE
Bug: Unable to use Assets.add due to missing settings.RETINA_PREFIX

### ISSUE THREAD

**Issue by adriendurepaire** [pixijs/pixijs#9780]
### Current Behavior

When adding a PNG asset with `Assets.add({ alias: '...', src: '...' });`, I get the error "Cannot read properties of undefined (reading 'exec')". This is due by the absence of RETINA_PREFIX in Pixi settings.

### Expected Behavior

The asset should load without error

### Steps to Reproduce

 `Assets.add({ alias: '...', src: '...' });` with a .png file

### Environment

- **`pixi.js` version**: *7.3.2*
- **Browser & Version**: *Opera 103.0.4928.34*
- **OS & Version**: *Windows 11*

### Possible Solution

I think `resolution: parseFloat(settings.RETINA_PREFIX.exec(value)?.[1] ?? '1')` should be resolution: `parseFloat(settings.RETINA_PREFIX?.exec(value)?.[1] ?? '1')` here: https://github.com/pixijs/pixijs/blob/c04c09c50874fef9296555af23e25fe58cc808a9/packages/assets/src/resolver/parsers/resolveTextureUrl.ts#L12

**Comment by bigtimebuddy** [comment]
`RETINA_PREFIX` does live here:
https://github.com/pixijs/pixijs/blob/c04c09c50874fef9296555af23e25fe58cc808a9/packages/utils/src/settings.ts#L12

Can you please provide a reproduction?

**Comment by adriendurepaire** [comment]
Weird, I was not able to reproduce the issue in the playground: https://www.pixiplayground.com/#/edit/cFLuV-rXO86YCwZVAczES

When I log settings in my project, RETINA_PREFIX is missing. I've temporarily fixed it by adding `settings.RETINA_PREFIX = /@([0-9\.]+)x/;` after Pixi import. I'll try to reproduce the problem in a smaller project with the same bundler (Parcel) and the same pixi plugins soon.

**Comment by bigtimebuddy** [comment]
Please make sure that you don't have multiple version of Pixi installed in your lock file. This can happen if you have upgraded pixi.js recently or have a weird mix of plugins/dependencies. Sometimes bundlers can also have issues with certain setups. In this case, a repository example would be more helpful.

**Comment by adriendurepaire** [comment]
I updated @pixi/graphics-extras to the latest version (7.2.3 -> 7.3.2) and that fixed the problem. Sorry, I didn't think to update the dependencies. Thanks for your help!
