### ISSUE TITLE
Bug: v8 canvas type HTMLCanvasElement in options is missing

### ISSUE THREAD

**Issue by YunYouJun** [pixijs/pixijs#9785]
### Current Behavior

![image](https://github.com/pixijs/pixijs/assets/25154432/ef058928-e28c-4d52-be62-015985b0394c)

```ts
const app = new PIXI.Application()
await app.init({
  canvas: pixiCanvasRef.value,
  background: '#1099bb',
})
```

canvas type in initOptions is `ICanvas`.

### Expected Behavior

ICanvas is a internal type.
In theory, we should allow `HTMLCanvasElement` to be passed in.

I'm trying to pass in canvas directly to work, so I guess that's a type loss.

### Steps to Reproduce

![image](https://github.com/pixijs/pixijs/assets/25154432/1d357854-6f30-402d-a85c-9f00d7e04f3f)

BrowserAdapter as Adapter

- BrowserAdapter.createCanvas return `HTMLCanvasElement`
- Adapter.createCanvas return `ICanvas`

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

### Possible Solution

I think type should be:

```ts
canvas: ICanvas | HTMLCanvasElement
```

### Additional Information

If you think my understanding is correct, I would be happy to create a PR for this.
If not, I hope you can tell me the reason. Thank you.

**Comment by Zyie** [comment]
Hey @YunYouJun i'm unable to reproduce this issue in the latest v8 beta

Is this still an issue for you if you update?

**Comment by YunYouJun** [comment]
This seems to have something to do with my monorepo configuration, and when I detached it from the project, the type prompt worked.

I'll check the reason.

**Comment by YunYouJun** [comment]
It's not that simple, and I think I found the real reason.

![image](https://github.com/pixijs/pixijs/assets/25154432/14d6aee6-d750-4308-ab60-c70f2e6f9bf2)

---

In my monorepo, `@babylon/core` `GPUCanvasContext` is working.
![image](https://github.com/pixijs/pixijs/assets/25154432/c1e46ef9-9b64-44c2-8470-be111bb98cd1)

I should use the type in pixi to override it.

### Solution

```ts
npm i -D @webgpu/types
```

- add typeRoots `./node_modules/@webgpu/types"`

```json
// tsconfig.json
{
  "compilerOptions": {
    // ...
    "typeRoots": [
      "./node_modules/@webgpu/types"
    ]
  }
}

```
