### ISSUE TITLE
Bug: backgroundAlpha not working

### ISSUE THREAD

**Issue by artvinn** [pixijs/pixijs#9799]
### Current Behavior

backgroundAlpha has no effect and the canvas is black

### Expected Behavior

Canvas should be transparent

### Steps to Reproduce

```
import { Application } from 'pixi.js';

const app = new Application();

(async () => {
  await app.init({
      backgroundAlpha: 0
  });
})();
```

### Environment

- **`pixi.js` version**: *^8.0.0-beta.6*
- **Browser & Version**: *Chrome 118*
- **OS & Version**: *macOS Sonoma 14.0*
- **Running Example**: https://pixiplayground.com/#/edit/hr-dRwTyTbESXRIQnV_5J

**Comment by Zyie** [comment]
should be fixed in latest release!
