### ISSUE TITLE
Bug: Mobile input text stopped working after 7.3.0

### ISSUE THREAD

**Issue by gfcrba** [pixijs/pixijs#9814]
### Current Behavior

Problem concerns mobile only.
Create interactive DisplayObject (sprite, graphics...).
Add pointerup event to this interactive object. In this event handler try to receive user keyboard input. As common approach to solve this task: 
* create hidden input (html element);
* focus on created input (input.focus());
* handle text from hidden input for in game needs;
* after user click somewhere outside virtual keyboard handle input blur event to clean things up (remove input etc.)

If you do it on mobile (or ex. chrome devtools with mobile simulation toggle on) input loses focus immediately. So no keyboard virtual keyboard appeared and no way to allow user input text.

### Expected Behavior

As right now works on nonmobile. Input can be created and focused. And then loose focus after user clicks somewhere on stage.

### Steps to Reproduce

Here is code sample https://ecknmg.csb.app/
If you run it on computer and press on red square hidden input will be added to body and after clicking elsewhere on stage blur event will fire and log will be added to console.
If you run it with Devtools open (In Chrome) and toggle simulate mobile device mode, when you press red square input is added and its blur handler fires immediately.

### Environment

- **`pixi.js` version**: *e.g. 7.3.0+*
- **Running Example**: *e.g. <https://ecknmg.csb.app/>*

### Possible Solution

You can partially solve issue by handling touchstart browser event and call preventDefault there, so hidden input won't lose focus. But it causes another problem: no way to handle events so canvas receives focus back (so input looses it and blur fires).

### Additional Information

https://stackoverflow.com/questions/57310622/unable-to-focus-dom-element-in-touch-events

**Comment by gfcrba** [comment]
Seems not actually a PixiJS bug. In pixi/ui this was fixed.

**Comment by bigtimebuddy** [comment]
Thanks for reporting. I'll close this, but feel free to re-open if you have any more issues.
