### ISSUE TITLE
Bug: [v8] Background alpha doesn't have an effect on WebGPU

### ISSUE THREAD

**Issue by levi** [pixijs/pixijs#9816]
### Current Behavior

Setting the background alpha option when initializing the app doesn't change the alpha of the background.

### Expected Behavior

Alpha should blend or completely remove the background based on value.

### Steps to Reproduce

const app = new Application()
await app.init({
backgroundAlpha: 0
})

### Environment

- **`pixi.js` version**:  v8 Beta 7

**Comment by bigtimebuddy** [comment]
Duplicate of #9799
