### ISSUE TITLE
Bug: The inside stroke cannot be displayed(8.0.0-beta.7)

### ISSUE THREAD

**Issue by yungzhu** [pixijs/pixijs#9829]
### Current Behavior

    const app = new Application();

    await app.init({
        width,
        height,
        preference: "webgpu",
        autoDensity: true,
        resolution: window.devicePixelRatio,
    });
    document.body.appendChild(app.canvas);

    const node1 = new Graphics();
    node1.fillStyle = 0xffff00;
    node1.rect(0, 0, 100, 100);
    node1.fill();
    node1.position.set(300, 300);
    app.stage.addChild(node1);

    const node2 = new Graphics();
    node2.fillStyle = 0xffff00;
    node2.rect(0, 0, 100, 100);
    node2.stroke({ color: 0xff0000, width: 10, alignment: 1 });
    node2.fill();
    node2.position.set(450, 300);
    app.stage.addChild(node2);
    
    
![image](https://github.com/pixijs/pixijs/assets/2418199/1108c804-a257-4a80-813b-847896456077)

### Expected Behavior

Stroke does not show when alignment=1, expect an inside stroke

by 8.0.0-beta.7

### Steps to Reproduce

rt
8.0.0-beta.7

### Environment

- **`pixi.js` version**: *e.g. 8.0.0-beta.7*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by JetLua** [comment]
workaround
```js
node2.stroke({ color: 0xff0000, width: 10, alignment: 1 });
node2.fill();
```
⬇️
```js
node2.fill();
node2.stroke({ color: 0xff0000, width: 10, alignment: 1 }); 
 ```

**Comment by yungzhu** [comment]
Wow!great
