### ISSUE TITLE
Bug: memory leak v8

### ISSUE THREAD

**Issue by GDX64** [pixijs/pixijs#9836]
### Current Behavior

it looks like there is a memory leak when I create and destroy several text objects.

### Expected Behavior

The amount of memory should stay relatively the same

### Steps to Reproduce

accessing https://glmachado.com/libtest it is possible to see the problem.
Even after removing text nodes from the scene and calling destroy on them, they are still in memory and seem to be retained here 
<img width="322" alt="image" src="https://github.com/pixijs/pixijs/assets/36547504/ba9569e5-0208-4f5e-b17c-41cdce7eab31">

### Environment

- **`pixi.js` version**: *v8.0.0.beta-8*
- **Browser & Version**: *Chrome 119*
- **OS & Version**: *Win 11*
- running: https://glmachado.com/libtest

**Comment by GDX64** [comment]
I'm also getting this error from time to time 
<img width="387" alt="image" src="https://github.com/pixijs/pixijs/assets/36547504/408a494f-8df4-47e7-aa32-95cadd8c2a6d">

Even removed from the scene some destroyed texts end up being updated and crash the app.

**Comment by GoodBoyDigital** [comment]
thankyou for sharing @GDX64 ! This is next on my list to investigate :D

**Comment by GoodBoyDigital** [comment]
Mats Todos
- [ ] validate destroy flow for CanvasTextSystem
    - [ ] ensure events are fully removed
    - [ ] gpu elements are returned to pool / destroyed correctly 
    - [ ] check cacheSize stays stable
- [ ] validate destroy flow for BitmapTextSystem
    - [ ] ensure events are fully removed
    - [ ] gpu elements are returned to pool / destroyed correctly 
    - [ ] check cacheSize stays stable

**Comment by steel97** [comment]
Not sure if it's related or just bug somewhere in my code (however I didn't got this on v7), but I'am also getting something similar with sprite after destroying them sometimes I get this error
![bug](https://github.com/pixijs/pixijs/assets/7414151/ee97a477-ecaf-496c-b528-bd6fad55201e)

**Comment by Zyie** [comment]
This should be fixed in the latest release!
