### ISSUE TITLE
Bug: version 7.3.0  Uncaught TypeError: currentTarget.isInteractive is not a function

### ISSUE THREAD

**Issue by zz201276** [pixijs/pixijs#9838]
### Current Behavior

I only initialized the instance, and then this error will appear when clicking anywhere on the page. I tried the updated version but still didn't solve the problem. I don't know what is causing this problem.

### Expected Behavior

Unbound events should not trigger or report errors.

### Steps to Reproduce

app = new Application({
        autoStart: true,
        width: 750,
        height,
        antialias: true,
        backgroundColor: 0x000000,
        backgroundAlpha: 0,
        view: canvas.value,
        hello: false,
        resolution: 1
        // , resolution: devicePixelRatio.toFixed(1)
    });

### Environment

- **`pixi.js` version**: *e.g. 7.3.0*

 "vue": "^3.2.25",
"vite": "^3.2.5",

**Comment by bigtimebuddy** [comment]
Unable to reproduce: https://jsfiddle.net/bigtimebuddy/bers5v4a/

Could you please provide a complete reproduction?

**Comment by zz201276** [comment]
> Unable to reproduce: https://jsfiddle.net/bigtimebuddy/bers5v4a/
> 
> Could you please provide a complete reproduction?

I deleted all the dependencies, then downgraded pixi.js to 7.0.5, and removed pixi-filters, and it can run normally. It should be a problem caused by mismatched dependencies. Thank you for your reply.

**Comment by baophungchi** [comment]
What is the solution of this problem. Thank you
