### ISSUE TITLE
Feature Request: setParent(container) should optionally allow you to retain the existing worldTransform

### ISSUE THREAD

**Issue by reececomo** [pixijs/pixijs#9848]
### Description

It would be stellar if PIXI.js natively supported changing a sprites parent while retaining the existing visual position (position, rotation, scale).

i.e.

```ts
sprite.setParent(newParent, { preserve: true });
```

**Comment by bigtimebuddy** [comment]
We have discussed this recently with regards to v8. It's a good idea.

**Comment by reececomo** [comment]
Is it a relatively straightforward implementation?

I'm trying to swap parents of a sprite, but I can't quite get the rotation and position to reapply (together) correctly.

Is there some version of this in PIXI already:

```ts
// Capture intended output
const tf = mySprite.worldTransform;

// Swap
mySprite.removeFromParent();
newParent.addChild(sprite);

// Revert state
// I.e. get delta between tf and current world transform
// and apply that locally
mySprite.setWorldTransform(tf);
```

**Comment by bigtimebuddy** [comment]
Perhaps you can try this using toGlobal/toLocal:
https://jsfiddle.net/bigtimebuddy/0s1nmtpu/

Unfortunately, that only does position, not scale, alpha, etc.

**Comment by reececomo** [comment]
Yeah position is the easy one - I'm running into trouble when adding rotation into the mix. Scale and alpha also fairly straightforward to do (just calculate up to the nearest common ancestor and apply the diff).

Retaining visual position adjusting for parent/grandparent rotation and anchors is the hard bit. It seems given how advanced PIXI is, there is probably a very simple function/implementation - but 2D graphics is not my specialty.

**Comment by reececomo** [comment]
Just double-checking its something approximating this?:

```ts
function replaceParentInPlace(target: Container, newParent: Container): void {
  const before = target.worldTransform.clone();

  // move
  target.removeFromParent();
  newParent.addChild(target);

  const after = target.worldTransform.clone();

  // reset to previous visual position
  target.localTransform.apply(before - after); // 🙈
}
```

**Comment by reececomo** [comment]
Maybe this MoveToParent operation from Phaser Scene Editor:
* https://github.com/PhaserEditor2D/PhaserEditor2D-v3/blob/9d9a633578162dc5d60c009d1bf00b49441609ed/source/editor/plugins/phasereditor2d.scene/src/ui/sceneobjects/object/properties/MoveToParentOperation.ts

I'm just on lunchbreak at work so I'll have a proper look tonight

**Comment by Zyie** [comment]
this has now been added in this PR: https://github.com/pixijs/pixijs/pull/10585

**Comment by reececomo** [comment]
Amazing, thanks @Zyie !
