### ISSUE TITLE
Bug: docs make package super heavy (v8)

### ISSUE THREAD

**Issue by Feavy** [pixijs/pixijs#9898]
### Current Behavior

For some reason all html docs are included in dist folder published on NPM which makes the package super heavy (+307 MB)  
Also jsDelivr is not able to serve it as it exeeds the size limit of 150 MB.

https://www.npmjs.com/package/pixi.js/v/8.0.0-beta.11?activeTab=code  
https://www.jsdelivr.com/package/npm/pixi.js?tab=files&version=8.0.0-beta.11

![image](https://github.com/pixijs/pixijs/assets/34109688/f685bdbb-6c5e-4855-a117-5d884274828d)

### Expected Behavior

Docs should not be included in published package.

### Steps to Reproduce

-

### Environment

- **`pixi.js` version**: *8.0.0-beta.11*

**Comment by bigtimebuddy** [comment]
I agree, docs shouldn't be included in package.
