### ISSUE TITLE
Bug: 8.0.0-rc renderer does not apply root container transform

### ISSUE THREAD

**Issue by davidye** [pixijs/pixijs#9951]
### Current Behavior

v8: https://www.pixiplayground.com/#/edit/1VFolvbwpAXx7cXGrJbFa
v7: https://www.pixiplayground.com/#/edit/byYO88lAWiCeKYLYEFjJJ

The red square is offset in v7 but not v8.

### Expected Behavior

The red square is offset.

### Steps to Reproduce

See playgrounds

### Environment

See playgrounds

**Comment by GoodBoyDigital** [comment]
this was actually intentional :)

A container is currently always rendered locally with no transform. Its easily solved by either nesting it into a another container, or by passing a matrix to the render function. 

Perhaps not that intuitive though... will have a think on this one too!
