### ISSUE TITLE
Bug: 8.0.0-rc mask is not applied

### ISSUE THREAD

**Issue by davidye** [pixijs/pixijs#9952]
### Current Behavior

v8: https://www.pixiplayground.com/#/edit/q9WhZr5DhD_RfQInXQIHa
v7: https://www.pixiplayground.com/#/edit/1W_ww8csYQDzxZVvnkysC

### Expected Behavior

Mask should apply so the blue rectangle's corners are masked

### Steps to Reproduce

See playgrounds

### Environment

Checked both Chrome and Safari, see playgrounds

**Comment by Zyie** [comment]
this seems to be related to the other issue with the transform not being updated: https://github.com/pixijs/pixijs/issues/9951

it seems that anything applied to the top level container isn't processed, only its children

**Comment by GoodBoyDigital** [comment]
Heya, thats a good shout! I'm going to look at this next :)

There will be almost zero impact on performance by adding the additional root container :D
