### ISSUE TITLE
Bug: 8.0.0-rc setting container mask to undefined results in typescript error

### ISSUE THREAD

**Issue by davidye** [pixijs/pixijs#9953]
### Current Behavior

```
const container = new Container();
container.mask = undefined;
```

Gives this typescript error: Type 'undefined' is not assignable to type 'number | Container<View>'.

### Expected Behavior

Should not error

### Steps to Reproduce

Run typescript

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by Zyie** [comment]
this seems to be related to the other issue with the transform not being updated: https://github.com/pixijs/pixijs/issues/9951

it seems that anything applied to the top level container isn't processed, only its children
