### ISSUE TITLE
Bug: 8.0.0-rc prevent use of new TextureSource() directly?

### ISSUE THREAD

**Issue by davidye** [pixijs/pixijs#9958]
### Current Behavior

I was trying to create a Texture from a canvas element and tried:

```
const textureSource = new PIXI.TextureSource({ resource: canvasTextureSource });
const texture = new PIXI.Texture(textureSource);
```

This didn't give any warnings or errors but the texture wasn't rendering. Had to read the source to figure it that it should be:

```
const textureSource = new PIXI.CanvasSource({ resource: canvasTextureSource });
const texture = new PIXI.Texture(textureSource);
```

This isn't really a bug and I'm not sure if TextureSource is used directly elsewhere but could it be an abstract class or throw a warning when used incorrectly?

### Expected Behavior

Some error or warning?

### Steps to Reproduce

N/a

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by GoodBoyDigital** [comment]
thanks for sharing, let me have a think on this one 👍

**Comment by Zyie** [comment]
Hey @davidye

We have `autoDetectSource` which would allow you to get the correct source

e.g

```js
const source = {
  resource: canvasTextureSource
};

const texture = new Texture({ source: autoDetectSource(source) });
```
