### ISSUE TITLE
Bug: 8.0.0-rc No way to draw native lines anymore?

### ISSUE THREAD

**Issue by davidye** [pixijs/pixijs#9959]
### Current Behavior

Maybe this option is only supported by the WebGL renderer but there does not appear to be a way to draw native lines anymore?

### Expected Behavior

Mark as breaking change or add it as an option specifically for WebGL renderer?

### Steps to Reproduce

N/a

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by Zyie** [comment]
this has now been shipped in `8.6.0` as `pixelLine`
