### ISSUE TITLE
Bug: extract.canvas api error(v8.0.0-rc)

### ISSUE THREAD

**Issue by yungzhu** [pixijs/pixijs#9974]
### Current Behavior

Place a shape to position 100*100,
when use 'app.renderer.extract.canvas' api

1. The shape position sudden has changed
2. The exported canvas content is incorrect
3. In addition,canvas screenshots do not contain filter effects(if has)

before
![image](https://github.com/pixijs/pixijs/assets/2418199/30722177-1bb3-4556-a90f-7811dc230712)
after
![image](https://github.com/pixijs/pixijs/assets/2418199/0060ed33-dbbc-461c-bb2a-ca80d8436d6b)

code:

const app = new Application();
await app.init({
  width: 800,
  height: 800,
  backgroundColor: 0xff0000,
  preference: "webgl",
  autoDensity: true,
  resolution: window.devicePixelRatio,
});
document.body.appendChild(app.canvas);

const g = new Graphics();
g.rect(0, 0, 100, 100);
g.fill({ color: 0xffff00 });
g.position.set(100);
app.stage.addChild(g);

setTimeout(() => {
  const canvas = app.renderer.extract.canvas(g) as HTMLCanvasElement;
  document.body.appendChild(canvas);
}, 1000);

### Expected Behavior

The exported canvas content is correct

### Steps to Reproduce

The exported canvas content is correct

### Environment

- **`pixi.js` version**: *e.g. v8*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by GoodBoyDigital** [comment]
thanks for sharing @yungzhu !! PR to fix this is up #10061

**Comment by Zyie** [comment]
This should be fixed in the latest rc.2
